### ISSUE TITLE
When displaying user input in an error message, put quotes around it

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/templating#100]
Ex. dotnet new3 asdfg

Would return an error like this
```
some text asdf some text
```

It should return text like this
```
some text "asdf" some text
```

**Comment by seancpeters** [comment]
As we move forward, this will be an ongoing concern. We'll just need to be diligent to quote the appropriates parameters in localizable strings as we create & modify them.

**Comment by mlorbetske** [comment]
Fixed by #116
