### ISSUE TITLE
framework option missing?

### ISSUE THREAD

**Issue by richlander** [dotnet/templating#1015]
I was wanting to give good guidance to https://github.com/dotnet/dotnet-docker-samples/issues/57. I wasn't able to do that given the lack of a "--framework" option for `dotnet new console`. Am I missing something?

/cc @mlorbetske

**Comment by mlorbetske** [comment]
Let's discuss as part of #965 where you brought this up originally

**Comment by richlander** [comment]
Funny. I forgot about that completely. Thanks for remembering.
