### ISSUE TITLE
Creating new web project defaults to https

### ISSUE THREAD

**Issue by prafullbhosale** [dotnet/templating#1023]
From @kimbell on https://github.com/aspnet/scaffolding/issues/540

-------------------------------------------------------------

Not 100% sure this is the right repo for this issue.

For the 1.x version of ASP.NET Core, I've created a number of web projects and all have defaulted to use http for Kestrel in the launch settings.

At the NDC Oslo workshop I created my first web project on the 2.0 base running VS2017 preview. Then I noticed Kestrel was set up to use https. I remember mentioning it to David Fowler or Jon Galloway.  

Today I created a new project running latest preview 2 and updated VS2017. Kestrel has again been configured to https, whilst IIS Express is using http. 

This is my launchSettings.json; I have not made any changes

```
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:62116/",
      "sslPort": 0
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "api/values",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "HostTests": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "api/values",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "https://localhost:44395/"
    }
  }
}
```

**Comment by prafullbhosale** [comment]
From @kimbell


I created another web api project now, and that didn't contain https, so it only happens some times. Also noticed that in the newly created file, the port numbers between IIS Express and Kestrel are much closer 

http://localhost:62725/
http://localhost:62726/

In the problem file there is a big difference in the selected ports.

**Comment by prafullbhosale** [comment]
From @prafullbhosale

This looks like either a template related, or the VS tooling itself. 
cc @BillHiebert, @mlorbetske any thoughts where this should get moved to?

**Comment by prafullbhosale** [comment]
From @mlorbetske 

This would go to dotnet/templating since it's a template content problem

**Comment by mlorbetske** [comment]
@prafullbhosale the closeness in the port numbers comes from not having port generation ranges when running from the CLI, for VS they'll be much further apart - the HTTPS port will be of the form 443xx

**Comment by kimbell** [comment]
All the projects have been generated using Visual Studio 2017 Preview.

**Comment by mlorbetske** [comment]
Sorry about that, somehow I missed that that was part of your message from the original issue and thought it was something we noticed when looking in to it.
