### ISSUE TITLE
Documenting the "secret" options for 2.0?

### ISSUE THREAD

**Issue by GuardRex** [dotnet/templating#1033]
Should we document the hidden arguments for 2.0? We have the `-all|--show-all` option covered now, but it seems like we should either cover all of them or cover none of them.

https://github.com/dotnet/templating/blob/rel/vs2017/3-Preview3/src/Microsoft.TemplateEngine.Cli/CommandParsing/CommandParserSupport.cs#L133-L152

**Comment by sayedihashimi** [comment]
Those two commandline options are just for backwards compatibility, we will be removing them in the future. So we should not  document them.
