### ISSUE TITLE
Choice type parameter handling

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/templating#104]
When an invalid choice is specified, show a message to that effect (and invoke the parameter error handler on the host) but don't stop execution in the parameter processor so that if the help switch has been specified, help is still shown.

If the template would be created & has a bad argument specified, creation should be prevented. This could be accomplished by validating parameters just before help or creation instead of during the parse.

Also, if the user explicitly specifies the default value for the parameter, it should be shown as the current value in help

**Comment by seancpeters** [comment]
Fixed by #112
