### ISSUE TITLE
dotnet new --install failed with too many open files

### ISSUE THREAD

**Issue by shampeter** [dotnet/templating#1069]
I have been trying to run dotnet new --install to install new templates, but doesn't matter which template I tried, it will fail with 'Too many open files'.  My machine is macOS 10.12.5.  My dotnet --version shows 1.0.4.  I suspect it is related to nuget restore is attempting to restore multiple project in parallel, and the limit of file open in macOS.  Output from the command will look like this

Getting ready...
  Restoring packages for /Users/petersham/.templateengine/dotnetcli/v1.0.4/scratch/restore.csproj...
  Failed to download package 'System.Numerics.Vectors.4.1.1' from 'https://api.nuget.org/v3-flatcontainer/system.numerics.vectors/4.1.1/system.numerics.vectors.4.1.1.nupkg'.
  Too many open files

**Comment by shampeter** [comment]
Sorry.  Scratch that.  Stupid me.  Solved the issue by ulimit -n to increase the open file limit.  Work like a charm now.

**Comment by seancpeters** [comment]
Not a problem. If you ran into this issue, others most likely will too - and now we know how to get around it :)
