### ISSUE TITLE
Use source link

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/templating#1081]
More info here https://github.com/ctaggart/SourceLink/blob/v2/README.md

**Comment by sayedihashimi** [comment]
I'd like to learn more about this. Let's chat when you get in later today.

**Comment by sayedihashimi** [comment]
Just remembered you are out of office today. I'll ask @seancpeters if he has more info on this when I see him.

**Comment by mlorbetske** [comment]
I saw this from a comment @davidfowl made on twitter. Just an engineering goodness item, not a feature proposal. This should improve the debugging experience when hosting the engine or when debugging bits from an old release.

**Comment by sayedihashimi** [comment]
Yeah it looks interesting.

**Comment by mlorbetske** [comment]
Closing this as a duplicate of #1574
