### ISSUE TITLE
Global conditional syntax

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/templating#1083]
Today if you want to do a replacement you need to know the syntax to include conditionals based on the file type.

For example in C# I will use `#if` and `#endif` or `//` but in a css file I'll use `//` or `/*` and `*/`.
For file types which are not in our default list of supported files users will need to add non-basic configuration into the `template.json` file.

It would be nice if there was a global replacement syntax that can be used across different files.

The challenge here is to introduce a syntax that works in all files but still enables every file to be as "runnable" as possible.

### Proposal

I'm proposing that we add a new syntax that will work across all files. The basic syntax is captured below.

```
[??]templatecond (IndividualAuth == "true")[??]
[??]endtemplatecond[??]
```

Here `[??]` represents 0 or more unknown characters. When processing the entire start/end line will not be omitted in the template result. Also `tempaltecond` should be matched ignoring case (in case some files need to be all upper/lower case).

For example in a C# file this can be:

```
// templatecond (IndividualAuth == "true")
    <content here>
// endtemplatecond
```

In a .html file we can use

```
<!-- templatecond (IndividualAuth == "true") -->
    <content here>
<!-- -->
```

Also if I don't care for the project to be runnable I can simply insert the following into any file.

```
templatecond (IndividualAuth == "true")
    <content here>
endtemplatecond
```

Another note: we should also think about `////` to see if that makes sense for this as well.

Thoughts?

cc @mlorbetske @seancpeters

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by donJoseLuis** [comment]
last updated about 2.5 years ago.
