### ISSUE TITLE
Cleanup unneeded usings for TempDataAttribute

### ISSUE THREAD

**Issue by danroth27** [dotnet/templating#1091]
Once https://github.com/aspnet/Mvc/issues/6542 makes it's way into the templates we should cleanup the usings for the TempDataAttribute.

**Comment by mlorbetske** [comment]
@danroth27 I'm not seeing any usages of TempDataAttribute, where should I be looking?

**Comment by danroth27** [comment]
The namespace of TempDataAttribute changed from Microsoft.AspNetCore.Mvc.ViewFeatures to Microsoft.AspNetCore.Mvc. We just need to cleanup the unused usings.

**Comment by mlorbetske** [comment]
/facepalm I searched the templates for "TempDataAttribute" rather than "TempData"
