### ISSUE TITLE
File name or folder name with spaces in template outputs with %20

### ISSUE THREAD

**Issue by neman** [dotnet/templating#1095]
I have a folder in my "Runnable Project" Template with name `Generated Models`

When I create project with `dotnet new mytemplate` I got following output:

![image](https://user-images.githubusercontent.com/350314/28246932-c6e85c34-6a26-11e7-9697-7b5b877a957c.png)

![image](https://user-images.githubusercontent.com/350314/28246939-ddcab5fa-6a26-11e7-857b-ca93f229b45c.png)

My folder is removed and renamed. Also my file got it's name encoded.

 ```
dotnet --info
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```

**Comment by mlorbetske** [comment]
This has been fixed for the 2.0 CLI and will be fixed for an upcoming release of Visual Studio 2017 (though I'm not positive which one we'll be able to get it in to just yet - hopefully update 4). I'm unsure at this point of we'll be able to release the fix for The 1.x CLI. The original report of this was #783.

**Comment by neman** [comment]
Ok, If I got it right, hopefully this fix will go to some 1.x version of CLI, but not for the next release?

**Comment by mlorbetske** [comment]
I think that's a fair way of putting it, yes. If there is another release of the 1.x CLI that we can update the engine bits in, we certainly will.
