### ISSUE TITLE
QR code generation doc link is broken in StarterWeb template

### ISSUE THREAD

**Issue by cesarbs** [dotnet/templating#1114]
https://go.microsoft.com/fwlink/?Linkid=852423 is redirected to https://www.microsoft.com/en-us/.

**Comment by mlorbetske** [comment]
@blowdart @danroth27 is there anything tracking pointing that fwlink at the right docs?

**Comment by danroth27** [comment]
Tracked by https://github.com/dotnet/templating/issues/1121
