### ISSUE TITLE
Windows auth does not work on web app template when running standalone

### ISSUE THREAD

**Issue by cesarbs** [dotnet/templating#1115]
Create a web app from the template and select Windows auth. When running behind IIS Express, you can see your Windows identity in the top-right corner of the page. It is not there, however, when running standalone.

Consider fixing the template or removing the launch setting from `launchSettings.json`.

**Comment by mlorbetske** [comment]
Any ideas on how to update the template to make it work? Can windows auth work when just running through Kestel or does it need to be running behind IIS or IIS Express for the context to be collected & passed through?

**Comment by cesarbs** [comment]
@mlorbetske It wouldn't work on Kestrel because we haven't implemented support for it. Could the template be changed so that `launchSettings.json` only has the option to run via IIS Express?
