### ISSUE TITLE
razor/web/mvc templates add UserSecretsId to the csproj but do not add a reference to SecretManager

### ISSUE THREAD

**Issue by moozzyk** [dotnet/templating#1116]
razor/web/mvc templates add UserSecretsId to the csproj but do not add a reference to SecretManager, e.g:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <UserSecretsId>aspnet-test-61850F14-3EBC-4A0B-A7F0-AA3071FA83D8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0-rtm-26343" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0-rtm-26343" />
  </ItemGroup>

</Project>
```
The UserSecretId is quite useless without a reference to Microsoft.Extensions.SecretManager.Tools

**Comment by mlorbetske** [comment]
Currently, UserSecretsId is always included by the secret manager tool is only included for OrgAuth - which one should change? Only include UserSecretsId for OrgAuth or always include the secret manager tool?

cc @danroth27

**Comment by danroth27** [comment]
I think we need it for IndividualLocalAuth, so you can easily enable social logins. 

Do you know why do we include it for org auth?

**Comment by mlorbetske** [comment]
It has something to do with the ability to store the secret for being able to read directory data - should we turn it on for all auth configurations then?

**Comment by mlorbetske** [comment]
Sorry, it is on for individual or org

**Comment by danroth27** [comment]
> It has something to do with the ability to store the secret for being able to read directory data

Makes sense

> Sorry, it is on for individual or org

Looks like the Razor Pages template only has org: https://github.com/dotnet/templating/blob/rel/vs2017/3-Preview3/template_feed/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/RazorPagesWeb-CSharp/Company.WebApplication1.csproj#L35. We should update all the templates to include the user secrets tool for individual auth and org auth
