### ISSUE TITLE
--use-local-db description is misleading/unclear

### ISSUE THREAD

**Issue by moozzyk** [dotnet/templating#1117]
```
-uld|--use-local-db             Whether or not to use LocalDB instead of SQLite
                                bool - Optional
                                Default: false
```

I thought it was just a general setting but apparently it only [applies when used along with IndividualAuth](https://github.com/dotnet/templating/blob/dd5981d39576995adef512463be4b4bef9a896f2/template_feed/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/RazorPagesWeb-CSharp/appsettings.json#L25). It would be good if the switch description reflected that.

**Comment by mlorbetske** [comment]
@sayedihashimi thoughts on what the specific text should be? Should we just append "(only applies when --auth Individual or --auth IndividualB2C has been specified)" to the end of the current help text?
