### ISSUE TITLE
AzureAdB2C WebApp using Extensions as folder name, while WebApi uses AzureAdB2C

### ISSUE THREAD

**Issue by jkotalik** [dotnet/templating#1118]
Small bug, but when calling file new on a new application that has AzureAdB2C (WebApp and WebApi), there are folder name differences between where each are stored. 

![image](https://user-images.githubusercontent.com/8302101/28396866-f459a09a-6cb2-11e7-9fa0-3b411ef7cd8d.png)

![image](https://user-images.githubusercontent.com/8302101/28396882-05a85a6c-6cb3-11e7-89b4-ed3e50614e59.png)

**Comment by mlorbetske** [comment]
@danroth27 @javiercn thoughts?

**Comment by danroth27** [comment]
We should update the web API templates to be consistent with the web app templates. Get rid of the AzureAd* specific folders and put stuff in an Extensions folder
