### ISSUE TITLE
Update QR code doc fwlink

### ISSUE THREAD

**Issue by danroth27** [dotnet/templating#1121]
We need to update https://go.microsoft.com/fwlink/?Linkid=852423 to point to the QR code doc https://github.com/aspnet/Docs/issues/3780

**Comment by DamianEdwards** [comment]
The doc is now live but the FW link hasn't been updated. Needs to point to https://docs.microsoft.com/en-au/aspnet/core/security/authentication/identity-enable-qrcodes

@danroth27

**Comment by mlorbetske** [comment]
This issue was moved to aspnet/templating#28
