### ISSUE TITLE
`--audience` switch has no effect on generated project

### ISSUE THREAD

**Issue by moozzyk** [dotnet/templating#1132]
There is no difference in output between:

`dotnet new webapi -au SingleOrg --no-restore --audience AUDIENCE --force`
and
`dotnet new webapi -au SingleOrg --no-restore`

(less than UserSecretsId)

**Comment by mlorbetske** [comment]
@moozzyk I don't follow the "less than UserSecretsId" part - could you elaborate please?

**Comment by mlorbetske** [comment]
cc @danroth27 I seem to remember talking about what the role of audience was supposed to be in the 2.0 web API template - it looks like we're not using it anywhere, should we just remove the parameter?

**Comment by mlorbetske** [comment]
@phenning any concerns if we did remove the parameter?

**Comment by danroth27** [comment]
@vibronet Should the org auth web API template have an audience URI parameter? I think we are currently using the client ID for the audience URI, which I think you said was fine.

**Comment by moozzyk** [comment]
@mlorbetske - _(less than UserSecretsId)_ I just tried to say that the only difference between the projects generated with and without `--audience` is different UserSecretId which is not relevant.
