### ISSUE TITLE
Consider adding the default layout to the default razor page item template

### ISSUE THREAD

**Issue by javiercn** [dotnet/templating#1142]
Not sure if this is the right repo for it.

I find myself writing that line for every new razor page. The item template should just include it. If a user has a different layout page they would have to add it anyway, so this just makes the default experience better.
```
@{
    Layout = "_Layout";
}
```

@DamianEdwards

**Comment by DamianEdwards** [comment]
Typically you'd put that in a _ViewStart.cshtml, not in the page itself.

**Comment by mlorbetske** [comment]
This seems to be in _ViewStart.cshtml already - are we seeing this not be picked up?

**Comment by javiercn** [comment]
Nope, this is probably because I started with the MVC template and added pages after that.
