### ISSUE TITLE
Web API logging configuration incorrect

### ISSUE THREAD

**Issue by mjrousos** [dotnet/templating#1152]
When creating MVC or WebApi projects from templates, logging is configured in [appsettings.json](https://github.com/dotnet/templating/blob/master/template_feed/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/WebApi-CSharp/appsettings.json) like this:

```json
{
  "Logging": {
    "IncludeScopes": false,
    "Debug": {
      "LogLevel": {
        "Default": "Warning"
      }
    },
    "Console": {
      "LogLevel": {
        "Default": "Warning"
      }
    }
  }
}
```

That configuration is overridden in [appsettings.Development.json](https://github.com/dotnet/templating/blob/master/template_feed/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/WebApi-CSharp/appsettings.Development.json) to be more verbose like this:

```json
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  }
}
```

The problem with this template is that the default settings are provider-specific (Debug/Console) and the Development ones are not, so the Development settings don't actually have the desired effect of making logging more verbose. This is different from the Razor pages template which uses provider-specific configuration in both json files (so it works as expected).
*edit*: It looks like the Razor Pages templates [were recently updated](https://github.com/dotnet/templating/commit/92c3a6bda19e41aff65e20bff444a0a4e1be7119) to use general settings instead of provider-specific ones. The point remains, though, that logging works as expected because they match.

**Expected Behavior**
Launching a new MVC or WebAPI template project in a Development environment should log information to the console as indicated in `appsettings.Development.json`.

**Actual Behavior**
Those projects continue to only log warnings and errors regardless of environment.

dotnet.exe version: 2.0.0-preview2-006497

**Comment by mlorbetske** [comment]
I know this one was first, but duplicating this to #1208 as it covers more of the things that need to be updated
