### ISSUE TITLE
Item Template - Project Awareness

### ISSUE THREAD

**Issue by dansiegel** [dotnet/templating#1154]
For my templates I have ViewModels with a Title property. The project template also has the option to use localization with a Resx file for strings... 

I have a couple of issues that it would be awesome if we could simplify.

- The Item Templates are not aware of the base namespace in the project they are created in, thus requiring an extra attribute. It would be great if dotnet new could pick this up as a replacement token. Particularly since I'm creating the items from the project level where the csproj is.
- It would be fantastic if my template could determine if the Resx file exists in the project so that it can set the Title property either with a string or from the Resx file. If the Resx file exists it would also be fantastic if there was a way for me to add a specified key and value

What I would like to do is something like:

```json
{
  "symbols": {
    "UsesLocalization": {
      "type": "computed",
      "value": "Exists(Strings/Resources.resx)"
    }
  },
  "postActions": [
    {
      // pick up project namespace and do replacement
    },
    {
      // add key/value to resx
    }
  ]
}
```

```cs
#if (UsesLocalization)
using Company.MobileApp.Strings;
#endif

// Where Company.MobileApp would be replaced by the root namespace from the project
namespace Company.MobileApp.ViewModels
{
    public class ItemTemplateViewModel : ViewModelBase
    {
        public ItemTemplateViewModel()
        {
#if (UsesLocalization)
            Title = Resources.ItemTemplateTitle;
#else
            Title = "ItemTemplate";
#endif
        }
    }
}
```

**Comment by dansiegel** [comment]
@mlorbetske @seancpeters any thoughts on this?

**Comment by mlorbetske** [comment]
For the namespace bits, this would fall in the #338 bit (discussions on that one have resumed starting yesterday - so that may be a thing soon).

For determining whether there's a relevant resx, any thoughts on how you'd express that in template.json? So far I'm thinking maybe a symbol that takes some configuration about what to look for that either takes on the value of the path for the located file or an empty string if it's not found - how does that sound?

**Comment by dansiegel** [comment]
I'm certainly open to whatever you come up with. As I had above I was thinking maybe something like:

```json
"symbols": {
    "UsesLocalization": {
      "type": "computed",
      "value": "Exists(Strings/Resources.resx)"
    }
  }
```

**Comment by donJoseLuis** [comment]
This issue was last touched some years ago.  We are working on a new delivery road map.  Please reopen if this is something we want & we'll properly assess its' priority compared to other work aimed at improving the overall templating UX.
