### ISSUE TITLE
Sharing Common Files Between Templates

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/templating#1179]
_From @RehanSaeed on July 23, 2017 15:31_

I have a ReadMe.html file which I'd like to share between my project templates. The file is mostly the same for all three templates, except that it contains a few symbols common to all my templates. I'd like to keep one copy of this file and use symbols to define template specific sections.
```
<html>
<p>Common paragraph...</p>
<!--#if MyTemplate1-->
<p>MyTemplate1 paragraph...</p>
<!--#endif-->
<!--#if MyTemplate2-->
<p>MyTemplate2 paragraph...</p>
<!--#endif-->
</html>
```

I can think of a way this might work without any help from the templating engine: Keep a common copy of the file, then copy the file into the template folders as a pre-packaging step in my build script. The disadvantage is that now I have three copies of my file unless I use a .gitignores file but then I have the extra step of having to remove the .gitignores file from the template output.

I propose that you should be able to add a file as a link, then mark that file as common in your template.json file. Finally, when generating the project, the file is converted from a linked file, into a real one.

_Copied from original issue: aspnet/Templates#856_

**Comment by dansiegel** [comment]
This is an excellent idea... and would be hugely beneficial for my templates as well!

**Comment by mlorbetske** [comment]
I've just tried this out locally & was able to get it working as follows:

### Layout
```
root\
    template1\
        .template.config\
            template.json
        Company.ClassLibrary1.csproj
    template2\
        .template.config\
            template.json
        Company.ClassLibrary1.csproj
    shared\
        Program.cs
```

### root\template1\.template.config\template.json
```
{
  "$schema": "http://json.schemastore.org/template",
  "author": "Microsoft",
  "classifications": ["Test"],
  "name": "Test",
  "generatorVersions": "[1.0.0.0-*)",
  "description": "Test",
  "groupIdentity": "Example.1",
  "precedence": "3000",
  "identity": "TestStuff.1",
  "shortName": "test1",
  "tags": {
    "language": "C#",
    "type": "project"
  },
  "sourceName": "Company.ClassLibrary1",
  "preferNameDirectory": true,
  "sources": [
    { },
    { "source": "../shared", "target": "./" }
  ],
  "symbols": {
  	"isThing1": {
      "type": "generated",
      "generator": "constant",
      "parameters": { "value": "true" }
    }
  }
}
```

### root\template1\Company.ClassLibrary1.csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup Condition="'$(isThing1)' != 'true'">
    <Compile Include="..\shared\Test.cs" Link="Test.cs" />
  </ItemGroup>

</Project>
```

### root\template2\.template.config\template.json
```
{
  "$schema": "http://json.schemastore.org/template",
  "author": "Microsoft",
  "classifications": ["Test"],
  "name": "Test",
  "generatorVersions": "[1.0.0.0-*)",
  "description": "Test",
  "groupIdentity": "Example.2",
  "precedence": "3000",
  "identity": "TestStuff.2",
  "shortName": "test2",
  "tags": {
    "language": "C#",
    "type": "project"
  },
  "sourceName": "Company.ClassLibrary1",
  "preferNameDirectory": true,
  "sources": [
    { },
    { "source": "../shared", "target": "./" }
  ],
  "symbols": {
    "isThing2": {
      "type": "generated",
      "generator": "constant",
      "parameters": { "value": "true" }
    }
  }
}
```

### root\template2\Company.ClassLibrary1.csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup Condition="'$(isThing2)' != 'true'">
    <Compile Include="..\shared\Test.cs" Link="Test.cs" />
  </ItemGroup>

</Project>
```

### root\shared\Program.cs
```
using System;

namespace Company.ClassLibrary1
{
    class Program
    {
        static void Main(string[] args)
        {
#if (isThing1)
            Console.WriteLine("thing1");
#elif (isThing2)
            Console.WriteLine("thing2");
#else
            Console.WriteLine("something else");
#endif
        }
    }
}
```

When running `dotnet new3 test2`, the writeline for `thing2` is used, `dotnet new3 test1` results in `thing1` being used. No special build or packaging steps were required and the explicit `Compile` directive is removed during template instantiation because of the condition.

Please feel free to re-open if this doesn't solve the issue.
