### ISSUE TITLE
Templates should use app.UseMvcWithDefaultRoute();

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/templating#1180]
_From @Rick-Anderson on July 28, 2017 2:6_

I recommend the templates use `app.UseMvcWithDefaultRoute();` rather than

```csharp
app.UseMvc(routes =>
{
    routes.MapRoute(
        name: "default",
        template: "{controller}/{action=Index}/{id?}");
});
```

The more complex code is a barrier to entry for new users who don't need this flexibility. Advanced users will have no problem adding the above code when they need it. The code above doesn't make much sense to Razor Pages developers. Recommend this change for all templates but especially for the Razor Pages template.

cc @DamianEdwards  - part of the lower the barrier to entry effort.

_Copied from original issue: aspnet/Templates#857_

**Comment by Rick-Anderson** [comment]
The Razor Pages template should use `app.UseMvc();`

Why add controller routing to a RP project.  @rynowak  - do you agree?

**Comment by mlorbetske** [comment]
This issue was moved to aspnet/templating#31
