### ISSUE TITLE
.git folder isn't getting excluded

### ISSUE THREAD

**Issue by chelseafarley** [dotnet/templating#1182]
I try to exclude the .git folder in my template.json but it gets pulled through anyway

**Comment by seancpeters** [comment]
Hi @chelseafarley - to help troubleshoot this issue, please post the output of `dotnet --version`, and also the `sources` section of your template.json file. Also, it would be helpful to know the path to your .git folder, relative to your template root.

**Comment by chelseafarley** [comment]
Version: 1.0.4
Sources:   "source": {  "exclude": ["**/[Bb]in/**", "**/[Oo]bj/**", ".git/**"] } but have also tried a couple of variations including "source": {  "exclude": ["**/[Bb]in/**", "**/[Oo]bj/**", ".git"] }
![image](https://user-images.githubusercontent.com/2008152/28942196-98c602c6-78ee-11e7-90ab-348c27ba912a.png)

**Comment by seancpeters** [comment]
@chelseafarley it appears that this sources isn't formatted correctly. Try this:
```
  "sources": [
    {
      "exclude": [ 
        "**/[Bb]in/**",
        "**/[Oo]bj/**",
        ".git/**",
      ]
    }
  ]
```
Note that the above is the entire sources specification - the "sources" I've included is a top-level key in the json.

**Comment by chelseafarley** [comment]
Perfect that worked! Sorry for the issue

**Comment by seancpeters** [comment]
No worries, the configs can get complicated.
