### ISSUE TITLE
Remove Microsoft.VisualStudio.Web.CodeGeneration.Tools from default MVC template

### ISSUE THREAD

**Issue by JosephWoodward** [dotnet/templating#1183]
In a similar vein to a [previous issue raised](https://github.com/dotnet/templating/issues/658), given .NET Core is targeted towards cross-platform development in a range of IDEs and editors, I feel it doesn't make sense to have Visual Studio specific packages (`Microsoft.VisualStudio.Web.CodeGeneration.Tools` in this case) referenced in the default template created when calling `dotnet new mvc` in the .NET Core 2 preview (2.0.0-preview2-006497)

<img width="794" alt="screen shot 2017-08-03 at 23 00 34" src="https://user-images.githubusercontent.com/1237341/28945744-9c3be01e-789f-11e7-99be-0f830dfe55cd.png">

A better, IDE agnostic alternative could be to add a reference to the package once Visual Studio has created the project?

**Comment by mlorbetske** [comment]
This package is unfortunately named, it's not actually specific to Visual Studio - it supports scaffolding additional content (like Entity Framework based views and controllers) into projects using the dotnet CLI.

@prafullbhosale

**Comment by seancpeters** [comment]
This issue was moved to aspnet/templating#30
