### ISSUE TITLE
[RFC] would you please add a default gitignore file when new a project

### ISSUE THREAD

**Issue by livarcocc** [dotnet/templating#1189]
_From @netroby on August 4, 2017 3:4_

by run dotnet new we can create a new project.
would you please add a default .gitignore file to the new created project?

```bash
#cat .gitignore 
bin/
obj/
.vscode/

```

_Copied from original issue: dotnet/cli#7368_

**Comment by mlorbetske** [comment]
This is a duplicate of #823
