### ISSUE TITLE
Avoid throwing 'ApplicationException' - it is not recommended by MSDN

### ISSUE THREAD

**Issue by Eilon** [dotnet/templating#1191]
The `ApplicationException` has been essentially obsolete since .NET 1.0, and MSDN specifically recommends avoiding it:

https://msdn.microsoft.com/en-us/library/system.applicationexception(v=vs.110).aspx

> You should derive custom exceptions from the Exception class rather than the ApplicationException class. You should not throw an ApplicationException exception in your code, and you should not catch an ApplicationException exception unless you intend to re-throw the original exception.

We should fix this ASAP in the project templates, as it is not a good practice.

**Comment by seancpeters** [comment]
This issue was moved to aspnet/templating#29
