### ISSUE TITLE
Logging configuration in WebApi and Spa template shouldn't include providers.

### ISSUE THREAD

**Issue by pakrym** [dotnet/templating#1208]
Expected:
```
 "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Warning"
    }
}
```
https://github.com/dotnet/templating/blob/rel/2.1.0-preview1/template_feed/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/StarterWeb-CSharp/appsettings.json

Actual:
```
"Logging": {
    "IncludeScopes": false,
    "Debug": {
      "LogLevel": {
        "Default": "Warning"
      }
    },
    "Console": {
      "LogLevel": {
        "Default": "Warning"
      }
    }
}
```
https://github.com/dotnet/templating/blob/rel/2.1.0-preview1/template_feed/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/WebApi-CSharp/appsettings.json

**Comment by seancpeters** [comment]
This issue was moved to aspnet/templating#27
