### ISSUE TITLE
Question: Should we do a community meeting?

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/templating#1210]
I was chatting with @mlorbetske and we were wondering if the community would like to have a call with us to discuss templating? We are all on board for such a meeting. If we get a good turn out we can also consider doing it on a regular basis.

Some questions for the community:

 - Are you interested in such a call?
 - If so, what type of content would you hope that we cover?
 - Any preferences to platform used? Google hangouts, Skype, etc.
 - What time zone are you in? 

cc @shanselman @seancpeters @phenning @davidfowl 

I'll close this issue in a few days, or when comments die down if we get any replies here.

**Comment by ankitvijay** [comment]
Yes,
to start with more on templates 
May be Google hangouts since it works well for ASP.NET community

**Comment by jaredcnance** [comment]
1. Yes
2. Project direction and upcoming/planned features. It might also be a good place to demo some of the not-so-obvious features. Maybe also present some recent challenges that you've encountered while using the current released versions and workarounds or strategies for solving those challenges.
3. Hangouts is good

**Comment by sayedihashimi** [comment]
@ankitvijay @jaredcnance 
What time zone are you guys in?

**Comment by ankitvijay** [comment]
Australia Eastern Time Zone

**Comment by RehanSaeed** [comment]
I've been following this repo, I'm confused about which features actually made it into the 2.0 tooling and what is work in progress and what is planned in the future (It would be nice if you used GitHub milestones BTW), would be nice to see a roundup. I'm in the BST timezone.

**Comment by chad-ramos** [comment]
- Yes!
- Central Time (CT)
- Would love to hear about what is in the pipeline, what is coming down the road, and a transparent look at current state of affairs.

**Comment by dansiegel** [comment]
I would echo the comments from @RehanSaeed. As for a platform I would say if the goal is a daily chat where the community can reach out both to each other and to the core team, then chances are most of us already have slack installed and adding a new slack team would be easy enough. It could also be a more general slack team with channels for the cli, templating, etc. If the goal is just a one time call then Skype seems like a pretty logical choice to me. I'm in the PST

**Comment by EdCharbeneau** [comment]
- Yes!
- Cover automation, template variables & best practices
- Skype
- ET

**Comment by hrboyceiii** [comment]
- Yes
- Automation, best practices
- Sykpe or otherwise
- US Eastern time

**Comment by sayedihashimi** [comment]
Thanks for the feedback, it looks like there is enough interest.
There were some questions on the frequency. Let's discuss that on call. I was thinking monthly or every other week. 

I noticed a couple suggestions to cover automation. Can someone expand on that? Are you looking to automate calling dotnet new and need more info?

FYI I'm out of the office until Wednesday. When I'm back I'll write up an agenda, and try to find a good time. If this becomes a recurring thing, I think we may rotate between two or three different times so we can cover timezone issues.

**Comment by EdCharbeneau** [comment]
RE: Automation

I'd like to see some ideas or practices around maintaining a project. How can I structure the project (folders, etc.) So that I can easily test, create the nupkg and run the template tool. Currently I have some batch jobs helping with this, but I feel like there has to be a better way. Even if it's just seeing how others have set up their projects and processes.

**Comment by sayedihashimi** [comment]
@EdCharbeneau thanks for the info. I think SideWaffleV2 has some of this info. SW2 helps with creating both the .vsix and NuGet package. We can discuss more on the call in this area as well. In the SW2 model, we use the VSIX project to drive creation of all output needed to share templates. You can also add additional templatepack*.proj files to output more than one NuGet package. I'm also going to extend it so that you can list NuGet packages by name/version which should be included in the .vsix.

**Comment by mlorbetske** [comment]
Closing this issue since it's not actionable. We do hope to start doing some form of community meeting soon & will open a new issue with details as soon as we get a bit more figured out.
