### ISSUE TITLE
Error Creating a Template Pack Project for .NET Core 2.0 Project in VS 2017 Update 3

### ISSUE THREAD

**Issue by aagarwal10** [dotnet/templating#1215]
@sayedihashimi -

When I try to create the template pack project it fails, here is the message.

There is a missing project subtype.
SubType: '(Guid) is unsupported by this installation.

I have VS 2017 Update 3 with .NET Core 2.0 installed.

Please help.

**Comment by aagarwal10** [comment]
@sayedihashimi  - I was following this video as walkthru 

https://www.youtube.com/watch?v=g6az_N95dVM

**Comment by mlorbetske** [comment]
This should either be a comment on #1209 or an issue on https://github.com/ligershark/side-waffle - @sayedihashimi which would you prefer?.

At a guess though, it's likely though that the project subtype GUID in the project file got added to the `guids` section of the generated template.json, causing Visual Studio to get confused about what kind of a project it is.

**Comment by aagarwal10** [comment]
I am creating .NET Core 2.0 Class Library project. I just need to install VS Extensiblity Tools from marketplace. Thanks @sayedihashimi  for pointing it out.
