### ISSUE TITLE
Missing license header in some files

### ISSUE THREAD

**Issue by omajid** [dotnet/templating#1216]
Some files have only this license header, which doesn't explicitly confirm that the file is licensed under the license documented in the https://github.com/dotnet/templating/blob/rel/2.1.0-preview1/LICENSE  file:

    /*!
    ** Unobtrusive validation support library for jQuery and jQuery Validate
    ** Copyright (C) Microsoft Corporation. All rights reserved.
    */

For example, https://github.com/dotnet/templating/blob/rel/2.1.0-preview1/template_feed/Microsoft.DotNet.Web.ProjectTemplates.1.x/content/StarterWeb-CSharp/wwwroot/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js. Can you please somehow clarify this header? The "All Rights Reserved" and no mention of MIT or jquery license makes me feel uncomfortable.

cc @leecow

**Comment by mlorbetske** [comment]
This issue was moved to aspnet/templating#32
