### ISSUE TITLE
[Question] - nuspec, packagetypes element

### ISSUE THREAD

**Issue by dazinator** [dotnet/templating#1218]
I haven't come accross this <packagetypes> element in a nuspec before: https://github.com/dotnet/templating/blob/59ea5050650f0928e557d5fdaa80e894448ec671/template_feed/Microsoft.DotNet.Common.ItemTemplates/Templates.nuspec#L11

Is this part of the official nuget specification - I haven't seen any documentatioin on it anywhere yet!

**Comment by sayedihashimi** [comment]
Yes it's an official NuSpwc thing. I'm not sure if it's documented or not. Try asking on NuGet/home repo.
Closing for now.

**Comment by dazinator** [comment]
Ok thank you for confirming.
