### ISSUE TITLE
dotnet new project templates allow automatically adding to sln

### ISSUE THREAD

**Issue by anurse** [dotnet/templating#1220]
My workflow for creating new projects is the following

1. `mkdir ProjectName`
2. `cd ProjectName`
3. `dotnet new sln`
4. `mkdir src`
5. `cd src`
6. `dotnet new classlib -n ProjectName`
7. `cd ..`
8. `dotnet sln add src\ProjectName\ProjectName.csproj`

Those last two steps (adding to the SLN) are super boilerplatey and are almost always what the user wants to do when a Project template is expanded in a location underneath an SLN. Having the ability to automatically add the project to the SLN during template expansion would be awesome. Extra points for creating solution folders matching the folder structure between the SLN and the project.

I'm OK with this being an opt-in or prompted thing (`Do you want to add this Project to [SLNname].sln ?` or `dotnet new classlib -n ProjectName --sln`)

**Comment by seancpeters** [comment]
At this point, the closest we have to the functionality you're describing is a post-action to add a project to an existing solution file. But that post-action must be part of the configuration for the project template being invoked. The documentation for authoring templates with this post action is here: https://github.com/dotnet/templating/wiki/Post-Action-Registry#add-projects-to-a-solution-file

The post action walks the directory path from the location the project template was created, up to root -  looking for a solution file. The first one it finds is the one that will get the configured project(s) added to it.

We don't currently have any way to cause this to occur if the template is not configured for it.
