### ISSUE TITLE
A possibility to check if it's project folder

### ISSUE THREAD

**Issue by korzh** [dotnet/templating#1221]
For item templates we need a possibility to check if the current folder is a project folder (so, at least it must contain .csproj, .fsproj or .vbproj file) and if not - show an error message and stop from proceeding further.

**Comment by mlorbetske** [comment]
@korzh can you expand on the scenario? We currently don't have anything like that where the template can stop itself from being created based on additional preconditions & I'd like to understand the class of things where this would be useful.

**Comment by korzh** [comment]
The scenario is simple. We would like to create an item template which adds a controller (with a corresponding view) or, for example, some other class to the current project. Of course, it would be better if the template could check if it's run in the project folder and stop its execution (with some error message) if it's not.

**Comment by mlorbetske** [comment]
Thanks for the clarification, but that's not really what I was getting at. If the item shouldn't be able to be created if there isn't a project there, then it seems like it shouldn't be shown unless there's a project there. If it should be shown always and there's some additional validation should be able should stop its creation after processing has started, what does that class of validations look like. These different ways of looking at the ask would end up producing different features.

In the specific case you mentioned, is there any harm if the user wanted to make the content in a directory to see what it looked like first, before deciding to incorporate it into their project?

**Comment by korzh** [comment]
No harm, just a couple of useless files in the wrong directory.  I encountered such situation my self when applied my own template right in Visual Studio via "Package Manager Console". I was thinking I was in a project folder while it was a solution folder actually. After that I spent some time trying to figure out where were the new files which had to be added.
