### ISSUE TITLE
.NET Core Class Templates do not apply code styles

### ISSUE THREAD

**Issue by davkean** [dotnet/templating#1225]
_From @natidea on August 22, 2017 3:40_

From [VSFeedback](https://developercommunity.visualstudio.com/content/problem/97435/new-net-core-application-doesnt-apply-code-styles.html) | [482102](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/482102)

**Repro Steps** 

Go to Tools/Options/TextEditor/C#/CodeStyle/Formatting/NewLines and turn off all checkboxes as to follow K&R brace style (i.e. brace opening goes on the same line).

Create a new .NET Core 2.0 application.

When a new .NET Core 2.0 application is created, the following is default file content:

```cs
    namespace TestCore2
    {
        class Program
        {
            static void Main(string[] args)
            {
                Console.WriteLine("Hello World!");
            }
        }
    }
```

Expected result would be default document properly following code styles:

```cs
    namespace TestCore2 {
        class Program {
            static void Main(string[] args) {
                Console.WriteLine("Hello World!");
            }
        }
    }
```

PS: Full .NET framework application properly follows code style on startup.
PPS: Style will be correctly applied upon pressing Ctrl+K,D. 

_Copied from original issue: dotnet/project-system#2726_

**Comment by davkean** [comment]
@CyrusNajmabadi What's your thoughts around this? Rather than individual templates opting into this - perhaps some generalized mechanism for auto-applying styles?

**Comment by davkean** [comment]
_From @CyrusNajmabadi on August 23, 2017 3:48_

I thought we already formatted newly created template files.  Is that not the case?

**Comment by davkean** [comment]
_From @jmarolf on August 23, 2017 8:46_

This is a bug.  Newly created files should have the formatter run on them by default already.

**Comment by davkean** [comment]
Does this happen for files that aren't item templates but are part of project templates?

**Comment by davkean** [comment]
_From @jmarolf on August 23, 2017 9:38_

Yes, set K+R braces 
![image](https://user-images.githubusercontent.com/9797472/29609408-f97a7d92-87ab-11e7-8963-ff531b432905.png)

And then create 
- net core app: not formatted
- net framework app: formatted

**Comment by davkean** [comment]
Ah, this will be the new template engine.

**Comment by davkean** [comment]
@jmarolf Any idea how this actually works under the covers?

**Comment by davkean** [comment]
_From @jmarolf on August 23, 2017 23:38_

@davkean I assume the old project system would do something to let the language service know to format the document.  I'm curious if this repos with the old templates (not based on the web framework).  If not then I believe that this bug should go to the new template engine.  I

**Comment by RehanSaeed** [comment]
I'd much rather support was added using a `.editorconfig` file so that it was cross platform and not Visual Studio specific.

**Comment by jmarolf** [comment]
@RehanSaeed `.editorconfig` support for these options already exists.  This is a bug in the templating engine implementation that is specific to Visual Studio

**Comment by seancpeters** [comment]
@phenning - any thoughts on this? This seems to not be a concern of the templating engine itself, but rather causing VS to apply the user's formatting settings to the newly created files.

**Comment by dansiegel** [comment]
I might add that it would be great if VS4Mac were to support user styling.

**Comment by davkean** [comment]
@seancpeters Templates created using the old templating engine automatically apply styles, so the templating engine must be doing something here.

**Comment by seancpeters** [comment]
@davkean - I believe the misunderstanding here is semantic, and related to the boundary between the new template "engine" and Visual Studio "host" integration of it. The template engine itself outputs files to disk, and is not concerned with how they will be consumed. The Visual Studio host integration (or VS4Mac, or other host) of the template engine would be responsible for any additional actions which are specific to that host, such as VS user defined code formatting. So, while VS-specific formatting of files generated by the template engine is indeed an action that should occur during the VS-specific template creation process, it's not a concern of the template engine itself.

The old template engine was VS only, and so the architectural boundaries are different than they are with the new engine.

**Comment by davkean** [comment]
@seancpeters I assumed this repro contained the VS wizard "entry point", no?

**Comment by seancpeters** [comment]
@davkean - I believe this is what you're looking for: https://github.com/dotnet/templating/blob/rel/2.1.0-preview1/src/Microsoft.TemplateEngine.VisualStudioWizard/TemplateEngineWizard.cs

**Comment by phenning** [comment]
@davkean The wizard which VS uses is not OSS, it is part of internal tooling also owned by this team.

**Comment by phenning** [comment]
@davkean I own the wizard code which invokes the core template engine, I'll take a look into seeing what we can do to bring this into parity with the traditional vs template experience.

**Comment by davkean** [comment]
Thanks Phil.

**Comment by davkean** [comment]
@seancpeters What's the bug for this?

**Comment by seancpeters** [comment]
@davkean - answered via email, the bug is being tracked internally for Visual Studio.
