### ISSUE TITLE
Razor Pages Docker Linux -- Did you mean to run dotnet SDK commands? Please install dotnet SDK from

### ISSUE THREAD

**Issue by espray** [dotnet/templating#1236]
Razor Pages with Linux Docker support enabled. Getting error 'Did you mean to run dotnet SDK commands?'. Template with Windows container works fine.

Linux Docker -- Folder 
C:\Users\erics\Documents\Visual Studio 2017\Projects\RazorPages\RazorPages\obj\Debug\netcoreapp2.0
is EMPTY.

Windows Docker --  The same folder has the build output.

 
Visual Studio Professional 2017
Version 15.3.2

Repro Steps
1. Create a new project '.NET Core - ASP.Net Core Web Application'
2. Select 'Web Application' project template. 'Enable Docker Support': true and 'OS': 'Linux'
3. After the project is created 'Start Without Debugging'

=== docker-compose.yml ===
version: '3'

services:
  razorpages:
    image: razorpages
    build:
      context: ./RazorPages
      dockerfile: Dockerfile

=== Dockerfile ===
FROM microsoft/aspnetcore:2.0
ARG source
WORKDIR /app
EXPOSE 80
COPY ${source:-obj/Docker/publish} .
ENTRYPOINT ["dotnet", "RazorPages.dll"]

=== Docker output ==

docker-compose -f "C:\Users\erics\Documents\Visual Studio 2017\Projects\RazorPages\docker-compose.yml" -f "C:\Users\erics\Documents\Visual Studio 2017\Projects\RazorPages\docker-compose.override.yml" -f "C:\Users\erics\Documents\Visual Studio 2017\Projects\RazorPages\obj\Docker\docker-compose.vs.debug.g.yml" -p dockercompose5164038261409161484 config
services:
  razorpages:
    build:
      args:
        source: obj/Docker/empty/
      context: C:\Users\erics\Documents\Visual Studio 2017\Projects\RazorPages\RazorPages
      dockerfile: Dockerfile
    entrypoint: tail -f /dev/null
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_USE_POLLING_FILE_WATCHER: '1'
      NUGET_FALLBACK_PACKAGES: /root/.nuget/fallbackpackages
    image: razorpages:dev
    labels:
      com.microsoft.visualstudio.debuggee.arguments: ' --additionalProbingPath /root/.nuget/packages
        --additionalProbingPath /root/.nuget/fallbackpackages  bin/Debug/netcoreapp2.0/RazorPages.dll'
      com.microsoft.visualstudio.debuggee.killprogram: /bin/bash -c "if PID=$(pidof
        -x dotnet); then kill $PID; fi"
      com.microsoft.visualstudio.debuggee.program: dotnet
      com.microsoft.visualstudio.debuggee.workingdirectory: /app
    ports:
    - 80/tcp
    volumes:
    - C:\Users\erics\Documents\Visual Studio 2017\Projects\RazorPages\RazorPages:/app:rw
    - C:\Users\erics\vsdbg:/remote_debugger:ro
    - C:\Program Files\dotnet\sdk\NuGetFallbackFolder:/root/.nuget/fallbackpackages:ro
    - C:\Users\erics\.nuget\packages:/root/.nuget/packages:ro
version: '3.0'
docker  ps --filter "status=running" --filter "name=dockercompose5164038261409161484_razorpages_" --format {{.ID}} -n 1
3ca299d693ae
docker  exec -i 3ca299d693ae dotnet  --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  bin/Debug/netcoreapp2.0/RazorPages.dll
docker  inspect --format="{{json .NetworkSettings.Ports}}" 3ca299d693ae
{"80/tcp":[{"HostIp":"0.0.0.0","HostPort":"32779"}]}
Waiting for response from http://localhost:32779/ ...
Did you mean to run dotnet SDK commands? Please install dotnet SDK from: 
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

**Comment by mlorbetske** [comment]
This issue was moved to aspnet/Templating#614
