### ISSUE TITLE
ability to open a file in web browser after project creation.

### ISSUE THREAD

**Issue by joeaudette** [dotnet/templating#1242]
In my template I am building a readme.html that has different information depending on which features are included based on template parameters.

I would like to be able to open that file in a web browser after project creation. I see [in the wiki](https://github.com/dotnet/templating/wiki/Post-Action-Registry) a setting for that but marked as TBD
Wondering if there is any information on when that might get implemented?

Also wondering if there is a cross platform way I could do it with the existing Run Script post action?

I have already managed to do this in my vsix but I would like it better if I could do it from the template instead so it could work from the command line if not using the vsix.  

Note that to get it working my my vsix I had to implement 2 IWizards, it could not be done in my main [ProjectWizard](https://github.com/joeaudette/cloudscribe.templates/blob/master/Content/cloudscribeTemplate/ProjectWizard.cs) because at the time when RunFinished is executed in the wizard the readme file does not really exist yet because the project has not been created yet, since the main TemplateEngineWizard that actually creates the project runs after ProjectWizard. So I had to make a second [ShowReadMeWizrd](https://github.com/joeaudette/cloudscribe.templates/blob/master/Content/cloudscribeTemplate/ShowReadMeWizard.cs) which is plugged in after the TemplateEngineWizard in my .vstemplate file.

It is really working nicely in my vsix but still I would prefer a way to do it directly in the template so it can work no matter whether using the vsix or not.

If the open file in web browser post action is coming soon I can wait for it, but if there is any advice on how I could implement using the existing Run Script post action that would be great. Specifically I guess I would need to run a .cmd file on windows but run a .sh file otherwise, but I am not aware of a way to detect the platform.

Any advice greatly appreciated!

**Comment by RehanSaeed** [comment]
Did you figure this out? Is the post action usable? When I use:

```
{
      "actionId": "FEA7469E-E2E7-4431-B86B-27EBC1744883",
      "condition": "(!SkipOpenReadMe)",
      "continueOnError": true,
      "description": "Open the Read-Me for the project in a web browser.",
      "manualInstructions": [
        { "text": "Open the ReadMe.html in a web browser." }
      ]
}
```

I get the following output:

> Description: Open the Read-Me for the project in a web browser.
> Manual instructions: Open the ReadMe.html in a web browser.

**Comment by joeaudette** [comment]
hi @rehansaeed I didn’t get it working, are you saying it works now and I should try again?

**Comment by RehanSaeed** [comment]
It doesn't work, it just prints out a message to the console.

**Comment by mlorbetske** [comment]
From the wiki page for the post action, the ID has been reserved for the purpose of opening a file in the browser, but there aren't any clients that implement it listed (dotnet new doesn't implement it at this time).

**Comment by donJoseLuis** [comment]
This issue was last touched some years ago.  We are working on a new delivery road map.  Please reopen if this is something we want & we'll properly assess its' priority compared to other work aimed at improving the overall templating UX.
