### ISSUE TITLE
Question on unnecessary usings in the templates

### ISSUE THREAD

**Issue by guardrex** [dotnet/templating#1261]
I'm working with an Azure AD/OpenID Connect sample in the Azure Docs tonight. I want to drive the updated sample from the `dotnet new mvc` template. I noticed that the template lays in a number of unnecessary `using` statements in *Program.cs* and other files.

*Program.cs* (I've commented out the unnecessary ones) ...

```csharp
//using System;
//using System.Collections.Generic;
//using System.IO;
//using System.Linq;
//using System.Threading.Tasks;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
//using Microsoft.Extensions.Configuration;
//using Microsoft.Extensions.Logging;

namespace WebApp_OpenIDConnect_DotNet
{
    public class Program
    {
        public static void Main(string[] args)
        {
            BuildWebHost(args).Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();
    }
}
```
Given the construction of the template engine, is it necessary to include the namespaces that aren't required?

**Comment by seancpeters** [comment]
@danroth27 @SteveSandersonMS - any thoughts on this?

**Comment by danroth27** [comment]
Some of the namespaces are just the common namespaces that get included in pretty much any C# file in web project (System, System.Collections.Generic. System.Linq, System.Threading.Tasks).

Some of the other namespaces (Microsoft.Extensions.Configuration, Microsoft.Extensions.Logging) are namespaces that aren't used by the generated code, but are likely to be used when modifying the code (ex adding config and logging providers).

System.IO was needed in 1.1 to get the current directory, but is no longer required for 2.0 and can be removed.
