### ISSUE TITLE
The templates favicon

### ISSUE THREAD

**Issue by guardrex** [dotnet/templating#1262]
I don't see a favicon here, so this might be the wrong place to ask. The `dotnet new` templates favicon isn't attractive ...

![favicon1](https://user-images.githubusercontent.com/1622880/31107913-7c7aba48-a7bb-11e7-9f0c-45961a01cb7c.png)

Any interest in using the *really nice looking* MS logo favicon? (or *anything else* :smile:)

![favicon2](https://user-images.githubusercontent.com/1622880/31107919-8d047f02-a7bb-11e7-9384-212a0b090dff.png)

**Comment by PureKrome** [comment]
this
should
be
the
favicon

(yes, reduce size, pixelate, etc)

![](http://images.danielwmoore.com/wp/MS-ninjacat-unicorn-office-xbox-windows-bing.png)

**Comment by guardrex** [comment]
They both :guitar: *ROCK* :guitar:!

I know it's a small thing, but I think MS should make a statement here. Hit them with a favicon that everyone can be proud of.

**Comment by ctolkien** [comment]
Here is my vote:

![image](https://user-images.githubusercontent.com/515955/31111520-52814e60-a85a-11e7-9e35-58923f7e6365.png)

#neverforgot

In all seriousness. I don't think a favicon should be shipped in the templates. They should be things you _build_ on, not things you need to remove and/or entirely replace.

**Comment by guardrex** [comment]
The thing about the *favicon.ico* is that browsers will (often) just check the base URL (domain) for it. It kind'a makes them "happy" :smile: if it's just there. If we'll provide it, then let's see something nice there.

**Comment by mlorbetske** [comment]
This issue was moved to aspnet/templating#206
