### ISSUE TITLE
The template focus on VS leads to a poor non-VS dev experience

### ISSUE THREAD

**Issue by guardrex** [dotnet/templating#1263]
1. Bower config files are present in the `dotnet new mvc` template, but without ...
   ```xml
   <Target Name="PreBuildScript" BeforeTargets="PrepareForBuild">
     <Exec Command="bower install" />
   </Target>
   ```
   ... the dev is hurt'in when developing in a non-VS environment (e.g. VS Code).
2. The template includes *bundleconfig.json*, but without ...

   ```xml
   <DotNetCliToolReference Include="BundlerMinifier.Core" Version="2.5.357" />
   ```
   ... and ...
   ```xml
   <Target Name="PrePublishScript" BeforeTargets="PrepareForPublish">
     <Exec Command="dotnet bundle" />
   </Target>
   ```
   ... again, the dev has a bad experience in a non-VS environment. The link `https://go.microsoft.com/fwlink/?LinkId=808241` is there, but that's overkill to merely find out what they need to make it :sparkles: *Just Work*:tm: :sparkles:.

**Comment by seancpeters** [comment]
@danroth27 - could you please take a look at this?

**Comment by danroth27** [comment]
@madskristensen is probably the right person to weigh in on these.

**Comment by madskristensen** [comment]
This issue is being addressed as we speak

Bower is being removed from the templates and we're working on a replacement for both Bower and bundleconfig.json. More information on that later.

**Comment by guardrex** [comment]
I just wanted to pop back for sec in case a dev lands here looking at lighting-up these features outside of VS.

The `BuildBundlerMinifier` package removes the need for the `dotnet bundle` target. Therefore, a good project file to use outside of VS will have ...
```xml
<ItemGroup>
  <!-- Other Packages -->
  <PackageReference Include="BuildBundlerMinifier" Version="2.5.357" />
</ItemGroup>

<ItemGroup>
  <!-- Other Tool References -->
  <DotNetCliToolReference Include="BundlerMinifier.Core" Version="2.5.357" />
</ItemGroup>

<Target Name="PreBuildScript" BeforeTargets="PrepareForBuild">
  <Exec Command="bower install" />
</Target>
```
Of course, NPM is required.
