### ISSUE TITLE
donet new -i only searching myget when nightly F# Visual Tools myget path is added to nuget package manager in VS 2017

### ISSUE THREAD

**Issue by a688** [dotnet/templating#1264]
In reference to https://github.com/fable-compiler/Fable/issues/1176

**Problem:**
"dotnet new -i <whatever>" only searches dotnet.myget.org if https://dotnet.myget.org/feed/fsharp/package/vsix/ is specified a NuGet package source in VS 2017

**How to reproduce:**
Open VS 2017
Go to Tools -> NuGet Package Manager -> Package Manager Settings
Go to "Package Sources"
Add a new package source using "https://dotnet.myget.org/feed/fsharp/package/vsix/" as the source and "F# nightly" as the name (I don't think the name matters though)
Save changes

Open a command prompt and enter "dotnet new -i Fable.Template"

You will see 404 errors in the output

Even if you go back into the NuGet Package Manager's settings and uncheck the source, you will still get the 404 errors when you run "dotnet new -i Fable.Template".

**Workaround:**
REMOVE, not just uncheck, the package source that points to "https://dotnet.myget.org/feed/fsharp/package/vsix/"

Now "dotnet new -i Fable.Template" will run successfully

**Comment by mlorbetske** [comment]
Sorry for the long delay here. dotnet new -i generates a csproj in a temp directory and calls dotnet restore on it to bring down any packages that have been requested for install, scanning the restored packages for templates. 404s in the output from restore that shouldn’t be there should be routed to NuGet/home, ideally with a minimal repro project/set of instructions. Given that this should impact any project (not just the temporary project generated by new during install), closing this.
