### ISSUE TITLE
Replacements in file name with sourceName and fileRename parameter

### ISSUE THREAD

**Issue by sibille** [dotnet/templating#1270]
I'm trying to include a file in a template that should be renamed with the sourceName and a fileRename parameter. Each of them is working in isolation, but I cannot rename the file with both sourceName and parameter. Replacements inside the file work fine.

The template.json is the following: 

```
{
  "name": "Blank",
  "sourceName": "BlankView",
  "preferNameDirectory": true,
  "PrimaryOutputs": [
    {
      "path": ".\\Views\\BlankViewPage.xaml"
    },
    {
      "path": ".\\Views\\BlankViewPage.xaml.cs"
    },
    {
      "path": ".\\ViewModels\\BlankViewPrefixViewModel.cs"
    }
  ],
  "symbols": {
       "viewmodelprefix": {
      "type": "parameter",
      "replaces": "Prefix",
      "fileRename": "Prefix"
    }
  }
}
```
Is this possible? Am I missing something?

**Comment by seancpeters** [comment]
Hi @sibille, we only recently added support for allowing multiple renames to be applied to a filename. That functionality is not available in the 2.0.0 version of dotnet new, but it is available in the 2.1.0-preview1 branch of this repo.

If you want to test your template against the 2.1.0-preview1 branch, pull down that branch and then run 'setup' in the repo root. You'll then be able to run `dotnet new3` to run the new branch, and running `dotnet new` will continue to run the bits shipped with dotnet. Note that `new` and `new3` maintain separate configurations from each other, including installed templates.

**Comment by sibille** [comment]
That's great news!! Thanks @seancpeters!! 
Could you tell me with which Visual Studio version the 2.1.0-preview1 branch is planned to be shipped?

**Comment by seancpeters** [comment]
We haven't get finalized when 2.1.0-preview1 will be shipped with Visual Studio, but I know it will be 15.6 or later.

**Comment by sibille** [comment]
I just tried the parameter fileRename option with 2.1.0-preview1 and it works great!! 
Another quick question: Will parameters used in PrimaryOutput paths also be replaced? 
For example with this template.json definition

```
"name": "Test",
"sourceName": "ClassName",
"PrimaryOutputs":
  [
    { "path": "Param_ProjectName.Test\\ClassNameTests.cs" },
    { "path": "Param_ProjectName\\ClassName.cs" }
  ],
 "symbols":
  {
    "projectName":
    {
      "type": "parameter",
      "replaces": "Param_ProjectName",
      "fileRename": "Param_ProjectName"
    }
}
```

**Comment by seancpeters** [comment]
Yes, your primary output paths will be modified in the same way. So they'll match the file / directoriy names which are actually created when the template is created.
