### ISSUE TITLE
dotnet test template for f# shouldnt add `Program.fs` for `net` tfm

### ISSUE THREAD

**Issue by enricosada** [dotnet/templating#1271]
The test templates (xunit, mstest) of F# always include a `Program.fs`, and is needed atm ( ref https://github.com/dotnet/netcorecli-fsc/issues/79 ) for `netcoreapp2.0`

But that's annoying swithcing to `net462` because there the project is a library (by design), and the entrypoint is not needed.

Changes required: add the `Program.fs` under a `Condition` of the tfm or runtime (or better another test sdk property, if exists). like

```xml
<Compile Include="Program.fs" Condition=" '$(DontRemeberTheProp)' == '.NETCore' " />
```

/cc @dsyme @cartermp @KevinRansom

**Comment by dsyme** [comment]
+1, thanks

**Comment by mlorbetske** [comment]
Looks like this should be fixed with https://github.com/dotnet/test-templates/pull/22
