### ISSUE TITLE
Making dotnet new more like Angular CLI schematics?

### ISSUE THREAD

**Issue by rendmath** [dotnet/templating#1295]
Are there any plans to bring the dotnet templating engine beyond the current declarative, replace-based approach?

I've recently worked with Angular CLI schematics, and it seems like dotnet/templating might want to follow the same path:

- Declarative approach for the parameters only
- Imperative approach for the actual template processing (C#?)
- Templating language (Razor? T4?)
- Access to the generated code AST (Roslyn?)

At the moment, I'm actually considering using Angular CLI for the dotnet part as well, because of the flexibility it provides. But it would be great to have a "native" .NET solution.

If you're worrying about the possibility of users executing third-party code... it can't be worse than NPM, can it? That might not be much of an argument, but I think you can see my point.

**Comment by mlorbetske** [comment]
The answer here isn't no, but it isn't directly yes either. The engine itself is less about processing templates and more about being able to exchange metadata between a content generator and a front end for taking user input. The runnable project generator that is included in `dotnet new` by default is one such generator, but the design allows for multiple generators to be present. Additional generators are planned for the future (with Razor based syntax), but there is not a concrete schedule for that work at this time.

A generator of the form you describe is certainly possible, but there are no plans to move the runnable project generator in that direction - it has a fairly robust templating language, quite a few existing templates and concrete plans to fill in most of the major gaps that have been reported (dynamic data, looping, etc).

If you've got specific thoughts on how you'd like to see an additional generator work (and would like to create one), I'd suggest taking a look at https://github.com/dotnet/templating/blob/rel/2.1.0-preview2/src/Microsoft.TemplateEngine.Abstractions/IGenerator.cs (implementation for the runnable project generator is here for reference https://github.com/dotnet/templating/blob/rel/2.1.0-preview2/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/RunnableProjectGenerator.cs) to get started.

If there are specific features missing from the runnable project generator that are preventing you from using it, please let us know.
