### ISSUE TITLE
improve dotnet new --uninstall

### ISSUE THREAD

**Issue by jannikb-sim** [dotnet/templating#1296]
Currently dotnet new --uninstall requires knowledge about how the template was installed. For example if you install from a path you also need to uninstall providing that path. 
It would be much easier if we could uninstall by providing the **shortname**

- Its much simpler
- does not require knowledge about how the template was installed
- does not require the original config (might be moved or deleted)
- harmonizes with other commands (i.e. dotnet new <simplename>

ref #961

**Comment by michaelongithub** [comment]
I also consider this really much needed, because it increases the risk of having orphaned templates.

**Comment by mlorbetske** [comment]
There are really two kinds of issues here:
1) There isn't good definition on what it means to uninstall
2) There is not way to figure out what things are installed

For the first one, we currently define "uninstall" as the opposite of install - the removal of all the things that were added by installing a package or disk location from the registry of installed templates/components. It seems like what's being asked for here is something different - hiding individual templates from display or removing them entirely (more on this below).

For the second one, we're trying some things out that should improve the situation some. We're currently experimenting with having `dotnet new -u` output the list of things that can be uninstalled (what's contained in those packages will come soon) - part of this is out for PR as #1298.

As far as hiding/removing individual templates goes - templates are commonly composite entities. For example, there are actually six different "templates" that go in to showing the console application template right now (C#/VB/F# for 1.0+1.1/2.0), removing "console" in this case is ambiguous but could be done (removing all registrations for all things with a short name of "console"). Going beyond that, these templates are part of a pack (console is bundled with class library for instance, all web project templates are bundled together, test templates go as a bundle, etc.). If that package is updated to a newer version (using `-i` to bring in a new version or leveraging the upcoming work to make update/template search more natural), these templates would be re-registered as part of the new installation.

In addition to the uninstall mechanics as described above, what would you think of having a switch that could be supplied to hide/filter all templates matching a particular set of arguments (unless a special flag is passed to show all templates)? Something like `dotnet new console -lang C# --prefs:hide+` (very likely to not be the actual syntax) that would add an entry that would keep, in the case of the example, the C# console app template for all frameworks from showing. Or `dotnet new console --framework netcoreapp2.0` would hide the .NET Core 2.0 flavor of the console app template (all languages) from showing. These filters would still apply even if the package carrying the template was updated.

**Comment by michaelongithub** [comment]
My point was only, that one has to know the real physical location the template had at installation time. This seems to be the only permissible parameter that leads to the uninstallation with dotnet new -u (it works even if this folder is empty, for uninstall !).  This information is not part of the CLI after installation. It is kind of "meta" information that is not part of the system. I would expect to be able to uninstall a template with some information / identification that is part of the info in the CLI template list.
