### ISSUE TITLE
Update or remove sample from help

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/templating#130]
From `dotnet new3 mvc --help` I see

```bash
Examples:
    dotnet new3 mvc --auth None --use-local-db false
    dotnet new3 mstest
    dotnet new3 --help
```

Is the `--use-local-db false` a relevant flag in the mvc template? I tried setting to `true` and then to `false` and the same content was produced.

**Comment by mlorbetske** [comment]
The decided on workaround for now is to:
- Omit value specification from flags
- Omit flags whose default value is false

When interactive CLI mode lands, we'll use the decision tree file to determine whether particular properties make sense in context with each other by following a prompting path to an end.

**Comment by seancpeters** [comment]
To clarify the use of the --use-local-db flag, it affects things when auth is set to Individual. With auth = none, the --use-local-db flag has no effect.

**Comment by seancpeters** [comment]
Note: the command listed at the start of this issue will not show examples since it's specifically asking for help on the mvc template. But if you just run "dotnet new3", it'll list examples.
