### ISSUE TITLE
Can not expand templates from a regular zip archive

### ISSUE THREAD

**Issue by xtmq** [dotnet/templating#1301]
It seems template engine does not work with regular zip archives with directory entries.
As far a I understand the problem is in ZipFileMountPoint.cs [lines 72-100]. This code supposes that we have only files in an archive, like this one:
![1](https://user-images.githubusercontent.com/1643827/32025656-75755892-b9e1-11e7-8890-ee5aec1db9d7.png)

But when I create a regular zip archive (via 7zip on windows or via ant on linux), my archive looks like this:
![2](https://user-images.githubusercontent.com/1643827/32025790-c30d6e0a-b9e1-11e7-8007-35e4d300305f.png)

So I have lots of xxx/yyy/ entries. These entries have fullpaths with '/' in the end AND empty names. So the code tries convert them into files (ZipFileFile) and then into directories (ZipFileDirectory). 
In the end I have lots of directories with EMPTY names. 

In the end if I try to expand such template, I'll get an error "access to the path 'c:\template.json' is denied". Because FileSystemInfoExtensions.PathRelativeTo performs lots of operations under directories with empty names...

**Comment by mlorbetske** [comment]
@seancpeters could you take a look please?

**Comment by seancpeters** [comment]
@xtmq - I just merged PR #1315 which should fix your issue. Please let me know if you have additional problems with this.

**Comment by xtmq** [comment]
We have updated template engine to the latest master and there is no issue anymore, thanks!
