### ISSUE TITLE
Constant generator interprets strings as numbers

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/templating#1302]
The constant generator in the 2.0.x templating engine does not respect data type for constant parameters. This causes issues when parameter values are strings, but might be interpretted as a number depending on current culture.

### Repro
Create a template package using the constant generator in the template.json file
```js
{
    // ...
  "symbols": {
    // ...
    "MicrosoftAspNetCoreAllPackageVersion": {
      "type": "generated",
      "description": "The package version for Microsoft.AspNetCore.All",
      "generator": "constant",
      "parameters": {
        "value": "2.0.3"
      },
      "replaces": "$(MicrosoftAspNetCoreAllPackageVersion)"
    }
  }
}
```
Add a file that uses this replacement. 
```xml
<PackageReference Include="Microsoft.AspNetCore.All" Version="$(MicrosoftAspNetCoreAllPackageVersion)" />
```

Install the template
Set locale to de_DE
`dotnet new`

### Result

"2.0.3" is interpreted as a number. The result varies because periods are thousands-separators in de_DE, but not in en_US.

```xml
<PackageReference Include="Microsoft.AspNetCore.All" Version="203" />
```

see also https://github.com/aspnet/templating/tree/4a897d69bcfab85b1eb9cc186117230cbcb17f2f/src/Microsoft.DotNet.Web.ProjectTemplates.2.0

**Comment by mlorbetske** [comment]
Fixed by #1303

**Comment by natemcmaster** [comment]
Can we leave this re-open and consider porting this to 2.0.x as well?

**Comment by mlorbetske** [comment]
If there is another insertion to the 2.0.x CLI for the engine, it'll come from this branch. However, the engine in CLI is only used in CLI, VS (this impacts partners like Windows Template Studio and Canaria), VS for Mac, etc would all need to be updated as well. Moving this change into the 2.0.x CLI alone doesn't actually help, as you wouldn't be able to count on the fix having propagate to all consumers.
