### ISSUE TITLE
dotnet new -i failes with 401 (unauthorized) when using private feed

### ISSUE THREAD

**Issue by livarcocc** [dotnet/templating#1306]
_From @tomstreet on October 27, 2017 15:51_

## Steps to reproduce
I have some private feeds setup in my AppData\Roaming\NuGet\NuGet.config.
These work fine with `dotnet restore` no problem (there are no local nuget.config files, just the global one).
I have published a template for dotnet new to one of the private feeds.
I then run `dotnet new -i the_template_package`

## Expected  behavior
I expect the template to install

## Actual behavior
It fails with a 401 unauthorized

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

_Copied from original issue: dotnet/cli#7923_

**Comment by DeluxZ** [comment]
We are running into this problem as well.

**Comment by tomstreet** [comment]
This was caused by an old Nuget.Config lying around in my c:\users folder. `dotnet restore` on other projects didn't pick this up so it got forgotten about. The lack of verbose logging for `dotnet new` also made this difficult to find.

In the end I stopped `dotnet new -i` half way though (so it didn't clean up scratch\restore.csproj) then ran `dotnet restore -v d` on the restore.csproj to find out where it was getting the packages sources from.

**Comment by JuanZamudioGBM** [comment]
I having this problem using a private feed in VSTS, 

C:\Program Files\dotnet\sdk\2.1.4\NuGet.targets(103,5): error : Unable to load the service index for source https://[Site].pkgs.visualstudio.com/_packaging/[Feed]/nuget/v3/index.json

Is there a way to avoid this?

**Comment by DeluxZ** [comment]
Any update on this? Still having this issue when I try to install for example the DotNetBoxed templates with dotnet new --install "Boxed.Templates::*" and a private feed set up in my NuGet.config which I need for other projects.

And yes, I know I can edit my nuget.config without my private feeds (VSTS feeds) but we want to create a template which will use the nuget packages from our private feed. This will cause the problem to be back.

**Comment by maracuja-juice** [comment]
I ran into this problem aswell yesterday. I solved it by generating a PAT and adding it to my NuGet.config:
```
  <packageSourceCredentials>
    <YourFeedKey>
      <add key="Username" value="yourUsernameOrEmail" />
      <add key="ClearTextPassword" value="yourPAT" />
    </YourFeedKey>
  </packageSourceCredentials>
```

**Comment by mlorbetske** [comment]
Let's continue the conversation over [here](https://github.com/dotnet/templating/issues/1545) as the original poster seems to have resolved the issue they were running in to & the remaining discussion seems to be around private feeds and personal access tokens
