### ISSUE TITLE
NUnit Test Templates

### ISSUE THREAD

**Issue by rprouse** [dotnet/templating#1307]
Should NUnit templates be included out of the box or would you prefer that the NUnit team maintain them? Either way I am happy to do the work. We've had quite a few users ask us for templates and many people are confused thinking that NUnit doesn't support .NET Core because the other major test frameworks are included out of the box but not NUnit.

**Comment by dburriss** [comment]
@rprouse what about these? I have not used them but I saw this issue and remembered seeing them in the list a while back.
https://github.com/halex2005/dotnet-new-nunit
Aforementioned list: https://github.com/dotnet/templating/wiki/Available-templates-for-dotnet-new

**Comment by rprouse** [comment]
I am actually working with @halex2005 now to pull those templates into the NUnit organization. They are well done and a great start, I just feel that it is a bit unfair that MSTest and xUnit ship with .NET Core whereas NUnit does not. It sets a higher bar for NUnit users and sends a message as to which frameworks are blessed or approved by the team.

**Comment by dburriss** [comment]
Well to be fair, they don't need to be fair. Things are this way for a reason I guess. Pressure from users and eating their own dog food.  That being said, with enough pressure and contributions I see no reason NUnit couldn't  get in on the shipped list. It still gets more downloads than xUnit. Good luck with the endeavor and thanks for the effort.

**Comment by mlorbetske** [comment]
Closing this as it sounds like this is being worked on in a different forum
