### ISSUE TITLE
dotnet restore postAction skips action when used with a .sln primary output

### ISSUE THREAD

**Issue by johlrich** [dotnet/templating#1310]
If you try and setup a template that has a postAction of dotnet restore on a primaryOutput of a sln file, it will skip the step with the message:

```
Processing post-creation actions...
No Primary Outputs to restore.
```

Looks like the check happens here to make sure the file ends in proj https://github.com/dotnet/templating/blob/c2e27ddce00cf9dec3a9e52f0ee56c2dc75aa2b0/src/Microsoft.TemplateEngine.Cli/PostActionProcessors/DotnetRestorePostActionProcessor.cs#L31

Workaround was to explicitly list the proj files, but not sure if this restriction makes sense since dotnet restore does seem to work on a sln file to restore all projects.

**Comment by seancpeters** [comment]
@johlrich - I just merged fix #1314 that will cause .sln files listed in the primary outputs to be used by the restore post-action.
