### ISSUE TITLE
dotnetnew.azurewebsites.net error

### ISSUE THREAD

**Issue by elanderson** [dotnet/templating#1312]
http://dotnetnew.azurewebsites.net/ returns an error.

Error.
An error occurred while processing your request.
Request ID: 0HL8SJP1GCKIU:00000006

Development Mode
Swapping to Development environment will display more detailed information about the error that occurred.

Development environment should not be enabled in deployed applications, as it can result in sensitive information from exceptions being displayed to end users. For local debugging, development environment can be enabled by setting the ASPNETCORE_ENVIRONMENT environment variable to Development, and restarting the application.

**Comment by sayedihashimi** [comment]
I’m not sure what’s happening there, I’ll take a look this morning.

**Comment by sayedihashimi** [comment]
OK we are back up. Not sure what the problem was. I just published again, restarted the api website and it's working now.
