### ISSUE TITLE
[BUG] Passthrough of TargetFrameworkVersion removes '.' from version number

### ISSUE THREAD

**Issue by brianlagunas** [dotnet/templating#1336]
When using **non-English** versions of Visual Studio 2017, if you have an IWizard that passes the $targetframeworkversion$ to your template which is used to set a parameter and replace a variable in your csproj file, the '.' will be removed.  This causes an exception when creating project templates using this as the `<TargetFrameworkVersion>` element.

For example; if the $targetframeworkversion$ is `4.5`, the result will be `45` when replaced by the parameter in the template.

In a wizard pass the targetframeworkversion:

`replacementsDictionary.Add("passthrough:TargetFrameworkVersion", replacementsDictionary["$targetframeworkversion$"]);`

Define your variable in your template.config:

```
"TargetFrameworkVersion": {
      "type": "parameter",
      "defaultValue": "4.5.2",
      "replaces": "$targetframeworkversion$"
    }
```

Then use in your template:

`<TargetFrameworkVersion>v$targetframeworkversion$</TargetFrameworkVersion>`

Exception occurs:

![image](https://user-images.githubusercontent.com/835562/32701551-31a691f0-c795-11e7-9ea5-69e9201213e4.png)

Here is one workaround: https://digitalsupport.ge.com/communities/en_US/Article/Error-Microsoft-Build-Utilities-ToolLocationHelper-GetPathToStandardLibraries

That's not going to work though as you can't expect you users to do that.

The other workaround is to create the full version string (prefix the 'v' to the version number) before passing it in.

`replacementsDictionary.Add("passthrough:TargetFrameworkVersion", $"v{replacementsDictionary["$targetframeworkversion$"]}");`

**Comment by brianlagunas** [comment]
Seems like this may be related to #1322

**Comment by seancpeters** [comment]
@brianlagunas - you're correct, this is pretty much the same thing as #1322.

**Comment by mlorbetske** [comment]
Closing this to track as part of #1322
