### ISSUE TITLE
"How to create your own templates" should be in project readme (on top somewhere visible)

### ISSUE THREAD

**Issue by ghost** [dotnet/templating#1338]
Project wiki (https://github.com/dotnet/templating/wiki) tells us:
How to create templates --points to--> https://aka.ms/dotnetnew-create-templates

but i really had to google and hit this page: https://github.com/dotnet/templating/issues/new, which points me back to wiki, even though i already went through project's README.

Please add it with bold letters as this is one of the most interesting aspect for visitors of this repo.

**Comment by scottaddie** [comment]
@kasper3 I've updated the Wiki link to point to the official doc: https://docs.microsoft.com/dotnet/core/tools/custom-templates. If you're satisfied with that, please close this issue.

**Comment by grinrag** [comment]
The link to the official docs was added.
