### ISSUE TITLE
The icon of .Net Core/Standard F# project templates not displayed correctly.

### ISSUE THREAD

**Issue by Xiu-Li** [dotnet/templating#1339]
• File-->New Project-->Visual F#-->.NET Core/.NET Standard
• The icon of .Net Core/Standard F# project templates display the icon of C#.
![image](https://user-images.githubusercontent.com/24784908/32770425-9030cf44-c95a-11e7-9e75-9e7a37f70ef6.png)
Test on d15.6stg.27113.3000
dotnet --info
![image](https://user-images.githubusercontent.com/24784908/32770479-d52a71d6-c95a-11e7-8fdf-cdfeb67ccd89.png)

**Comment by Pilchie** [comment]
@KevinRansom @jmarolf can you take a look?  This should be fixed by this build I thought?

**Comment by KevinRansom** [comment]
@Xiu-Li which build of Visual Studio are you using?

**Comment by Pilchie** [comment]
@KevinRansom 

> Test on d15.6stg.27113.3000

**Comment by KevinRansom** [comment]
````
    "Microsoft.VisualStudio.NetCore.ProjectTemplates": {
      "fileName": "Microsoft.VisualStudio.NetCore.ProjectTemplates.vsman",
      "url": "https://vsdrop.corp.microsoft.com/file/v1/Products/DevDiv/dotnet/project-system/master/20171031.1;Microsoft.VisualStudio.NetCore.ProjectTemplates.vsman"
    },

````
Looks like the checked in project system was built on 31 October..  The fix was merged to project-system repo on the 3rd November I think.

https://github.com/dotnet/project-system/pull/2927

Hope this helps

**Comment by Pilchie** [comment]
@Xiu-Li does this bug repro on d15rel builds?  If not, I'm going to assume that the change just hasn't flowed to d15.6stg yet.

**Comment by Xiu-Li** [comment]
This bug repro on 15.6stg.27113.3000, not repro on d15rel.27110.00.

**Comment by seancpeters** [comment]
@phenning - can you take a look at this? I'm not 100% sure if it's in your realm or not

**Comment by Pilchie** [comment]
I expect this is fixed already, but the fix hasn't flowed to d15.6stg yet.  We had a pair of changes in the templates and then to add the resources that happened relatively late.

**Comment by Xiu-Li** [comment]
This issue **not repro** on d15.6stg.27125.3000.

**Comment by Pilchie** [comment]
I'm going to close this then, as I believe it's the bug @KevinRansom already fixed.
