### ISSUE TITLE
[loc][Query][.NETCoreTemplateEngine] Localizability of "0; "AllUpdatesApplyPrompt"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/templating#1341]
**Hi, we have a question from a translator. Could you help please?**

**Source:**
Apply updates ([A]ll|[N]one|[P]rompt)?

**File Name:**
localize\ploc\Microsoft.TemplateEngine.Cli.resources.dll

**Resource ID:**
0; "AllUpdatesApplyPrompt"

**Query:**
Please confirm that letters between [ and ] are localizable?

**Comment by seancpeters** [comment]
@PDostalek - This is the same situation as #1342, what we decide for that issue will also be applicable here.
