### ISSUE TITLE
NuGet Config template can't be used in solution directory (by default)

### ISSUE THREAD

**Issue by anurse** [dotnet/templating#1346]
Steps:

1. `dotnet new sln`
2. `dotnet new nugetconfig`

Expected Behavior: A NuGet.Config file is written

Actual Behavior: The following error

```
        - [Nuget Config] is an item template. By default it's only created in a target location containing a project. Force creation with the -all flag.

Template Instantiation Commands for .NET Core CLI.

Usage: dotnet new [arguments] [options]

Arguments:
  template  The template to instantiate.

Options:
  -l|--list         List templates containing the specified name.
  -lang|--language  Specifies the language of the template to create
  -n|--name         The name for the output being created. If no name is specified, the name of the current directory is used.
  -o|--output       Location to place the generated output.
  -h|--help         Displays help for this command.
  -all|--show-all   Shows all templates


Templates      Short Name      Language      Tags
-------------------------------------------------

Examples:
    dotnet new mvc --auth None --framework netcoreapp1.1
    dotnet new xunit --framework netcoreapp1.1
    dotnet new --help
```

I know I can use `-all` to prevent this, but the NuGet.config template is rarely expanded into a folder containing a `csproj`, it's much more likely to be at a solution or repository root. This template should be configured to be runnable from any location by default.

**Comment by mlorbetske** [comment]
@anurse what version of the CLI is this? The behavior to be opinionated about whether project or item templates should be allowed should have been removed long ago.

**Comment by anurse** [comment]
It's possible that this was a really old version, I realized that later on. Never mind then!

**Comment by anurse** [comment]
Yep, verified on a more recent version. Sorry about that!
