### ISSUE TITLE
Setting up debug environment with readme.md incompleteness

### ISSUE THREAD

**Issue by neman** [dotnet/templating#1350]
I have couple of question regarding setting up build and debug environment, while reading `Readme.md`

1. `When working with the source inside Visual Studio, it is recommended you use the latest available version.` 
Does this mean latest stable or latest preview version?

2. Reference to `Microsoft.VisualStudio.TemplateWizardInterface` is hard coded to Enterprise edition of Visual Studio.
```xml
<ItemGroup>
    <Reference Include="Microsoft.VisualStudio.TemplateWizardInterface">
      <HintPath>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\PublicAssemblies\Microsoft.VisualStudio.TemplateWizardInterface.dll</HintPath>
    </Reference>
  </ItemGroup>
```
This will not work for community edition of VS (or anu othrer non enterprise edition)

![image](https://user-images.githubusercontent.com/350314/32989200-33493422-cd12-11e7-8e34-43a8e21de561.png)

![image](https://user-images.githubusercontent.com/350314/32989508-e27fad5e-cd17-11e7-9a7f-e9371827d77d.png)

Once I change this reference to Community path `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\PublicAssemblies\Microsoft.VisualStudio.TemplateWizardInterface.dll` I am able to build the solution.

3. `Open the Microsoft.Templating.sln solution in the application you will use to attach your debugger.`
I can't find file `Microsoft.Templating.sln`. Is it maybe `Microsoft.TemplateEngine.sln` ?
And what does exactly mean this part **`in the application you will use`**? What application is this text referring to?

**Comment by mlorbetske** [comment]
We should remove this project from the solution, add a second solution for Visual Studio specifics & add documentation to the readme on how to load that one as needed. @seancpeters @phenning

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by vlada-shubina** [comment]
`Microsoft.VisualStudio.TemplateWizardInterface` is no longer part of `Microsoft.TemplateEngine.sln`, so no action was taken on that.
Renamed `Microsoft.Templating.sln` to `Microsoft.TemplateEngine.sln` in `readme.md` file, thank you for spotting it.

`Open the Microsoft.Templating.sln solution in the application you will use to attach your debugger.`
The application here refers to the application to use for debugging. Usually Visual Studio, but not limited to.
