### ISSUE TITLE
[QUESTION] "new3" what is this 3 all about ?

### ISSUE THREAD

**Issue by tebeco** [dotnet/templating#1357]
Hello,

I was looking for "How do i update my installed template" but reading over the readme i tend to see lots of command using
`dotnet new3`, beeing curious i tried and get :
```
>dotnet new3`
No executable found matching command "dotnet-new3"
```

I also saw a paragraph about updates beeing in the roadmap (so not yet avalaible)
does Uninstall / Reinstall is ok as a workaround ?

Did i missed something ?

```
> dotnet --info
.NET Command Line Tools (2.0.3)

Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  12f0c7efcc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17040
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.3\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```

**Comment by seancpeters** [comment]
@tebeco - The cli ships with the `new` command, so if you're only using a dotnet/cli installation, then you'll never need to use `dotnet new3`. But if you download and build the dotnet/templating repo (to get the latest templating bits), those bits are run using `dotnet new3`. This allows you to have both running side-by-side, without interfering with one another. 

In general if documentation says `new3`, you can do the same thing using `new` - except for cases where the feature has not yet shipped with the cli and is only available in the dotnet/templating repo.

**Comment by tebeco** [comment]
@seancpeters, any idea for the update of template today ? uninstall/ reinstall ?

**Comment by seancpeters** [comment]
@tebeco - Install is currently supported for a couple of cases. You can install templates that are on your local file system, and also templates that are on nugget.org. For filesystem installs, the command is:
`dotnet new -i <path to nupkg>`
For example:
`dotnet new -i c:\MyCustomTemplates\MyTemplatePack.nupkg`

For installing from nuget, you can just name the package you want to install, something like:
`dotnet new -i Microsoft.AspNetCore.SpaTemplates`
You can also suffix a specific version of the template pack from nuget:
`dotnet new -i Microsoft.AspNetCore.SpaTemplates::2.0.3`
If you don't specify a version, the newest release version will be installed. 

Also, if you're developing your own templates locally, you can install them without packaging them into a nupkg, by providing a path to the template files on disk. The path needs to be at or above the content root of the template. If you don't provide custom sources in your template.json, then the root is generally one directory above the directory containing the template.json file. 

If you want to update installed templates to a newer version, just install the newer version as explained above - it will overwrite the currently installed version of the templates in the pack being installed. Note that install doesn't do any version comparison, so if you install an older version than you currently have installed, the older version will be installed, overwriting the currently installed version. With this in mind, reinstall is the same as install.

**Comment by tebeco** [comment]
thx
