### ISSUE TITLE
dotnet new --install {SOME-PACKAGE} --source {SOME-REPO}

### ISSUE THREAD

**Issue by otakusid** [dotnet/templating#1362]
It would be good to have an option that specifies NuGet repository used for templates installation.  F.e.: 

`dotnet new --install {SOME-PACKAGE} --source {SOME-REPO}`

This allows using private repositories without adding them globally to `%appdata%\NuGet\NuGet.config` file

**Comment by mlorbetske** [comment]
This shouldn't be too difficult for install itself, we'd need to add a new parameter, passing it in here https://github.com/dotnet/templating/blob/31685c0f8fd05f1ee09da0a456bc97fbf239e31c/src/Microsoft.TemplateEngine.Cli/New3Command.cs#L275

Add a parameter to https://github.com/dotnet/templating/blob/rel/2.1.0-preview1/src/Microsoft.TemplateEngine.Cli/Installer.cs#L32 and https://github.com/dotnet/templating/blob/rel/2.1.0-preview1/src/Microsoft.TemplateEngine.Cli/IInstaller.cs#L10

Ultimately, the source parameter needs to get passed here https://github.com/dotnet/templating/blob/rel/2.1.0-preview1/src/Microsoft.TemplateEngine.Cli/Installer.cs#L205

There may be considerations to make for the update flow. @seancpeters thoughts?

**Comment by seancpeters** [comment]
This solution is similar to some thoughts I've had about a different source repo issue. For updates, the install descriptor cache isn't currently storing the nuget source repo for nuget installed packages, just that the packages came from nuget feeds. The specific feed would matter if we're concerned about same-named packages in different repos - and only want an update for a pack to come from the same repo that the thing being updated came from. But our current install / update story doesn't take that into account, it uses the restore resolution logic. It might even be a bad idea to force updates to come from the same nuget source - for example if a repo moves - then the concept of "same source" becomes muddled.

**Comment by jstallm** [comment]
It would be great if we could specify a private nuget feed, this way enterprise developers can keep versions of templates for internal projects on a private feed.
