### ISSUE TITLE
Parameter generator for relative paths

### ISSUE THREAD

**Issue by xtmq** [dotnet/templating#1366]
Imagine we have a project template like this one:

_/root
  /.template.config  
  /Project1
    /Project1.csproj
  /Libs
    /Project2
      /Project2.csproj_

Project1.csproj and Project2.csproj have some old-style packages. Something like:
_< Reference Include="P">< HintPath>..\packages\P\P.dll< /HintPath>< /Reference>_

We want to point HintPath to the actual package location in the solution file. So in the example above we have to introduce two parameters 'RelativeSolutionPath1' and 'RelativeSolutionPath2' because projects in the templates are located in different levels. 

It would be nice to pass only one parameter SolutionPath and specify two autogenerated parameters for the relative paths in the template. 
I guess it is possible to calculate relative paths to the processed files right during template expansion...

**Comment by seancpeters** [comment]
@xtmq - If I correctly understand your situation, then derived symbols is probably the solution you're looking for. This sounds similar to what you need: https://github.com/dotnet/templating/issues/1066#issuecomment-319827279
You'd define the parameter SolutionPath, which is the user input. Then you'd define the 2 derived symbols RelativeSolutionPath1 and RelativeSolutionPath2, both with `"valueSource": "SolutionPath"`. In those derived symbols, you'd reference the "forms" to convert the SolutionPath to the appropriate values for the relative paths. The "forms" themselves are defined in the "Forms" section of the template.json.

**Comment by seancpeters** [comment]
That referenced thread is a little confusing, the specific issue it's solving is from this post: https://github.com/dotnet/templating/issues/1066#issuecomment-319507911

**Comment by xtmq** [comment]
So you suggest to use regular expressions to transform one path to another?

**Comment by seancpeters** [comment]
Yes - value forms configured in templates are defined by regular expressions. There are a few built-ins you can leverage - as documented here: https://github.com/dotnet/templating/wiki/Runnable-Project-Templates---Value-Forms
but the only one that is probably useful in this case would be the "chain" type, which works like a pipeline - allowing you do define forms such that the result of the first one is input to the next one, and so on.

**Comment by xtmq** [comment]
Thanks, I'll try =)

**Comment by mlorbetske** [comment]
@xtmq how'd it go? Should we keep this issue open or were you able to get things working?

**Comment by mlorbetske** [comment]
Closing this as there hasn’t been a response in quite a while
