### ISSUE TITLE
macOS truncating trailing ".0" on datatype choice

### ISSUE THREAD

**Issue by Plac3hold3r** [dotnet/templating#1382]
I'm working on a Xamarin MvvmCross template. 

In the `template.json` I made use of `symbols` replacing with `datatype choice`. Here is an example of one for .NET Standard version options:

```
 "NETStandardVersion": {
  "type": "parameter",
  "datatype": "choice",
  "defaultValue": "2.0",
  "description": "The version of .NET Standard to use in the Core project.",
  "choices": [
    {
      "choice": "2.0",
      "description": ".NET Standard 2.0"
    },
    {
      "choice": "1.6",
      "description": ".NET Standard 1.6"
    },
    {
      "choice": "1.5",
      "description": ".NET Standard 1.5"
    },
    {
      "choice": "1.4",
      "description": ".NET Standard 1.4"
    }
  ],
  "replaces": "2.0",
  "onlyIf": [
    {
      "after": "netstandard"
    }
  ]
}
```
The issue I'm experiencing is on macOS (Only tested with High Sierra) when specifying the choice of "2.0" or even not choosing any and using the default "2.0". The generate project solutions will contain only "2" and not "2.0". The issue only occurs when creating a solution from the template when running on a Mac. When running on Windows project solutions are generated with "2.0".

There are other places in the `template.json` that also make use of a `datatype choice` for example iOS min SDK version. These also experiences the same issue where selecting "10.0" with only generate "10". So it does seem to be fairly consistent behaviour.

The template is available on [NuGet](https://www.nuget.org/packages/MvxScaffolding.Templates/) currently in beta and can be installed with

```text
dotnet new -i MvxScaffolding.Templates::0.4.2-beta
```

The [GitHub repo](https://github.com/Plac3hold3r/MvxScaffolding) for the project, I have not yet made the template fully public so let me know if you need more details. 

__UPDATE__

I have create a [branch (macOS-trailing-zero)](https://github.com/Plac3hold3r/MvxScaffolding/tree/Issue/macOS-trailing-zero) in the repo that has a simple .NET Standard class library template that can be used to replicate the issue on the Mac. I have also included the [NuGet package](https://github.com/Plac3hold3r/MvxScaffolding/blob/Issue/macOS-trailing-zero/nuspec/Zero.Template.0.1.0.nupkg) to easily test locally.

__UPDATE 2__

Originally tested against .NET SDK 2.0.3 but I have subsequently update to 2.1.3 both version produce the same result, in that the trailing ".0" are getting removed.

**Comment by mlorbetske** [comment]
Could you post your dotnet CLI version please? This sounds very similar to #1302 which should be fixed in recent builds of the CLI.

**Comment by Plac3hold3r** [comment]
@mlorbetske I updated to the latest stable 2.1.3 and I'm still having the same issue.

**Comment by mlorbetske** [comment]
Could you run `dotnet new --debug:version` please and post the result? It looks like the 2.1.3 CLI should have the fix, but we'll know for sure with the output of that command.

**Comment by Plac3hold3r** [comment]
I seems to be having issues running `dotnet new --debug:version` command. The same command works perfectly on my Windows PC, I get back a version and commit hash. I wonder is there is not something wrong with my install of .NET Core SDK? Any ideas? 

![image](https://user-images.githubusercontent.com/13716738/34422666-66970030-ec1f-11e7-90a9-034639884714.png)

**Comment by mlorbetske** [comment]
Digging in to it a bit more, it looks like 2.1.3 carried version 1.0.0-beta2-20171004-309 of the engine (2c4653e) and the first build with the fix (which also carries the debug:version switch) is 1.0.0-beta3-20171109-311 (dbb59b3) - so this should be included in the next CLI release.

**Comment by Plac3hold3r** [comment]
Oh I see, so version 2.1.2 of the SDK did include the `debug:version` switch but was removed in 2.1.3 and will return in a future version. Which was why it worked on my Windows PC which was running 2.1.2. After update my Windows PC .NET Core SDK to 2.1.3, it now throws the same invalid input switch error (PC and Mac are now on the same version 2.1.3).

So in terms of being able to test that the newer preview versions have fixed the issue I'm experiencing on Mac, would I be able to test using `new3` running off of the latest code in `rel/2.1.0-preview2` branch?

**Comment by Plac3hold3r** [comment]
I seem to be running into errors when trying to run via `new3` command for `rel/2.1.0-preview2` branch.

This is the console output of the `sh setup.sh`

> `sh setup.sh`
> Using RID: osx.10.12-x64                                                                                                                     
> Using OS: osx.10.12                                                                                                                          
> Using build configuration Debug                                                                                                              
> /Users/jon/Repositories/GitHub/templating                                                                                                    
> Removing ~/.templateengine...                                                                                                                
> Removing packages from cache...                                                                                                              
> Done                                                                                                                                         
> Creating directory structure...                                                                                                              
> mkdir: dev: File exists                                                                                                                      
> mkdir: dev/BuiltIns: File exists                                                                                                             
> dotnet-install: Calling: machine_has curl                                                                                                    
> dotnet-install: Calling: calculate_vars                                                                                                      
> dotnet-install: Calling: get_normalized_architecture_from_architecture <auto>                                                                
> dotnet-install: Calling: get_machine_architecture                                                                                            
> dotnet-install: Calling: get_normalized_architecture_from_architecture x64                                                                   
> dotnet-install: normalized_architecture=x64                                                                                                  
> dotnet-install: Calling: get_specific_version_from_version https://dotnetcli.azureedge.net/dotnet LTS x64 1.0.4                              
> dotnet-install: specific_version=1.0.4                                                                                                       
> dotnet-install: Calling: construct_download_link https://dotnetcli.azureedge.net/dotnet LTS x64 1.0.4                                        
> dotnet-install: Calling: get_current_os_name                                                                                                 
> dotnet-install: download_link=https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.4/dotnet-sdk-1.0.4-osx-x64.tar.gz                               
> dotnet-install: Calling: construct_legacy_download_link https://dotnetcli.azureedge.net/dotnet LTS x64 1.0.4                                 
> dotnet-install: Calling: get_legacy_os_name                                                                                                  
> dotnet-install: legacy_download_link=https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.4/dotnet-dev-osx-x64.1.0.4.tar.gz                        
> dotnet-install: Calling: resolve_installation_path <auto>                                                                                    
> dotnet-install: Calling: get_user_install_path                                                                                               
> dotnet-install: resolve_installation_path: user_install_path=/Users/jon/Repositories/GitHub/templating/.dotnet                               
> dotnet-install: install_root=/Users/jon/Repositories/GitHub/templating/.dotnet                                                               
> dotnet-install: Calling: check_pre_reqs                                                                                                      
> dotnet-install: Calling: install_dotnet                                                                                                      
> dotnet-install: Calling: is_dotnet_package_installed /Users/jon/Repositories/GitHub/templating/.dotnet sdk 1.0.4                             
> dotnet-install: Calling: combine_paths /Users/jon/Repositories/GitHub/templating/.dotnet sdk                                                 
> dotnet-install: combine_paths: root_path=/Users/jon/Repositories/GitHub/templating/.dotnet                                                   
> dotnet-install: combine_paths: child_path=sdk                                                                                                
> dotnet-install: Calling: combine_paths /Users/jon/Repositories/GitHub/templating/.dotnet/sdk 1.0.4                                           
> dotnet-install: combine_paths: root_path=/Users/jon/Repositories/GitHub/templating/.dotnet/sdk                                               
> dotnet-install: combine_paths: child_path=1.0.4                                                                                              
> dotnet-install: is_dotnet_package_installed: dotnet_package_path=/Users/jon/Repositories/GitHub/templating/.dotnet/sdk/1.0.4                 
> dotnet-install: .NET SDK version 1.0.4 is already installed.                                                                                 
> dotnet-install: Calling: combine_paths /Users/jon/Repositories/GitHub/templating/.dotnet                                                     
> dotnet-install: combine_paths: root_path=/Users/jon/Repositories/GitHub/templating/.dotnet                                                   
> dotnet-install: combine_paths: child_path=                                                                                                   
> dotnet-install: Calling: get_absolute_path /Users/jon/Repositories/GitHub/templating/.dotnet/                                                
> dotnet-install: Adding to current process PATH: `/Users/jon/Repositories/GitHub/templating/.dotnet`. Note: This change will be visible only w
> hen sourcing script.                                                                                                                         
> dotnet-install: Installation finished successfully.                                                                                          
> Microsoft (R) Build Engine version 15.1.1012.6693                                                                                            
> Copyright (C) Microsoft Corporation. All rights reserved.                                                                                    
>                                                                                                                                              
>   1777                                                                                                                                       
>   4636fb677a1e54b21c55dcad814c5b8a970acf37                                                                                                   
>   Restoring packages for /Users/jon/Repositories/GitHub/templating/src/Microsoft.TemplateEngine.Abstractions/Microsoft.TemplateEngine.Abstrac
> tions.csproj...                                                                                                                              
> Importing built in templates...                                                                                                              
> Done!                                                                                                                                        
> You can now use setup.sh from anywhere to rebuild dotnet new3                                                                                
> You can now use harderreset.sh from anywhere to delete dotnet new3 artifacts                                                                 
> chmod: /Users/jon/Repositories/GitHub/templating/dev/dotnet-new3.sh: No such file or directory                                               
> dotnet new3 is ready!  

Which seems to complete successfully, however it does say that `dotnet-new3.sh` is missing from the `dev` directory, which I would guess relates to the issue running `new3`??

Then when I try and run `dotnet new3 --help` I get the following error saying that there are "more that one project file".

> `dotnet new3 --help`
> Specify which project file to use because this '/Users/jon/Repositories/GitHub/templating' contains more than one project file.    

Trying the same command from a different directory yields the following error  

>   `dotnet new3 --help`
> System.ComponentModel.Win32Exception (0x80004005): No such file or directory                                                                 
>    at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout
> , Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)                                               
>    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)                                                                       
>    at System.Diagnostics.Process.Start()                                                                                                     
>    at Microsoft.DotNet.Cli.Utils.Command.Execute()                                                                                           
>    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)                                                    
>    at Microsoft.DotNet.Cli.Program.Main(String[] args)        
>

**Comment by mlorbetske** [comment]
I ran into this last night too but haven't gotten to take a closer look at it yet. The error with fork is actually for the permissions not being right for `dotnet-new3.sh`, you'll want to set the executable bit on it, however, setup didn't actually complete fully, you'll want to do `dotnet msbuild build.proj` to force the build to actually happen.

**Comment by Plac3hold3r** [comment]
Awesome, thank you for all your help. I was able to test against `rel/2.1.0-preview2` branch with `new3` with the following details:

![image](https://user-images.githubusercontent.com/13716738/34447339-7fa453e4-eceb-11e7-919f-fa42a25046fb.png)

I also had to install .NET Core Runtime version 1.1.2. But after that I was able to generate a project with the template and it preserved the ".0" 👍 

In terms of when the stable version will include this fix, how does versioning work exactly? I use to think that the templating engine matched the versioning of the .NET core SDK. But it seems that idea was wrong and that the templating engine has it own versioning  accessible via `dotnet new --debug:version`? The current development branch name seems to suggest a v2.1 release but the .NET Core SDK has already moved past v2.1.

**Comment by mlorbetske** [comment]
Glad to hear it's working :)

With regard to versioning - agreed, it's super confusing. The version of the template engine is independent from the dotnet CLI because it's shipped as part of multiple products (Visual Studio, Visual Studio for Mac, the dotnet CLI and others). Since the version information itself isn't prominently exposed anywhere, we didn't put any effort into trying to make it align with any of the products it ships in. The commit hash is the interesting part (as we can track down what changes are included in that particular build from there) - the version number is just a convenience for us in being able to track down the matching NuGet packages for the engine binaries if someone runs this from the dotnet CLI (the information was already available in the properties DLLs themselves, but it's more of a pain to find it that way).

The branch name is interesting as well, since this ships as part of multiple products it doesn't really get a release schedule of its own (it just follows the release schedule of the things that carry it). We've tried naming branches for Visual Studio versions (which didn't work out very well) and .NET runtime versions (this worked a bit better), however, now that the SDK's version is looking like it'll stay different than the runtime it carries, this approach is beginning to make less sense. We'll put some more thought into this.

**Comment by Plac3hold3r** [comment]
Interesting, thanks for the details explanation. I did not fully realise that the templating engine was installed directly in Visual Studio. I always though that I was just run via the .NET core SDK installation. Would that explain the difference in behaviour between the dotnet CLI and Visual Studio VSIX with the templating engine wizard with regards to folder and generated solution file?

The scenario (I can create a separate issue, if this is template engine related?) is when you create a template with a predefined folder structure and solution the behaviour differs between dotnet CLI and Visual Studio VSIX.

Example for the dotnet CLI, the template would generate:

```Text
src/**  - various cs projs included in template
test/** - various test cs projs included in template
*.sln   - the template solution
```

Visual studio would however generate:

```Text
<Chosen_name>/src/**  - various cs projs included in template
<Chosen_name>/test/** - various test cs projs included in template
<Chosen_name>/*.sln   - the template solution
*.sln                 - solution seemly generate by Visual Studio
```
Essentially, everything is placed inside of a folder and a new solution is generate for the root. There does not seem to be a way to turn off the behaviour.

This issue has also been reported under the sidewafflev2 repo [#24](https://github.com/ligershark/sidewafflev2/issues/24) and [#25](https://github.com/ligershark/sidewafflev2/issues/25). But I'm wondering if it is not a template engine issue.

**Comment by mlorbetske** [comment]
In this case, Visual Studio is generating a solution regardless of what the template specifies - that part isn't controllable by the engine. The custom wizard in [#25](https://github.com/ligershark/sidewafflev2/issues/25) runs in to some potential problems if the user attempts to add the projects to an existing solution - perhaps @phenning has some ideas on this (as well as for the project's name being used as an initial path part), maybe there are some additional switches we can expose in the wizard that would address this.

I wouldn't open a separate issue for this on this repo for that (since it's Visual Studio specific & that sort of thing isn't handled here - there is one Visual Studio specific project, but it's not actually used & should be deleted), let's just track it here unless you'd prefer to open an issue on Developer Community for it.

**Comment by Plac3hold3r** [comment]
I have created an issue on [Developer Community](https://developercommunity.visualstudio.com/content/problem/176022/dotnet-new-templating-engine-with-visx-auto-genera.html) as well

**Comment by Plac3hold3r** [comment]
Awesome, I can confirm that this is no longer an issue on Windows or macOS when using .NET Core SDK `2.1.4`. With the following template engine version
```Text
λ dotnet new --debug:version
Template Instantiation Commands for .NET Core CLI

 Version:     1.0.0-beta3-20171117-314
 Commit Hash: 71c5c12c4dbd25c35776431640238c29e01999e8
```

**Comment by mlorbetske** [comment]
Thanks @Plac3hold3r !
