### ISSUE TITLE
Template hangs during dotnet new

### ISSUE THREAD

**Issue by EdCharbeneau** [dotnet/templating#1409]
We’re having some trouble with the `dotnet CLI` template generation tool.
 
We had a working template, but something in the process has changed. For example, when we run:
 
```
.\nuget.exe pack .\kendo-ng
dotnet new -i .\Progress.AspNetCore.SpaTemplates.0.1.1.nupkg
dotnet new kendo-ng
```
 
_[Source Code](https://github.com/EdCharbeneau/kendo-ng/commits/master/content/kendo-ng) _
 
dotnet new hangs and never completes. Since there’s no error message, and reverting to the previously working copy doesn’t help, then we have no way to troubleshoot.
 
Is there anything you can do to help get us on the right path?

We tried several version of NuGet.exe 3.5 -> 4.4.1
Dotnet –version 2.1.4

**Comment by mlorbetske** [comment]
Cloning the repository and performing the steps you've listed (using the 4.4.1 version of NuGet.exe) I'm not experiencing a hang. Would it be possible to get one of the actual NuPkg files you're seeing this with? I'm currently wondering if maybe there are some additional large files (maybe non-template content artifacts from working with the project) that are getting included in the package that are severely slowing down create.

We've seen things of this nature with the version of the engine carried in the 2.1.4 CLI (in particular with large minified files) and have fixed those for the CLI release that will support the .NET Core 2.1.0 runtime. For 2.1.4, this can often be worked around by updating the `copyOnly` or `exclude` values for the default source in template.json; even with the fix included for CLIs with the 2.1 runtime, having these settings are recommended to ensure that build artifacts are regenerated or additional time isn't spent during creation looking for things to update in what should be a static file.

**Comment by EdCharbeneau** [comment]
Which .NET Version were you successful with?

**Comment by mlorbetske** [comment]
I used 2.1.4. @seancpeters has done some additional investigation & will reply in a bit with additional information & proposed changes.

**Comment by seancpeters** [comment]
I've downloaded the nupkg packaged in your repo here: https://github.com/EdCharbeneau/kendo-ng/blob/master/Progress.AspNetCore.SpaTemplates.0.1.1.nupkg and taken a look at it. Running the command `dotnet new kendo-ng` did not complete after about 30 minutes, it appeared to get stuck on the file `wwwroot\dist\main-client.js.map`.

As Mike speculated, there are a number of very large files that are probably just taking a very long time to process. For example under ClientApp\ there is a dist\ directory with a 12 Mb main-server.js file and a 3.8 Mb vendor.js file. The main-server.js file is marked as copy-only in template.json, and so shouldn't slow things down, but the vendor.js file gets processed. Also, the wwwroot folder has large files that get processed: main-client.js is copy-only, but main-client.js.map and vendor.js are large, and get processed.

The template.json could be modified to copy-only the entire directories. I modified the source copy-only section to copy-only the entire contents of ClientApp & wwwroot, and was able to successfully run `dotnet new kendo-ng`. It completed in < 1 second with that modification. The specific change I made was this (leaving the original commented out, for comparison purposes:
```
  "sources": [
    {
      "source": "./",
      "target": "./",
      "exclude": [
        ".template.config/**"
      ],
      "copyOnly": [
//        "ClientApp/dist/main-server.js",
//        "wwwroot/dist/main-client.js"
        "ClientApp/**",
        "wwwroot/**"
      ]
    }
  ],
```

**Comment by seancpeters** [comment]
Another way to go is to performg a clean on the project before packing the nupkg. This should eliminate the need for special directive on build-artifact files. But to be really safe, you could also include the copy-only directives, in case the nupkg gets mistakenly packed with artifacts again in a future release.

**Comment by EdCharbeneau** [comment]
@seancpeters @mlorbetske Thanks so much for taking the time to investigate this. We'll make the recommended changes and report back our findings.

**Comment by EdCharbeneau** [comment]
Excellent feedback. The package works flawlessly now.
