### ISSUE TITLE
Please update vue/typescript template

### ISSUE THREAD

**Issue by denimaaark** [dotnet/templating#1414]
Please update vue/typescript template, there are old versions in package.json.

I have try to update manualy but there are errors on starting.

And please add .vue file extension as recognized file for imports etc.

**Comment by seancpeters** [comment]
@denimaaark - can you post the output from running `dotnet --info`? Also, could you post the exact command use used to try to update the template?

**Comment by mlorbetske** [comment]
This issue was moved to aspnet/templating#568
