### ISSUE TITLE
Add flag/option for indent character preference

### ISSUE THREAD

**Issue by CzechsMix** [dotnet/templating#1440]
I hate to resurface the Tabs vs Spaces debate, but since it's far from settled, I'd like if the cli gave me the option.

**Comment by mlorbetske** [comment]
Adding support for code styles could be nice, but requires semantic understanding of the content being generated, which is not actually available with the runnable project generator. Options for tabs vs. spaces, `var` vs qualified type names, brace positioning, etc could be provided by individual templates, but would require those templates to have content that can adjust to each of those pivots (and combinations of those pivots) which potentially makes it much more expensive to create a template that offers a compelling set of style options - the goal of this particular template format is to make it very easy to create templates, so this isn't something we'd be likely to recommend to do as a "best practice".

Unfortunately, I don't have a good alternative to offer either. I did some looking in to a way of applying editorconfig from the command line a while back for similar reasons, but it seems that the recommendation is not to do that (the owner of the tool I was looking at called out the need for semantic understanding of the documents as their reason).

**Comment by CzechsMix** [comment]
Ah, Understood.
