### ISSUE TITLE
spanish translation

### ISSUE THREAD

**Issue by UlisesTJ** [dotnet/templating#1448]
hello I would like to collaborate with your project for free by serving as a translator to Spanish

**Comment by mlorbetske** [comment]
Hi @UlisesTJ, thank you for your offer of help. However, we have a team that has been providing translations of the command line inputs and outputs already. With regard to localization of the content included in templates, we've built a system to support that, but haven't yet connected the parts of the build process that would be used to get things into the format required by our localization team. We'll happily evaluate pull requests for preparing the rest of that infrastructure, but this is not a language specific item.
