### ISSUE TITLE
Unexpected results when filtering installed templates by type "project"

### ISSUE THREAD

**Issue by livarcocc** [dotnet/templating#1450]
_From @scottaddie on March 5, 2018 21:4_

## Steps to reproduce
1. Run the following command: `dotnet new --type project`

## Expected  behavior
I'd expect to only see project templates listed.

## Actual behavior
In addition to project templates, I see the following item templates listed:
1. Solution File
1. Razor Page
1. MVC ViewImports
1. MVC ViewStart

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.2.0-preview1-007866)

Product Information:
 Version:            2.2.0-preview1-007866
 Commit SHA-1 hash:  a99154ed46

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\scaddie\.dotnet\x64\sdk\2.2.0-preview1-007866\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26103-03
  Build    : 1d51767c35cb879c2388adf3d76722c6ad658c72

_Copied from original issue: dotnet/cli#8727_

**Comment by seancpeters** [comment]
Created this issue https://github.com/aspnet/templating/issues/341 for RazorPage, Mvc ViewImports, & Mvc ViewStart templates.

**Comment by scottaddie** [comment]
@mlorbetske Filtering by language could be another useful feature. If I know I'll only ever use F#, for example, much of what's currently displayed is noise.

With that in mind, I'd expect the Razor Page, MVC ViewImports, and MVC ViewStart item templates' **Language** value to be populated. Right now, that column is blank for the item templates. It should reflect C# only, as depicted in the table below.

| Templates | Short Name | Language | Tags |
|-------------|---------------|-----------|-------|
| Console Application | console | [C#], F#, VB | Common/Console |
| Class library | classlib | [C#], F#, VB | Common/Library |
| Unit Test Project | mstest | [C#], F#, VB | Test/MSTest |
| xUnit Test Project | xunit | [C#], F#, VB | Test/xUnit |
| ASP.NET Core Empty | web | [C#], F# | Web/Empty |
| ASP.NET Core Web App (Model-View-Controller) | mvc | [C#], F# | Web/MVC |
| ASP.NET Core Web App | razor | [C#] | Web/MVC/Razor Pages |
| ASP.NET Core with Angular | angular | [C#] | Web/MVC/SPA |
| ASP.NET Core with React.js | react | [C#] | Web/MVC/SPA |
| ASP.NET Core with React.js and Redux | reactredux | [C#] | Web/MVC/SPA |
| ASP.NET Core Web API | webapi | [C#], F# | Web/WebAPI |
| global.json file | globaljson | | Config |
| NuGet Config | nugetconfig | | Config |
| Web Config | webconfig | | Config |
| Solution File | sln | | Solution |
| Razor Page | page | [C#] | Web/ASP.NET |
| MVC ViewImports | viewimports | [C#] | Web/ASP.NET |
| MVC ViewStart | viewstart | [C#] | Web/ASP.NET |

**Comment by seancpeters** [comment]
@scottaddie - it's currently possible to list the templates by a specific language. For example, if you want to see only the F# templates, use:
`dotnet new -lang F#`

In general, if your command line options can't be resolved to a single template to invoke, a list of the templates that matched the options will be displayed (or if nothing matches the criteria, the entire list will be displayed).

Regarding showing the language for item templates, as long as the template specifies a language, that language will be displayed regardless of the template type. It just happens to be the case that none of the item templates included by default specify a language. You're absolutely correct that the Razor Page, MVC ViewImports, and MVC ViewStart should include their language. I'll update the issue I created accordingly.

**Comment by scottaddie** [comment]
@seancpeters Thanks for the tip! I had no idea I could filter by language.

**Comment by scottaddie** [comment]
@livarcocc This was fixed via https://github.com/aspnet/templating/pull/343. Feel free to close this issue.
