### ISSUE TITLE
Change folder path in multi project solution

### ISSUE THREAD

**Issue by FlavioKrahl** [dotnet/templating#1452]
Hello, I have created a VSIX template using the sidewaffle creator and editing the created template.json file. It works fine except for one issue:
The folder the solution is created in contains an extra folder and has the wrong name.
So my question is: Is there a way to actually change folder names, solution names and pathing the template applys to new solutions? For example, my solution path now is "C:\dotnet projects\MyModule1\MyModule1.sln" whereas in this folder there is another Folder where the project folders are stored like this: "C:\dotnet projects\MyModule1\MyModule1\Project1\Project1.csproj" and "C:\dotnet projects\MyModule1\MyModule1\Project2\Project2.csproj".
What I want to achieve should look like this: 
"C:\dotnet projects\MyModule1\CustomName.MyModule1.sln" 
"C:\dotnet projects\MyModule1\Module.Project1\Project1.csproj"
Is there some way to do this?

**Comment by FlavioKrahl** [comment]
@sayedihashimi

**Comment by mlorbetske** [comment]
I believe @phenning has some stuff in progress for this

**Comment by phenning** [comment]
Could you please share your template.json?

**Comment by FlavioKrahl** [comment]
Hey @phenning sorry but i was not at work the last 2 weeks.
This is how my template.json looks like:
`{
  "author": "Me",
  "classifications": [],
  "description": "My Template for BasicData child dialog solutions",
  "name": "BasicData child dialog template",
  "defaultName": "MyChildDialog",
  "identity": "DialogSample.Template.CSharp",
  "groupIdentity": "DialogSample.Template",
  "tags": {
    "language": "C#",
    "type": "project"
  },
  "shortName": "childdialogtemplate",
  "sourceName": "ToolGroup",
  "guids": [
    "{D5F5B0B7-C91D-48BD-BADF-51460FF92B9D}",
    "{DF2BECCD-498B-4700-AA76-53BCAE6EC446}"
  ],
  "primaryOutputs": [
    {
      "path": "BasicData.ToolGroup\\BasicData.ToolGroup.csproj"
    },
    {
      "path": "BasicData.ToolGroup.Installer\\BasicData.ToolGroup.Installer.csproj"
    }
  ], 
  "sources": [
    { "source": "./" },
    { "target": "./" },
    { "include": [ "**/*" ] },
    { "exclude": [ "**/[Bb]in/**", "**/[Oo]bj/**", ".template.config/**/*", "**/*.filelist", "**/*.user", "**/*.lock.json", "**/ChildDialogTemplatePack/**", "**/BasicData.ToolGroup.sln"] }
  ]
}`

**Comment by phenning** [comment]
Your template.json looks good, I wonder though if the sourceName perhaps shouldn't be BasicData.ToolGroup, based on your primary outputs.

To your directory structure issue though, we unfortunately do not currently have support for this directly in Visual Studio via a simple Custom Template parameter. 

However, you can work around this with by configuring your own custom wizard running before our wizard which can update the destination directory for the project. 

In the future, we plan on enabling this scenario by allowing you to specify a custom parameter which would accomplish what the below workaround would do.

In order to eliminate that second level directory, your custom wizard would need to do something similar to this.:

```
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using EnvDTE;
using Microsoft.VisualStudio.TemplateWizard;

namespace CompanyNamespace
{
    public class CustomWizard : IWizard
    {
        private string _originalDestinationDirectory;
        
        public void BeforeOpeningFile(ProjectItem projectItem) { }

        public void ProjectFinishedGenerating(Project project) { }

        public void ProjectItemFinishedGenerating(ProjectItem projectItem) { }

        public void RunFinished() 
        {
            if (Directory.Exists(_originalDestinationDirectory))
            {
                Directory.Delete(_originalDestinationDirectory, true);
            }
        }

        public void RunStarted(object automationObject, Dictionary<string, string> replacementsDictionary, WizardRunKind runKind, object[] customParams)
        {
            _originalDestinationDirectory = replacementsDictionary["$destinationdirectory$"];
            replacementsDictionary["$destinationdirectory$"] = Path.GetDirectoryName(_originalDestinationDirectory);
        }

        public bool ShouldAddProjectItem(string filePath) => !File.Exists(filePath);
    }
}

```

You can add this to your vstemplate file that invokes your template, as shown below.

Addtionally, you can also pass other parameters to your template by using passthrough properties in the vstemplate. Alternately, you could also do this in your wizard by adding them directly to the replacements dictionary.

```
  <TemplateContent>
      <ProjectCollection />
      <CustomParameters>
        <CustomParameter Name "$language$" Value="CSharp" />
        <CustomParameter Name="$uistyle$" Value="none"/>
        <CustomParameter Name="$groupid$" Value="your.template.group.id" />
        <CustomParameter Name="$passthrough:MySymbolInTemplateConfig$" Value="Custom" />
      </CustomParameters>
  </TemplateContent>

  <WizardExtension>
    <Assembly>YourAssembly, Version=1.0.0.0, Culture=neutral, PublicKeyToken=32205a4084b9ece2</Assembly>
    <FullClassName>CompanyNamespaceCustomWizard</FullClassName>
  </WizardExtension>

  <WizardExtension>
    <Assembly>Microsoft.VisualStudio.TemplateEngine.Wizard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a</Assembly>
    <FullClassName>Microsoft.VisualStudio.TemplateEngine.Wizard.TemplateEngineWizard</FullClassName>
  </WizardExtension>

```

**Comment by FlavioKrahl** [comment]
OK that did the trick for me thanks a lot! I Think this Issue can be closed.

**Comment by HenKun** [comment]
I followed the guidance by @phenning and my custom wizard is called correctly and the `$destinationdirectory$` is replaced correctly. However, if the default wizard is called (Microsoft.VisualStudio.TemplateEngine.Wizard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a) an exception is raised:

"Der zu Grunde liegende exportierte Wert vom Typ 'Microsoft.VisualStudio.TemplateEngine.Contracts.ITemplateCreator' kann nicht in den Typ 'Microsoft.VisualStudio.TemplateEngine.Contracts.ITemplateCreator' umgewandelt werden."

Rougly in english:
"The underlying exported value of type 'Microsoft.VisualStudio.TemplateEngine.Contracts.ITemplateCreator' cannot be converted into type 'Microsoft.VisualStudio.TemplateEngine.Contracts.ITemplateCreator'"

As a result the projects are not generated. If I leave out the default wizard the projects are created but not correctly stored on disk and they look weird in the solution explorer.

is it a version conflict of ITemplateCreator?

**Comment by robertbarclayy** [comment]
Did this ever get addressed?
