### ISSUE TITLE
Better handling for choice parameter with an invalid default value

### ISSUE THREAD

**Issue by seancpeters** [dotnet/templating#1460]
When a template defines a choice parameter with a default value that is not one of the choices, errors are reporting when displaying help, and when attempting to invoke the template. This also occurs when the "replaces" value is used as the default - which occurs when no default is explicitly defined.

This situation should be reported at install time when the --trace:authoring flag is specified. 

One proposed way to handle this during template invocation is to cause these problematic choice parameters to be required - meaning the template won't invoke unless the author specifies a valid value.

**Comment by donJoseLuis** [comment]
This issue was last touched some years ago.  We are working on a new delivery road map.  Please reopen if this is something we want & we'll properly assess its' priority compared to other work aimed at improving the overall templating UX.
