### ISSUE TITLE
Conditionnal content in file with no extension

### ISSUE THREAD

**Issue by RomainWilbert** [dotnet/templating#1465]
Hi,

I have a template with a Dockerfile (no extension). I would like to add a condition in it. I read the documentation [https://github.com/dotnet/templating/wiki/Reference-for-comment-syntax#other-file-types](url), and I tried:
`//if (persistenceLayer)	
ENV MONGODB_URL mongodb://service:service@mongodb27017/dbname
//endif`
and also with Dockerfile standard comment syntax:
`#if (persistenceLayer)	
ENV MONGODB_URL mongodb://service:service@mongodb27017/dbname
#endif`
But it does not work. Are there limits on files types ?

**Comment by seancpeters** [comment]
@RomainWilbert - If you use a syntax like this, it should work:
```
//#if
...
//#endif
```

The documentation for the built in handling of "other" file types is a bit unclear. It mentions the prefix being `//`, but doesn't clearly indicate what the "conditional expressions" need to be. For templating, the conditional itself always begins with `#`, so the conditionals are things like `#if`, `#elseif`, `#elif`, etc. When those are put together with the "prefix", the full syntax is things like:
```
//#if
//#else
//#endif
```

**Comment by RomainWilbert** [comment]
Thanks, it works ! Documentation could be amended with an example.
