### ISSUE TITLE
Can't use Angular CLI commands (ng)

### ISSUE THREAD

**Issue by lukyer** [dotnet/templating#1475]
I'm trying to use newest ASP.NET Core 2.1 with Angular template. It works as is but i'm unable to scaffold components using `ng` command. Actually no `ng` command is working because of missing `.angular-cli.json` in default template.

It also makes impossible to `ng serve` manually out of ASP.NET Core application. It is important because now angular http server is always restarted and it has to start again (slow) with every rebuild.

**Comment by seancpeters** [comment]
Moving this issue to https://github.com/aspnet/templating/issues/367
