### ISSUE TITLE
Graceful recovery if user deletes installed templates

### ISSUE THREAD

**Issue by seancpeters** [dotnet/templating#1477]
Currently, if an installed template pack is deleted from the filesystem (not uninstalled using dotnet new -u), then the users configuration becomes invalid because `new` still has a reference to the template pack in its configuration files - one problem being that the template cache still contains entries for the deleted templates since they were not properly uninstalled. 

The template cache entries are used for initial filtering of templates based on the input parameters. But when a deleted template gets chosen to be acted upon (invoked or detailed help display), the engine attempts to open the full template. But the location indicated in the configuration data no longer exists, which currently results in a hard error. Fortunately this only occurs if the user manually messes with their install configuration.

**Proposed fix**:
When a situation as described above occurs, an attempt to repair the configuration will occur. This will entail re-checking all of the configured install locations to see if the content still exists. Those which no longer exist will be removed from the configuration, including the template cache. The user will be informed of all the removed template packs, along with a general message indicating that the problem was caused by the configuration being corrupted. Similar repair will be attempted for any installed custom code components, which could suffer from the same type of problem.

**Comment by donJoseLuis** [comment]
This issue was last touched some years ago.  We are working on a new delivery road map.  Please reopen if this is something we want & we'll properly assess its' priority compared to other work aimed at improving the overall templating UX.
