### ISSUE TITLE
fileRename does not update primaryOutputs

### ISSUE THREAD

**Issue by dlemstra** [dotnet/templating#1489]
I have created a template where a parameter renames a project file. But this does not seem to update the primaryOutputs. And because this is not updated I the `Add projects to a solution file` post action fails. I am using the following `.template.json`:

```json
{
  "$schema": "http://json.schemastore.org/template",
  "author": "TestTemplate",
  "classifications": [ "Common/Library" ],
  "identity": "TestTemplate",
  "sourceName": "TestTemplate",
  "name": "TestTemplate",
  "shortName": "test.template",
  "preferNameDirectory": true,
  "tags": {
    "language": "C#"
  },
  "symbols": {
    "testName": {
      "description": "The test argument.",
      "type": "parameter",
      "datatype": "string",
      "isRequired": true,
      "fileRename": "Name"
    }
  },
  "primaryOutputs": [
    {
      "path": "TestTemplate.Test.Name.csproj"
    }
  ],
  "postActions": [
    {
      "actionId": "D396686C-DE0E-4DE6-906D-291CD29FC5DE",
      "manualInstructions": [
        {
          "text": ""
        }
      ]
    }
  ]
}
```

When I use this template in a folder named `TestProject` with the following commands:
```
dotnet --version

dotnet new -i ../template

dotnet new test.template --testName FooBar
```

I get the following output:

```
2.1.103

Templates                                         Short Name         Language          Tags
----------------------------------------------------------------------------------------------------------
TestTemplate                                      test.template                        Common/Library

The template "TestTemplate" was created successfully.

Processing post-creation actions...
Adding project reference(s) to solution file. Running dotnet sln TestProject\TestProject.Test.FooBar.sln add TestProject.Test.Name.csproj
Failed to add project(s) TestProject.Test.Name.csproj to solution file TestProject\TestProject.Test.FooBar.sln
```

As you can see the solution name is changed from `TestTemplate.Test.Name.sln` to `TestProject.Test.FooBar.sln` but it tries to add `TestProject.Test.Name.csproj` to the solution. The file has been renamed on disk to `TestProject.Test.FooBar.csproj`. And `TestTemplate` has been renamed to `TestProject` in the `primaryOutputs` so it seems to work partially but `Name` has not been renamed to `FooBar`. 

I have created a repository that can be used to reproduce this issue: https://github.com/dlemstra/dotnet-templating-bug. The file `TestProject/create-test-project.cmd` can be used to reproduce the issue.

I have not tried this with the code from the repository so it might be possible that this has already been fixed.

**Comment by seancpeters** [comment]
@dlemstra - This issue still exists in the current code in the repo, I'm able to reproduce the problem locally. I'll update this thread when a fix is available, I expect to get to in within the next few days.

Thanks for making us aware of the issue, and providing the test repo - made it really easy to repro :)

**Comment by mlorbetske** [comment]
In addition to the PR I'm about to make, the template also needs the full relative path to the primary output file, currently it's just `TestTemplate.Test.Name.csproj` but needs to be `TestTemplate.Test.Name/TestTemplate.Test.Name.csproj` in order for the file to be located.
