### ISSUE TITLE
evaluate does not replace keyword.

### ISSUE THREAD

**Issue by dlemstra** [dotnet/templating#1490]
I have created a template where I want to use a computed variable to replace a keyword. This does not seem to work. But when I use a `generated` type with the `coalesce` generator it does seem to work. I first tried `computed` but this also does not seem to work, the docs make it look like this can only be a boolean. This might be by design but I would like to use a variable to replace a keyword.

 I am using the following template:

```json
{
  "$schema": "http://json.schemastore.org/template",
  "author": "TestTemplate",
  "classifications": [ "Common/Library" ],
  "identity": "TestTemplate.evaluate",
  "sourceName": "TestTemplate",
  "name": "TestTemplate",
  "shortName": "test.template.evaluate",
  "preferNameDirectory": true,
  "symbols": {
    "name1": {
      "type": "generated",
      "generator": "evaluate",
      "value": "name",
      "replaces": "Name1"
    },
    "name2": {
     "type": "generated",
     "generator": "coalesce",
     "parameters": {
       "sourceVariableName": "name",
       "fallbackVariableName": "name"
     },
     "replaces": "Name2"
    },
    "name3": {
      "type": "computed",
      "value": "name",
      "replaces": "Name3"
    }
  }
}
```

And the class where I want to replace keywords has this content:

```C#
using System;

namespace Template
{
    public class Class1_Name1
    {
    }

    public class Class1_Name2
    {
    }

    public class Class1_Name3
    {
    }
}
```

I would expect the following output:

```C#
using System;

namespace Template
{
    public class Class1_TestProject
    {
    }

    public class Class1_TestProject
    {
    }

    public class Class1_TestProject
    {
    }
}
```

But I get the following output:

```C#
using System;

namespace Template
{
    public class Class1_Name1
    {
    }

    public class Class1_TestProject
    {
    }

    public class Class1_Name3
    {
    }
}
```

It does seem to work with `coalesce` and I can use that as a work around but I would prefer to use a `evaluate` or maybe even a `computed` value.

I have created a repository that can be used to reproduce this issue: https://github.com/dlemstra/dotnet-templating-bug. The file `evaluate/TestProject/create-test-class.cmd` can be used to reproduce the issue.

I have not tried this with the code from the repository so it might be possible that this has already been fixed.

**Comment by mlorbetske** [comment]
The computed and evaluated symbols are actually the same thing (computed is a short hand for generated evaluate type symbols) - this evaluates an expression and produces a boolean result, so those aren't suitable for this purpose. A derived symbol should work for this:

```
   "name3": {
      "type": "derived",
      "valueSource": "name",
      "valueTransform": "identity",
      "replaces": "Name3"
   }
```

Please re-open if this solution doesn't meet you needs.
