### ISSUE TITLE
[Proposal] Update help to not aggregate all parameters in all templates across groups

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/templating#1491]
**Problem**
Imagine a set of templates T1, T2 and T3 with the same `groupIdentity` and `shortName` "T"

|   | T1 | T2 | T3
|---|---|----|----
| Precedence | 1 | 2| 3
| --framework | netcoreapp1.0 | netcoreapp2.0 | netcoreapp3.0
| --a | yes | no | no
| --b | no | yes | no
| --c | no | no | yes

- a, b and c being optional parameters - yes and no indicating whether it's defined on that template
- framework's default assumed to be the value listed in the table

Today, calling up help on "T" will result in something like

```
--a                  Information about a
--b                  Information about b
--c                  Information about c
--framework          Information about framework
                         netcoreapp1.0
                         netcoreapp2.0
                         netcoreapp3.0
```

This is a bit confusing - all the options for all templates have been merged together & it's not clear to which template(s) `--a`, `--b` or `--c` apply or that they relate to the value of `--framework`

At invocation time:
- If no parameters are specified, you'll get `T3` since it has the highest precedence
- If you specify `--framework`, you'll get the template with the matching framework
- If you specify `--a`, `--b` or `--c`, you'll get the template for which they're defined
- If you specify a combination of `--a`, `--b` and `--c`, you'll get an error as no template defines a combination of them
- If you specify a combination of `--framework` and `--a`, `--b` or `--c`, where the additional option isn't defined on the template with the value of `--framework`, you'll also get an error

**Desired Outcome**
Display help for the most relevant specific subset of templates in the group by default, but allow opting-in to the current behavior to see the all the available data.

Ex. If the CLI in use carries the 2.0 runtime, help would ideally look like this (with better messages, of course):

```
--b                  Information about b
--framework          Information about framework
                         netcoreapp1.0 (more specific help available)
                         netcoreapp2.0
                         netcoreapp3.0 (more specific help available)

* Some information has been filtered out
  To see all help, run dotnet new T --help --all
  To see more specific help, try passing the parameter and value along with the --help switch
```

Running `dotnet new T` then should produce content corresponding to the one that information was shown about in help (in this case T2).

**Proposed Solution**
*For simplicity, it's assumed that we're talking about the single, unambiguous template group case. No multi-group scenarios should be impacted by this change*

Surface an [additional value](https://github.com/dotnet/cli/blob/master/src/dotnet/commands/dotnet-new/NewCommandShim.cs#L60) from the host (the dotnet CLI) to the engine, (the default app-model target framework) and use it to select a subset of the templates in the group from which to select the "preferred" help properties.

The filtering will be done by comparing the incoming value to all choice-type parameters on the template information for each template in the group. If found, the name of the parameter whose choices contain the value would be noted.

If the user's input at the command line specifies that parameter, or no templates are found with a matching choice value, we'd use the current logic instead of continuing down the new path.

Otherwise, the current merge logic would be run over those templates that did match to produce the top-level help information (constraining the parameters that may be shown). Remaining templates in the group would then be inspected & their choice type parameter values concatenated to any matching choice type parameter values, adding the "more specific help available" tag to them.

At invocation time, this additional filtering process would also run to ensure that `dotnet new T {args}` and `dotnet new T {args} --help` are always in terms of the same template.

**Comment by mlorbetske** [comment]
@javiercn

**Comment by donJoseLuis** [comment]
This issue was last touched some years ago.  We are working on a new delivery road map.  Please reopen if this is something we want & we'll properly assess its' priority compared to other work aimed at improving the overall templating UX.
