### ISSUE TITLE
I cannot create a .NET Core 2.0 console app with `dotnet new console`

### ISSUE THREAD

**Issue by livarcocc** [dotnet/templating#1495]
_From @richlander on April 2, 2018 23:42_

I want to do this:

````
dotnet new console -f netcorapp2.0
```

I cannot. How do I specify the TFM for a new app?

_Copied from original issue: dotnet/cli#8973_

**Comment by livarcocc** [comment]
This is currently not supported by dotnet new console and it is actually on the list of work items we need to do to support our LTS plan of having only a current version of the SDK. This was one of the things you, me and @leecow discussed. In any case, I will move this issue to dotnet/templating.

**Comment by seancpeters** [comment]
The 2.1 CLI install does not carry the 2.0 templates. The pack containing the 2.0 console template could be installed using:
`dotnet new -i Microsoft.DotNet.Common.ProjectTemplates.2.0::1.0.0-beta*`

Then you'll have the 2.1 console template (carried by 2.1 CLI), and the 2.0 console template, which was installed by the above command.
