### ISSUE TITLE
Provide a way to split up features in template.json

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/templating#150]
My template.json is going to get very long and difficult to maintain, especially when all the JSON for a single feature is not all together in one place but spread across the template.json file. Would it be possible to somehow have a json file per feature?

Perhaps we can copy the ASP.NET Core configuration where we can add additional config files by adding as many template.{featurename}.json files as you want. Each additional feature file can contain the same schema minus the header section at the top of the file.

**Comment by attilah** [comment]
Composeable templates and "template inheritance" would be an awesome feature to get rid of copy paste...of course it involves template dependency and templates referencing each other.

**Comment by mlorbetske** [comment]
@attilah I think that deserves its own issue, could you open one with your thoughts on the topic? We've discussed composition in the past but haven't found a way to make it non-fragile (as you note). Maybe if the template could depend on a specific version of another template and we require all template kinds to export some sort of version information?

**Comment by mlorbetske** [comment]
Something like this could also help declare a common set of parameters across multiple templates in a package

**Comment by attilah** [comment]
Yes template versioning is one this I "miss". But that's where it gets complicated...and I feel an NPM hell in my veins... :-)

Issue I created: https://github.com/dotnet/templating/issues/285

**Comment by mlorbetske** [comment]
@attilah thanks!

**Comment by seancpeters** [comment]
Implemented in #366

**Comment by RehanSaeed** [comment]
@seancpeters How does this now work?

**Comment by seancpeters** [comment]
@RehanSaeed to spilt up a template config into multiple files:
The template.json file can still contain any parts of the config desired (or none, it doesn't really matter). To reference other files with pieces of the configuration, template.json needs a top-level element called "AdditionalConfigFiles", whose value is an array of strings. Each entry is the name of another file to read configuration from. For example, something like this:
`  "AdditionalConfigFiles": [ 
    "otherStuff.template.json"
  ],`
All of the config files must be in the same directory as the template.json file. Also the file names must end with `.template.json`. 

Here's an example, based on the current C# console app template in this repo:
Content of template.json
{
  "author": "Microsoft",
  "classifications": ["Common", "Console"],
  "name": "Console Application",
  "groupIdentity": "Microsoft.Common.Console",
  "identity": "Microsoft.Common.Console.CSharp",
  "shortName": "console",
  "tags": {
    "language": "C#",
    "type": "project"
  },
  "AdditionalConfigFiles": [
    "symbols.template.json"
  ],
  "sourceName": "Company.ConsoleApplication1",
  "preferNameDirectory": true,
  "primaryOutputs": [ { "path": "Company.ConsoleApplication1.csproj" } ]
}`

Content of symbols.template.json
{
  "symbols": {
    "sdkVersion": {
      "type": "bind",
      "binding": "dotnet-cli-version",
      "replaces": "1.0.0-preview5-004445"
    },
    "Framework": {
      "type": "parameter",
      "datatype": "choice",
      "choices": [
        {
          "choice": "netcoreapp1.0",
          "description": "Target netcoreapp1.0"
        },
        {
          "choice": "netcoreapp1.1",
          "description": "Target netcoreapp1.1"
        }
      ],
      "defaultValue": "netcoreapp1.1"
    }
  }
}`

At this point, I'm not 100% sure when this functionality will be released.
