### ISSUE TITLE
Restore hangs when referenced project targets only .net standard 2.0

### ISSUE THREAD

**Issue by livarcocc** [dotnet/templating#1506]
_From @MNie on April 6, 2018 20:53_

## Steps to reproduce
1. Try to install an Expecto Template via `dotnet new -i Expecto.Template`

## Expected  behavior
2. Everything is ok, the template is installed as expected.

## Actual behavior
```bash
$ dotnet new -i Expecto.Template
...
...
~/.templateengine/dotnetcli/v2.1.4/scratch/restore.csproj : error NU1202: Package Expecto 7.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Expecto 7.0.0 supports:
~/.templateengine/dotnetcli/v2.1.4/scratch/restore.csproj : error NU1202:   - net461 (.NETFramework,Version=v4.6.1)
~/.templateengine/dotnetcli/v2.1.4/scratch/restore.csproj : error NU1202:   - netstandard2.0 (.NETStandard,Version=v2.0)
  Generating MSBuild file ~/.templateengine/dotnetcli/v2.1.4/scratch/obj/restore.csproj.nuget.g.props.
  Generating MSBuild file ~/.templateengine/dotnetcli/v2.1.4/scratch/obj/restore.csproj.nuget.g.targets.
  Restore failed in 6.24 sec for ~/.templateengine/dotnetcli/v2.1.4/scratch/restore.csproj.
```
2. Installation hangs with an error that Expecto library doesn't support .net core 1.0 (Expecto supports .net standard 2.0, and drops support to .net standard 1.6 after 7.0 release).
3. When we cancel the installation, regardless of the error from point 2, a template would be installed properly.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.103)

Product Information:
 Version:            2.1.103
 Commit SHA-1 hash:  60218cecb5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.103\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
```

[Related issue](https://github.com/MNie/Expecto.Template/issues/10)

_Copied from original issue: dotnet/cli#9017_

**Comment by mlorbetske** [comment]
Template packages are currently required to target netcoreapp1.0 even if it doesn’t apply to the content in them. A hang certainly isn’t expected though, we’ll investigate.

**Comment by mlorbetske** [comment]
I tried this out and took a look at the template package. The template package's target framework is OK (not specified). As far as the hang goes, it turns out (at least on Windows, I haven't tried this on my mac yet) that this isn't actually a hang. Because of the way that the template is authored (where the libraries used by the template are referenced in the template package itself) the installation process ends up looking through all of the types in all of the DLLs that are restored by the dependencies to see if there are any components that are required for making the template - this process takes a long time (multiple minutes) but does eventually complete, discovering the contained templates and no "components".

The nupkg containing the template currently has a NuSpec that looks like this:

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>Expecto.Template</id>
    <version>8.2.0</version>
    <authors>Michał Niegrzybowski</authors>
    <owners>Michał Niegrzybowski</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <licenseUrl>https://github.com/MNie/Expecto.Template/blob/master/LICENSE</licenseUrl>
    <projectUrl>https://github.com/MNie/Expecto.Template</projectUrl>
    <description>Expecto .net core Template</description>
    <copyright>Copyright 2018</copyright>
    <tags>.net core Expecto template</tags>
    <packageTypes>
      <packageType name="Template" />
    </packageTypes>
    <dependencies>
      <dependency id="Expecto" version="[7.0.0, 8.0.0)" />
      <dependency id="FSharp.Core" version="[4.2.3, 5.0.0)" />
      <dependency id="YoloDev.Expecto.TestSdk" version="[0.5.0, 1.0.0)" />
      <dependency id="Microsoft.NET.Test.Sdk" version="[15.0.0, 16.0.0)" />
    </dependencies>
  </metadata>
</package>
```

Changing it to this:

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>Expecto.Template</id>
    <version>8.2.0</version>
    <authors>Michał Niegrzybowski</authors>
    <owners>Michał Niegrzybowski</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <licenseUrl>https://github.com/MNie/Expecto.Template/blob/master/LICENSE</licenseUrl>
    <projectUrl>https://github.com/MNie/Expecto.Template</projectUrl>
    <description>Expecto .net core Template</description>
    <copyright>Copyright 2018</copyright>
    <tags>.net core Expecto template</tags>
    <packageTypes>
      <packageType name="Template" />
    </packageTypes>
  </metadata>
</package>
```

Should dramatically speed up the installation process (getting it down to a second or so).

**Comment by MNie** [comment]
@mlorbetske wow, I will update nuspec file and release a new version and check if that helps. Thank you!

**Comment by MNie** [comment]
@mlorbetske 

![image](https://user-images.githubusercontent.com/7689103/38472197-8524c03a-3b7c-11e8-8b81-13a0a007c357.png)

Works like a charm! Thank you one more time :)!

**Comment by mlorbetske** [comment]
Glad to hear it!

**Comment by MNie** [comment]
@mlorbetske but there are some disadvantages of this. Right now section of dependencies on nuget is empty:
![image](https://user-images.githubusercontent.com/7689103/38489381-8333b2da-3be6-11e8-9706-0bd14e73a331.png)

**Comment by mlorbetske** [comment]
This is actually correct, as the package doesn’t have any dependencies for its function. I do take your meaning though, the user isn’t able to examine that section to determine what the created content would depend on - I’d suggest including that information in one of the description fields of the package if you feel that it would be valuable.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MNie** [comment]
@mlorbetske I'm not 100% sure if a description is a right place for something like that. Maybe it would be doable to create some section on NuGet page, which will write all dependencies from some special section in a nuspec if it is a DotNet Core template? Wouldn't be that a good idea?

**Comment by mlorbetske** [comment]
Sounds interesting, I’d suggest filing an issue on NuGet/Home to get their thoughts on it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
