### ISSUE TITLE
launchUrl property shows a warning

### ISSUE THREAD

**Issue by jbagga** [dotnet/templating#1508]
![image](https://user-images.githubusercontent.com/6234561/38575613-af8fcbc8-3cb0-11e8-871e-a20556e84271.png)

When trying to use `launchUrl` in `launchSettings.json`, the user sees a warning but the correct url (as specified in `launchUrl` and `applicationUrl`) is launched regardless

cc @seancpeters

**Comment by mlorbetske** [comment]
@jbagga is there thinking that this is related to the project creation process? This looks like an issue with the schema for launchSettings.json

**Comment by jbagga** [comment]
Yeah, it does look like a schema issue. Where is the appropriate place to file this? @seancpeters said here was fine and he can look into it.

**Comment by seancpeters** [comment]
Yeah, I had originally mistook it as an issue with Mads' template.json schema, which is not the case.

**Comment by mlorbetske** [comment]
Closing this, opened a PR with the change here https://github.com/SchemaStore/schemastore/pull/430

**Comment by jbagga** [comment]
> the expectation for the repo is generally for folks to fix issues they find themselves

@mlorbetske Oh I was not aware. Sorry! Thanks for the fix

**Comment by mlorbetske** [comment]
To clarify, I meant that for schemastore that's the expectation generally
