### ISSUE TITLE
How do I find the fully expanded file path of where the template is being installed?

### ISSUE THREAD

**Issue by jakejscott** [dotnet/templating#1517]

**Comment by seancpeters** [comment]
If you are installing templates from a .nupkg or a .zip, they go under your user directory, which Windows, the basedir is `%USERPROFILE%`, and on mac / *nix it's`~`.

Under that directory, look in .templateengine/dotnet/cli/<dotnet-version>/packages/

So, for example, on my windows machine running 2.2.0-preview1-008003 I'd find my installed templates under `C:\Users\sepeters\.templateengine\dotnetcli\v2.2.0-preview1-008003\packages\`
And similarly on *nix, the location would be
`/home/sepeters/.templateengine/dotnetcli/v2.2.0-preview1-008003/packages/`

If you're developing your own templates and install from a directory on the filesystem (not a .nupkg or .zip), the "install location" remains wherever you install from.

Is there something particular you want to do with the installed templates? Perhaps there are built-in commands to take care of it. Any manual modifications to files / directories under the .templateengine directory could leave you in a corrupted state

**Comment by jakejscott** [comment]
Nice one thanks
