### ISSUE TITLE
NuGet.config template adds bogus entry to the sources list

### ISSUE THREAD

**Issue by anurse** [dotnet/templating#1520]
Repro steps:

1. `mkdir Test`
2. `dotnet new nugetconfig`
3. `cat nuget.config`

Expected Output:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
 <packageSources>
    <!--To inherit the global NuGet package sources remove the <clear/> line below -->
    <clear />
    <add key="nuget" value="https://api.nuget.org/v3/index.json" />
 </packageSources>
</configuration>
```

Actual Output:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
 <packageSources>
    <!--To inherit the global NuGet package sources remove the <clear/> line below -->
    <clear />
    <add key="test" value="https://api.test.org/v3/index.json" />
 </packageSources>
</configuration>
```

I'm not sure what the `test` entry is, but it seems to match the name of the directory in which the template is run. Something seems to be replacing the "nuget" string in the actual template file with the name of the directory. That's not something I'd expect to happen, and it's confusing because I don't know what this feed is for or if it's a "real" feed (unlikely since it's based on my directory name ;))

**Comment by mlorbetske** [comment]
The associated PR for this has been merged
