### ISSUE TITLE
Nuget config template needs update

### ISSUE THREAD

**Issue by seancpeters** [dotnet/templating#1523]
While testing #1522 I noticed that with sourceName = "Nuget", the source name value was replacing "nuget" (different casing), but was not replacing "NuGet" (also different casing). 

If sourceName is changed to "NuGet", then it replaces both "nuget" and "NuGet".

TODO: Determine what causes this, the scope of the problem, and the fix.

**Comment by seancpeters** [comment]
I believe this issue came to be when value forms were reworked. The sourceName implicitly gets assigned the safe name, safe namespace, etc. value forms in addition to identity. It's most likely those replacements which are causing the problem. 

Case 1: When sourceName = "Nuget":
The lowercase source safe name is "nuget", thus it gets replaced. But "NuGet" doesn't match any of the value form transformations of "Nuget".

Case 2: When sourceName = "NuGet"
The lowerase source safe name is the same as case 1. And "NuGet" is a direct (identity) match, and so the original form of the input name is used for the replacement.

So there is probably no problem in the engine, the problem is this template's configuration.

**Comment by mlorbetske** [comment]
The above comment is correct, the lowercase value form is what allows the lower case variation to match

**Comment by seancpeters** [comment]
This is dealt with in #1522

**Comment by mlorbetske** [comment]
The associated PR has been merged
