### ISSUE TITLE
XML Encoding Not Working

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/templating#1524]
I am using a symbol to replace content in a `csproj` file. I understand from https://github.com/dotnet/templating/issues/368 that I can XML encode the contents like so:

```
  "symbols": {
    "Title": {
      "type": "parameter",
      "datatype": "string",
      "defaultValue": "Project Title",
      "replaces": "PROJECT-TITLE",
      "description": "The name of the project which determines the assembly product name.",
      "forms": [ "encode" ]
    },
  "forms": {
    "encode": {
      "identifier": "xmlEncode"
    }
  }
```

When I run:

`dotnet new graphql --name Foo --Title "Foo & Bar"`

My csproj file is output with:

`<Product>Foo & Bar</Product>`

XML encoding is failing to occur. As an aside, what happens if you want to make the replacement in a csproj and separately a json file? i.e. I only want to XML encode when I replace the content in the csproj file and not the JSON file.

**Comment by seancpeters** [comment]
I agree, it is a bit complicated. Here's another way to do it that you might like better, and doesn't require sometimes xml encoding in the template source.
Not too long ago, we introduced "derived symbols" which allow transforming the value of one symbol into the value of another. So a template could be setup to have a title symbol as a normal string parameter, such as:
```
    "Title": {
	  "type": "parameter",
	  "datatype": "string",
	  "defaultValue": "Project Title",
	  "replaces": "PROJECT TITLE",
	  "description": "Plaintext title",
	},
```
And then define a symbol whose value is derived from this symbol, and replaces something else, such as:
```
    "XmlEncodedTitle": {
	  "type": "derived",
	  "replaces": "PROJECT XML TITLE",
	  "description": "Xml encoded title",
	  "valueSource": "Title",
	  "valueTransform": "xmlEncode"
	}
```

The derived symbol's value is determined by the attributes:
- valueSource: The name of the other symbol that this symbol's value is derived from.
- valueTransform: How the other symbol's value is transformed to generate this value. This can be a built in value form, or one defined in the "forms" section of the template.

Given the above symbol definitions, and template content of:
```
<Product>PROJECT XML TITLE</Product>
<Product>PROJECT TITLE</Product>
```
...and invoking the template with `--Title "Foo & Bar"`, the content would be transformed to:
```
<Product>Foo &amp; Bar</Product>
<Product>Foo & Bar</Product>
```

With this method (if a jsonEncode value form existed), then for adding a json encoded version of the title, and appropriate replacements, we'd just define another derived symbol, such as:
```
    "JsonEncodedTitle": {
	  "type": "derived",
	  "replaces": "PROJECT JSON TITLE",
	  "description": "Json encoded title",
	  "valueSource": "Title",
	  "valueTransform": "jsonEncode"
	}
```

Note that there is no need to have the words "json" or "xml" in the replaces values, I was using those values for clarity.

**Comment by RehanSaeed** [comment]
Thanks, that seems to be a much cleaner approach. Was about to raise an issue for a JSON encode form but looks like you've already beat me to it https://github.com/dotnet/templating/issues/1526.

**Comment by RehanSaeed** [comment]
BTW, I had to add a `datatype` property. The JSON schema needs updating as I was getting warnings about `type` being set to `derived`.

```
    "TitleXmlEncoded": {
      "type": "derived",
      "datatype": "string",
      "replaces": "PROJECT-TITLE-XML",
      "valueSource": "Title",
      "valueTransform": "xmlEncode"
    },
```
