### ISSUE TITLE
Mandatory parameters (isRequired) missing in schema

### ISSUE THREAD

**Issue by matkoch** [dotnet/templating#1537]
Seems that all parameters are optional. Are there any plans to support mandatory parameters as well?

**Comment by marcusien** [comment]
Hi, you can mark each symbol as "isRequired":"true"

Example : 

> "symbols": {
>     "firstParameter": {
>       **"isRequired": "true",**
>       "type": "parameter",
>       "datatype": "string",
>       "replaces": "MY_FIRST_PARAMETER_TO_REPLACE",
>       "description": "First mandatory parameter"
>     },
>  "secondParameter": {
>       **"isRequired": "true",**
>       "type": "parameter",
>       "datatype": "string",
>       "replaces": "MY_SECOND_PARAMETER_TO_REPLACE",
>       "description": "Second mandatory parameter"
>     },
>  "thirdParameter": {
>       **"isRequired": "false",**
>       "type": "parameter",
>       "datatype": "string",
>       "replaces": "MY_THIRD_PARAMETER_TO_REPLACE",
>       "description": "Third optional parameter"
>     }
> }

Is it what you're asking for ?

**Comment by matkoch** [comment]
Nice, thanks @marcusien. It's not listed in the [schema](http://json.schemastore.org/template) though.

**Comment by marcusien** [comment]
Didn't know what you provided ☺️

In my case I always used what's listed on this link. Don't hesitate to take a look
https://github.com/dotnet/templating/wiki/"Runnable-Project"-Templates

**Comment by matkoch** [comment]
I'll leave this open.

**Comment by mlorbetske** [comment]
https://github.com/SchemaStore/schemastore/pull/493 has been merged which should take care of this.
