### ISSUE TITLE
Provide template names for command line completion.

### ISSUE THREAD

**Issue by peterhuene** [dotnet/templating#1539]
## Steps to reproduce

1. `dotnet complete 'dotnet new '`.

## Expected  behavior

Acceptable template names should be displayed in the output.

## Actual behavior

Template names are not output as suggestions (for `release/2.1.4xx` branch on `dotnet/cli`).

## Discussion

A partial list of templates is displayed for 2.1.300 and older versions of the .NET Core SDK.  This is because those versions of the CLI used a "fake" command line parser that redefined (poorly) what options were supported by the `new` command.  This fake parser had a hard-coded list of template names to suggest.

In the `release/2.1.4xx` branch, we're about to make a change (see https://github.com/dotnet/cli/pull/9294) that properly forwards completion requests to the actual parser defined here by the templating engine.  This prevents us from having to duplicate the supported command line options.  However, we will lose the list of template names to suggest.

If possible, we would like the command line parser defined for the `new` command to implement a call to `WithSuggestionsFrom` on the argument for the command defined by `CreateNewCommandWithoutTemplateInfo`:

```
...
Accept.ZeroOrMoreArguments().WithSuggestionsFrom(arg => GetTemplateShortNamesStartingWith(arg))
...
```

As an example, I'd expect `dotnet complete 'dotnet new r'` to output:

```
razor
razorclasslib
react
reactredux
```

## Environment data
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.400-preview-008861
 Commit:    defbeb6f1c

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /Users/peterhuene/src/cli/bin/2/osx-x64/dotnet/sdk/2.1.400-preview-008861/

Host (useful for support):
  Version: 2.1.0-rtm-26508-02
  Commit:  4a59ba1833

.NET Core SDKs installed:
  2.1.400-preview-008861 [/Users/peterhuene/src/cli/bin/2/osx-x64/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rtm-30752 [/Users/peterhuene/src/cli/bin/2/osx-x64/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rtm-30752 [/Users/peterhuene/src/cli/bin/2/osx-x64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0-rtm-26508-02 [/Users/peterhuene/src/cli/bin/2/osx-x64/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by mlorbetske** [comment]
This will be a bit more complicated than the example code above suggests. The setup done in https://github.com/dotnet/cli/blob/670dcedba2da87d33b030dfed0e963e301323a84/src/dotnet/commands/dotnet-new/NewCommandShim.cs needs to be performed by whatever gets invoked here https://github.com/dotnet/cli/pull/9294/files#diff-4d789304b7cfe2b0f4aad8e7fc4bc96dR47 (probably creating a new method on `NewCommandShim` to get that all configured). Beyond that, `CommandParserSupport` will need to be reworked to take in the necessary stuff to produce the template list (logic that's currently in `New3Command` indirectly uses `CommandParserSupport` - making this a bit circular). Going a step further, template options should also be made available for completion, not just their names - this combination of things leads me to believe that we need to be looking at reworking some of the initialization flow to make this happen & likely won't be a quick thing to do.

@seancpeters do you agree?

**Comment by seancpeters** [comment]
Yes, this sounds about right. One thing we'll have to decide regarding template name completion is whether to just include the "short name" values, or also to include the "name" values. Also for the short names, we'll need to decide whether to include in the completion list, all of the short names for each template, or just the ones that get displayed in the list output, e.g. `dotnet new -l` - this is related to #1431 which allows a template to define multiple short names, and the way we display & resolve them.

**Comment by mlorbetske** [comment]
Looking at this more, beyond template names and the system level switches, I don't think completion for templates can fully work in this way.

We end up reconstructing the Command object internally multiple times during what we consider to be our parsing phase in order to add the switches specific to the situation (no template/one template/set of templates), some switches may not be used together (different templates in a group can differ in switches that disambiguate between the two, but are considered all to be top level options of the command).

What we really end up needing to make this a compelling experience is either a way of defining the set of options available on a command after the command's argument has been parsed already or to just give us the raw arguments and let us give back the set of completions without requiring us to return an instance of Command.

@peterhuene any thoughts on possible solutions?

**Comment by mlorbetske** [comment]
Even for template names, we need to actually bootstrap the engine so that it can read its configuration, which'll take some time. The class you're using isn't intended to be used directly, it's a support class for the stateful parser class that's instantiated by the engine during initialization.

**Comment by donJoseLuis** [comment]
This issue was last touched some years ago.  We are working on a new delivery road map.  Please reopen if this is something we want & we'll properly assess its' priority compared to other work aimed at improving the overall templating UX.
