### ISSUE TITLE
rename a file extension

### ISSUE THREAD

**Issue by maracuja-juice** [dotnet/templating#1546]
In my Project Template there's a `nuspec` file that (for whatever reason) isn't included in the NuGet package I make. 
Therefore I renamed the `file extension` to `SpecialNuspecFile` and added a new constant parameter:
```
		"nuspecFile": {
			"type": "generated",
			"generator": "constant",
			"parameters": {
				"value": "nuspec"
			},
			"replaces": "SpecialNuspecFile"
		}
```
But when executing the template the `SpecialNuspecFile` extension isn't replaced with `nuspec` as expected.

How can I rename the file extension with a generated parameter?

**Comment by maracuja-juice** [comment]
I tried it with `fileRename` now aswell but I get the same result.

```
		"nuspecFile": {
			"type": "generated",
			"generator": "constant",
			"parameters": {
				"value": "nuspec"
			},
			"fileRename": "SpecialNuspecFile"
		}
```

**Comment by seancpeters** [comment]
@maracuja-juice - The generated symbols don't currently support file rename, which is why this isn't working. But there's another way to do it. If you setup a rename in the template's "sources" section, it'll accomplish what you want. 

For example, if the file that should have the extension "nuspec" in your template source is named "MyConfig.SpecialNuspecFile", the source rename should be setup like this:
```
  "sources": [
    {
	  "modifiers": [
	    {
		  "rename": { "MyConfig.SpecialNuspecFile": "MyConfig.nuspec" }
		}
	  ]
	}
  ],
```

**Comment by maracuja-juice** [comment]
@seancpeters That looks good.
It seems that this rename is applied AFTER the fileRename is. 
Therefore I need to use a value that is supplied via a symbol in the rename. How can I do that?

**Comment by horseyhorsey** [comment]
@maracuja-juice Did you figure out sending a value to the "MyConfig.nuspec"?

My file gets renamed like {myfile}.txt

**Comment by maracuja-juice** [comment]
@horseyhorsey As a user of the template do you need to give your example parameter to the template so it takes effect?

**Comment by maracuja-juice** [comment]
@horseyhorsey As a user of the template do you need to give your example parameter to the template so it takes effect?

**Comment by horseyhorsey** [comment]
Not sure what you mean but I did have to use "dotnetcli.host.json" as with "template.json"

    {
        "$schema": "http://json.schemastore.org/dotnetcli.host",
        "symbolInfo": {
            "className": {
                "longName": "className",
                "shortName": "c"
            }
        },
        "usageExamples": [
            "--className \"Your Class Name\""
        ]
    }

**Comment by horseyhorsey** [comment]
I had to use the extra "dotnetcli.host.json". Without that it wouldn't give me the optional parameter in the CLI.

**Comment by maracuja-juice** [comment]
But does it also rename the file extension? Because from your code I can't find the part where you specify the new file extension.

**Comment by maracuja-juice** [comment]
@seancpeters Is there a way now to either have a rename that is applied before fileRename is or use a symbol in the method that you are suggesting.

**Comment by maracuja-juice** [comment]
We now have a Powershell in place that does this for us.
