### ISSUE TITLE
Show version number of installed packages

### ISSUE THREAD

**Issue by maracuja-juice** [dotnet/templating#1548]
With 

```
dotnet new -u
```

I can see all my installed templates but not their version. How can I see their version number?
Could you add this to -u aswell or a new parameter?

**Comment by maracuja-juice** [comment]
How can I get this behaviour? I still don't see the version of the package with `-u`

**Comment by mlorbetske** [comment]
@maracuja-juice that's odd, could you post the output of `dotnet new --debug:version` please?

**Comment by maracuja-juice** [comment]
Seems like I have an old version. Not sure how exactly I can update it.

```
 Version:    1.0.2-beta4
 Commithash: 2b52e96b5737d86c215e0d80483d48c4b107c2a8
```

(With `dotnet --version` it shows `2.2.101`)
