### ISSUE TITLE
Projects created by the templating engine aren't "considered" new projects

### ISSUE THREAD

**Issue by davkean** [dotnet/templating#1550]
(This is the same as https://github.com/dotnet/templating/issues/863, but I cannot reopen it because I don't have rights)

This is still occurring in Version 15.8.0 Preview 3.0 [27731.3004.d15.8stg].

CPS's ProjectFactory isn't being told that the new project being passed it from the templating engine is a new project. 

This is causing it to skip all the "new project" paths in the factory.

I'm not sure how the templating engine creates us, below is the stack (sorry, not doing native debugging, so native frames are missing), but we're not being passed the __VSCREATEPROJFLAGS.CPF_CLONEFILE flags which is what we use to indicate that's it a new project:

```
>	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectFactory.CreateProject(string fileName, string location, string name, uint flags, ref System.Guid projectIid, out System.IntPtr project, out int canceled) Line 277	C#
 	Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.VisualStudio.Shell.Flavor.FlavoredProjectFactoryBase.Microsoft.VisualStudio.Shell.Interop.IVsProjectFactory.CreateProject(string fileName, string location, string name, uint flags, ref System.Guid projectGuid, out System.IntPtr project, out int canceled)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Microsoft.VisualStudio.TemplateEngine.UI.dll!Microsoft.VisualStudio.TemplateEngine.TemplateCreatorBase.CreateAsync(EnvDTE.Solution solution, Microsoft.VisualStudio.TemplateEngine.Contracts.ITemplateCreationInteractions interactions, System.Collections.Generic.IReadOnlyDictionary<string, string> passthroughParams, string baseline)	Unknown

```

**Comment by seancpeters** [comment]
@phenning - I believe this would be part of the VS integration of dotnet/templating.

**Comment by mlorbetske** [comment]
From an offline conversation with @phenning, it looks like this is the code we're using to add the project to the solution - I'm unclear on how we could change this to pass that flag. I'll send you a mail with a link to the code & add Phil in case you've got any thoughts on what we should be doing differently.

```
solution.AddFromTemplate(proj, Path.GetDirectoryName(proj), Path.GetFileNameWithoutExtension(output.Path));
```

**Comment by donJoseLuis** [comment]
Need to talk to the VS integration team about this one

**Comment by DavidKarlas** [comment]
Hey @phenning is this still an issue?

**Comment by phenning** [comment]
I have no idea what the underlying issue is here or what is broken. In any event, the API provided by the solution has no way to pass this flag. 

Closing, as there is nothing actionable to do here.
