### ISSUE TITLE
Issue with location of Dockerfile when using template

### ISSUE THREAD

**Issue by LeighF51** [dotnet/templating#1551]
Hi,

I have a template with 3 projects (one of them being a docker project) that are setup in a template. When creating a new solution from the template the docker file in my service project is included but it is stored away in a set of folders rather than being left at the root of the project it should be part of.

I've tried including a copyOnly section in my template.json but it doesn't seem to work with the DockerFile.

```
{
  "author": "Author",
  "classifications": [],
  "description": "Service Package Template, generates a set of projects that can be bundled up into a nuget package for service usage",
  "name": "Service Template (.NET Core)",
  "defaultName": "Test",
  "identity": "Sample.Template.CSharp",
  "groupIdentity": "Sample.Template",
  "tags": {
    "language": "C#",
    "type": "project"
  },
  "shortName": "NetCoreServiceTemplate",
  "sourceName": "NetCoreServiceTemplate",
  "guids": [
	"{05DCBF2B-411C-45E0-B5F2-7E8E3120670F}",
	"{73E50470-2CD5-4CD0-89CB-E54FA997F56B}"
  ],
  "primaryOutputs": [
    {
      "path": "TestServiceTemplate\\TestServiceTemplate.csproj"
    },
	{
      "path": "TestServiceTemplateLibrary\\TestServiceTemplateLibrary.csproj"
    }
  ],
  "sources": [
	{
		"include":[
			"**/*"
        ],
		"exclude": [
			"**/[Tt]estServiceTemplateVsix/**",
			"**/*.sln",
			"**/.template.config/**"
		],		
		"copyOnly": [
			"**/DockerFile"
		]
	}  
  ]
}
```
![image](https://user-images.githubusercontent.com/8517007/40987817-6f98420e-68e1-11e8-8d7d-3de8d860be9d.png)
As the image above shows the window on the left displays the path where the file gets stored when creating a solution using the template and the one on the right shows the root of the project where the dockerfile should be based on the location it was at in the template.

I'm not sure if the issue with the dockerfile being stored elsewhere is due to it not having an extension?
Is there a way of me controlling where this file gets stored to in the projects generated from a template?

**Comment by seancpeters** [comment]
Could you post some info on the directory structure of your template source, including:
- the fully expanded path to the docker file in the source
- the location of the template.json file

The existence or lack of a file extension shouldn't affect the output location of any files.

**Comment by LeighF51** [comment]
@seancpeters 

In the source the dockerfile can be found at the root of the service template project i.e. C:\Users\fyfieldl\source\Templates\ServiceTemplate\NetCore\NetCoreServiceTemplate - from here I have the dockerfile, csproj etc 
![image](https://user-images.githubusercontent.com/8517007/41022297-fb6f1922-6960-11e8-943c-a72269c5927f.png)

This structure for the docker file can also be seen in the template in the solution view 
![image](https://user-images.githubusercontent.com/8517007/41022378-49042f92-6961-11e8-996c-1cd7dbf074ad.png)

The template.json file is stored one directory up from the service template itself (as it's a multi project template) inside the .template.config folder
![image](https://user-images.githubusercontent.com/8517007/41022329-1d3892fe-6961-11e8-9c2e-9f322f1e162a.png)
![image](https://user-images.githubusercontent.com/8517007/41022351-2bf6801c-6961-11e8-932b-8c3487b0fb3b.png)

Hope this is enough info

**Comment by LeighF51** [comment]
@seancpeters 

You can find a version of the template at https://github.com/LeighF51/ServiceTemplate

Only invoking the template from VS, not using dotnet new at all

**Comment by mlorbetske** [comment]
Taking a look at the nupkg generated when building the solution in the repo, it looks like the docker file is being placed at a different location than expected.

To get the behavior you expect, the file would need to be located at
Content\NetCoreServiceTemplate\Dockerfile

But it's actually located here instead
Content\NetCoreServiceTemplate\Dockerfile\NetCoreServiceTemplate\Dockerfile

It looks like this is being done as part of the SideWaffle build process (nothing's jumping out as being a customization that'd have this effect), I'll move this issue to that repo.

**Comment by mlorbetske** [comment]
This issue was moved to ligershark/sidewafflev2#34
