### ISSUE TITLE
Move files during template creation and maintain project rename

### ISSUE THREAD

**Issue by Plac3hold3r** [dotnet/templating#1553]
Hi

I'm struggling to find documentation describing if it is possible to move files and folder during template creation while maintaining the `sourceName` auto rename of the project and folder names. Is this possible with dotnet templating?

The template that I have been working on, can be found on [GitHub](https://github.com/Plac3hold3r/MvxScaffolding). The use case I'm trying to cater for relates to an idea to support multiple projects structure types, for example (Related to Xamarin apps), a blank app, a single view based app or an app with a navigation menu. 

Initially, I was thinking about including all the different types in a single project and excluding the files that do not relate to the chosen template option. However, this creates a bit of an issue as I lose the ability to test the template except through creating the output via the dotnet new cli. So I thought perhaps I could create a separate project on disk and move the chosen template option into the correct folder location and skip the others.

**_Example_**

SourceName = "MvxNative"

```Text
Structure on disk in template

./src/SingleView/MvxNative.Droid/{{ other files }}
./src/SingleView/MvxNative.Droid/MvxNative.Droid.cspoj
./src/NavigationMenu/MvxNative.Droid/{{ other files }}
./src/NavigationMenu/MvxNative.Droid/MvxNative.Droid.cspoj
```

`dotnet new mvxnative -n "MyApp" --scaffold-type "navigation-menu"`
```Text
Structure after move, but before rename

./src/MvxNative.Droid/{{ other files }}
./src/MvxNative/MvxNative.Droid/MvxNative.Droid.cspoj

Structure after move and rename

./src/MyApp.Droid/{{ other files }}
./src/MyApp.Droid/MyApp.Droid.cspoj
``` 

Perhaps there is an alternative, any help/advice would be greatly appreciated.

**Comment by seancpeters** [comment]
If I understand your question correctly, the answer is yes, you can do both at the same time, as long as you have a new enough version of dotnet (I know 2.1.3 is sufficient). Some older versions had a bug where only 1 type of renaming operation would apply to a given file. In the example below, both the source name handling, and moving of files are handled by rename operations.

I setup a minimal template that I think accomplishes what you're asking for - in terms of file renames and moves. Here is the relevant parts of the template.json:
```
  "sourceName": "Company.ConsoleApplication1",
  "sources": [
    {
	  "modifiers": [
	    {
	      "condition": "(Pivot == \"Single\")",
		  "rename": { "SingleView/": "" },
		  "exclude": [ "src/NavigationMenu/**/*" ]
	    },
		{
		  "condition": "(Pivot == \"Navigation\")",
		  "rename": { "NavigationMenu/": "" },
		  "exclude": [ "src/SingleView/**/*" ]
		}
	  ]
	}
  ],
  "symbols": {
    "Pivot": {
	  "type": "parameter",
	  "description": "Demonstrates move & rename",
	  "datatype": "choice",
	  "choices": [
	    {
		  "choice": "Single",
		  "description": "Use the contents of SingleView"
		},
		{
		  "choice": "Navigation",
		  "description": "Use the contents of NavigationMenu"
		}
	  ],
	  "defaultValue": "Single"
	},
  },
```

And here is the file / directory structure of the source template:
![moverename](https://user-images.githubusercontent.com/20912881/41183404-200d3b46-6b6a-11e8-9806-9c7a7feb4a35.PNG)

**Comment by Plac3hold3r** [comment]
Thank you @seancpeters that works perfectly.
