### ISSUE TITLE
dotnet new --install can cause deadlocks

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/templating#1557]
I run unit tests which execute `dotnet new --install` and then other commands to create, build and run my project template code to see if it compiles.

XUnit runs tests in parallel by default. When two `dotnet new --install` commands are run in parallel, deadlocks can occur and the process hangs. I'd love for this to be fixed, so I can run tests in parallel.

**Comment by mlorbetske** [comment]
There’s a mutex that gets acquired on startup that’s meant to prevent hive corruption from multiple writers, it seems likely that this is related to what’s causing the trouble. To enable test parallelism we’ve had folks specify a configuration hive (this also can be used to ensure a known state during the test) with the --debug:custom-hive parameter which takes in a path to use for the configuration. If you generate a name for the hive to use in each test & specify it in each call to dotnet new in the tests, this should allow parallel test runs, if not, it’ll need to obtain the mutex to ensure that the run is working with a stable configuration set.

@seancpeters might be able to point you to a concrete example of its usage.

**Comment by seancpeters** [comment]
We use the --debug:custom-hive flag in this class: 
https://github.com/dotnet/templating/blob/d18c42fe62ca500bfd1afbaa7a6382180dff52ef/tools/BaselineComparer/BaselineComparer/CustomHiveCoordinator.cs
which is part of a tool contained in this repo that we use for testing changes to the engine.

It might be useful for your purposes, although the TryCreateTemplateData method is somewhat specific to our tests, and should probably be outside this class.

Perhaps we should also create a debug flag hat allows creating a custom hive without installing any templates.

**Comment by RehanSaeed** [comment]
Sounds like that will help me get around the deadlock problem. Any plans to fix it when not using `--debug:custom-hive`?

**Comment by donJoseLuis** [comment]
This issue was last touched some years ago.  We are working on a new delivery road map.  Please reopen if this is something we want & we'll properly assess its' priority compared to other work aimed at improving the overall templating UX.
