### ISSUE TITLE
F# Classlibrary Template Default Encoding Isn't Unicode

### ISSUE THREAD

**Issue by liboz** [dotnet/templating#1565]
When creating a new F# classlibrary (other projects/templates may have this issue as well but I didn't test it), the first library file `Library1.fs` that is created does not by default have Unicode encoding. For me with Japanese regional settings, it is encoded in Shift-JIS. This is in contrast to the default library file of a C# library, which is by default encoded with UTF-8 with signature.

Any ideas as to why this is?

More information: https://github.com/Microsoft/visualfsharp/issues/5159

**Comment by abelbraaksma** [comment]
I think the programmes at the time just forgot to use the invariant culture and that it then defaulted to whatever local culture is available. Either way, this was a good find and an accident waiting to happen, I don't know how it needs to be fixed, but imo it's definitely a bug.

**Comment by mlorbetske** [comment]
The associated PR for this has been merged
