### ISSUE TITLE
Symbols are not being published to internal symbol server

### ISSUE THREAD

**Issue by davkean** [dotnet/templating#1574]
The symbols for the following dlls are not being published to internal symbol server. This makes it impossible to debug code coming from these dlls:

Micorsoft.TemplateEngine.Orchestrator.RunnableProjects.dll
Microsoft.TemplateEngine.Core.dll
Microsoft.TemplateEngine.UI.dll
Microsoft.TemplateEngine.IDE.dll
Microsoft.TemplateEngine.Wizard.dll

I'm on build Version 15.8.0 Preview 3.0 [27807.3004.d15.8stg], but it appears to be a problem for all builds.

When these symbols are being published, please also make sure the source files can be pulled automatically via VSTS, or via [Source Link](https://github.com/ctaggart/SourceLink).

**Comment by mlorbetske** [comment]
Re-opening since the build configuration update to actually publish the PDBs is still in progress

**Comment by davkean** [comment]
Was going to ask that... :)

**Comment by mlorbetske** [comment]
Just updated the microbuild definition to push the symbols, should be good to go with the next release. There's still work to do on the VS side of things, but that's tracked in the TFS bug. Thanks!
