### ISSUE TITLE
Angular 6 Update

### ISSUE THREAD

**Issue by mbeckenbach** [dotnet/templating#1592]
Hi, 

do you have plans to upgrade to angular 6 anytime soon?
The project file and some dependencies have changed there.

Best regards

**Comment by mlorbetske** [comment]
This issue was moved to aspnet/templating#586

**Comment by mlorbetske** [comment]
Moving this to where the ASP.NET template content is maintained

**Comment by blogcraft** [comment]
Any support for Angular 10 or 11? Cant update stock angular template cause module-map-ngfactory-loader no longer supported since ng9.
