### ISSUE TITLE
Error when source file is missing final end-of-line

### ISSUE THREAD

**Issue by dsyme** [dotnet/templating#1593]
I'm leaving this here for people in case they need to search for it

I was creating a template and got this error when using `dotnet new`:

```
Template "ABC" could not be created.
Error while processing file DEF
Non-negative number required.
Parameter name: offset
```

The problem appears to be that the input file was missing a final end-of-line character

**Comment by mlorbetske** [comment]
@dsyme I'm not clear on why this was closed, if this is something you're running in to, we should fix it

**Comment by dsyme** [comment]
I didn't have time to make a repro, if you can find one easily then it would be good to fix it

**Comment by mlorbetske** [comment]
Tracking this as #1641 as it includes a repro
