### ISSUE TITLE
dotnet new --langVersion=latest

### ISSUE THREAD

**Issue by vijayrkn** [dotnet/templating#1595]
Creating an issue corresponding to this developer community ticket
https://developercommunity.visualstudio.com/content/problem/279130/dotnet-new-langversionlatest.html

from : David Bond 
I would like to be able to execute the following (or similar):
dotnet new console --langVersion=latest

**Comment by mlorbetske** [comment]
This should just be a change to the template content to include the language version and set it to the value of the parameter if it was specified. This, however, can’t be a global change, it’d need to be made on a template by template basis and raises the question of which templates to bring the change to (specifically, which versions of them).
