### ISSUE TITLE
--nuget-source missing

### ISSUE THREAD

**Issue by Marfusios** [dotnet/templating#1598]
Hello,

creating an issue for #1386 (@mlorbetske)
I'm trying to install a template from different nuget source, but with no success. 
That new parameter `--nuget-source` is missing. 

```
λ dotnet --version
2.1.201

λ dotnet new --nuget-source http://mynugetserver:5033 -i "Alza.Konzole.Templates.Microservice.Simple::*"
Invalid input switch:
  --nuget-source
  http://mynugetserver:5033
Run dotnet new --help for usage information.
See https://aka.ms/dotnet-install-templates to learn how to install additional template packs.
```

**Comment by mlorbetske** [comment]
What version of the dotnet CLI are you using? If you could also let us know the output of dotnet new —debug:version, that’d be great.

**Comment by Marfusios** [comment]
Version: 2.1.201
Debug:
```
λ  dotnet new --debug:version
Template Instantiation Commands for .NET Core CLI

 Version:     1.0.0-beta3-20171117-314
 Commit Hash: 71c5c12c4dbd25c35776431640238c29e01999e8
```

**Comment by mlorbetske** [comment]
It seems that the version of the engine that's included in that build of the dotnet CLI is about a month older than the change that added that feature. It appears that dotnet SDK that includes this feature is 2.1.301 (obtainable here https://www.microsoft.com/net/download/)
