### ISSUE TITLE
Missing documentation for Regex Macro

### ISSUE THREAD

**Issue by TiagoOliveiraMarques** [dotnet/templating#1602]
I was trying to check how to use the regex macro but the only documentation I found is here: https://github.com/dotnet/templating/wiki/Available-Parameter-Generators, which is incomplete.

Right now i'm just checking the code to see how this works but this is a bad developer experience.
Is there any other documentation available? 

Thanks in advance.

**Comment by mlorbetske** [comment]
Unfortunately I don't have a great source for docs at the moment. Hopefully within the next couple of weeks I'll get some time to update a bunch of items on the wiki & get the schema back to current.

**Comment by mlorbetske** [comment]
Here's an example using the regex macro

```
{
    "author": "Mike Lorbetske",
    "classifications": [ "Examples" ], 
    "name": "Macro Examples",
    "identity": "Microsoft.TemplateEngine.Examples.Macros",         
    "shortName": "macroexamples",
    "tags": {
      "language": "C#"
    },
    "sourceName": "Template.1",
    "preferNameDirectory":"true",
    "symbols":{
      "message": {
        "type": "parameter",
        "defaultValue": "Hi There!",
        "replaces":"Hello World!"
      },
      "regexExample": {
        "type": "generated",
        "generator": "regex",
        "dataType": "string",
        "replaces":"A different message",
        "parameters": {
        "source": "message",
            "steps": [
                { 
                    "regex": "^test",
                    "replacement": "[Replaced]"
                },
                { 
                    "regex": "test$",
                    "replacement": "[/Replaced]"
                }
            ]
        }
      }
    }
  }
```

**Comment by mlorbetske** [comment]
I've updated the wiki and [submitted a PR to update the schema](https://github.com/SchemaStore/schemastore/pull/493) to bring it in line with the current capabilities. Thanks again for bringing this to our attention.

**Comment by sakopov** [comment]
This seems incredibly convoluted. Could you expand on what this actually replaces and what the message parameter have to do with the replacement?
