### ISSUE TITLE
#if blocks in code are ignored

### ISSUE THREAD

**Issue by jimbobbennett** [dotnet/templating#1610]
**To reproduce**
Create a template for an app with code contained inside a #if block.
Create an app from the template

**Expected**
The created app should contain all the code including the #if block

**Actual**
Code inside the #if block is ignored.

**To reproduce**

Create an Elmish.XamarinForms app using the [0.14.4 NuGet package](https://www.nuget.org/packages/Elmish.XamarinForms.Templates/0.14.4). The core project App.fs file should contain code inside two #if blocks - APPSTART and DEBUG, but this code is missing from the output. You can see the expected code at https://github.com/fsprojects/Elmish.XamarinForms/blob/master/templates/content/blank/NewApp/NewApp.fs

**Comment by mlorbetske** [comment]
Since `#if` is processed by the engine, you'll want to turn off that processing in the template content. You can do this by adding comments

(Taken from #1497)
```
//-:cnd:noEmit
#if STUFF
...
#endif
//+:cnd:noEmit
```
