### ISSUE TITLE
Restore packages postAction uses original primary output instead of renamed one

### ISSUE THREAD

**Issue by flcdrg** [dotnet/templating#1622]
Given a template.json similar to this:
``` json
{
    "$schema": "http://json.schemastore.org/template",
    "author": "David Gardiner",
    "classifications": [
        "Common",
        "Console"
    ],
    "identity": "TemplateBug.CSharp",
    "name": "Template Bug Repro",
    "shortName": "template-bug-repro",
    "preferNameDirectory": true,
    "tags": {
        "language": "C#",
        "type": "project"
    },
    "primaryOutputs": [
        {
            "path": "Client.sln"
        }
    ],
    "symbols": {
        "clientPrefix": {
            "type": "parameter",
            "isRequired": true,
            "description": "Client prefix",
            "replaces": "ClientPrefixTemplateSymbol",
            "fileRename": "Client"
        }
    },
        "postActions": [
        {
            "description": "Restore NuGet packages required by this project.",
            "manualInstructions": [
                {
                    "text": "Run 'dotnet restore'"
                }
            ],
            "actionId": "210D431B-A78B-4D2F-B762-4ED3E3EA9025",
            "continueOnError": true
        }
    ]
}
```
and an existing file "Client.sln", when this template is used, it correctly renames Client.sln to the value supplied to the clientPrefix symbol, but the dotnet restore is run with "Client.sln"

```
C:\tmp\sample> dotnet new template-bug-repro --clientPrefix=Blah
The template "Template Bug Repro" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on C:\tmp\sample\Client.sln...
MSBUILD : error MSB1009: Project file does not exist.
Switch: C:\tmp\sample\Client.sln

Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'
```

**Comment by mlorbetske** [comment]
Could you provide the output of `dotnet new --debug:version` please? This sounds like something that @seancpeters fixed not too long ago where not all file renames were getting applied to post-actions.

**Comment by flcdrg** [comment]
Template Instantiation Commands for .NET Core CLI

 Version:     1.0.2-beta3
 Commit Hash: c0f84b79c361e961a699a5c70d255db11c0d411c

**Comment by mlorbetske** [comment]
Thanks! The fix should have been in that build, so it looks like something else is in play here, I’ll investigate. #1625 should happen to fix it for this case since it uses the full input-output map for post-actions, but from what you’re seeing it looks like the wrong value is present in PrimaryOutputs on the creation result, which can cause other problems.

**Comment by mlorbetske** [comment]
Out of curiosity (unrelated to the issue itself), why have a symbol to rename the solution and presumably project prefix and not use sourceName?

**Comment by flcdrg** [comment]
I don't think I'd even noticed sourceName. I'll check it out!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mlorbetske** [comment]
Ah, it looks like the change I mentioned didn't actually make it in to that build. Trying with latest, it doesn't repro, but with a CLI carrying those bits it does. However, in looking at the code that handles that to try to figure out what's going on, I discovered that this would still repro if there were multiple sources involved. I'm updating #1625 to contain that fix as well. Thanks!
