### ISSUE TITLE
AddReferencePostActionProcessor for specific project

### ISSUE THREAD

**Issue by flcdrg** [dotnet/templating#1623]
In a template which has multiple projects, is it possible to use AddReferencePostActionProcessor to add a reference to a package to just one specific project?

**Comment by mlorbetske** [comment]
Unfortunately, there doesn't seem to be, I've submitted #1625 to fix this, which should make its way in to the CLI for .NET Core 2.2. You'll be able to include `targetFiles` in the post-action's `args` which is a semicolon delimited list of globs (matching files in the template source) that select the files you'd like to add the reference to. The action will appropriately select the matching output file to actually perform the action on.
