### ISSUE TITLE
Add missing required parameter "value" to ConstantMacro schema

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/templating#1626]
The `value` parameter for the Constant Macro isn't included in the schema

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by vlada-shubina** [comment]
`value` parameter for the constant macro has been added to the schema
