### ISSUE TITLE
Misleading help text for --no-https option

### ISSUE THREAD

**Issue by scottaddie** [dotnet/templating#1636]
Execute the `dotnet new mvc --help` command, and you'll see the following help text for the `--no-https` option:

> Whether to turn off HTTPS. This option only applies if IndividualAuth or OrganizationalAuth are not being used.

This text may lead some to believe that `IndividualAuth` and `OrganizationalAuth` are valid values for the `--auth` option. Both `--auth IndividualAuth` and `--auth OrganizationalAuth` result in error messages.

I propose that the help text change to the following:

> Whether to turn off HTTPS. This option only applies if Individual, IndividualB2C, SingleOrg, or MultiOrg aren't being used.

/cc: @seancpeters

**Comment by mlorbetske** [comment]
The docs for the template specific switches come from the templates themselves, this would be something to file on aspnet/templating

**Comment by scottaddie** [comment]
Thanks for the info, @mlorbetske! I'll move it over there.
