### ISSUE TITLE
Post Actions user confirmation should accept french answer

### ISSUE THREAD

**Issue by ggirou** [dotnet/templating#1638]
On Post Actions user confirmation, it asks confirmation in french, accepting `O` or `N` as answer.
It doesn't work when I type `O` but still works with english answer `Y`.

Full logs below:
```
Traitement des actions postcréation...
Le modèle est configuré pour exécuter l'action suivante :
Description : Restore NuGet packages required by this project.
Instructions manuelles : Run 'dotnet restore'
Commande réelle : dotnet restore
Voulez-vous exécuter cette action (O|N) ?
O
Entrée non valide : "O". Entrez O ou N.
Y
Exécution de la commande 'dotnet restore'...
Commande réussie.
```

**Comment by mlorbetske** [comment]
Thanks for pointing this out. The intention here was to leave Y and N unlocalized, but perhaps with a localized legend (ex. (Y=oui|N=non)). Would a solution like this make sense or do you feel it’s more appropriate to just accept the first letter of the yes/no for the current language?

**Comment by ggirou** [comment]
I think it's better to be fully localized including Y / N answers

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by vlada-shubina** [comment]
We will adjust localized strings for this output to indicate that expected answers are Y for yes and N for no for all languages. It is agreed not to make inputs itself localized, particularly due to it makes input difficult for non-Latin alphabet languages.
