### ISSUE TITLE
Unhandled Rejection (SyntaxError): Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by nickdb93** [dotnet/templating#1639]
Steps to reproduce:

Run the following commands:

`dotnet new react -n <SOME_NAME>`
`cd <SOME_NAME>`
`dotnet build`
`dotnet run`

Navigate to http://localhost:<PORT>/ then click on "Fetch Data".

This results in the following error appearing tin the browser:

```
Unhandled Rejection (SyntaxError): Unexpected token < in JSON at position 0
(anonymous function)
C:/<SOME_NAME>/ClientApp/src/components/FetchData.js:11

   8 |    this.state = { forecasts: [], loading: true };
   9 | 
  10 |    fetch('api/SampleData/WeatherForecasts')
> 11 |      .then(response => response.json())
  12 |      .then(data => {
  13 |        this.setState({ forecasts: data, loading: false });
  14 |      });
```

I assume this is due to the client app trying to fetch the list from `http://localhost:3000/api/SampleData/WeatherForecasts` (NPM server) when it should be attempting to get it from `http://localhost:5000/api/SampleData/WeatherForecasts` (.NET Web API server).

I did not alter any code before running this.

After this, I tried using the following code in `Startup.cs`
```
app.UseSpa(spa =>
            {
                spa.Options.SourcePath = "ClientApp";

                if (env.IsDevelopment())
                {
                    // spa.UseReactDevelopmentServer(npmScript: "start");
                    spa.UseProxyToSpaDevelopmentServer("http://localhost:3000");

                }
            });
```

I then navigated to `http://localhost:3000/fetchdata` and saw the same error.

I know that I can solve this by enabling CORS on the API side and hard-coding `FetchData.js:10` to be `fetch('http://localhost:5000/api/SampleData/WeatherForecasts')` , but I'm kind-of wondering how to get it working as intended.

I am running this on Windows 7 x64 in Google Chrome. The project is targeting `netcoreapp2.1` and using `Microsoft.AspNetCore.SpaServices.Extensions.2.1.1`

**EDIT**
I tried it on Windows 10 x64 as well, not changing and code from the template and got the same error.

**Comment by mlorbetske** [comment]
This issue was moved to aspnet/Templating#666

**Comment by mlorbetske** [comment]
@nickdb93 I’d suggest sharing your findings and question on the other issue, as the folks who know how best to handle this watch that repo & not this one (as the relevant template content is over there)
