### ISSUE TITLE
closing a condition block on the last line of file fails when followed by a blank line

### ISSUE THREAD

**Issue by williamdenton** [dotnet/templating#1641]
Part of my dotnet project template has a `yml` file for which i have had to add my own `SpecialCustomOperations` configuration so comments can be detected

`template.json:`
```j son
  "SpecialCustomOperations": {
    "*.yml" : {
      "Operations": [
        {
          "type": "conditional",
          "configuration": {
            "style": "line",
            "token": "#"
          }
        }
      ]
    }
  }
```

I have found that when an `#endif` statement is on  the last line of the file followed by a blank line (as posix requires) the `dotnet new` operation fails to initialise the template completely. However if the file has no blank lines or more than one blank line the template is processed correctly.

`my-config-file.yml:`
```yml

thing:
  - thing1
  - thing2
##if( condition )
  -- thing3
##endif

```

The error i get is
```
Template "DemoProject" could not be created.
Error while processing file /my-config-file.yml
Non-negative number required.
Parameter name: srcOffset
```

**Comment by williamdenton** [comment]
oops this appears to be a duplicate of https://github.com/dotnet/templating/issues/1593. Not sure how i missed that before posting this issue. I did try and search - honest!

**Comment by mlorbetske** [comment]
Thanks @williamdenton! We were looking for a repro for that issue & it seems you’ve found it, I’ll close the other issue in preference to this one since this is more actionable :)

**Comment by bartelink** [comment]
Can confirm this is sadly still an issue
```
dotnet --version
3.1.101
```

This is very painful as it falls foul of `.editorconfig` rules dictating [arguably!] redundant CR at EOF so it's easy to leave a template malformed

**Comment by donJoseLuis** [comment]
@grinrag , let's look at a fixing this in the short-term

**Comment by AR-May** [comment]
Fixed!

**Comment by RehanSaeed** [comment]
Will this come out in the .NET 5 timeframe?

**Comment by grinrag** [comment]
@RehanSaeed I will try my best to include this fix into .NET 5 release (5.0.100 mid of November). Also, feel free to join our Gitter channel, where you can ask questions like this (https://gitter.im/dotnet/templating).
