### ISSUE TITLE
dotnet new with no cache

### ISSUE THREAD

**Issue by livarcocc** [dotnet/templating#1645]
_From @jnevins-gcm on August 17, 2018 19:1_

## Steps to reproduce
run dotnet new -i MyTemplate::1.2.*

## Expected  behavior
Installs latest 1.2.* of MyTemplate

## Actual behavior
Uses cache and doesn't resolve latest version (sometimes). Have to clear %localappdata%\NuGet\v3-cache and re-run install of template to get latest.

Is there a way of forcing dotnet new -i to not use the cache? Like --no-cache with other dotnet commands?

_Copied from original issue: dotnet/cli#9856_

**Comment by mlorbetske** [comment]
To clean dotnet new’s cache, you can pass the --debug:reinit flag. To use a blank cache for a single operation, you can use --debug:ephemeral-hive. For an alternate cache location, you can use --debug:custom-hive {path}

**Comment by jnevins-gcm** [comment]
Says unknown project file when used at the end of a -i command

**Comment by mlorbetske** [comment]
Could you post the exact command line you've used? The different options have different implications on how they combine with other commands.

**Comment by mlorbetske** [comment]
Closing this since we don't have enough information to investigate & it's been some time since the last response.

**Comment by jannikbuschke** [comment]
I have probably a similar problem. When running `dotnet new -i MyPackage::0.6` which was just published and I get an error message indicating the nearest version is 0.5.
I tried 

`dotnet new -i MyPackage::0.6 --debug:reinit`  => no output, problem persists

`dotnet new -i MyPackage::0.6 --debug:ephemeral-hive` => MSBUILD : error MSB1009: Project file does not exist.

**Comment by mlorbetske** [comment]
@jannikbuschke where was the package published to? You'll want to make sure that the feed containing the new package is available in your global NuGet.config (which you can check with visual studio) or pass in the location of the feed to use to the `--nuget-source` parameter

**Comment by jannikbuschke** [comment]
Template was published to Nuget.org. It is found after some time (like 30-60 min) though its relativly fast (<5 min) visible on the nuget website.

**Comment by mlorbetske** [comment]
Thanks for the additional information. It sounds like the indexing process for serving the package may run at a different cadence than the package search. If you run in to this regularly, I'd suggest reporting the timing discrepancy on NuGet/Home

**Comment by vyckou** [comment]
actually running `dotnet new -i mytemplate::1.0.1 --debug:reinit`
and then running `dotnet new -i mytemplate::1.0.1`
did the job for me
