### ISSUE TITLE
regex generator - Enable usage of MatcherEvaluator for more complex substituations

### ISSUE THREAD

**Issue by ido-namely** [dotnet/templating#1646]
For example, uppercasing of letters cannot be done with \u in C#.
This requires a [MatchEvaluator](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.replace?redirectedfrom=MSDN&view=netframework-4.7.2#System_Text_RegularExpressions_Regex_Replace_System_String_System_Text_RegularExpressions_MatchEvaluator_System_Int32_System_Int32_) delegate.

**Comment by mlorbetske** [comment]
This is interesting, any proposal for how various match evaluators would be set up in config?

**Comment by mlorbetske** [comment]
@seancpeters

**Comment by ido-namely** [comment]
Perhaps you implement a method in a C# file and you reference that file?
The templating allows running scripts in postActions, so I wouldn't consider it a change in terms of security.

Also, this is mostly coming from C# regex not allowing to use \u \l to upper/lower case in substitutions so working on that functionality can be a good start as well :)

**Comment by ido-namely** [comment]
thanks for your input, I think what you wrote makes a lot of sense.
We could think of a post action to take care of some special substitutions.

Adding support for some extended constructs would be great.
A good start point would be  for the regex generator to have some args to indicate you want to naively upper/lower the input.
another one that could be useful for me (and hopefully for others) is to camelcase the input (e.g `some-word` to `SomeWord`

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by donJoseLuis** [comment]
Hello @ido-namely .  This issue evolved to the point you suggested...

1. post action support for special substitutions
1. support for extended constructs
1. RegEx generator accepting args to uppwer|lower-case input

Can you confirm you are still championing for these items?
If yes, we'll track each distinct ask in an issue.

**Comment by grinrag** [comment]
@ido-namely I am closing this issue since there is no much activity on it. If you feel you still need this feature, feel free to reopen it.
