### ISSUE TITLE
Templating rant - why don't you guys just use a git repo?

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/templating#1652]
From @jtheisen on August 25, 2018 in aspnet/templating#708

> I just figured that the new React template is not longer Typescript, despite them having the same name as they used to have, which prompts me to go on this rant.
> 
> The ASP.NET Core templates have been quite the time waster for me so far, much unlike the classic ASP.NET VS templates that hardly ever changed.
> 
> But really I just don't get why the templates are distributed through dedicated tools such as "dotnet new" to begin with - it makes important things you want to do with it quite hard:
> 
> You can't go back to a version you got from a previous version of dotnet new,
> you can't compare the version you get to what you got earlier so you don't really know why a template may behave differently now that you remember it did a month ago and
> you can't just fix a problem with the template and contribute it back to the community with a pull request right from the repo you checked out to use.
> You could do that if the template were just git repos offered for convenient cloning.
> 
> This git repo (aspnet/Templating) contains the templates, but it's not convenient to use as the starting point for a new app directly.
> 
> For that, the templates need to live at the root of the repo. Different templates could either be in different repos or in different branches of the same repo, depending on how similar they are. In the latter case, fixes could be easily merged.
> 
> The only drawback here is that "dotnet new" also performs some replacements. But that's a) not really that important and b) you could factor that out in a separate script if you really think it needs to be there.
> 
> End of rant.

**Comment by mlorbetske** [comment]
There's a lot here, so I'll try to unpack some of it

> But really I just don't get why the templates are distributed through dedicated tools such as "dotnet new" to begin with

Templates are often distributed as NuGet packages, available on NuGet.org, backed by Git repos that can be directly cloned an installed, while this isn't the case for ASP.NET currently, it's hopefully the general case.

> You can't go back to a version you got from a previous version of dotnet new,
you can't compare the version you get to what you got earlier so you don't really know why a template may behave differently now that you remember it did a month ago and
you can't just fix a problem with the template and contribute it back to the community with a pull request right from the repo you checked out to use.
You could do that if the template were just git repos offered for convenient cloning.

It's possible to roll back to the content carried by a previous version of the CLI by installing the templates from that CLI (you can find them at `%ProgramFiles%\dotnet\sdk\{version}\Templates`  - though it's definitely not discoverable) or by placing a global.json file that directs command to the `dotnet` CLI to a particular version of the tools. The reason for not shipping multiple versions of the content in each CLI was simply to prevent the download size from increasing as we move from release to release. If that creates a workflow problem, we can definitely start those discussions again to see if there's something better that can be done here.

> The only drawback here is that "dotnet new" also performs some replacements. But that's a) not really that important and b) you could factor that out in a separate script if you really think it needs to be there.

I'm not positive what you mean with this one, would you be able to elaborate on this please?

**Comment by tpetrina** [comment]
I think he means that alternative of running `git clone starter-template` is missing replacing namespaces with your desired project name. E.g. running `dotnet new react` inside folder named `mycoolproject` will propagate `mycoolproject` to thing like project names, namespace, `<title>`, etc.

And if that is the only benefit, then we might just as well use starter templates.

**Comment by mlorbetske** [comment]
That's fair. I think that's the distinction between sample content and templates though. dotnet/templating (dotnet new) supports much richer parameterization than that, however if that's not being leveraged, then the distinction between samples and templates does break down.

**Comment by tpetrina** [comment]
I am not sure how much parametrization SPA templates have. Also, I am not sure how much parametrization we want in those templates anyway.

It is an interesting proposition for sure.

**Comment by jtheisen** [comment]
@tpetrina Yes, that's what I meant. I would prefer starter templates.

In any case, thanks for the constructive feedback, @mlorbetske.

**Comment by mlorbetske** [comment]
Given that the feedback is more around providing samples, it may be best to continue the discussion back on the original issue as the content owners would need to drive that. Thanks again for the feedback, always a good to hear about how people are using the feature and what they'd like to see from it.
