### ISSUE TITLE
Warning when building .Net Core 2.2 F# mstets/xunit projects

### ISSUE THREAD

**Issue by richaverma1** [dotnet/templating#1653]
This is blocking 2.2 Preview 2 release -

Repro steps :
1. Create F# .net core mstest/xunit projects and  build
2. dotnet build succeeded with the warning:" A 'Program.fs' file can be automatically generated for F# .NET Core test projects. To fix this warning, either delete the file from the project, or set the <GenerateProgramFile> property to 'false'.”

![fsharpbuilderror](https://user-images.githubusercontent.com/19596695/45112993-082abb00-b0fe-11e8-8b7e-23b1d8a009af.png)
 
Workaround: Edit the .csproj file, set the <GenerateProgramFile> property to 'false'. i.e. :<GenerateProgramFile>false</GenerateProgramFile>

**Comment by seancpeters** [comment]
This issue was moved to dotnet/test-templates#11
