### ISSUE TITLE
Templates for publish profiles

### ISSUE THREAD

**Issue by dasMulli** [dotnet/templating#1654]
Not sure if this has been discussed already but:

Creating publish profiles is hard if you don't know much about them already. If you're on Windows and use VS, it's a no-brainer.
But without VS and e.g. on a Linux box, publishing an asp.net core application is hard (at least [they are documented](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/visual-studio-publish-profiles?view=aspnetcore-2.1&tabs=aspnetcore2x#the-kudu-service)), even though the SDK supports a variety of publish options via aspnet/websdk, but they require a publish profile.

A lot of this could be solved via templates for publish profiles, like `dotnet new azure-publish-profile`, `dotnet new pubxml --target filesystem` or similar.

Does it seem reasonable to approach this problem via templates?

**Comment by mlorbetske** [comment]
This has been discussed before (though I can't seem to find the issue where it was discussed) - the thinking at the time was that it might add noise to the list of templates. I'm not opposed to adding templates for this, but a few things will need to happen with this:

1. We'll need to figure out the relationship between this and the getting started profiles in WebSDK
2. We'll need to figure out where the template content should live
3. We'll need to determine whether these should be shipped in the dotnet CLI or as a package folks could install to get the functionality

@vijayrkn @Andrew-MSFT

**Comment by Andrew-MSFT** [comment]
cc: @AngelosP

**Comment by dasMulli** [comment]
Cross-linking https://github.com/dotnet/cli/issues/12163 for a discussion about potentiall not cluttering `dotnet publish` with too many options for new features but moving things to publish profiles, for which templates with publish options would become of importance.

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by vlada-shubina** [comment]
@KathleenDollard could you please check if this template should be considered?

**Comment by baronfel** [comment]
Will talk with @AngelosP about this and report back.

**Comment by sayedihashimi** [comment]
Seems like a good idea to me!

**Comment by baronfel** [comment]
After talking with Angelos a bit, publish profiles are both _variable_ and _complex_ - we wouldn't make a template for a 'raw' publish profile, instead we might make one for 'publishing to Azure Container Registry via .NET SDK native containers'. The schemas of these files are very open to change as well, and not something that the template engine team have full knowledge of. If any templates are to be made for publish profiles, they should come from @AngelosP/@vijayrkn and be ingested as part of the SDK, not defined here in a top-down manner.

**Comment by YuliiaKovalova** [comment]
Close as low priority.
The template content should be suggested by a team that owns publish profiles.
