### ISSUE TITLE
dotnet new -i doesn’t provide errors

### ISSUE THREAD

**Issue by jnevins-gcm** [dotnet/templating#1655]
When dotnet new -i MyPackage::1.2.3 finds no version match, it logs such to the output, installs and uses an old version it can find (1.2.2 let’s say), and exits with code 0. Further, it seems that nothing is written to stderr 

How can I identify a failure? I want to stop, not continue, if dotnet new can’t find a version that meets my spec.

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by vlada-shubina** [comment]
The issue will be fixed with https://github.com/dotnet/templating/issues/2745, when implementing that epic install-uninstall was majorly reworked. 

The error messages and the result of installation will be now shown to user.

Draft example:
```
> dotnet  new  -i Take.Blip.Client.Templates::0.50.10 --nuget-source https://api.nuget.org/v3/index.json
The following template sources will be installed:
  Take.Blip.Client.Templates, version: 0.50.10

Warning: Take.Blip.Client.Templates::0.5.10 is not found in NuGet feeds https://api.nuget.org/v3/index.json.
'Take.Blip.Client.Templates::0.50.10' could not be installed, the package does not exist.
```

**Comment by vlada-shubina** [comment]
Above was implemented and merged to main branch, closing.
