### ISSUE TITLE
"dotnet new" should offer a way to find a package ID for an installed template

### ISSUE THREAD

**Issue by livarcocc** [dotnet/templating#1659]
_From @gregbair on September 13, 2018 13:21_

When uninstalling a template pack, knowing the package ID (NUGET_ID in the docs) is required. However, there is currently no way to find out the package ID of an installed template, making uninstalling a template pack inconvenient.

_Copied from original issue: dotnet/cli#9994_

**Comment by seancpeters** [comment]
@gregbair @livarcocc - running `dotnet new -u` will list all of the installed packages, and the templates within each of those packages. The package names should be what's needed for uninstalling the pack.

Note: Running `dotnet new -u` on older versions of dotnet new will only list the package names, but not the templates in the packs.
