### ISSUE TITLE
Provide a url for finding more templates on `dotnet new --help`

### ISSUE THREAD

**Issue by livarcocc** [dotnet/templating#1660]
_From @KathleenDollard on September 13, 2018 23:26_

help for dotnet new obviously displays only the installed templates. 

Add a URL to either docs with a further link to NuGet or directly to NuGet to find additional templates. 

_Copied from original issue: dotnet/cli#10002_

**Comment by livarcocc** [comment]
I don't know if nuget can filter packages to package templates. And I don't believe there is one package type for such a thing. In any instance, I would move this issue to dotnet/templating. Could you do that?

**Comment by mlorbetske** [comment]
I know @sayedihashimi has a website for this. Sayed, would it be ok to include a link to that in the help text?

**Comment by sayedihashimi** [comment]
Yeah that would be fine, but let’s out it behind an aka.ms link in case we want to change the rest url in the future.

**Comment by sayedihashimi** [comment]
The current website is https://dotnetnew.azurewebsites.net. The code is at https://github.com/sayedihashimi/dotnet-new-web. I’m happy to transfer the App Service to MSFT or you can host it on another site.

**Comment by KathleenDollard** [comment]
@mairaw Maybe we should link to docs in help and then have the a link to templates there?

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by KathleenDollard** [comment]
This suggestion was a way to provide search capabilities prior to our other efforts on this. 

Search is for finding things that are not installed on the local machine. List is for listing what is installed (this is a convention across the CLI). 

Since we are now working on help, I am closing this issue.
