### ISSUE TITLE
Update help text for `dotnet new`

### ISSUE THREAD

**Issue by livarcocc** [dotnet/templating#1661]
_From @KathleenDollard on September 15, 2018 18:9_

## Current
```bash
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
````

## Proposed
```bash
  -l, --list          Lists templates containing the specified template name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
````

## Problem
Name usage differs in these two adjacent items. In one case, it is the name of the result and the other the name of the template. 

_Copied from original issue: dotnet/cli#10011_

**Comment by seancpeters** [comment]
@kathleendollard - For the command `dotnet new install -h` , did you actually mean `dotnet new --install -h` ? 

The first word after "dotnet new" is always treated like a template name, unless it begins with dashes, so the command `dotnet new install -h` is not a subcommand of dotnet new. It would attempt to display help for a template (group) matching the name "install". If no template is found with that name, what should be displayed is:
- The standard usage message including the top leve help options for dotnet new
- A message in red saying `No templates matched the input template name: install.`
- A list of the installed templates.
So yes, "install" is a filter to list in this context, similar to if I ran the command `dotnet new mvc -h`. 

Running `dotnet new --install -h` will show the usage help & options. We don't currently have specific help for the install command.

**Comment by KathleenDollard** [comment]
Way simpler problem 

```bash
dotnet new -h
```

The two lines I quoted use the word "name" differently.

**Comment by grinrag** [comment]
I also see a problem with this, moreover, the statement `If no name is specified, the name of the current directory is used` is incorrect because I can set different output directory with option `-o`.
Should be like `...name of output directory`
I will open a PR shortly.

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by KathleenDollard** [comment]
I agree, let's do it.
