### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by vhmoura** [dotnet/templating#1663]
Hi there,

Trying to run a post action but it seems to be failing with the message below:

Running command 'build.bat'...
The system cannot find the file specified

my template.json looks like this:

{
	"author": "xxx",
	"classifications": [ "Web" ],
	"name": "Project",
	"identity": "Project",        
	"shortName": "Project",                 
	"tags": {
		"language": "C#"                
	},
	"sourceName": "Net.Project",      
	"preferNameDirectory" : "true",
	"postActions": [{
    "actionId": "3A7C4B45-1F5D-4A30-959A-51B88E82B5D2",	                 
    "args": {
      "executable": "build.bat",
      "args": ""
    },
    "manualInstructions": [{ 
       "text": "Run 'build.bat'" 
       }],
    "continueOnError": "true",
    "description ": "setups the project by calling build.bat"
  }]
}

The command I am running is like this:
dotnet new Net.Project -o SuperUperDuper

It creates the project, copy all the files to folder appropriately but it fails with the system cannot find the file.

Any clues?

Thanks in advance.

**Comment by seancpeters** [comment]
Where is the file build.bat located? If it's at the root of your template output, it should work. If it's in a subdirectory of the template output, you'll need to give the relative path in the post action configuration. For example:
```
{
…
"executable": "path\to\file\build.bat",
…
}
```

**Comment by mlorbetske** [comment]
I believe you need to set the executable to “cmd.exe” and the args property to “/c {the relative path to your batch file}”

**Comment by mlorbetske** [comment]
Closing this since we haven't heard back. Please let us know if this is still an issue

**Comment by ADIX7** [comment]
I have the same issue. Because preferNameDirectory is true dotnet will create a folder for the project so "executable" should be ProjectName\build.bat instead of build.bat. Is there any variable I can use in the executable variable? I tried the same value as the sourceName but it does not work.

**Comment by mlorbetske** [comment]
@ADIX7 could you post more details please? A link to the right files in a repository would be best, otherwise the contents of template.json and the file/directory structure of your template content would also work

**Comment by ADIX7** [comment]
template.json: https://pastebin.com/Vh5a7Gu3
Directory tree: https://pastebin.com/r2EQsSgX
command: dotnet new vmtsMdm --name VMTS.Web.Tutorial_ClassDiagram --className ClassDiagram --domainName ClassDiagramWebTutorial

When preferNameDirectory is false, dotnet new will create all the content in the current directory. In my case there will be an initTemplate.sh (and an initTemplate.ps1 but lets focus to linux, same happens on both platform) file. I start it with 'Run script' (3A7C4B45-1F5D-4A30-959A-51B88E82B5D2) post action. When preferNameDirectory is false initTemplate.sh will be in the current folder.

When preferNameDirectory is true dotnet new will create a VMTS.Web.Tutorial_ClassDiagram folder (if you run the command I gave above) and the content will go there. But the run script post action will try to run initTemplate.sh instead of VMTS.Web.Tutorial_ClassDiagram/initTemplate.sh

So preferNameDirectory: true will create a folder but run script post action does not handle this.

There could be several solutions:
-Change the process's working directory to the newly created instead of the current if preferNameDirectory is true
-Give some variable what we can use in executable and/or args parameters of the run script post action

**Comment by mlorbetske** [comment]
That's exactly the information I was looking for, thanks! We'll hopefully get to dig in to this more soon.

**Comment by ADIX7** [comment]
Your welcome :) Looking forward for the results.

**Comment by mlorbetske** [comment]
Would you also be able to provide the output of `dotnet new --debug:version` please?

**Comment by ADIX7** [comment]
On Ubuntu 18.04 with dotnet 2.2.103

$ dotnet new --debug:version           

Permission denied to modify the '/usr/share/dotnet/sdk/NuGetFallbackFolder' folder.

Here are some options to fix this error:
----------------------------------------
1. Re-run this command with elevated access.
2. Disabled the first run experience by setting the environment variable DOTNET_SKIP_FIRST_TIME_EXPERIENCE to true.
3. Copy the .NET Core SDK to a non-protected location and use it from there.
    
Template Instantiation Commands for .NET Core CLI

 Version:     1.0.2-beta4
 Commit Hash: 2b52e96b5737d86c215e0d80483d48c4b107c2a8

**Comment by brandonseydel** [comment]
This is happening to me as well.  I have work around but they are not appealing to look at in the command window.

**Comment by kierenj** [comment]
I have the same issue.  `preferNameDirectory` is `true` and I'm using:

```json
  {
      "actionId": "3A7C4B45-1F5D-4A30-959A-51B88E82B5D2",
      "args": {
        "executable": "seed.cmd",
        "args": ""
      },
      "manualInstructions": [
        {
          "text": "Run 'seed.cmd'"
        }
      ],
      "continueOnError": true,
      "description ": "Seeds the system"
    }
```

Output:

```
Template is configured to run the following action:
Description:
Manual instructions: Run 'seed.cmd'
Actual command: seed.cmd 
Do you want to run this action (Y|N)?
Y
Running command 'seed.cmd '...
The system cannot find the file specified.
```

It's a real blocker at the moment, anything I can do at all?

**Comment by kolluri-rk** [comment]
I have similar issue. I was able to make it work on Mac with bash script, but not able to get it work on windows machine with batch file. 

I tried to describe my workflow as clear as possible. please let me know how can I get this working on windows. 

my use case is - 
* user provides an input swagger file (configured as symbol)
* template output will have an empty spec folder 
* user provided input swagger file has to be copied into spec folder (using post actions)

```json
"symbols": {
  "InputSpec": {
      "type": "parameter",
      "datatype": "string",
      "defaultValue": "",
      "replaces": "swagger-spec",
      "description": "The value of this symbol replaces 'swagger-spec' in the generated content"
    }
  },
```

```json
{
      "actionId": "3A7C4B45-1F5D-4A30-959A-51B88E82B5D2",
      "description ": "copies input swagger spec by calling copy-spec.cmd",  
      "condition": "(OS == \"Windows_NT\")",
      "manualInstructions": [{ "text": "Run 'postActionScripts\\copy-spec.cmd'" }],
      "continueOnError": false,
      "args": {
        "executable": "'postActionScripts\\copy-spec.cmd",
        "args": ""
      }
    }
```

my template folder structure (removed other content for brevity). `preferNameDirectory` was set to **true** in `template.json`.

```text
└── webapi-template
    ├── WebApi.Template.sln
    ├── postActionScripts
    │   ├── copy-spec.cmd
    │   └── copy-spec.sh
    ├── src
    │   └── WebApi.Template
    │       ├── WebApi.Template.csproj
    │       └── spec
    │       │   └── empty.dir
    └── test
    ├── WebApi.Template.IntegrationTests
    └── WebApi.Template.UnitTests
```

dotnet new command

```cmd
dotnet new agwebapi -n ProductApi --InputSpec c:\swaggerspecs\some-swagger.json --allow-scripts yes
```

here is dotnet new version

```text
dotnet new --debug:version
Template Instantiation Commands for .NET Core CLI

 Version:     1.0.2-beta4
 Commit Hash: 2b52e96b5737d86c215e0d80483d48c4b107c2a8
```

**Comment by dannycarrera** [comment]
I'm running into this issue as well.

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by MaxCrank** [comment]
Not sure if it's the same bug, because it's happening only on Windows. I have a _postprocessing_ folder which contains several text files.

The following post-action code to remove this folder doesn't work, throwing error that it wasn't found:

```
{
    "actionId": "3A7C4B45-1F5D-4A30-959A-51B88E82B5D2",
    "condition": "(OS == \"win\")",
    "args": {
      "executable": "rmdir",
      "args": "/s /q postprocessing"
    },
    "continueOnError": false
  }
```

I've tried "postprocessing", ./postprocessing, .\\\postprocessing etc., no luck. Absolute path isn't an option obviously. `del` command behaves exactly the same way. Still, if I copy-paste it to cmd and run manually, everything is OK.

At the same time, the Powershell workaround below does work.
```
{
    "actionId": "3A7C4B45-1F5D-4A30-959A-51B88E82B5D2",
    "condition": "(OS == \"win\")",
    "args": {
      "executable": "powershell",
      "args": "-command Remove-Item -Recurse -Force \"postprocessing\""
    },
    "continueOnError": false
  }
```

For Linux I use `rm` and it works absolutely fine, too.

**Comment by AR-May** [comment]
Hello @MaxCrank, yes, it seems like you had not the same bug as others. My understanding at the moment that `rmdir` is not an executable, but just a command, so it can not be used there.

**Comment by AR-May** [comment]
Fixed. Implemented search logic: first, search for the executable file in the template base folder, then, if no file has been found, the executable should be searched in the directories from PATH.
