### ISSUE TITLE
How to add a nuget package to a specific project file

### ISSUE THREAD

**Issue by skoruba** [dotnet/templating#1665]
My project template contains two csproj files:

```
"primaryOutputs": [
    {
      "path": "src/UI/UI.csproj"
    },
    {
      "path": "src/BL/BL.csproj"
    }
  ]
```
I want to add a nuget package to first csproj file - UI.csproj, I have tried to use the postAction:

```
 "postActions": [
...
    {
      "Description": "Add a reference",
      "ActionId": "B17581D1-C5C9-4489-8F0A-004BE667B814",
      "ContinueOnError": "false",
      "ManualInstructions": [
        {
          "Text": "Manually add the reference to your project file"
        }
      ],
      "args": {
        "referenceType": "package", 
        "reference": "newtonsoft.json",
        "version": "9.0.1",
        "projectFileExtensions": ".csproj"
      }
    }
...
  ]
```
How can I specify csproj file - UI.csproj? I can't  use direct name UI.csproj because this name is dynamically renamed according --name flag.

Thanks!

**Comment by maracuja-juice** [comment]
Would it be an option to set the following to your input csproj?
```
<PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
```

**Comment by skoruba** [comment]
`Newtonsoft.Json` was mentioned for example. I have my own nuget package that has same name as my project. For example - `UI.csproj` and in my csproj:

`<PackageReference Include="UI" Version="1.0.0" />`

After instalation of the template - this `UI` nuget package was replace with --name flag.

`dotnew template --name example` and I get following csproj reference collision:

`<PackageReference Include="example" Version="1.0.0" />`

Any idea how to disable replacing of this line `<PackageReference Include="UI" Version="1.0.0" />` in csproj?

**Comment by skoruba** [comment]
I've found the solution in this issue: https://github.com/dotnet/templating/issues/1627#issuecomment-408658447
```
<!--/-:replacements:noEmit -->
<PackageReference Include="UI" Version="1.0.0" />
<!--/+:replacements:noEmit -->
```
@maracuja-juice Thanks for your idea, it was great direction!
