### ISSUE TITLE
Template unlisted from NuGet can still be installed with `dotnet new`

### ISSUE THREAD

**Issue by theimowski** [dotnet/templating#1671]
I released the initial 0.0.1 version of SAFE.Template using `SAFE-Template.0.0.1.nupkg` package name.
Because I wanted the template to be installed using `dotnet new -i SAFE.Template` rather than `dotnet new -i SAFE-Template`, I changed the name of nupkg to `SAFE.Template.*.*.*.nupkg` for following releases.

Unfortunately, it turns out that even after I [unlisted](https://www.nuget.org/packages/SAFE.Template/0.0.1) the initial version it can still be installed using `dotnet new -i SAFE-Template`

**Comment by theimowski** [comment]
Is there any way to "hide" the `SAFE-Template` (with dash) from `dotnet new` ?

**Comment by sayedihashimi** [comment]
In addition to this, there would be nothing preventing someone from downloading the .nupkg and then manually hooking up the template. For in-process templates I think it's better to use a myget, or customer nuget feed, to prevent it from getting to nuget.org if you may want to "hide" it.

**Comment by theimowski** [comment]
So my only option is to push the same package both as safe-template and safe.template to avoid confusion for users?

**Comment by mlorbetske** [comment]
I believe that's the safest way, yes. You may want to open an issue on NuGet/Home to see if there's a way for you to prevent users from installing the package you no longer want to be available.
