### ISSUE TITLE
For .vb files, conditionals can't cause uncommenting of their content

### ISSUE THREAD

**Issue by seancpeters** [dotnet/templating#1673]
Because the Vb conditionals don't have a lead token, the "actionable" conditional keywords are identical to the regular ones. Also, without the lead token, there is nothing known as the "comment to remove" when the uncomment replacement is setup.

See the method GenerateConditionalSetup() in this file:
https://github.com/dotnet/templating/blob/stabilize/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/Config/ConditionalLineCommentConfig.cs

For Vb, this is called from: 
https://github.com/dotnet/templating/blob/stabilize/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/Config/ConditionalConfig.cs as:
```
setup = ConditionalLineCommentConfig.GenerateConditionalSetup("", new ConditionalKeywords
                    {
                        IfKeywords = new[] { "If" },
                        ElseIfKeywords = new[] { "ElseIf" },
                        ElseKeywords = new[] { "Else" },
                        EndIfKeywords = new[] { "End If" },
                        KeywordPrefix = "#"
                    }, new ConditionalOperationOptions
                    {
                        EvaluatorType = "VB",
                        WholeLine = true
                    });
```

The key part being the empty string as the first param.

**Comment by donJoseLuis** [comment]
This issue was last touched some years ago.  We are working on a new delivery road map.  Please reopen if this is something we want & we'll properly assess its' priority compared to other work aimed at improving the overall templating UX.
