### ISSUE TITLE
Installing a template with `dotnet new -i` from custom Nuget source not working

### ISSUE THREAD

**Issue by markvincze** [dotnet/templating#1677]
I have a template published to our own Nuget feed. I'm trying to install it with `dotnet new -i`, but none of the installation methods are working, and I'm not getting any error messages either.

I'm going to show the output I get from `dotnet`.

First try: try to install without specifying the Nuget source. This is expected to fail, and it gives me a proper error message, so so far so good.

```
$ dotnet new -i MyCustomTemplate
  Restoring packages for C:\Users\mvincze\.templateengine\dotnetcli\v2.1.400\scratch\restore.csproj...
C:\Users\mvincze\.templateengine\dotnetcli\v2.1.400\scratch\restore.csproj : error NU1101: Unable to find package MyCustomTemplate. No packages exist with this id in source(s): C:\Program Files\dotnet\sdk\NuGetFallbackFolder, Microsoft Visual Studio Offline Packages
  Generating MSBuild file C:\Users\mvincze\.templateengine\dotnetcli\v2.1.400\scratch\obj\restore.csproj.nuget.g.props.
  Generating MSBuild file C:\Users\mvincze\.templateengine\dotnetcli\v2.1.400\scratch\obj\restore.csproj.nuget.g.targets.
  Restore failed in 89.32 ms for C:\Users\mvincze\.templateengine\dotnetcli\v2.1.400\scratch\restore.csproj.

Usage: new [options]

Options:
  -h, --help          Displays help for this command.
... rest of the help message
```

So I tried to specify the Nuget source with `--nuget-source`. This doesn't do anything, and doesn't print any errors.

```
$ dotnet new -i MyCustomTemplate --nuget-source https://acme-int.myget.org/F/private-nuget/auth/4160d2cc-1775-4542-9b8b-3f7f46ffc0c3/api/v3/index.json
  Restoring packages for C:\Users\mvincze\.templateengine\dotnetcli\v2.1.400\scratch\restore.csproj...
  Installing MyCustomTemplate  0.3.0.
  Generating MSBuild file C:\Users\mvincze\.templateengine\dotnetcli\v2.1.400\scratch\obj\restore.csproj.nuget.g.props.
  Generating MSBuild file C:\Users\mvincze\.templateengine\dotnetcli\v2.1.400\scratch\obj\restore.csproj.nuget.g.targets.
  Restore completed in 6.65 sec for C:\Users\mvincze\.templateengine\dotnetcli\v2.1.400\scratch\restore.csproj.

Usage: new [options]

Options:
  -h, --help          Displays help for this command.
... rest of the help message
```

This says `Installing MyCustomTemplate 0.3.0.` and there are no errors, but it actually doesn't install it, so if I try to use it, it's not found.

I also tried to install by specifying the local `nupkg` file.

```
$ dotnet new -i ./MyCustomTemplate.0.3.0.nupkg
Usage: new [options]

Options:
  -h, --help          Displays help for this command.
... rest of the help message
```

This just doesn't seem to do anything at all.

And I also tried to first add the custom Nuget feed as a source globally with the `nuget` CLI, and then do the installation with `dotnet new -i`.

```
$ nuget sources Add -Name "Custom Myget" -Source https://acme-int.myget.org/F/private-nuget/auth/4160d2cc-1775-4542-9b8b-3f7f46ffc0c3/api/v3/index.json
Package Source with Name: Custom Myget added successfully.
$ dotnet new -i MyCustomTemplate
  Restoring packages for C:\Users\mvincze\.templateengine\dotnetcli\v2.1.400\scratch\restore.csproj...
  Installing MyCustomTemplate 0.3.0.
  Generating MSBuild file C:\Users\mvincze\.templateengine\dotnetcli\v2.1.400\scratch\obj\restore.csproj.nuget.g.props.
  Generating MSBuild file C:\Users\mvincze\.templateengine\dotnetcli\v2.1.400\scratch\obj\restore.csproj.nuget.g.targets.
  Restore completed in 421.31 ms for C:\Users\mvincze\.templateengine\dotnetcli\v2.1.400\scratch\restore.csproj.

Usage: new [options]

Options:
  -h, --help          Displays help for this command.
... rest of the help message
```

This outputs the same as the first attempt, but I still can't find the installed template if I do `dotnet new`.

What can be the reason for this, and how could I troubleshoot what's going wrong?

**Comment by mlorbetske** [comment]
It seems like it’s finding the package but is determining there are no templates in that package. Would it be possible to get the package or see the template sources so we can get a better idea of what’s going on?

**Comment by markvincze** [comment]
Hi @mlorbetske,

Thanks for the reply. Here is the source of the template: 
[Travix.WebApi.Template.zip](https://github.com/dotnet/templating/files/2494953/Travix.WebApi.Template.zip)  
(The only change I did before uploading is I removed two custom yaml files from the root of the project, which contained some confidential stuff.)

If you could take a look and see if you can spot any mistake there, I'd really appreciate it, or if you can give me some pointers about what I need to check (like what are the exact conditions for the package to be "considered" a template), that'd be great too.

**Comment by mlorbetske** [comment]
The sources appear to be right (installing the zip works correctly) - if you extract the NuPkg, does the layout match your source?

**Comment by markvincze** [comment]
I verified too that installing the zip directly works for me.

Then I compared the contents of the zip, and the nupkg, and the structure looked the same, they both had the nuspec file, the content dir, the .template.config folder, etc. in the same place.

So what I did now is I pushed a new version of the template (with some code changes in the actual template part) to our Nuget, and now this one works properly. I don't know what could be the problem with the previous one.

One thing that might be a useful improvement is in this case to print out an error message with some info about why the package is not a correct template.

**Comment by mlorbetske** [comment]
That's definitely something we've been thinking about & we've added some degree of authoring diagnostics with the `--trace:authoring` or `--trace:install` switches. If it can't actually find `template.json` during installation though, neither of those will yield any useful information.

Glad you got it working, please let us know if there's anything more we can do to help

**Comment by ncunning** [comment]
If anyone else comes across this same issue. In my case I found that I could not have a packages folder in the content directory. Removing this prior to the nuget pack command allowed the dotnet new -i [customnuget package path] command to work

**Comment by WeihanLi** [comment]
the same problem here, any solutions?

**Comment by rodrigocarfer** [comment]
Thanks

> If anyone else comes across this same issue. In my case I found that I could not have a packages folder in the content directory. Removing this prior to the nuget pack command allowed the dotnet new -i [customnuget package path] command to work

Thanks! I just got it working by removing all unnecessary packages folders, .nupkg and .nuspec files.
