### ISSUE TITLE
how to condtionnal replace content in bash files like dockerfile

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/templating#1681]
Hi, I'm trying to replace based on the symbols,I've tried like follows, but not work.

``` bash
#if (svcType=='service')
COPY --from=build /src/MockingJ.Services.TServiceName.Web/out .
ENTRYPOINT ["dotnet", "MockingJ.Services.TServiceName.Web.dll"]
#else
COPY --from=build /src/MockingJ.Business.TServiceName.Web/out .
ENTRYPOINT ["dotnet", "MockingJ.Business.TServiceName.Web.dll"]
#endif
```

**Comment by mlorbetske** [comment]
Could you elaborate on this please? What symbols do you have declared in template.json, what parameters did you pass at the command line when using it and what is the expected output?

**Comment by WeihanLi** [comment]
my symbols are defined as follows:
``` json
"symbols":{
      "svcType": {
        "type": "parameter",
        "datatype": "choice",
        "defaultValue": "service",
        "choices":[
          {
            "choice": "service",
            "description": "service"
          },
          {
            "choice": "business",
            "description":"business"
          }
        ]
      }
}
```
the dockerfile content something like:

``` bash
#if (svcType=='service')
ENTRYPOINT ["dotnet", "MockingJ.Services.TServiceName.Web.dll"]
#else
ENTRYPOINT ["dotnet", "MockingJ.Business.TServiceName.Web.dll"]
#endif
```

when the `svcType` is service, the output I want should be 
```
ENTRYPOINT ["dotnet", "MockingJ.Services.TServiceName.Web.dll"]
```
otherwise, the output should be 
```
ENTRYPOINT ["dotnet", "MockingJ.Business.TServiceName.Web.dll"]
```

**Comment by seancpeters** [comment]
The syntax for conditionals vary based on the file, usually based on the extension. For a `.sh` file, the syntax is like this:
```
#if (svcType=='service')
ENTRYPOINT ["dotnet", "MockingJ.Services.TServiceName.Web.dll"]
#else
ENTRYPOINT ["dotnet", "MockingJ.Business.TServiceName.Web.dll"]
#endif
```

For your dockerfile, if the name is just `dockerfile`, the default conditional syntax will be used, which is like this:
```
//#if (svcType=='service')
ENTRYPOINT ["dotnet", "MockingJ.Services.TServiceName.Web.dll"]
//#else
ENTRYPOINT ["dotnet", "MockingJ.Business.TServiceName.Web.dll"]
//#endif
```

In general, templating has built-in syntax for most of the common file types. When there isn't a specific setup for a filetype, then the default syntax is used, as shown above for dockerfile.

**Comment by WeihanLi** [comment]
Works fine! Thank you @seancpeters
