### ISSUE TITLE
Need newer version of Microsoft.DotNet.Build.Tasks.Feed in  'prodcon/templating/release/2.2/' - '20181019.01'

### ISSUE THREAD

**Issue by MattGal** [dotnet/templating#1682]
@dotnet-mc-bot commented on [Fri Oct 19 2018](https://github.com/dotnet/core-eng/issues/4419)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2133460
  - **Agent:** DDVSOWINAGE050
  - **Error log:** E:\A\_work\0\s\build\publish.proj(0,0): error : An error occurred while sending the request....

@jcagme, @markwilkie

---

@MattGal commented on [Fri Oct 19 2018](https://github.com/dotnet/core-eng/issues/4419#issuecomment-431427238)

This is an issue with a temporary Http issue with the BlobFeed "CheckIfBlobExists" function.  Ricardo already added retry logic here:
https://github.com/dotnet/buildtools/blob/5d4d0646ce36b8bb3b9e835dacd84834240aa7ae/src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeed.cs 

---

@MattGal commented on [Fri Oct 19 2018](https://github.com/dotnet/core-eng/issues/4419#issuecomment-431432082)

I am unable to find the specific package used here:
(Microsoft.DotNet.Build.Tasks.Feed 2.1.0-prerelease-02419-02 )  but I note that the fix has already been ported into the 2.1 branch in 2.1.0-rc1-03131-06 .

Since the fix here is to simply take a newer build tools version, I am reclassifying this as SourceCode and moving to the templating repo.

**Comment by vijayrkn** [comment]
@joeloff - There may or may not be any action items here once we move to arcade. I will assign this to you for now incase we end up having work after we convert to arcade.

**Comment by vijayrkn** [comment]
This is fixed with the move to arcade.
