### ISSUE TITLE
Can nuget.exe be replaced by dotnet pack, when packaging up a template?

### ISSUE THREAD

**Issue by PureKrome** [dotnet/templating#1691]
Currently, I believe the only way to package a template is to use `nuget.exe pack` to package up a `content` folder ( [ref: MSdocs on 'Custom templates for dotnet new'](https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates#packing-a-template-into-a-nuget-package-nupkg-file) )

Is there any chance this can be replaced by `dotnet pack` instead?

**Comment by mlorbetske** [comment]
Yep, we use `dotnet pack` to package the templates in this repo. See https://github.com/dotnet/templating/blob/stabilize/template_feed/Template.proj, https://github.com/dotnet/templating/blob/stabilize/template_feed/Microsoft.DotNet.Common.ItemTemplates/build.csproj and https://github.com/dotnet/templating/blob/stabilize/template_feed/Microsoft.DotNet.Common.ItemTemplates/Templates.nuspec for the specifics.

**Comment by PureKrome** [comment]
Hi @mlorbetske - thanks for the reply. So this means the MS Docs are ... out of date?

> Currently, a custom template is packed on Windows with nuget.exe (not dotnet pack). For cross-platform packaging, consider using NuGetizer 3000.

**Comment by mlorbetske** [comment]
It would seem so, @mairaw could you help with that?
