### ISSUE TITLE
Multiple choice datatype

### ISSUE THREAD

**Issue by Nhowka** [dotnet/templating#1698]
Is it possible as now to select multiple choices? When there is two choices besides an empty one is easy to do a `both` one. Do those have to become different arguments?

**Comment by mlorbetske** [comment]
@Nhowka I don't believe we currently have any support for multi-valued paramters (@seancpeters may have ideas though). Could you expand on your scenario please?

**Comment by Nhowka** [comment]
It's mainly because of this [issue](https://github.com/SAFE-Stack/SAFE-template/pull/110). There was a library (Fable.Remoting) that create a http based endpoint for doing RPC and I created another library for communication (Elmish.Bridge) that passes messages through a stateful channel. Both can be used as communication and for some targets both could be used at the same time.

The experience could be nicer if the user could just use `--communication bridge --communication remoting` to have both at the same time, also to maintaining the template. If we add a third library it could be needed to check for `bridgeandremoting`, `bridge` and `bridgeremotingandthirdlibrary` for adding code for Bridge.

Would it be possible to have a datatype that works as a flag and comparing the value with the choice returned true if that value was set? That would be great when adding new values that fit in the same category and aren't mutually exclusive.

**Comment by mlorbetske** [comment]
That’s definitely an interesting scenario and fits in nicely with the “structured” data type we’ve been evaluating adding. So far we’ve been considering them as mappings on to assets carried along with the template or dynamically generated values - mainly producing elements to iterate over on a subset of template content.

This would be a good extension to that concept, allowing multiple input values for certain parameters (maybe introducing min/max arity, defaulting both to 1 or 0/1 for optional params) and a “set contains” operator to each of the evaluators.

**Comment by donJoseLuis** [comment]
This issue was last touched some years ago.  We are working on a new delivery road map.  Please reopen if this is something we want & we'll properly assess its' priority compared to other work aimed at improving the overall templating UX.
