### ISSUE TITLE
Update classlib tempalte to include .NET Standard 2.1

### ISSUE THREAD

**Issue by terrajobst** [dotnet/templating#1699]
Running

```
dotnet new classlib
```

Should still create a .NET Standard **2.0** project. However, it should be possible for a developer to specify the 2.1 TFM as well:

```
dotnet new classlib -f netstandard2.1
```

Since they are hardcoded in the template itself, we need to add it to the list.

**Comment by mlorbetske** [comment]
@terrajobst which CLIs should be able to make these - ones carrying 2.2 or ones carrying 3.0?

**Comment by mlorbetske** [comment]
+ @AngelosP as fyi

**Comment by terrajobst** [comment]
The ones carrying .NET Standard 2.1 TP, which would be the same as the ones carrying .NET Core 3.0.

**Comment by livarcocc** [comment]
Re-activating since we had to pull this out due to the default in VS changing to netstandard2.1.

We need the option to create a netstandard 2.1 project, however, the default should continue being netstandard2.0 for both Visual Studio and the CLI.

cc @terrajobst

**Comment by terrajobst** [comment]
> We need the option to create a netstandard 2.1 project, however, the default should continue being netstandard2.0 for both Visual Studio and the CLI.

Correct. Thanks!

**Comment by vijayrkn** [comment]
@mlorbetske - How much work is involved in adding this feature?

**Comment by vijayrkn** [comment]
https://github.com/dotnet/templating/pull/1796

**Comment by vijayrkn** [comment]
> @mlorbetske - How much work is involved in adding this feature?

Mike showed me where to make the change. Have a PR with the fix.
