### ISSUE TITLE
'Microsoft.VisualStudio.TemplateEngine.Contracts.ITemplateCreator' cannot be converted

### ISSUE THREAD

**Issue by HenKun** [dotnet/templating#1705]
I followed the guidance by @phenning and my custom wizard is called correctly and the $destinationdirectory$ is replaced correctly. However, if the default wizard is called (Microsoft.VisualStudio.TemplateEngine.Wizard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a) an exception is raised:

"Der zu Grunde liegende exportierte Wert vom Typ 'Microsoft.VisualStudio.TemplateEngine.Contracts.ITemplateCreator' kann nicht in den Typ 'Microsoft.VisualStudio.TemplateEngine.Contracts.ITemplateCreator' umgewandelt werden."

Rougly in english:
"The underlying exported value of type 'Microsoft.VisualStudio.TemplateEngine.Contracts.ITemplateCreator' cannot be converted into type 'Microsoft.VisualStudio.TemplateEngine.Contracts.ITemplateCreator'"

As a result the projects are not generated. If I leave out the default wizard the projects are created but not correctly stored on disk and they look weird in the solution explorer.

is it a version conflict of ITemplateCreator?

VisualStudio 15.8.2

_Originally posted by @HenKun in https://github.com/dotnet/templating/issues/1452#issuecomment-439915433_

**Comment by vijayrkn** [comment]
@phenning - Can you please take a look?

**Comment by HenKun** [comment]
Your proposed solution did not help, however, it worked without problems on the computer of a colleague. Furthermore I noticed that I don't need the default wizard, so I simply left it out and adapted the custom wizard to my needs, which works now.
