### ISSUE TITLE
Templating engine as library

### ISSUE THREAD

**Issue by oyvindh** [dotnet/templating#1707]
It would be great to see a library, so that the templating engine could be integrated into programs without having to rely on calling out to a process. Happy to contribute :)

**Comment by mlorbetske** [comment]
Hi @oyvindh, that's actually the case already. The packages for doing so are currently not on NuGet, however they are available on MyGet at https://dotnet.myget.org/gallery/templating. Using the code that calls in to the engine in the CLI project or the [IDE bootstrapper](https://github.com/dotnet/templating/blob/stabilize/src/Microsoft.TemplateEngine.IDE/Bootstrapper.cs)as a guide (depending on which one is closer to your use case) would be the best places to start.

**Comment by henrykhadass** [comment]
Hi @mlorbetske , I'm working with oyvind on this. Would you mind linking the relevant files in the CLI project too? I have difficulty finding what I'm looking for, with the closest being the [Dotnet.cs](https://github.com/dotnet/templating/blob/stabilize/src/Microsoft.TemplateEngine.Cli/Dotnet.cs) and [Battery.cs](https://github.com/dotnet/templating/blob/4bd80f0577550c7f36867b53d0c074f8f3dcde17/tools/ProjectTestRunner/Battery.cs) files. Most promising is the "CreateNewCommandWithArgsForTemplate" method in [CommandParserSupport.cs](https://github.com/dotnet/templating/blob/4bd80f0577550c7f36867b53d0c074f8f3dcde17/src/Microsoft.TemplateEngine.Cli/CommandParsing/CommandParserSupport.cs). Any help would be greatly appreciated!

**Comment by mlorbetske** [comment]
CreateTemplateAsync in https://github.com/dotnet/templating/blob/4bd80f0577550c7f36867b53d0c074f8f3dcde17/src/Microsoft.TemplateEngine.Cli/New3Command.cs will probably be the best thing to look at if you’re working toward a command line experience.
