### ISSUE TITLE
Please bring back the typescript enabled CRA template

### ISSUE THREAD

**Issue by theconnectionist** [dotnet/templating#1712]
I love using Visual Studio and the dotnet core platform. Played with the CRA and typescript template last year and came back to it to start creating typescript enabled react apps. I love the way the dotnet core platform combines client and server in one package, but now I have to  choose between that great convenience or having typescript built in.

I know an expert can start with the typescript less template and add typescript to it, but this is not something easy or advisable for a novice.

Typescript is touted as a good practice for creating Javascript apps, yet the creator and owner of Typescript drops support for it in their flagship development platform. Please reconsider this decision. Shouldn't be a big deal to create a CRAT template so people looking for Typescript have that choice.

Dropping this support makes me wonder if Typescript will go the way of the dinosaur. Maybe we shouldn't bother coming up to speed on it; perhaps look for alternatives such as Flow?

**Comment by mlorbetske** [comment]
This issue was moved to aspnet/AspNetCore#4375
