### ISSUE TITLE
Installation from external nuget repository with authentication

### ISSUE THREAD

**Issue by JamieKeeling** [dotnet/templating#1715]
We have a NuGet based template being deployed into our Artifactory instance as changes are made, with an aim to move everyone to a package based installation method instead of the current file based approach.

Additionally, we also store generic NuGet packages in the same repository and due to shortcomings in the dotnet CLI we have to configure credentials for the NuGet source via nuget.exe instead, after which `dotnet restore` works fine.

When attempting to install the template NuGet package using `dotnet new install` I am receiving a consistent HTTP 401 from Artifactory, leading me to believe that the use case of external package sources requiring credentials is not supported.

Is this a known issue? I can appreciate a lot of this is based on NuGet so it may not be straight forward.

**Comment by mlorbetske** [comment]
`dotnet new install` actually uses `dotnet restore` under the covers to get the listed package. It runs the restore in the user directory (I believe it's at %userprofile%\.templateengine\dotnetcli\v2.1.302\scratch), so in order for the credentials in the NuGet.config to apply, they'd either need to be in the global NuGet.config or in one in that directory.

**Comment by JamieKeeling** [comment]
@mlorbetske To verify my credentials are valid I cleared all packages using `dotnet nuget locals all --clear` and then performed a `dotnet restore` immediately after against a separate project, and all packages were restored successfully.

Both the NuGet packages referenced above and the NuGet CLI template exist within the same repository in Artifactory. The credentials were configured against the default location using `nuget.exe`

Using Fiddler I can see an initial HTTP 401 and then the NuGet client appears to respond with malformed authentication:

`Authorization: Basic Og==`

What could I do to troubleshoot this further? It's the only blocker for allowing our team to use templates via NuGet.

**Comment by JamieKeeling** [comment]
> @mlorbetske To verify my credentials are valid I cleared all packages using `dotnet nuget locals all --clear` and then performed a `dotnet restore` immediately after against a separate project, and all packages were restored successfully.
> 
> Both the NuGet packages referenced above and the NuGet CLI template exist within the same repository in Artifactory. The credentials were configured against the default location using `nuget.exe`
> 
> Using Fiddler I can see an initial HTTP 401 and then the NuGet client appears to respond with malformed authentication:
> 
> `Authorization: Basic Og==`
> 
> What could I do to troubleshoot this further? It's the only blocker for allowing our team to use templates via NuGet.

So having checked the basics again I realized the reason behind the authentication failure was that my source path used when attempting to install the template was the physical repository that the NuGet package had been pushed into, and not the virtual repository I use elsewhere that Artifactory exposes for consumption that's been added to my Nuget.config file.

Correcting my path now gives me access (albeit a package not found error), but that's something out of scope for this issue.
