### ISSUE TITLE
Add directory parameter to PostAction dotnet restore

### ISSUE THREAD

**Issue by shatl** [dotnet/templating#1720]
Allow to specify directory to run `dotnet restore` PostAction. 

This is needed in case of multi-project template where solution or project file does not reside in the same folder as `.template.config`

**Comment by seancpeters** [comment]
In the CLI, the restore post action is run on each of the PrimaryOutputs where the filename is one of:
- *.*proj
- *.sln

If you list the proj or sln files you want restored in the primary outputs, they will each get restored by the restore post action.

**Comment by shatl** [comment]
Thanks
