### ISSUE TITLE
Generic Host Template

### ISSUE THREAD

**Issue by r734** [dotnet/templating#1725]
I'd really like to see a template for the [.NET Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.2) project type. The closest templates right now are `web` and `webapi`, but they're both focused on HTTP-based applications.

Ideally, I would just do `dotnet new generichost`, and I'd have a ready-to-go Generic Host project with configuration, logging, and a HostedService or two (such as the `LifetimeEventsHostedService` or `TimedHostedService` from the documentation) as examples.

**Comment by seancpeters** [comment]
@AngelosP

**Comment by mlorbetske** [comment]
This issue was moved to aspnet/AspNetCore#6929
