### ISSUE TITLE
The command "git rev-parse --show-toplevel" exited with code 128

### ISSUE THREAD

**Issue by DragonMastery** [dotnet/templating#1729]
I get this error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "git rev-parse --show-toplevel" exited with code 128.	dotnet-new3	C:\Users\<user>\.nuget\packages\sourcelink.create.commandline\2.8.0\build\SourceLink.Create.CommandLine.targets	21

**Comment by seancpeters** [comment]
What command are you running when this error occurs?

**Comment by mlorbetske** [comment]
@DragonMastery from a quick look around the internet, it sounds like git exiting with code 128 usually has to do with username and email not being set correctly in git config - could you confirm that they're set?

**Comment by mlorbetske** [comment]
Closing this as we haven't heard back, feel free to re-open if needed
