### ISSUE TITLE
postActions !skipRestore not working

### ISSUE THREAD

**Issue by DragonMastery** [dotnet/templating#1730]
My template will not run the dotnet restore after doing dotnet new

```json
{ 
    "$schema": "http://json.schemastore.org/template",
    "identity": "CoreUpgrade",
    "author": "Dragon Mastery",
    "classifications": [ "Web/MVC/Razor Pages" ],
    "name": "ASP.NET Core 2.2 Web App Razor Base",
    "shortName": "razorbase",
    "tags": {
        "language": "C#"
    },
    "sourceName": "CoreUpgrade",
    "postActions": [
        {
          "condition": "(!skipRestore)",
          "description": "Restore NuGet packages required by this project.",
          "manualInstructions": [
            { "text": "Run 'dotnet restore'" }
          ],
          "actionId": "210D431B-A78B-4D2F-B762-4ED3E3EA9025",
          "continueOnError": true
        }
    ]
}
```

**Comment by seancpeters** [comment]
This post action configuration includes the condition `"(!skipRestore)"` but the `skipRestore` symbol is not defined in the template configuration. If you add the following, it should work as desired:
```
"symbols": {
    "skipRestore": {
      "type": "parameter",
      "datatype": "bool",
      "description": "If specified, skips the automatic restore of the project on create.",
      "defaultValue": "false"
    }
}
```

Note that `symbols` is a top-level element in the json.

**Comment by DragonMastery** [comment]
almost got it, now it give me this:

**Comment by DragonMastery** [comment]
almost got it, now it gives me this:
Processing post-creation actions...
No Primary Outputs to restore.

**Comment by DragonMastery** [comment]
you might want to add that piece to the [template](https://github.com/dotnet/templating/wiki/%22Runnable-Project%22-Templates#configuration)

**Comment by DragonMastery** [comment]
Thank you!

**Comment by seancpeters** [comment]
Yes, that would be part of the template.json file.

The restore post action is run on the appropriate primary outputs, as described here #1720

**Comment by DragonMastery** [comment]
It works thanks!
