### ISSUE TITLE
Broken link (web app stopped) for dotnet new templates

### ISSUE THREAD

**Issue by turibbio** [dotnet/templating#1733]
The first link (https://dotnetnew.azurewebsites.net) in this page redirect to a stopped azure web app:
https://github.com/dotnet/templating/wiki/Available-templates-for-dotnet-new

**Comment by sayedihashimi** [comment]
Sorry about that, [the site](https://dotnetnew.azurewebsites.net/) is back up and running now. Can we close this issue now?

**Comment by seancpeters** [comment]
Awesome, thanks much Sayed!
