### ISSUE TITLE
How to specify default Language for a multi-language Template ?

### ISSUE THREAD

**Issue by bartelink** [dotnet/templating#1734]
I've got a template which has a C# and an F# impl under the same `groupIdentity`.

No amount of searching can tell me why its picking the wrong default language.

is there a way for me to indicate in the `template.json` which language should win ?

**Comment by seancpeters** [comment]
The default language is a template engine host defined value. For example, in the CLI, C# is the default language. It's not something that is specified in the template configuration. So when invoking your template from the CLI, if the -lang flag & value are not specified, C# will always win.

**Comment by bartelink** [comment]
Thanks for the response; that's unfortunate -- the fact the `-l` presents a lang list with a default per row had me thinking it might be controllable. I guess where there are 2 langs and neither is C# the selection needs to be presented.

I'll close on the basis this is not likely to be a widespread need (but to be clear: for my use case, I definitely want the optimal language for my template to be chosen ;) so I'd definitely be interested in the feature)

💭 Maybe I just need to forgo the `groupIdentity` and put the lang name in the template...

**Comment by bartelink** [comment]
Thanks for detailing the lookup process - nice to know all that logic is in there.
The work in question is https://github.com/jet/dotnet-templates/pull/5 - I have had to do [this](https://github.com/jet/dotnet-templates/commit/3b14ae6c3e3e6a395edbe5241955225b51465752) as a workaround.

While I have you... VS is not showing the template in it's list - or at least I can't seem to persuade it to. Given its a runnable application template and hence arguably could count as a solution template - is there a way to tag it as such ? (Rider shows it...)

**Comment by seancpeters** [comment]
Getting templates to show up in Visual Studio is a bit more complex than just installing them in your dotnet new instance. This #1209 has info and links for how to get your template to show up in Visual Studio.

**Comment by bartelink** [comment]
Thanks Sean - that's all very helpful; thanks for the great service!

**Comment by bartelink** [comment]
FWIW, for now I've done two separate templates not under a common `groupId`.

I do look forward to a point in time where `dotnet new -i` can provision all 3/4 IDEs I've got on my Mac without any busywork. The biggest pain is the conceptual overhead of having to explain/justify in the readme for a project that you do this for `dotnet new` and whole other thing for the most commonly used thing.

If I'm forced to pick one (I'm not, any more than you guys are, but I'm using the same "not enough traffic" argument to justify my laziness ;) ), it's `dotnet net` as it's sooo clean to be able to have a quickstart consisting of

1. `dotnet tool install Equinox.Tool`
2. `dotnet new -i Equinox.Templates`

3. `dotnet new eqxwebv --todo`
4. `dotnet run -p Web`

ASIDE: a better job needs to be done on consistency - the `-i` vs `install` should not be per-tool, and it'd really be nice for the `-p` clutter to go away from what's for me the most common usage of `dotnet run`
