### ISSUE TITLE
GUID generator 'format' doesn't work

### ISSUE THREAD

**Issue by psmolkin** [dotnet/templating#1737]
**dotnet version:**
 2.2.102

**Steps to reproduce**
Create any file with following content
```
id1 = myid01
id2 = myid02
id3 = myid03
id4 = myid04
id5 = myid05
```
and copy-paste `symbols` from [docs](https://github.com/dotnet/templating/wiki/Reference-for-available-macros#guid) to `template.json`

**Expected behavior**
Different formats like in docs

**Actual behavior**
All GUIDs in lowercased 'D' format
```
id1 = 5abf1bfd-ede1-46cb-999f-24a7d210856f
id2 = 9fcfb3b3-d2e7-4791-a720-fc316150f88d
id3 = baaa6f39-33a8-42ad-a444-553ec35adc4d
id4 = 97663434-0bdb-4495-a562-2131465191a3
id5 = 9cb50b21-d6a5-427f-a32d-55365db9ee17
```

**Comment by sayedihashimi** [comment]
It was working for me in the past when I created the [guid sample](https://github.com/dotnet/dotnet-template-samples/blob/master/14-guid/MyProject.Con/.template.config/template.json). Can you double check your template.json to ensure it looks like that one?
If you can share a sample template.json that isn't working that would be helpful.

**Comment by psmolkin** [comment]
I've taken your guid sample and unfortunately got the same result. Tested on Win10 + 2.2.102 and WSL Debian9 + 2.2.101

```
.
├── Content
│   └── Generator.Empty
│       ├── ids.txt
│       └── .template.config
│           └── template.json
└── Templates.nuspec
```
**_ids.txt_**
```
id1 = myid01
id2 = myid02
id3 = myid03
id4 = myid04
id5 = myid05
```
**_template.json_** - [your sample](https://github.com/dotnet/dotnet-template-samples/blob/master/14-guid/MyProject.Con/.template.config/template.json)

**_Templates.nuspec_**
```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>Templates</id>
    <authors>psmolkin</authors>
    <version>1.0.0</version>
    <description>Templates</description>
    <language>en-US</language>
    <packageTypes>
      <packageType name="Template" />
    </packageTypes>
  </metadata>
</package>
```

**_Commands_**
```
nuget pack -Version 1.0.0  -NoPackageAnalysis
dotnet new --force -i Templates.1.0.0.nupkg
cd ../tmp
dotnet new sample14 --force 
cat ./ids.txt
```
**_Result:_**
```
id1 = e32306c4-64db-4901-8ac5-e3d0dc88779e
id2 = 34f78b50-53b0-4839-8e28-4d671680c589
id3 = 378b0983-3cc5-43a8-b5e8-c7d55c370d5d
id4 = 6b99c8d4-fc64-4bf2-b9a7-a07b3aa9bac0
id5 = 21c17c8f-afe3-4ee4-942f-c0fc4762a7f7
```

**Comment by mlorbetske** [comment]
I've tracked this down to [here](https://github.com/dotnet/templating/blob/stabilize/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/Macros/GuidMacro.cs#L69), it seems that this behavior was introduced in e2554bee4f5c4e5d2afae4e44d640411bed80582 where the names of the individual format options became unique, while leaving the default as `D` always.

I'm hesitant to directly fix this (maybe just setting the format used by the raw symbol name to the first format value), but we could probably introduce a new parameter along with format called `defaultFormat` that accepts only one format value and sets the non-suffixed symbol name to the specified format. If the new parameter isn't present, it'd have the current behavior. Any thoughts on that approach?

**Comment by harold-b** [comment]
This seems to still be going on
```shell
$ dotnet --version
5.0.100-rc.1.20452.10
```

**Comment by cbcrouse** [comment]
This issue also seems to still be persisting in dotnet 5.0.202.

The `format` parameter is ignored. The `defaultFormat` is accepted and produces the correct guid, but casing is ignored. I am unable to produce an upper-case guid.

**Comment by DavidKarlas** [comment]
@cbcrouse sorry about that, I opened bug for `defaultFormat` not respecting casing, I opened new issue to remove need to read this whole issue... It also includes workaround for you: https://github.com/dotnet/templating/issues/3128

**Comment by DavidKarlas** [comment]
@cbcrouse also notice that we have "guids" replacement feature see https://github.com/dotnet/templating/wiki/Runnable-Project-Templates#guids-optional and https://github.com/dotnet/dotnet-template-samples/blob/master/14-guid/MyProject.Con/.template.config/template.json#L15-L18 that might be easier workaround.

**Comment by cbcrouse** [comment]
Hey @DavidKarlas - Thanks for the response and opening up the issue. Actually, the "guids" replacement is strategy is much more desirable. Thanks for recommending that - it's working great!
