### ISSUE TITLE
Another `dotnet new` in PostActions locks the process

### ISSUE THREAD

**Issue by psmolkin** [dotnet/templating#1741]
My question similar with [issue 1557](https://github.com/dotnet/templating/issues/1557) but i try to run `dotnet new` from PostAction e.g.

```json
{
  "$schema": "http://json.schemastore.org/template",
  "identity": "Sample",
  "name": "lock sample",
  "shortName": "mytest",
  "postActions": [
    {
      "description": "Run another dotnet new here",
      "args": {
        "executable": "dotnet",
        "redirectStandardOutput": "false",
        "args": "new console --force"
      },
      "actionId":"3A7C4B45-1F5D-4A30-959A-51B88E82B5D2"
    }
  ]
}
```
Is any workaround known?

Actually I want to run a script that asks the user for some details before the generation.

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome
