### ISSUE TITLE
files containing - gets translated incorrectly in files

### ISSUE THREAD

**Issue by hersing** [dotnet/templating#1744]
When a file name contains "-" and is refereed in another file, the templates are replacing "-" with "_"

I have a .csproj file called "fiks-hej", and in the .sln file it is refereed to as:

`"fiks_hej", "fiks_hej\fiks_hej.csproj",`

**Comment by mlorbetske** [comment]
Could you post the output of `dotnet new --debug:version` as well as the contents of your template.json please?

**Comment by donJoseLuis** [comment]
hello @hersing could you please share your template JSon?

**Comment by donJoseLuis** [comment]
this repro attempt should be easy to do.  In the case we cannot reproduce & no repro artifacts are provided we'll close the issue.

**Comment by grinrag** [comment]
@hersing since the requested info was not provided, I am closing this issue. Feel free to open if the issue is still relevant for you.
