### ISSUE TITLE
Possible to lowercase -n parameter?

### ISSUE THREAD

**Issue by joseftw** [dotnet/templating#1746]
I have created a custom template with a template.config that looks like this:

```
{
	"author": "Josef Ottosson",
	"classifications": ["Web", "Api"],
	"name": "My.Project.Name.Template",
	"identity": "My.Project.Name.Template",
	"shortName": "my.template",
	"tags": {
		"language": "C#"
	},
	"sourceName": "My.Project.Name.Template",
	"preferNameDirectory": "true",

}
```
Then I can run it like this and files/contents in files get's replaced, works like a charm.
``dotnet new my.template -n My.Project.Name``

However, I have a config file where I need the value to be in lowercase, is it possible to lowercase the -n parameter somehow?
For example, I want to replace the value "My.Project.Name.Template(L)" to the lowercase value of the -n parameter, example: ``dotnet new my.template -n My.Project.Name`` would replace the "My.Project.Name.Template(L)" with "my.project.name".

Is that possible to do with symbols or something else? When I looked in the documentation I only found examples of lowercasing own "custom" parameters.

If it's possible, please help me and I'll send a PR to update the documentation :)

**Comment by mlorbetske** [comment]
Just using the string `my.project.name.template` in the template content where you want the lowercased version of the user input should do the trick.

**Comment by joseftw** [comment]
Omg...so easy, thank you! :)

**Comment by saborrie** [comment]
This doesn't work for the names of files. If you named a file `my.project.name.template.txt` it would not get renamed at all, whereas `My.Project.Name.Template.txt` would.
