### ISSUE TITLE
Support --interactive for templates behind private nuget feed

### ISSUE THREAD

**Issue by wli3** [dotnet/templating#1747]
1. For dotnet new -i. To use install a template behind private nuget feed the user cannot specify nuget feed in the command line . The user need to set the nuget feed in the global nuget config.

2. After adding a private nuget feed, if the feed need auth. The user will see the following error

```
/Users/williamli/Documents/cli/artifacts/tmp/Debug/dotnet/sdk/3.0.100-preview-009752/NuGet.targets(114,5): warning : The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet` [/Users/williamli/.templateengine/dotnetcli/v3.0.100-preview-009752/scratch/restore.csproj]
```

However, --interactive command is not available for dotnet new

To repro add my private feed to ~/.nuget/NuGet/NuGet.Config

```
<add key="testingnugetauth" value="https://williamleewul.pkgs.visualstudio.com/_packaging/testingnugetauth/nuget/v3/index.json" />
```

And run `dotnet new -i wul.DotNet.Common.ItemTemplates`

3. If the template uses a private package in another feed. The restore will fail due to no `--interactive` is passed to subsequence restore.

related to https://github.com/dotnet/templating/issues/1545 but now we have --interactive

**Comment by mlorbetske** [comment]
@wli3 if no auth is needed, the `--nuget-source` allows you to specify an alternate feed to use

**Comment by KathleenDollard** [comment]
@mlorbetske your answer clears up #1. 

For #2 and 3, we've done work in the CLI to improve the authentication experience for NuGet private feeds. We'd like to see this added to `dotnet new` as well. The interactive switch is needed both to access the feed with the template (#2) and the restore if it uses any packages that come from a different feed and that feed needs authentication #3

**Comment by mlorbetske** [comment]
@KathleenDollard understood, I was only commenting with regard to the first item. We'll schedule the work to pass the `--interactive` switch in the internal calls to restore

**Comment by maracuja-juice** [comment]
Is there any documentation on this new --interactive flag or can anyone clear up for me if this will help with #1545 ?

**Comment by wli3** [comment]
Any update on this issue?

**Comment by seancpeters** [comment]
No update at this point.

**Comment by allysonjoses** [comment]
Any update on this issue?

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by anderly** [comment]
Any update? This prevents using custom templates in DevOps artifacts feeds.

**Comment by wli3** [comment]
@anderly meanwhile you could run any other command that supports --interactive first to the authorized

**Comment by anderly** [comment]
@wli3 which command can I run that supports --interactive if I'm running in a directory that has no sln or project?

**Comment by wli3** [comment]
@nkolev92 I remember there is a command just to get authorized

**Comment by nkolev92** [comment]
Unfortunately we don't have any commands that will just authorize.
You have add something like restore/add package that absolutely requires a remote feed.

**Comment by anderly** [comment]
@nkolev92 @wli3 ok. gonna try to publish the templates package to a file-shared based nuget source instead until this is supported.

**Comment by donJoseLuis** [comment]
@grinrag greetings.  Based on recent traffic we should move up the priority list.  Please bring it up in the next triage.

**Comment by npuc85** [comment]
I don't know if this will help anyone, but I ended up on this page after searching for a way to install dotnet new templates from a nuget package in a feed that requires user credentials. I found the way to do that without requiring an `--interactive` switch. First add the nuget source with your credentials
`nuget source Add -Name "<name>" -Source "<your nuget source>" -UserName <your username> -Password <your password>` And then templates can be installed from that source `dotnet new -i <your template package name> --nuget-source <your nuget source>`

If this is not what everyone else is trying to do, sorry for the misunderstanding.

**Comment by anderly** [comment]
@npuc85 was this for on-prem or cloud devops? I can't seem to get it to work with cloud devops.

**Comment by Boruc04** [comment]
Something like that works for us:

1. Download the Credentials Provider installation script - [link](https://github.com/microsoft/artifacts-credprovider/blob/master/helpers/installcredprovider.ps1)
2. Open the PowerShell console and run the installation script with the -AddNetfx switch
   ```ps
   .\installcredprovider.ps1 -AddNetfx
   ```
3. Navigate to %userprofile%\\.nuget\plugins\netfx\CredentialProvider.Microsoft and open Command Prompt there.
4. Run the following command:

   ```
   CredentialProvider.Microsoft.exe -U <your nuget source>
   ```
5. Follow the instructions printed to the console window: Open microsoft.com/devicelogin, enter the code and login to the account.
6. Run the following command to install the template to your dotnet cli templates:

   ```
   dotnet new -i <template name> --nuget-source <your nuget source>
   ```

Hope this will help :)

**Comment by anderly** [comment]
@Boruc04 thanks for the steps! That works!

**Comment by Shmew** [comment]
@Boruc04 thanks for this, we were having trouble with this via our Azure DevOps feed.

**Comment by albertocorrales** [comment]
> I don't know if this will help anyone, but I ended up on this page after searching for a way to install dotnet new templates from a nuget package in a feed that requires user credentials. I found the way to do that without requiring an `--interactive` switch. First add the nuget source with your credentials
> `nuget source Add -Name "<name>" -Source "<your nuget source>" -UserName <your username> -Password <your password>` And then templates can be installed from that source `dotnet new -i <your template package name> --nuget-source <your nuget source>`
> 
> If this is not what everyone else is trying to do, sorry for the misunderstanding.

Thanks, I created a PAT and this worked for me. I hope this --interactive option will be available soon, so we don't have to create PATs

**Comment by arielnahom** [comment]
is there any progress on this?
Thanks

**Comment by bozturkMSFT** [comment]
This was delivered in .NET 5.0 with #2276.
