### ISSUE TITLE
Documentation for switch shows an example with coalesce instead

### ISSUE THREAD

**Issue by alexeyzimarev** [dotnet/templating#1748]
The wiki page here https://github.com/dotnet/templating/wiki/Reference-for-available-macros#switch doesn't show an example of using the `switch`. The sample code uses `coalesce` instead.

```
"KestrelPortReplacer": {
  "type": "generated",
  "generator": "coalesce",
  "parameters": {
    "sourceVariableName": "KestrelPort",
    "fallbackVariableName": "KestrelPortGenerated"
  },
  "replaces": "5000"
},
```

**Comment by mlorbetske** [comment]
Great catch! We'll get it taken care of, thanks!

**Comment by mlorbetske** [comment]
I've updated the documentation, thanks again!
