### ISSUE TITLE
dotnet new react requires .env

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/templating#1752]
See https://github.com/aspnet/Docs/pull/10423 and [Use the React project template](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-2.2&tabs=visual-studio)

Add a *.env* file to the *ClientApp* subdirectory with the following setting:

     `BROWSER=none`

This will prevent your web browser from opening when starting the CRA server externally.

**Comment by mlorbetske** [comment]
This issue was moved to aspnet/AspNetCore#7286
