### ISSUE TITLE
Project name warning (bad format) or auto conversion to correct format

### ISSUE THREAD

**Issue by kristianmandrup** [dotnet/templating#1753]
Please have the CLI respond with a warning when passing in a name that is not in .NET class name format (ie. camelcase with first letter uppercase). Alternatively have it automatically convert any name passed as project name to a valid name. Cheers!

I can see various other historical tickets on fixing naming issues, but still if I use `dotnet new` with a lowercase project name as I'm used to on any other platform, I get a project generated that is malformed, without any warning (ie. filename matches project name of CLI without conversion to module/class format - camelcase).

Not sure where to fix this in the code either (to make a fix and PR).

**Comment by mlorbetske** [comment]
Could you elaborate on this? On the one hand it sounds like you're looking for an enforcement of convention for convenience, but you also mention that the generated files aren't valid. A concrete example of what you're seeing would be very helpful.

**Comment by kristianmandrup** [comment]
I initially created project with lowercase name and dashes as that is typical on other platforms.
I had files generated with project name in original form, but references using camelcased form and then the IDE complaining that the file referenced doesn't exist. 

Try creating a new project `dotnet new my-app` and see for yourself ;)

**Comment by mlorbetske** [comment]
@kristianmandrup that sounds like a template authoring problem to be honest, if something's creating multiple projects but doesn't have the reference names matching in the first place is where you'd run in to things like that. There's logic that tries to help with differentiating between filenames and project names & there's a matrix of things to use to allow the engine to appropriately disambiguate that's been posted in multiple issues; I'll track that down and add it to the wiki. There's also no template called "my-app" nor any multi-project templates that ship with the default distribution of the engine that I'm aware of - if this is an issue with a particular template, it'd be good to file an issue on the owning repo or at least mention what it is so we can help find the appropriate owner and work with them to fix things. As far as enforcing .NET specific concerns in the code in this repo goes, that's not something we're likely to do as the templating code is language agnostic - you could very easily produce a JavaScript or Ruby template with no .NET code whatsoever where the application of those rules would make things different to the expectations for folks working in those languages.

**Comment by mlorbetske** [comment]
The wiki now has more information about name replacements [here](https://github.com/dotnet/templating/wiki/Naming-and-default-value-forms)

**Comment by kristianmandrup** [comment]
Cool, whatever, don't recall the exact `new` CLI syntax. Someplace you give it the name of the app to create. Yes, you pass it a template name too. I used the CLI command as advertised, passing template in `""`, ie sth like `"FSharp.Template::*" or whatever... Too exhausted now :D

**Comment by mlorbetske** [comment]
Let us know if you're willing to get in to the specifics at some point. Until then I'm not really sure what other action we can take here.

**Comment by kristianmandrup** [comment]
What I am proposing is simply to use an inflector, such as: https://github.com/srkirkland/Inflector/tree/master/Inflector.Tests

Ie. to transform the project name (from the CLI `arg`) to a valid name passed on to the generator engine.

See: https://github.com/srkirkland/Inflector/blob/master/Inflector.Tests/PascalizeAndCamelizeTests.cs#L30

```csharp
            TestData.Add("customer_name", "CustomerName");
            TestData.Add("customer_first_name", "CustomerFirstName");
            TestData.Add("customer_first_name_goes_here", "CustomerFirstNameGoesHere");
            TestData.Add("customer name", "Customer name");
```

If you replace any whitespace with `_` and `Pascalize()` you should get a valid project name in most cases.

**Comment by mlorbetske** [comment]
I can understand the suggestion, but I'd still like to know more about the portion where you indicated that the generated content isn't valid. Irrespective of whether an inflector is used, it's not ideal if a name can be supplied that results in the content being unusable/requiring correction before use.

**Comment by donJoseLuis** [comment]
This issue was last touched some years ago.  We are working on a new delivery road map.  Please reopen if this is something we want & we'll properly assess its' priority compared to other work aimed at improving the overall templating UX.
