### ISSUE TITLE
New Templates requirement for VB/B#

### ISSUE THREAD

**Issue by rrvenki** [dotnet/templating#1754]
1. Need for SQL CLR VB templates.  Have tried creating a project using C# SQL CLR, manually convert all C# to B#... it works.  The DLL ported into SQL works as expected.  So please add this template in VB.
2. In VB/B# project, On right click on solution which already has EF connection/model, if user choses to add a page, initiate a wizard and provide option to connect to EF data, select one or more table or Linq query and generate a UI in the form with Master Details or Details page.  This was already available pre VB6.  Advanced option in this wizard to connect to web service other than EF to generate a UI will be great.

**Comment by mlorbetske** [comment]
I'm not totally certain that I understand the ask. However, this feels like it's do better as a suggestion filed through the send feedback link in Visual Studio as the templates being requested would be created by a team that is more familiar with that subject matter than the folks in this repo. If this is a request to help you make custom templates or a problem you're encountering with the template engine itself, please feel free to re-open this issue.

**Comment by rrvenki** [comment]
I've precisely asked for B# templates equivalents available in C#.  For example SQL CLR vb templates are not available while available in C#. Post creating a SQL CLR project using C# template and changing all the project contents from cs to vb actually works.  So this is a straight partiality done by templates team towards B# favouring C#.  You may not like B# but the real world out there likes it very much and we don't want C# shovelled through our throat just because you like it or it may be a better new language.
Read the original request again and make sure you understand that all C# project templates in VS must be available in B# with urgency.

**Comment by mlorbetske** [comment]
@rrvenki thanks for the clarification. As I mentioned though, this repository doesn't manage the templates for the various feature teams, we provide the infrastructure for templates to be generated irrespective of language or technology. It'll be better to reach out to the subject matter experts for the area you're looking to see new templates in to ask them to produce the content you're looking for. It's often best to do so by using the send feedback link in Visual Studio.
