### ISSUE TITLE
Errors when using computed symbol in a condition of a switch symbol

### ISSUE THREAD

**Issue by XomegaNet** [dotnet/templating#1758]
We are trying to port our [Xomega](https://www.xomega.net) project and solution templates for our model-driven development platform to use `dotnet new`, but we ran into this issue that appears to be a bug.

If you use a computed symbol in a condition of another symbol of type "switch", you get the following error when running your [sample template](https://github.com/dotnet/dotnet-template-samples/tree/master/15-computed-symbol) from a CLI:
```
C:\temp>dotnet new sample15 -o Sam15 --DisplayCopywrite true --BackgroundColor aliceblue
Template "Contoso Sample 15" could not be created.
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
```
The new "switch" symbol is defined as follows.
```
    "newParam": {
      "type": "generated",
      "datatype": "text",
      "generator": "switch",
      "replaces": "something",
      "parameters": {
        "evaluator": "C++",
        "cases": [
          {
            "condition": "BackgroundGreyAndDisplayCopyright",
            "value": "val1"
          }
        ]
      }
    },
```

**Comment by mlorbetske** [comment]
Just out of curiosity (as the C++ evaluator sometimes has issues with non-parenthesized expressions), could you try this:

```
    "newParam": {
      "type": "generated",
      "datatype": "text",
      "generator": "switch",
      "replaces": "something",
      "parameters": {
        "evaluator": "C++",
        "cases": [
          {
            "condition": "(BackgroundGreyAndDisplayCopyright)",
            "value": "val1"
          }
        ]
      }
    },
```

**Comment by XomegaNet** [comment]
Hmm, parenthesizing the condition seems to have done the trick in this case, even though it was not required when using regular non-computed parameters in the condition.

Thanks for the quick response.
