### ISSUE TITLE
unsupported semvar version build failures in 'official/dotnet/templating/refs/heads/darc-master-ad2a07ff-321c-499a-9b56-6f99a6209177' - '20190213.1'

### ISSUE THREAD

**Issue by robertborr** [dotnet/templating#1765]
@dotnet-mc-bot commented on [Wed Feb 13 2019](https://github.com/dotnet/core-eng/issues/5228)

There were a set of failures during this build. Here is a summary of these:
* https://dnceng.visualstudio.com/internal/_build/results?buildId=94272
  - **Agent:** a0000S3
  - **Error log:** F:\vsagent\25\s\.dotnet\sdk\2.1.502\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(0,0): error NU5105: The package version '1.0.2-beta5.19113.1' uses SemVer 2.0.0 or components of SemVer 1.0.0 that are not suppor...

@robertborr

---

@robertborr commented on [Wed Feb 13 2019](https://github.com/dotnet/core-eng/issues/5228#issuecomment-463270678)

dup #5219 
marking sourcecode  and closing.
@mlorbetske - can you take a look at this? its happened 4 times so far. Should I move this into the templating repo ?

---

@mlorbetske commented on [Wed Feb 13 2019](https://github.com/dotnet/core-eng/issues/5228#issuecomment-463282641)

@robertborr moving it to the templating repo sounds good, thanks. We’ll take a look

**Comment by mlorbetske** [comment]
@vijayrkn @joeloff any ideas on what to do with this? I'm not familiar with how these package versions get generated with the move to arcade

**Comment by joeloff** [comment]
Hmm, not sure where that is coming from. All we define are the 1.0.2 version prefix and the pre-release label (beta5). Anything else is being added by Arcade AFAIK. It has different versioning it uses depending on the type of build (PR, CI, CI official, etc)

**Comment by vijayrkn** [comment]
This is where the versions are set https://github.com/dotnet/templating/blob/master/eng/Versions.props#L7

I think there is some logic in the individual csproj which is causing this. I will take a look.

**Comment by vijayrkn** [comment]
This is fixed.
