### ISSUE TITLE
Is there a way to use just the template orchestrator without using dotnet new?

### ISSUE THREAD

**Issue by DevKumar4Git** [dotnet/templating#1766]
Is there a way that I can just use the template orchestrator without having to use 
dotnet install &
dotnet new?

**Comment by mlorbetske** [comment]
The packages containing the libraries that dotnet new builds on are available on [MyGet](https://dotnet.myget.org/gallery/templating), it is possible to build other experiences on top of them. Visual Studio, Visual Studio for Mac and other IDEs take this approach for supporting some or all of the project/item creation.

**Comment by DevKumar4Git** [comment]
Thanks. I will try to use this. It would be good if there are examples on how to use this easily.
