### ISSUE TITLE
Linux build does not put content in nupkgs

### ISSUE THREAD

**Issue by crummel** [dotnet/templating#1769]
Building on RHEL7.6 with the command
`./build.sh --configuration Release -bl`
successfully builds, tests, and produces packages, but the template packages do not include the `content/` directory.  When these packages are later used in a core-sdk build, the SDK ends up not having the `console` or `classlib` templates.

This is on both latest master and the 3.0 preview2 commit ac8f12b90238542dfd2ea596178ae24ea20a0f55.

Here's the log from the build: [binlog.zip](https://github.com/dotnet/templating/files/2887104/binlog.zip).

Let me know if you need any other details!

**Comment by crummel** [comment]
Just wanted to ping this again since the same commit is in the preview3 build.

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by bekir-ozturk** [comment]
Hi @crummel 
 Thanks for the issue.
 This should already be fixed. Let me know if you encounter it again. Closing.
