### ISSUE TITLE
dotnet new -i '{path}' 2.1.504 vs 2.2.104

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/templating#1773]
_From @TomekDex on February 19, 2019 16:27_

Hello
Are there any differences between the templates for these dotnet versions?

After upgrading to 2.2.104, this command stopped working.

It prints everything in the same way as in the previous version and doesn't add any templates to the list

_Copied from original issue: dotnet/core#2328_

**Comment by mlorbetske** [comment]
_From @karelz on February 27, 2019 1:10_

@livarcocc @nguerrera can you please help route the question?

**Comment by mlorbetske** [comment]
_From @livarcocc on February 27, 2019 3:24_

@vijayrkn @mlorbetske

**Comment by TheAngryByrd** [comment]
Yeah definitely experiencing this on osx

After running the install command 

```
dotnet new -i dist/MiniScaffold.0.14.0.nupkg
```

mini-scaffold does not show up in my list of dotnet templates.

```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.104/

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84
```

**Comment by WeihanLi** [comment]
Any update here? Is there'a solution for now?

**Comment by WeihanLi** [comment]
Is there a plan or roadman to fix it? @mlorbetske

**Comment by mlorbetske** [comment]
This is something we’re looking at in the work we’re currently doing to enable template search and updates. cc @seancpeters

**Comment by erikest** [comment]
Same issue on the latest preview 3 bits (3.0.100-preview3-010431)

`dotnet new -i ./mytemplate.1.0.0.nupkg`

Just prints the help, tried adding --dry-run, same result.

no bin/obj/modules/dlls/etc in the package.  

structure is

* .nuspec
* content/
    * .template.config/
        * template.json
    * mytemplate.sln
    * src/
        * various source files and projects.

**Comment by seancpeters** [comment]
Can you try running your install command with the additional flag `--dev:install`, so:
`dotnet new -i ./mytemplate.1.0.0.nupkg --dev:install`

Depending on the type of problem encountered while installing, this may give some useful diagnostics.

**Comment by erikest** [comment]
@seancpeters  okay, gave that a go.  Nothing new to report - it just shows the help.

**Comment by MattRuwe** [comment]
I had a similar issue.  I was trying to install a template from a file path, but after running the command it would only show the usage information without telling me it succeeded or failed.  I assume that because it was showing the usage information that I was doing something wrong.  However, after digging a bit deeper and asking on [Stackoverflow](https://stackoverflow.com/questions/56259025/dotnet-new-install-shows-usage-information), I found that it was indeed installing the template, but not showing any details about the result of the command.

I suggest that this functionality be changed to at least include a success or failure indication.

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by vlada-shubina** [comment]
The issue will be fixed with https://github.com/dotnet/templating/issues/2745, when implementing that epic install-uninstall was majorly reworked. 

The error messages and the result of installation will be now shown to user. If installation was not successful, the error and the reason will be shown to user.
Draft example:
```
> dotnet  new  -i Take.Blip.Client.Templates::0.50.10 --nuget-source https://api.nuget.org/v3/index.json
The following template sources will be installed:
  Take.Blip.Client.Templates, version: 0.50.10

Warning: Take.Blip.Client.Templates::0.50.10 is not found in NuGet feeds https://api.nuget.org/v3/index.json.
'Take.Blip.Client.Templates::0.50.10' could not be installed, the package does not exist.
```

If installation was successful, the list of installed templates will be shown to user:
```
dotnet new3 -i Microsoft.Azure.WebJobs.ItemTemplates
The following sources will be installed:
  Microsoft.Azure.WebJobs.ItemTemplates

The template source Microsoft.Azure.WebJobs.ItemTemplates::3.1.1648 was successfully installed.
The following templates were installed:
Template Name                  Short Name  Language  Tags
-----------------------------  ----------  --------  ----------------------------------------------
DurableFunctionsOrchestration  durable     [C#]      Azure Function/Durable Functions Orchestration
SendGrid                       sendgrid    [C#]      Azure Function/Ouput/SendGrid
BlobTrigger                    blob        [C#],F#   Azure Function/Trigger/Blob
CosmosDBTrigger                cosmos      [C#],F#   Azure Function/Trigger/Cosmos DB
EventGridTrigger               eventgrid   [C#]      Azure Function/Trigger/EventGrid
EventHubTrigger                eventhub    [C#],F#   Azure Function/Trigger/EventHub
HttpTrigger                    http        [C#],F#   Azure Function/Trigger/Http
SignalRTrigger                 signalr     [C#]      Azure Function/Trigger/Http/SignalR
IotHubTrigger                  iothub      [C#]      Azure Function/Trigger/IotHub
RabbitMQTrigger                rqueue      [C#]      Azure Function/Trigger/RabbitMQ Queue
ServiceBusQueueTrigger         squeue      [C#]      Azure Function/Trigger/Service Bus/Queue
ServiceBusTopicTrigger         stopic      [C#]      Azure Function/Trigger/Service Bus/Topic
QueueTrigger                   queue       [C#]      Azure Function/Trigger/Storage Queue
TimerTrigger                   timer       [C#],F#   Azure Function/Trigger/Timer

```

**Comment by vlada-shubina** [comment]
Above was implemented, closing
