### ISSUE TITLE
fileRename for symbol of type "generated" doesn't work

### ISSUE THREAD

**Issue by pihalve** [dotnet/templating#1783]
I'm trying to create a symbol which takes a service name, and then do replacements of different variants of this Service Name. So, first I create a "parameter" symbol, which takes the service name specified by user and replaces instances of "ServiceName" with what the user specified. Then I do a couple of transformations to achieve a result where the service name is changed, e.g. from MyService to my-service, and then replace instances of "service-name" with the transformed value. However, when I specify "fileRename" in a symbol of type "generated" it has no effect, where as "replacements" works fine. Is this a bug or is this behavior intended, and if so, how can I achieve my goal?

    "ServiceName": {
      "type": "parameter",
      "datatype": "text",
      "replaces": "ServiceName",
      "fileRename": "ServiceName",
      "description": "Name of the service to be created. Use Pascal casing and only use A-Z|a-z|0-9",
      "isRequired": true
    },
    "ServiceNameDash": {
      "type": "generated",
      "generator": "regex",
      "datatype": "text",
      "parameters": {
        "action": "replace",
        "source": "ServiceName",
        "steps": [
          {
            "regex": "([a-z]|\\d)([A-Z])",
            "replacement": "$1-$2"
          }
        ]
      }
    },
    "ServiceNameLower": {
      "type": "generated",
      "generator": "casing",
      "parameters": {
        "source": "ServiceNameDash",
        "toLower": true
      },
      "replaces": "service-name",
      "fileRename": "service-name"
    }

**Comment by bluetentacle** [comment]
I also experienced this limitation. It would be nice to be able to rename files with generated symbols.

**Comment by mlorbetske** [comment]
@seancpeters any ideas on this?

**Comment by mlorbetske** [comment]
From the look of it, you can accomplish what you're looking for with [value forms](https://github.com/dotnet/templating/wiki/Runnable-Project-Templates---Value-Forms). Please let us know if this meets your needs

```
  "symbols": {
    "ServiceName": {
      "type": "parameter",
      "datatype": "text",
      "replaces": "ServiceName",
      "fileRename": "ServiceName",
      "description": "Name of the service to be created. Use Pascal casing and only use A-Z|a-z|0-9",
      "isRequired": true
    },
    "ServiceNameDashLower": {
      "type": "derived",
      "datatype": "text",
      "valueSource": "ServiceName",
      "valueTransform": "serviceNameDashLowerForm",
      "replaces": "Program",
      "fileRename": "Program"
    }
  },
  "forms": {
    "serviceNameDashForm": {
      "identifier": "replace",
      "pattern": "([a-z]|\\d)([A-Z])",
      "replacement": "$1-$2"
    },
    "serviceNameDashLowerForm": {
      "identifier": "chain",
      "steps": [
        "serviceNameDashForm",
        "lowerCase"
      ]
    }
  }
```

**Comment by pihalve** [comment]
It works fine. Thanks a lot. Originally I did actually look into the 'forms' approach, but this chaining of built-in and custom stuff was unclear to me. Thanks.

**Comment by bluetentacle** [comment]
This should not be closed. Not being able to use generated symbols for file rename is a bug. If it can be used for renaming in-file tokens, it should be usable for file rename for consistency.

**Comment by pihalve** [comment]
Fair enough.

**Comment by mlorbetske** [comment]
@bluetentacle generated symbols are largely for values that aren't supplied by the user (generating GUIDs, getting the current date/time, manipulating values to prepare them for comparisons in conditions, etc.).

`fileRename` is a feature of `parameter` type symbols - ones that are supplied by the user or `derived` type symbols (which are essentially parameter type symbols under the hood, but with the ability to directly accept values suppressed).

We could add support for `fileRename` to non-parameter type symbols, but the common scenarios that one would use it for already have a more direct and friendly feature for accomplishing that goal. If you're experiencing an issue with not having fileRename available, could you provide more details about your scenario?

**Comment by henkish** [comment]
Is it possible to use "forms" to get current date ("yyyyMMdd") replaced in the filename? For instance: "20190507.js". Or is there any other way to achieve that?

The use case is that we use a database migration tool - and all migration scripts should be tagged using date times.

**Comment by pihalve** [comment]
I'm closing this issue, since it has been resolved to an acceptable degree of satisfactory, and it is now getting off topic. @henkish can you please post in new issue.
