### ISSUE TITLE
Custom Symbol Creation

### ISSUE THREAD

**Issue by DinoSourcesRex** [dotnet/templating#1788]
Hi,

Sorry if this is the wrong place (not sure if stackoverflow or something would be more reasonable to place this)

I've taken a look [here](https://github.com/dotnet/templating/wiki/Available-Parameter-Generators) at the parameter generators but it doesn't quite fit what I'm after.

I need to do a combination of 3 things.

1. Take the input name and lowercase it - this is covered by the [casing](https://github.com/dotnet/templating/wiki/Available-Parameter-Generators#casing) generator
2. Take the input (which can include dots where I work. So something like `project.thing`) and remove the dots then apply camel casing for each individual word then remove spaces. I want to end up with `ProjectThing`. I have no idea how to achieve this one.
3. Almost the same as #2 but I just need to lowercase everything instead of camel case.

Any advice would be most welcome.

**Comment by donJoseLuis** [comment]
@grinrag , can Phil and you discuss this & get back the issue creator?

**Comment by donJoseLuis** [comment]
Also, is this something that should be added to our docs?

**Comment by vlada-shubina** [comment]
hi @DinoSourcesRex, 

Below are examples which can do /1 and /3:
```json
"case1": {
    "type": "generated",
    "generator": "casing",
    "dataType": "string",
    "replaces": "case1",
    "parameters": {
      "action" : "replace",
      "source": "name",
	  "toLower": true
    }
  },	
"case3": {
    "type": "generated",
    "generator": "regex",
    "dataType": "string",
    "replaces": "case3",
    "parameters": {
      "source": "case1",
      "steps": [
        {
          "regex": "\\.",
          "replacement": ""
        }
      ]
    }
  }
```
For /3 you can use regex generator, which removes (replaces with nothing) dots from the name in lower case. Please check this [section](https://github.com/dotnet/templating/wiki/Reference-for-available-macros#regex) for regex macro description. 

Case 2/ is more tricky. You may try to achieve it with regex generator as well, similar to what is suggested in [this](https://github.com/dotnet/templating/issues/1238#issuecomment-476736389) comment. however it needs lots of regex replacements defined. 

Please let me know in case you have further questions, feel free to reopen the issue if needed.
