### ISSUE TITLE
Include RocketMod in the Wiki

### ISSUE THREAD

**Issue by Trojaner** [dotnet/templating#1790]
Name | Quick Install
--------|----------------
[RocketMod Plugin Templates](https://github.com/RocketMod/Rocket.Templates) | dotnet new -i "Rocket.Templates::*" |

RocketMod is a plugin framework for .NET based games. This template allows to quickly get started with a new RocketMod Plugin.

**Comment by mlorbetske** [comment]
Done, thanks for making the template! :)
