### ISSUE TITLE
MSBuild Conditions based on Symbols

### ISSUE THREAD

**Issue by Trojaner** [dotnet/templating#1795]
This is actually a question, not an issue.

I want to dynamically include a PackageReference if a specific symbol is defined.
E.g:
 `<PackageReference ... Condition="Defined(MySymbol)" />`. 

Is this possible, and if yes, how would I do that?
I have tried to use compiler constants but apparently these are not set/replaced in CsProj's.

**Comment by mlorbetske** [comment]
The only things the engine can process conditions on are symbols declared in `template.json` which are always defined, but can take on different values depending on the options the user supplies. You can use standard MSBuild condition syntax to evaluate based on the values of symbols.

Ex. if you've declared a symbol called `Foo` in `template.json`, you could do something like the following if you want to include the reference when `Foo` has a value of `Hello World`

```
<PackageReference ... Condition="'$(Foo)' == 'Hello World'" />
```

**Comment by Trojaner** [comment]
Thanks, this was exactly what I was looking for.
