### ISSUE TITLE
Post action script problem with -o option

### ISSUE THREAD

**Issue by brandonseydel** [dotnet/templating#1811]
![image](https://user-images.githubusercontent.com/5033585/55200256-559a7280-518b-11e9-9f0e-68ef4af4b3e9.png)

I am running a command with the -o option and when I do that the post action for execution fails.  If the -o option is omitted it works as intended.  The path doesn't seem to be changing relative to the -o parameter.

**Comment by mlorbetske** [comment]
I believe you'll want to set the executable to `cmd.exe` and the args to `/c GenerateAureliaCLI.cmd` in order to get this to work. Could you post your template.json please? This also looks pretty similar to #1663

**Comment by brandonseydel** [comment]
https://github.com/aurelia/dotnet/blob/6dbfb1ff9914090175bc1887f9648840e1b29f05/NugetTemplates/Aurelia.DotNet.Spa/content/.template.config/template.json#L335

I will try the cmd.exe option.

**Comment by brandonseydel** [comment]
Worked for me thank you.  The documentation should at least note that it will not work with output specified.   Then put the other way.
