### ISSUE TITLE
Add "Configuration"  & "Supported in" content to Post Action Registry Document

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/templating#1812]
`dotnet new` has been around for a while now, it would be nice if the post-action tasks could be documented. Some of them still have `TBD` against them.

https://github.com/dotnet/templating/wiki/Post-Action-Registry#open-a-file-in-the-web-browser

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by vlada-shubina** [comment]
Was recently fixed in https://github.com/dotnet/templating/wiki/Post-Action-Registry article. 
'Open file in web browser' post action is not implemented at the moment, and is not planned to be implemented.
Please reopen the issue if more information is required.
