### ISSUE TITLE
Request to include new template in wiki

### ISSUE THREAD

**Issue by AshrafAlam** [dotnet/templating#1821]
Please consider the following new template to be included in [Available templates for dotnet new](https://github.com/dotnet/templating/wiki/Available-templates-for-dotnet-new) wiki.

**Name**
[EISK Web Api](https://github.com/eisk/eisk.webapi) - ASP.NET Core templates with simple use cases to build scalable web api with architectural best practices (DDD, Onion Architecture etc).

**Quick Install**
dotnet new -i "eisk.webapi::*"

**Comment by mlorbetske** [comment]
I've added it to the wiki. Thank you for making templates :)
