### ISSUE TITLE
unsupported semver version  build failures in 'official/dotnet/templating/refs/heads/release/3.0' - '20190407.3'

### ISSUE THREAD

**Issue by robertborr** [dotnet/templating#1844]
@dotnet-mc-bot commented on [Sun Apr 07 2019](https://github.com/dotnet/core-eng/issues/5841)

There were a set of failures during this build. Here is a summary of these:
* https://dnceng.visualstudio.com/internal/_build/results?buildId=146330
  - **Agent:** NetCoreInternal-Int-Pool 4
  - **Error log:** C:\Program Files\dotnet\sdk\2.1.503\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(0,0): error NU5105: The package version '1.0.2-beta5.19207.3' uses SemVer 2.0.0 or components of SemVer 1.0.0 that are not suppor...

@robertborr

---

@robertborr commented on [Mon Apr 08 2019](https://github.com/dotnet/core-eng/issues/5841#issuecomment-480936758)

dup #5219. this was fixed by the next build https://dnceng.visualstudio.com/internal/_build/results?buildId=146491.   Reclass sourcecode and close

**Comment by vijayrkn** [comment]
All the build issues are fixed. Closing
