### ISSUE TITLE
Not Authorised to install template package from private NuGet feed

### ISSUE THREAD

**Issue by DMEvans** [dotnet/templating#1849]
I have created a .NET Core solution that my team will be using as a template for new applications.  I've built it as a template package and published it to our company's NuGet feed which is hosted in Azure DevOps (VSTS).

When I try to install my package into the .NET CLI templates using the command below I get a 401 (unauthorized) response.
`dotnet new -i MyCompany.MyTotallyAwesemeTemplate --nuget-source https://mycompany.pkgs.visualstudio.com/_packaging/GlobalPackages/nuget/v3/index.json`

Here is the full response I receive:
`Restoring packages for C:\Users\myusername\.templateengine\dotnetcli\v2.1.505\scratch\restore.csproj...
C:\Program Files\dotnet\sdk\2.1.505\NuGet.targets(114,5): error : Unable to load the service index for source https://mycompany.pkgs.visualstudio.com/_packaging/GlobalPackages/nuget/v3/index.json. [C:\Users\myusername\.templateengine\dotnetcli\v2.1.505\scratch\restore.csproj]
C:\Program Files\dotnet\sdk\2.1.505\NuGet.targets(114,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Users\myusername\.templateengine\dotnetcli\v2.1.505\scratch\restore.csproj]`

I'm authorized to access this feed but I don't know how to go about making the .NET CLI use those credentials and I can't find any help in the documentation.  Can you offer any assistance on this?

**Comment by mlorbetske** [comment]
This looks like a duplicate of #1747. If it is, could you please +1 that issue & close this one?

**Comment by DMEvans** [comment]
@mlorbetske correctly identified that this issue has already been logged
