### ISSUE TITLE
Using template without installing it in local machine

### ISSUE THREAD

**Issue by satyajit-behera** [dotnet/templating#1860]
It looks mandatory to install the dotnet core tamplates to use it to create new items or projects.

Is it possible to create a file or project from a dotnet core template without installing it in the local machine.

Are there any options available in the CLI.

Thanks

**Comment by mlorbetske** [comment]
Currently there is no way of creating a template without having installed the sources from which to create it. Could you elaborate on what you'd use a feature like that for?

**Comment by satyajit-behera** [comment]
Thanks @mlorbetske This question came up because when I have lots of custom templates for one of my projects, I was looking at if I can do this without installing it and directly accessing one folder. If I can group many templates into one installation, that will also help.

**Comment by mlorbetske** [comment]
To install multiple templates from the same directory:

If the templates are contained in NuPkg files, run: `dotnet new -i {path to directory}\*` (or `/*` if on non-windows)
If the templates are loose files under the directory, run: `dotnet new -i {path to directory}`
