### ISSUE TITLE
.NET Include .sln files, sub folders, etc

### ISSUE THREAD

**Issue by issafram** [dotnet/templating#1862]
I'm trying to create a template that I thought would be pretty easy.

My folder structure is typically like this

- TopLevelFolder
  - HelloWorld.sln
  - Other important files (needed for builds, deployments, etc)
  - .nuget.config
  - ProjectNameFolder
    - ProjectName.csproj
    - .cs files
    - Controllers
      - HelloWorld.cs
        
I just want to create a template that would include all of those.  Currently I pack the nuget file.  I see that it includes all my files as expected.  I install it using dotnet new -i just fine.  But then when I actually use the template using dotnet new HelloWorld it runs fine but all I get is the csproj and its files.

How can I bring in everything?  Do I need anything specific in the template.json?
Please help.

**Comment by mlorbetske** [comment]
Could you post your template.json file along with its location relative to the directory containing the sln file please?

**Comment by issafram** [comment]
My MyGet server was caching packages.  This is my fault.  I apologize.  Closing issue
