### ISSUE TITLE
DotNet New -n is not renaming custom template

### ISSUE THREAD

**Issue by wli3** [dotnet/templating#1869]
_From @jkears on Monday, 22 April 2019 20:37:11_

## Steps to reproduce
1. In a folder D:\\ProjectTemplates\SomeCo.DomainTemplate.CSharp copy in a working c# class library project and rename it to **DomainTemplate.csproj**
2. Add new subfolder in project root folder called .**template.config**
3. Create a new **template.json** file in the .template.config folder with the following content ...
{
    "$schema": "http://json.schemastore.org/template",
    "author": "Me",
    "classifications": [ "Domain", "Class Library"],
    "identity": "SomeCo.DomainTemplate.CSharp",
    "name": "SomeCo Domain Class Library",
    "shortName": "scdomain",
    "sourceName": "SomeCo.DomainTemplate",      
    "preferNameDirectory" : true
   
}

4. Install template as follows
**dotnet new -i D:\ProjectTemplates\SomeCo\DomainTemplate\CSharp**
verify custom template is installed

5. Create new project in a known empty folder
**dotnet new scdomain --name domaina -o domaina** 

## Expected  behavior
That a new subfolder is created called domaina containing my custom template was created and renamed to domaina.csproj

## Actual behavior
A new subfolder is created called domaina and although the csproj that my custom template was created based upon is there it has the name of the project that my template had, in my case  DomainTemplate.csproj

## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   2.2.202
 Commit:    8a7ff6789d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.202\

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

_Copied from original issue: dotnet/cli#11230_

**Comment by mlorbetske** [comment]
The value supplied for `sourceName` must match the file or directory you'd like to be renamed. I can't tell for certain whether that's the case based on your message - could let us know whether they do or not, please?

**Comment by jkears** [comment]
Many examples do not show the use of the sourceName in the template.json file.  I only put that in there to see if it would help with my issue.  Without sourceName the behavior is the same.  Do I require sourceName?  I was under then impression that one does not require that field in the template json. 

All examples will rename the project to the value provided in the --Name option... which is the behaviour that is not working for me, whether I use the - o output option or not.

**Comment by mlorbetske** [comment]
`sourceName` isn't required for all templates, just ones that want to have a file renamed as part of creation. `--name` in some cases will create a directory of the specified name, but doesn't otherwise have any special logic to determine which file you'd like to rename to match the user's supplied value for it unless `sourceName` is set in the configuration. You can see an example of how to properly use this value [here](https://github.com/dotnet/templating/blob/stabilize/template_feed/Microsoft.DotNet.Common.ProjectTemplates.1.x/content/ClassLibrary-CSharp/.template.config/template.json#L16), as you can see, it matches the name of the file in the template to rename [here](https://github.com/dotnet/templating/blob/stabilize/template_feed/Microsoft.DotNet.Common.ProjectTemplates.1.x/content/ClassLibrary-CSharp/Company.ClassLibrary1.csproj).

**Comment by jkears** [comment]
Thank you for that added clarity, as that works as expected.  I must have missed the docs that specify that you need to make the name and template the same.  Thanks so much.

**Comment by mlorbetske** [comment]
Glad you’ve got it working, always happy to help 👍
