### ISSUE TITLE
Show project templates and file templates separately

### ISSUE THREAD

**Issue by livarcocc** [dotnet/templating#1894]
@gulshan commented on [Sun May 12 2019](https://github.com/dotnet/cli/issues/11320)

Currently with `dotnet new` command, all available templates are listed. Some of them are project templates and some are file templates. Requesting to show them separately, for clarity.

**Comment by seancpeters** [comment]
This can be accomplished with:
`dotnet new --type project`
`dotnet new --type item`

One caveat is that templates that don't have any type configured in the template.json will "match" any given type argument.

**Comment by gulshan** [comment]
Can these two categories be __always__ shown separately? It will reduce the confusion IMHO.

**Comment by seancpeters** [comment]
@gulshan - I'm not what the user experience would be for this. The template type is specified by the template author, and could be anything. Type isn't limited to just "project" & "item".
