### ISSUE TITLE
Loss of functionality in postActions Restore between version 2.1.604 and 2.2.204.

### ISSUE THREAD

**Issue by swiato** [dotnet/templating#1896]
In dotnet version **2.1.604** it was possible to use following construction:

```
"sources": [
    {
      "include": [
        "TemplateProject.csproj" 
      ],
      "rename": { "TemplateProject": "TemplateProject.UI" }
    },
    {
      "include": [
        "TemplateProject.csproj" 
      ],
      "rename": {
        "TemplateProject": "TemplateProject.Tests" 
      }
    }
  ]
```

And after that using renamed filenames in primaryOutputs:

```
"primaryOutputs": [
	{ "path": "TemplateProject.UI.csproj" },
	{ "path": "TemplateProject.Tests.csproj" }
]
```

Then after using restore postAction everything behaved as expected, restore was performed for both generated projects. 

In dotnet version **2.2.204** it does not work anymore, all we get is "MSBUILD : error MSB1009". Attached is simple example of this behaviour:

[TemplateProjectRestore.zip](https://github.com/dotnet/templating/files/3201107/TemplateProjectRestore.zip)

I believe there could be many use cases for such functionality. In our case it is using custom SDK, that can recognize project name (suffix) and e.g add necessary references to that project just by knowing its name. All in the spirit of "convention over configuration".

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by vlada-shubina** [comment]
@swiato 
I have analyzed the configuration attached - there is an issue with this configuration: `primaryOutputs` should include the source filenames, and not the names after the rename, therefore the config file doesn't work. Unfortunately, for same reason it is not possible to use same file as the source for 2 target files in case these files are meant to be primary outputs. 
I'm attaching the configuration that should work for your case.
[TemplateProjectRestore - corrected.zip](https://github.com/dotnet/templating/files/5304868/TemplateProjectRestore.-.corrected.zip)

It's correct that this configuration worked in 2.1, however we don't plan to fix it for later versions. 
Please do not hesitate to reopen the issue in case of follow-up questions.
