### ISSUE TITLE
Example Templates for Code Snippets

### ISSUE THREAD

**Issue by shaggygi** [dotnet/templating#1902]
Do you have any links/docs/examples how to create [code snippets](https://docs.microsoft.com/en-us/visualstudio/ide/walkthrough-creating-a-code-snippet?view=vs-2019) for a template?

Any help is appreciated.

**Comment by donJoseLuis** [comment]
@grinrag , can Phil and you discuss this & get back to the issue creator?

Also, is this something we should add to our documentation?

**Comment by bekir-ozturk** [comment]
Hi @shaggygi,
 Code snippets are a feature of Visual Studio, while the templates are part of .NET. Can you elaborate on what do you mean by "create code snippets for a template"?

**Comment by shaggygi** [comment]
Hi @bekir-ozturk.  I've slept a few days since 😄 and don't actually remember all the details.  I believe the use-case was to create a template that would allow an install of snippets.  As mentioned, it is probably more of a VS and extensions feature.  For example, the [Prism pack](https://marketplace.visualstudio.com/items?itemName=BrianLagunas.PrismTemplatePack) includes snippets that are added during the install.

Feel free to close this out if it is not related to templates.

**Comment by sayedihashimi** [comment]
Hi @shaggygi, in order to make snippets available in Visual Studio, a Visual Studio extension is needed. If you want to include your template in the vsix, I have some info on how to do that over at https://github.com/sayedihashimi/template-sample#how-to-ship-a-template-inside-of-a-visual-studio-extension-vsix.

**Comment by bekir-ozturk** [comment]
Hi @shaggygi,
 That is totally understandable :) Closing this issue now.
