### ISSUE TITLE
dotnet new -i for an already installed template doesn't do anything

### ISSUE THREAD

**Issue by ardove** [dotnet/templating#1918]
Similar to https://github.com/dotnet/templating/issues/1538, but there is no duplicate template installed anymore. The dotnet new -i (without the force option) just appears to succeed, but it doesn't do anything. 

In any case, there doesn't seem to be a simple way to update a template without first uninstalling it and then reinstalling it. Running the install command again appears to succeed, but just does nothing (I'd expect it to fail with instructions on how to update). The --force option seems like a hack to me (unless this is the supported way to update an already installed template?).

### Repro
1. Install an old version of a template using `dotnet new -i <templateName>` (I did this by packing a template locally and then using the --nuget-source option on `dotnet new`)
2. Run `dotnet new -i <templateName>` again (without the --nuget-source option) to install the latest version

### Expected behavior
The latest version of the template is used when running the template (`dotnet new <templateName>`)

### Actual behavior
The old version of the template is used when running the template (`dotnet new <templateName>`)

Note, if I use `dotnet new -i <templateName> --force`, the behavior is what I would expect (though, I don't really think using a --force option should be required). Maybe this should be a `dotnet template update <templateName>` or something instead. 

### dotnet --info output
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.104\

Host (useful for support):
  Version: 3.0.0-preview5-27626-15
  Commit:  61f30f5a23

.NET Core SDKs installed:
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  3.0.100-preview5-011568 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview5-19227-01 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27626-15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview5-27626-15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by seancpeters** [comment]
Could you please try upgrading to a newer .NET Core SDK? The install functionality has improved, and newer versions should not have the behavior you're seeing.

**Comment by ardove** [comment]
Which version do you suggest? I’ve tried 2.2.104 and 3.0 preview.

**Comment by seancpeters** [comment]
If you're seeing this behavior with the 3.0 preview, then there is something else going on, it's not the old install bug.

Regarding using the --force flag for installing a template - the --force flag should never come into play - it doesn't affect installation. It's only used to tell template invocation to overwrite existing files.

This seems like a problem with the template pack being installed. Would you be able to share the template pack that you're trying to install (both the old and new versions)? It'd be easiest to debug it if I have the packs available.

**Comment by ardove** [comment]
Certainly, see if this link works. Let me know when you've downloaded packages so I can stop sharing. 

https://drive.google.com/drive/folders/13socZtgXUDBDwRZyImBW9kXI4CLZDQns?usp=sharing

**Comment by seancpeters** [comment]
Thanks, I was able to download the packs, so you can stop sharing. I should be able to find time to take an in-depth look at this later today.

From a quick look at the packs, the contents appear to be identical – looking at the template.json and the .gitignore files. So I’m not clear how you’d be able to tell which one is installed from invoking the templates.

Thanks,
Sean

**Comment by ardove** [comment]
@seancpeters I was mistaken (going off of information from a colleague). Looks like it does work properly in preview 3.0 (also, those nupkgs were the incorrect ones. Apologies.) 

Thanks for the quick response!

**Comment by seancpeters** [comment]
No problem, glad you were able to work it out :)
