### ISSUE TITLE
Cannot find setup.sh or setup.cmd

### ISSUE THREAD

**Issue by trinitrotoluene** [dotnet/templating#1922]
Both links in the README are 404, and I can't find the files anywhere in the repo.

Has the installation process for dotnet new3 changed?

**Comment by mbalmes** [comment]
Looks like those files were removed in [6492bb69](https://github.com/dotnet/templating/commit/6492bb69) when the build process was simplified with the ArcadeSDK. Setup.sh and setup.cmd have been replaced with build.sh and build.cmd.

**Comment by mbalmes** [comment]
I'll create a pull request to update the README but the [contributing](https://github.com/dotnet/templating/wiki/Contributing) page on the wiki needs an update too.

**Comment by orangudan** [comment]
Also stumbled across this. Perhaps unrelated but I ran `./build.sh` anyway and it didn't enable the `dotnet new3` command.

**Comment by Eilon** [comment]
BTW to run a local build here's what I've done:

1. Run `build.cmd`, which will build DLLs, NUPKGs, etc., and run tests
1. Run `dotnet .\artifacts\bin\dotnet-new3\Debug\netcoreapp2.1\dotnet-new3.dll --list` (or whatever other command)

**Comment by grinrag** [comment]
Instructions are fixed. The problem with `dotnet-new3` will be fixed, I created a separate issue #2306. The current issue will be closed.
