### ISSUE TITLE
Can't pass a name to filter with dotnet new --list

### ISSUE THREAD

**Issue by Thraka** [dotnet/templating#1926]
##### VERSION: 3.0.100-preview5-011568

Both `dotnet new -l` and `dotnet new --list` give errors when passing a name to filter by. The help information states:

```text
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
```

But when I run `dotnet new -l class` I get this error:

```text
Invalid input switch:
  class
Run dotnet new --help for usage information.
See https://aka.ms/dotnet-install-templates to learn how to install additional template packs.
```

**Comment by seancpeters** [comment]
The template "name" specification is always the first parameter for dotnet new. To accomplish what you're attempting, run the command: `dotnet new class --list` (or -l)

**Comment by Thraka** [comment]
That seems completely backwards to any traditional command line program :(

It also doesn't make sense based on the existing command line help:

```console
Usage: new [options]

Options:
  -h, --help          Displays help for this command.
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
```

There is indication that there's an optional [name] parameter passed prior to the switches. Also, there is another parameter named "name" (-n) which is additionally confusing to provide a "name" for the list switch.

Additionally, the other switches do behave in exactly the way I expected:

```console
dotnet new -i PackageName
dotnet new -u PackageName
dotnet new --type item
```

**Comment by Thraka** [comment]
Is it possible to get this issue on the radar for discussion on rewriting the format of this command to be more intuitive? 😄

**Comment by seancpeters** [comment]
I'd argue against changing how --list works, because it's a "support" command, sort of like --help. For example:
`dotnet new --help`
`dotnet new mvc --help`
This pattern of having help as the final param is also the case for other dotnet commands, their form is more like:
`dotnet <command & args> --help`
than like
`dotnet --help <command & args>`

With dotnet new, in all cases where a template name / partial name is used, the command is always 
`dotnet new <template specification> <other args>`
The --list option is consistent with this.

But, it could be helpful to rewrite the documentation for the --list command to make this more intuitive.

**Comment by bartelink** [comment]
It should also be mentioned that `dotnet new` is badly out of sync with `dotnet tool` in terms of usage - IME it was one of the most frustrating parts of my first experiences with the tooling. I'd really like to see those things getting more consistent, even if there is a cost in terms of breaking things. Slightly further off is `dotnet run` and how it manages the mix between build/project args vs actual invocation args with `--` to separate and then some super confusing heuristics around it. Please take the time to coordinate across subteams on this, because everyone loses when you don't, which is extremely evident here.

**Comment by Thraka** [comment]
> I'd argue against changing how --list works, because it's a "support" command, sort of like --help. For example:
> `dotnet new --help`
> `dotnet new mvc --help`
> This pattern of having help as the final param is also the case for other dotnet commands, their form is more like:
> `dotnet <command & args> --help`
> than like
> `dotnet --help <command & args>`
> 
> With dotnet new, in all cases where a template name / partial name is used, the command is always
> `dotnet new <template specification> <other args>`
> The --list option is consistent with this.
> 
> But, it could be helpful to rewrite the documentation for the --list command to make this more intuitive.

I can understand that. I think it would be much clearer if the actual help message gave this information. It's not indicated that template items are treated as commands.

```console
dotnet new --help
Usage: new [options]

Options:
  -h, --help          Displays help for this command.
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
  -o, --output        Location to place the generated output.
  -i, --install       Installs a source or a template pack.
  -u, --uninstall     Uninstalls a source or a template pack.
  --nuget-source      Specifies a NuGet source to use during install.
  --type              Filters templates based on available types. Predefined values are "project", "item" or "other".
  --dry-run           Displays a summary of what would happen if the given command line were run if it would result in a template creation.
  --force             Forces content to be generated even if it would change existing files.
  -lang, --language   Filters templates based on language and specifies the language of the template to create.
```

Contrast that to `dotnet tool`

```console
dotnet pack --help
Usage: dotnet pack [options] <PROJECT>

Arguments:
  <PROJECT>   The project file to operate on. If a file is not specified, the command will search the current directory for one.

Options:
  -h, --help                            Show command line help.
  -o, --output <OUTPUT_DIR>             The output directory to place built packages in.
  --no-build                            Do not build the project before packing. Implies --no-restore.
...
```

There is a clear indication about what is expected. There is a clear distinction between arguments and options. And, when the option accepts a parameter, it is shown (as in `-o`). This stuff is missing from the help with new.

```console
Usage: new [options]
Usage: new [<template>] [options]

...

  -o, --output <OUTPUT_DIR>       Location to place the generated output.
  -i, --install <SOURCE_DIR|SOURCE_NUPKG|NUGET_FEED_PACKAGE>      Installs a source or a template pack.
  -u, --uninstall <SOURCE_DIR|SOURCE_NUPKG|NUGET_FEED_PACKAGE>    Uninstalls a source or a template pack.
```

Command line help for any command should list all information required to use it. We shouldn't expect customers to have to search online help to understand options. :)

**Comment by bartelink** [comment]
>Command line help for any command should list all information required to use it. We shouldn't expect customers to have to search online help to understand options. :)

However, :troll: Ideally they should have to use `--help` in the first instance - [it should simply be consistent with the other commands](https://github.com/dotnet/templating/issues/1926#issuecomment-502241117)

**Comment by rlundy** [comment]
I found this issue because I was having the same problem:

```
C:\Code>dotnet new
Nutzung: new [Optionen]

Optionen:
  -h, --help          Displays help for this command.
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
[... etc. ...]


Templates                                         Short Name            Language          Tags
-------------------------------------------------------------------------------------------------------------------------------
Console Application                               console               [C#], F#, VB      Common/Console
Class library                                     classlib              [C#], F#, VB      Common/Library
WPF Application                                   wpf                   [C#]              Common/WPF
Windows Forms (WinForms) Application              winforms              [C#], VB          Common/WinForms
Worker Service                                    worker                [C#]              Common/Worker/Web
Unit Test Project                                 mstest                [C#], F#, VB      Test/MSTest
NUnit 3 Test Project                              nunit                 [C#], F#, VB      Test/NUnit
NUnit 3 Test Item                                 nunit-test            [C#], F#, VB      Test/NUnit
xUnit Test Project                                xunit                 [C#], F#, VB      Test/xUnit
Razor Component                                   razorcomponent        [C#]              Web/ASP.NET
[... etc. ...]
Solution File                                     sln                                     Solution

Examples:
    dotnet new mvc --auth Individual
    dotnet new xunit
    dotnet new --help

C:\Code>dotnet new --list Web
Invalid input switch:
  Web
Run dotnet new --help for usage information.
See https://aka.ms/dotnet-install-templates to learn how to install additional template packs.

C:\Code>
```

If I use the --lang switch, the argument comes after:

```
dotnet new classlib --lang F#
```

But for some reason, if I want to filter using `--list`, the argument comes _before_:

```
dotnet new web --list
```

If this inconsistency can't be changed, then it would be great if the console help could be changed to explain more clearly how `--list` is supposed to work.

**Comment by rlundy** [comment]
As a side note, is it supposed to be possible to filter by the *tags*?  I thought at one time that could be done, but if I pass an argument like `dotnet new web --list` now, it only shows me things with `web` in the Short Name column.

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by tamlin-mike** [comment]
Even the synopsis is broken.

`Usage: new [options]`

This in no way or form allows an argument before options.

Seriously people, when Microsoft can't even get _that_ right, what hope do you think there is they even have the capability to fix this problem?

**Comment by vlada-shubina** [comment]
Agreed:
- fix usage as new <template name> [options]  
- add arguments for options where needed.
GitHub item: https://github.com/dotnet/templating/issues/2591 

Original item remains open for now

**Comment by vlada-shubina** [comment]
Most items in the issue were fixed in .NET 7.0.1xx preview2.
- more intuitive syntax for list `dotnet new list class`
- usage in help - reflects all elements of command syntax now 
```
Usage:
  dotnet new [<template-short-name> [<template-args>...]] [options]
  dotnet new [command] [options]
```

Old syntax is still supported
