### ISSUE TITLE
can not install my template from vsts nuget source

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/templating#1930]
I'm trying to install the template with the command below:

``` bash
dotnet new -i MockingJ.Templates.Service::1.0.0-preview-* --nuget-source https://mvn11.pkgs.visualstudio.com/_packaging/dev/nuget/v3/index.json                                                                                                         
```

no error, but the template not installed.

> PS C:\Users\liweihan> dotnet new -i MockingJ.Templates.Service::1.0.0-preview-* --nuget-source https://mvn11.pkgs.visualstudio.com/_packaging/dev/nuget/v3/index.json                                                                                                         Restore completed in 4.33 sec for C:\Users\liweihan\.templateengine\dotnetcli\v3.0.100-preview5-011568\scratch\restore.csproj.

 without version:

> PS C:\Users\liweihan> dotnet new -i MockingJ.Templates.Service --nuget-source https://mvn11.pkgs.visualstudio.com/_packaging/dev/nuget/v3/index.json --force                                                                                                                C:\Users\liweihan\.templateengine\dotnetcli\v3.0.100-preview5-011568\scratch\restore.csproj : error NU1103: Unable to find a stable package MockingJ.Templates.Service with version
C:\Users\liweihan\.templateengine\dotnetcli\v3.0.100-preview5-011568\scratch\restore.csproj : error NU1103:   - Found 2 version(s) in zhongyi-dev [ Nearest version: 1.0.0-preview-20190612-093251 ]
C:\Users\liweihan\.templateengine\dotnetcli\v3.0.100-preview5-011568\scratch\restore.csproj : error NU1103:   - Found 0 version(s) in C:\Program Files\dotnet\sdk\NuGetFallbackFolder
C:\Users\liweihan\.templateengine\dotnetcli\v3.0.100-preview5-011568\scratch\restore.csproj : error NU1103:   - Found 0 version(s) in https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/index.json
C:\Users\liweihan\.templateengine\dotnetcli\v3.0.100-preview5-011568\scratch\restore.csproj : error NU1103:   - Found 0 version(s) in https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/index.json
C:\Users\liweihan\.templateengine\dotnetcli\v3.0.100-preview5-011568\scratch\restore.csproj : error NU1103:   - Found 0 version(s) in https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/index.json
C:\Users\liweihan\.templateengine\dotnetcli\v3.0.100-preview5-011568\scratch\restore.csproj : error NU1103:   - Found 0 version(s) in https://dotnetfeed.blob.core.windows.net/aspnet-extensions/index.json
C:\Users\liweihan\.templateengine\dotnetcli\v3.0.100-preview5-011568\scratch\restore.csproj : error NU1103:   - Found 0 version(s) in https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
C:\Users\liweihan\.templateengine\dotnetcli\v3.0.100-preview5-011568\scratch\restore.csproj : error NU1103:   - Found 0 version(s) in https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/index.json
  Restore failed in 2.17 sec for C:\Users\liweihan\.templateengine\dotnetcli\v3.0.100-preview5-011568\scratch\restore.csproj.

dotnet info:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011568
 Commit:    b487ff10aa

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\

Host (useful for support):
  Version: 3.0.0-preview5-27626-15
  Commit:  61f30f5a23
```

install templates from nuget works greatly

**Comment by seancpeters** [comment]
This appears to be an issue with the templates in your pack. The install process was able to acquire the package - the restore succeeded, but nothing installable was found in the pack.

Are you able to successfully install this pack if you already have it locally on disk? This can be done with:
`dotnet new -I <path to nupkg>`

To figure out why the pack isn't installing, I'd need, at a minimum, the template.json files for the templates in the packs.

Regarding the need for the preview version in the install string - that is due to how restore works in generl. Without a version specified, preview versions are not restored - nuget (or nuget-like) sources will always give the latest stable version when no version string is specified.

**Comment by WeihanLi** [comment]
I'd tried locally also, can not install either. The `template.json` I use is as follows:

``` json
{
    "$schema": "http://json.schemastore.org/template",
    "author": "Zhongyi dev team",
    "classifications": [ "Web", "API", "mockingj" ], 
    "name": "MockingJ Service",
    "shortName": "mkj",
    "tags": {
      "language": "C#",
      "type":"project"
    },
    "sourceName": "TServiceName",
    "preferNameDirectory": true,
    "symbols":{
      "includeTest": {
        "type": "parameter",
        "datatype": "bool",
        "defaultValue": "true"
      },
      "svcType": {
        "type": "parameter",
        "datatype": "choice",
        "defaultValue": "service",
        "choices":[
          {
            "choice": "service",
            "description": "service"
          },
          {
            "choice": "business",
            "description":"business"
          }
        ]
      }
    },
    "sources":[{
      "modifiers": [
          {
            "condition": "(!includeTest)",
            "exclude": [ "MockingJ.Services.TServiceName.Test/**/*"]
          },
          {
            "condition": "(svcType=='business')",
            "rename":{
              "MockingJ.Services.TServiceName":"MockingJ.Business.TServiceName",
              "MockingJ.Services.WebApi.TServiceName":"MockingJ.Business.WebApi.TServiceName"
            },
            "exclude": [ "MockingJ.Services.TServiceName.Business/**/*"]
          },
          {
            "condition": "(svcType=='service')",
            "exclude": [ "MockingJ.Business.TServiceName/**/*"]
          }
      ]
    }]
  }
```

**Comment by seancpeters** [comment]
Try adding an "identity" to your template. It's a top level key with a string value, and is required.

**Comment by WeihanLi** [comment]
Thanks @seancpeters , works greatly after adding "identity" for the template
