### ISSUE TITLE
Generate classes when using templates

### ISSUE THREAD

**Issue by libin85** [dotnet/templating#1934]
What options are there for us to generate code while using dotnet templates. To be more specific, for a user input of type json, I would like to generate some entity classes.

I have seen similar questions asked in here before, but did not see any conclusive answers. But I hope it can be done, as I see certain template packs have done similar things which are not open sources .
@sayedihashimi

**Comment by Thraka** [comment]
If you download any template pack from nuget, just open up the file in your favorite compression program. It's just a zip file. you can then explore the template files and see how things are done.

**Comment by seancpeters** [comment]
> "for a user input of type json, I would like to generate some entity classes"

Could you provide an example of what would be a valid "input of type json" for what you're trying to accomplish?

**Comment by libin85** [comment]
@seancpeters : Sorry, I did not mean "type json". But rather I would like to know if I could pass a list of entity model names to create those models in the project. Pretty flexible about how the parameter need to be as long as I can create those models. The parameter can be a json string, comma separated values or any other option. I will send a sample of json string a bit later today

**Comment by libin85** [comment]
`{
  "Database" : "SQLite",
 "FeatureBranching" : true,
  "Entities": [
    "Students",
    "Teachers"
  ]
}`

**Comment by libin85** [comment]
@seancpeters : or is it possible to invoke "roslyn code generator" as post action?

**Comment by seancpeters** [comment]
There's no currently built-in way to parse an input parameter value that is json, or any other complex data-types. It would conceivably be possible to do this using "derived" symbols - treating the input json as a string, and using derived symbols to effectively parse the json into other symbol values, but I think this would take considerable effort.

As for post actions, you could write a custom post action to do just about anything, including invoking roslyn. But there are some caveats with custom post actions. First off, each template engine host (Examples include: dotnet new, Visual Studio, VS Mac, etc.), is responsible for implementations of post actions, or to choose not to run them. With dotnet new, there is the ability to install your own custom components, which post action implementation would fall under. But post actions do not currently have access to the input parameters, and so would not be able to see the user input json.

I don't fully see what you're trying to accomplish, but it seems outside the scope of dotnet/templating.

**Comment by libin85** [comment]
@seancpeters : Really appreciate such a  detailed explanation. Thank you :)
