### ISSUE TITLE
Remove CollectGitInfo

### ISSUE THREAD

**Issue by tmat** [dotnet/templating#1959]
Remove https://github.com/dotnet/templating/blob/stabilize/Version.props#L9-L77. 
Source Link provides the commit SHA stamp for AssemblyInformationalVersion.

**Comment by donJoseLuis** [comment]
@tmat greetings\ahoj.  The above link is regretfully now gone.  Can you please provide the details again (apologies) if the issue remains something you want us to triage?

**Comment by grinrag** [comment]
The obsolete issue, closing it. 
The branch `stabilize` has been removed already. 
In the `master` we have: `$(GitInfoCommitHash)`
