### ISSUE TITLE
Mark the 3.0 template packages as shipping packages

### ISSUE THREAD

**Issue by vijayrkn** [dotnet/templating#1983]
This is needed to ensure that dotnet new search works for the newer console & class lib templates.

**Comment by grinrag** [comment]
Looks like this issue is obsolete. Current `dotnet-sdk` version 3.1 is shipped with console & class lib templates. Everything is working. Mark this issue for grooming the next triage session.

**Comment by grinrag** [comment]
Also, I am going to double check that dotnet new search works for console & classlib tamplates for the version 3.0.

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by grinrag** [comment]
@vijayrkn Could you, please, write steps to reproduce? Currently I cannot reproduce the bug. Thanks.

**Comment by vijayrkn** [comment]
This issue is to track publishing the older versions of Console/ClassLib packages to NuGet.org. Also to make sure that 5.0+ packages do get published to NuGet.org for the search functionality to work.

**Comment by bozturkMSFT** [comment]
3.0 Templates are shipping today. Closing.
