### ISSUE TITLE
How does the VS wizard work?

### ISSUE THREAD

**Issue by Jjagg** [dotnet/templating#1987]
I've been trying to use the TemplateEngine Wizard to embed a dotnet templating template in a VSIX package. I know SideWaffle v2 does exactly that, but I want to understand how the wizard works instead of relying on a third-party tool. So far I have failed to get a template working without SideWaffle in VS2019.
Here's what I got from @sayedihashimi's explanations:

- The nupkg that contains the template needs to be in the vsix.
- a pkgdef needs to be included with the following content to make the template discoverable for the wizard:
```
[$RootKey$\TemplateEngine\Templates\<something-unique>]
"InstalledPath"="$PackageFolder$"    // Path to the folder with the nupkg
```
- A .zip file with the template.json and .vstemplate needs to be in the vsix
- Set the following CustomParameters in the vstemplate file
  - $groupid$ to the group id specified in the template.json file
  - $language$ to the language as specified in the template.json under tags.language (or is this appended to groupid to get the identity?)
  - $uistyle$ to 'none'
- Reference the wizard in the vstemplate file:
```
<WizardExtension>
  <Assembly>Microsoft.VisualStudio.TemplateEngine.Wizard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a</Assembly>
  <FullClassName>Microsoft.VisualStudio.TemplateEngine.Wizard.TemplateEngineWizard</FullClassName>
</WizardExtension>
```
- In the vsix manifest, include the template folder as a ProjectTemplate asset and the pkgdef as a vspackage asset:
```
<Assets>
    <Asset Type="Microsoft.VisualStudio.VsPackage" d:Source="Project" d:ProjectName="%CurrentProject%" Path="|%CurrentProject%;PkgdefProjectOutputGroup|" />
    <Asset Type="Microsoft.VisualStudio.ProjectTemplate" Path="<path to folder that contains zip file (zip file can be in subfolder of this for VS nodes)>" />
</Assets>
```

Having taken all these steps, VS fails to create a project from the template when testing the VSIX. I shows an error dialog with the following message: 
```
To create this project type, go to Tools | Options | Projects and
Solutions | .NET Core and check "Use preview versions of the
.NET Core SDK"
```
Which seems to indicate that maybe it can't find the dotnet executable (even thought it's in my PATH).
I'm wondering if I'm missing anything or if anyone has a clue what's wrong.
VSIX built with SideWaffle v2 work just fine.

**Comment by phenning** [comment]
What is likely going on there is that a template matching the group id specified in the vstemplate file could not be found.

To diagnose further:
Check your %userprofile%\.templateengine\vs-2017.3\[instance]\packages folder and see if your nupkg is there.

Are you able to create other .NET Core projects?

**Comment by Jjagg** [comment]
I will try that, thanks! The built-in .NET Core templates work, and so does a template built with SideWaffle.

**Comment by sayedihashimi** [comment]
@Jjagg FYI SIdeWafflev2 is open source (https://github.com/ligershark/sidewafflev2/), I'd be happy to have you as a contributor.

**Comment by Jjagg** [comment]
@sayedihashimi For the project I'm interested in we already have dotnet templating templates, and I would like to have a simple CLI tool that can create .vstemplate files to match and pack templates together in a vsix, so I planned on creating a dotnet global tool. It seemed to me like that would be a better fit for a separate project.
SideWaffle v2 and your videos helped me a lot in figuring out how things work, so thanks!

**Comment by Jjagg** [comment]
> Check your %userprofile%.templateengine\vs-2017.3[instance]\packages folder and see if your nupkg is there.

@phenning It is missing. How should the templating engine find and copy over the nupkg?

**Comment by sayedihashimi** [comment]
@Jjagg yes having a global tool would be cool. If it's open source, please share the link.

**Comment by Jjagg** [comment]
I first need to figure out what I'm doing wrong. If you can point me in the right direction or know how to best debug this, any help would be appreciated :)

**Comment by Jjagg** [comment]
@phenning Sorry for the bump. How should the templating engine find and copy over the nupkg? It's not getting copied over to the .templateengine folder.

**Comment by donJoseLuis** [comment]
greetings @Jjagg , it's been a while since there was action on this issue. Do you still need help on the following...?
- NuGet package is not getting copied over to the .templateengine folder
Can you share more details?

**Comment by Jjagg** [comment]
@donJoseLuis Yes, I haven't solved my issue yet. Thank you for picking this up :) I will upload my project to GitHub later today with my reasoning, that should help us figure out what I'm missing.

**Comment by Jjagg** [comment]
@donJoseLuis Well I looked into this again to upload the project and gave it another go from scratch in the process and... It works! I don't have a clue what I did wrong before or what I did differently this time, but I have it working right now :) I'll reopen or open a new issue if I figure out what happened and it turns out to be a bug, but for now I'll assume I did something wrong.
