### ISSUE TITLE
post-action to add project to a solution fails as path string is not updated with sourcename

### ISSUE THREAD

**Issue by ggoyal-Axum** [dotnet/templating#1991]
I am using dotnet version 2.2.300 and template version 1.0.2-beta4
**Have the following template**
{
  "$schema": "http://json.schemastore.org/template",
  "author": "Me",
  "classifications": ["Empty" ],
  "name": "Project",
  "identity": "Project.CSharp",
  "groupIdentity":"Project",
  "shortName": "MyProject",
  "tags": {
    "language": "C#",
    "type": "project"
  },
  "sourceName": "[hello]",
  "preferNameDirectory": true,
  "primaryOutputs": [
	{ "path": "[hello]\\[hello].csproj" }
  ],
   "postActions": [{
    "description": "Add projects to solution",
    "manualInstructions": [   ],
	"primaryOutputIndexes": "0",
    "actionId": "D396686C-DE0E-4DE6-906D-291CD29FC5DE",
    "continueOnError": true
   }]
 }

**Gets the following issue on running the template**
PS D:\dev\Demo\WebApplication1> dotnet new MyProject -n aa 
The template "Project" was created successfully.

Processing post-creation actions...
Adding project reference(s) to solution file. Running dotnet sln D:\dev\Demo\WebApplication1\WebApplication1.sln add [hello]\[hello].csproj
Failed to add project(s) [hello]\[hello].csproj to solution file D:\dev\Demo\WebApplication1\WebApplication1.sln

_Here it failed to rename the [hello] sourcename in the path variable_
**Similar issues i looked at https://github.com/dotnet/templating/pull/1566**

Please assist me with this issue

**Comment by hillin** [comment]
Same here.
```bash
> dotnet --version
3.1.100-preview1-014459
```

**Comment by julianbartel** [comment]
Same here.
Works when
`    "primaryOutputs":
    [
       { "path": "<sourceName>.csproj" }
    ],`

but fails when
 `    "primaryOutputs":
    [
       { "path": "<sourceName>\<sourceName>.csproj" }
    ],`

Tested with `3.1.101`

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by AR-May** [comment]
I can reproduce the issue, however, not in the initial state.

The original issue was partially fixed: `sourceName` is replaced in `primaryOutputs`. This is already delivered, I checked that for the 3.1 version of dotnet. However, the post action does not work well with `-n` and `-o` options, as it tries to use the relative path instead of the full path in some cases. That is to be fixed.

**Comment by AR-May** [comment]
> Works when
`    "primaryOutputs":
    [
       { "path": "<sourceName>.csproj" }
    ],`
but fails when
 `    "primaryOutputs":
    [
       { "path": "<sourceName>\<sourceName>.csproj" }
    ],`

That, I suppose, also should be fixed. However, there is a [workaround:](https://github.com/dotnet/templating/issues/2068#issuecomment-529036265) try using forward slashes as path separators. That should work.

**Comment by AR-May** [comment]
> However, the post action does not work well with `-n` and `-o` options, as it tries to use the relative path instead of the full path in some cases.

Fixed this. I am closing the issue. The other problem with `primaryOutputs` and backslashes will be tracked in #2068, no need for a duplicate.
