### ISSUE TITLE
Update documentation with YAML/YML extensions support content

### ISSUE THREAD

**Issue by crhairr** [dotnet/templating#1995]
The comment syntax for yaml/yml files is not supported, but should be treated as identical to ["Language Constructs"](https://github.com/dotnet/templating/wiki/Reference-for-comment-syntax#language-source-files) listed in the wiki. YAML comments start with a #, and would work identically with the preprocessor syntax.

**Comment by pholden77** [comment]
I was having the same problem and ended up trying to setup a specialCustomOperation for **/*.yml files based on the [runnable targets](https://github.com/dotnet/templating/wiki/%22Runnable-Project%22-Templates) wiki article.

I couldn't get it to work by setting up the if/else/else if configuration based on that, but there's another open issue [1641](https://github.com/dotnet/templating/issues/1641) which shows a different solution;

template.json:
``` json
  "SpecialCustomOperations": {
    "**/*.yml" : {
      "Operations": [
        {
          "type": "conditional",
          "configuration": {
            "style": "line",
            "token": "#"
          }
        }
      ]
    }
  }
```

sample.yml
```yml
thing:
  - thing1
  - thing2
##if( condition )
  - thing3
##endif
  - thing4
```

It's working for me.  All credit goes to @williamdenton.

**Comment by crhairr** [comment]
Awesome! I'll give this a shot.

It would still be nice if Yaml was supported our of the box given its overseeing increasing prevalence in the software world. Especially vis-a-vis Docker.

**Comment by bvkeersop** [comment]
You can do the following for yaml:

```
//#if (condition)
somestuff
//#endif
```

**Comment by donJoseLuis** [comment]
@grinrag ,  let's update the docs with the above.

**Comment by vlada-shubina** [comment]
Added example above to [wiki ](https://github.com/dotnet/templating/wiki/Reference-for-comment-syntax) page.
