### ISSUE TITLE
Add MyType to VB console and classlib templates

### ISSUE THREAD

**Issue by nguerrera** [dotnet/templating#2006]
This is needed in support of getting VB code that uses `My.*`  working out of the box.

Sync with @KathleenDollard on the correct content, but I *think* we want the following for VB console app:

``` xml
<PropertyGroup>
  <MyType>Console</MyType>
</PropertyGroup>
```

And eventually the following for VB class library, but only Console may work there now.

``` xml
<PropertyGroup>
  <MyType>Windows</MyType>
</PropertyGroup>
```

(Strangely, in classic projects, VS UI shows Application type == Class Library and persists as MyType=Windows.)

Also this may need to be conditioned on minimum TFMs that have an adequate VB runtime.

cc @cston

**Comment by nguerrera** [comment]
Note: VB runtime doesn't work in netstandard, minimum TFM is probably NETCoreApp 3.0+ and nothing else.

**Comment by nguerrera** [comment]
Please hold off on making this change, there may need to be some things reverted from 3.0 and deferred to 3.1 such that MyType=Console would not work.

**Comment by donJoseLuis** [comment]
Please reopen if this remains relevant
