### ISSUE TITLE
[source-build] DotNetCliCommandLineVersion property is incorrectly named

### ISSUE THREAD

**Issue by dseefeld** [dotnet/templating#2044]
The `DotNetCliCommandLineVersion` property is incorrectly named, so it's not picking up the source-built package when building in source-build.  This is causing source-build to use a prebuilt version of Microsoft.DotNet.Cli.CommandLine.  The name of the property should be changed to `MicrosoftDotNetCliCommandLinePackageVersion`.

**Comment by vijayrkn** [comment]
@phenning - Can you please update this?

**Comment by donJoseLuis** [comment]
fixed
