### ISSUE TITLE
Installed templates are not persisted after SDK updates

### ISSUE THREAD

**Issue by GaProgMan** [dotnet/templating#2047]
### Steps to Recreate

1. Install vLatest -1 minor of the SDK (for example: 2.2.301)
1. Install a template (I have a number of them in a [repo that I maintain](https://github.com/GaProgMan/DotNet-New-Templates))
1. Verify that the template is installed with `dotnet new`
1. Install vLatest of the SDK (at the time of writing, this is 2.2.401)
1. List the installed templates
1. Template installed in step 2 is not listed

### Excepted Results

The template installed should be persisted across SDK updates.

### Background Information

I have seen this one Windows 10 vLatest, MacOS 10.14.6, and Debian derivatives of Linux (I use Pop!OS 19.04), and have seen this happen from the first public versions of `dotnet new3`.

My understanding is that templates are installed per SDK version, and that installing a new version of the SDK alters the PATH variable such that the dotnet binary for the highest version of the SDK is installed is used. This is a minor inconvenience, and I don't know of many other developers who see this issue.

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by bozturkMSFT** [comment]
Hi @GaProgMan,
 We have already delivered this in .NET 6.0, which should be available starting preview 4.
 Closing this one.
