### ISSUE TITLE
The table in "dotnet new" is too big

### ISSUE THREAD

**Issue by svick** [dotnet/templating#2062]
When I open a new terminal on Windows and run `dotnet new`, this is what I see:

![](https://user-images.githubusercontent.com/287848/62788671-acb03c80-bac7-11e9-8114-b7791975390c.png)

Notice that:

1. Most of the visible templates are some of the least used ones (I think). Accessing the interesting information requires quite a lot of scrolling or resizing the terminal window.
2. Many of the visible lines are empty (or almost empty), because the table is too wide.

I think this is not good enough, especially considering that this might be one of the first things a newcomer to .Net Core will see.

What I think should be done:

1. Decrease the width of the table.

    Since the only row that's wider than the default terminal window width is Razor Class Library (see the image above), this could be as simple as removing "Razor Class Library" from its tags.

2. Decrease the height of the table.

    The table currently contains 30 entries and some of them are for fairly niche technologies (e.g. Dotnet local tool manifest file) or contain lots of variations, some of which probably aren't commonly used (ASP.NET Core).

    Maybe the less commonly used items should be hidden when running `dotnet new` and only shown for `dotnet new --list`? Though I'm not sure how to decide how many items to show and which items to show by default (telemetry could help, but recent data is not available, at least not publicly: https://github.com/dotnet/core/issues/2213).

What do you think?

**Comment by Eilon** [comment]
I have a PR for this here: https://github.com/dotnet/templating/pull/2270
