### ISSUE TITLE
dotnet new strips our conditional compile code

### ISSUE THREAD

**Issue by davidortinau** [dotnet/templating#2079]
I have an `AppDelegate.cs` file in my project with the following code. It is being stripped out when `dotnet new` is executed. I have verified the code is present in my packed NuGet.

```
#if DEBUG
Comet.Reload.Init();
#if
```

Is there a way to escape this and protect it?

**Comment by dansiegel** [comment]
Yes @davidortinau you'll need to escape it in your AppDelegate like the following:

```cs
//-:cnd:noEmit
            // Code for starting up the Xamarin Test Cloud Agent
#if DEBUG
            Xamarin.Calabash.Start();
#endif
//+:cnd:noEmit
```

Keep in mind that all of your conditional properties and groups in the csproj will also be stripped out if you do not escape them.

```xml
  <PropertyGroup>
<!--/-:cnd:noEmit -->
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">iPhoneSimulator</Platform>
<!--/+:cnd:noEmit -->
    <ProductVersion>8.0.30703</ProductVersion>
    <SchemaVersion>2.0</SchemaVersion>
    <ProjectGuid>{00000000-0000-0000-0000-000000000000}</ProjectGuid>
    <ProjectTypeGuids>{FEACFBD2-3405-455C-9665-78FE426C6842};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
    <OutputType>Exe</OutputType>
    <RootNamespace>Company.Project.Mobile.App.iOS</RootNamespace>
    <IPhoneResourcePrefix>Resources</IPhoneResourcePrefix>
    <AssemblyName>Company.Project.Mobile.App.iOS</AssemblyName>
    <NuGetPackageImportStamp></NuGetPackageImportStamp>
    <BuildIpa>True</BuildIpa>
  </PropertyGroup>
<!--/-:cnd:noEmit -->
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|iPhoneSimulator' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\iPhoneSimulator\Debug</OutputPath>
    <DefineConstants>__UNIFIED__;__MOBILE__;__IOS__;DEBUG;ENABLE_TEST_CLOUD;</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <ConsolePause>false</ConsolePause>
    <MtouchArch>i386, x86_64</MtouchArch>
    <MtouchLink>None</MtouchLink>
    <MtouchDebug>true</MtouchDebug>
  </PropertyGroup>
<!--/+:cnd:noEmit -->

**Comment by davidortinau** [comment]
Per @sayedihashimi this is working for me:

```
//-:cnd
            #if DEBUG
            Comet.Reload.Init();
            #endif
//+:cnd
```

**Comment by sayedihashimi** [comment]
Regarding project files, I think that bug was fixed. Would be good to hear for sure though.

**Comment by dansiegel** [comment]
@sayedihashimi I don't believe that's a bug... Conditions are used to dynamically add/remove entire PropertyGroups and Properties, etc... it's ultimately the same issue you're seeing in the C# code where the condition evaluates to false thus it's stripped out

**Comment by sayedihashimi** [comment]
@dansiegel it was a bug and it was fixed see https://github.com/dotnet/templating/issues/1195

**Comment by davidortinau** [comment]
Where is this documented? I looked for similar with no luck.

```
//-:cnd:noEmit
```

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by vlada-shubina** [comment]
Related to: https://github.com/dotnet/templating/issues/1692, https://github.com/dotnet/templating/issues/1438

**Comment by vlada-shubina** [comment]
[Wiki ](https://github.com/dotnet/templating/wiki/Reference-for-comment-syntax#ignore-conditions-expressions-in-language-files) documentation was updated
