### ISSUE TITLE
Update Wiki with content to open file in IDE or browser

### ISSUE THREAD

**Issue by robertmclaws** [dotnet/templating#2087]
There is a section in the template.json reference that talk about presenting templates in groups (groupIdentity). It has a link to "https://github.com/dotnet/templating/wiki/_new#creation-of-multiple-tamplates-shown-as-one" that does not actually exist anymore. 

Also the wiki seems to be missing information on how to trigger the IDE or your web browser to open a file (https://github.com/dotnet/templating/wiki/Post-Action-Registry#open-a-file-in-the-editor).

Would be great if this could be fixed in such a way that explains this behavior, as I am curious how it works. Thanks!

**Comment by donJoseLuis** [comment]
Update the documentation for correctness

1. update the dead link
1. update info on triggering IDE or browser, if still relevant

**Comment by vlada-shubina** [comment]
Updated https://github.com/dotnet/templating/wiki/Post-Action-Registry#open-a-file-in-the-editor with description.
Removed "open a file in the web editor" post action as it is not implemented.

**Comment by vlada-shubina** [comment]
Related issue: https://github.com/dotnet/templating/issues/2384

**Comment by vlada-shubina** [comment]
Group identity reference is available in template.json schema and [Reference for template.json] (https://github.com/dotnet/templating/wiki/Reference-for-template.json). For the moment it was decided not to extend it. 
Linked PR will remove dead links from the article.

@robertmclaws if you are interested in anything specific about group identity which is not covered in existing docs, please let us know, will try to help you.
