### ISSUE TITLE
As a dotnet new user, I want Roslyn analyzer project templates, to enhance my productivity

### ISSUE THREAD

**Issue by alrz** [dotnet/templating#2113]
It would be nice to be able to run dotnet new analyzer|codefix to create roslyn analyzer/codefix projects.

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by StevenTCramer** [comment]
@donJoseLuis  I think this got lost.

**Comment by alrz** [comment]
I don't know it's already considered but `dotnet new generator` could be a new option to create C# 9.0 generator projects.

**Comment by alrz** [comment]
This probably should be closed. https://github.com/dotnet/roslyn-sdk/pull/612

**Comment by KathleenDollard** [comment]
Teams with expertise in specific areas own their templates (so we get the best brains on the template). Since Roslyn folks are looking at this, I am closing.
