### ISSUE TITLE
Access cmdline parameters from template config

### ISSUE THREAD

**Issue by RaphaelFourdrilis** [dotnet/templating#2114]
Hello,

I've been toying with the `dotnet new` templates in order to simplify my coworkers life, but I can't seem to find a way to reference cmdline parameters inside my config.
I'd like to be able to launch a postAction that runs a script inside the template, but when using the `-o` switch, my postAction cannot find the script, since it's not in `./whatever.cmd` anymore ...
I find this quite ... annoying, to say the least.
I've read through pretty much anything I can find on the wiki, but cannot seem to find anything related to referencing cmdline parameters. I'd basically want to be able to say:

```json
"postActions": [
    {
      "actionId": "3A7C4B45-1F5D-4A30-959A-51B88E82B5D2",
      "args": {
        "executable": "${targetDir}/launch.cmd"
      },
      "manualInstructions": [
        {
          "text": "Finishes project setup."
        }
      ]
    }
  ]
```

But this just tries to call `${targetDir}/launch.cmd`, which is obviously not what I was aiming for.

Am I missing something or is this just plain impossible?

PS: I've tried every syntax I could think of `{targetDir}` `${targetDir}` `$targetDir` ... I've tried with different variable names, like `name` and such, since the `-n` switch value would also work in my case, but to no avail.

**Comment by bravo-kernel** [comment]
Variables are not available in postActions as explained here https://github.com/dotnet/templating/issues/1728. The last comment has a hint on how to solve it using a `generated` variable.
