### ISSUE TITLE
How can I programmatically get template shortname?

### ISSUE THREAD

**Issue by foragerr** [dotnet/templating#2123]
For a bunch of custom templates we host in-house, I'm trying to write a bootstrap script that fetches and installs a template, generates code, and optionally sticks it our git repo.

After installing the template with 
```
dotnet new -i  template-name --nuget-source artifactory-url
```

I'd like to run 
```
dotnet new shortname
```

except shortname does not always match template-name. 

I could:
* unpack the nupkg file and parse .template.config/template.json to acquire shortname, but the downloaded .nupkg file location seems to vary by installed sdk version.

* parse the output of `dotnet new --list` but that isn't in a good machine parsable format. Also identity doesn't match template name or shortname anyway

Is there some other obvious option I'm missing?

**Comment by grinrag** [comment]
@foragerr actually, there is another way how to do this.
All the information about installed templates is in the cache `<USER>\.templateengine\dotnetcli\v3.1.200\en-US.templatecache.json`
So, this is a json file. You can parse it, before installation, build a list of shortnames for all installed templates. Then, after running the installation of new packages, you can parse the cache file again and build diff.

I'm closing this question issue. Feel free to reopen if you still have some problems.

**Comment by foragerr** [comment]
This isn't ideal in that the path to templatecache.json would vary by installed sdk version, similar to the problem with the unpacking-nuget approach in my original post. But it's better than nothing, will give it a shot.
