### ISSUE TITLE
Remove retired "AspNetCore.SpaTemplates" from WIKI

### ISSUE THREAD

**Issue by pedroreys** [dotnet/templating#2125]
In the [Available templates for dotnet new](https://github.com/dotnet/templating/wiki/Available-templates-for-dotnet-new) wiki page there is an entry for `Microsoft.AspNetCore.SpaTemplates::*` but those templates [have been retired](https://github.com/aspnet/Announcements/issues/289).

**Comment by donJoseLuis** [comment]
Update wiki page.

**Comment by vlada-shubina** [comment]
Mentioned templates were removed from the wiki page.
