### ISSUE TITLE
Derived parameter for file renaming

### ISSUE THREAD

**Issue by PeterAnaniaHC** [dotnet/templating#2126]
Guys I'm really sorry for bothering you, but I can't seem to find any information on derived parameters.

Specifically I'm trying to use this to rename a file, and I found a reference to: https://github.com/dotnet/templating/pull/1194

From this post: https://github.com/dotnet/templating/issues/1238

And I tried implementing the a derived parameter for file renaming as shown, but it wouldn't work for me. If I didn't supply the parameter in the dotnet new command (thinking it's derived why do i have to supply it?) I would receive an error that would say 'value cannot be null - key'. If I supplied the parameter with no value then I would get the same message, but with an addition 50 lines of errors. I didn't try it with name and value, because at that point I could just use a regular parameter. 

There's very little material about this online, can you give me a working example?

Thanks,

Peter

**Comment by vlada-shubina** [comment]
Documented in [this ](https://github.com/dotnet/templating/wiki/Reference-for-template.json#derived-symbol)article.
