### ISSUE TITLE
dotnet new -u - add double quotes on the list where the source is a folder that contains space

### ISSUE THREAD

**Issue by AClerbois** [dotnet/templating#2127]
Hello, 

I'm face to something interesting. 

When I'm executing the command ```dotnet new -u```, I retrieve the complete list of my installed dotnet template. 

This list contains the uninstall command to remove the template. But if your initial path contains spaces, it should be interesting to encapsulated the path with double quotes. 

![image](https://user-images.githubusercontent.com/50712277/65813324-1699b800-e1d4-11e9-95a2-670991763548.png)

Thank you,

Adrien C.

**Comment by LeaFrock** [comment]
I met this problem right now! If I don't add double quotes, the template can't be uninstalled and *CMD.exe* will tell '*Invalid Input Switch: ......*(Skip here)'.
Thank you for helping me!

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome
