### ISSUE TITLE
[Feature] Create an item template with an custom event handlers

### ISSUE THREAD

**Issue by doggy8088** [dotnet/templating#2130]
I'd like to have a feature that can create an item template with some event handlers.

For example, I need to create a set of classes in my existing project. Before/After generated files in my project, I'd like to modify some files of my project such as some config files or some other classes.

**Comment by bozturkMSFT** [comment]
Hi @doggy8088,
 Thanks for the issue. We seem to be already tracking this in #2148. 
 Please let us know if you think this should be a separate issue.
