### ISSUE TITLE
dotnet cli: dotnet new failed when there is a private nuget package

### ISSUE THREAD

**Issue by hanslai** [dotnet/templating#2133]
I have a private nuget package setup in Visual Studio.

![AIS Internal nuget](https://user-images.githubusercontent.com/20576491/66546180-0b00a680-eb6f-11e9-9ab5-43dcae189c23.png)

When I run the following CLI command `dotnet new -i "Amazon.Lambda.Templates::*"` in Powershell , `dotnet new `will failed with Status Code 401.   Please see error message below.

![Dotnet new failed with private nuget](https://user-images.githubusercontent.com/20576491/66546448-a0039f80-eb6f-11e9-8847-8edc5ed3c94b.png)

But if I unchecked my private nuget in Nuget Package Manager from Visual Studio.  Then the above `dotnet new` command will successfully restore the Templates.

Since having a private nuget package or not should not have anything to do with `dotnet new`. This CLI command should not failed.

Thanks

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by bozturkMSFT** [comment]
This is fixed in .NET 6 Preview 4.
