### ISSUE TITLE
Sorting and/or Filtering

### ISSUE THREAD

**Issue by bradygaster** [dotnet/templating#2134]
Has there ever been a discussion on providing sorting capabilities when someone calls dotnet new without a template? Like maybe items like these below. Adding an issue per discussion with @KathleenDollard
 
`dotnet new --sort name` (sorts by template name)
`dotnet new --sort short` (sorts by short name)
`dotnet new --filter WPF` (gives me only the templates that have WPF in their Tags)
`dotnet new --filter WPF --sort name` (2-hit combo)

**Comment by sayedihashimi** [comment]
For filter you can already do that with a partial match passed to `-l`, it's not ideal though. In the case that the name matches fully, all the results are not shown.

For example

```bash
> dotnet new bla -l
Usage: new [options]

Options:
  -h, --help          Displays help for this command.
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
  -o, --output        Location to place the generated output.
  -i, --install       Installs a source or a template pack.
  -u, --uninstall     Uninstalls a source or a template pack.
  --nuget-source      Specifies a NuGet source to use during install.
  --type              Filters templates based on available types. Predefined values are "project", "item" or "other".
  --dry-run           Displays a summary of what would happen if the given command line were run if it would result in a template creation.
  --force             Forces content to be generated even if it would change existing files.
  -lang, --language   Filters templates based on language and specifies the language of the template to create.
  --update-check      Check the currently installed template packs for updates.
  --update-apply      Check the currently installed template packs for update, and install the updates.


Unable to determine the desired template from the input template name: bla.
The following templates partially match the input. Be more specific with the template name and/or language.

Templates                   Short Name        Language      Tags
----------------------------------------------------------------------------------
Blazor Server App           blazorserver      [C#]          Web/Blazor
Blazor WebAssembly App      blazorwasm        [C#]          Web/Blazor/WebAssembly
```

**Comment by vlada-shubina** [comment]
There are already 2 filters implemented:
- by language: `dotnet new --language=C#` displays all templates for C# language
- by type: `dotnet new --type=project` displays all project templates. Possible types: `project, item, other.`

In .NET 5 release there will be some improvements to list functionality which can be used as filter by name:
- `dotnet new  con --list`  shows all the templates that has `con` in short name or name
- `dotnet new  console --list`  shows all the templates that has `console` in short name or name. 
https://github.com/dotnet/templating/issues/2491 fixes the limitation of exact match described above.
Filters by `--language` and `--type` can be applied together with `--list`.

Going forward, we are looking also to add a filter by tags: https://github.com/dotnet/templating/issues/2475 (this will be implemented post .NET 5 release).

Sorting is not available at the moment.

**Comment by KathleenDollard** [comment]
We agree! You should be able to filter and sort!!!

This will be fixed as part of finalizing List and Search after we switch to the new parser. 

We can close this issue if we think that work is sufficiently tracked elsewhere.
