### ISSUE TITLE
[Loc]Run “dotnet new --help” in Japanese, the output are not localized. 

### ISSUE THREAD

**Issue by Jepson109** [dotnet/templating#2137]
1.	Prepare a clean Japanese environment machine
2.	Install SDK [3.1.100-preview2-014562](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdotnetcli.blob.core.windows.net%2Fdotnet%2FSdk%2Frelease%2F3.1.1xx%2Fdotnet-sdk-latest-win-x64.exe&data=02%7C01%7Cv-pejian%40microsoft.com%7C356ba53cf70d499839d308d75d09592c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637080167041418611&sdata=U%2BHnkF2Dnjpb3qAKP8Gq62TOEohGNn4%2BZJGUc0wNjjA%3D&reserved=0)
3. Run “dotnet new --help” in Japanese

**Expected**: Output window should contain message in Localized language

**Actual**: The output are not localized. 
![image](https://user-images.githubusercontent.com/38854445/67837476-13bf1980-fb2a-11e9-9d15-4f8487ece694.png)
_-h, --help          Displays help for this command.
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
  -o, --output        Location to place the generated output.
  -i, --install       Installs a source or a template pack.
  -u, --uninstall     Uninstalls a source or a template pack.
  --nuget-source      Specifies a NuGet source to use during install.
  --type              Filters templates based on available types. Predefined values are "project", "item" or "other".
  --dry-run           Displays a summary of what would happen if the given command line were run if it would result in a template creation.
  --force             Forces content to be generated even if it would change existing files.
  -lang, --language   Filters templates based on language and specifies the language of the template to create.
  --update-check      Check the currently installed template packs for updates.
  --update-apply      Check the currently installed template packs for update, and install the updates._

Note: 
1. For German environment, the output are also not localized.
2. The output of dotnet –info are also not localized. The output of dotnet build --help are all localized.

**Dotnet --info**:
.NET Core SDK (global.json を反映):
Version:   3.1.100-preview2-014571
Commit:    4a0133f605

ランタイム環境:
OS Name:     Windows
OS Version:  10.0.16299
OS Platform: Windows
RID:         win10-x64
Base Path:   C:\Program Files\dotnet\sdk\3.1.100-preview2-014571\

Host (useful for support):
  Version: 3.1.0-preview2.19525.6
  Commit:  5672978d91

.NET Core SDKs installed:
  3.1.100-preview2-014571 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0-preview2.19528.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0-preview2.19525.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview2.19525.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes

**Comment by Jepson112** [comment]
This bug is also reported in the Turkye environment(SDK:3.1.200-preview-014977).

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by vdanche** [comment]
also repro on .net5 SDK.(SDK:5.0.100-preview.7.20357.4)

**Comment by DavidKarlas** [comment]
* Looks like problem is that https://github.com/dotnet/templating/blob/master/src/Microsoft.TemplateEngine.Cli.Localization/Microsoft.TemplateEngine.Cli.Localization.csproj is not included into SDK.
* We should also check updating localisations
* We should look for unlocalized use of Console.WriteLine

**Comment by vdanche** [comment]
@DavidKarlas checked on net6 preview 6 SDK on locale OS(e.g Chinese) we found that some strings still unlocalized.

SC:
![image](https://user-images.githubusercontent.com/65637796/122370758-ebe82800-cf91-11eb-8864-be84287ee05d.png)
![image](https://user-images.githubusercontent.com/65637796/122370998-1afe9980-cf92-11eb-8015-cd8239cec764.png)

**Comment by vlada-shubina** [comment]
@vdanche localizations are not yet merged for Preview 6, should arrive shortly. I merged some of them in preview 6, but probably they didn't make through yet due to installer insertion issue https://github.com/dotnet/installer/pull/10856.

**Comment by vdanche** [comment]
@vlada-shubina  Thanks your reply, vlada. we'll keep tracking as some strings still unlocalized.
e.g. JP
![image](https://user-images.githubusercontent.com/65637796/124090796-c249f900-da87-11eb-8731-45923f4be043.png)
![image](https://user-images.githubusercontent.com/65637796/124091613-9b3ff700-da88-11eb-8735-b88db412303c.png)
