### ISSUE TITLE
Is there a nicer API for this?

### ISSUE THREAD

**Issue by jzabroski** [dotnet/templating#2140]
Other than using the Visual Studio Project menu's Export Template menu, is there a fluent API for this so we don't twiddle with JSON?

The JSON document structure for templates looks like it was designed for consumption by Visual Studio, but not meant to be written by humans.

Ideally, I want to write `dotnet new` plug-ins as C# programs that use whatever templating system I want for customizing the wizard.  I imagine the reason it's not a C# program is that it enhances the trustworthiness of a template by making it pure data.  Even so, I would like a `dotnet metanew` keyword that would allow me to write C# programs that write json templates.

With Roslyn and expression tree [funcletization](https://code.google.com/archive/p/relinq/wikis/Funcletizer.wiki), there is almost no reason I need to write C# templates in anything but C#.

**Comment by jzabroski** [comment]
Given that dotnet templating is basically a re-write of yeoman, it might be inspiring for the team to look at something like Yeoman-Easily https://www.freecodecamp.org/news/creating-yeoman-generators-easily-with-yeoman-easily-cf552aef0d2f/

**Comment by brettrowberry** [comment]
Or perhaps something like Farmer https://compositionalit.github.io/farmer/. It was made for Azure’s ARM Templates (also JSON).

**Comment by vlada-shubina** [comment]
Couple of thoughts here:
- creating JSON configuration might become significantly easier when the template for template authors are done: https://github.com/dotnet/templating/issues/2722
- the idea above might be realized via implementing custom generator which will use other approach to configuration (not JSON, may be even C#). The generators are components and as of now only one exists (based on `template.json`). Custom generators might or might not use `TemplateEngine.Core` for actual template generation, it just needs to implement the `IGenerator` interface so `TemplateEngine.Edge` (apis) can work with it.  
Using custom generators will be fully supported by `dotnet new` or VS when the way to install the custom components will be exposed (https://github.com/dotnet/templating/issues/2942) - they will work with it through template engine API seamlessly as they currently do with `RunnableProjects` generator. Also we might need to look into a way how generator to run template is picked up, it might not be extensible at the moment. 

@baronfel could you please share your opinion here?

**Comment by jzabroski** [comment]
> we'd almost want something that could be installed globally (similar to dotnet tools), but centrally managed. We'd need a good story for managing these.

You do not want things to be installed globally. You want a local installation, and for templates to have clear target framework dependencies, such that if you try to use a template designed for .NET 6.0, and you don't have that installed, you would be asked to install it via Visual Studio. - In other words, You do not need a good story. You need a clear metadata format and reasoning for each element in that metadata format.

Here is my observation:

.NET/Visual Studio has:

* VStemplates - xml configuration with weird variable substitution rules for passing variables from parent to child.
* .NET Core Project Templates - json configuration with weird variable substitution rules for passing variables from parent to child.  Rules may or may not be due to some legacy nuget 1.0 conventions. Not sure. Packages can be hosted on nuget and should use a specific PackageType.

.NET Templating has a really weird, non-enjoyable syntax with lots of edge cases.  I personally hope it's de-commissioned.
