### ISSUE TITLE
Bringing new templates in the CLI means changing the version of the template engine.

### ISSUE THREAD

**Issue by livarcocc** [dotnet/templating#216]
We should not have to take a new template engine every time we need to update the new3 templates in the CLI.

A new template engine brings with it new code, new dependencies and the new templates, where we may only care about the new templates at the moment.

This just hit is now where our deb packaging in broken because we took a new template engine to update the templates and this version of the engine brought in conflicting versions.

Revving the engine and the templates should be done separately. Maybe with two separate versions.

**Comment by seancpeters** [comment]
This will be fixed in https://github.com/dotnet/cli/pull/5430
