### ISSUE TITLE
Exclusions not working for files without an extension

### ISSUE THREAD

**Issue by vb-software** [dotnet/templating#2174]
I have a template that I intend to create a Jenkinsfile and Dockerfile only if --useJenkinsfile is set to true.  Therefore, I added these files as exclusions if the condition is not true.

The files are still appearing regardless of the value of the flag.

I'm assuming it's because they don't have file extensions.

**Comment by RehanSaeed** [comment]
It seems I have a similar issue in https://github.com/dotnet/templating/issues/2208

**Comment by AR-May** [comment]
Hello @vb-software!  
I tried to reproduce the issue and I made the exclusion work with the following template.json: 
```
{
    "$schema": "http://json.schemastore.org/template",
    "author": "AR-May",
    "classifications": [ "Common", "Console" ],
    "identity": "Test.TemplateWithExclusionFileWithoutExtension",
    "name": "Test Template With Exclusion of File Without Extension",
    "shortName": "test-exclusions-file-without-extension",
    "sources": [{
      "source": "./",
      "target": "./",
      "modifiers": [{
        "condition": "(!useDockerfile)",
        "exclude": [
          "Dockerfile"
        ]
      }]
    }],
    "symbols":{
      "useDockerfile":{
        "type": "parameter",
        "dataType":"bool",
        "defaultValue": "false"
      }
    }
}
```

**Comment by AR-May** [comment]
I can not find any problems with exclusions of the files without an extension at the moment, so I close the issue. 
Please do not hesitate to reopen it and provide additional details about your template.json if this example is not helpful.
