### ISSUE TITLE
If conditions for .sln or alternative

### ISSUE THREAD

**Issue by vb-software** [dotnet/templating#2176]
In one of my templates, I have a useTests flag that will include test .csproj boilerplate.  I also have a .sln file in my template but find it difficult to have to support this with conditionals (and documentation does not mention .sln as an MSBuild project for conditionals).

Although I could use if/else for .sln if it is supported I actually foresee a better approach...

Can there be post steps in templates that run a dotnet command?

For instance, suppose my template does not have a solution, but based on all the .csproj in the template I could have a post step to create the solution with a given name and then add all .csproj files to the solution with the appropriate glob pattern.

**Comment by AshleyPoole** [comment]
@phenning @brianrob would you be able to shed some light of how if conditions could be done in solutions files? I tried using SpecialCustomOperations section in template.json to do an if statement in a .sln file but it didn't seem to work.

I need to be able to include an optional reference in the solution file that's in the template to a project outside of the template. Thanks in advance for any help!

**Comment by brianrob** [comment]
@AshleyPoole I can't say I've ever done anything involving conditionals in a solution file.  Not sure if @phenning has.

**Comment by vb-software** [comment]
It’s been a while since I first asked this but I have a workaround for my use case and unless this is an overwhelming need from others this could probably be closed.

**Comment by AshleyPoole** [comment]
@vb-software does you work around use an if in sln files and if so, something you could share?

**Comment by AshleyPoole** [comment]
@brianrob do you know anyone else familiar with the repo that could help?

**Comment by brianrob** [comment]
@rainersigwald do you know if this is possible?

**Comment by rainersigwald** [comment]
The solution file format doesn't allow conditionals as far as I know.

**Comment by brettrowberry** [comment]
It works. I just did it.

**Comment by AshleyPoole** [comment]
> It works. I just did it.

Have you got an example of the IF syntax you used @brettrowberry?

**Comment by brettrowberry** [comment]
I don’t have a public repository, but the syntax is:
```
#if (symbol-name == "value")
stuff
#endif
```

Make sure there is no space between the # and the if.

**Comment by vlada-shubina** [comment]
Added example to [wiki ](https://github.com/dotnet/templating/wiki/Reference-for-comment-syntax#solution-files) article, closing the issue.
