### ISSUE TITLE
dotnet new -i templates --nuget-source does not support --interactive auth

### ISSUE THREAD

**Issue by GregYankovoy** [dotnet/templating#2212]
Hi,

dotnet sdk version 3.1.100

Attempting to install dotnet CLI templates from a secured Azure Artifacts NuGet repository does not seem to be working.  The command correctly outputs that an --interactive authentication flow may be required.  However, the dotnet new -i command does not actually support the --interactive flag.  

Using the same repository, csproj dependencies can be restored via the CLI.  See below for command output.

```
dotnet new -i Test.Templates --nuget-source https://privatesource.pkgs.visualstudio.com/_packaging/Test/nuget/v3/index.json

C:\Program Files\dotnet\sdk\3.1.100\NuGet.targets(123,5): warning : The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet` [C:\Users\Greg\.templateengine\dotnetcli\v3.1.100\scratch\restore.csproj]

C:\Program Files\dotnet\sdk\3.1.100\NuGet.targets(123,5): error : Unable to load the service index for source https://privatesource.pkgs.visualstudio.com/_packaging/Test/nuget/v3/index.json. [C:\Users\Greg\.templateengine\dotnetcli\v3.1.100\scratch\restore.csproj]

C:\Program Files\dotnet\sdk\3.1.100\NuGet.targets(123,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Users\Greg\.templateengine\dotnetcli\v3.1.100\scratch\restore.csproj]
```

**Comment by GregYankovoy** [comment]
Hi @fabiomilheiro, I was able to find a workaround for the time being.  You can get cached nuget credentials to the private repository via dotnet restore --interactive (with a project incorporating a package from the protected repository).

The dotnet template installation command supports alternative NuGet sources, and actually suggests running with the interactive flag upon authentication failure. Just the command itself needs to support the --interactive as one of the parameters.

**Comment by GregYankovoy** [comment]
After looking through some open pull requests, it looks like someone took a first pass at correcting the problem:
https://github.com/dotnet/templating/pull/2064/commit

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by DaveMiscampbell** [comment]
So I just wanted to ask - now that #2276 is merged - does that mean this is resolved? Is there any idea of when we might be able to use `dotnet new -i --interactive` or still totally up in the air?

**Comment by vlada-shubina** [comment]
`dotnet new --install <package> --nuget-source <source> --interactive` should be supported since .NET 5. Also since .NET 6 preview 4, we switched to using NuGet API for managing NuGet installations, so it is also supported with `--update-*` commands as well.
Please feel free to open the issue in case of the problems with this feature.

**Comment by viliket** [comment]
@vlada-shubina Unfortunately `--interactive` flag does not seem to work with the `dotnet new` command - looks like it does not recognize this flag and therefore fails with 401 Unauthorized similar to @GregYankovoy's attempt. According to https://github.com/dotnet/templating/pull/2276, it looks like this flag is only supported with `dotnet restore` command.

My `dotnet --version` is `5.0.201`.

Currently I am using the workaround from https://github.com/dotnet/templating/issues/1747#issuecomment-616594663

Can you reopen this issue?

**Comment by vlada-shubina** [comment]
@viliket 

Until .NET 6 Preview 4 `dotnet new` was running `dotnet restore` to install the packages, that's why #2276 mentions it. 
To use `--interactive` flag, you still need to install credential provider, as mentioned in #1747 (first 2 steps, without -netfx option)

I've tested it on 5.0.201, and it works for me - see below:
```
C:\Users\WDAGUtilityAccount> dotnet --list-sdks
5.0.201 [C:\Program Files\dotnet\sdk]


C:\Users\WDAGUtilityAccount> dotnet new --install Microsoft.DotNet.Web.Spa.ProjectTemplates.6.0::6.0.0-preview.3.21201.13 --nuget-source <my nuget feed>
  Determining projects to restore...
C:\Program Files\dotnet\sdk\5.0.201\NuGet.targets(131,5): warning : The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet` [C:\Users\WDAGUtilityAccount\.templateengine\dotnetcli\v5.0.201\scratch\restore.csproj]
C:\Program Files\dotnet\sdk\5.0.201\NuGet.targets(131,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/internal/_packaging/dotnet5-internal/nuget/v3/index.json. [C:\Users\WDAGUtilityAccount\.templateengine\dotnetcli\v5.0.201\scratch\restore.csproj]
C:\Program Files\dotnet\sdk\5.0.201\NuGet.targets(131,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Users\WDAGUtilityAccount\.templateengine\dotnetcli\v5.0.201\scratch\restore.csproj]
Templates                                     Short Name           Language    Tags
--------------------------------------------  -------------------  ----------  ----------------------
Console Application                           console              [C#],F#,VB  Common/Console
Class library                                 classlib             [C#],F#,VB  Common/Library
<output cut>

C:\Users\WDAGUtilityAccount> dotnet new --install Microsoft.DotNet.Web.Spa.ProjectTemplates.6.0::6.0.0-preview.3.21201.13 --nuget-source  <my nuget feed> --interactive
  Determining projects to restore...
      [CredentialProvider]DeviceFlow:  <my nuget feed> 
      [CredentialProvider]ATTENTION: User interaction required.

      **********************************************************************

      To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code <code> to authenticate.

      **********************************************************************

```
I need more information to see what might be wrong for your case.
Could you please try to run `dotnet restore <csproj> --source <your source> --packages .\ --interactive` for the csproj file shim attached and check if it is successful? In csproj shim please replace placeholders with name and version of the package you are trying to install. 

This will be exactly the same action `dotnet new` is running to install the packages, but might give more information on the errors, especially in verbose mode.

Thanks.
[shim.zip](https://github.com/dotnet/templating/files/6516390/shim.zip)

(I will keep issue open to receive notifications)

**Comment by viliket** [comment]
@vlada-shubina Thanks, installing the [artifacts-credprovider](https://github.com/microsoft/artifacts-credprovider#automatic-powershell-script) with the command `iex "& { $(irm https://aka.ms/install-artifacts-credprovider.ps1) }"` followed by `dotnet new -i <package name> --nuget-source <Azure Artifacts package source> --interactive` works.

You may close the issue now.
