### ISSUE TITLE
[Bug] Cake Build (.cake) Files Not Supported

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/templating#2243]
I have a `build.cake` file that I am trying to do replacements in:

```c#
//#if (AppVeyor)
var foo = 1;
//#endif

#if (AppVeyor)
var bar = 2;
#endif
```

A [Cake build](https://cakebuild.net/) file is essentially a C# `.cs` file. When I run `dotnet new nuget --appveyor=true` or `dotnet new nuget --appveyor=false`, the output I always get is:

```c#
var foo = 1;

var bar = 2;
```

My understanding is that unsupported file types fall back to using `#` for the comments (which is why I also tried it above). In this case that doesn't seem true. Can support be added?

**Comment by vlada-shubina** [comment]
We're planning to work on this a bit later, let us know if anyone start working on it, so we don't work on this in parallel.

**Comment by vlada-shubina** [comment]
@RehanSaeed 

I've checked the scenario above, and `//#` syntax work for `.cake`. I'm adding also support for C# syntax.
Probably the reason why it doesn't work for you, is option syntax - options are case-sensitive, so probably it should be `dotnet new nuget --AppVeyor=true` (unless you added the synonyms in `dotnetcli.host json`).
