### ISSUE TITLE
Async Entry Point for ConsoleApp project template.

### ISSUE THREAD

**Issue by seesharprun** [dotnet/templating#2244]
I always wondered why the default **consoleapp** project template does not have an [asynchronous entry point](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-1#async-main)?

Here's the code I am referencing:

[template_feed/Microsoft.DotNet.Common.ProjectTemplates.3.0/content/ConsoleApplication-CSharp/Program.cs](https://github.com/dotnet/templating/blob/5bd81ea15df351cc042c7c48fce0f158a0586f9a/template_feed/Microsoft.DotNet.Common.ProjectTemplates.3.0/content/ConsoleApplication-CSharp/Program.cs#L7)

I would imagine that it would be updated to async by now:

```
using System;
using System.Threading.Tasks;

namespace Company.ConsoleApplication1
{
    class Program
    {
        static async Task Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```

Many APIs are now natively async so it would make sense to update the template.

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by grinrag** [comment]
@seesharprun thank you for the feature request. The template which we are shipping together with SDK will remain synchronous. Feel free to create your own custom template for `async` console app,  following the [documentation](https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates)
Also, you can publish this template and make it available for others.
