### ISSUE TITLE
Add support for 5.0 templates

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/templating#2245]
1. Install the latest SDK builds from `master` (e.g. 5.0.100-alpha.1.20073.4)
2. run `dotnet new console`
3. inspect the `TargetFramework` in the project

**Expected:**
The project would target 5.0

**Actual**
The project targets 3.1

4. run `dotnet new console --framework netcoreapp5.0`

**Expected:**
Error: Invalid parameter(s):
--framework netcoreapp5.0
    'netcoreapp5.0' is not a valid value for --framework (Framework).

**Actual**
The project is created targeting 5.0

**Comment by donJoseLuis** [comment]
f
