### ISSUE TITLE
Can not get the template pack to install with certain folder included

### ISSUE THREAD

**Issue by scottkirwanthomas** [dotnet/templating#2266]
Hi,

I've created a template pack for a solution that contains everything we need for our project.

As part of the solution, we include an opencover folder (attached as a zip) this is required for our dev ops process.

The issue I have is if i include this folder, the package never installs with dotnet new but if i take it out the package installs fine.

Is this by design? 
[opencover.zip](https://github.com/dotnet/templating/files/4185063/opencover.zip)

**Comment by Thraka** [comment]
It would be easier to see your template project used to generate the nuget package.

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by donJoseLuis** [comment]
Hello @scottkirwanthomas , can you please share the relevant template project?

**Comment by grinrag** [comment]
Hi, @scottkirwanthomas . Actually, it is not by design, you can include additional directories. But in the zip file, you attached not information about your template. Looks like this is `nupkg` for opencover.
Could you, pls, double check it?
