### ISSUE TITLE
[feature] Add project(s) to a solution directory

### ISSUE THREAD

**Issue by peterbomers** [dotnet/templating#2274]
The post action `Add project(s) to a solution file` with id `D396686C-DE0E-4DE6-906D-291CD29FC5DE` allows us to add projects to an existing solution. 

It's however not possible to add a project to a solution folder inside the existing solution.
The dotnet cmd used by the template engine supports this by adding the `--solution-folder` argument. 

It would be nice if could specify it like this:
```json
  "postActions": [
    {
      "description": "Add projects to solution",
      "manualInstructions": [],
      "primaryOutputIndexes": "0",
      "solutionDirectory":  "unit-tests",
      "actionId": "D396686C-DE0E-4DE6-906D-291CD29FC5DE",
      "continueOnError": true
    }
  ]
```

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by vlada-shubina** [comment]
The feature is implemented, JSON schema and documentation is updated
