### ISSUE TITLE
Add Dev Container templates

### ISSUE THREAD

**Issue by eerhardt** [dotnet/templating#2297]
I should be able to do the following:

```sh
dotnet new api
dotnet new devcontainer
```

And my directory would look roughly like

https://github.com/microsoft/vscode-remote-try-dotnetcore/

specifically I would have a `.devcontainer` folder that was set up for usage in VS Code (See https://code.visualstudio.com/docs/remote/containers).

Making it easier to get a `.devcontainer` folder up and running with my application would be great. That way I wouldn't have to go find a sample on the web, and copy-paste it into my folder.

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by baronfel** [comment]
Generally in favor of this, but it's hampered somewhat by VSCode giving a nice experience when adding devcontainer configurations to a repo that doesn't have them already:

![image](https://user-images.githubusercontent.com/573979/163062075-e3b933d9-5942-410e-8b98-8d340cadbe9d.png)

![image](https://user-images.githubusercontent.com/573979/163062092-5de55601-f866-4856-a29c-a5436e157b5f.png)

These do basically all of what a simple app would need (though there should be F# examples as well for completeness, likely drawn from the setup that dotnet/fsharp has already done in their repo).

**Comment by baronfel** [comment]
I forgot to note that this list of pre-configured devcontainer configurations is maintained by vscode [here](https://github.com/Microsoft/vscode-dev-containers), so one potential pathway for us (similar to the editorconfig and gitignore discussions we'd been having) is creating templates based off of these remote resources in an automated or semi-automated process that watches for changes and absorbs them automatically.

**Comment by YuliiaKovalova** [comment]
Closing in favor of using VS Code.
