### ISSUE TITLE
Replace different strings

### ISSUE THREAD

**Issue by marclena** [dotnet/templating#2302]
Hi I have created a templatre with some parameters
"symbols": {

    "slnName": {
      "type": "parameter",
      "datatype": "string",
      "isRequired": true,
	  "replaces": "Vueling.XXX",
      "fileRename":"Vueling.XXX"

This works ok,it replaces all the strings like Vueling.XXX with the value yoiu pass on the command line.
However apart of replacing the value Vueling.XXX I would like to replace also with the value of the parameter all the strings Vueling_XXX
So what I want is to replace difreent strings with the value passed on the -slnName parameter
Thanks

**Comment by vlada-shubina** [comment]
@marclena you can use value forms to achieve desired behavior.

```
"slnName": {
  "type": "parameter",
  "datatype": "string",
  "isRequired": true,
  "replaces": "Vueling.XXX",
  "fileRename":"Vueling.XXX",
  "forms" : {
		"global": [ "underscore" ]
   }

...
"forms": {
    "underscore": {
      "identifier": "replace",
	  "pattern": "\\.",
	  "replacement":"_"
    }
},
```
Forms defines which other matches should be replaced except exact match. As one of the form you can use regex transformation which define other value to be replaced.

Please take a look on this article for more details - https://github.com/dotnet/templating/wiki/Runnable-Project-Templates---Value-Forms 

Thanks.
