### ISSUE TITLE
dotnet new --update-* searches source only in public feed

### ISSUE THREAD

**Issue by nuzolx** [dotnet/templating#2308]
Hi,

You can install packages from a private event feed if it's little bit tricky without --interactive option.
However, as far as I understand, the update search is only done from the public feed (from a blob storage).

Would it be possible to manage private feeds for both installation and update?

Thanks for your help.

**Comment by donJoseLuis** [comment]
greetigns @grinrag , can Phil & you please discuss this one?  

- Basically, is private feed support for install & update currently available?

**Comment by nuzolx** [comment]
@donJoseLuis You can install and _update_ from private feed. But only with '`new -i foo --nuget-source bar`'.
My issue is about '`new --update-check`' and '`new --update-check`'.

We can say that it works but it would still be cool to have it, without being mandatory.
All the same what is done with the templates is worderful!

**Comment by brettrowberry** [comment]
Potentially related to #2398

**Comment by vlada-shubina** [comment]
Need to investigate whether it is possible to get source of package (file system, nuget public feed, nuget private feed) after installation of template.

**Comment by vlada-shubina** [comment]
The fix will be delivered in https://github.com/dotnet/templating/issues/2592.

**Comment by donJoseLuis** [comment]
@nuzolx greetings.  Please track #2592 for resolution to the request.  Closing this to consolidate relevant backlog items.
