### ISSUE TITLE
uninstall templates by short name

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/templating#2337]
Extracted from #1750 which tracked many issues

Quoting an entry from the above  issue...
 short name or name are intentionally not unique, they are used as a beginning disambiguator for which set of content to use. Consider the short name console - there's a template for the 1.0/1.1 targeting flavor of console, 2.0, 2.1, 2.2 and 3.0, each is a different template in a different package, multiple can be installed at the same time and they collapse into a single display template (as determined by groupId) and are addressable by the short name of at least one of the individual templates. Each one of these comes in a separate package (console happens to ship in the same package as class library), and install happens at the package (or directory) level, not on a template by template basis. These things combine to make something like dotnet new -u console very ambiguous - should it remove just the default console or everything that exists in any group addressable by the name console? Should it remove the package that delivered it (which would remove class library as well) or just that template? If you update the package, should it somehow prevent console from coming back or allow it? What's the process for getting sub-package/directory content back once uninstalled?

**Comment by donJoseLuis** [comment]
quoting an entry from #1750 

 short name or name are intentionally not unique, they are used as a beginning disambiguator for which set of content to use. Consider the short name console - there's a template for the 1.0/1.1 targeting flavor of console, 2.0, 2.1, 2.2 and 3.0, each is a different template in a different package, multiple can be installed at the same time and they collapse into a single display template (as determined by groupId) and are addressable by the short name of at least one of the individual templates. Each one of these comes in a separate package (console happens to ship in the same package as class library), and install happens at the package (or directory) level, not on a template by template basis. These things combine to make something like dotnet new -u console very ambiguous - should it remove just the default console or everything that exists in any group addressable by the name console? Should it remove the package that delivered it (which would remove class library as well) or just that template? If you update the package, should it somehow prevent console from coming back or allow it? What's the process for getting sub-package/directory content back once uninstalled?

**Comment by xtrmstep** [comment]
It's actual to me also.
Actually, I cannot uninstall a template even specifying a full absolute path.

**Comment by bozturkMSFT** [comment]
Uninstalling by short name is not possible by design, because templates are installed with "packages" (nuget packages, specifically).
We have improved the user experience though to help you uninstall templates more easily. Here is the output you would get today:

> dotnet new -u roslyn-sg
The template package 'roslyn-sg' is not found
The template 'roslyn-sg' is included to the packages:
Community.RoslynTemplates::1.0.3 (contains 1 templates)
To uninstall the template package, use dotnet new -u Community.RoslynTemplates
