### ISSUE TITLE
ability to see a version in the list of installed templates

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/templating#2338]
issue extracted from #1750 

quote from the above issue...
version in terms of individual templates is also one of those things that seems like a straightforward proposition but really is not. Version may not apply at all (at least not in a meaningful way) to templates if installed from a disk location, network share, or (eventually) a git repo. Even in the installation via package case, multiple packages at multiple versions can contribute to the same "display template", displaying all that information could be quite verbose & we often get complaints about the list mode overrunning the console buffer already. That's not to say that the current design for the list view must be adhered to, but if it's not wide like it is now, it'll likely need to convert to being long & more entries in a long list make the list less useful. There's a possibility of listing all the contributing templates' source/version (if applicable) information in detailed help for an individual template - similar to how we present provenance information in the new Web Application project dialog.

**Comment by bozturkMSFT** [comment]
There is another issue for this work item. Please track it here #2908.
