### ISSUE TITLE
Add post actions to templates to run restore after creation

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/templating#234]
This would impact project context templates only.

This is the change per the suggestion here https://github.com/dotnet/cli/issues/5444#issuecomment-275292388

**Comment by seancpeters** [comment]
Support for this is implemented in #242

**Comment by RehanSaeed** [comment]
So adding the following will cause a dotnet restore on project creation? Is the advice that we should add this to all project templates? When will this feature be released?

```
"PostActions": [
  {
    "Description": "Run dotnet restore",
    "ActionId": "210D431B-A78B-4D2F-B762-4ED3E3EA9025",
    "ContinueOnError": "false",
    "ManualInstructions": [
      {
        "Text": "Run 'dotnet restore' in the directory the template was created in."
      }
    ]
  }
]
```

**Comment by seancpeters** [comment]
Yes, adding this to a template will cause dotnet restore to try to run automatically when the template is created. 

We are not adding this to the built-in templates. @sayedihashimi - can you comment on our plans / best practices for using the restore post action in the future?

**Comment by seancpeters** [comment]
@RehanSaeed I need to clarify: this functionality is not it the current release bits. It's in the rel/vs2017/post-rtw code.

**Comment by RehanSaeed** [comment]
Why would the built in templates not include this? Is there a reason not to?

**Comment by mlorbetske** [comment]
There's been a bit of debate on whether this is the desired default behavior, so we've left it out for now while consensus is reached
