### ISSUE TITLE
Fix error message when provided template doesn't exist.

### ISSUE THREAD

**Issue by grinrag** [dotnet/templating#2347]
If the provided template name doesn't exist, would be better to show information of how to list all available templates.
```
$ dotnet new NotExists

No templates found matching 'NotExists'.

To list installed templates: dotnet new --list.
```

This issue is a result of splitting #725

**Comment by grinrag** [comment]
The conclusion after discussion with PM. We neither should show the list of installed templates nor try to search the matching templates online. 

For the searching online, there should be an additional option and the result should be a well-formatted table. I am going to create a new issue for this.

**Comment by danroth27** [comment]
> For the searching online, there should be an additional option and the result should be a well-formatted table. I am going to create a new issue for this.

Can this decision be reconsidered? We have some plans to move some of the templates that currently ship in the SDK to instead ship out of band. This plan partially relies on the template search experience provided by the SDK. We have been assuming that if the user tries to generate a template that they previously assumed was installed with the SDK but is now shipping as a NuGet package, that they would get a  message telling them how to install the template.

@DamianEdwards
