### ISSUE TITLE
More informative help message for '--install' and '--uninstall' options

### ISSUE THREAD

**Issue by genalt** [dotnet/templating#2348]
Help for the install and uninstall should show more information about the usage of these options, than just general help about `dotnet new`

Expected result:

See the [ proposal and diff for install](https://github.com/sayedihashimi/sayed-tools/pull/12/files#diff-a5c12d0d3e5643dc60e013dad95bc51c)

See the [ proposal and diff for uninstall](https://github.com/sayedihashimi/sayed-tools/pull/12/files#diff-6085e18fc6aa2fe22158418886078d9e)

We would like to have a message like in the proposal.

This issue is a result of splitting #725

**Comment by bozturkMSFT** [comment]
This issue was delivered https://github.com/dotnet/templating/issues/2918
