### ISSUE TITLE
More information about template in the help message if '-h' provided

### ISSUE THREAD

**Issue by genalt** [dotnet/templating#2349]
In case if '-h' option was provided after a template name, we should emphasise our help message on that template. For example, first, show the template information and then general help for the `dotnet new` itself.

This issue is a result of splitting #725

**Comment by grinrag** [comment]
This item needs more discussion with PM, update the item with result.

**Comment by grinrag** [comment]
The result of the discussion with PM: in the help message of a particular template, it's not necessary to show general help about `dotnet new` usage.
