### ISSUE TITLE
sdk 3.1.201 omits hidden files

### ISSUE THREAD

**Issue by theimowski** [dotnet/templating#2350]
For [this](https://github.com/SAFE-Stack/SAFE-template/blob/master/SAFE.Template.proj) template project, when using .NET SDK 3.1.201, it doesn't include the `.gitignore` or `.editorconfig` files in the nupkg.
When packing with .NET SDK 3.1.101 includes these files.
Not sure if this is part of the templating engine, or maybe nuget pack command itself?

**Comment by grinrag** [comment]
I am going to discuss this issue with @phenning 
Then we will decide how to proceed with the issue. If it belongs to us, we will assign priority and put it into the right bucket.

**Comment by grinrag** [comment]
This issue is not related to the templating engine itself.  It looks like a behavior change for dotnet pack. 

Adding the following to the project resolves the issue:
```xml
        <NoDefaultExcludes>true</NoDefaultExcludes>
```

@theimowski I am closing this issue, If you still have some problems, feel free to reopen it.

**Comment by theimowski** [comment]
Thanks @grinrag - `NoDefaultExcludes` does the job 👍
