### ISSUE TITLE
Enable previewing vaule replacement consequences

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/templating#2356]
Currently the template authoring UX suffers from unpredictable values replacement
- lacking capability to show replacements’ consequences
- ideally could simulate what the file will look like without needing to build

What's desired in this issue is to enable previewing the outcome of value replacements.

**Comment by vlada-shubina** [comment]
Related to template testing, to be discussed further.

**Comment by vlada-shubina** [comment]
@donJoseLuis is this issue same as https://github.com/dotnet/templating/issues/2357? https://github.com/dotnet/templating/issues/2357#issuecomment-624951511 states exactly same requirements.

**Comment by vlada-shubina** [comment]
Moving to Low Prio backlog until feedback on #2357 or above is provided.

**Comment by donJoseLuis** [comment]
please re-triage, potentially a dup.

**Comment by AR-May** [comment]
This issue also concerns testing. It is similar to #2357 but seems not the same. Here we would like to get only a list of replaces, not whole files, which may be too big.

**Comment by KathleenDollard** [comment]
Is this for template authors or end users? If authors, is this making the tool @DavidKarlas created available?

**Comment by DavidKarlas** [comment]
I think its reasonable to close this issue and point people to https://github.com/davidkarlas/watchtemplate
