### ISSUE TITLE
Improve managing templates with many auth options

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/templating#2357]
- large amount of template required code
- difficult to read the files with so many options

Example: [Razor Startup.cs](https://github.com/dotnet/aspnetcore/blob/master/src/ProjectTemplates/Web.ProjectTemplates/content/RazorPagesWeb-CSharp/Startup.cs)

**Comment by donJoseLuis** [comment]
Need to understand from the aspnet team what specific deliverable is desired to improve this UX.

**Comment by grinrag** [comment]
Probably, our next steps will be:

1. Discuss the problem with ASP.Net guys.
2. Assign the right priority.
3. Investigate & Discuss possible solutions within our team.

**Comment by mkArtakMSFT** [comment]
Thanks for trying to improve this, folks.
Here is one proposal we've discussed last time we've talked about this with Jose.

## The problem
The way to validate template changes at the moment is to make the changes, get a build, install it and then create a new project with a specific options.
This is quite lengthy process.

## Proposal
It would be great if we could have a mechanism to `dry-run` the templating engine for a given template. Imagine having a command-line utility which will allow us to generate an output of a template by giving all the values the template needs.

For example if the following is a template (note, this is just an example, and not a real template  format):

```
/// myTemplateName
This is my $(projectName) which.

if ($(authEnabled) == "true")
{
   This template supports authentication.
}
```

The required parameters for this would be `projectName` and `authEnabled`. So the utility would require these two parameters to be specified as an input for a dry run, as follows:

```
template-process myTemplateName --projectName:firstProject --authEnabled:true
```

and the expectation would be for this to generate the following content:

```
This is my firstProject which.

This template supports authentication.
```

**Comment by mkArtakMSFT** [comment]
@javiercn, @pranavkm and @ryanbrandenburg do you have any other suggestions regarding how this could be simplified, given that you've worked on templates a lot.

**Comment by ryanbrandenburg** [comment]
@mkArtakMSFT that's a pretty good suggestion. It doesn't improve the actual readability of the templated syntax, but it does reduce the infrastructure and turnaround needed to test combinations, which is probably the next best thing. It also has the side-benefit of reducing the [amount of infrastructure needed to run automated tests](https://github.com/dotnet/aspnetcore/blob/master/src/ProjectTemplates/Shared/TemplatePackageInstaller.cs) on templates (maybe that's what's meant by bulletpoint 1 and it's not a side-benefit at all).

My only idea to improve this experience is some tooling magic to detect a templated project and fold away code that won't be used with a particular combo of template options. That would reduce the "dev loop" size considerably, but I would imagine that's a significantly larger investment than @mkArtakMSFT's suggestion (especially since you'd likely have to implement it for VS and VSCode).

**Comment by vlada-shubina** [comment]
@mkArtakMSFT @ryanbrandenburg I would like to follow up on that. 

For dry-run suggestion, at the moment dotnet new has `--dry-run` option.  
The output for this option is as following:
```
dotnet .\dotnet-new3.dll console --dry-run
File actions would have been taken:
  Create: netcoreapp2.1.csproj
  Create: Program.cs

Processing post-creation actions...
Action would have been taken automatically:
  Restore NuGet packages required by this project.
```
However, this doesn't show the actual contents of the files.  
What I can suggest at this point, what if we modify this feature to include file contents, as example:
```
dotnet .\dotnet-new3.dll console --dry-run --preview-files --param1 value1 -- param2 value2
File actions would have been taken:
  Create: netcoreapp2.1.csproj
<file content goes here>
  Create: Program.cs
<file content goes here>

Processing post-creation actions...
Action would have been taken automatically:
  Restore NuGet packages required by this project.
```
Also how do you plan to use it in automated tests? Would it be easier if content is in file instead?

@ryanbrandenburg for your suggestion: as far as I understand you'd like it to built as UI tool, possibly VS/VSCode extension correct?

**Comment by vlada-shubina** [comment]
@KathleenDollard: just fyi, this is another topic related to template testing.

**Comment by vlada-shubina** [comment]
Moving to Low Prio backlog until feedback is provided.

**Comment by vlada-shubina** [comment]
Closing the issue due to no timely feedback. Please do not hesitate to reopen it if needed. 
We are also considering implementing another means of template testing next year.

**Comment by mkArtakMSFT** [comment]
Hi @vlada-shubina.
Just saw the notification about this being closed.
Printing the file content inline will lead to an unacceptable experience. Imagine a project template with many more files with 50+ lines of code each. Printing all that on a console will make it unreadable. I guess the --dry-run can still work, if you will also provide some output parameter where to place the generated files. On the other hand, won't that be the same as running the command without `dry-run` ?
