### ISSUE TITLE
Update MonoGame wiki entry

### ISSUE THREAD

**Issue by Jjagg** [dotnet/templating#2361]
Hey there! Could someone please edit the MonoGame entry in the [wiki](https://github.com/dotnet/templating/wiki/Available-templates-for-dotnet-new#c-templates)?

From:

```| [MonoGame (.NET Core)](https://github.com/cra0zy/MonoGame/tree/core) | `dotnet new -i "MonoGame.Template.CSharp"` |```

To:

```| [MonoGame](https://github.com/MonoGame/MonoGame) | `dotnet new -i "MonoGame.Templates.CSharp"` |```

**Comment by harry-cpp** [comment]
You mean to:

```
| [MonoGame](https://github.com/MonoGame/MonoGame/tree/develop) | `dotnet new -i "MonoGame.Templates.CSharp"` |
```

**Comment by grinrag** [comment]
@Jjagg nice catch! fixed.

**Comment by Jjagg** [comment]
Thanks!

**Comment by harry-cpp** [comment]
Ugh, you only fixed the url, not the package name, "MonoGame.Template.CSharp" is deprecated, was one of my personal packages for .NET Core version of MG, and instead "MonoGame.Templates.CSharp" should be used.

**Comment by Jjagg** [comment]
Oops yes, I didn't check the change. @grinrag could you please copy over the line from my first comment? There's 3 changes:
- remove '(.NET Core)'
- Point to official repo
- MonoGame.Template.CSharp -> MonoGame.Templates.CSharp

**Comment by WardBenjamin** [comment]
Hello, this issue is still outstanding. The wiki page is a high ranking search result, and the requisite changes have not been made.
