### ISSUE TITLE
Can't Update MonoGame Templates

### ISSUE THREAD

**Issue by FloatingSunfish** [dotnet/templating#2362]
I'm using `dotnet 3.1.201` and saw an update for the MonoGame templates:

    dotnet new --update-check
    Updates are available for the following:
    An update for template pack MonoGame.Template.CSharp::3.7.0.7 is available.
    install command: dotnet new -i MonoGame.Template.CSharp::3.7.0.7

(NOTE: You can also see that there's an update when creating a new MonoGame project: e.g. `dotnet new mgdesktopgl -o MyProject`.)

However, I can't seem to update the MonoGame templates.
Running the above install command does not seem to have any effect.
The `--update-apply` flag doesn't seem to work either:

    dotnet new --update-apply
    An update for template pack MonoGame.Template.CSharp::3.7.0.7 is available.
    install command: dotnet new -i MonoGame.Template.CSharp::3.7.0.7
    Updating...
    Restore completed in 251.97 ms for C:\Users\Admin\.templateengine\dotnetcli\v3.1.201\scratch\restore.csproj.
    ...Update succeeded

Installing and uninstalling the templates doesn't help as well:

    dotnet new --uninstall MonoGame.Template.CSharp
    dotnet new --install MonoGame.Template.CSharp

Any advice on how to update the templates?

**Comment by harry-cpp** [comment]
MonoGame.Template.CSharp has been deprecated, and instead MonoGame.Templates.CSharp should be used.

The wiki page needs to be updated: https://github.com/dotnet/templating/issues/2361#issuecomment-613421909

**Comment by FloatingSunfish** [comment]
@harry-cpp Noted, thanks!
