### ISSUE TITLE
Can a defaultValue parameter be generated?

### ISSUE THREAD

**Issue by onelioubov** [dotnet/templating#2367]
Hi there!

I'm not sure if this is possible or not, but couldn't find anything on it so I'm hoping I could find some help here.

I would like to be able to specify a port parameter for some files in my template. I would like for this parameter to be optional; however, instead of having a specific set default value, I want is to be able to generate a port in a specific range. 

I can have it generate a port for me without a problem if the parameter itself is generated. For example (these aren't the actual ports I used, but wanted to have something to fill with):

```    
"port": {
   "type": "generated",
   "generator": "port",
   "parameters": {
      "low": 8000,
      "high": 8099
   },
   "replaces": "8080"
},
```

Now, I want to be able to optionally have the template user provide a port as a parameter, but if no parameter is specified, have it generate a port in a specific range; however, I'm not sure how to go about it. I tried creating a symbol of type "parameter" instead; however, it defaulted to the value I'm trying to replace (if no port parameter is passed in). Is there a way to reference the generated symbol I mentioned above as the defaultValue in another parameter symbol? If not, is there any other recommended way to accomplish this? 

Thank you for taking the time to read this :)

**Comment by grinrag** [comment]
@onelioubov could you, please, provide a link to a repo with template project?

**Comment by onelioubov** [comment]
The template I created is hosted in a private repo with a different provider and works fine - there isn't anything to troubleshoot there 😄. It's really just a value replacement and I was hoping to get guidance on how to change the part of the sample code I mentioned above to also work for an optional value to be passed into the command line when using the template. For example, I want to be able to run the following command:

`dotnet new <name-of-template> --port <desired-port-number>`

In this case, `--port` is an optional parameter. If it is not passed in, it should default to generating a random port for me. I have no problem with it taking in an optional parameter (and setting a static default value if that switch isn't used). An example template.json file for this:

```
"$schema": "http://json.schemastore.org/template",
  "author": "Human Who Wrote This",
  "classifications": [ "Api" ],
  "identity": "Example.Template",
  "name": "An Example Template",
  "shortName": "example-template",
  "tags": {
    "language": "C#",
    "type": "item"
  },
  "symbols": {
    "port": {
      "type": "parameter",
      "datatype": "integer",
      "description": "This is an optional port parameter",
      "defaultValue": "8080",
      "replaces": "8080",
      "isRequired": false
    }
  },
  "sources":[{
    "modifiers": [{
      "exclude": [
        "**/[Bb]in/**",
        "**/[Oo]bj/**",
        ".template.config/**/*",
        "**/*.filelist",
        "**/*.user",
        "**/*.lock.json",
        "**/.vs/**",
        "**/.vscode/**",
        "**/.git/**"
        "**/.tmp/**"
      ]
    }]
  }]
}
```

I also don't have a problem with it generating a port in a specific range for me (and not having an optional parameter). An example template.json file for this:

```
"$schema": "http://json.schemastore.org/template",
  "author": "Human Who Wrote This",
  "classifications": [ "Api" ],
  "identity": "Example.Template",
  "name": "An Example Template",
  "shortName": "example-template",
  "tags": {
    "language": "C#",
    "type": "item"
  },
  "symbols": {
	"port": {
	   "type": "generated",
	   "generator": "port",
	   "parameters": {
		  "low": 8000,
		  "high": 8099
	   },
	   "replaces": "8080"
	}
  },
  "sources":[{
    "modifiers": [{
      "exclude": [
        "**/[Bb]in/**",
        "**/[Oo]bj/**",
        ".template.config/**/*",
        "**/*.filelist",
        "**/*.user",
        "**/*.lock.json",
        "**/.vs/**",
        "**/.vscode/**",
        "**/.git/**"
        "**/.tmp/**"
      ]
    }]
  }]
}
```

Both of these examples replace any occurrence of `8080` in the code and they work fine by themselves; however, the functionality that I'm hoping to get is one that is combined. This is my best example of it (it doesn't work, but I'm hoping it shows what I'm trying to attain):

```
"$schema": "http://json.schemastore.org/template",
  "author": "Human Who Wrote This",
  "classifications": [ "Api" ],
  "identity": "Example.Template",
  "name": "An Example Template",
  "shortName": "example-template",
  "tags": {
    "language": "C#",
    "type": "item"
  },
  "symbols": {
    "port": {
      "type": "parameter",
      "datatype": "integer",
      "description": "This is an optional port parameter",
      "defaultValue": {
		"type": "generated",
		"generator": "port",
		"parameters": {
			"low": 8000,
			"high": 8099
	          }
	  },
      "replaces": "8080",
      "isRequired": false
    }
  },
  "sources":[{
    "modifiers": [{
      "exclude": [
        "**/[Bb]in/**",
        "**/[Oo]bj/**",
        ".template.config/**/*",
        "**/*.filelist",
        "**/*.user",
        "**/*.lock.json",
        "**/.vs/**",
        "**/.vscode/**",
        "**/.git/**"
        "**/.tmp/**"
      ]
    }]
  }]
}
```

For this example, I basically took the `generated` port symbol and placed it in the defaultValue of the `parameter` symbol. I know this doesn't work, but I want to know if there is another way that does. Once again, I'm trying to give the template user the option of passing in their own port or have it generate a random one in a specific range that is not in use on their machine. I'm trying to avoid port conflicts so I don't want to have it default to a static one 😄

**Comment by DavidJFowler** [comment]
Hi @onelioubov 

Would [coalesce](https://github.com/dotnet/templating/wiki/Available-Parameter-Generators#coalesce) do what you want?

**Comment by onelioubov** [comment]
This is exactly what I needed. Thank you!

When I originally looked at it, I think I misunderstood its purpose, but this is definitely what I was looking for. 😄
