### ISSUE TITLE
`update-*` commands are not working

### ISSUE THREAD

**Issue by cilerler** [dotnet/templating#2369]
### Reproduction steps

1. Install an old version of a template via `dotnet new --install "Burcin.Templates.CSharp::1.2.21" --nuget-source https://api.nuget.org/v3/index.json`

2. Confirm that the installed version of the template is **1.2.21** via `dotnet new -u`, it should be located at the end of the output

3. Run the command `dotnet new "Burcin.Templates.CSharp" --update-check` or `dotnet new --update-check`

It returns `No updates were found.` even the latest version is different than the **1.2.21**

### Expected result

If the template has been provided, it should update only the provided template to the latest version. Otherwise, it should update all the existing templates on the system.

**Comment by grinrag** [comment]
@cilerler thank you very much for the issue. I will check it out.

**Comment by brettrowberry** [comment]
Related to #2398

**Comment by vlada-shubina** [comment]
The fix will be delivered in https://github.com/dotnet/templating/issues/2592.

**Comment by vlada-shubina** [comment]
We implemented check via NuGet API (available in main branch), now the update information is available immediately.
Also API is forced not to use cache, so issue of local NuGet cache being old also eliminated (https://github.com/dotnet/templating/issues/2874) .
