### ISSUE TITLE
How to modify appsettings.json depending on symbols

### ISSUE THREAD

**Issue by tidyui** [dotnet/templating#2371]
Hi there! Do you have a recommended solution for how to transform `appsettings.json` content depending on symbol values. In my case I want to include/exclude parts of the config depending on the options the user has made during `dotnet new`.

I've tried to go through the documentation I've managed to find with my google-skills but I just can't seem to figure it out.

**Comment by brettrowberry** [comment]
Best resources are https://github.com/dotnet/templating/wiki and https://github.com/SAFE-Stack/SAFE-template

**Comment by vlada-shubina** [comment]
@tidyui please check the examples of conditions for JSON files on the wiki page: https://github.com/dotnet/templating/wiki/Reference-for-comment-syntax#json-files

Please let me know if you need more information. Thanks

**Comment by vlada-shubina** [comment]
Closing the issue, please feel free to reopen if the information given is not sufficient.
