### ISSUE TITLE
Add Fabulous template to community wiki

### ISSUE THREAD

**Issue by zakaluka** [dotnet/templating#2373]
On this page: https://github.com/dotnet/templating/wiki/Available-templates-for-dotnet-new

Please add the following F# template: 

Name: Fabulous for Xamarin.Forms
Quick Install: dotnet new -i Fabulous.XamarinForms.Templates

Unfortunately, I cannot submit a PR for the wiki, so not sure what to do other than submit this issue.  If there's something else I should do, please let me know.

**Comment by grinrag** [comment]
closing as a duplicate of #2374
