### ISSUE TITLE
Add Fabulous to community templates on wiki

### ISSUE THREAD

**Issue by zakaluka** [dotnet/templating#2374]
On this page: https://github.com/dotnet/templating/wiki/Available-templates-for-dotnet-new

Please add the following F# template: 

Name: Fabulous for Xamarin.Forms
Quick Install: `dotnet new -i Fabulous.XamarinForms.Templates`

Unfortunately, I cannot submit a PR for the wiki, so not sure what to do other than submit this issue.  If there's something else I should do, please let me know.

**Comment by zakaluka** [comment]
Here is the reference for these instructions: https://fsprojects.github.io/Fabulous/Fabulous.XamarinForms/index.html#getting-started

**Comment by grinrag** [comment]
@zakaluka thank you for the proposal, I will edit the wiki.

**Comment by grinrag** [comment]
@zakaluka thank you! I have updated the wiki.
