### ISSUE TITLE
React template - mvc urls not hitting only after hard refresh

### ISSUE THREAD

**Issue by mausinc** [dotnet/templating#2377]
Hi!

I build this Office 365 add in with your react template, i am using several mvc routes for instance to add external accounts which works well in development. When i publish the app to Azure the routes are not rendered the first time, hard refresh however does. Locally this works fine
Do you have any thoughts how this can be resolved?
Thanks so much!

To reproduce - 
Add Mvc project (3.1) with React template in VS 2019. - 
Add HomeController and Index View 
Locally /Home/Index show the MVC View 
Release only after hard refresh (https://office365demo.azurewebsites.net/home/index)

**Comment by grinrag** [comment]
@mausinc what do you mean by `hard refresh`?

It looks like the problem not in the templating engine, maybe guys from ASP.NET can help or explain what is the problem.  @mkArtakMSFT ?

**Comment by mausinc** [comment]
Hi @grinrag  , thanks for your response.  
If you visit https://office365demo.azurewebsites.net/home/index , it initially shows the react page. When i hard refresh in the browser (ctrl+f5) it shows the razor view which is wanted. This problem doesn't happen in development.

**Comment by grinrag** [comment]
@mausinc thanks. Now I see that the problem is not about the templating engine, maybe ASP.NET guys can help/explain (the guy I pinged above).

**Comment by mausinc** [comment]
@grinrag  great thank you for your help.
@mkArtakMSFT if you need any further info, please let me know. thank so much

**Comment by mausinc** [comment]
issue is resolved by mapping the react app in a dedicated route.
