### ISSUE TITLE
Using dotnet pack to package template solution?

### ISSUE THREAD

**Issue by quietkatalyst** [dotnet/templating#2381]
I have a solution for a generic microservice that I've created a custom dotnet template for. This template is used to bootstrap creation of other microservices via the dotnet new command, which means that both the solution and all the projects inside of it, need to be inside of the *.nupkg that gets published to nuget.

This works fine when using `nuget pack` with a nuspec, but I need to move the build from Windows to Linux, so I've been trying to switch it over to using `dotnet pack`.  Unfortunately, instead of packaging up the entire solution, `dotnet pack` seems to output multiple *.nupkg files, one for each project in the solution.

Is it possible to use `dotnet pack` to package an entire solution the way you can with `nuget pack`? Is there some configuration I am missing?

**Comment by grinrag** [comment]
@quietkatalyst thank you for the issue. Actually, the issue is not related to the template engine itself,  but if you will provide a link to your project and the command which you execute on Linux to pack your solutions, I will try to reproduce it myself.

**Comment by brettrowberry** [comment]
Look at https://github.com/SAFE-Stack/SAFE-template/tree/master/Content. They do multiple projects.

**Comment by brettrowberry** [comment]
I like to use template packs as well https://docs.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-template-pack

**Comment by quietkatalyst** [comment]
I haven't had the bandwidth to come back and look at this, so going to close the issue for now :) Thanks for the replies and links, I will take a closer look at them.
