### ISSUE TITLE
How to add new project templates to the Wiki?

### ISSUE THREAD

**Issue by InteXX** [dotnet/templating#2382]
Currently, there exists a list of available project templates:

https://github.com/dotnet/templating/wiki/Available-templates-for-dotnet-new

Will it be possible to add entries to this list? It would be nice to be able to contribute to the community in this way.

**Comment by grinrag** [comment]
@InteXX Hello Jeff, just give me the details and I will add a new entry.
I need a name, quick install command, link to a template project page with additional information.

Thanks.

**Comment by InteXX** [comment]
@grinrag 

OK, will do.

I hope to have it ready by the end of today or tomorrow.

**Comment by InteXX** [comment]
@grinrag 

OK, I have the information for you:

1. Azure Function Project (HTTP Trigger)
2. https://github.com/InteXX/Templates
3. `dotnet new -i .\`

I have eventual plans to include all of the Azure Function project types and roll them up into a single template, but I'm not there just yet. When I do, we're going to need to change the name. I presume that won't cause too much trouble?

**Comment by grinrag** [comment]
@InteXX Thank you, Jeff. The template should be packed and published on nuget.org, so other users should not do anything else and just type `dotnet new --install <package_id>` to install the template.
See the example https://www.nuget.org/packages/Amazon.Lambda.Templates

**Comment by InteXX** [comment]
@grinrag 

Would you recommend something like [this approach](https://timheuer.com/blog/use-nuget-with-github-actions-github-packages/) for getting started with that?

**Comment by InteXX** [comment]
OK, I'm working on it.

What about the rename at some future date? If that's going to cause trouble for you, I'd rather wait.

**Comment by InteXX** [comment]
Here's the updated info:

1. Azure Functions
2. `dotnet new -i Intexx.Templates.AzureFunctions`
3. https://github.com/InteXX/Templates

Never mind about the rename. I managed to get to the task of bundling multiples sooner than I'd expected. Granted there's only one template in this first version, but future Azure Function templates will all go into the same package.

Again, this is for the VB.NET section.

Let me know if you need anything else.

**Comment by InteXX** [comment]
@grinrag 

Do you need anything more from me?

**Comment by grinrag** [comment]
@InteXX thank you. done!

**Comment by InteXX** [comment]
Thank you @grinrag 

Unfortunately, however, I failed to update the name prior to your posting. Since I've decided to roll all templates into a single package, the name should be `Assorted Templates` instead of `Azure Templates`.

Is it too late to make the change?
