### ISSUE TITLE
A path as an option for --uninstall looks ambiguous

### ISSUE THREAD

**Issue by genalt** [dotnet/templating#2383]
One of the ways to install a template is from a directory on the file system. 
For this user should provide a path, like this:
```bash
dotnet new -i  C:\Users\username\Template
```

After that template engine gets the real path on a filesystem to this directory, install the template and save the path as an identifier for this template. For example if the user passes as a parameter `C:\Users\username\TemplATE`, templating engine will save the real path like `C:\Users\username\Template`.

Then to uninstall a template user has to provide the path saved as an identifier. To see the correct identifier, a user can execute `dotnet new -u` without any parameter and `dotnet new` will show the Uninstall Command.

For users, this could be confusing, if they can install template with `dotnet new -i  C:\Users\username\TemplATE`, but cannot delete it with `dotnet new -u C:\Users\username\TemplATE`

The second problem here is using a bash shell on Windows. In bash on Windows user can pass a path in Unix-like format for the installation `/c/user/username/Template`, but then to remove the same installed template user has to pass the path already in WIndows format, as it was saved by the templating engine `C:\User\username\Template`

Probably for the templates installed from a directory, we can use something else as an identifier.

**Comment by bozturkMSFT** [comment]
We have decided to update the path resolution on un-installation to be consistent with installation.

**Comment by toadicusrex** [comment]
I'm running into this as well, looking forward to resolution!
