### ISSUE TITLE
Groupidentity not validated, improve documentation about requiredness of template.json fields

### ISSUE THREAD

**Issue by jannikbuschke** [dotnet/templating#2384]
Using the same `groupIdentity` in two different templates, but not providing any `tags`, its possible to pack a nuget template and publish it. I.e. there are no warnings or errors shown.
However when trying to create one of theses templates, via `dotnet new` the following error is shown:
`Couldn't find an installed template that matches the input, searching online for one that does...`
(no user input is triggered).

# Steps to reproduce

Create two templates with same groupIdentity but no tags.

# Possible solutions

**Improve the documentation** https://github.com/dotnet/templating/wiki/Reference-for-template.json. It is unclear that `groupIdentity` and `tags` should be used together (I also just assume this by my observations). It is also unclear if `groupIdentity` is a required property or not. This is also true for all other properties. Ideally there should be a column, that states for each property the requiredness.

Also when creating the template and some point the should happen some **validation**. I.e. when running `nuget pack` or `nuget push`

**Comment by vlada-shubina** [comment]
Using `groupIdentity` is still poorly documented. It's worth to create a separate article explaining:
- `groupIdentity` concept and its uniqueness
- `precedence` and `identity` withing the template group
- how to use `groupIdentity` to create the template group for templates in different languages
- how to use `groupIdentity` to create the template group for templates with different choice parameters values (as 1st party templates do for framework)

**Comment by seangwright** [comment]
I recently used `groupIdentity` and `tags.language` to expose 2 completely different templates under the same `shortName` by letting consumers of the template specify the `-lang` option when using the template.

I don't know if this is the intended use, but it would be great to have this area of templating documented.
