### ISSUE TITLE
[Loc]With .Net 5 preview5 installed in different Locales (for DE/TR/JP/CN) the output are not localized after running “dotnet new console” in CLI.

### ISSUE THREAD

**Issue by vdanche** [dotnet/templating#2385]
**Repro steps:**
1.	Install .net preview5 SDK(5.0.100-preview.5.20272.9) on Chinese OS.
2.	Run “dotnet new console” in CLI.
3.	Welcome texts about using .net5.0 for the first time will be displayed and then check if the contents are all localized
**Expected result:**
The contents should be localized well.

**Actual result:**
The contents are not localized.

SC:
![image](https://user-images.githubusercontent.com/65637796/82863918-ef0f1100-9f55-11ea-9052-1e3311d8eba7.png)

Dotnet --info:
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.5.20272.9
 Commit:    ac9984b120

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.5.20272.9\

Host (useful for support):
  Version: 5.0.0-preview.5.20268.11
  Commit:  201841eea7

.NET SDKs installed:
  5.0.100-preview.5.20272.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-preview.5.20272.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-preview.5.20268.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by vdanche** [comment]
for DE, the contents are partly unlocalized, 
![image](https://user-images.githubusercontent.com/65637796/82864916-33031580-9f58-11ea-8f33-932656b71263.png)
For Turkish and Japanese, Will update them when we test in the next time.

**Comment by donJoseLuis** [comment]
Needed by rel candidate 1

**Comment by vdanche** [comment]
> for DE, the contents are partly unlocalized,
> ![image](https://user-images.githubusercontent.com/65637796/82864916-33031580-9f58-11ea-8f33-932656b71263.png)
> For Turkish and Japanese, Will update them when we test in the next time.

For JA, partly unlocalized
![image](https://user-images.githubusercontent.com/65637796/83485798-6276cc80-a4da-11ea-9950-8eefb30fe69a.png)

**Comment by DavidKarlas** [comment]
I think this should be closed as dup of https://github.com/dotnet/templating/issues/2137

**Comment by vlada-shubina** [comment]
Closed as duplicate.
