### ISSUE TITLE
postAction script run does not show output on console

### ISSUE THREAD

**Issue by anandgupta08** [dotnet/templating#2388]
I have a postAction to run a script as below :

"postActions": [     
    {
      "actionId": "3A7C4B45-1F5D-4A30-959A-51B88E82B5D2",
      "condition": "(OS == \"Windows_NT\")",
      "description": "Install npm packages for client side SPA project",
      "args": {
        "executable": "setup.cmd",
        "args": ""
      },
      "manualInstructions": [
        {
          "text": "Navigate to UI folder and Run 'npm install'"
        }
      ],
      "continueOnError": true
    },
    {
      "actionId": "3A7C4B45-1F5D-4A30-959A-51B88E82B5D2",
      "condition": "(OS != \"Windows_NT\")",
      "description": "Install npm packages for client side SPA project",
      "args": {
        "executable": "setup.sh",
        "args": ""
      },
      "manualInstructions": [
        {
          "text": "Navigate to UI folder and Run 'npm install'"
        }
      ],
      "continueOnError": true
    }    
  ]

When this setup.cmd is run as part of the postAction, I do not see any output on console for the commands in the setup.cmd.
For, example setup.cmd has 'npm install && del setup.cmd' as a command inside it.
While the command does get executed successfully, but I do not see any npm install related progress on console.
However, if I run setup.cmd directly from terminal / command line, I can see the npm install related progress as below -
![image](https://user-images.githubusercontent.com/12773087/83270533-2fdb8400-a1fb-11ea-90ee-f9826a140ebc.png)

Since, npm install can take from several seconds to a couple of minutes (depending on the number and size if the npm dependencies), it will good and reassuring for end user to see progress and not mistakenly assume that the action may be stuck.
Also, is there a  way to prevent prompt for confirmation of script action run as below:
Do you want to run this action (Y|N)?
I noticed this confirmation is not there for the in-built dotnet restore action. I want to ensure minimal manual intervention.

Any help or suggestion would be highly appreciated.

**Comment by anandgupta08** [comment]
@donJoseLuis , thanks for adding the issue to your backlog.

Is there a way to prevent prompt for confirmation of script action run as below:
Do you want to run this action (Y|N)?
I noticed this confirmation is not there for the in-built dotnet restore action. I want to ensure minimal manual intervention.

**Comment by AR-May** [comment]
Hello @anandgupta08! I was looking at the post actions' code and I think I found something that might be helpful for you.
There is an option `redirectStandardOutput`, the default value of which is `true`. You could use it as in the following example:
```
"postActions": [{
      "actionId": "3A7C4B45-1F5D-4A30-959A-51B88E82B5D2",
      "args": {
        "executable": "setup.cmd",
        "args": "",
        "redirectStandardOutput": false
      },
      "manualInstructions": [{
        "text": "Run 'setup.cmd'"
      }],
      "continueOnError": "true",
      "description ": "description"
    }]
```

**Comment by AR-May** [comment]
As for your second question, you may try to take a look at issue #765, there is a discussion on the user confirmation.

**Comment by AR-May** [comment]
The information about the option `redirectStandardOutput` will be soon added to our wiki (#2515). I am closing this issue since there is nothing to do about it. Please do not hesitate to reopen the issue if the solution above does not work for you.
