### ISSUE TITLE
Feature Request: Resolve SA1210 Using statements out of order due to templated namespaces

### ISSUE THREAD

**Issue by rcollette** [dotnet/templating#2389]
I am generating a solution that has multiple projects.    

I get an SA1210 error when I build right after creating the new solution.   I have to go into the startup.cs file and reorder the using statements.

Can we get a post action to do formatting globally?

**Comment by donJoseLuis** [comment]
Hello @rcollette , thanks for the suggestion.  We'll track this need in your previous issue, #2390
