### ISSUE TITLE
UserProfileDir is incorrect when running with Mono on non-Windows platforms

### ISSUE THREAD

**Issue by mrward** [dotnet/templating#239]
The UserProfileDir is using the USERPROFILE environment variable which is not set on non-Windows platforms:

https://github.com/dotnet/templating/blob/b96ec9c36f8c1accf6dcc608da66c768ac17ab5f/src/Microsoft.TemplateEngine.Utils/EngineEnvironmentSettings.cs#L54

**Comment by mlorbetske** [comment]
@mrward thanks for pointing this out, what do you feel would be the best way to make the determination here?

**Comment by mrward** [comment]
Looking at what Xamarin Studio does it checks the path separator to determine if the current platform is Windows.

    IsWindows = System.IO.Path.DirectorySeparatorChar == '\\';

Then the HOME environment variable could be used instead based on this test.

**Comment by mlorbetske** [comment]
PR merged, thanks again!
