### ISSUE TITLE
C# Code is formatted causing SA1000 errors

### ISSUE THREAD

**Issue by rcollette** [dotnet/templating#2390]
It appears that some sort of code reformatting happens when the content is processed to replace variables, resulting in may added spaces around parens and braces.  I get a ton of SA1000 errors in my startup.cs as a result when I go to compile it the first time.   I wind up having to open the code and format it in Rider.

**Comment by vlada-shubina** [comment]
@rcollette 

Could you please provide the template with this issue? We would like to investigate it further. Thank you.

**Comment by vlada-shubina** [comment]
Closing due to no feedback. Please reopen if needed.
