### ISSUE TITLE
template.json how to use two parameters to rename a directory?

### ISSUE THREAD

**Issue by StevenTCramer** [dotnet/templating#2393]
I would like to be able to rename a directory to path combined from two input params.

example command: `dotnet new endpoint -n GetHealth -R Purple -F Health`

I would like to rename a template directory `\Api` to `Source\Api\Feature\Health\GetHealth`.
`sources` `modifiers` I don't think support parameters and using a derived rename only has one `valueSource`.  

I am sure I am missing something.  Thanks.

**Comment by donJoseLuis** [comment]
@StevenTCramer greetings.  Thanks for your question.  Off the top of our heads, could Post-
Action serve the purpose?  If not, please explain a bit more about what you're trying to accomplish.  
- What is the value gained in the rename?

Let us know.

**Comment by StevenTCramer** [comment]
@donJoseLuis The value gained is putting it the properly named folder.
in `Source\Api\Feature\Feature\Name`  

And yes a think Post-Action I could move files anywhere just figured I was missing something.

the derived only takes one `valueSource` if could take two then this would be easily possible.

**Comment by vlada-shubina** [comment]
It might be possible to achieve it with `Join` generator (non documented at the moment - see https://github.com/dotnet/templating/issues/2583), and support of using generated symbols for file renames (https://github.com/dotnet/templating/issues/2507). 

Need further investigation.

**Comment by DavidKarlas** [comment]
Hi @StevenTCramer,

could you try using following example with `join`? I will write docs now explaining more about `join`.

```json
  "symbols": {
    "n": {
      "type": "parameter",
      "dataType": "string"
    },
    "F": {
      "type": "parameter",
      "dataType": "string"
    },
    "joinedRename": {
      "type": "generated",
      "generator": "join",
      "fileRename": "Api",
      "parameters": {
        "symbols": [
          {
            "type": "const",
            "value": "Source"
          },
          {
            "type": "const",
            "value": "Api"
          },
           {
            "type": "const",
            "value": "Feature"
          },
          {
            "type": "ref",
            "value": "F"
          },
          {
            "type": "ref",
            "value": "n"
          }
        ],
        "separator": "/"
      }
    }
  }
```

If `n` and `F` are not defined, resulting string will be `Source/Api/Feature//` which is fine because File API will just ignore empty `//`.
Also notice that File API will automatically convert `/` to `\` on Windows.

I hope this solves your issue.

**Comment by vlada-shubina** [comment]
Closing this item. Please do not hesitate to reopen if the solution above doesn't fix the issue.
