### ISSUE TITLE
dotnet new --update-check not finding latest version

### ISSUE THREAD

**Issue by brettrowberry** [dotnet/templating#2398]
`dotnet new --update-check` does not find the latest version.

# System Information
`> dotnet --version`
`3.1.300`

# Steps to Reproduce
```
dotnet new --install SAFE.Template::1.0.0
dotnet new --update-check
```
Output:
```
An update for template pack SAFE.Template::1.0.0 is available.
    install command: dotnet new -i SAFE.Template::1.19.0```
```
I expected to see the latest version, 1.24.0, not 1.19.0.

# Workaround
`dotnet new -i SAFE.Template`
Sometimes this still fails and I have to run
`dotnet nuget locals all --clear;dotnet new -i SAFE.Template`
I can't get it to fail again and I wonder if this would be sufficient:
`dotnet nuget locals http-cache --clear;dotnet new -i SAFE.Template`

**Comment by donJoseLuis** [comment]
@brettrowberry thanks for letting us know. We'll take a look this week to understand more what's happening.

@grinrag please spend time this week on this one.

**Comment by vlada-shubina** [comment]
The fix will be delivered in https://github.com/dotnet/templating/issues/2592.

**Comment by vlada-shubina** [comment]
The issue is fixed: now dotnet new uses NuGet API to get information about updates and it reflects update immediately. 
Also API is forced not to use cache, so issue of local NuGet cache being old also eliminated (https://github.com/dotnet/templating/issues/2874) .
