### ISSUE TITLE
packages.lock.json files are excluded

### ISSUE THREAD

**Issue by gitfool** [dotnet/templating#2399]
`packages.lock.json` files are used to [enable repeatable package restores](https://devblogs.microsoft.com/nuget/enable-repeatable-package-restores-using-a-lock-file/) and should not be [excluded](https://github.com/dotnet/templating/blob/master/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/SimpleConfigModel.cs#L32); how can I override this behavior?

**Comment by donJoseLuis** [comment]
@grinrag please consult with @KathleenDollard to understand the related use case.  Why are excluding *.lock.json to begin with?

@gitfool , thanks for the issue.  Please give us a bit of time to discuss this & then get back to you.

**Comment by brettrowberry** [comment]
Look at https://github.com/SAFE-Stack/SAFE-template/tree/master/Content

**Comment by gitfool** [comment]
@brettrowberry that's a different file that doesn't match the [ExcludePatternDefaults](https://github.com/dotnet/templating/blob/master/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/SimpleConfigModel.cs#L25-L33).

**Comment by brettrowberry** [comment]
Oh wow, that’s the NuGet lock file, not the Paket lock file!

**Comment by brettrowberry** [comment]
https://github.com/SAFE-Stack/SAFE-template/blob/f8fbfe4e7be481cd1a2433db6036cdc2ca0b886b/Content/.template.config/template.json#L179 Can sources.include do the trick (sources.exclude shown there)?

**Comment by gitfool** [comment]
@donJoseLuis gentle nudge... what was the outcome of your discussion?

**Comment by bozturkMSFT** [comment]
@vlada-shubina Did you have a chance to investigate this?
