### ISSUE TITLE
`dotnet new` writes template content with 'chmod +x'

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/templating#240]
Repro
------

1. `dotnet new xunit`
2. `ls -l`

Expected
------
```
total 16
-rw-r--r--  1 piotrp  staff  151 Feb  2 13:43 UnitTest1.cs
-rw-r--r--  1 piotrp  staff  461 Feb  2 13:43 r5548.csproj
```

Actual
------
```
total 16
-rwxr--r--  1 piotrp  staff  151 Feb  2 13:43 UnitTest1.cs
-rwxr--r--  1 piotrp  staff  461 Feb  2 13:43 r5548.csproj
```

CLI Info:
------
```
.NET Command Line Tools (1.0.0-rc4-004748)

Product Information:
 Version:            1.0.0-rc4-004748
 Commit SHA-1 hash:  260b40456a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /Users/piotrp/code/github/piotrpMSFT/cli/artifacts/osx.10.11-x64/stage2/sdk/1.0.0-rc4-004748
```

**Comment by mlorbetske** [comment]
This was/is an issue with `FileStream` https://github.com/dotnet/corefx/issues/13342 and has been resolved with https://github.com/dotnet/coreclr/pull/7995, I believe we're just waiting for the release carrying this change to make it to a place we can use

**Comment by wjk** [comment]
@mlorbetske Any news on when this change will be pushed? I was the one who originally filed dotnet/corefx#13342, and this behavior is still driving me crazy, three months later. Thanks!

**Comment by mlorbetske** [comment]
@seancpeters can you verify this is fixed on a non-Windows machine tomorrow please?

**Comment by seancpeters** [comment]
Testing with dotnet 2.0.0-oreview2-005905 on Ubuntu 16.04-x64 the created files have 664 permissions (-rw-rw-r--), which is the expected outcome with the fix in place.

My umask is 0002
