### ISSUE TITLE
Remove RocketMod Template, add OpenMod 

### ISSUE THREAD

**Issue by Trojaner** [dotnet/templating#2404]
[About a year earlier](https://github.com/dotnet/templating/issues/1790) I asked if the [RocketMod](https://github.com/rocketmod/Rocket) templates could be added. Since then a lot has changed and the RocketMod project has been abandoned. The project is no longer continued (see linked repo). 

It's successor is the new [OpenMod](https://github.com/openmod/openmod) framework, which also ships dotnet templates.

 Name | Quick Install
--------|----------------
[OpenMod Plugin Templates](https://github.com/openmod/openmod/tree/master/templates) - OpenMod is .NET plugin framework. These templates allow to quickly get started with a new OpenMod Plugin. | dotnet new -i "OpenMod.Templates::*" |

**Comment by grinrag** [comment]
@Trojaner thank you very much. I added information about new templates into the wiki. Also, I would still keep the RocketMod templates on the list for a while.

**Comment by Trojaner** [comment]
Thank you!
