### ISSUE TITLE
New Project Templates for top-level programs in C# 9

### ISSUE THREAD

**Issue by seesharprun** [dotnet/templating#2415]
With C# 9 on the horizon, we are already able to start building top-level programs in C#:

I think it would make sense to build a new project template that includes a top-level program in C# with a Program.cs file and a csproj file. The code in the **Program.cs** file would be as simple as this:

```
using System;

await Console.Out.WriteLineAsync("Hello, World!");
```

Before I built the PR, I want to ask if this was something your team was willing to consider at this point?

There's some exciting stuff happening in this space, and it would be great to point people at a simple template to get started. I even saw some of the ASP.NET team on Twitter showing off top-level programs that host a simple HTTP API in a few lines of code.

**Comment by grinrag** [comment]
@seesharprun thank you very much for the issue. I need to discuss this with PM. Right now I am not sure we are going to add this change to the template for .Net 5 release.

**Comment by seesharprun** [comment]
I wold recommend considering it as a new template, not a change to existing templates. That will make sure you don’t break anything already out there relying on the console template.

It could be as simple as ``dotnet new script``

**Comment by grinrag** [comment]
@seesharprun thank you for the proposal, at the current stage of the .Net 5 release, we are not going to add a new template to the SDK. But you can add it yourself and I will update the list of available templates, maintained by the community.
From our side we can include these changes only into our template in the next major .Net release (and C# 10).

I am keeping this issue open.

**Comment by seesharprun** [comment]
Where is the community list located? I added a template to NuGet here: https://www.nuget.org/packages/Preview.CSharp.Templates/

**Comment by vlada-shubina** [comment]
This was already done for .NET 6. The templates are using top-level programs now. Closing
