### ISSUE TITLE
[Loc]With .Net5 Preview7 installed, the texts in CLI are partly unlocalzied after running "dotnet --info" for DE/TR/JP

### ISSUE THREAD

**Issue by vdanche** [dotnet/templating#2419]
**Repro Steps:**
1. Install .net5 preview7 SDK(5.0.100-preview.7.20366.15) on local OS[DE/TR/JP].
2. Run “dotnet --info” in CLI.
**Expected Result:**
The texts should be localized well.
**Actual Result:**
The texts are partly unlocalized.

EN:
![image](https://user-images.githubusercontent.com/65637796/88154160-f8a4b480-cc38-11ea-90f3-0e9bc6d72917.png)
JP:
![image](https://user-images.githubusercontent.com/65637796/88154251-1bcf6400-cc39-11ea-9c64-bbc1acfc00d2.png)

DE:
![image](https://user-images.githubusercontent.com/65637796/88154197-05290d00-cc39-11ea-9588-56e5d33b9a8b.png)
TR:
![image](https://user-images.githubusercontent.com/65637796/88154227-1114cf00-cc39-11ea-9576-d1cd4b338489.png)

**Comment by vdanche** [comment]
For SC, all texts in CLI are unlocalized, track the bug: [#2420 ](https://github.com/dotnet/templating/issues/2420)

**Comment by ladipro** [comment]
@vdanche is this the same issue as https://github.com/dotnet/templating/issues/2385 or are you seeing something else in Preview7 compared to Preview5? Thanks!

**Comment by grinrag** [comment]
I am closing this issue in favor of #2385. We are aware of the problem. There were no changes since the Preview 5.

**Comment by vdanche** [comment]
@genalt on net6 preview 7 SDK, we found that the text in CLI are still partly unlocalized after runing "dotnet --info"
e.g on SC:
![image](https://user-images.githubusercontent.com/65637796/125765118-44249126-f032-4991-b44f-7f52d1947270.png)
 Is it still under translation?

**Comment by vlada-shubina** [comment]
@dotnet/dotnet-cli could you please advise on above?

**Comment by vdanche** [comment]
@vlada-shubina on NET6 RTM SDK--6.0.100-rtm.21515.2(runtime-6.0.0-rtm.21514.7), we found that the text in CLI are still partly unlocalized after runing "dotnet --info" 
e.g TK
![image](https://user-images.githubusercontent.com/65637796/138252309-3618def9-45fd-4f6f-bd08-37867ebf58c1.png)

**Comment by vlada-shubina** [comment]
@vdanche this is out of scope for dotnet/templating. Could you please report it to dotnet/sdk? Thank you.

**Comment by vdanche** [comment]
@sfoslund @vlada-shubina Thanks, we filed a bug [#60756](https://github.com/dotnet/runtime/issues/60756) at  dotnet/runtime

FYI @richaverma1
