### ISSUE TITLE
Regex Example fails Schema Validation

### ISSUE THREAD

**Issue by antmdvs** [dotnet/templating#2423]
The [Regex example in the wiki](https://github.com/dotnet/templating/wiki/Available-Parameter-Generators#regex) fails schema validation due to the lack of a [required `action` property](https://github.com/mlorbetske/schemastore/blob/9f9148b09cf1190ce45199c956d8a0bb8e19347f/src/schemas/json/template.json#L111-L116).

Is that supposed to be required or is that a mistake in the schema?

**Comment by vlada-shubina** [comment]
@antmdvs it is a mistake in schema, the example is correct. Schema fixes will be addressed in https://github.com/dotnet/templating/issues/2514

**Comment by vlada-shubina** [comment]
Schema was updated and now contains correct properties for regex macro.
