### ISSUE TITLE
Extend Hive (for .Net 5) cache with additional information about Optional Workload Templates

### ISSUE THREAD

**Issue by grinrag** [dotnet/templating#2426]
Template Engine keeps the information about all templates in the hive in the cache file. The location of cache file:
`~\.templateengine\dotnetcli\<version>\templatecache`

To track the information about templates from optional workloads, we need to extend the cache with some tag:
```json
{ "OptionalWorkload": true }
```

This tag should be added during the installation template into the Hive

**Comment by ladipro** [comment]
@grinrag does this require more than just adding the new flag to the schema (to `ITemplateInfo`?) and plumbing it through the code? It looks like it should not be the case but the estimated size of **3.0** suggests that maybe more work is expected. Thanks!
