### ISSUE TITLE
Integrate with the mock library for Optional Workload templates listing.

### ISSUE THREAD

**Issue by grinrag** [dotnet/templating#2428]
To list the templates from Optional Workload we need to integrate with the Library provided by SDK team.
This, in general, includes:

- add information about custom feed to the (https://github.com/dotnet/templating/blob/master/NuGet.config). This is the repo with nuget package

- add imports for the API method and template information interface

**Comment by grinrag** [comment]
The related task #2405 will consume the mock library until the integration is completed

**Comment by grinrag** [comment]
@wli3 Hi William, the both issues #2405 and this one depend on the completeness of the nupkg with the Optional Workload  API. Could you, please, link an issue for that task from the SDK repo? Thanks.

**Comment by wli3** [comment]
https://github.com/dotnet/sdk/issues/12721

**Comment by wli3** [comment]
I will get the package done in 24 hr

**Comment by grinrag** [comment]
I added reference to the `<PackageReference Include="Microsoft.Internal.DotNet.MockTemplateLocator" Version="5.0.100-rc.1.20405.5" />` in the TemplateEngine.Cli project
