### ISSUE TITLE
Feature Request - Project Test Runner for Templates as NuGet package(s)

### ISSUE THREAD

**Issue by mikhey** [dotnet/templating#2430]
I'm in the process of authoring some templates for my team.  I was looking at the Project Test Runner and thought that would be a nice to have in my own template solution as well.

Would it be a possibility to make the project test runner a NuGet package (with some configuration options)? The thought is it could be used in a XUnit test project and one would only need to specify their own test JSON files for their templates.

This would be something I would be willing to work on.

**Comment by AR-May** [comment]
Hi @mikhey ! 

Yes, one can make a custom template from the project. Here is some info for this:
https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates

Take a look at the available communities templates:
https://github.com/dotnet/templating/wiki

Let us know if you need anything else.
