### ISSUE TITLE
Question: Support other languages

### ISSUE THREAD

**Issue by borgdylan** [dotnet/templating#2431]
Is it possible to add translations of existing templates for other languages without having to modify the templating engine or dotnet-new itself?

**Comment by AR-May** [comment]
Thank you for the question, @borgdylan . Yes, this is possible. We need some time to give you "how".

**Comment by grinrag** [comment]
@borgdylan it's possible to have several templates for computer languages (C#, F#, VB, etc). In this case, if you need them all look like one template just set the same group id.
For the translations of templates to different human languages (for example localization for help info), the work is still in progress.
Currently, you cannot use this feature yet. 

I am closing this issue now. Also, I would recommend joining our gitter channel (see the link in README in the root of the repo), many questions like this could be answered there.

Thank you.

**Comment by borgdylan** [comment]
By other language I meant other programming languages in the ..net ecosystem. I am the maintainer of one such language.
