### ISSUE TITLE
Audit and fix all culture-dependent calls

### ISSUE THREAD

**Issue by AR-May** [dotnet/templating#2436]
Conditionals use the language of locale for parsing. In different locales, some types (for example double) have different formats. If an author of a template uses one locale and a consumer of the template uses another then the conditional may execute incorrectly.
```
#if (1.4 < 2.5)
// Code will not show in RUS, FRA locales
#endif
```

**Comment by AR-May** [comment]
One of the unit tests catches this problem in some locales (for example RUS, FRA).  I disabled (PR #2450) this unit test in order to keep the project buildable in such locales. Once this issue is done, it would be necessary to turn it on back.

**Comment by AR-May** [comment]
Issue #2073 also concerns the problem with doubles.

**Comment by bozturkMSFT** [comment]
This was fixed with https://github.com/dotnet/templating/pull/2547. Closing.
