### ISSUE TITLE
macOS: Certain NuGet stable package versions failing to be located when they actually exist

### ISSUE THREAD

**Issue by snickler** [dotnet/templating#2447]
### OS Version 
macOS Big Sur 11.0 Beta (20A5343i)

### .NET Version 
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.16
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.301/

### Issue

I'm currently having an issue with installing anything higher than v2.4.0 of the Uno.ProjectTemplates.DotNet NuGet package by using the following command: `dotnet new --install Uno.ProjectTemplates.Dotnet::3.0.5`. 

```
Determining projects to restore...
/Users/snickler/.templateengine/dotnetcli/v3.1.301/scratch/restore.csproj : error NU1102: Unable to find package Uno.ProjectTemplates.Dotnet with version (>= 3.0.5)
/Users/snickler/.templateengine/dotnetcli/v3.1.301/scratch/restore.csproj : error NU1102:   - Found 476 version(s) in nuget.org [ Nearest version: 2.4.0 ]
/Users/snickler/.templateengine/dotnetcli/v3.1.301/scratch/restore.csproj : error NU1102:   - Found 0 version(s) in /usr/local/share/dotnet/sdk/NuGetFallbackFolder
  Failed to restore /Users/snickler/.templateengine/dotnetcli/v3.1.301/scratch/restore.csproj (in 749 ms).
```

Many versions exist past 2.4.0, such as a 2.4.4 stable version. The one I'm focused on is 3.0.5. 

I was able to successfully install the template by adding `https://api.nuget.org/v3-index/index.json` as the `--nuget-source` parameter. I initially tried the default `https://api.nuget.org/v3/index.json` endpoint. I can reproduce this failing to work properly only from my macOS. I can run the dotnet new command from Windows without needing to specify a NuGet source.

**Comment by grinrag** [comment]
The problem here with the obsolete metadata file for nuget.org.
We have an [EPIC issue 2483](https://github.com/dotnet/templating/issues/2483) for nuget search, which includes the task for an automated process of the metadata update.

The current issue will be automatically resolved after that EPIC is done. I am closing it as a duplicate.
