### ISSUE TITLE
Add template for .editorconfig

### ISSUE THREAD

**Issue by webczat** [dotnet/templating#2448]
Generally there are visual studio templates for editorconfig, but dotnet new templateengine does not support .editorconfig items.
That said, nowadays visual studio code does support editorconfig including roslyn specific dotnet style and formatting options, so for visual studio code or commandline users it would be easier if a .editorconfig template existed, allowing to quickly bootstrap editorconfig instead of copying it from project or writing by hand.

**Comment by AR-May** [comment]
Hello @webczat !
The template engine can process all the types of files, but some of them need non-default configuration. This includes .editorconfig files. So, you can search the [NuGet web page](https://www.nuget.org/) for existing custom templates or make your own custom template with an .editorconfig item. 

Here is [docs web page](https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates) that may be helpful for creating custom templates.

We also have plans to add more default configurations for some file types, we track it in issue #282 . 
Btw, you can also find an .editorconfig configuration there in the discussion.

Please tell us if you have other questions on this issue.

**Comment by webczat** [comment]
well not sure. what I wanted was to be able to do dotnet new editorconfig, and get, for example, editorconfig that effectively does the same as vs/omnisharp/roslyn defaults, so I can edit it. I have never played with template engine itself so not fully certain what the linked issue is about, tbh.

**Comment by AR-May** [comment]
@webczat , you do have your own editorconfig and you copy it from project to project, right? And you wish to add a certain editorconfig file to the project using '<a>dotnet new</a>' command. That is possible. You need to install a template with an editorconfig item on your machine. You have two options. 

You may try to search for community templates (they are usually published on [NuGet](https://www.nuget.org/)). For example, you may try [this one](https://www.nuget.org/packages/ForEvolve.Conventions.Templates/).

If you are not satisfied with community templates you also can create and install your own template, from any project/any file. However, in the case of .editorconfig file, the configuration json for a template may be a bit tricky, that is what the issue #282 about. Please refer to the links from my previous message. It is also helpful to look at the source code of community templates.

**Comment by webczat** [comment]
My use case is a bit different. As in, when I have my own customized editorconfig, then it's true that I copy it from project to project. However when I am making the first project with editorconfig, then it's a problem, because I have to either copy it from foreign project, or write it manually, if not using something like vs that can generate it (and I am using vscode that cannot). Of course, community templates are an option and it's nice they do exist, but it requires a bit of searching, same as when you want to copy editorconfig from a well established project. I would think that having such a default template officially would be more discoverable and easier to use for newcomers, especially that I believe vs does have such templates. Then if you don't have anything to copy to your projects and no vs you could create something with one command and customize, then you could make your template or copy manually.

**Comment by AR-May** [comment]
@webczat , I see your point about availability. I do not think we plan to add this item to our default templates. 
But there is something that could be done for the availability of editorconfig template. 
If one creates an editorconfig template and publishes it on NuGet, we can share it on [our wiki page](https://github.com/dotnet/templating/wiki/Available-templates-for-dotnet-new) with available community templates. One just needs to create an issue providing the necessary information on the template.

**Comment by webczat** [comment]
okay. should this issue be open so that it can be considered/reconsidered, or remain closed, meaning this is not going to happen at all in the form proposed?

**Comment by AR-May** [comment]
@webczat , unfortunately, we do not have resources for searching for / creating a nice editorconfig template ourselves, so that is why I proposed this way and left the issue closed. 
If you are ready to do so, then once we get the info I will update our wiki page. 
And, sure, feel free to open this issue or create a new one (like #2416) to track this.

**Comment by AR-May** [comment]
I do need the following info for an item on our wiki page: Name, Url, Quick install command.

**Comment by AR-May** [comment]
Since no additional information was provided I'm closing it now.
Feel free to reopen it with additional information.
