### ISSUE TITLE
Update information in the listing when the type parameter was provided.

### ISSUE THREAD

**Issue by AR-May** [dotnet/templating#2457]
In case if the --type option was provided, it should show only templates for the specified type. In particular, when we have no results matching the search, we should write that we got no results, as it is done for -lang option:
![Annotation 2020-08-20 165255](https://user-images.githubusercontent.com/67507805/90788151-cb195c80-e305-11ea-9d03-5d495d4f5db6.png)

At this moment one gets all these messages for an empty search result:
![Annotation 2020-08-20 165124](https://user-images.githubusercontent.com/67507805/90788607-4549e100-e306-11ea-87d7-471179e47b74.png)

**Comment by AR-May** [comment]
We discussed the issue with PM. Here is the result:
1.  There is a need to fix the wording. We would like to get the following:
      - When no templates found: `No templates found matching: <whatever>.`
      - When there are templates found: `These templates matched your input: <input>.`

2.  Remove all these strings for the type parameter. Instead, if we have an empty search we need to show a grouped description concerning partial matches and the reasons for exclusion: `12 templates partially matched, but failed on <whatever>`. In case we have no information concerning the reasons, we may end at the comma.

**Comment by AR-May** [comment]
Item 1 from my previous comment has been delivered.

**Comment by vlada-shubina** [comment]
@AR-May could you please check the words regarding to plural form:  should we use `{0} template(s) partially matched, but have (has) been excluded by the --type parameter. Remove or change the --type parameter to use that template(s).` or implement different strings for single and plural? (like now in the code)

**Comment by vlada-shubina** [comment]
Replaced above with: `Changed to {count} template(s) partially matched, but failed on {reason}`

**Comment by vlada-shubina** [comment]
2nd issue is closed with https://github.com/dotnet/templating/pull/2461
