### ISSUE TITLE
Link to MonoGame templates is invalid

### ISSUE THREAD

**Issue by harry-cpp** [dotnet/templating#2464]
When you try to create a MonoGame project from terminal without the templates installed you get the following info:
```
> dotnet new mgdesktopgl
Getting ready...
Couldn't find an installed template that matches the input, searching online for one that does...
Matches from template source: NuGet
-----------------------------------
Template name "MonoGame DesktopGL Game" (mgdesktopgl) from author "cra0zy" in pack MonoGame.Template.CSharp
    To use this template, run the following command and try again:
        dotnet new -i MonoGame.Template.CSharp::3.7.0.7

>
```

However the info in here is wrong, `MonoGame.Template.CSharp` is not a valid package anymore, the needed package is `MonoGame.Templates.CSharp`.

Also the info in the wiki needs updating: https://github.com/dotnet/templating/wiki/Available-templates-for-dotnet-new

**Comment by AR-May** [comment]
I updated the wiki page with the new package name. Thank you for pointing the problem with the search on NuGet. This is because the metadata file for the search is out-of-date. We are going to track and fix this as a part of an EPIC #2483, related to the search on the NuGet.
