### ISSUE TITLE
Community Contributions - Need entry update

### ISSUE THREAD

**Issue by InteXX** [dotnet/templating#2465]
I presently have an entry—Azure Functions—in the VB.NET section at the end of this list:

https://github.com/dotnet/templating/wiki/Available-templates-for-dotnet-new

Thank you.

Due to my own oversight, however, the text of the link should be `Assorted Templates` instead of `Azure Functions`. I tried creating a PR to submit this change, but apparently Wiki PRs aren't yet supported on GitHub.

Can you assist?

**Comment by grinrag** [comment]
`Assorted Templates` sounds to "general". I changed the text to `InteXX Assorted Templates`.

**Comment by InteXX** [comment]
@grinrag 

OK, sounds good. Thanks for preserving the casing on InteXX.
