### ISSUE TITLE
Welcome page/README/Project_ReadMe

### ISSUE THREAD

**Issue by peterblazejewicz** [dotnet/templating#247]
Not sure if this is a correct repo:
I'm missing a warm welcome page (README) for content:
[Remove Project_ReadMe.txt from templates](https://github.com/aspnet/Templates/pull/681)
[Replacement for content in README.md](https://github.com/OmniSharp/generator-aspnet/issues/867)
https://github.com/aspnet/Templates/pull/681#issuecomment-256466493
I've used to write a script to scrap relevant content:
https://github.com/peterblazejewicz/missing-aspnet-readme
but aspnet/Templates#681 removed that option.
[The somehow close one startup page from docs is too long I think](https://github.com/dotnet/docs/blob/master/index.md)

I could be missing bit of info, but is there a source or content similar to this one from VS2017 RC?
![https://cloud.githubusercontent.com/assets/14539/22482499/916fe2b6-e7f9-11e6-9a31-867f73ca8df2.png](https://cloud.githubusercontent.com/assets/14539/22482499/916fe2b6-e7f9-11e6-9a31-867f73ca8df2.png)

Have you folks discussed that topic?

See below:
![https://camo.githubusercontent.com/cb65f07210255d434e2d2b0aab5a1cd572394443/687474703a2f2f6775696465732e727562796f6e7261696c732e6f72672f696d616765732f67657474696e675f737461727465642f7261696c735f77656c636f6d652e706e67](https://camo.githubusercontent.com/cb65f07210255d434e2d2b0aab5a1cd572394443/687474703a2f2f6775696465732e727562796f6e7261696c732e6f72672f696d616765732f67657474696e675f737461727465642f7261696c735f77656c636f6d652e706e67)

or even this old  one:

https://cloud.githubusercontent.com/assets/14539/22607067/8cd81246-ea56-11e6-94c2-8cde68e7c208.png

Thanks!

**Comment by mlorbetske** [comment]
@sayedihashimi thoughts?

@seancpeters in our post-actions work, we'll likely want to have an "automatically open after generation" post-action (would mark the file as being the one to open in the overview page in VS)

@peterblazejewicz for templates at the CLI - would you expect that the file opens or just gets included in the output?

**Comment by peterblazejewicz** [comment]
> @peterblazejewicz for templates at the CLI - would you expect that the file opens or just gets included in the output? Also, are you asking for how to indicate that the content in Visual Studio should be customized from templates generated outside of Visual Studio?

```
just gets included in the output
```
👍 

But that is for consideration only for you folks :)

If this is a markdown file the current most commonly used IDEs (VSCode/Atom) renders preview out-of-the-box (unless I'm wrong). And VS/TFS online renders preview now for MD too.

**Comment by mlorbetske** [comment]
This issue was moved to aspnet/templating#17
