### ISSUE TITLE
Add support for --tag option in the listing

### ISSUE THREAD

**Issue by AR-May** [dotnet/templating#2475]
Currently `dotnet new -l` does not support filtering by the tag name. 

There is an implementation for filtering by the tag name, but it does not work right because:
1) it uses the specified template name for the search on the tags, which is wrong. The template name should be only for description and for the short name. 
2) the tag match considers as a partial match and `dotnet new -l` do not show partial matches at all. Previously `dotnet new -l` showed partial matches if there are no matches, so sometimes it worked. However, considering that we almost always have matches when we try to search by a tag name, this feature did not work properly in most of the cases back then also. 

We could add `--tag` option for filtering by a tag name and process it the same way the `--language` option works.

**Comment by vlada-shubina** [comment]
Will start on this after https://github.com/dotnet/templating/pull/2618 is merged based on refactoring done in the PR
