### ISSUE TITLE
Bump jQuery version up

### ISSUE THREAD

**Issue by peterblazejewicz** [dotnet/templating#249]
e.g.:
https://github.com/dotnet/templating/blob/master/template_feed/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-FSharp/bower.json#L6

The 2.2.3 works just fine:
https://github.com/OmniSharp/generator-aspnet/blob/master/templates/projects/web/bower.json#L6

**Comment by mlorbetske** [comment]
@sayedihashimi @phenning should we get these updated & updated in aspnet/templates as well?

**Comment by peterblazejewicz** [comment]
Well, there is `2.2.4` on `aspnet cdn` already:
https://www.asp.net/ajax/cdn#jQuery_Releases_on_the_CDN_0

**Comment by mlorbetske** [comment]
This issue was moved to aspnet/templating#18
