### ISSUE TITLE
Support inline XML conditions

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/templating#25]
Several items here:

* Port an MSBUILD style condition evaluator https://github.com/mono/monodevelop/blob/master/main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEvaluationContext.cs and/or this https://github.com/Microsoft/msbuild/blob/master/src/XMakeBuildEngine/Evaluation/ConditionEvaluator.cs for syntax support.
* Brace balancing should not be authoritative for expression ends (the value of the conditioning attribute can be pre-read and processed, searching for the end-quote, collecting the expression along the way)
* The root variable collection should be passed with a format string of `$({0})`
* Files matching the pattern `**/*.*proj` should use this new conditional evaluator instead of the existing `Conditional` provider
* `**/*.*proj` files should have a default attribute for evaluation called `Condition`
  * This may produce several variations that consume different common surrounding whitespace configurations
  * The basic form of this would be something like `Condition="`
* If the condition evaluates to false...
  * Reposition the output stream back to the start tag (by scanning backwards for `<`), or earlier depending on the leading whitespace behavior
  * Set the "open element" count to 1
  * Scan forward in the input buffer
    * If the end element start token `</` is encountered, decrement the open element count and seek to the element end token `>`
    * If the start element start token `<` is encountered, increment the open element count
    * If the self closing token `/>` is encountered, decrement the open element count
    * If the open element count is `0`, process the trailing whitespace behavior
* In order to avoid having to use `flags` settings to disable and enable `conditional` behavior for things like the default property groups, references to unresolved symbols should not be treated as false-y (as they are in the C++ style condition evaluator), instead, the expression (and originally matched `conditional` token) should be emitted to the output stream if the expression contains any unresolved symbols

Ex.
``` XML
<root>
  <element if="'$(variable)' == 'value'"/>
  <element if="'$(variable)' != 'value'">
    <child>
        <grandchild />
    </child>
  </element>
</root>
```

If `variable` == `"value"`, the output would be
``` XML
<root>
  <element />
</root>
```

If `variable` != `"value"`, the output would be
``` XML
<root>
  <element>
    <child>
        <grandchild />
    </child>
  </element>
</root>
```

**Comment by mlorbetske** [comment]
@sayedihashimi @mhutch agree/thoughts?

**Comment by mlorbetske** [comment]
The parts that #27 does not address:
* Non-brace balanced expression (expressions should be self balanced, not relying on brace depth count/single token)
* Resolution of symbols within quotes (prohibited by the C++ evaluator to avoid cyclic definition issues when symbols are bare)

The actual condition evaluator with those behaviors will need to be built.

**Comment by sayedihashimi** [comment]
Let's chat more in person today
