### ISSUE TITLE
Bump jQuery.Validate version up

### ISSUE THREAD

**Issue by peterblazejewicz** [dotnet/templating#250]
E.g.:
https://github.com/dotnet/templating/blob/master/template_feed/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-FSharp/bower.json#L7

The 1.15.0 version works just fine with scaffolded content:
https://github.com/OmniSharp/generator-aspnet/blob/master/templates/projects/web/bower.json#L7

**Comment by mlorbetske** [comment]
@sayedihashimi @phenning should we get these updated & updated in aspnet/templates as well?

**Comment by mlorbetske** [comment]
This issue was moved to aspnet/templating#19
