### ISSUE TITLE
[feature] Add support for fileRename for symbols with type=generated

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#2507]
Currently fileRename parameter is only supported for symbols of type=parameter.
Consider adding it also to other types, at least for generated parameters.
Split from https://github.com/dotnet/templating/issues/2240

- [x] implementation
- [x] unit tests
- [x] documentation update
- [x] JSON schema update (?)

**Comment by mmisztal1980** [comment]
when is this expected? will this be out with .NET 5?

**Comment by KathleenDollard** [comment]
@vlada-shubina - I didn't find this in the JSON schema, can you point me to an example of its current use? 

@mmisztal1980 - can you explain how you will use it. 

The TemplateEngine is part of the SDK which releases quarterly. It will not be in 5.0.100, but we could consider for the next quarterly release.

**Comment by vlada-shubina** [comment]
@KathleenDollard fileRename can be used with `parameter` or `derived` symbols and defines the filenames which will be replaced by symbol value.

```
"ServiceName": {
  "type": "parameter",
  "datatype": "text",
  "replaces": "ServiceName",
  "fileRename": "ServiceName",
  "description": "Name of the service to be created. Use Pascal casing and only use A-Z|a-z|0-9",
  "isRequired": true
}
```

This request is implement same behavior but for generated symbols.

There were multiple issues referencing this feature: https://github.com/dotnet/templating/issues/1783, https://github.com/dotnet/templating/issues/2240, https://github.com/dotnet/templating/issues/1642.

**Comment by mmisztal1980** [comment]
@KathleenDollard sure,

I'm working on templating the generation of services using my microservice framework. I want to achieve a separation on a per-release-artifact basis (release artifact = k8s service).

Example:

Given I have defined a template `core-microservice-api` with 2 parameters: `project` and `module`
My current `dotnet new core-microservice-api --project Xray --module Tango` output is:
```
├── project-module-api # xray-tango-api (desired)
│   └── src
│       ├── Xray.Tango.Api.     # the actual service (.net core rest api) being deployed
│       │   ├── Program.cs
│       │   ├── Properties
│       │   │   └── launchSettings.json
│       │   ├── Startup.cs
│       │   ├── Xray.Tango.Api.csproj
│       │   ├── appsettings.Development.json
│       │   └── appsettings.json
│       ├── Xray.Tango.Api.Client  # nuget with http client to the service
│       │   ├── Class1.cs
│       │   └── Xray.Tango.Api.Client.csproj
│       ├── Xray.Tango.DataContracts.   # nuget with DTOs for the API
│       │   ├── WeatherForecast.cs
│       │   └── Xray.Tango.DataContracts.csproj
│       └── Xray.Tango.Messages.  # service bus messages
│           ├── Class1.cs
│           └── Xray.Tango.Messages.csproj
└── telemetry.json
```

In my case there are multiple more types of templates incoming (graphql, one-time fire and forget jobs, bacground workers etc.) all with different templates, and all being separate deployment types for kubernetes.

This template is my attempt at keeping it tidy and using the `dotnet new` goodness to speed up my workflow

**Comment by vlada-shubina** [comment]
Keep open for documentation update, blocked by https://github.com/dotnet/templating/pull/2529
