### ISSUE TITLE
WebAPI (Web/WebAPI) F# version

### ISSUE THREAD

**Issue by peterblazejewicz** [dotnet/templating#252]
I'm rewriting `generator-aspnet` templatest for RC and the F# version of `WebAPI` project is missing in `dotnet new3`. 
https://github.com/OmniSharp/generator-aspnet/issues/884
https://github.com/OmniSharp/generator-aspnet/tree/master/templates/projects/fsharp_webapi

Do you want a PR (maybe not now though)?

Thanks!

**Comment by mlorbetske** [comment]
A PR would be great, thanks!
