### ISSUE TITLE
Use System.CommandLine for parsing the command line input

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#2520]
Exit criteria:
- Import System.CommandLine package and replace the current parser with it.
- Some of the existing options should be converted to subcommands (such as --install, --uninstall, --list) 
- Verify help for a specific template is displayed correctly (we don't display the generic dotnet new help)

**Comment by donJoseLuis** [comment]
Related to _user story_  [ ] https://github.com/dotnet/templating/issues/2191

**Comment by bozturkMSFT** [comment]
I'm closing this in favor of the duplicate issue https://github.com/dotnet/templating/issues/2191
