### ISSUE TITLE
[Samples] Samples repository maintenance

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#2522]
There is a samples repository: https://github.com/dotnet/dotnet-template-samples

Decide:
- if we are going to maintain it? Now it is archived.
- should we bring it to main repository?
- should we accept requests for new examples there

_Originally posted by @bozturkMSFT in https://github.com/dotnet/templating/pull/2518#discussion_r488742525_

---- 

We agreed to move examples to dotnet/templating repo instead.
The examples should be part of separate project containing all the templates. 
The tests (using [test framework](https://github.com/dotnet/templating/blob/main/docs/authoring-tools/Templates-Testing-Tooling.md)) should be added to verify the examples can be run and produce correct output - as a separate test project.
After it is done, we should update links in the documentation to a new location in templating repo.

**Comment by vlada-shubina** [comment]
@mmitche 
we are considering bringing https://github.com/dotnet/dotnet-template-samples back to life as it is proved to be very useful resource for community.

1. Is "unarchiving" it an option to consider? we can own that repo and update the samples there and possibly add them to our CI.
2. If  answer to 1.  is no, is it possible to unarchive it for a while so we can reference sample in their new location in dotnet/templating repo readme.md over there. 

Thanks. 

cc @KathleenDollard @DavidKarlas

**Comment by JanKrivanek** [comment]
Docs for testing framework (to be used to test the samples): https://github.com/dotnet/templating/blob/main/docs/authoring-tools/Templates-Testing-Tooling.md

**Comment by milanjaros** [comment]
@mmitche, @vlada-shubina, may I help with this?

**Comment by vlada-shubina** [comment]
@milanjaros 
not at the moment, we are moving the examples to dotnet/templating shortly. I will let you know when done.
afterwards it would be good if you can rework your PR from https://github.com/dotnet/templating/issues/5651 to contribute to new location. Thank you

**Comment by JanKrivanek** [comment]
Test FW extensions for testing within templating repo is being added: https://github.com/dotnet/templating/pull/5677/files#r1032639941

We should be validating schema as well - we can simply reuse https://github.com/dotnet/templating/blob/main/test/Microsoft.TemplateEngine.Orchestrator.RunnableProjects.UnitTests/SchemaTests/JSONSchemaTests.cs#L59

**Comment by vlada-shubina** [comment]
The following was done:
- [x] move the template samples to dotnet\templating repo
- [x] create a template package for them
- [x] modernize the templates
- [x] create end-to-end tests in dotnet\templating.

Pending task:
- run the template samples in dotnet\sdk repo as part of integration tests.

**Comment by donJoseLuis** [comment]
moved & covered w/ tests in templates & sdk repos.
