### ISSUE TITLE
Custom Post Actions

### ISSUE THREAD

**Issue by ManniManfred** [dotnet/templating#2531]
Hi, is it possible to ship custom post actions with my template/nuget package?

**Comment by vlada-shubina** [comment]
Hi @ManniManfred, unfortunately it is not possible in the moment. 
[Post Actions Registry](https://github.com/dotnet/templating/wiki/Post-Action-Registry) article explains the set of custom actions available at the moment.  As a possible workaround, I can suggest to check if you can use "Run script" action.

Let me know if you need more information.
