### ISSUE TITLE
Call stacks shouldn't be displayed when calling dotnet new with the wrong parameters

### ISSUE THREAD

**Issue by mairaw** [dotnet/templating#256]
I was testing some wrong parameters with dotnet new to see the strings and in a lot of cases I do get the error message with the call stack.

## Steps to reproduce
![image](https://cloud.githubusercontent.com/assets/12971179/22616314/e9b40bf6-ea5f-11e6-8ea3-6544e417f28d.png)

## Expected behavior 
I'll get the error message without the call stack. Perhaps with the command usage?

## Actual behavior
I get the error message + call stack.

## Environment data
.NET Command Line Tools (1.0.0-rc4-004761)

Product Information:
Version: 1.0.0-rc4-004761
Commit SHA-1 hash: fc475dfd51

Runtime Environment:
OS Name: Windows
OS Version: 10.0.14393
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\1.0.0-rc4-004761

**Comment by mlorbetske** [comment]
This has been merged, thanks!
