### ISSUE TITLE
template.json doesn't recognize scaped text in json for generated constants

### ISSUE THREAD

**Issue by jesuscampos** [dotnet/templating#2570]
I'd like to replace some text from a json file. I need that the text to compare spans strings including double quotes characters. For example, I need to replace this text:
```json
"MyJsonProperty": "TemplateValue.xxxxxxxxxx",
```
by this other:
```json
"MyJsonProperty2": "MyReplacedValue.xxxxxxxxxx",
```
I've tried scaping the double quotes but the text isn't replaced.
```
"myConstantParam": {
	"type": "generated",
	"generator": "constant",
	"parameters": {
		"value": "\"MyJsonProperty2\": \"MyReplacedValue"
	},
	"replaces": "\"MyJsonProperty\": \"TemplateValue"
}
```
How can I scape the json special chars in template.json values?

I need the comparison to be the full text. I can't split in two different constants.

**Comment by vlada-shubina** [comment]
@jesuscampos 

I have tried the config mentioned above, and it works perfectly fine in dotnet SDK 3.1.402. Attached the configuration I've tried with and the received output. 
[test-json.zip](https://github.com/dotnet/templating/files/5365454/test-json.zip)
[test-json-replace.zip](https://github.com/dotnet/templating/files/5365443/test-json-replace.zip)

Could you please check the version you are trying with and if it's not the latest try to upgrade? In case of issues, could you please attach full configuration so I can check it?

Thank you.

**Comment by jesuscampos** [comment]
I've upgraded to 3.1.402 and it works.

Thank you!
