### ISSUE TITLE
Consider implementing end-to-end testing on the real file system

### ISSUE THREAD

**Issue by AR-May** [dotnet/templating#2580]
The current end-to-end tests use an in-memory file system. Hence, some of the features were left untested, such as the run script post-action and the chmod post-action: seems like the corresponding tests could not be written within the current testing infrastructure. We already run into the issue with the absence of these tests: the change in one of our dependencies broke the chmod post-action and that was not noticed that for a long time (PR #1555, PR #2579, issue #1547).

Consider designing and implementing proper end-to-end testing on the real file system for these post-actions. 
The second option here is to find a workaround / somehow to leverage the current infrastructure and write proper tests for these post-actions if it is decided not to make end-to-end testing on the real file system.

**Comment by donJoseLuis** [comment]
Abandoned, work tracked via other means.
