### ISSUE TITLE
[docs] document Join and RegexMatch generators

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#2583]
https://github.com/dotnet/templating/blob/master/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/Macros/JoinMacro.cs
https://github.com/dotnet/templating/blob/master/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/Macros/RegexMatchMacro.cs

Update wiki article and JSON schema

**Comment by DavidKarlas** [comment]
This is fixed... @vlada-shubina how do we sync docs/ folder with Github Wiki?

**Comment by vlada-shubina** [comment]
@DavidKarlas we need to sync the content manually at the moment. Upload them via web site or push to https://github.com/dotnet/templating.wiki.git

Also we need to update the schema at https://github.com/SchemaStore/schemastore/tree/master/src/schemas/json/template.json with the changes you made as those are already release.d
