### ISSUE TITLE
Better handling of projects created in a filesystem root

### ISSUE THREAD

**Issue by lukas-lansky** [dotnet/templating#2589]
When I try to build this Dockerfile:

```
FROM mcr.microsoft.com/dotnet/sdk:5.0.100-rc.2
RUN dotnet new console
```

into a Windows Docker container, I get the following error:

```
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on C:\.csproj...
  Determining projects to restore...
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\NuGet.targets(462,5): error MSB4044: The "GetRestoreProjectStyleTask" task was not given a value for the required parameter "MSBuildProjectName". [C:\.csproj]
Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'
```

After some careful reading of the error message it occurs to me that the problem is that the generated name of the project is empty, and that's because `dotnet new` takes the name from of the current folder, and because the Docker default working directory is `C:\`.

I wonder whether we can offer either a better default name than `""` or a better error message in this case.

**Comment by vlada-shubina** [comment]
Can be related to https://github.com/dotnet/templating/issues/2303.

**Comment by vlada-shubina** [comment]
@lukas-lansky 
I could reproduce the issue above. We will discuss it shortly and come up with solution. 

There 2 aspects of the issue:
- default name specified in template.json file is not used (https://github.com/dotnet/templating/issues/2303)
- in case output directory is C:/ (or any root disk folder) the name is not correctly evaluated.

Depending on the outcome for #2303, the solution for this problem may differ.

**Comment by vlada-shubina** [comment]
Agreed not to use default name instead of current directory name, however I will fix name generation for root disk folder to use drive name as the name (probably not the optimal solution, but on the other hand we do not expect root disk folder to be used frequently).
