### ISSUE TITLE
Support "condition" on top level sources

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/templating#26]
Sources can have conditioned modifiers, but sources themselves should support conditions as well

**Comment by seancpeters** [comment]
Conditions in modifiers was added in:
https://github.com/dotnet/templating/pull/28/commits/94fdaa4c93cc494c4064c6bd328eefe57076a17b
#28

**Comment by seancpeters** [comment]
I misunderstood the requirement, reopening. Will be fixed in a PR soon.

**Comment by seancpeters** [comment]
This commit addresses the issue:
The nginx.conf and robots.txt setup is complete with https://github.com/dotnet/templating/pull/39/commits/d33aa93c0963a099f71613fb2def35e9eb58d90e
