### ISSUE TITLE
Use `.gitkeep` instead of `-.-`

### ISSUE THREAD

**Issue by peterblazejewicz** [dotnet/templating#260]
I assume the intent is to keep directory under git. Can this be simply `.gitkeep`?
https://github.com/angular/angular-cli/tree/master/packages/%40angular/cli/blueprints/ng2/files/__path__/assets

**Comment by mlorbetske** [comment]
`-.-` serves a different purpose - it preserves empty directories when zipped & doesn't imply a particular source control system

**Comment by peterblazejewicz** [comment]
Oh, how could I know this :) Thanks!
