### ISSUE TITLE
StarterWeb project does not run with 1.1 framework [error CS1061]

### ISSUE THREAD

**Issue by peterblazejewicz** [dotnet/templating#261]
When using content from current branch or vs2017-post-rtw, the template for C# does not run with 1.1 framework if BrowserLink include tag is missing:

> ➜  WebApplicationBasic dotnet run
Startup.cs(43,21): error CS1061: 'IApplicationBuilder' does not contain a definition for 'UseBrowserLink' and no extension method 'UseBrowserLink' accepting a first argument of type 'IApplicationBuilder' could be found (are you missing a using directive or an assembly reference?) [/Users/piotrblazejewicz/development/WebApplicationBasic/WebApplicationBasic.csproj]
>
> The build failed. Please fix the build errors and run again.

https://github.com/dotnet/templating/blob/master/template_feed/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-CSharp/Company.WebApplication1.csproj#L30-L48

The version shipped with my dotnet-cli does contain the BrowserLink for 1.1 though, so I'm confused:
```bash
dotnet --info
.NET Command Line Tools (1.0.0-rc4-004597)

Product Information:
 Version:            1.0.0-rc4-004597
 Commit SHA-1 hash:  0a62481cc0

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.0-rc4-004597
```

**Comment by mlorbetske** [comment]
@seancpeters can you investigate please? From what I see in the master branch, this should be working.

**Comment by seancpeters** [comment]
@peterblazejewicz
Can you post the entire contents of the .csproj file from the generated template? Or even better, send me a zip with all of the generated content? (sepeters@microsoft.com)

**Comment by seancpeters** [comment]
@peterblazejewicz 
Could you also let me know the exact command you used to create the template.

**Comment by peterblazejewicz** [comment]
@seancpeters 
- the issue is a question: `should the sources for 1.0 and 1.1 be different?':
https://github.com/dotnet/templating/blob/master/template_feed/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-CSharp/Company.WebApplication1.csproj#L29-L30
https://github.com/dotnet/templating/blob/master/template_feed/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-CSharp/Company.WebApplication1.csproj#L48

The `dotnet new3 --framework 1.1` on my machine (details above) .csproj is OK:
```xml
<Project ToolsVersion="15.0" Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.0.0" />
  </ItemGroup>
</Project>
```
but note that version is older from one used in 1.0 framework, so I asked a question myself if the config node is missing in 1.1 section:
```xml
 <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.0.0" />
```

**Comment by seancpeters** [comment]
Can you try running with 
`dotnet-new3`
instead of 
`'dotnet new3'`

**Comment by peterblazejewicz** [comment]
> Can you try running with
Nope, it won't work. I've used only content with already installed dotnet runtime, but I do not have the project built locally and I do not have `dotnet-new3` tool at path.
I've just pointed that browserlink dep is missing in 1.1 section

**Comment by seancpeters** [comment]
Using netcoreapp1.0, there should be no referencesto browserlink anywhere in the template.
When we removed the browserlink reference from the 1.1 section, we also made a change to startup.cs so that the following line is only included when using framework 1.0:
`app.UseBrowserLink(); `
That was in #214 

I think you have some outdated bits. The browserlink package ref should not be included when using the 1.1 framework, but we had it included in some older versions. If you have the vs2017-post-rtw branch of the templating repo, and can build it, the exe will be at: 
`<repo root>\dev\dotnet-new3.exe`
That should have the correct template setup so that using framework netcoreapp1.0 includes browserlink, but when using netcoreapp1., there should be nothing browserlink related in the generated template.

**Comment by peterblazejewicz** [comment]
> That was in #214

Now it makes sense. Thanks!

@sayedihashimi @mlorbetske 
Do you have a frozen branch that will be released for VS2017RC or is it still in development and the content can be taken from current, master branch? E.g. when updating `yo aspnet` which branch should be used?

**Comment by peterblazejewicz** [comment]
closing after @seancpeters comment
