### ISSUE TITLE
Want the xUnit template to include "IsTestProject" and "IsPublishable"

### ISSUE THREAD

**Issue by RYO-4947123** [dotnet/templating#2625]
The project file immediately after executing `dotnet new xunit` is currently as follows.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.7.1" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="1.3.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```

I think it is necessary to add `<IsTestProject>true</IsTestProject>` and `<IsPublishable>false</IsPublishable>` here.

Without `<IsTestProject>true</IsTestProject>`, some CIs (e.g.GitLab) will not run the test.
Without `<IsPublishable>false</IsPublishable>`, the output of `dotnet publish` will contain tests and will not work when deployed to Azure App Service.

Please consider it.

**Comment by vlada-shubina** [comment]
@RYO-4947123 I have transferred this issue to https://github.com/dotnet/test-templates/issues/109, `xunit` template is maintained in that repo. Please follow up the new issue if still needed. Thank you.

**Comment by RYO-4947123** [comment]
Sorry for the inconvenience.
Thank you very much.
