### ISSUE TITLE
Deleting a template folder cause a "dotnet new" error

### ISSUE THREAD

**Issue by wli3** [dotnet/templating#2631]
@mhollebecq commented on [Thu Oct 08 2020](https://github.com/dotnet/sdk/issues/14033)

If we create a template with `dotnet new -i [FolderName]` and then delete the folder, some option of `dotnet new` like "-u" or "--help" are blocked.

Of course we expect an error if we try to use the deleted template, but maybe we can be allowed to list template with "-u" or display the help

**Comment by vlada-shubina** [comment]
@wli3 is error you are getting same as in https://github.com/dotnet/templating/issues/2630?

**Comment by wli3** [comment]
@mhollebecq ?

**Comment by mhollebecq** [comment]
Sorry for the delay
Yes, it is exactly the same error

**Comment by vlada-shubina** [comment]
Let's track it then in https://github.com/dotnet/templating/issues/2630.  Please follow up it there if needed.
Closing this issue as duplicate.
