### ISSUE TITLE
Checkup on the Microsoft.TemplateEngine.Cli circular dependency: dotnet/sdk -> dotnet/templating -> dotnet/sdk

### ISSUE THREAD

**Issue by dagood** [dotnet/templating#2651]
Looking at `v5.0.0`, this package reference causes a circular dependency:

https://github.com/dotnet/templating/blob/31980633108a1bef00c798136fcd30a873c90fa3/src/Microsoft.TemplateEngine.Cli/Microsoft.TemplateEngine.Cli.csproj#L22

Circularity:
* dotnet/sdk depends on `Microsoft.TemplateEngine.Cli`, and produces `Microsoft.DotNet.TemplateLocator`.
* dotnet/templating depends on `Microsoft.DotNet.TemplateLocator`, and produces `Microsoft.TemplateEngine.Cli`.

Since dotnet/templating is "earlier" in the .NET SDK build graph (templating -> sdk -> installer), it ends up depending on an earlier version of the package than the one we actually ship. (This shows up above as dotnet/templating `v5.0.0` depending on a `5.0.0-rc.1` package!)

This isn't inherently a problem. It looks like dotnet/templating is compiling against `Microsoft.DotNet.TemplateLocator` for the API, but a newer version is inserted in the SDK that is actually used at runtime instead. In source-build, we can handle this by generating a ref-only version of `Microsoft.DotNet.TemplateLocator/5.0.100-rc.1.20421.19` to have dotnet/templating compile against rather than having a dependency cycle.

Note that cycles do have inherent risk, this isn't *just* a source-build issue. 😄 If the TemplateLocator API has breaking changes, dotnet/templating may produce a library that can't actually run in the SDK. This is particularly risky with unstable/prerelease/rc versions of APIs.

---

A few questions about this:
1. Is this cycle intentional? (Is one of these libraries actually in the wrong repo?)
1. Can source-build rely on dotnet/templating `release/5.0` always using `Microsoft.DotNet.TemplateLocator/5.0.100-rc.1.20421.19`, never updating?
   * Updating this causes source-build significant maintenance effort because we have to put together a new ref-only version of the package's new version.

@vlada-shubina
/cc @mmitche FYI on cycle.

**Comment by vlada-shubina** [comment]
Adding @wli3 

`Microsoft.DotNet.TemplateLocator` is used for optional workloads which are not yet live, that's the reason probably why the version is hardcoded, as it was just used for initial implementation. 

imo it is not possible to move `Microsoft.DotNet.TemplateLocator` to templating as it is reusing SDK features, however probably instead of calling it from `Microsoft.TemplateEngine.Cli` to determine packages to install/uninstall we can inject this information from sdk when [instantiating new command](https://github.com/dotnet/sdk/blob/27dc08c39d3ae0936d1de9e14bed34ece26fbacd/src/Cli/dotnet/commands/dotnet-new/NewCommandShim.cs#L61) , thus avoiding circular dependency. At first glance I don't see any dependency on template engine for template locator to evaluate packages to install/uninstall, but I might be wrong. 

Related issue: https://github.com/dotnet/templating/pull/2614

**Comment by wli3** [comment]
> Is this cycle intentional?

Yes. It need logic from SDK

> Can source-build rely on dotnet/templating release/5.0 always using Microsoft.DotNet.TemplateLocator/5.0.100-rc.1.20421.19, never updating?

Potentially, or only update only few times. Since when building SDK, the Microsoft.DotNet.TemplateLocator from SDK repo will be used instead. So as long as the binary interface does not change, we can keep using the old version

> Microsoft.DotNet.TemplateLocator is used for optional workloads which are not yet live

It is enabled. And it should work with Xamarin preview once it is released

**Comment by dagood** [comment]
> > Is this cycle intentional?
> 
> Yes. It need logic from SDK

@vlada-shubina outlined a way to avoid this dependency by inverting some of it:

> probably instead of calling it from `Microsoft.TemplateEngine.Cli` to determine packages to install/uninstall we can inject this information from sdk when [instantiating new command](https://github.com/dotnet/sdk/blob/27dc08c39d3ae0936d1de9e14bed34ece26fbacd/src/Cli/dotnet/commands/dotnet-new/NewCommandShim.cs#L61) , thus avoiding circular dependency.

It would be fantastic if you could do this. It avoids that API break risk, and more directly looming for me, it avoids the extra manual maintenance the current situation will be putting source-build folks through for each upgrade 😕

/cc @dleeapho @dseefeld @crummel

**Comment by wli3** [comment]
> it avoids the extra manual maintenance the current situation will be putting source-build folks through for each upgrade 😕

If we consider template engine as a separate component, it should have the functionality to manage all templates location including workload. By separating `Microsoft.DotNet.TemplateLocator` out and inject in runtime by SDK, template engine become crippled without SDK. That would prevent future reuse of template engine.

Ideally the dependency should be something like this. Be we also don't want to spin more repos.

```
                                                              +-------------+
                                       +----------------------+ SDK         |
                                       |                      +--------+----+
                                       v                               |
+--------------------------------------+----------+                    |
|SDK resolver and Microsoft.DotNet.TemplateLocator+<-------+           |
+-------------------------------------------------+        |           v
                                                           +-----------+------+
                                                           ++Template  engine |
                                                            +-----------------+


```

It is cart before the horse to bend design to fit build requirement. That said, I did not realize it will cause problem for source build. And there is no plan to use template engine outside SDK. We probably can find some solution to it. I think let dotnet/templating to expose something like ITemplateLocator, make Microsoft.DotNet.TemplateLocator implement it and dependency inject in runtime would be an easier transition.

**Comment by dagood** [comment]
> I did not realize it will cause problem for source build.

Yeah, this is definitely a problem with the current way source-build happens, and one of the things I'm looking forward to most about arcade-powered source-build. Then this would have shown up as a CI failure back then and we could have discussed it before GA rather than after. 😛

> If we consider template engine as a separate component, it should have the functionality to manage all templates location including workload. By separating `Microsoft.DotNet.TemplateLocator` out and inject in runtime by SDK, template engine become crippled without SDK. That would prevent future reuse of template engine.

Have security fixes been considered here? I.e. if dotnet/sdk takes a `Microsoft.DotNet.TemplateLocator` security fix that doesn't break binary compatibility, users of `Microsoft.TemplateEngine.Cli` are left implicitly depending on an insecure version. It's possible to be conscious of this rebuild dotnet/sdk -> insert into dotnet/templating -> rebuild dotnet/templating -> insert into dotnet/sdk. Or, we could request that all users override their `Microsoft.DotNet.TemplateLocator` version manually. But these solutions seem cumbersome and easy to miss.

Since there's no plan for people to use the package standalone, this isn't a factor yet, but I wanted to raise it in case this affects things.

> I think let dotnet/templating to expose something like ITemplateLocator, make Microsoft.DotNet.TemplateLocator implement it and dependency inject in runtime would be an easier transition.

:+1:

I can see how this makes it more cumbersome to use `Microsoft.TemplateEngine.Cli` standalone (having to also depend on `Microsoft.DotNet.TemplateLocator` and inject the implementation) but this would be a solid fix as far as the cycle goes.

**Comment by dagood** [comment]
About priority/scheduling:

I bring up the non-source-build issues with this cycle for you to look at and evaluate on its own merits, in case this is a product bug that needs to be fixed from that perspective. I don't have any real perspective on how this affects criticality and schedule, it's just that if this rises to the level of a product bug, the source-build perspective probably doesn't matter as much.

As far as source-build goes, this is a maintainability fix. There's not much point in trying to fix it for 5.0.100 GA (that is, giving us a set of patches that fix it that we can apply to the 5.0.100 GA commits), and since you don't expect to update this reference often in 5.0.1xx servicing, it isn't a huge concern for me right now in `release/5.0`. I wouldn't be alarmed if this ends up only getting fixed in 6.0. And even it if never gets fixed, that's not necessarily a problem in itself. (At some point, the maintenance burden will shift to you, when arcade-powered source-build is fully online.)

**Comment by vlada-shubina** [comment]
Agreed: 
- Template Engine to define `ITemplateLocator` interface (1 method) and `IOptionalSdkTemplatePackageInfo` interface and change `Microsoft.TemplateEngine.Cli` to use it instead `Microsoft.DotNet.TemplateLocator` members
- once done SDK will inject implemetation of `ITemplateLocator` from `Microsoft.DotNet.TemplateLocator` when calling TE in the shim

**Comment by DavidKarlas** [comment]
Just note to myself:
We can solve this easily by implementing OptionaWorkloadPackagesProvider on SDK side, once TemplateDiscovery is merged.

**Comment by DavidKarlas** [comment]
This is now fixed via
https://github.com/dotnet/templating/pull/3052
and
https://github.com/dotnet/sdk/pull/16967
