### ISSUE TITLE
forms replace regex pattern seems to work only with uppercase letters

### ISSUE THREAD

**Issue by Strizzi12** [dotnet/templating#2657]
It seems like there is a bug in the forms replace regex pattern. When creating a new solution with the following template and the CLI command `dotnet new dev.backend.template -n Test.Backend -o Test.Backend` any `cloudbuild.project.name.template` string in files gets replaced with `Test.Backend` like it should be without the forms replace. (Tested with different files containing the `cloudbuild.project.name.template` string)

With forms replace it does not work as expected. I tried many different regex patterns where it seems that only patterns with uppercase letters work.
What patterns I tried and the result:

- "\\\\." -> "Test.Backend",
- "e" -> "Test.Backend",
- "T" -> "-est.Backend"
- "Te" -> "-st.Backend"
- "([^A-Za-z0-9])" -> "Test.Backend"

With the name "Test.BackeTnd":
- "T" -> "-est.Backe-nd"
- "eT" -> "Test.Back-nd"
- "e" -> "Test.BackeTnd"

template.json:
```
{
  "author": "Me",
  "classifications": [
    "Web"
  ],
  "name": "Dev Backend Template",
  "preferNameDirectory": "true",
  "shortName": "dev.backend.template",
  "symbols": {
    "name": {
      "dataType": "string",
      "fileRename": "Backend.Project.Template",
      "type": "parameter",
      "replaces": "Backend.Project.Template"
    },
    "name": {
      "dataType": "string",
      "type": "parameter",
      "replaces": "cloudbuild.project.name.template",
      "forms": {
        "global": ["dotToMinus"]
      }
    },
  },
  "forms": {
    "dotToMinus": {
      "identifier": "replace",
      "pattern": "\\.",
      "replacement":"-"
    }
  },
  "tags": {
    "language": "C#"
  }
}
```

Dotnet version: 3.1.404
Platform: Windows 10

**Comment by Strizzi12** [comment]
Seem to missunderstood this feature after step-by-step debugging of the templating engine

**Comment by sayedihashimi** [comment]
@Strizzi12 side note, you should add the `type` tag, it can be either `project` or `item`, for example

```
  "tags": {
    "language": "C#",
    "type" : "project"
  }
```

FYI I am working on a tool to validate templates, it would be great if you can try it out, more info at https://github.com/sayedihashimi/template-sample#template-analyzer.
