### ISSUE TITLE
--name argument casing is not preserved

### ISSUE THREAD

**Issue by mrmartan** [dotnet/templating#2658]
## Repro steps

Using .NET SDK 5.0.100 and having custom template in folder `customwebapi`. Contents created using `dotnet new webapi`.  

**template.json**
```json
{
  "$schema": "http://json.schemastore.org/template",
  "classifications": [
    "Web",
    "WebAPI"
  ],
  "identity": "Custom.Templates.Project.WebAPI",
  "name": "Custom WebAPI Project",
  "tags": {
    "language": "C#",
    "type": "project"
  },
  "shortName": "customwebapi",
  "sourceName": "customwebapi",
  "preferNameDirectory": true
}
```

Installed the template using `dotnet new -i ./` Now running:

```bash
mkdir test
cd test
dotnet new customwebapi --name MyNewTemplatedProj
```

## Actual

```text
\---test
    \---MyNewTemplatedProj
        |   appsettings.Development.json
        |   appsettings.json
        |   MyNewTemplatedProj.csproj
        |   Program.cs
        |   Startup.cs
        |   WeatherForecast.cs
        |
        +---.vs
        |   \---MyNewTemplatedProj
        |       +---DesignTimeBuild
        |       |       .dtbcache.v2
        |       |
        |       \---v16
        |               .suo
        |
        +---Controllers
        |       WeatherForecastController.cs
        |
        \---Properties
                launchSettings.json
```

So far so good. The problem is the content of the files is replaced incorrectly.

**launchSettings.json**
```json
{
  "$schema": "http://json.schemastore.org/launchsettings.json",
  "profiles": {
    "mynewtemplatedproj": {
      "commandName": "Project",
      "dotnetRunMessages": "true",
      "launchBrowser": true,
      "launchUrl": "swagger",
      "applicationUrl": "http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

**WeatherForecast.cs**
```csharp
using System;

namespace mynewtemplatedproj
{
    public class WeatherForecast
    {
        public DateTime Date { get; set; }

        public int TemperatureC { get; set; }

        public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);

        public string Summary { get; set; }
    }
}
```

## Expected

The casing of value of  `--name`  ("MyNewTemplatedProj") is preserved, e.g. in `namespace MyNewTemplatedProj`

**Comment by vlada-shubina** [comment]
@mrmartan using lower case (`customwebapi`) for source name is not a good choice. The transformations applied to this value are not providing different results.
Please refer to [wiki](https://github.com/dotnet/templating/wiki/Naming-and-default-value-forms) article explaining transformations applied.

I would recommend to use `CustomWebApi` as source name and retry. If you still have the issue after that, please let us know. Providing full template in this case will be helpful. Thanks.

**Comment by mrmartan** [comment]
It really is the full template. All it is, is the output of `dotnet new webapi` and the `template.json` I posted.

You suggestion helped. I did not know about your wiki. I went by the [docs](https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates) and they do not mention the casing for `sourcename` is significant.

**Comment by vlada-shubina** [comment]
We are working on getting more information on docs.microsoft.com, at the moment there is only link to wiki available.
I'm closing the issue now, do not hesitate to reopen if you have any further problems on that.
