### ISSUE TITLE
templates do not create dotfiles

### ISSUE THREAD

**Issue by divinebovine** [dotnet/templating#2665]
I have several dotfiles in my template for example .gitignore, .dockerignore, and .editorconfig. Whenever I create a new project with these templates all files are created except for these dotfiles.

```sh
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.100/

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.1.404 [/usr/share/dotnet/sdk]
  5.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by divinebovine** [comment]
This appears to actually be an issue with dotnet pack not including dotfiles.

**Comment by divinebovine** [comment]
Ok, an update to this. The reason the files are missing is because dotnet pack excludes dotfiles much like nuget pack. However nuget pack has an option `NoDefaultExcludes` that is missing in dotnet pack. Created a new issue for this and looking for a temporary workaround.

https://github.com/dotnet/sdk/issues/14600

**Comment by divinebovine** [comment]
Found a fix, ` dotnet pack /p:NoDefaultExcludes=true`

**Comment by feffe81** [comment]
Anyone have an idea how to specify this when using the CI tasl DotNetCoreCLI@2 - .NET Core v2 task?
