### ISSUE TITLE
Template engine replaces PackageReference Include="nugetName" in .csproj when templating from folder

### ISSUE THREAD

**Issue by lostphenomenon** [dotnet/templating#2666]
USING dotnet new my-template-name
WHEN <PackageReference Include="nugetName" Version="1.3.0" />
AND sourceName in template.json equals nugetName
AND folderName of root folder (of the template) equals nugetName
THEN the engine replaces the package reference Include attributes value with the name of the root folder where the dotnet new my-template-name was called

**Comment by vlada-shubina** [comment]
@lostphenomenon Could you please clarify if you provide --name or --output when running your template?
In case no, the root name of the folder will be used as the source name and will replace the occurrences of the source name in template files. 
If the replace of the file contents is not desirable, you might use `copyOnly` [option ](https://github.com/dotnet/templating/wiki/Reference-for-template.json#source-definition) of `source` definition if your template to skip content modification for certain file, or refer to [wiki](https://github.com/dotnet/templating/wiki/Reference-for-comment-syntax#ignore-conditions-expressions-in-language-files) article which explains how to disable processing of the file partially. 

Thank you.

**Comment by vlada-shubina** [comment]
Closing the issue. Do not hesitate to reopen it if the suggestion above doesn't help.
