### ISSUE TITLE
Add end-to-end tests defined in tools/ProjectTestRunner to local/CI build

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#2669]
we have end-to-end tests defined in tools/ProjectTestRunner, however they are not run anymore. 
Consider adding them to:
- local build process
- CI build process

There is a documentation explaining the features of the framework: https://github.com/dotnet/templating/wiki/Testing-your-templates

**Comment by YuliiaKovalova** [comment]
Close with Low Priority
