### ISSUE TITLE
Review content links to always use https for short-url to dotnet docs

### ISSUE THREAD

**Issue by peterblazejewicz** [dotnet/templating#267]
Some links are still using `http` instead of `https`.

For example:
https://github.com/dotnet/templating/blob/75e1bfb9fcf960dc3530db8d689c7a9c8f3c8d0b/template_feed/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-CSharp/Services/MessageServices.cs#L10
which nomen-omen points to `Security` :)

https://github.com/aspnet/Templates/issues/656

Thanks!

**Comment by mlorbetske** [comment]
Fixed by #308
