### ISSUE TITLE
Update names of the ASP.NET Core templates

### ISSUE THREAD

**Issue by danroth27** [dotnet/templating#268]
The current names of the ASP.NET Core templates are a bit awkward:
- Empty ASP.NET Core Web Application 
- MVC ASP.NET Core Web Application
- Web API ASP.NET Core Web Application

Proposed updates:
- ASP.NET Core Empty
- ASP.NET Core Web App
- ASP.NET Core Web API

@mlorbetske @DamianEdwards @sayedihashimi

**Comment by sayedihashimi** [comment]
Yes I like this idea, lets go ahead with the change

**Comment by mlorbetske** [comment]
Fixed with #341
