### ISSUE TITLE
Improve the error handling on dotnet new initialization

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#2685]
Recently we have several issues with unhandled exceptions on dotnet new initialization (null ref, dictionary etc). 
- https://github.com/dotnet/templating/issues/2677
- TBD 

Consider better error handling for this step (catching exceptions, showing meaningful error messages etc.)

**Comment by bozturkMSFT** [comment]
Internal discussions:
 - We should have better logging, which will be partly delivered [here](https://github.com/dotnet/templating/issues/2811).
 - Nullable reference types will help us avoid some of the exceptions. We will track it [here](https://github.com/dotnet/templating/issues/2976).
