### ISSUE TITLE
 error NU1202: Package is not compatible with netcoreapp1.0, but package did not reference  

### ISSUE THREAD

**Issue by jiyoon-koo** [dotnet/templating#2696]
I have done the following:

1. Created a template and published it as a nuget package on a private nuget feed in Azure DevOps

2. Followed [this comment](https://github.com/dotnet/templating/issues/1747#issuecomment-618519996) to authenticate myself so that I can pass in `--nuget-source {my_private_nuget_feed}` in the `dotnet new -i` command

3. Attempting to run the command in Step 2 causes this issue for me. Log is pasted below. This seems to have also happened to another user, as demonstrated [here](https://github.com/NuGet/Home/issues/7863)

```
$ dotnet new -i {my_template_name} --nuget-source {my_private_nuget_feed}

  Determining projects to restore...

C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): 
warning NETSDK1138: The target framework 'netcoreapp1.0' is out of support and 
will not receive security updates in the future. 
Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. 

[%user%\.templateengine\dotnetcli\v5.0.100\scratch\restore.csproj]

%user%\.templateengine\dotnetcli\v5.0.100\scratch\restore.csproj : 
error NU1202: Package {my_template} 1.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). 
Package {my_template} supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1)

Failed to restore %user%\.templateengine\dotnetcli\v5.0.100\scratch\restore.csproj (in 171 ms).
```

I do not reference netcoreapp1.0 anywhere on the template. The location where I'm trying to call the `dotnet new -i` command is an empty folder, and also does not dictate what version of .NET core should be run... Any help would be appreciated, thank you!

**Comment by vlada-shubina** [comment]
@jiyoon-koo this is a known issue https://github.com/dotnet/templating/issues/2627 and will be fixed in 5.0.1 servicing release.

The template you are creating is not causing this issue; the issue was that the project shim used to install the template under the hood of `dotnet new` was still using `netcoreapp1.0`

I'm closing this issue now, please do not hesitate to reopen in case your issue is not solved in 5.0.1. Thank you.
