### ISSUE TITLE
Remove --debug:version

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#2697]
We have decided to remove `--debug:version` after discussions. This tasks will track the removal work.

--------------------------------
Output for `dotnet new --debug:version`

```
dotnet new --debug:version
Template Instantiation Commands for .NET Core CLI

 Version:
 Commit Hash:
```

Consider make it `--version` instead of `--debug:version`.

**Comment by oliver254** [comment]
The GitInfo class is empty.
Should this class be populated by the ci?

**Comment by KathleenDollard** [comment]
What version would we expect to display? Even if we had a template version, it might be different for different templates with that name. 

Any reason not to drop this feature?

**Comment by DavidKarlas** [comment]
Since we probably want to show same version as `dotnet --version`, I agree with dropping this feature.
