### ISSUE TITLE
.net Framework MVC template with HTTPS

### ISSUE THREAD

**Issue by anth12** [dotnet/templating#2699]
When creating an asp.net framework template with HTTPS enabled, the generated output won't run under HTTPS. I don't believe this is an issue with dotnet templating, but I'm hoping it's sufficiently relevant to get some assistance/pointed in the right direction.

Steps to reproduce:
- Clone https://github.com/anth12/aspnet-templating-https/tree/main
- Install the template `dotnet new --install ./`
- Create a new project using the template `dotnet new mvc-https-demo`
- Run the generated project from Visual Studio (using IIS Express)

Expected result:
The site runs under http & https.
Actual:
The site runs fine on the http port but not on the https port.

_The template runs under the following ports;_
https://localhost:44309
http://localhost:56533

**Comment by DavidKarlas** [comment]
Hi,

Inside your template you need to add "Properties/launchSettings.json" file.

See example here:
https://github.com/dotnet/aspnetcore/blob/master/src/ProjectTemplates/Web.ProjectTemplates/content/WebApi-CSharp/Properties/launchSettings.json

Hope that helps.

**Comment by anth12** [comment]
Thanks, I believe launchSettings.json is only for .net core projects?

**Comment by DavidKarlas** [comment]
Seems like you do everything right by setting
```
    <IISExpressSSLPort>XXXX</IISExpressSSLPort>
```
but for some reason ISS doesn't listen on that port :(
Not sure if this is templating issue... And Im not familiar enough with how IIS should work...

**Comment by anth12** [comment]
Thanks for your suggestions.

It turns out the IIS Express port range I was using to replace was too wide. IIS Express, by default, only seems to support 44300-44399 for SSL:
https://docs.microsoft.com/en-us/iis/extensions/using-iis-express/handling-url-binding-failures-in-iis-express#using-a-custom-ssl-port
