### ISSUE TITLE
Symbol startsWith

### ISSUE THREAD

**Issue by kaflake** [dotnet/templating#2708]
Hi,
I try to set a symbol to set to true, if the name starts with a specific string.
I can test, if the string is the same with

`    
"StartWidthPrefix": {
      "type": "computed",
      "value": "(name == \"MyPrefix\")"
    }
`

but something like

`   
 "StartWidthPrefix": {
      "type": "computed",
      "value": "(name.startsWith(\"MyPrefix\"))"
    }
`

is not working. Is there away to do somthing like this?

**Comment by DavidKarlas** [comment]
You could use [RegexMatch](https://github.com/dotnet/templating/blob/master/docs/Available-Symbols-Generators.md#regexmatch)
So symbol would look like this:
```json
"StartWidthPrefix": {
  "type": "generated",
  "generator": "regexMatch",
  "parameters": {
        "source": "name",
        "pattern": "^MyPrefix"
      } 
}
```
`^` in Regex means string that is being matched must start with rest of regex.

I hope this helps.

**Comment by kaflake** [comment]
Thank you very much. It works perfectly. I only searched in the wiki doku, which seem to be not up to date.
