### ISSUE TITLE
Update link to Cake.Frosting template on wiki (C# Community Templates)

### ISSUE THREAD

**Issue by augustoproiete** [dotnet/templating#2710]
Please, update the link to the repository of the [Cake.Frosting template in the C# Community Templates](https://github.com/dotnet/templating/wiki/Available-templates-for-dotnet-new#c-templates) in the wiki to https://github.com/cake-build/cake which is the new location where the templates are (the current link points to the old and archived repo).

[![image](https://user-images.githubusercontent.com/177608/102292995-9d8f9900-3f1c-11eb-9778-5244c3d44d6d.png)](https://github.com/dotnet/templating/wiki/Available-templates-for-dotnet-new#c-templates)

**Comment by DavidKarlas** [comment]
Opened PR to fix this, thank you for reporting this issue.

**Comment by augustoproiete** [comment]
Thank you @DavidKarlas!

What is the relationship between [the file that you updated](https://github.com/dotnet/templating/blob/34960afb11417927d3ec6362126b192f0e9e6dbc/docs/Available-templates-for-dotnet-new.md) in your PR and [the wiki page](https://github.com/dotnet/templating/wiki/Available-templates-for-dotnet-new) with the template list?

Is there automation that will copy the changes you've made, to the Wiki at some point? I ask because the wiki is still outdated even after your PR was merged.

**Comment by DavidKarlas** [comment]
I just synced Wiki with docs/ folder.

Thank you for reminding me.

We have plan to automate this.

**Comment by augustoproiete** [comment]
Perfect. Thanks!

ps: I didn't know that was the workflow, otherwise I would have opened a PR myself :smile:
