### ISSUE TITLE
New3Command.Run outputs to StandardOut/StandardError

### ISSUE THREAD

**Issue by philasmar** [dotnet/templating#2714]
Hello,

We are using the New3Command class to run commands using the templating engine. 
Currently, that is writing directly to StandardOut/StandardError. We need a way to override this behavior and specify where the output is sent.

**Comment by DavidKarlas** [comment]
May I ask what is the use case?
 * Maybe you should be using "Microsoft.TemplateEngine.IDE" or "Microsoft.TemplateEngine.Edge"+"Microsoft.TemplateEngine.Orchestrator.RunnableProjects" Nugets?
 * Hacky workaround would be to call https://docs.microsoft.com/en-us/dotnet/api/system.console.setout?view=net-5.0
 * Another Hacky way would be executing `dotnet new` as sub-process

**Comment by philasmar** [comment]
I was using the Cli nuget package and not the IDE one. Switching to that gave me what I was looking for. Thanm you!
