### ISSUE TITLE
Create templates for template authors

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#2722]
https://docs.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-template-pack contains a lot of manual steps that can be avoided when using the templates

Create templates:
- `templatepack`: project template; contains csproj file setup for template packing, required folder structure, one sample template (that can be disabled by parameter). This template should be ready to go for the first template.
- `templatejson`:  item template for template.json file
   - add `$schema`
- consider creating sample templates for csproj and other project types

Update documentation after the package is available.

**Comment by DavidKarlas** [comment]
Consider not creating .csproj but instead .nuspec file, but for that we probably need https://github.com/NuGet/Home/issues/4254 to be fixed.

**Comment by paulomorgado** [comment]
Maybe it's overkill but, probably, a specific SDK would circumvent the need for having any kind of project that Visual Studio needs to understand.

**Comment by zivkan** [comment]
> Consider not creating .csproj but instead .nuspec file,

why is that?

With a project file the project can be added to the solution and customers using Visual Studio can more easily see and edit their templates. 

Running `dotnet pack` on a solution automatically runs pack on all projects in the solution, and therefore build scripts can be simpler.

For these reason I suggest the overall customer experience will be improved with a csproj, not a nuspec.
