### ISSUE TITLE
Only check for updates for user installed templates

### ISSUE THREAD

**Issue by DavidKarlas** [dotnet/templating#2738]

**Comment by vlada-shubina** [comment]
Related: https://github.com/dotnet/templating/issues/2616

**Comment by 89z** [comment]
Since the other issue was closed, and this one doesnt really have any context, let me add some. The current behavior is to check for template updates of any kind, without any way to opt out by the user.

**Comment by 89z** [comment]
https://github.com/dotnet/templating/issues/2739

**Comment by vlada-shubina** [comment]
#2738 temporarily fixes the issue by removing SDK packages from template search cache file, so updates for SDK shipped templates will never appear in CLI. Updates to the templates (if any) are shipped with new version of SDK so there is no need to check them on NuGet.
The permanent fix will be provided together with new approach to storing the installed templates on disk as the templates shipped with SDK will have a different flow from user installed templates and SDK shipped templates won't be checked for updates.

**Comment by vlada-shubina** [comment]
The permanent fix will be delivered with https://github.com/dotnet/templating/issues/2745. Keeping open for now.

**Comment by 89z** [comment]
These issues you guys keep opening, have nothing to do with the root issue.

The root issue is: I dont want the tool checking for updates. I have stopped all personal programming in C#, because I feel that the `dotnet` tool doesnt respect my privacy. **I dont want the tool checking for updates, unless I tell it to.**

**Comment by DavidKarlas** [comment]
Thats what https://github.com/dotnet/templating/issues/2739 is supposed to fix.

**Comment by KathleenDollard** [comment]
There are two issues: 

* We were displaying a suggestion to update template NuGet packages when it was not appropriate. This is a bug that we are fixing and is this issue.
* We do not have a mechanism for users to opt out of checking for updates, which is issue #2739. That's a good idea for folks that want to control their data usage, and just generally a good idea. We plan to do this. 

The mechanism we use is to download a file from blob storage. As an Open Source project, you can check this. 

We take privacy quite seriously. You can check our privacy statement [here](https://privacy.microsoft.com/en-us/privacystatement) and information about the telemetry we collect [here](https://docs.microsoft.com/en-us/dotnet/core/tools/telemetry).

Again, we agree that allowing you to turn off the check for template updates is a good idea and are planning it in #2739

**Comment by 89z** [comment]
Why was this closed? Can we get some communication here?

**Comment by DavidKarlas** [comment]
Sorry, I didn't comment, as part of refactoring and big PR we did recently, we don't check updates for SDK installed templates anymore which fixes this issue, but notice that https://github.com/dotnet/templating/issues/2739 is still open and is scheduled to be fixed in May.
