### ISSUE TITLE
As a customer, speed up my first run of "dotnet new console"

### ISSUE THREAD

**Issue by DavidKarlas** [dotnet/templating#2743]
Things that can be improved for .NET 6:

- ~3sec: [Run template instantiation and check for updates in parallel #2717](https://github.com/dotnet/templating/issues/2717)
- ~300ms: [FirstRun can take long time because it needs to install/scan multiple packages, this could be done in parallel #2741](https://github.com/dotnet/templating/issues/2741)
- ~400ms: [Cache HostSpecificDataLoader.ReadHostSpecificTemplateData #2742](https://github.com/dotnet/templating/issues/2742)
- ~100ms: [Stop using reflection for ITemplateEngineHost.BuiltInComponents](https://github.com/dotnet/templating/issues/3075)

Some of this changes will improve also general `dotnet new` usage not just 1st...

**Comment by vlada-shubina** [comment]
Closing as .NET 6 epic, moved outstanding issues to .NET 7
