### ISSUE TITLE
Command to list installed templates and metadata

### ISSUE THREAD

**Issue by joacar** [dotnet/templating#2755]
Hi,

It would be great if `dotnet new` support similar command as `dotnet tool list -g`. The new command would output
* What version is installed
* From what source it was installed
* Where it's installed

Thanks!

**Comment by DavidKarlas** [comment]
* What version is installed
 * You probably mean NuGet packages version? `dotnet new -u` prints version and bunch of other stuff 
* From what source it was installed
 * Do you mean NuGet Soruces like myget.org or some internal NuGet server or something else? If its former, we don't have/display that information anywhere
* Where it's installed
 * Everything is installed in $HOME\.templateengine\dotnet-cli\{sdk-version}\packages

We probably need better way for this...

**Comment by joacar** [comment]
@DavidKarlas Thanks for quick reply. I wasn't aware of `dotnet new -u` actually writing out all information, thanks for that. However the format isn't very easy to quickly navigate and a more condensed view option would be preferable. The `list -g` is nice table format

```
$ dotnet tool list -g
Package Id           Version              Commands
---------------------------------------------------------
dotnet-counters      3.1.57502            dotnet-counters
dotnet-ef            3.1.7                dotnet-ef
dotnet-serve         1.7.122              dotnet-serve
dotnet-trace         3.1.57502            dotnet-trace
powershell           6.2.4                pwsh
```

To view specific version installed for a given template id one go to her inner command line hacker. Example  
```
dotnet new -u | grep -A 2 <id>
<id>
    Details:
      NuGetPackageId: <id>
      Version: 1.1.5
      Author: <author>
--
      dotnet new -u <id>
```

**Comment by DavidKarlas** [comment]
I agree, we should make that output tabular, hence keeping this issue open and also should be accessible without `uninstall`(`-u`) command

**Comment by DavidKarlas** [comment]
Notice that we do have `dotnet new --list` but doesn't include versions.

**Comment by vlada-shubina** [comment]
- consider adding new option/subcommand to print tabulated list of installed packages
- SDK shipped templates / optional workloads should not be shown in that list

**Comment by YuliiaKovalova** [comment]
This will be delivered by https://github.com/dotnet/templating/issues/2908 and https://github.com/dotnet/templating/issues/2909.
