### ISSUE TITLE
Modify NuGetInstaller to support multiple download / update implementations

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#2812]
At the moment:
- installation from NuGet is done using dotnet restore
- updates from NuGet are checked via template search cache file

- create interfaces for install update
- existing implementation should implement these interfaces
- logic on how the installer/updater should be picked up TBD.

**Comment by bozturkMSFT** [comment]
We have decided not to keep the support for the old way. Changes in the related epic should deliver the new feature. No other work will be needed. Closing.
