### ISSUE TITLE
Issues in template discovery

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#2829]
- [x] ManagedTemplateSource should have GetLatestVersion/Update/Uninstall methods implemented as well as ManagedSourceProvider.
- [x] When deserializing the sources in GlobalSettingsProvider, if no installer found create ITemplateSource instead
- [x] race condition on saving global settings (moved to https://github.com/dotnet/templating/issues/2857)
- [x] Bootstrapper should also have an ability to virtualize the global settings
- [x] remove command option for "allowDevInstall"
- [x] rename InstallUnitDescriptors everywhere
- [x] rename *TemplateSource to *TemplatePackage in the code

**Comment by bozturkMSFT** [comment]
We should also remember to remove the branch from pipeline definition by reverting this PR https://github.com/dotnet/templating/pull/2839.
