### ISSUE TITLE
Is there a template for template.json

### ISSUE THREAD

**Issue by bitbonk** [dotnet/templating#2832]
Does a template for `.template.config/template.json` exist in a package somewhere so I can create it with `dotnet new` or `dotnet add`? And may also for the other things I need for template authoring (e.g. the main template csproj).

**Comment by vlada-shubina** [comment]
@bitbonk we have already planned this work in https://github.com/dotnet/templating/issues/2722. Could you please follow it up in that issue? Thank you.
