### ISSUE TITLE
Add support for partial matches in choice parameters

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/templating#284]
It'd be nice to be able to specify `dotnet new mvc -au Individual` as `dotnet new mvc -au ind` (or other partial forms of the value).

We can use the same logic as we do for partial name matching. A single match for the supplied value uses the matching value, zero or more matches (error) would display help for the template

@sayedihashimi @seancpeters

**Comment by sayedihashimi** [comment]
I think we should hold off on this. We've already received a bit of negative feedback on the partial name match for templates.

Also thinking about this a bit more, considering that we are going to have an interactive mode, I think the explicit mode doesn't have to have features like partial match.

**Comment by seancpeters** [comment]
Fixed in #366
