### ISSUE TITLE
Add support to make them composable, inheritable

### ISSUE THREAD

**Issue by attilah** [dotnet/templating#285]
"Composable" templates and "template inheritance" would be an awesome feature to get rid of copy paste...of course it involves template dependency and templates referencing each other.

When it comes to dependency, there comes the versioning and dependency type.

Since multiple install sources are supported (local, git, nuget) I think the the same kind of dependencies should be supported (just like in npm).

So for example TemplateA can depend a given git commit of TemplateB and it is possible that TemplateA is coming from a NuGet package.

Versioning: Just take NuGet's version dependency handling, that's already figured out, written, just need to reuse.

**Comment by sayedihashimi** [comment]
We've discussed this and we are not currently thinking to support this. By enabling composable templates we believe that it would be very easy to get to a state that the generated content has a much higher chance of not working correctly.
We will monitor this and revisit the decision but for the time being we are not planning to support this. I'm going to close this issue for now but if it keeps coming up we will revisit it.

**Comment by attilah** [comment]
Hi @sayedihashimi !

I am sure you are aware of the https://github.com/Microsoft/WindowsTemplateStudio project, which built upon .Net Core templating and they made possible some kind of composition already.

It would be good to get to a common ground and not to have n+1 templating solutions out there...

**Comment by sayedihashimi** [comment]
I didn't realize this was related to WTS. I'll reopen and discuss with @mlorbetske

**Comment by mlorbetske** [comment]
@seancpeters could you come up with & post a proposal for how this could work? We talked about having a post-action that could create another template previously, but I'm not sure how well that covers everything here

**Comment by donJoseLuis** [comment]
We will add this to a bucket for which we are planning template sets improvements.  At the point when all backlog issues have been reviewed and placed in corresponding buckets; we'll then order by priority each item per bucket.  ETA: by end of March.

once this is done, we'll schedule delivery.

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by donJoseLuis** [comment]
This issue is over 3 years old & last updated around the same time.
