### ISSUE TITLE
PostAction manual instructions are not localized

### ISSUE THREAD

**Issue by bozturkMSFT** [dotnet/templating#2869]
We support localizing manual instructions in post actions. However, the engine cannot properly parse the localized template.json file and retrieve the manual instructions.

**Comment by DavidKarlas** [comment]
I'm curious, where is the problem? https://github.com/dotnet/templating/blob/master/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/Localization/PostActionLocalizationModel.cs#L25 or somewhere else?

**Comment by bozturkMSFT** [comment]
Yes, at the line you linked.
