### ISSUE TITLE
Combine sources from different folders in generation

### ISSUE THREAD

**Issue by sibille** [dotnet/templating#287]
Hi, 

I'm configuring a partial generation and want to include some files from another directory.

My folder structure is the following:
```
	/
		Templates/
			BlankPage/
				.template.config
				BlankPage/
					BlankPage.xaml
					BlankPagePage.xaml.cs
					BlankPageViewModel.cs
				MVVMLight/
					ViewModelLocator.cs
```
					
					
					
The sourceName is BlankPage, and what I want to achieve is that both the content from BlankPage and MVVMLight is copied into a folder with the name the user specifies. 

My current configuration is the following 

```
"sources":
  [
    {
        "source" : "./"
    },
    {
        "source" : "../MVVMLight",
        "target":"./BlankPage",
        "condition": "(isMVVMLight)"
    }
  ],

```
In the case of BlankPage the sourceName is replaced correctly, (BlankPage folder is called Blank (as user specified in name) for example), but the files from the MVVMLight folder are copied to a folder called BlankPage (the sourceName is not replaced here).

Thanks for your help and best regards, 
Sibille

**Comment by sayedihashimi** [comment]
@sibille thanks for the issue. I think @mlorbetske is going to reply back with some more info. If you don't mind me asking, what are you working on? If it's open source I'd love to take a look at the templates you're creating.

**Comment by mlorbetske** [comment]
This behavior comes from https://github.com/dotnet/templating/blob/rel/vs2017/rtw/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/RunnableProjectGenerator.cs#L44, essentially, when a source is specified, it's currently assumed that the target contains only literals (no substitution is done for name or other symbols). We should change that to make things like this easier to accomplish/more intuitive.

@sibille for the time being, if your directory structure were to change to this:

```
	/
		Templates/
			BlankPage/
				.template.config
				BlankPage/
					BlankPage.xaml
					BlankPagePage.xaml.cs
					BlankPageViewModel.cs
				MVVMLight/
                                        BlankPage/
					        ViewModelLocator.cs
```

and your second source changed to have a target of `./`, then this should work
