### ISSUE TITLE
Feature request: --no-cache for dotnet new

### ISSUE THREAD

**Issue by stefanloerwald** [dotnet/templating#2874]
Hi, similar to https://github.com/dotnet/sdk/issues/9577, there's currently no way to to force an update to the cache of packages used for `dotnet new` other than to wait. It would be great if `dotnet new` also understood `--no-cache` such that the cache can be avoided explicitly.

**Comment by vlada-shubina** [comment]
@stefanloerwald we are currently reworking the NuGet integration in scope of https://github.com/dotnet/templating/issues/2745 and https://github.com/dotnet/templating/issues/2592. 

For template engine purposes, we decided not to use cache at all for any calls to NuGet by default, so option is not needed. 
Commit fixing the issue: https://github.com/dotnet/templating/pull/2876/commits/c6b567c155abf8ba57589b2f1208d748bb28d5e0

We will close the issue once the feature branch is merged to master.

**Comment by vlada-shubina** [comment]
The implementation is already in master, closing

**Comment by LechuckThePirate** [comment]
Which version of the dotnet client includes this fix? How do I update it?

**Comment by LechuckThePirate** [comment]
> @LechuckThePirate this fix is available from .NET 6 preview 4. You can get it from https://dotnet.microsoft.com/download/dotnet.

Thanks! I will wait for the final release then... the project can wait for one month.
