### ISSUE TITLE
[Visual Studio] Template logo is changed based on VS theme

### ISSUE THREAD

**Issue by tomkerkhove** [dotnet/templating#2882]
Template logo is changed based on VS theme which gives odd outcomes:

**Light theme:**
![image](https://user-images.githubusercontent.com/4345663/108491102-c711cb80-72a3-11eb-9614-1ef4c75fb51e.png)

**Dark theme:**
![image](https://user-images.githubusercontent.com/4345663/108491131-d09b3380-72a3-11eb-878c-a29d496571b9.png)

We are using a JPG, not sure what is recommended though - https://github.com/arcus-azure/arcus.templates/tree/master/src/Arcus.Templates.AzureFunctions.Databricks.JobMetrics/.template.config

Relates to https://github.com/arcus-azure/arcus.templates/issues/297

/cc @sayedihashimi

**Comment by bozturkMSFT** [comment]
Hi @tomkerkhove,
 Thank you for the issue. 
 Rendering of the icons is not part of the templating engine and it is handled in Visual Studio.
 Please create a new ticket using Visual Studio by clicking `"Send Feedback" (at the top-right corner of VS)` -> `Report a problem`. If you can share the ticket number afterwards, I can help move it to the correct team.
