### ISSUE TITLE
Unprotected concurrent access leads to infinite loop

### ISSUE THREAD

**Issue by sharwell** [dotnet/templating#2884]
https://github.com/dotnet/templating/blob/ae5642b664ad6615e3b621be6b16e06e6e59dfc1/src/Microsoft.TemplateEngine.Edge/Settings/TemplateCache.cs#L460-L474

These two methods are called from concurrent `Scan` invocations, making it possible to corrupt the internal data structures for `Dictionary<TKey, TValue>`. This is the root cause of [AB#1283398](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1283398).

/cc @stephentoub

**Comment by sharwell** [comment]
Here's the entry point to this thread pool operation:
![image](https://user-images.githubusercontent.com/1408396/108918222-e1221580-75e5-11eb-92c6-61b9c07787a3.png)

**Comment by donJoseLuis** [comment]
@sharwell thanks for the issue.  We'll protect the relevant data structure(s) in the template engine then transfer to the team that owns the relevant integration for [AB#1283398](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1283398).

**Comment by bozturkMSFT** [comment]
This issue is on Visual Studio side and should be fixed in 16.9.
