### ISSUE TITLE
Remove EnableAnalyzers property from projects as it overrides the value from Analyzers.props

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/templating#2900]
As part of the changes for #2767 made in PR #2793, the EnableAnalyzers property was explicitly set to true in all src and test projects ([example](https://github.com/dotnet/templating/pull/2793/files#diff-0e8ae1c14576362e8c40224b7a1bc3d8c21e2f82c9a850550326c68238f8ac4bR7)).  These properties override the value set in [eng/Analyzers.props](https://github.com/dotnet/templating/pull/2793/files#diff-489b1e12d93a4928641f4e40fc9d33fe0490b257176f4f055c901dbfc8b751e5).  This not an issue for normal builds but it breaks source-build which triggers a conditional to set to property false.  This is done because the analyzers are not part of source-build and are therefore a prebuilt which is not permitted.

This is blocking the [ArPow (arcade-powered source-build)](https://github.com/dotnet/source-build/tree/master/Documentation/planning/arcade-powered-source-build) work.

**Comment by MichaelSimons** [comment]
cc @bozturkMSFT

**Comment by bozturkMSFT** [comment]
@MichaelSimons Changes were merged. Please let us know if this doesn't resolve the related issue with source build.
