### ISSUE TITLE
EOL formatting issues w/SECURITY.md

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/templating#2901]
**Steps to Reproduce**
1. docker run -it --rm ubuntu:20.04
2. apt-get update
3. apt-get install git    (At the time of logging this issue the git version is 2.25.1)
4. git clone https://github.com/dotnet/templating.git
5. cd templating
6. git diff | cat -v

**Expected Results**
No files should be changed.

**Actual Results**
SECURITY.md is a modified file.  All EOL=CRLF have been replaced with LF

**Notes**
1. I have reproduced this on a variety of environments (e.g. Windows 10, Debian, Centos, Ubuntu) with a variety of git versions and this happens consistently.
2. The git config looks like the following:

```bash
>git config -l
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/dotnet/templating.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
```

3. Removing `*.md		eol=crlf` from `.getattributes` seems to eliminate the problem.

I am confused at why this only affects `SECURITY.md`, other md files are formatted the same e.g. `CONTRIBUTING.md`.

**Comment by vlada-shubina** [comment]
@MichaelSimons thanks for raising - I've normalized all line endings in master branch, and `SECURITY.md` appeared to have wrong endings in the repo, the issue should be fixed.
