### ISSUE TITLE
Please add Avalonia.Templates to the list on the Wiki

### ISSUE THREAD

**Issue by danwalmsley** [dotnet/templating#2904]
I was not able to do a PR for the WIKI..

```
| [Avalonia UI Templates](https://github.com/AvaloniaUI/Avalonia) - Avalonia is a framework for creating cross platform UI | `dotnet new -i "Avalonia.Templates::*"`|
```

This project is in the dotnet foundation and has quite wide adoption.

Thanks

**Comment by DavidKarlas** [comment]
Should URL be https://github.com/AvaloniaUI/avalonia-dotnet-templates or https://github.com/AvaloniaUI/Avalonia ?
Also notice that the way we maintain WIKI, is by opening PR against https://github.com/dotnet/templating/blob/master/docs/Available-templates-for-dotnet-new.md and then maintainers sync docs/ folder into wiki repo.

**Comment by danwalmsley** [comment]
ok I will open a PR there... URL should be the project site or the template git repo?

**Comment by danwalmsley** [comment]
https://github.com/dotnet/templating/pull/2905

Iv added a PR, will close this issue.
