### ISSUE TITLE
Using //-:cnd:noEmit on the first line of *.cs file corrupts file content when templating new project

### ISSUE THREAD

**Issue by xtomino** [dotnet/templating#2913]
**Steps to reproduce**
1. In any *.cs file in template project add at the begining
```
//-:cnd:noEmit
#if !NOAUTH
using Microsoft.AspNetCore.Authorization;
#endif
//+:cnd:noEmit
```
2. Install this template and create a new project from that
3. It should look like this at the beginning of the modified * .cs file
```
#if !NOAUTH
using Microsoft.AspNetCore.Authorization;
#endif
```
4. Until now, everything looks good BUT... three unwanted bytes was inserted between **#if** and  **!NOAUTH**
#if**ď»ż** !NOAUTH
HEX: **EF BB BF**

An attempt to build a project fails :-(
_*.cs(1,2): error CS1024: Preprocessor directive expected
*.cs(3,1): error CS1028: Unexpected preprocessor directive_

**Workaround**
Just move the above piece of code below and put something in front of it (another using) - then everything works as expected!
using Microsoft.AspNetCore.Mvc;
```
using Microsoft.AspNetCore.Mvc;
//-:cnd:noEmit
#if !NOAUTH
using Microsoft.AspNetCore.Authorization;
#endif
//+:cnd:noEmit
```

**.NET version**
.NET 5

**Comment by DavidKarlas** [comment]
Hi,

sorry for slow response, I'm having hard time reproducing this, I have few questions:

1) Can you share this C# file, I want to see if there is some BOM that is causing problem.
2) What operating system is this on?
3) What is Language/Culture do you have set?

It's really weird that position of noEmit effects this behavior indeed.

**Comment by xtomino** [comment]
Hi David,

I prepared a testing template for you ;-)
[consoleasync.zip](https://github.com/dotnet/templating/files/6143623/consoleasync.zip)

**Steps to reproduce**

1. Unpack a content of attached file to any folder
2. Enter that folder and run command `dotnet run` - everything should be OK!
3. Well. Now you can install the template by running a command `dotnet new -i .\`
4. Create an another folder and enter it
5. Run command `dotnet new consoleasync`
6. Run command `dotnet run` and now you should see some errors
7. Inspect both files _Program.cs_ and _MyClass.cs_

Both files are encoded as **UTF-8 with BOM** in template. They are originally created by using a command `dotnet new console`.
_Program.cs_ file has `//-:cnd:noEmit` on second line in template and _MyClass.cs_ file has it on the first line.

As a result, the first file is OK and the second (_MyClass.cs_) is corrupted! **BOM** three bytes were moved after `#if`!!!
![2021-03-15 19_56_22-Window](https://user-images.githubusercontent.com/17108003/111206553-cdf0dd00-85c8-11eb-9646-dd4a0e52884a.png)

I'm on **Windows 10 1909** in **Czech** language.

Regards,
Tom

**Comment by DavidKarlas** [comment]
Thank you for quick response.
I'm able to reproduce, we will fix this.

Thank you for nice repro steps!

**Comment by DavidKarlas** [comment]
This has been fixed, again thank you for all help.
