### ISSUE TITLE
Consider removing template cache versioning TemplateInfoReaderVersionX_X_X_X

### ISSUE THREAD

**Issue by bekir-ozturk** [dotnet/templating#2929]
We currently keep 5 different versions of TemplateInfoReader (initial, 1000, 1001, 1002, 1003, 1004). 

This allows us to read the templatecache.json files created by an older version of Template Engine. But it also brings a maintenance costs: we need to update the old serializers to make sure they are compatible with the current models.

The engine doesn't use the templatecache.json generated by an older version today. This invalidates any benefit we get by keeping the versioning system alive.

Consider if we should get rid of this versioning. At the very least, we can get rid of the `TemplateInfoReader`s up to the latest one until the day we decide that the old cache files will need to be read by the engine.

**Comment by DavidKarlas** [comment]
This was fixed in https://github.com/dotnet/templating/pull/3175
