### ISSUE TITLE
Replace multiple values on one symbol

### ISSUE THREAD

**Issue by rwkarg** [dotnet/templating#2932]
I have a template that I'd like to have one symbol `framework` that triggers multiple replacements.
For example, `framework` == `netcoreapp3.1` by default to match LTS but can be optionally set to `net5.0` (and eventually `net6.0`)

`net5.0` Example:
| File | Default | `net5.0` Replacement |
|---|---|---|
| *.csproj | `netcoreapp3.1` | `net5.0` |
| Dockerfile | `3.1.407` | `5.0.201` |
| Dockerfile | `3.1.13` | `5.0.4` |
| global.json | `3.1.100` | `5.0.100` |

It doesn't look like there's currently a way to do that. If there is then an example would be good to show how it's done.

**Comment by DavidKarlas** [comment]
Hi,

I'm not 100% sure what you are trying to achieve.
But sounds like Switch generator might be useful: https://github.com/dotnet/templating/wiki/Available-Symbols-Generators#switch

So you could do something like this:
```
"versionInDockerFile":{
  "type": "generated",
  "generator": "switch",
  "replaces": "3.1.407",
  "parameters": {
    "datatype": "string",
    "cases": [
      {
        "condition": "framework == 'net5.0'",
        "value": "5.0.201"
      },
      {
        "condition": "framework == 'net6.0'",
        "value": "6.0.100"
      },
      {
        "condition": "true",
        "value": "3.1.407"
      }
    ]
  }
```

And then create different symbol for each of versions you want to be modify.

I hope this solves it for you, if not don't hesitate to ask more questions.

**Comment by rwkarg** [comment]
That does it. I was not able to locate a specific example describing the use of `"type": "generated"` symbols to trigger multiple different replacements from a single input symbol.
