### ISSUE TITLE
Building a host multiple times without running the equivalent of --debug:reinit leads to an unhandled exception

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/templating#294]
If building the dotnet CLI from source (for example) the configuration for the previous build is orphaned & needs to be deleted to work properly.

To fix this, we need to make sure that any packaged content gets copied into the configuration hive during the first run experience rather than leaving it where it is. This already happens when installing remote packages, so the change should be relatively minor.

Related to https://github.com/dotnet/cli/issues/5644

**Comment by mlorbetske** [comment]
@rohit21agrawal @livarcocc

**Comment by rohit21agrawal** [comment]
so what leads to two different builds of CLI having the same build number?

**Comment by mlorbetske** [comment]
@rohit21agrawal building from source multiple times

**Comment by rohit21agrawal** [comment]
any ETA on when this is fixed?

**Comment by mlorbetske** [comment]
@rohit21agrawal the fix has been made but it needs to get pulled into CLI - for which we'll need ship room approval. I'm working to see if we can get an updated engine build in yet, so no ETA, but working on it.

**Comment by rohit21agrawal** [comment]
was this pulled into CLI for RTM?

**Comment by mlorbetske** [comment]
No, it will be pulled in to the master branch of CLI soon though. I'll close this issue when it is.

**Comment by mlorbetske** [comment]
Fixed by https://github.com/dotnet/cli/pull/6168
