### ISSUE TITLE
Move tools projects to tools folder under the main solution

### ISSUE THREAD

**Issue by bekir-ozturk** [dotnet/templating#2956]
All tools should be non-shipping by default.
An individual project can be set to ship via MSBuild properties in the corresponding .csproj file, ideally using the same properties we use with arcade (`IsShipping`, `IsShippingAssembly`, `IsShippingPackage` etc.).

**Comment by vlada-shubina** [comment]
I was thinking about templates problems and versioning: in theory it should be possible to make versioning for internal tools different from src cadence. Should we explore that? It think it would be useful for TemplateDiscovery tool.

**Comment by vlada-shubina** [comment]
done
