### ISSUE TITLE
Add alias for language names

### ISSUE THREAD

**Issue by enricosada** [dotnet/templating#296]
The old `dotnet new` supported alias for language names in `--lang` argument.

So `--lang f#` or `--lang fsharp` or `--lang fs` was the same.

Use `-lang c#` or `-lang f#` can be annoying with docs (because of hash, is a sort of special char), so having an alias can be really nice.

Also personally (as a a statistically relevant sample size) i used more `-lang fs` or `-lang fsharp`

If is ok, just approve it as `up-for-grab`, so we can send a PR. 

Is a small change, just normalizing arg `fsharp` or `fs` as `f#`. same for c#.

/cc @dsyme

**Comment by dsyme** [comment]
Yes, the use of ``#`` will cause havoc in bash scripting, where ``#`` is a comment, isn't it?

**Comment by sitepodmatt** [comment]
@dsyme I think # in bash requires a boundary such as a space-before or new-line to be interpreted as a comment so this should work okay, but regardless restoring aliases would make more sense than stepping on the edge of shells..

**Comment by mlorbetske** [comment]
@enricosada we're actually working on something that would enable this right now :)

**Comment by sayedihashimi** [comment]
+1

**Comment by sayedihashimi** [comment]
@mlorbetske is this still pending?

**Comment by mlorbetske** [comment]
Yep

**Comment by sayedihashimi** [comment]
OK. I think this is pretty important, let's chat tomorrow to sync up on this item.

**Comment by donJoseLuis** [comment]
This issue was last touched 3 years ago.  We are working on a new delivery road map.  Please reopen if this is something we want & we'll properly assess its' priority compared to other work aimed at improving the overall templating UX.
