### ISSUE TITLE
Can't install templates on linux without sudo

### ISSUE THREAD

**Issue by mastoj** [dotnet/templating#2966]
Not sure what happened, but when my dotnet version was upgraded to 5.0.201 installing templates stopped working unless I do `sudo dotnet new -i ..`. The command doesn't fails, it just doesn't install the template I want to install. Using `sudo ` will install the template, but it will only be available if I use `sudo` to create the project with the template after.

Not sure what to do here.

Some info about my machine:

```
➜ dotnet --list-sdks
3.1.407 [/usr/share/dotnet/sdk]
5.0.201 [/usr/share/dotnet/sdk]

➜  dotnet --version       
5.0.201

➜  cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```

**Comment by mastoj** [comment]
I've tried to remove everything dotnet related and make a fresh install, that didn't help.

**Comment by mastoj** [comment]
I do think it stopped working between 5.0.103 and 5.0.201.

**Comment by DavidKarlas** [comment]
Hi, thank you for reporting this issue. I have few questions:
1) Can you check permissions on `~/.templateengine` and its subfolders?
2) Also, is there any exception when it fails?
3) Can you remove `~/.templateengine` and see if that fixes it?

**Comment by mastoj** [comment]
Sure.

1. Access rights looks good, 775 on the folders and subfolder
2. No exception

Harder to answer 3. I did try a lot of things yesterday trying to fix it and have now installed dotnet using snap to get it somewhat working.

What happens now when I install dotnet following the steps here https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2010- (I'm running pop os which is based on ubuntu 20.10) the package says that it is installed, but the executable isn't added. The dotnet executable should be in the folder /usr/share/dotnet, but there I only find the sdk and templates folder. So not sure what is going on.

**Comment by DavidKarlas** [comment]
Did you manage to get `dotnet` back to working? If you did and you still can't install without using `sudo` can you try adding `--trace:install` to command arguments, which will produce richer output and give us clue into why it can't install.

Thank you!

**Comment by mastoj** [comment]
@DavidKarlas, I took a drastic approach and installed the OS :laughing: I was planning to do so soon anyhow, so not a big deal. I'm pretty sure the issues was caused by something I had done unintentionally.
