### ISSUE TITLE
Suggestion: SDK-aware Generator

### ISSUE THREAD

**Issue by rcollina** [dotnet/templating#2974]
Hello,
I have been asked to share the following here as a suggestion / feature request.

Scenario: a generator that determines the TargetFramework property of an MSBuild project.

The generator should look for the closest global.json in the filesystem hierarchy with respect to the generated project path.

If no global.json is found, the value could be derived either from the lowest or highest sdk version installed in the user’s system. Fallback mode should be configurable.

It should be possible to further constrain the template’s lowest and highest supported sdk version, resolution strategy notwithstanding. Possibly error out of the project generation too, if no supported SDK has been found.

Ideally the generator could output either a TargetFramework or a configurable combination of the SDK version components (major, minor, feature band).

The latter could be used for conditional includes or further variable generation.

**Comment by KathleenDollard** [comment]
@rcollina Can you give some context here? I'm afraid I do not understand what you are trying to do.

You currently get the TFM for the SDK you are currently running. We made and then reversed a decision in 5.0 about whether we should use the highest LTS (3.1) instead. 

All versions of the SDK build all versions of the runtime. Therefore, it isn't logical to pick a TFM based on the SDK. You should always run the latest SDK as the simplest way to ensure you are on a supported/serviced SDK.

**Comment by rcollina** [comment]
Hello @KathleenDollard, thank you kindly for your reply.

> All versions of the SDK build all versions of the runtime. Therefore, it isn't logical to pick a TFM based on the SDK. You should always run the latest SDK as the simplest way to ensure you are on a supported/serviced SDK.

Makes total sense, and thank you for the clarification. Not sure how I missed this, but I guess the whole .NET Standard, Core. unified .NET story must have led to this mix-up.

I believe I've been misusing the global.json as a means to enforce and define the TFM in a roundabout way.
I think there's still some value in providing a minimum SDK version? (rollForward set to latestMajor, maybe allowPrerelease set to false). 

Thanks again for the invaluable feedback.
