### ISSUE TITLE
Support .yaml for SpecialCustomOperations.

### ISSUE THREAD

**Issue by jeffrey-vang** [dotnet/templating#2982]
Would it be possible to add `**/*.yaml` to this list?

https://github.com/dotnet/templating/blob/5b5eb6278bd745149a57d0882d655b29d02c70f4/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/SimpleConfigModel.cs#L389-L464

**Comment by DavidKarlas** [comment]
Hi, as temporary workaround you can add this information to your own template.json file like this:
https://github.com/Dotnet-Boxed/Templates/blob/4af76bca8c62137add058a4900e47333f3453572/Source/NuGetTemplate/.template.config/template.json#L474-L507

We plan to add documentation on this: https://github.com/dotnet/templating/issues/2516

And there is already existing issue for adding more formats at https://github.com/dotnet/templating/issues/282 including .yaml
