### ISSUE TITLE
Creating new solution using "dotnet new sln" in .NET 5.0.201 SDK has wrong/invalid solution version number

### ISSUE THREAD

**Issue by eriawan** [dotnet/templating#2992]
## Problem

When we create new solution using "dotnet new sln" in .NET 5.0.201 SDK has wrong/invalid solution version number in the `VisualStudioVersion`. This version is invalid, because there's no Visual Studio solution has higher version than "16.6.*.*" at this moment (at least in observed 16.9.x)

Reason: this version cannot be used to enforce minimum version of Visual Studio to open. 

## Steps to reproduce

The steps are:

1. Create new solution using `dotnet new sln`. Example: `dotnet new sln -n SolutionNET5`
2. Open the solution file in notepad other text editor
3. The version of the VisualStudioVersion is `16.6.30114.105`
4. Update the MinimumVisualStudioVersion to be the same as VisualStudioVersion
5. Open the solution in Visual Studio 2019 16.9.x (error happened in 16.9.0, 16.9.1, 16.9.2)

Full contents after `dotnet new sln` is:
```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 16
VisualStudioVersion = 16.6.30114.105
MinimumVisualStudioVersion = 10.0.40219.1
Global
        GlobalSection(SolutionConfigurationPlatforms) = preSolution
                Debug|Any CPU = Debug|Any CPU
                Debug|x64 = Debug|x64
                Debug|x86 = Debug|x86
                Release|Any CPU = Release|Any CPU
                Release|x64 = Release|x64
                Release|x86 = Release|x86
        EndGlobalSection
        GlobalSection(SolutionProperties) = preSolution
                HideSolutionNode = FALSE
        EndGlobalSection
EndGlobal
```

The error after I update the MinimumVisualStudioVersion value to `16.6.30114.105` is:

![image](https://user-images.githubusercontent.com/8773147/112659681-2fe1fa00-8e87-11eb-9d73-92807ec183ba.png)

If I use .NET Core 3.1.406 SDK to create new solution, I have this:

```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 15
VisualStudioVersion = 15.0.26124.0
MinimumVisualStudioVersion = 15.0.26124.0
Global
        GlobalSection(SolutionConfigurationPlatforms) = preSolution
                Debug|Any CPU = Debug|Any CPU
                Debug|x64 = Debug|x64
                Debug|x86 = Debug|x86
                Release|Any CPU = Release|Any CPU
                Release|x64 = Release|x64
                Release|x86 = Release|x86
        EndGlobalSection
        GlobalSection(SolutionProperties) = preSolution
                HideSolutionNode = FALSE
        EndGlobalSection
EndGlobal
```

And this file can always be opened by Visual Studio 16.8.x to 16.9.x without any error, as the `MinimumVisualStudioVersion ` is still valid solution version.

If I use VS 2019 16.9.2 to create new blank solution, I get this:

```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 16
VisualStudioVersion = 16.0.31112.23
MinimumVisualStudioVersion = 10.0.40219.1
Global
        GlobalSection(SolutionProperties) = preSolution
                HideSolutionNode = FALSE
        EndGlobalSection
        GlobalSection(ExtensibilityGlobals) = postSolution
                SolutionGuid = {195F37AF-9751-4154-9434-59DB85FFDC3F}
        EndGlobalSection
EndGlobal
```

Update that file by setting MinimumVisualStudioVersion to `16.0.31112.23`, like below:. 

```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 16
VisualStudioVersion = 16.0.31112.23
MinimumVisualStudioVersion = 16.0.31112.23
Global
        GlobalSection(SolutionProperties) = preSolution
                HideSolutionNode = FALSE
        EndGlobalSection
        GlobalSection(ExtensibilityGlobals) = postSolution
                SolutionGuid = {195F37AF-9751-4154-9434-59DB85FFDC3F}
        EndGlobalSection
EndGlobal
```

Open this file in Visual Studio, and it will open nicely!

Notice the `VisualStudioVersion` generated by 16.9.2. It is versioned as `16.0.31112.23`, so VS will not see the version generated by .NET Core 5.0.201 SDK as valid version, because version `16.6.30114.105` is definitely **_higher_** than the current generated version of 16.9,2. 

## Suggestion

Please fix this solution creation version in .NET 5.0.201 SDK!

**Comment by marcpopMSFT** [comment]
The minor version number should always be specified as zero in the solution file.  The correct value for 16.6 for example would be 16.0.30114.105 which is the build number of 16.6.0 per the shipready internal tool. Moving to templating repo so they are aware of this requirement.  Additionally, I'm not sure what the VS version affects and if it should ever be updated (as I think it's just informational and only minimum is used) and the minimum version should be left at 10.0....

**Comment by eriawan** [comment]
@marcpopMSFT 

Many thanks for transferring this issue to dotnet/templating! 

About this:

> I'm not sure what the VS version affects and if it should ever be updated (as I think it's just informational and only minimum is used) and the minimum version should be left at 10.0....

Yes, I agree in most common situations or conditions, because we having at least v10.0.xxxx.xxx means we have broadest possible compatibility, especially with older version of project model and older .NET Framework projects, such as WPF/WinForms  created in VS 2019 that target .NET Framework 4.0 can be opened in VS 2010 as well.

My team and my customers used to have `MinimumVisualStudioVersion` set from the value of `VisualStudioVersion` because we know that all of our projects are targeted to both .NET Core 3.0 and above and .NET Framework v4.7. 
Therefore my team will always have our own `MinimumVisualStudioVersion` to _**ensure that all members of our team are having the same minimum Visual Studio IDE version to support our current .NET Core development target**_. 
Since my team has agreed to use minimum VS IDE to use for .NET Core, especially right now we use 3.1.401 SDK, then we always get this advantage: we we always avoid incompatibility problems that we might have if all of our team members don't have the base minimum version to support our current target .NET Core SDK such as 3.1.401.

Example:
In the current matrix of 3.1.401 SDK, minimum VS IDE version is 16.7:

![image](https://user-images.githubusercontent.com/8773147/114090296-71d85a80-98e1-11eb-8d29-cc5d6481c42f.png)

So we will base our minimum solution version to generated solution from VS 2019 16.7. We could base on using 3.1.107,that require 16.4, but we consider the fact that VS 2019 support baseline for 16.4 support will end on this October 2021, like in this table below, so we have decided that we won't use VS 2019 16.4.x anymore.

![image](https://user-images.githubusercontent.com/8773147/114091034-5ae63800-98e2-11eb-95a9-5ae2bad32785.png)

To ease having minimum VS 2019 that in sync with longer baseline support, we decide to use solution generated from VS 2019 16.7.1 to be used as `MinimumVisualStudioVersion`. If our developers want to upgrade their own VS to latest VS such as 2019 16.9.3, we simply allow them. 

So we then think (after having those considerations) simply: for the case/condition that we know all of our projects in the solution targeted to  .NET Core 3.1.x and .NET Framework v4.7, then we can ignore older version of VS and we will always have `MinimumVisualStudioVersion` enforced for our development workflow for all of team members and our customers as well.

about this:
> (as I think it's just informational and only minimum is used) and the minimum version should be left at 10.0....

I agree totally. I'm not against that at all. Again, apologize if I may sound harsh or stupidly stubborn, I only want to emphasize that my team has specific needs based on the behavior and the requirement to enforce minimum VS version to be used across all team members.

Also in my team's pragmatic perspective: it would be strange and problematic for my team, let's say if we keep the `MinimumVisualStudioVersion` to be the version that comes with VS 2010 but if the some or all of the projects inside the solution targeted to .NET Core 3.0 or later. We already tried this before and the projects will not be able to be compiled at all when it's opened in VS 2010.
Feel free to correct me on this point, @marcpopMSFT 🙏 

Ok, could I submit a PR to update the `VisualStudioVersion` to use version `15.0.26124.0` as this is the version used by creating solution from .NET Core 3.1.406 SDK?

**Comment by eriawan** [comment]
@marcpopMSFT 

About this:
> The minor version number should always be specified as zero in the solution file. The correct value for 16.6 for example would be 16.0.30114.105 which is the build number of 16.6.0 per the shipready internal tool. 

I think we may agree on one point: the version in the solution is incorrect.
Therefore, to fix this problem I have just submitted a PR #3007 to revert back to valid solution version number for `release/5.0.2xx` branch. I also strongly suggest that any changes to `VisualStudioVersion` and  `MinimumVisualStudioVersion` must follow these rules:

1. Obey current versioning schema of VS 2019: using pattern of `16.0.xxx.xxx`
2. The version number for both `VisualStudioVersion` and  `MinimumVisualStudioVersion` must not be higher than the current VS 2019 latest RTM version. E.g. today the latest version is 16.9.3, therefore these `VisualStudioVersion` and  `MinimumVisualStudioVersion` must not be higher than the solution version as generated by 16.9.3.

Feel free to correct me and I welcome feedback 🙂
