### ISSUE TITLE
CLI - Item template for creating a new class

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet/templating#3008]
Today, there is no way to create a new class file from the command line. For net new developers this is something that they would be doing very often. 

Spec:

```
dotnet new class -n MyClass -na MyApp.Namespace
```

Ideally, it would automatically be able to figure out the namespace for you so you wouldn't need to do it based on your csproject and the folder that you are in..

So if you are in:  MyApp/Models and did `dotnet new class -n MyClass` 

the following would be generated:

```csharp
using System;
using System.Collections.Generic;
using System.Text;

namespace MyApp.Models
{
    class MyClass
    {
    }
}
```

**Comment by bozturkMSFT** [comment]
@KathleenDollard

**Comment by KathleenDollard** [comment]
This came up when we were talking about templates. We should do this, but probably after the new parser so we can have a conversation about handling the name for item templates #3009.

And let's review the template VS uses and at least add "public" and review the using statements.

**Comment by bozturkMSFT** [comment]
@KathleenDollard  What version should we aim for this? .NET 6, .NET 7?

**Comment by DavidKarlas** [comment]
Do we need new generator that will figure out correct namespace to be used(if user doesn't specify) based on .csproj content and folders?(using same rules as VS)

**Comment by bekir-ozturk** [comment]
There is an older issue, so we are closing this one in favor of the other. Please track here: #1713
