### ISSUE TITLE
-all is confusing as the force parameter

### ISSUE THREAD

**Issue by billwert** [dotnet/templating#301]
While working on another bug I tried to run `dotnet new webconfig` in an empty directory and got this message:
```
  - [Web Config] is an item template. By default it's only created in a target location containing a project. Force creation with the -all flag.
```

Given that -all is also a shortcut for showing all templates reusing it here is confusing. Why not -force?

**Comment by mlorbetske** [comment]
`force` is a bit of different concept. #300 adds a `--force` flag that deals with agreeing to changes to existing files. The `all` flag deals with determining the context in which searching for the template to use should be done.

This is pretty deeply related to #302 where the switch in context between project type things and item type things isn't very clear - perhaps this could be solved with a new switch like `--show` where the behavior would be something like:

+ Everything would be shown by default (`--show all`)
+ If looking for project templates, you can filter to that (`--show project`)
+ If looking for item templates, you can filter to that (`--show item`)

With this change, `web.config` wouldn't be created by typing `dotnet new web` unless specifically looking in the set of item templates. It would, however, try to make the empty web template but this would be picked off by the new overwrite behavior & indicate that `--force` must be passed to create the template.

Thoughts?

cc @sayedihashimi

**Comment by mlorbetske** [comment]
Maybe `--search` would be better than `--show` as well

**Comment by billwert** [comment]
Right. So with #302, the existing message, `Force creation with the -all flag.`, would be come `Force creation with the --force flag.`?

It's very confusing to me that the search/show (I'll just use show, I think that's preferable) options take this form:
`dotnet new <templatename> --show`. 

This, of course, doesn't work right now.
```
PS D:\work\scratch\test11>D:\work\dotnets\1.0.0-rc4-004777\dotnet.exe new -l -all con
Value specified for valueless parameter: --show-all
   at Microsoft.TemplateEngine.Cli.ExtendedCommandParser.ParseArgs(IList`1 extraArgFileNames)
   at Microsoft.TemplateEngine.Cli.New3Command.<ExecuteAsync>d__66.MoveNext()
PS D:\work\scratch\test11>D:\work\dotnets\1.0.0-rc4-004777\dotnet.exe new -all -l con
Value specified for valueless parameter: --list
   at Microsoft.TemplateEngine.Cli.ExtendedCommandParser.ParseArgs(IList`1 extraArgFileNames)
   at Microsoft.TemplateEngine.Cli.New3Command.<ExecuteAsync>d__66.MoveNext()
```

The help says, in part:
```
Usage: dotnet new [arguments] [options]

Arguments:
  template  The template to instantiate.
```

If I am still trying to figure out what I want to actually make by asking the tool questions, it's not intuitive to me that I should specify some substring to the template argument. I don't want to instantiate anything yet; I want to know what my choices are.

IMO, the form `dotnet new <template>` should be reserved for actually doing something. `--force`, `--name`, `--ouptut`, and the like are reasonable modifiers for that. `--show` in that context is confusing.

I'd also say that in the case I've installed several templates and have a conflict of short names, the tooling should bail and require me to pass the full template name. (You could imagine I install some third party templates that collide.)

**Comment by mlorbetske** [comment]
@billwert the thing that you just ran in to is from not specifying the argument first (getting a better experience for this was the focus of #257). My proposal takes away the need for `-all`, by showing you everything by default (as the context switching is not currently intuitive) but allowing you to filter a query for templates (generally to be used in combination with `-l|--list`).

**Comment by mlorbetske** [comment]
Implicit context switching has been removed for the next release after RTW and the default behavior will be to show and allow the creation of any template rather than just the ones in the detected "context"
