### ISSUE TITLE
Short name partial matching for templates leads to confusion

### ISSUE THREAD

**Issue by billwert** [dotnet/templating#302]
Copied from dotnet/cli#5651 and retitled since I now understand the issue a bit better.

Consider:
```
PS D:\work\scratch\test9>D:\work\dotnets\1.0.0-rc4-004777\dotnet.exe new web
Content generation time: 67.3824 ms
The template "Empty ASP.NET Core Web Application" created successfully.
PS D:\work\scratch\test9>dir


    Directory: D:\work\scratch\test9


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        2/10/2017  10:24 AM                wwwroot
-a----        2/10/2017  10:24 AM            544 Program.cs
-a----        2/10/2017  10:24 AM           1188 Startup.cs
-a----        2/10/2017  10:24 AM            307 test9.csproj


PS D:\work\scratch\test9>D:\work\dotnets\1.0.0-rc4-004777\dotnet.exe new web
Content generation time: 18.6667 ms
The template "Web Config" created successfully.
```
And highlights of the output from dotnet new -all:
```
Templates                                 Short Name       Language      Tags
---------------------------------------------------------------------------------------
Empty ASP.NET Core Web Application        web              [C#]          Web/Empty
Web Config                                webconfig                      Config
```
It is incredibly confusing that in this instance, an already reserved short name for a template is partially matched to another template when the first template fails.

I'd much rather see this just fail in this instance. These names are incredibly short; perhaps partial match isn't worth it here?

**Comment by mlorbetske** [comment]
cc @sayedihashimi

**Comment by sayedihashimi** [comment]
We are considering disabling the partial name matching.

**Comment by mlorbetske** [comment]
Implicit context switching has been removed for the next release after RTW - so the behavior for any supplied name will be consistent

**Comment by billwert** [comment]
@mlorbetske thanks! does this mean that short names will no longer collide either?

**Comment by mlorbetske** [comment]
Yep, doing the same thing twice in the same directory won't change the template (ex. Webconfig will never be picked in a context you'd expect web for empty web to be the one)
