### ISSUE TITLE
dotnet new --language IL support

### ISSUE THREAD

**Issue by am11** [dotnet/templating#3021]
Since Microsoft.NET.SDK.IL is officially released as part of .NET Runtime, it would be nice to include ilproj support.

Current behavior:

```sh
$ dotnet new console --language IL
Couldn't find an installed template that matches the input, searching online for one that does...
No templates found matching: 'console', language='IL'.
1 template(s) partially matched, but failed on language='IL'.
```

**Comment by KathleenDollard** [comment]
@am11 Can you explain the scenario where this is important. The IL is created from the Roslyn compiler and changes as we improve the processes, so I am hesitant to hard code something into a template that we could not keep in sync with what you'd get from a template. 

For Console this might not be relevant, but I think we should understand the scenario prior to creating such a template.

**Comment by am11** [comment]
The IL SDK is relatively a new addition (since .NET Core 3.0?) that wraps CoreCLR's cross-platform implementation of ilasm and allows us to build [`.ilproj` projects](https://github.com/search?q=extension:ilproj+project). Such projects are typically used to write (mainly performance-oriented) code constructs that are allowed in CIL by ECMA 335, but not possible with C#, F# or VB. Other projects in our solution (such as `.csproj`) can reference an ilproj using `<PackageReference>` mechanism.

Prior to IL SDK, developers used to write custom msbuild tasks to compile IL code using ilasm.exe. Since the IL SDK has been built with same release cycle as .NET Runtime, I think it would be a good addition to add IL in list of languages of tooling so users can create IL projects with the familiar command line interface.

I agree that console template is not interesting, and that we can scope the template to classlib.

**Comment by baronfel** [comment]
This SDK was added by the runtime team, so we should consult with them on what a minimal classlib ilproj would look like, then add it subject to team availability/other contributor interest..

**Comment by baronfel** [comment]
oh hey, @am11 I didn't realize you were a domain expert here. Do you have a sample IL classlib-style project that could be used as a base for a template? If so we could help you polish that up and get it added to the default templates shipped with the SDK.

**Comment by YuliiaKovalova** [comment]
Close due to lack of feedback.
