### ISSUE TITLE
dotnet new -i should not list every template

### ISSUE THREAD

**Issue by halter73** [dotnet/templating#3048]
`dotnet new --install` currently lists every template after a successful installation. This makes users think the command has failed. We recently did a user study for ASP.NET Core based on [this tutorial](https://github.com/halter73/tutorial#create-a-new-project). 

![template](https://user-images.githubusercontent.com/2546640/112074057-c04cd180-8b4b-11eb-8aee-4dc2e0fc344a.gif)

Despite including this gif in the user study tutorial to show what successful installation of a template looks like, *multiple* users thought installation had failed because there was so much output. It looked like some sort of help text and it wasn't easy to find the newly installed template in such a long list.

**Comment by DavidKarlas** [comment]
Hi,

this is exactly what we have done in latest `main` build which will be released as .NET 6 preview 4.
This is how output looks like:
![image](https://user-images.githubusercontent.com/774791/114932859-4b15a900-9e38-11eb-9c2c-291782b7ffae.png)

**Comment by vlada-shubina** [comment]
Duplicate issue: https://github.com/dotnet/templating/issues/2562

**Comment by vlada-shubina** [comment]
I'm closing this issue, as it is already implemented. Please feel free to reopen if the functionality of main/preview 4 is not what's expected. Thanks.
