### ISSUE TITLE
Replace character in sourceName

### ISSUE THREAD

**Issue by TheDiggster13** [dotnet/templating#3068]
Hi, I have a situation where I don't want to allow any hyphens in source names. Is there a way to replace these automatically with underscores at the time of initialising the template?

**Comment by DavidKarlas** [comment]
On symbols you can use `forms`, here are few examples: https://github.com/dotnet/templating/wiki/Runnable-Project-Templates---Value-Forms

**Comment by DavidKarlas** [comment]
Here is also small example on how to use forms:
https://github.com/dotnet/templating/blob/main/test/Microsoft.TemplateEngine.TestTemplates/test_templates/TemplateWithDerivedSymbolFileRename/.template.config/template.json

**Comment by TheDiggster13** [comment]
That's awesome, thank you
