### ISSUE TITLE
With .net6 preview4 SDK installed,  dotnet restore could not run automatically when creating project in CLI.

### ISSUE THREAD

**Issue by dandanmu** [dotnet/templating#3084]
Repro steps: 
1. Download and install NET6 preview 4 SDK--6.0.100-preview.4.21215.12(runtime-6.0.0-preview.4.21213.9)- from https://github.com/dotnet/installer
2. dotnet new console in CLI 

Expected Result: 
Create and restore  successfully. 

Actual Result:
dotnet restore could not run automatically , need to run by manual. 
![image](https://user-images.githubusercontent.com/65638819/114992486-641c6980-9ecd-11eb-8cdb-af0e8afdf5a7.png)
In net6 preview 3, It shows as below 
![image](https://user-images.githubusercontent.com/65638819/114997174-2706a600-9ed2-11eb-94bc-a29e4427df4a.png)

**Comment by DavidKarlas** [comment]
Thank you for using and reporting bugs on preview releases!
This bug is fixed via https://github.com/dotnet/templating/pull/3043 in latest Preview4.

Thank you!
