### ISSUE TITLE
--update-apply rolls back templates that are in beta

### ISSUE THREAD

**Issue by isaacabraham** [dotnet/templating#3109]
I have a beta version of a dotnet template installed on my machine. I ran the `dotnet -new --update-apply` command and found that it replaced it with an *older* version - the latest *non-beta* version but an older version nonetheless than what was previously installed.

This is not the behaviour I would expect - if you have a newer beta version of a template, `--update-apply` should simply do nothing.

**Comment by vlada-shubina** [comment]
@isaacabraham could you please specify the version you are running (output of `dotnet --info`)? Thanks

**Comment by isaacabraham** [comment]
Hi. 5.0.202
