### ISSUE TITLE
GuidMacro `defaultFormat` doesn't respect casing format

### ISSUE THREAD

**Issue by DavidKarlas** [dotnet/templating#3128]
GuidMacro is respecting lower vs upper format "D" vs "d"... But this does not happen for "defaultFormat"... This needs fixing...

Temporary workaround:
```
  "symbols":{
    "my-guid": {
      "type": "generated",
      "generator": "guid",
      "parameters": {
        "defaultFormat": "d"
      }
    },
    "id01": {
      "type": "generated",
      "generator": "casing",
      "replaces": "myid01",
      "parameters": {
        "source": "my-guid",
        "toLower": false
      }
    }
  }
```

Fix will be changing https://github.com/dotnet/templating/blob/7e14ef44/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/Macros/GuidMacro.cs#L73-L74 to be like https://github.com/dotnet/templating/blob/7e14ef44/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/Macros/GuidMacro.cs#L42

Consider extracting this formating that respects upper/lower case into `Guid` method extension...

**Comment by DavidKarlas** [comment]
Another workaround would also be using "guids" feature, see https://github.com/dotnet/templating/wiki/Runnable-Project-Templates#guids-optional and https://github.com/dotnet/dotnet-template-samples/blob/master/14-guid/MyProject.Con/.template.config/template.json#L15-L18 that might be easier workaround.

**Comment by vijaya-lakshmi-venkatraman** [comment]
Hi David,
Is the change required as below: 
```
string value = char.IsUpper(config.DefaultFormat[i]) ? g.ToString(config.DefaultFormat[i].ToString()).ToUpperInvariant() : g.ToString(config.DefaultFormat[i].ToString()).ToLowerInvariant();
vars[config.VariableName] = value;
setter(pd, value);
```

**Comment by DavidKarlas** [comment]
Yes, except it would be just `config.DefaultFormat` without `[i]`.
Unit test for this will be in this file: https://github.com/dotnet/templating/blob/main/test/Microsoft.TemplateEngine.Orchestrator.RunnableProjects.UnitTests/MacroTests/GuidMacroTests.cs

**Comment by vijaya-lakshmi-venkatraman** [comment]
Thanks,
I will try the changes and submit for your review
