### ISSUE TITLE
[Localization] Assistance with translations

### ISSUE THREAD

**Issue by cristianosuzuki77** [dotnet/templating#3136]
Three questions:
1.Please clarify what replaces the placeholder in this string: "Success: {0} installed the following templates:"
Is it NuGet Package Manager, Package Manager Console, or something else? The RID contains 'TemplatesPackageCoordinator' but when I loaded all strings containing it into Fabric, I couldn't figure out the actor in this string.
File: src/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.xlf

2. Please clarify the placeholders of this string. There is no dev comment to explain them. The first one is most likely a number, but is the second one a template name or something else?

String:"{0} template(s) partially matched, but failed on {1}."
File: src/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.xlf

3. Please clarify if 'Change' is used as a verb or a noun here. There is no dev comment to explain it, and nothing in the RID gives a hint about it.
String: "Due to the ambiguity, this string needs to be sent for a string review."
File: src/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.xlf

Note: For your reference, for all strings with placeholders, please include in the comments of the xlf file what the placeholders will be replaced with and an example if possible

**Comment by bozturkMSFT** [comment]
Hi @cristianosuzuki77 
1. Can we replace the English string with the following:
```
Package "{0}" containing the following templates was installed successfully:
```
where {0} is a package name such as "Microsoft.DotNet.Web.Spa.ProjectTemplates".

2. {1} in this case represents a list of comma separated "filters" such as "language=C#, author=Microsoft" or "type=project". 

The app is searching for templates in a database based on the criteria the user specified (filters). If no templates were found, the app tries to figure out what templates would we be able to find if user loosened up the criteria a bit. For instance

- User searches for the term "function" and also uses language=C# to only get C# results.
- No templates are found. However, there is one "Azure.Functions" template that is for Visual Basic.
- We print "1 template(s) partially matched, but failed on language=C#."

Would the following be better? Feel free to update it.
```
{0} template(s) partially matched the search criteria, but they failed on the following filter(s) "{1}".
```

3. "Change" here is a verb here. Other verbs in the same "group" are "Delete", "Overwrite", "UnknownChangeKind". This string is informing users about what will happen to their files on disk. A sample output message containing these words would look like this:

```
Creating this template will make changes to existing files:
    Delete    someFile.png
    Change    some-other-file.txt
    Overwrite console.csproj
```

 I believe a more appropriate term for "Change" here would be "Modify".

----------------------

We will better keep an eye on such cases in the future. Sorry for the inconvenience.

@vlada-shubina @DavidKarlas can one of you confirm the above explanations?

**Comment by cristianosuzuki77** [comment]
Thank you @bozturkMSFT I forwarded the explanations to the translators.
