### ISSUE TITLE
Add postActions support for "npm install" and "webpack"

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/templating#317]
Hey, the new `postActions` concept looks good.

For the SPA templates I'm building (and in general, for any typical web application that contains client-side code), after generating the project, developers currently have to run the following commands manually so their application can run:

    npm install
    webpack
    webpack --config webpack.config.vendor.js

As you can imagine, developers may well forget to do this (even if there's a "manual instruction" telling them to do so). It would be great if we could automate it.

Can I suggest adding the following post-action processors?

 * `NpmInstallPostActionProcessor` - would be exactly like `DotnetRestorePostActionProcessor` except it invokes `npm install` instead of `dotnet restore`. It wouldn't need to take any parameters, at least for the scenarios I have in mind, since NPM is all configured inside your `package.json` file.
 * `WebpackPostActionProcessor`, which would take an optional `string[]` parameter called `configFiles`.
     * If `configFiles` is not set, then execute `webpack` with no args
     * Otherwise, run Webpack with each specific config file, i.e.: `foreach(var configFile in configFiles) { invoke("webpack --config " + configFile); }`

This would take care of the requirements of a large range of SPA-type projects.

Alternatively, if you want to be more generalised still, you could forget about `WebpackPostActionProcessor` and instead implement `NpmRunPostActionProcessor`, which takes a `string[]` parameter called `taskNames`, and then does: `foreach(var taskName in taskNames) { invoke("npm run " + taskName) }`. That would let developers invoke the tasks they declared in the project's `package.json` file, which is often used for all kinds of front-end project config stuff, such as package restoration and compilation, via Webpack or any other JS build system.

**Comment by peterblazejewicz** [comment]
`WebpackPostActionProcessor`, `NpmRunPostActionProcessor`
Just a note, there are `rollup` (http://rollupjs.org/)  or `yarn` (https://yarnpkg.com/) out there and others, so I would not use a tool specific naming
Discussed here: https://github.com/dotnet/cli/issues/5443

**Comment by mlorbetske** [comment]
Blanket support for this via #433. Docs are (here)[https://github.com/dotnet/templating/wiki/Post-Action-Registry#run-script].

Do you think it would still be a good idea to tool these specifically (to give a more tailored experience for the tools that are ultimately called)?

**Comment by mlorbetske** [comment]
Closing this as the generic support is there
