### ISSUE TITLE
"dll" could be an alias for "classlib"

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/templating#318]
I wanted to create a new project, but forgot the name `classlib`. I tried my best guess `dotnet new dll`.

## Expected  behavior
A new project, exactly as if I had typed the formal name `classlib`.

## Actual behavior
```
No templates matched the input template name: [dll]
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771
```

**Comment by mlorbetske** [comment]
@sayedihashimi thoughts on supporting multiple names for templates out of the box?

**Comment by sayedihashimi** [comment]
I think this is an interesting concept but I'm worried that it may cause confusion when we have a bunch of templates authored by the community. What do we do in the case of a conflict on alias?

**Comment by dasMulli** [comment]
tbh it think that `dll` is a bit confusing in the new ecosystem since the primary output of all .net core application types is now a `dll` file.

**Comment by sayedihashimi** [comment]
Also if I'm used to `dotnet new classlib` and then I see my colleague run `dotnet new dll` is it obvious those two are the same thing? Does it need to be?

**Comment by sayedihashimi** [comment]
We are not going to be making this change. I'd rather avoid confusion by adding this. If the suggestion continues to come up and have broad community support we can revisit. Closing for now.
