### ISSUE TITLE
[CLI] review exit codes sent via New3CommandResult enum

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#3186]
Since a while we were using `CreationResultStatus` as the exit code, which was limited only to errors on template creation. Now we have different enum: `New3CommandResult` which we can modify and add new statuses.
- review existing exit codes and create new codes where needed
- review sending hex as exit code - it is not supported in Unix, where exit code is limited to 8-bit integer.

**Comment by vlada-shubina** [comment]
@baronfel let's discuss this issue at one of the next meetings, particularly using hex COM codes.  

We recently got https://github.com/dotnet/templating/issues/4253 on one of the code being incorrect, however it's might be a good time to change others at the same time / release.

**Comment by baronfel** [comment]
We should move to portable exit codes and document it as a breaking change for .NET 7.

**Comment by JanKrivanek** [comment]
Repositories to be touched:
- [x] dotnet/templating PR: https://github.com/dotnet/templating/pull/4787
- [ ] dotnet/sdk - Inject the help link for [the 127 error code](https://github.com/dotnet/sdk/blob/main/src/Cli/dotnet/Parser.cs#L148)
