### ISSUE TITLE
Combining "Run script" Post Action with sourceName

### ISSUE THREAD

**Issue by bradcavanagh-unity3d** [dotnet/templating#3220]
I would like to set up a "Run script" Post Action to execute a file that exists in a directory whose name gets substituted using the `sourceName` parameter of the template, with something like this:

```
{
  "$schema": "http://json.schemastore.org/template",
  "author": "Author.Name",
  "classifications": [ ],
  "identity": "Test.Template",
  "name": "Testing executable postAction with dynamic directory",
  "shortName": "test-dynamic-executable",
  "sourceName": "APPLICATION_NAME",
  "preferNameDirectory": false,
  "postActions": [
    {
      "actionId": "3A7C4B45-1F5D-4A30-959A-51B88E82B5D2",
      "args": {
        "executable": "sh",
        "args": "src/APPLICATION_NAME/script.sh",
        "redirectStandardOutput": "false"
      },
      "description": "Run script",
      "manualInstructions": []
    }
  ]
}
```

In other words, `APPLICATION_NAME` gets swapped out with whatever the user supplies to `-n <APPLICATION_NAME>`, so the template would create a file in `src/<APPLICATION_NAME>/script.sh` that I'd then like to execute. Unfortunately it appears that `APPLICATION_NAME` doesn't get swapped out for the post action to execute, so it actually tries to execute `src/APPLICATION_NAME/script.sh` instead of using the user-supplied directory name.

Is it currently possible to do this sort of thing? I'm currently using dotnet 5.0.203 if that matters, and can supply any additional information you require.

**Comment by vlada-shubina** [comment]
@bradcavanagh-unity3d 

Thank you for reaching us. 
Unfortunately it is not possible to use parameters (therefore `sourceName` too) in `args` of the post actions.  We already have an issue on this: https://github.com/dotnet/templating/issues/1600. For now, `args` are limited to constant values.

As a workaround, I may suggest to put the script to folder that doesn't need symbol replacement, e.g. `src/script.sh`. Inside the script, however replacements are possible so you can use relative paths as `APPLICATION_NAME/my_project.csproj` if needed, and APPLICATION_NAME will be replaced by the name user specified in `-n <APPLICATION_NAME>`. 

Let me know if it works for you or if you have further questions.
For support of parameters in `args` of the post actions, please track https://github.com/dotnet/templating/issues/1600, I'll be closing this issue as the duplicate in case of no further questions.

**Comment by bradcavanagh-unity3d** [comment]
@vlada-shubina Thank you for the workaround, I'll give that a shot. I've done similar things before so I'm confident it'll work with a little bit of reorganization of my files within the template.

Thank you also for pointing me to that other ticket. I've followed it and hopefully parameters in `args` for post actions will be supported at some point in the future!

**Comment by bradcavanagh-unity3d** [comment]
@vlada-shubina A little late but yes, I can confirm that the workaround you suggested works just fine for this purpose.
