### ISSUE TITLE
[Search cache] Create a build pipeline to automate the publishing of the old cache file format

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#3229]
Create a build pipeline to automate the publishing of the old cache file format
Pipeline to be run once in a week / two weeks.
Check if we can write to blob storage directly without need to send email

We should use the tool version in the tag: https://github.com/dotnet/templating/releases/tag/TemplateDiscovery-CacheVersion-1-0
Create a branch from that tag so that further improvements can be done on that branch. The pipeline should use the HEAD of that branch as well.

**Comment by bekir-ozturk** [comment]
This work is done. We are currently running the pipeline once every hour as an experiment, but this may change in the coming days.
The file is directly uploaded to the blob storage: no emails.
The branch containing the tool and the pipeline is: legacy/template-discovery-tool
