### ISSUE TITLE
[Search cache] Compress the cache file in the blob storage

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#3231]
- Compress the cache file in the blob storage, this should be done in the tool while generating the cache file.
- Update the engine to unzip the cache file upon download (we already have this functionality from reading nuget packages).

**Comment by vlada-shubina** [comment]
Likely to be done by CDN configuration for dedicated Azure storage account - no code change should be needed.

**Comment by bekir-ozturk** [comment]
Cache files are now compressed by CDN.
