### ISSUE TITLE
Decision on whether parsing should be case-sensitive

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#3237]
The current parser is case sensitive:   `--Nullable` and `--nullable` are different options. 
We need to decide whether to keep it so with new parser.

If we decide to keep parser case-sensitive, we should probably adopt naming symbols with small character in `template.json`, to avoid putting entry in dotnetcli.host.json just for case change, and make respective changes in the templates (for example now we have Framework, but langVersion). Alternatively, we can change the case of first letter programmatically.

----
_Originally posted by @vlada-shubina in https://github.com/dotnet/templating/pull/3173#discussion_r644701307_

**Comment by RussKie** [comment]
I find case sensitivity **on Windows** rather surprising. E.g. this caught me off-guard:
![image](https://user-images.githubusercontent.com/4403806/129835003-2df1e5ec-85fa-4b58-843e-daa3da04b882.png)

**Comment by sayedihashimi** [comment]
I found that being case sensitive was very unexpected.

**Comment by vlada-shubina** [comment]
No change to this behavior is planned in scope of #2191, keeping the issue opened for discussions.

**Comment by YuliiaKovalova** [comment]
Close with Low Priority + no major feedback has been received.
