### ISSUE TITLE
Decision on should short alias on template parameter be generated by default

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#3238]
Default behavior of current parser is to generate short alias on each template option, unless it is not mentioned in dotnetcli.host.json:
- for `--Nullable` it will be `-N`
- for `--nullable` it will be `-nu` as `-n` is already taken for `--name`

Now, if you don't want to have short name for the option, you need to put it dotnetcli.host.json with empty shortName:
```
    "Nullable": {
        "longName": "nullable",
        "shortName": ""
    }
```
which is inconvenient, and lot of Microsoft templates have to do it.

-----
_Originally posted by @vlada-shubina in https://github.com/dotnet/templating/pull/3173#discussion_r644701307_

**Comment by baronfel** [comment]
Follow-up questions for @baronfel:
* look into the template metadata (external and internal) and get counts of how many are using this syntax to provide lowercase parameter names only
* how many are using host config files at all?
* how many are using this rename for other, non-lowercase-only use cases?

In every case, we should try to solve the need expressed in the usage.

**Comment by sayedihashimi** [comment]
I have some of this info from the tools that I previously created. From the 2105 templates that I've found in nuget.org, I see that 1525 do NOT have a host file.

We can probably add some code to answer your other questions as well.

Here are the reports that I just generated, there may be some useful info for you. In our Thursday meeting I will go over how to run these tools for @baronfel.

[template-reports.zip](https://github.com/dotnet/templating/files/7628058/template-reports.zip)

**Comment by vlada-shubina** [comment]
We agreed that in scope of #2191 no change should be for this behavior.

**Comment by baronfel** [comment]
This is partially related to https://github.com/dotnet/templating/issues/3238 because the casing provided in the host configs can mess with expected results for case (in)sensitive parsing.

**Comment by baronfel** [comment]
We should not generate shortnames by default, due to the inconsistencies that Vlada has mentioned below. Template authors should have the expectation that the symbols they create are the exact representations the users will see.

**Comment by YuliiaKovalova** [comment]
We decided not to change this behavior.
