### ISSUE TITLE
Refactor selecting correct locale file for the template

### ISSUE THREAD

**Issue by bekir-ozturk** [dotnet/templating#3255]
Current localization file for a template is currently picked in `TemplateCache.cs`. This is too late for the initialization of `RunnableProjectTemplate` at  https://github.com/dotnet/templating/blob/a12ffe38aa1cda585e0b1f810a4bbd0be4596552/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/RunnableProjectGenerator.cs#L191. For this reason, we pass null while constructing the `RunnableProjectTemplate` and later clone it to inject the `localeConfigFile` property.

Change the implementation so that:
- The proper `localeConfigFile` is passed to the constructor of `RunnableProjectTemplate` above instead of null.
- Template cache doesn't decide what locale to use for each template.
- Template cache doesn't clone the templates given in the scan results.

**Comment by YuliiaKovalova** [comment]
done
