### ISSUE TITLE
Make decision on TargetFrameworkOverride parameter in templates

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#3261]
Templates have parameter `TargetFrameworkOverride` which is hidden from users. 

Decision needed whether it should be kept (and documented) or removed from all .NET templates.

**Comment by baronfel** [comment]
Internal Usage:
* dotnet/templating
* dotnet/winforms

External usage:
* 31 separate templates, notable ones are NUnit, AspNetCore.SpaTemplates, Eto.Forms, Falanx, Persimmon, and the ones listed using baselines in https://github.com/dotnet/templating/issues/4062#issuecomment-971743831

This seems much more broadly in-use than baselines, and it's often used to set a TargetFramework or conditionally include a set of package references. It seems worth keeping, but I'm not sure that it's any more special than any other symbol. Perhaps the documentation or examples about how symbols are evaluated at template instanciation could be highlighted?

**Comment by vlada-shubina** [comment]
It's more of the question whether we want to keep it in those templates:
- dotnet/templating
- dotnet/winforms

Effectively, those templates have 2 framework parameters:
- Framework - choice with restricted values (net6.0, net5.0, ...)
- TargetFrameworkOverride - text, accepts any text value (hidden)

We made a trade-off when implementing new idioms in those templates and `TargetFrameworkOverride` parameter is not considered when evaluating flavor to be used, so 2 choices here:
- we keep parameter in and implement logic to try to consider it when determining features to use in generated template
- we remove the parameter

**Comment by baronfel** [comment]
Linking https://github.com/dotnet/sdk/issues/22769 as a request for something like TargetFrameworkOverride to allow setting the TFM uniformly on templates.

**Comment by YuliiaKovalova** [comment]
We decided not to change it for now.
