### ISSUE TITLE
Adding local path (not nupkg) templates appear to overwrite each other (can only have one at a time)

### ISSUE THREAD

**Issue by JustinGrote** [dotnet/templating#3265]
If have defined three templates:
`path\to\template1`
`another\path\template2`
`third\path\template3`

Adding the first template with `dotnet new -i path\to\template1` will work fine. Adding the second subsequent template will cause the other one to disappear for some reason and now only show that template (in addition to the nupkg ones)

Demo:

https://user-images.githubusercontent.com/15258962/121405254-ab453a80-c911-11eb-9737-f89d68b510d9.mp4

**Comment by vlada-shubina** [comment]
hi @JustinGrote 

what are `groupIdentity`, `identity` and `precedence` values in your templates?
Is it possible to share the templates so I can check them?

could you also share `dotnet new -u` and `dotnet --info` output? 

thank you

**Comment by JustinGrote** [comment]
Hi @vlada-shubina,

Confirmed dupe of https://github.com/dotnet/templating/issues/649, I had duplicate groupIdentity entries and misunderstood the purpose.

**Comment by JustinGrote** [comment]
@vlada-shubina related to this, I think the schema needs to clarify what this is for better, this is not very clear. What are the "keys"? How do the "tags" influence? When does the "prompt" occur?
![image](https://user-images.githubusercontent.com/15258962/121422137-c28d2380-c923-11eb-8e72-3bae1e654a0c.png)

**Comment by vlada-shubina** [comment]
@JustinGrote 
I agree - the description looks confusing. We already have an issue to improve it (https://github.com/dotnet/templating/issues/2384), it's part of documentation improvements we are planning to do.
