### ISSUE TITLE
Revise error message on conflicting templates

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#3275]
![image](https://user-images.githubusercontent.com/56045248/121576497-1cc7da80-ca31-11eb-841b-540ace1e1b59.png)
in case there are multiple templates coming from different group with same name the error message is confusing.

Revise error message:
- if short name are same and languages are same, the CTA should be to uninstall one of the packages
- if languages are different, suggest to use --language option
- if short names are different can stay as it (though it is unlikely case after moving to exact match on short name

TODO:
 - [ ] Undo https://github.com/dotnet/templating/pull/3276

**Comment by baronfel** [comment]
This sounds reasonable to me, though this is another thing that might be helped by better validation for template authors.  Since we have the template manifest, during the Pack of a tool we could emit a warning if the desired short name would conflict with another known tool.  The idea would be to push this error to the author instead of to the template consumer.

**Comment by vlada-shubina** [comment]
The error message was fixed while migrating to new parser, the new output is below:
```
Identity                         Template Name       Short Name     Language  Author      Package
%TABLE HEADER DELIMITER%
Invalid.SameShortName.TemplateA  Invalid.SameSho...  sameshortname            Test Asset  %TEMPLATE LOCATION%
Invalid.SameShortName.TemplateB  Invalid.SameSho...  sameshortname            Test Asset  %TEMPLATE LOCATION%

Uninstall the template packages containing the templates to keep only one template from the list or add the template options which differentiate the template to run.

```

This is not yet perfect, as still there is no way to run the templates that have same name. We plan to improve this behavior in https://github.com/dotnet/templating/issues/4135.
