### ISSUE TITLE
template.json schema does not define a format property for generatorNow

### ISSUE THREAD

**Issue by Bene81** [dotnet/templating#3277]
Generator "now " defined in lines 69 to 87  of file 'src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/Schemas/JSON/template.json'
does specify a `parameters` property `action`  in lines 76 to 79.
No parameter property `format` is specified.
The parser though requires `format` and ignores `action`.

The file uploaded to `http://json.schemastore.org/template` shows the same definition.

**Comment by vlada-shubina** [comment]
Thank you for reporting, will be fixed in https://github.com/dotnet/templating/pull/3284
