### ISSUE TITLE
-h|--help missing options

### ISSUE THREAD

**Issue by spboyer** [dotnet/templating#328]
Internal options missing from `-h`|--help, commented as "hidden" but minimally `--install` is needed for adding additional templates.

`-i|--install`

`dotnet new -i [package_path] : the path to the folder containing the templates 
This is mentioned in the[ README.md ](https://github.com/dotnet/templating#installing-templates)

`--locale`
`--quiet`
`-x|--extra-args`
`--debug:attach`
`-a|--alias`
`-t|--type`

https://github.com/dotnet/templating/blob/4da0a69b70ac542a6fa87b2892147a26406b6282/src/Microsoft.TemplateEngine.Cli/New3Command.cs#L856

**Comment by spboyer** [comment]
Documenting in https://github.com/dotnet/docs/pull/1511#pullrequestreview-22059989 

Should I hold off on `--install` for now, and are the others for internal use only?

**Comment by mlorbetske** [comment]
These are intentionally not documented at this point.

`-i|--install` is still being worked on (it has some quirks) and isn't necessarily the syntax we want, but it needs to be available for authors
`-a|--alias` exists but doesn't have a complete story (you can't select an aliased template by the alias)
`-t|--type` hasn't been released yet & we're not sure if we're going to
`--quiet` is largely ignored at this point - we need to either make it be quiet or to remove the option
`--debug:attach`, `--debug:reinit` and `--debug:showconfig` are for development use only

`-x|--extra-args` could be documented, but we haven't figured out good text for it yet
`--locale` could be documented but there are no locales other than `en_US` available at this time

**Comment by spboyer** [comment]
Thanks @mlorbetske ! Helps me clear the path.
