### ISSUE TITLE
Place files in root of output

### ISSUE THREAD

**Issue by h3rmanj** [dotnet/templating#3280]
I'm creating a template where I want to include a `.gitlab-ci.yml` and `README.md`, which needs to be in the root of the output. As in, if it's a solution, I'd want them in the same folder as the `sln`, but if it's a project, I'd want it in the same folder as the `csproj`.

Right now, I have to make two separate templates, one as a solution, containing the project, and one with the project. Even then when using the solution template with Visual Studio, I have to check `Place solution in same directory as project` for the files in my solution template to be placed besides the solution. I feel like I should be able to achieve what I want with only one template though.

Would be nice with some kind of option to always place specific files in the "root" of the output. Or get to know what the user selects during the Visual Studio solution creation process, so I can do a postAction where I move the files?

**Comment by h3rmanj** [comment]
I see this is related to https://github.com/sayedihashimi/template-sample/issues/31

**Comment by vlada-shubina** [comment]
@h3rmanj just to double check: is your issue only applicable to Visual Studio solution templates or is it also applies to the templates to be run by dotnet new? 
In case of dotnet new, are you using add projects to solution action then?

**Comment by h3rmanj** [comment]
This is only an issue with Visual Studio as far as I know. dotnet new doesn't seem to have a relation with any solution, so it just spits out whatevers in the template. What do you mean by add projects to solution action?

**Comment by vlada-shubina** [comment]
@h3rmanj do you use [add projects to solution post action](https://github.com/dotnet/templating/wiki/Post-Action-Registry#add-projects-to-a-solution-file) in your template? 

@phenning  @sayedihashimi could you please advice for "type=solution" processing in Visual Studio?

**Comment by h3rmanj** [comment]
No, I do not use that.

**Comment by phenning** [comment]
@h3rmanj This does seem like this would be resolved by my proposal in my last comment here. sayedihashimi/template-sample#31

Do you think that would work for you?

**Comment by h3rmanj** [comment]
@phenning I'm trying to wrap my head around this.

What I want is to be able to have 1 template for all scenarios, so the user doesn't have to select different templates depending on if their using cli, vs solution creator or adding to existing solution.
```
├── README.md
├── Program.cs
└── template.csproj
```

Here I'd like to be able to specify that `README.md` should always be in the top-level of whats created. So if the user creates a solution in visual studio, the resulting structure would be:
```
├── output
│   ├── Program.cs
│   └── output.csproj
├── README.md
└── output.sln
```

And if I'd add to an existing solution, I want it to end up like:
```
├── output
│   ├── Program.cs
│   ├── README.md
│   └── output.csproj
├── existing
│   └── existing.csproj
└── existing.sln
```

With what's available today, I have to create a solution template like so:
```
├── template
│   ├── Program.cs
│   └── template.csproj
├── README.md
└── template.sln
```

What it seems like your proposed solution will fix is wether or not an extra folder is created when checking the `Place Solution and Project in same folder`.

The only problem now however, is that if I use this template to add to an existing solution, the file structure would end up like:
```
├── output
│   ├── output
│   │   ├── Program.cs
│   │   └── output.csproj
│   └── README.md
└── existing.sln
```

Meaning that I'd still need a separate Project and Solution template for what I consider the "same" template.

**Comment by phenning** [comment]
@h3rmanj  I think we would be to have a host property that you could bind to in a condition in your template.json to change the output location of your files relative to the creation path.  

Something like this (based on the !Hosted condition for the Blazor WASM template here: https://github.com/dotnet/aspnetcore/blob/9f48bb24d4a077c2a706c6f02d8a7201a2ed2b4a/src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/.template.config/template.json#L66)

```
"symbols": {
  "HostIdentifier": {
    "type": "bind",
    "binding": "HostIdentifier"
  },
  "IsExclusive": {
    "type": "bind",
    "binding": "IsExclusive"
  }
},
"source": [
  {
    "source": "./",
    "target": "./",
    "exclude": [
      ".template.config/**"
    ],
    "modifiers": [
      {
        "condition": "(!IsExclusive &&  HostIdentifier != \"dotnetcli\")",
        "rename": {
          "output", "."
        }
      }
    ]
  }
]
```

**Comment by h3rmanj** [comment]
In this case I would have one solution template, and when adding a project to solution with VS it would remove the .sln? That sounds good. When will the `IsExclusive` variable be supported in Visual Studio?

How will it interact with earlier versions of VS though, I'm guessing `IsExclusive` will default to false, which would make it always move the project files to the root, even when creating a solution?

**Comment by bekir-ozturk** [comment]
Hi @h3rmanj,
 Thanks for creating the issue. I'm happy to see that (even though not ideal) there is a solution that can alleviate some of the pain.
 
I understand that the problem you are having is more on the Visual Studio side than the template engine. To keep our template engine backlog organized, I will be closing this issue now. But please feel free to continue your discussions here with @phenning  on how this can be solved.
 
If at any point this issue becomes something that can be helped by template engine, I will be sure to reopen this.

**Comment by h3rmanj** [comment]
@phenning Hi again.

I've gotten around to upgrading my templates to .NET 6, and I'm testing your solution in my template to avoid having one template for creating a project, and one for creating a solution.

However, it seems like the `rename` modifier don't support folders/globs. I've tried

```json
{
  "condition": "(!IsExclusive &&  HostIdentifier != 'dotnetcli')",
  "rename": {
    "Company.WebApplication1/**": "."
  }
}
```

and

```json
{
  "condition": "(!IsExclusive &&  HostIdentifier != 'dotnetcli')",
  "rename": {
    "Company.WebApplication1": "."
  }
}
```

Where `Company.WebApplication1` is the folder containing my project in the solution folder.

Any suggestions?

**Comment by h3rmanj** [comment]
After testing this all day, the only conclusion I can come to is that `IsExclusive` is not implemented yet, if I include it in any condition, it never runs.

**Comment by phenning** [comment]
I took another look, and it doesn’t look like the IsExclusive functionality was implemented and merged into the Visual Studio host yet.

**Comment by h3rmanj** [comment]
I see. Can I expect it anytime soon?

**Comment by phenning** [comment]
@h3rmanj since this issue is closed and the feature relates to the Visual Studio host, we can continue this in the linked issue:

https://github.com/sayedihashimi/template-sample/issues/31
