### ISSUE TITLE
Solution templates modified outside the environment

### ISSUE THREAD

**Issue by h3rmanj** [dotnet/templating#3282]
I have a template with `"type": "solution"`, which includes a solution file. When using the template with Visual Studio, I get this box.

![image](https://user-images.githubusercontent.com/11387548/121905834-d4f3cc80-cd2a-11eb-958e-ba7206e252ae.png)

I don't know if this behavior is because I'm including a solution file, if it's a bug with Visual Studio, or my solution file is configured wrong. Here is my solution contents:

```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 16
VisualStudioVersion = 16.0.31123.39
MinimumVisualStudioVersion = 10.0.40219.1
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Company.WebApplication1", "Company.WebApplication1\Company.WebApplication1.csproj", "{0E62310C-D76A-4681-9926-B1BFFDC379FC}"
EndProject
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Solution Items", "Solution Items", "{6B4D25B3-1CA5-49A7-BD85-EDC0FFF3AC14}"
	ProjectSection(SolutionItems) = preProject
		.gitlab-ci.yml = .gitlab-ci.yml
		README.md = README.md
	EndProjectSection
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{0E62310C-D76A-4681-9926-B1BFFDC379FC}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{0E62310C-D76A-4681-9926-B1BFFDC379FC}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{0E62310C-D76A-4681-9926-B1BFFDC379FC}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{0E62310C-D76A-4681-9926-B1BFFDC379FC}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {5DE71351-DC3F-4E17-8AE3-443815BF1289}
	EndGlobalSection
EndGlobal
```

And in my `template.json` I have the following in the `guid` section:
```
  "guids": [
    "0E62310C-D76A-4681-9926-B1BFFDC379FC",
    "53bc9b9d-9d6a-45d4-8429-2a2761773502"
  ],
```

The template in question is `iwebapi` from [Intility.Templates](https://www.nuget.org/packages/Intility.Templates/).

**Comment by vlada-shubina** [comment]
@phenning @sayedihashimi could you please check this issue? thank you.

**Comment by phenning** [comment]
Note that this only repros if Place solution and project in the same directory is checked. Otherwise, there is no conflict as I explain below, since your sln and VS's sln get generated in separate folders.

I believe this is happening because the .sln you have in the project exactly matches the sourceName property, which will conflict with the Visual Studio generated sln.

What is happening is this:

1. File new project -> Select InfiinityApi7 (or whatever for the solution and project names).
2. VS generates a InfinityApi7.sln file.
3. VS passes InfinityApi7 as the default name of the project.
4. Since the .sln file in your template exactly matches sourceName specified in template.json, you sln file gets created as InfiinityApi7.sln which is what is causing VS to display the dialog.

You can fix this in your template by just naming your solution file so that it doesn't conflict with the VS generated file.

**Comment by h3rmanj** [comment]
I renamed it to `Solution.sln` and added that to the `primaryOutputs`. It seems to have fixed it, thanks!

But then again, now I'm stuck with a generic name when using the template with `dotnet new`, which is suboptimal, and I'd hope to not add an argument specifically for naming the solution to avoid a generic name. Any tips?

**Comment by sayedihashimi** [comment]
@h3rmanj I think the easiest fix would be to just append something to the solution file name.

For example, lets say that source name is set to 'DemoTemplate' and your solution was originally named `DemoTemplate.sln`. You can just change the solution file to something like `DemoTemplate.App.sln`. When the template is used the project name provided by the user will replace `DemoTemplate` in the solution file name.

**Comment by phenning** [comment]
Sayed's suggestion is the easiest fix.  

Alternatively, you could keep it named the way it is and conditionally rename it (I think this is the correct syntax)

Add a bind for HostIdentifier in symbols:

    "HostIdentifier": {
      "type": "bind",
      "binding": "HostIdentifier"
    },

And add a type level sources array: (use != dotnetcli here so other IDE based hosts other then "vs" would also have the proper rename)
  "sources": [
    {
      "modifiers": [
        {
          "condition": "(HostIdentifier != \"dotnetcli\")",
          "rename": {
            "Company.WebApplication1.sln": "Company.WebApplication1.generated.sln"
          }
        }
      ]
    }
  ]

**Comment by h3rmanj** [comment]
I ended up using @phenning's solution, which worked like a charm, thanks!

@sayedihashimi did you mean to post this comment here?
https://github.com/sayedihashimi/template-sample/issues/31#issuecomment-860809380
> @phenning if I understand correct, the issue occurs when sourceName and the file name for the solution file matches exactly (minus the extension). Seems like we should add a warning to the analyzer to detect and warn in this case, is that correct?

**Comment by sayedihashimi** [comment]
@h3rmanj yes, thanks.

**Comment by phenning** [comment]
Yes. The rule should verify that any SLN files in the templates loot folder does not match the sourceName, regardless if it is a primary output, or if it is a solution project, as this could have the same effect on templates with type = project

**Comment by sayedihashimi** [comment]
Thanks, I filed a new issue to track that update https://github.com/dotnet/templating/issues/3285.

@h3rmanj can we close this issue, or is there still some pending questions?

**Comment by phenning** [comment]
I think that should resolve this specific issue.

**Comment by h3rmanj** [comment]
This is solved, closing
