### ISSUE TITLE
Update analyzer to check if sln name matches sourceName

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/templating#3285]
See conversation at https://github.com/dotnet/templating/issues/3282#issuecomment-860811244

**Comment by vlada-shubina** [comment]
@sayedihashimi is it for analyzer in https://github.com/sayedihashimi/dotnet-new-web?

**Comment by sayedihashimi** [comment]
Sorry, created this in the wrong repo. Made a new issue at https://github.com/sayedihashimi/template-sample/issues/34. Will close this one.
