### ISSUE TITLE
Update --install to support --version for package version

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/templating#330]
`dotnet new --install` should be consistent with `dotnet add`. Specifically we should add a -v|--version parameter instead of what we have today.

**Comment by blackdwarf** [comment]
There is a small gotcha here. `--install` supports installing from file shares and NuGet, correct? However, as we discussed, in the future it may be a lot more potential sources. It will get tricky because for some of those sources the `--version` will not make sense.

**Comment by sayedihashimi** [comment]
Today we support `--install` to a NuGet package or a folder. Later we may add sources like `git`. As you stated in the NuGet case we can have a `--version` and in the `git` case we may have a `--branch`. We'll have to figure out what's the right experience for this. We can chat more next week when we meet.

**Comment by mlorbetske** [comment]
In the latest version, the ::* syntax is no longer required. dotnet new --install {packageid} will install the latest available version
