### ISSUE TITLE
Blazor Server VB.net template

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#3351]
### Discussed in https://github.com/dotnet/templating/discussions/3313

<div type='discussions-op-text'>

<sup>Originally posted by **MarcusMM2** June 19, 2021</sup>
Are anyone planning a template for Blazor Server with VB.net (vbproj instead of csproj)?

When I see it right there are only few "things" to collect, maybe I will do it when I know better how to do.
</div>

**Comment by YuliiaKovalova** [comment]
Close due to no feedback and low demand.
If you still need this template please open the issue in ASP.NetCore repo.
