### ISSUE TITLE
dotnet new --update-check still not working on private feed?

### ISSUE THREAD

**Issue by dominikjeske** [dotnet/templating#3353]
I saw that https://github.com/dotnet/templating/issues/2592 should fix problem on private feeds but for me it is still not working - or I'm doing something wrong?

I have .NET SDK 5.0.301 and two versions of the package 1.0.1 and 1.0.2

I'm installing 1.0.1 with explicit version
dotnet new -i "package::1.0.1" --nuget-source https://ourfeed

next I'm trying to check for update (I don't know if --nuget-source is supported in update so I tried both)
dotnet new --update-check
dotnet new --update-check --nuget-source https://ourfeed

but I have "No updates were found." 
When I use explicit version in install command I can install new version. Similar problem I have with --update-apply.

Ps. The other problem with working with update is that list is not displaying version number and it is only available in "dotnet new --debug:showconfig" or "dotnet new -u"

**Comment by vlada-shubina** [comment]
@dominikjeske thank you for reaching out.
This feature is only available starting .NET 6 preview 4. 
Let me know if it is not working for you in .NET 6 preview 4 or later. 
Thank you.

**Comment by vlada-shubina** [comment]
Closing issue. In case you have any issues starting .NET 6 Preview 4, please let us know.
