### ISSUE TITLE
[Loc]With .Net6 Preview6 installed, "dotnet new --list" is displayed as "dotnet dotnet --list --list" for DE. 

### ISSUE THREAD

**Issue by vdanche** [dotnet/templating#3357]
Repro steps:
Install .NET 6 prevew 6 SDK-6.0.100-preview.6.21328.10(runtime-6.0.0-preview.6.21325.12) from https://github.com/dotnet/installer from Main branch
Execute "dotnet new global.json" In CLI and then display no related templated messages
check the message displays

Expected Result:
message display correctly.

Actual Result:
"dotnet new --list" is displayed as "dotnet dotnet --list --list" for DE.

EN
![image](https://user-images.githubusercontent.com/65637796/123776682-1a56f300-d902-11eb-9bdf-4d15f98386f1.png)

DE(incorrectly)
![image](https://user-images.githubusercontent.com/65637796/123776855-42deed00-d902-11eb-8ee3-d0041496aa98.png)

**Comment by vdanche** [comment]
Please check the other local language at the same time.

**Comment by vlada-shubina** [comment]
@vdanche this is fixed in https://github.com/dotnet/templating/pull/3322 
Translations to be updated accordingly.

**Comment by vdanche** [comment]
It has been fixed on the latest RC1 SDK-6.0.100-rc.1.21458.32(runtime-6.0.0-rc.1.21451.13)
E.g(DE screenshot)
![image](https://user-images.githubusercontent.com/65637796/133034460-da479fee-c839-4c0b-86be-cd535f9f5e7c.png)

(SC screenshot)
![image](https://user-images.githubusercontent.com/65637796/133034478-7e94dba1-05bb-4a40-82a7-1d3f2428d61f.png)
