### ISSUE TITLE
Upgrade System.CommandLine dependency

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/templating#3379]
In order to support source-build, an auto update dependency flow should be established to keep the System.CommandLine dependency on the latest version.  The version of System.CommandLine used by the templating projects (2.0.0-beta1.21109.1) lags behind the version included in the SDK which is the version produced by source build.  

Currently the templating repo fails to build in source-build because of a breaking API change made in System.CommandLine with https://github.com/dotnet/command-line-api/pull/1148/files#diff-72cee93846ef63ae468a9f0b8c214ec5989e9f7e71268505248d9834596f146a.  This PR changed the protection level of the Argument property utilized here - https://github.com/dotnet/templating/blob/main/src/Microsoft.TemplateEngine.TemplateLocalizer/Commands/Export/ExportCommand.cs#L40

```
 /repos/installer/artifacts/tarball/src/templating.3bc0d90f3e450f3e4ebda128081d091fb42968e3/artifacts/source-build/self/src/src/Microsoft.TemplateEngine.TemplateLocalizer/Commands/Export/ExportCommand.cs(40,17): error CS0122: 'Option.Argument' is inaccessible due to its protection level [/repos/installer/artifacts/tarball/src/templating.3bc0d90f3e450f3e4ebda128081d091fb42968e3/artifacts/source-build/self/src/src/Microsoft.TemplateEngine.TemplateLocalizer/Microsoft.TemplateEngine.TemplateLocalizer.csproj]
```

**Comment by vlada-shubina** [comment]
Consider adding `Microsoft.Extensions.Logging` and `NuGet` libs at the same time

**Comment by vlada-shubina** [comment]
Added all dependencies in https://github.com/dotnet/templating/pull/3401.
Configured subscriptions:
`https://github.com/nuget/nuget.client (VS 17.0) ==> 'https://github.com/dotnet/templating' ('main')`
`https://github.com/dotnet/command-line-api (.NET Libraries) ==> 'https://github.com/dotnet/templating' ('main')`

`Microsoft.Extensions.Logging` libs will be updated by existing runtime dependencies.
