### ISSUE TITLE
firstLowerCase and kebabCase value forms not working

### ISSUE THREAD

**Issue by CodyDunlap** [dotnet/templating#3385]
I'm trying to use the firstLowerCase and kebabCase value forms in my custom template but they don't seem to be matching the parameter as expected.

Maybe I'm misunderstanding how these are intended to work or what input is expected. I have the following configuration:

``` json
"symbols": {
  "appName": {
    "type": "derived",
    "valueSource": "name",
    "valueTransform": "serviceNameOnly",
    "replaces": "AppName",
    "fileRename": "AppName",
    "forms": {
      "global": [
        "split",
        "lowerCase",
        "kebabCase",
        "camelCase"
      ]
    }
  }
},
"forms": {
  "serviceNameOnly": {
    "identifier": "replace",
    "pattern": "^(.*)(Service)",
    "replacement": "$1"
  },
  "lowerCase": {
    "identifier": "lowerCase"
  },
  "camelCase": {
    "identifier": "firstLowerCaseInvariant"
  },
  "kebabCase": {
    "identifier": "kebabCase"
  }
}
```

When I perform the command `dotnet new my-service -n MyNewService` the `serviceNameOnly` value transform will return the name without "Service". In this example, it would result in `MyNew`. My expectation is that with the replacement on the `appName` symbol and the additional global forms that it would perform the following replacements:

AppName -> MyNew
appName -> myNew
app-name -> my-new
appname -> mynew 

But what I actually get is:

AppName -> MyNew
appName -> appName
app-name -> app-name
appname -> mynew

Any help would be appreciated if I'm doing something incorrect. But according to the documentation, I think I'm doing this correctly, so I'm not sure what's going wrong.

I'm using **dotnet cli 5.0.202**.

**Comment by vlada-shubina** [comment]
@CodyDunlap it appears that `kebabCase` and `firstLowerCaseInvariant` were added only in 5.0.3xx - apologies for incorrect documentation - I'll fix it now.

**Comment by vlada-shubina** [comment]
https://github.com/dotnet/templating/wiki/Runnable-Project-Templates---Value-Forms was updated with correct versions, closing.
