### ISSUE TITLE
Lowering required Newtonsoft.Json to 8.0.3

### ISSUE THREAD

**Issue by DavidKarlas** [dotnet/templating#339]
I'm sorry for causing you this extra work which is pretty useless extra work for you... But is it possible that we could lower required Newtonsoft.Json version from 9.0.1 to 8.0.3.

Reason we need this is that we want to use Templating engine in Visual Studio for Mac where we must use 8.0.3, because we share some Plugins with VS2013 which is using Newtonsoft.Json 8.0.3 as far as I understand.

**Comment by sayedihashimi** [comment]
@mlorbetske thoughts?

**Comment by mlorbetske** [comment]
Note that this would be for the `net45` build only, which should be OK pending some verification.
