### ISSUE TITLE
Input/Output blocks post-action until keypress

### ISSUE THREAD

**Issue by Blackclaws** [dotnet/templating#3429]
I've been trying to leverage the Run Script PostAction with a custom script that lives in my template that gets turned into an executable script by a first PostAction.

However I'm running into a bit of an issue when trying to run interactive commands such as editor windows. 

Essentially:

```
git commit -m "Initial Commit" -e
```

in the PostAction script will indefinitely block the dotnet new command until another key is pressed without the editor window being shown. Once a key is pressed the editor window shows up and works as expected. These pauses are a bit weird and might have to do with the handover to another application somehow, at the very least they make people wait a long time while the action has already taken place. I was about to file a bug report that it blocks indefinitely in general until I pressed a key and suddenly there was an editor window.

**Comment by vlada-shubina** [comment]
@Blackclaws could you please clarify the versions you are using? (`dotnet --info` output)? Thank you.

**Comment by Blackclaws** [comment]
Here you go:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.3.21202.5
 Commit:    aee38a6dd4

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.100-preview.3.21202.5/

Host (useful for support):
  Version: 6.0.0-preview.3.21201.4
  Commit:  236cb21e3c

.NET SDKs installed:
  5.0.102 [/usr/share/dotnet/sdk]
  5.0.204 [/usr/share/dotnet/sdk]
  6.0.100-preview.3.21202.5 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.18 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.18 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.3.21201.13 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.3.21201.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by vlada-shubina** [comment]
@Blackclaws  

do you mean this block:
```
dotnet new TestAssets.PostActions.RunScript.Basic -o test-lnx --force
The template "TestAssets.PostActions.RunScript.Basic" was created successfully.

Processing post-creation actions...

Template is configured to run the following action:
Actual command: vi
Do you want to run this action [Y(yes)|N(no)]?
```

If so, that is as expected. By default, running the script should be confirmed by user in interactive mode. If you want to avoid that, use: `dotnet new <your template name> --allow-scrips yes`

I cannot reproduce any other issues here.

**Comment by Blackclaws** [comment]
The issue is indeed a bit different. The program I called from my script wrote some of its output to stderr, requesting the user to press enter to continue. This was _not_ printed in the ongoing log.
So the issue is actually that stderr is not being printed (or it is sometimes printed of the command does NOT succeed at the end. Otherwise its simply silently dropped.

A solution would be to not redirect stderr during the run or at least copy it to console as well when redirectStandardOutput is set to false.

Minimal example: 

https://github.com/Blackclaws/dotnet-template-issue

**Comment by vlada-shubina** [comment]
@Blackclaws I've added additional configuration `redirectStandardError` in https://github.com/dotnet/templating/pull/3499 which allows to configure whether stream should be redirected or not, it will be available in next .NET 6 preview (RC 1)
