### ISSUE TITLE
PrimaryOutputs is case sensetive but templates have lower case P

### ISSUE THREAD

**Issue by DavidKarlas** [dotnet/templating#344]
Using https://github.com/dotnet/templating/tree/master/template_feed which have `primaryOutputs` with lower case Template.Config.PrimaryOutputs property is always empty, changing casing to `PrimaryOutputs`(with capital P) everything works as expected.

So either templates need fixing to `PrimaryOutputs` or logic needs to be case insensitive.

I'm using NuGets in .Net 4.5 project, I can provide sample project if you can't reproduce this.

**Comment by mlorbetske** [comment]
This is fixed to be case insensitive on read in #342
