### ISSUE TITLE
[Loc]Run “dotnet new --list” in SC, the font is wrong, it should be displayed as simplified Chinese not tranditional chinese

### ISSUE THREAD

**Issue by vdanche** [dotnet/templating#3460]
1. Install net 6 preview 7 SDK[6.0.100-preview.7.21364.30(runtime:6.0.0-preview.7.21360.10)] from https://github.com/dotnet/installer
2. Install it on simplified Chinese OS
3. Run “dotnet new --list” in Japanese
4. Check if the localized strings display well.

**Actual Result:** 
The localized strings fold display wrong. It display tranditional chinese not  simplified Chinese
SC:
![image](https://user-images.githubusercontent.com/65637796/125740218-61c66012-8579-4153-a465-05bb18a9e40d.png)

**Comment by vdanche** [comment]
Currently some other template names still unlocalized, we'll keep track this bug also. Please check other localized languages simultaneously 
![image](https://user-images.githubusercontent.com/65637796/125741021-1aa77071-0770-4588-a5a6-da0d68bdc492.png)

**Comment by vlada-shubina** [comment]
@vdanche 
1) could you please check if the strings below are simplified Chinese? 
```
{
  "author": "Microsoft",
  "name": "控制台应用程序",
  "description": "一个用于创建可在 Windows、Linux 和 macOS 上的 .NET Core 上运行的命令行应用程序的项目",
  "symbols/TargetFrameworkOverride/description": "替代目标框架",
  "symbols/TargetFrameworkOverride/displayName": "目标框架替代",
  "symbols/Framework/description": "项目的目标框架。",
  "symbols/Framework/choices/net6.0/description": "目标 net6.0",
  "symbols/Framework/choices/net6.0/displayName": ".NET 6.0",
  "symbols/Framework/displayName": "框架",
  "symbols/langVersion/description": "在创建的项目文件中设置 LangVersion 属性",
  "symbols/langVersion/displayName": "语言版本",
  "symbols/skipRestore/description": "如果指定，则在创建时跳过项目的自动还原。",
  "symbols/skipRestore/displayName": "跳过还原",
  "postActions/restore/description": "还原此项目所需的 NuGet 包。",
  "postActions/restore/manualInstructions/default/text": "运行“dotnet restore”",
  "postActions/open-file/description": "在编辑器中打开 Program.cs"
}
```
if they are not, this seems to be a translation issue.

2) We do not own other templates. The issue on localizing those should be created in corresponding repos instead (aspnetcore, wpf, winforms, test-templates).

**Comment by vdanche** [comment]
@vlada-shubina 
1. Yes, strings below are simplified Chinese
{
  "author": "Microsoft",
  "name": "控制台应用程序",
  "description": "一个用于创建可在 Windows、Linux 和 macOS 上的 .NET Core 上运行的命令行应用程序的项目",
  "symbols/TargetFrameworkOverride/description": "替代目标框架",
  "symbols/TargetFrameworkOverride/displayName": "目标框架替代",
  "symbols/Framework/description": "项目的目标框架。",
  "symbols/Framework/choices/net6.0/description": "目标 net6.0",
  "symbols/Framework/choices/net6.0/displayName": ".NET 6.0",
  "symbols/Framework/displayName": "框架",
  "symbols/langVersion/description": "在创建的项目文件中设置 LangVersion 属性",
  "symbols/langVersion/displayName": "语言版本",
  "symbols/skipRestore/description": "如果指定，则在创建时跳过项目的自动还原。",
  "symbols/skipRestore/displayName": "跳过还原",
  "postActions/restore/description": "还原此项目所需的 NuGet 包。",
  "postActions/restore/manualInstructions/default/text": "运行“dotnet restore”",
  "postActions/open-file/description": "在编辑器中打开 Program.cs"
}

2. We need to file a bug separately for other unlocalized template name, right?

**Comment by vlada-shubina** [comment]
> 2\. We need to file a bug separately for other unlocalized template name, right?

Correct. Web templates are in dotnet/aspnetcore repo, test templates are in dotnet/test-templates repo, winforms templates are in dotnet/winforms repo, wpf templates are in dotnet/wpf repo. 

I will check the issue with Chinese language. Can you please confirm the locale of the system you are using for testing (Get-WinSystemLocale in powershell) and if the header below is localized correctly?
![image](https://user-images.githubusercontent.com/56045248/125753114-3b72d6da-c209-4e04-95c3-ffbfb4c6213e.png)

**Comment by vdanche** [comment]
> I will check the issue with Chinese language. Can you please confirm the locale of the system you are using for testing (Get-WinSystemLocale in powershell) and if the header below is localized correctly?
> ![image](https://user-images.githubusercontent.com/56045248/125753114-3b72d6da-c209-4e04-95c3-ffbfb4c6213e.png)

below is my system
![image](https://user-images.githubusercontent.com/65637796/125753753-cb62b289-f28c-494f-9329-cb7c196844b3.png)
and the header islocalized correctly.

**Comment by vlada-shubina** [comment]
One additional note about `NuGet Config` and `Web Config`: translators left those strings not localized (similarly to `Microsoft`, `macOS`, `Linux` etc). If you consider this an issue, we need to raise the issue with them and ask to localize it.

**Comment by vdanche** [comment]
@richaverma1 Could you help confirm if NuGet Config and Web Config need to be localized?

**Comment by richaverma1** [comment]
@vdanche are those two translated in .NET 5?

**Comment by vlada-shubina** [comment]
Issue with Chinese localization has been fixed in https://github.com/dotnet/templating/pull/3470. If more fixes are needed for `dotnet new` CLI or templates managed by this repo feel free to reopen it.

**Comment by vdanche** [comment]
@vlada-shubina  Web Config and NuGet Config in CLI need to be localized by referring to the similar strings in VS which has been localized.

SC
![image](https://user-images.githubusercontent.com/65637796/125903313-818f43ec-ddff-424a-a253-ae3d38a7f44d.png)
SC--VS(17.0 preview 3)
![image](https://user-images.githubusercontent.com/65637796/125903504-6acc5490-e772-4542-a0ef-3cdb48c49980.png)
EN--VS(17.0 preview3)
![image](https://user-images.githubusercontent.com/65637796/125907382-0a10034c-dab4-4334-96fc-cdd3ef55a93e.png)



DE
![image](https://user-images.githubusercontent.com/65637796/125904816-ecd73d46-2529-4fd8-a72b-fa7078cfa9d8.png)

please help to fix other locale langauge simultaneously. thanks

FYI @richaverma1 
on net5, Most of the strings have not yet been translated in cli , so we refer to similar strings in VS.

**Comment by vlada-shubina** [comment]
@vdanche I can only open the ticket in translating project for that
It would be helpful to list all wrong translations in format: current translation - expected translation, otherwise they won't likely to be addressed. 
It would be extremely useful if you can copy actual Chinese translations as the text (not as screenshot).

**Comment by vdanche** [comment]
@vlada-shubina
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>


<div style='direction:ltr'>



EN strings | SC current translation | Expected SC   strings
-- | -- | --
Web Config | Web Config | Web 配置文件
Nuget Config | Nuget Config | Nuget   配置文件



</div>


</body>

</html>

**Comment by vlada-shubina** [comment]
> @vlada-shubina Vlada Shubina FTE
> 
> EN strings	SC current translation	Expected SC strings
> Web Config	Web Config	Web 配置文件
> Nuget Config	Nuget Config	Nuget 配置文件

this has been fixed in https://github.com/dotnet/templating/pull/3539

**Comment by vdanche** [comment]
This issue not repro on the latest RC1 SDK-6.0.100-rc.1.21458.32(runtime-6.0.0-rc.1.21451.13) on SC
![image](https://user-images.githubusercontent.com/65637796/133034918-244ddc1e-0192-43e4-8195-7a259f0e7e93.png)
