### ISSUE TITLE
.NET CLI Template doesn't appear in Visual Studio

### ISSUE THREAD

**Issue by LadyNaggaga** [dotnet/templating#3479]
Version of Visual Studio 2022:  Int Preview Version 17.0.0 Preview 3.0 [31515.332.main]

- Installed a local package 

`dotnet new i -  localpath` 

package installed successfully 
![image](https://user-images.githubusercontent.com/2546640/125965739-dc534130-fc14-4248-82f7-b5f7e829ba91.png)

Local template isn't discovered in Visual Studio.

**Comment by KathleenDollard** [comment]
@phenning Can you check this template for any issues if you are in today. @vlada-shubina can take a look on Monday to determine whether there is a discovery bug or an issue with the template.

**Comment by sayedihashimi** [comment]
Try running my analyzer on the template to see if it helps https://github.com/sayedihashimi/template-sample#template-analyzer

**Comment by LadyNaggaga** [comment]
> Try running my analyzer on the template to see if it helps https://github.com/sayedihashimi/template-sample#template-analyzer

Tried the tool : didn't get any output or error 
![image](https://user-images.githubusercontent.com/2546640/125983148-f757c710-2ac9-432b-a646-56aa67859f19.png)

**Comment by sayedihashimi** [comment]
@LadyNaggaga where is the code? I will take a look.

**Comment by phenning** [comment]
Based on the comment “local template” it sounds like you are trying to use a template on a directory path, not a nupkg.  Is that right?

If that’s the case, that isn’t supported quite yet, but will be in VS 2022 Preview 3 soon.

**Comment by vlada-shubina** [comment]
Closing as per previous comment.
