### ISSUE TITLE
Template Localizer tool to support adding comments for templates localization

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#3483]
Use cases:
- add a comment to certain property
  - support multiple templates (via `-r` option)
  - support adding comments to all choices of certain symbol

- update a comment for certain property
  - support multiple templates
  - support adding comments to all choices of certain symbol

Example:
`dotnet <localizer tool> comment  <path to templates>  -r "symbols/framework" "do not localize netcoreapp, netstandard"`
`dotnet <localizer tool> comment  <path to templates>  -r --all-choices "symbols/framework" "do not localize netcoreapp, netstandard"`

Example of adding comment:
```
JSON File
{
 "extension.description": "This is a resource that needs to be localized",
 "_extension.description.comment": "this is the comment for the localization"
}
```

Additionally, template localizer should not remove any comments when updating the localization file content.

**Comment by vlada-shubina** [comment]
We decided not to implement additional command for commenting. 

Double check

> Additionally, template localizer should not remove any comments when updating the localization file content.

If reproduced, this should be fixed.

**Comment by bekir-ozturk** [comment]
Comments seem to be ignored in English loc files (or whatever the original template language is). Works in other languages.

The fix should be:
- Not to ignore existing localizations [here](https://github.com/dotnet/templating/blob/b97a0a93d0649a9d9a0e8a0a7be3e77b40c66358/src/Microsoft.TemplateEngine.TemplateLocalizer.Core/TemplateStringUpdater.cs#L49) (by removing the if check).
- Ignore the existing strings for the template.json language in `SaveTemplateStringsFileAsync` method [here](https://github.com/dotnet/templating/blob/b97a0a93d0649a9d9a0e8a0a7be3e77b40c66358/src/Microsoft.TemplateEngine.TemplateLocalizer.Core/TemplateStringUpdater.cs#L114), but continue to check them for any comments.
