### ISSUE TITLE
`dotnet new -i *.nupkg` doesn't install the template

### ISSUE THREAD

**Issue by dehghani-mehdi** [dotnet/templating#3486]
I have a solution which I wish turn it into a template. I added `.template.config`, `template.json` and `TemplatePack.csproj` and I can install the template using file path, e.g `dotnet new -i C:\MyTemplate`. but I can not install it using generated `.nupkg`.

I could not find any way to tell `dotnet new` to show me the possible error(s).

BTW, after running `dotnet new -i MyTemplate.nupkg` the list of templates shown in the terminal.

`TemplatePack.csproj`:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageType>Template</PackageType>
    <PackageVersion>1.0</PackageVersion>
    <PackageId>MyTemplate</PackageId>
    <Title>MyTemplate</Title>
    <Authors>Me</Authors>
    <Description>MyTemplate.</Description>
    <PackageTags>dotnet-new;templates</PackageTags>

    <TargetFramework>net5.0</TargetFramework>

    <IncludeContentInPack>true</IncludeContentInPack>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <ContentTargetFolders>content</ContentTargetFolders>
    <NoWarn>$(NoWarn);NU5128</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="templates\**\*" Exclude="templates\**\bin\**;templates\**\obj\**" />
    <Compile Remove="**\*" />
  </ItemGroup>

</Project>
```

`template.json`:
```
{
  "$schema": "http://json.schemastore.org/template",
  "author": "Me",
  "classifications": [
    "Web",
    "ASP.NET"
  ],
  "tags": {
    "language": "C#"
  },
  "identity": "MyTemplate",
  "name": "MyTemplate",
  "shortName": "mywebapp",
  "sourceName": "MyTemplate",
  "preferNameDirectory": true
}
```

_MyTemplate is not real, in the actual files I wrote something else._

**Comment by vlada-shubina** [comment]
@dehghani-mehdi could you please clarify the version you are using (`dotnet --info` output)? Thank you.

**Comment by dehghani-mehdi** [comment]
```
.NET SDK (reflecting any global.json):
 Version:   5.0.301
 Commit:    ef17233f86

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.301\

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964
```

**Comment by sayedihashimi** [comment]
@dehghani-mehdi try and run my analyzer on your template https://github.com/sayedihashimi/template-sample#template-analyzer. I can see that you’re missing some required info like the “type” tag. Analyzer may find more.

**Comment by dehghani-mehdi** [comment]
@sayedihashimi ok, but if `template.json` should have `type` why installing the template using file path works?

**Comment by sayedihashimi** [comment]
@dehghani-mehdi because the CLI doesn't care if it's a project or item template. It just generates the files. Visual Studio does care, it will only show `project` or 'solution` in the New Project Dialog.

**Comment by dehghani-mehdi** [comment]
@sayedihashimi I didn't say anything about Visual Studio, I don't even open it.

If I install template using file path and then run `dotnet new --list`, I can see my template and I can use it to make a new solution, but If I install template using .nugpk and then run `dotnet new --list`, I can not see my template. so no VS here.

**Comment by dehghani-mehdi** [comment]
@sayedihashimi I added `"type": "template"` and nothing is changed.

Also from [Reference for template.json](https://github.com/dotnet/templating/wiki/Reference-for-template.json#package-definition)

> You can use tags to improve the metadata of your project. To specify the project language you have to add the tag language, and if you want to make your project searchable via the dotnet new --type command you have to use the tag type

No word about type is required.

**Comment by AR-May** [comment]
Better to add the type, as it is stated as a required field in the json schema, but this indeed does not seem related to the failed installation in CLI. 

I installed the same version of sdk and tried to reproduce the issue.  As for my minimal repro, I used some txt file as a template content and exact files `TemplatePack.csproj` and `template.json` from the description. Installation from nuget package seems working, so my repro attempt failed. 

@dehghani-mehdi, could you please tell us more details? It might help us to get a repro and/or figure out the problem.

- What is the exact command you calling for the installation and what is its output.
- The command `dotnet new -u` shows all the template sources and their uninstallation commands, do you see your nuget package `MyTemplate` there after the installation?

Upgrade to `6.0.100-preview4` or higher version might resolve the problem or help to identify it, as there are plenty of changes and it has better handling of errors and warnings.

Also, if you could share with us some minimal repro template it would be awesome. Template content should not matter during the installation. I'd like to verify that we have the same repro template to work with.

**Comment by dehghani-mehdi** [comment]
@AR-May 

> What is the exact command you calling for the installation and what is its output.

`dotnet new -i ABSOLUTE PATH TO NUPKG FILE` and the output is same as running `dotnet new --list`

> The command dotnet new -u shows all the template sources and their uninstallation commands, do you see your nuget package MyTemplate there after the installation

No, I don't see my nuget package.

> Also, if you could share with us some minimal repro template it would be awesome.

Sure, it's open source and it is already published on nuget right here: https://www.nuget.org/packages/Rightek.CleanArchitecture.Template/

Source code: https://github.com/rightek/rightek.clean-architecture

BTW, I can not install my template by running `dotnet new --install Rightek.CleanArchitecture.Template::1.0.0` too

**Comment by AR-May** [comment]
@dehghani-mehdi 
Ah, the situation seems clear now. Please take a look at the folders structure from this [doc](https://docs.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-template-pack):
```
working
│   templatepack.csproj
└───templates
    ├───extensions
    │   └───.template.config
    │           template.json
    └───consoleasync
        └───.template.config
                template.json
```
There should be a special folder for each template in `templates` folder (there might be many templates in one nuget). There should be a `.template.config` forlder in a root directory of each template. You need not modify the folder structure.

So, what happens is that `dotnet new` successfully installs 0 templates it finds in your nuget package. 
The info and errors during installation were improved in further versions, so sdk upgrade might help you to investigate problems easier.

**Comment by dehghani-mehdi** [comment]
@AR-May 
I have not multiple templates, I just have one template with multiple projects. I didn't mention it before, but I could install my template from the nupkg file once, then I make some changes _I don't remember what changes exactly_, after that I published the template on nuget. when I wanted to test the published template I found out it can not be installed (same for generated nupkg on my computer)

I'm 100% sure the folder structure was exactly same as current structure (at the time I was able to install the generated nupkg). so still I'm not sure your answer is correct about my problem.

I'll try the new version of SDK, maybe it tells me what is wrong.

**Comment by AR-May** [comment]
@dehghani-mehdi 
The number of templates does not matter in the example, it might be 1,2, etc. I am more or less confident that fixing folders structure would resolve your problem. Here is reasoning:

The main problem with your nuget package is complete absence of `.template.config` folder in it. It is not included into package by given `templatepack.csproj`. Thus, the nuget package has 0 templates, nothing is installed, and that is correct behavior. 

The miscommunication between folders structure and what is in `.csproj` file is the reason for absence of `template.json` file in nuget. 

What I suggested is not the only way to fix, right, so your previous working version could have been indeed different. 
You can also fix it in `.csproj` file. Or you can move `.template.config` to `templates` folder. But I'd better keep the folders structure as what is in documentation.

**Comment by dehghani-mehdi** [comment]
@AR-May by moving `.template.config` folder to `templates` folder everything works. thanks to you!

How can I fix it using `.csproj`? I mean I don't like to move `.template.config` folder into `templates` folder.

**Comment by AR-May** [comment]
@dehghani-mehdi 
This is the line you need to fix, it now includes the `template` folder (excluding `bin` and `obj` internal folders) to nuget content:
```
<Content Include="templates\**\*" Exclude="templates\**\bin\**;templates\**\obj\**" />
```
just add folder `.template.config` to include there too.

Only small amount of all nuget packages consists templates, so no reason to have a warning. 

Some docs about writing a `.csproj` for packing: [one](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-using-a-nuspec), [two](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-msbuild).
