### ISSUE TITLE
Missing .Net Core library template

### ISSUE THREAD

**Issue by DavidKarlas** [dotnet/templating#355]
VS2017 has template libraries for .NET Core and .NET Standard see screenshots below:
![image](https://cloud.githubusercontent.com/assets/774791/23215149/a8bded54-f911-11e6-9da7-fb84b20daaf0.png)

![image](https://cloud.githubusercontent.com/assets/774791/23215162/b5d1a4b8-f911-11e6-88a5-f8205f789554.png)

Difference is basically just in TargetFramework which is in one case netstandard1.4 and in other netcoreapp1.0.

Is this intentionally missing in `dotnet new` and is plan to remove it in future VS2017 or should it be added?

**Comment by mlorbetske** [comment]
In these templates it's just part of the regular class library template as one of the choices for framework.

**Comment by DavidKarlas** [comment]
Thank you for quick reply!
