### ISSUE TITLE
Message not displayed when template name in wrong location

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/templating#3552]
I accidently typed this: 

> dotnet new --search zoop --columns author

and got a very long list of templates. I am not sure it was all of them. Unless I am missing something "zoop" is not legal in that location. We should either give a syntax error, or the insufficient information message. We can consider more positional flexibility after we update the parser.

**Comment by KathleenDollard** [comment]
I know this is going to be difficult to fix at the point of the parser. Can we fix it by recognizing at the point of the search that we are returning too many items? Am I correct that this syntax results in a full list of what's on NuGet, or is it filtered in a way I'm not seeing.

**Comment by vlada-shubina** [comment]
The issue is fixed by enabling both `dotnet new zoop --search` and `dotnet new --search zoop` syntax possible. 
Specifying partial name both in argument and `--search` option value will result in error.
