### ISSUE TITLE
PostAction for opening files in IDE

### ISSUE THREAD

**Issue by DavidKarlas** [dotnet/templating#356]
IDEs open "default" file of project. For example VS2017(and all previous afaik) open Program.cs for Console Application.

Is there plan to add PostAction with GUID which indicates opening file in IDE with Args set to file names which template wants to be opened after creation?

**Comment by mlorbetske** [comment]
The model for post actions depends on the environment calling in to the engine. Generally, this means that the calling environment interprets what post actions are available and is responsible for running the ones it supports.  The restore post action is included here for two reasons - first, this repo houses the actual implementation of dotnet new and is therefore responsible for both the concerns of the engine and of that calling environment, second to provide a reference as to how these post actions can be implemented. The restore post action code here wouldn't be the implementation used in VS or VS for Mac as those environments have a different way of integrating with NuGet. Given this model, the direct answer to your question is no, this wouldn't be implemented here.

That said, post actions do rely on an identifier in the configuration to determine what to run and what information to provide to it. Those identifiers and configurations do not change with respect to the caller. This means that there'll need to be a sort of global registry for what the different IDs mean, what their configuration looks like (for each), which environments they're supported in, how to acquire them if they're not included in the calling environment natively and where to file issues for the individual implementations. This will be done in our next documentation push and will be available for everyone to contribute to on the wiki - enabling template authors to discover what the available post actions are and what environments they're expected to work in.

**Comment by RehanSaeed** [comment]
Another post action for opening a file in the users chosen web browser is needed. My use case is to open a ReadMe.html file in the project after project creation. VS does this with ASP.NET Core projects today.

**Comment by mlorbetske** [comment]
Starting a list of post action IDs/configuration requirements/supported environments https://github.com/dotnet/templating/wiki/Post-Action-Registry. The one for opening in the editor, we can't do in this repo, but we can probably do one to open in the default web browser (though that could be an annoyance when running from the CLI).

Also, @RehanSaeed if you wouldn't mind, could you add info for your templates here? https://github.com/dotnet/templating/wiki#community-templates

**Comment by RehanSaeed** [comment]
@mlorbetske Looks like someone has already added it.

**Comment by mlorbetske** [comment]
@RehanSaeed yep, thanks @sayedihashimi for making the list!

**Comment by RehanSaeed** [comment]
Agreed that it would be annoying from the CLI. However, looks like you've found a workaround for that by adding a `condition` property to the post-action (I can't seem to get restore to work with the 1.0 release).

  "symbols": [
    ...
    "SkipRestore": {
      "type": "parameter",
      "datatype": "bool",
      "description": "Skips the execution of 'dotnet restore' on project creation.",
      "defaultValue": "false"
    }
  },
  "postActions": [
    {
      "condition": "(!SkipRestore)",
      "description": "Restore NuGet packages required by this project.",
      "manualInstructions": [
        { "text": "Run 'dotnet restore' in the directory the template was created in." }
      ],
      "actionId": "210D431B-A78B-4D2F-B762-4ED3E3EA9025",
      "continueOnError": true
    }
  ]
}

**Comment by mlorbetske** [comment]
Two things here:
1) We'll want to add an action to the CLI that ignores this post action (as prompting the user that they may want to open a file in those scenarios feels redundant)
2) Define the parameters that are needed on the [Wiki](https://github.com/dotnet/templating/wiki/Post-Action-Registry)

**Comment by DavidKarlas** [comment]
I noticed this is fixed in recent templates and there is entry in Wiki `Open a file in the editor | 84C0DA21-51C8-4541-9940-6CA19AF04EE6`, hence closing
