### ISSUE TITLE
Refactor templates out of this repository

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/templating#359]
Currently we author the templates that we ship for `dotnet new` here. We've done this to simplify our engineering effort during shipping. We should remove the template content from here and place them in the correct repositories. We still have some things to figure out before we can do this, but I'm creating this issue so that it's on our radar.

**Comment by seancpeters** [comment]
Web templates are moved to aspnet/templating

**Comment by mlorbetske** [comment]
Filed #1683 to track communicating the different places the content has moved to
