### ISSUE TITLE
Update console & classlib project templates to opt-in to ImplicitUsings feature

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/templating#3619]
To prepare for the changes coming in dotnet/sdk#19521 we need to update the .NET 6 project templates to include the `<ImplicitUsings>enable</ImplicitUsings>` property setup in their project files.

**Comment by DamianEdwards** [comment]
FYI @vlada-shubina

**Comment by vlada-shubina** [comment]
@bekir-ozturk @DavidKarlas could you please take it over whilst I'm on leave? Thanks

**Comment by DavidKarlas** [comment]
I looked into making this change... We need SDK to make switch first so our integration tests can pass...

**Comment by DamianEdwards** [comment]
@DavidKarlas why is that? The property is benign right now so I think the opposite is true isn't it? Add the property now so that when the SDK change lands the templates continue to get implicit usings applied.

**Comment by DavidKarlas** [comment]
Problem is that if user specify following parameters:
```
dotnet new classlib -o MyProject --framework net6.0 --langVersion 9.0
```
and tries to build project using `dotnet build` this is result:
```
error CS8023: Feature 'global using directive' is not available in C# 9.0. Please use language version 10.0 or greater.
```

**Comment by AraHaan** [comment]
That is because the PR in SDK should do a conditional check to ensure that C# 10 is selected first before emiting global usings.

**Comment by DamianEdwards** [comment]
The templates that support specifying version as an option (like classlib and console) could decide to condition the addition of `<ImplicitUsings>enable</ImplicitUsings>` based on language version, i.e. if `--langVersion` is specified and is less than 10 then do not emit the property.

**Comment by DavidKarlas** [comment]
I have that change ready, problem is that integration tests are failing with error message from previous comment with **current SDK**, hence need to wait for SDK change... I guess I could disable those tests temporary... I will open PR

**Comment by DamianEdwards** [comment]
@DavidKarlas ah sorry I understand now. I keep forgetting the classlib and console templates are "special" in that they support defining language version and thus you'd have tests for that :smile:

Do the needful to coordinate the changes.

**Comment by AraHaan** [comment]
Perhaps what should be done is default the templates to disabled but have a line that overrides it like so:

``<ImplicitUsings Condition="'$(LangVersion)' == '10' OR '$(LangVersion)' == 'preview' OR '$(LangVersion)' == 'latest'">enable</ImplicitUsings>``

I think with the .NET 6 SDK that technically all 3 values would mean the same thing?

**Comment by DamianEdwards** [comment]
@AraHaan as long as the conditions are evaluated by the template engine at project creation time, rather than staying as MSBuild conditions **in** the project file, I think it makes sense to default the inclusion of `<ImplicitUsings>enabled</ImplicitUsings>` based on the template's `--langVersion` option.

**Comment by AraHaan** [comment]
Alternatively why not have the .NET Sdk enable it for the user if they select a language version of 10 or newer?

**Comment by DamianEdwards** [comment]
@AraHaan that's effectively what I'm saying and the PR does AFAICT.

**Comment by pranavkm** [comment]
@DavidKarlas a build of the installer with the SDK changes are available in case you needed to update your tests.

**Comment by DavidKarlas** [comment]
I noticed, thank you, I'm working on making changes, tnx!

**Comment by DavidKarlas** [comment]
With removal of <DisableImplicitUsings>... This change is now complete...
