### ISSUE TITLE
dotnet new -l : Inconsistent naming leads to unneeded confusion.

### ISSUE THREAD

**Issue by chad-ramos** [dotnet/templating#362]
# Issue
Currently, there is an inconsistency between naming in **template.json** and fields in the **dotnet new -l** template table view.

Template => name
Tags => classifications

# Solution

From a users view, there is no value in this and it is bound to confuse someone.  

- Change the naming in **template.json** to match table fields.
- Change the naming in the table view to match **template.json**

**Comment by mlorbetske** [comment]
@chad-ramos I don't think I agree that this would be confusing. While it wouldn't be a big deal to make the column names match what's in the config files, this boils down to intent - the configuration and the usage of the template content are separate concerns. For the dotnet cli, shortname is much closer to having the semantics of a "name" property and name is closer to a description, classifications are interpreted as tags in the cli (you can use them for searching by separating one or more with / in any order) - not to mention that calling something "name" in the grid could lead to confusion with the --name parameter. Conversely, IDE usage would consider name to be name (but it'd be unlikely to label a name for an item as being a name), classifications to be an ordered path through a hierarchy of template clarification nodes and shortname would likely be omitted entirely. Also, the impact of any confusion would be limited to people reading/writing the configuration itself - so long as they supply values in the configuration that seem appropriate for those fields, the application providing the choices will provide a consistent user facing representation of that data, but there's no guarantee that all (or any, for that matter) calling environments would find it best to express the fields to the user instantiating a template in explicitly the terms used during authoring.

@sayedihashimi what are your thoughts on this?

**Comment by chad-ramos** [comment]
@mlorbetske Fair enough.  Admittedly, I was approaching it from too narrow of a scope and was not considering it from a "third-party" viewpoint.  The CLI labels are a translation of the configuration that suits that implementation needs.  Any future tooling developed around the templating engine would translate the configuration to meets its specific lexicon.

**Comment by sayedihashimi** [comment]
@chad-ramos thanks for the comments.

Naming can be a very tricky thing. In this case the names you suggested may make sense if you look at it through the command line lens, but maybe not in other scenarios. I think @mlorbetske spoke to that pretty well.

The reality is that any change that we make now will be a breaking change, so we would have to have good justification for any changes. I'd like to avoid any changes that would make minor improvements in favor of compatibility.

There are two things that I think will significantly improve how the elements in the `template.json` map to how end users see those. I'm already having discussions with @mlorbetske regarding that as well.

Would love to hear your thoughts.

 - Good docs
 - JSON schema + editor support

I'm already working to get some good docs. For the JSON schema, the idea is that we create a JSON schema file for the `template.json` file and then when the file is edited in editors that support JSON schema (like VS2017) users can get info from tooltips and validation.
