### ISSUE TITLE
The form designer is not opened by default when creating a .NET core project from VS

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/templating#3624]
**Visual Studio Version**: 17.0.0 Preview 3.0 [31527.368.main]

**Summary**:
Solution Explorer Icon is set correctly, `.user` file has `Form` subtype, but designer does not open automatically. Designer opens on double-click as expected.

**Steps to Reproduce**:

1. Create a Winforms (or WPF) .NET core project from VS
2. Observe the form designer of this project

**Expected Behavior**:
Designer loads the form

**Actual Behavior**:
The form designer is not opened by default.

![image](https://user-images.githubusercontent.com/15823268/127383240-cec5f0a5-4dbc-4035-a3a0-3ae1e2b4bc63.png)

Is this an intentional change?

**More info**:
* This is a recent regression issue, it doesn't repro on VS 17.0.0 Preview 3.0 [31520.416.main]
* The designer window can be opened by default when creating a Winforms(.NET Framework), WPF(.NET Framework) or Windows Forms Control Library(.NET Framework) project in VS

**Comment by bekir-ozturk** [comment]
Hey @Tanya-Solyanik. This is a duplicate issue, please track: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1360968.
