### ISSUE TITLE
Output "Failed to load host data for template" to Error and not Verbose level logging

### ISSUE THREAD

**Issue by DavidKarlas** [dotnet/templating#3627]
If template author accidentally corrupts "dotnetcli.host.json" we log that issue only in verbose logging, hence it goes unnoticed and causes problems since that file is ignored.

**Comment by vlada-shubina** [comment]
We'll add the warning for .NET 6, however it needs to be moved to --validate functionality (https://github.com/dotnet/templating/issues/2623) later.
