### ISSUE TITLE
Can template.json symbols have also Name/Label property?

### ISSUE THREAD

**Issue by DavidKarlas** [dotnet/templating#363]
Template symbols already have Description property(https://github.com/dotnet/templating/wiki/"Runnable-Project"-Templates#symbolsdescription-optional), can Name(or Label) also be added which could be localised and have spaces in name? e.g. "Application Insights". I want to create generic wizard page where user can set all values based on template.json content.

**Comment by mlorbetske** [comment]
This is something you'll want to put in a "host specific file" (similar to the dotnetcli.host.json files in the templates in template_feed) as you'll want not just custom names but some control over presentation (what sort of control to use to collect the information, how to validate the information, what order the controls will appear in, which inputs should be available only if another parameter has been set to a certain value, etc.). @seancpeters can walk you through the mechanics of that and how it plays with localization.

**Comment by seancpeters** [comment]
Let's setup a meeting / call to discuss this in detail. @DavidKarlas if you want to suggest a date/time we'll try to accommodate as best we can.

**Comment by DavidKarlas** [comment]
@mlorbetske ping me when you are online so we can find best time to chat
