### ISSUE TITLE
Proposal: Two console templates: console & main

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#3654]
See https://github.com/dotnet/templates/issues/520

**Comment by vlada-shubina** [comment]
@KathleenDollard @DamianEdwards could you please review it? It's feedback from last community stand up.

**Comment by DavidKarlas** [comment]
my 2 cents, I'm still fan of my `--classic` idea

**Comment by mducharm** [comment]
This seems like a good compromise; my first thought was that refactoring hints would be sufficient (e.g. a hint to refactor a template using Main to the top-level syntax), but refactoring hints are better suited to the task of easing existing C# developers into new features rather than new developers.

**Comment by tthiery** [comment]
Adding to my original issue: I think the final verdict on the zero-ceremony Program.cs and implicit/static/sdk usings will be in maybe shortly before .NET 7. For a DSL heavy project type (something like SwifUI) these features will stay forever and are useful. But if the zero-ceremony console template is the long-term entry point into .NET programs I think is open for discussion. The pendulum might swing one day into another direction and people might not accept it.

Having the "main" and "console" templates may also soften the argumentative fall if we one day step back again from it.

**Comment by surfmuggle** [comment]
> my 2 cents, I'm still fan of my `--classic` idea

@DavidKarlas how would it look like? Like this `dotnet new console --classic`?

**Comment by baronfel** [comment]
I'm happy to report that in .NET SDK 6.0, the `--use-program-main` option was added to the console and web templates to bring back the 'old style' of console template. This is available in both VS and CLI experiences. Thanks for your engagement and feedback on this issue!
