### ISSUE TITLE
Encoding Symbol Constants

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/templating#368]
If I have a `constant` symbol that determines the assembly product in a `.csproj` and I enter an `&`, the ampersand needs to be XML encoded.

**Comment by mlorbetske** [comment]
How do you think would be the best way to do this? Automatic escaping that the engine just does transparently, with a special directive that indicates that replacements in a particular region should be escaped in a certain way (in the content files), an alternate value form (like how name changes behavior between file name, namespace and class) or a special indication in the config?

**Comment by RehanSaeed** [comment]
Not entirely sure. A default of being encoded by default might be good but with a way of turning that off.

**Comment by mlorbetske** [comment]
Assuming that the value that needs to be encoded in the XML is encoded in the XML already, you can use name forms for this.

Ex.
```
{
  "symbols": {
    "x": {
      "type": "parameter",
      "dataType": "string",
      "replaces": "Test\"Value",
      "forms": [ "encode" ]
   },
  "forms": {
    "encode": {
      "identifier": "xmlEncode"
    }
  }
}
```

This will replace the literal `Test"Value` with the literal the user supplies and it will also replace the XML encoded form (`Test&quot;Value`) with the XML encoded form of the user's value.

**Comment by RehanSaeed** [comment]
What if I have the following in my `template.json`:

```
    "Title": {
      "type": "parameter",
      "datatype": "string",
      "defaultValue": "Project Title",
      "replaces": "PROJECT-TITLE",
      "description": "The name of the project which determines the assembly product name. If the Swagger feature is enabled, shows the title on the Swagger UI."
    }
```

And I want to perform a replacement in my csproj:

```
<PropertyGroup Label="Package">
    <Version>1.0.0</Version>
    <Authors>PROJECT-AUTHOR</Authors>
    <Company>PROJECT-AUTHOR</Company>
    <Product>PROJECT-TITLE</Product>
    <Description>PROJECT-DESCRIPTION</Description>
    <Copyright>Copyright © PROJECT-AUTHOR. All rights Reserved</Copyright>
  </PropertyGroup>
```

Using the following command:

> dotnet new api --name Foo --Title "Foo & Bar"

When I add the `forms` from your sample code, the csproj is still output with:

```
<Product>Foo & Bar</Product>
```

**Comment by seancpeters** [comment]
Note: The syntax for defining value forms in template.json has changed since this post. See #1524 for an updated example.
