### ISSUE TITLE
dotnet mvc fails to run

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/templating#369]
**Repro steps** 

dotnet new 
dotnet restore 
dotnet run 

**Expected**
runs successfully 

**Actual**
c:\mvc>dotnet run

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**dotnet version** 
1.0.0-rc4-004883

**Comment by jinujoseph** [comment]
cc / @mlorbetske

**Comment by mlorbetske** [comment]
This is being tracked by TFS#388215
