### ISSUE TITLE
Support for solution templating with multiple project

### ISSUE THREAD

**Issue by moattarwork** [dotnet/templating#375]
Is there any way to use this templating on solution basis. That was a missing element in visual studio templating for a long time

**Comment by moattarwork** [comment]
Closed by mistake

**Comment by mlorbetske** [comment]
Yep, all you need to do is put the .template.config directory next to the solution instead of next to a single project.

**Comment by sayedihashimi** [comment]
@moattarwork you can use this with `.sln` files already today. As Mike mentioned just move your `.template.config` folder up next to the `.sln` file. When the template is executed the `.sln` file will be included and processed. For example: https://github.com/vbfox/FSharpTemplates/tree/master/content/FSharp-Dll-Sln.

I'm going to close this, but if I've misunderstood please reopen with more details.

**Comment by moattarwork** [comment]
Thnx
