### ISSUE TITLE
Add IsPackable=false to test project templates

### ISSUE THREAD

**Issue by tintoy** [dotnet/templating#376]
Hi.

At present, running `dotnet pack` on a solution with test projects often generates unnecessary warnings when packing test projects. Given that there's no point in packing test projects, how about adding:

```xml
<IsPackable>false</IsPackable>
```

to the test project templates.

That way, they'll be ignored when running `dotnet pack`. If you guys are ok with this idea, I could open a PR - it's probably as simple as adding a single line to 4 files.

**Comment by mlorbetske** [comment]
Sounds good to me, @codito what do you think of this idea?

**Comment by motowilliams** [comment]
> Given that there's no point in packing test projects

There isn't?

**Comment by tintoy** [comment]
@motowilliams why produce a NuGet package for your tests? Unless you're planning on distributing them it doesn't seem to serve any real purpose (that I can see, at least).

**Comment by motowilliams** [comment]
@tintoy that's precisely the reason - we package our suites of integration, acceptance and regression tests to our deployment targets.

**Comment by tintoy** [comment]
@mlorbetske puts it better than I could; I was admittedly focusing only on the common case and didn't think someone might want to do that. Perhaps if it was a switch-style template parameter that's off by default?

**Comment by codito** [comment]
@mlorbetske +1. I think we should set it in the `Microsoft.NET.Test.Sdk` package (it will apply to both IDE, CLI and keep the csproj clean too).

https://github.com/Microsoft/vstest/issues/380 tracks this in vstest.

**Comment by tintoy** [comment]
@codito - if it's set in `Microsoft.NET.Test.Sdk` can that still be overridden per-project, if required?

**Comment by codito** [comment]
Yes, it should be overridable by user.

**Comment by YunWeiaa** [comment]
Repro on D15.0/28106.9000

**Comment by mlorbetske** [comment]
@YunWeiaa what’s reproducing? Visual Studio displaying an option to pack the project even with IsPackable=false or the project having a property saying IsPackable=true by default? If it’s the first one, an issue should be opened on NuGet/home, if the second one (or anything else related to the test templates) an issue should be filed on dotnet/test-templates as those templates are now maintained in that repo.
