### ISSUE TITLE
Templates not being discovered by name with .NET 6.0 Preview 7

### ISSUE THREAD

**Issue by brettsam** [dotnet/templating#3779]
After installing my template package on Preview 7, I can run this:

```
> dotnet new HttpTrigger --list
These templates matched your input: 'HttpTrigger'

Template Name  Short Name  Language  Tags
-------------  ----------  --------  ---------------------------
HttpTrigger    http        [C#]      Azure Function/Trigger/Http
```

But then this fails:
```
> dotnet new HttpTrigger --name HttpTriggerCSharp --namespace abc.def
No templates found matching: 'HttpTrigger'.

To list installed templates, run:
   dotnet new --list
To search for the templates on NuGet.org, run:
   dotnet new HttpTrigger --search
```

It does work when I use short name -- but this is a built-in part of the Azure Functions Core Tools (we use it to power our `func new` CLI command).

**Comment by vlada-shubina** [comment]
We intentionally disabled using full name in https://github.com/dotnet/templating/issues/3113, from .NET 6  only exact short name is allowed to avoid ambiguity and unexpected template instantiations in case of (wrong) partial name match. 

So in case above `dotnet new http` should be used. 

Please let us know if you are blocked by this change, closing.
