### ISSUE TITLE
[Announcement]: wiki now editable by all

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/templating#378]
_This is just an announcement to all watchers, and a place for discussion of this topic. I'll close this after any discussions end here._

I've modified the wiki so that everyone can edit it. I'm working on creating some formal docs, and the team is helping where they can but, in general they are super busy. I'd like for the team to continue focusing on writing code, enabling new features and answering questions that cannot be answered by others via issues. I was hoping that the community can contribute to the wiki because it's going to take some time for us to get formal docs and even when those come it won't be as detailed as we can get here in the wiki.

**Comment by chad-ramos** [comment]
@sayedihashimi - I would love to help where I can but without any kicking off point or loosely defined structure, the community/I would not know where to focus our efforts.  I fear a collision of work might arise, in addition to a bit of confusion.  Did you have any plans on producing some actionable items that would be up for grabs?

**Comment by sayedihashimi** [comment]
@chad-ramos thanks for the comments. I like your suggestion. I've created an issue to improve [Docs in the wiki](https://github.com/dotnet/templating/issues/390) to list what is needed, and that points to more specific issues.
