### ISSUE TITLE
Improve output when choice value is invalid

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/templating#380]
When an invalid choice is passed I noticed that we have an error message in red which indicates the parameter which has a bad value. And in the help output we display the value that was passed in which was problematic. See the image below.
![template-error](https://cloud.githubusercontent.com/assets/1283154/23344966/b41d8566-fc3a-11e6-94b1-b0fc24c43656.png)

The line indicating the bad value doesn't really pop here. Mostly because it's printed in the same color as regular text, but also because the output here has a lot of lines. Especially if the template has a lot of parameters. I think this would be more clear if we make the output more concise and give a hint about how to get more info. For example we can update the error message in red to be something like:

From
------
`Error: Invalid values for parameter(s) [-B] for template Sayed Starter Web.`

To
--

```
Error: Invalid parameter(s):
  -B green
      'green' is not a valid value for -B

Use dotnet new sayedweb -h for usage info.
```

Thoughts?

**Comment by mlorbetske** [comment]
I like it, will add to #373 tonight or tomorrow
