### ISSUE TITLE
[Tab Completion] Move hidden commands to new command line parser

### ISSUE THREAD

**Issue by bekir-ozturk** [dotnet/templating#3813]
Hidden commands list:

- [ ] --alias,
- [ ] --show-alias, 
- [ ] --extraArgs; replaced with [response files](https://github.com/dotnet/command-line-api/blob/72e86ec7615c0c8ecb6a13e34a5c0a97e9309909/docs/Features-overview.md#response-files)
- [ ] `--quiet` - not used
- [ ] `-all, --show-all` - not used
- [x] `--allow-scripts` 
- [x] `--baseline`

Reenable test when implemented: alias is not implemented - https://github.com/dotnet/templating/issues/3813
CanInstantiateTemplate_WithAlias

**Comment by vlada-shubina** [comment]
@baronfel let's discuss it next time, in particularly `--alias`, `--show-alias`, `--extraArgs` with new parser.

**Comment by baronfel** [comment]
`--extraFile` support should probably be deprecated in favor of the response-file handling in [System.CommandLine](https://github.com/dotnet/command-line-api/blob/72e86ec7615c0c8ecb6a13e34a5c0a97e9309909/docs/Features-overview.md#response-files). We'd have to change the parser configuration to add the `ParseResponseFileAs` middleware.

**Comment by vlada-shubina** [comment]
Moved alias related work to separate issue https://github.com/dotnet/templating/issues/4998.
