### ISSUE TITLE
Simplify NuGet package delivery and validation for template authors (via MSBuild Targets)

### ISSUE THREAD

**Issue by bekir-ozturk** [dotnet/templating#3828]
Deliver `Microsoft.TemplateEngine.Authoring.Tasks` package that may be used by template authors.

The package will:
- [ ] - define common properties for template packages (instead of putting them manually)
- [ ] - validate the templates inside the package - see https://github.com/dotnet/templating/issues/2623 (via MSBuild Task)
- [x] - localize the templates (if needed) (via MSBuild Task)

**Comment by JanKrivanek** [comment]
Other possible validation candidate: https://github.com/dotnet/templating/issues/3254
+ localization should be validated for all locales and then during standard installation, only current (or best match) locale should be returned by `RunnableProjectGenerator.GetTemplatesAndLangpacksFromDir`
