### ISSUE TITLE
Improve content in main wiki page

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/templating#384]
Improve content in [main wiki page](https://github.com/dotnet/templating/wiki). It hasn't been updated, besides very specific items recently. It would be nice to have @mlorbetske take a look to ensure the technical aspects are still accurate, and then we work with community to improve the wording/styling.

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by donJoseLuis** [comment]
This item is not as specific about the other items we are currently triaging in our road map; which aim to improve the wiki's content.  Let's close this item & track the work in the other specific issues.
