### ISSUE TITLE
Reference for comment syntax used for each file type

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/templating#385]
Reference for comment syntax used for each file type. For example in a .cs file `#if` and in a .cshtml file `@*#if`

**Comment by lucamorelli** [comment]
I suppose this for json

////#if (IndividualB2CAuth)
//  "AzureAdB2C": {
//    "Instance": "https:////login.microsoftonline.com/tfp",
//    "ClientId": "11111111-1111-1111-11111111111111111",
//    "Domain": "qualified.domain.name",
//    "SignUpSignInPolicyId": "MySignUpSignInPolicyId"
//  },

**Comment by mlorbetske** [comment]
This should be the document covering this https://github.com/dotnet/templating/wiki/Reference-for-comment-syntax
