### ISSUE TITLE
Reference for available macros

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/templating#386]
Reference for available macros, ex now, randomnumber, etc

**Comment by sayedihashimi** [comment]
I think this is covered by https://github.com/dotnet/templating/wiki/Post-Action-Registry. Closing @mlorbetske please reopen if I got that wrong.

**Comment by sayedihashimi** [comment]
Actually I think this is different. @mlorbetske reopening, lets chat about how I can add these to the wiki.

**Comment by seancpeters** [comment]
This is the macro documentation: https://github.com/dotnet/templating/wiki/Available-Parameter-Generators
