### ISSUE TITLE
Share test infra

### ISSUE THREAD

**Issue by RussKie** [dotnet/templating#3866]
I had a chat with @vlada-shubina about sharing your test infra, so https://github.com/dotnet/winforms (and possible others) can test their templates.

**Comment by DavidKarlas** [comment]
Unfortunately current infra is hard to use instead we want to do approval tests hence I created https://github.com/dotnet/templating/issues/3868 we are not sure yet when we will fix this, but I believe it should be part of .NET 7.

**Comment by RussKie** [comment]
Vlada indicated the same. I've raised this for tracking purposes, but since there's #3868 I'll watch it.
