### ISSUE TITLE
Doc for best practices

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/templating#388]
Doc for best practices. @mlorbetske has some best practices that we can follow. Let's get a list from him and put together a page with that content. For ex: in project templates set `preferNameDirectory` to `true`; also ensure project files have a `.` in the name to ensure casing consistency.

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by donJoseLuis** [comment]
Not a P1 issue, but we'll include in the road map.

- not many community votes
- quite old an issue
- will require research for correctness prior to creating the document

**Comment by YuliiaKovalova** [comment]
close because we have enough documentation now and best practices may be controlled/revealed via validation messages.
