### ISSUE TITLE
How to create a template and publish to NuGet

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/templating#389]
How to create a template and share it on NuGet. A walk through to help users create the .nupkg and publish to NuGet that hasn't done this before.

**Comment by chad-ramos** [comment]
@sayedihashimi - I can give this one a go.

**Comment by sayedihashimi** [comment]
Thanks @chad-ramos, I've marked this as assigned.

**Comment by sayedihashimi** [comment]
@chad-ramos did you have a chance to look at this?

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by donJoseLuis** [comment]
Last updated about 3 years ago.
