### ISSUE TITLE
dotnet new postAction script running `git add .` breaks on windows

### ISSUE THREAD

**Issue by aslezak** [dotnet/templating#3900]
I have a template that as part of running `dotnet new ....` also runs a small script to initialize a git repository.
step is configured as:
```json
  "postActions": [{
     "description": "Initialize Git Repo and Submodules",
     "manualInstructions": [{ 
       "text": "Run 'git-init.ps1'" 
       }],
     "actionId": "3A7C4B45-1F5D-4A30-959A-51B88E82B5D2",
     "args": {
       "executable": "powershell",
       "args": "-File git-init.ps1"
     },
     "redirectStandardOutput": false,
     "continueOnError": true
   }
```

the `git-init.ps1` consists of:
```powershell
git init
git add .
git commit -m "Init"
git tag 0.1.0
```

Idea was to simplify creation of new standardized service and initialise repository with required steps, namely tag so that local build can produce same artefacts as build on CI agent.

Problem is that script hangs on `git add .` step.
Initially I assumed that was because it was messing with line endings of script file itself, but adding it to `.gitignore` did not fix the problem.
Also, there is no visible output from those git commands. Reading discussions here I thought that setting
`"redirectStandardOutput": false,` 
 should make output of this commands show up.
 
 Interestingly enough, this behaviour I have observed only when template is installed from nuget, not when it is installed from local solution.

Any help would be much appreciated.
cheers

**Comment by vlada-shubina** [comment]
@aslezak we had a similar issue before: https://github.com/dotnet/templating/issues/3429. 
Could you please check if the script you are using is not waiting for user input?

Also, when investigating #3429 we made several improvements to run script post action including possibility to disable redirecting stderr via ` "redirectStandardError": false`
I would recommend you to update to latest .NET 6 preview to see if it helps displaying output. I ran your template on the latest version and see that it works as expected.

Regarding NuGet pack behavior I would recommend to check NuGet package itself to see if it packed ps1 correctly. NuGet might not pack ps1 file if not suppressed (https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5111).

**Comment by vlada-shubina** [comment]
> Hey @vlada-shubina Vlada Shubina FTE
> nuget is definitely packed correctly I can see it running the .ps1 file, it even executes about half of it. Running the same file manually works fine. When I have a second I will make a "public version" of template I have and put it on nuget to see if it will be happening on your end as well.

Okay, I can check that if available.

> Second it just get's stuck on running `git add .` command in the scrip, and I have never seen that one asking for user input so far.

If you are using the version prior to fix made, it may output something to stderr and wait for input and that's not displayed.

> Question about the issue #3429, is that related to error output only or stdout as well?

There were multiple improvements for run script post action, both to stdout and stderr in .NET 6.

**Comment by bekir-ozturk** [comment]
I will close this issue now. If you still have issues, please feel free to reply @aslezak.

**Comment by JimWolff** [comment]
I just had the same error with `git add .` breaking / getting stuck / hanging forever.

After changing the postAction to this:
```
    {
      "actionId": "3A7C4B45-1F5D-4A30-959A-51B88E82B5D2",
      "description ": "Add files to git reposository, also hidden folders and files.",
      "manualInstructions": [ { "text": "Run 'git add . -v'" } ],
      "args": {
        "executable": "git",
        "args": "add . -v",
        "redirectStandardOutput": false
      },
      "continueOnError": true
    },
```
The `"redirectStandardOutput": false` was the key.
I'm not sure i understand why it should be set to `false` because when i executed it before i didn't get any output.

I just got:
> Running command 'git add . -v'...
> Command succeeded.

Which to me seems like some output is **not** being redirected. But I'm probably not understanding it correctly, any comment on this would be helpful, because to me it seems like the `redirectStandardOutput` is negated?

Now after setting it to `redirectStandardOutput` `false` i get output from `git add .` when using the verbose `-v` parameter, note `git add .` doesn't output anything by default.
