### ISSUE TITLE
Add dotnet new to Visual Studio Marketplace/NuGet Search

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/templating#391]
Templates need to be more discoverable. Having a list of them in a Wiki in this project is a good start. I'm thinking that either the Visual Studio Marketplace and/or NuGet search (specifically for templates) needs to be able to search for project templates. That's going to take time but good to start the conversation.

A detail page showing the template description, icon, and a list of all the symbols would be good to show. That would mean adding icon properties to the template.json file.

**Comment by sayedihashimi** [comment]
@RehanSaeed we are working with the NuGet team to enable searching for packages which have `packageType` set to `Template`. We will likely create an experience on the command line with something like `dotnet new --search`. For VS we should create a similar experience.

**Comment by mlorbetske** [comment]
We'll be increasing the discoverability of this at the command line soon with #1084

**Comment by Ibro** [comment]
@sayedihashimi any updates regarding VS integration?

**Comment by donJoseLuis** [comment]
This issue was last touched some years ago.  We are working on a new delivery road map.  Please reopen if this is something we want & we'll properly assess its' priority compared to other work aimed at improving the overall templating UX.
