### ISSUE TITLE
Use file-scoped namespace for new item template

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/templating#3930]
Currently, the file-scoped namespace feature had been supported, but when I create a new item(`class`/`interface`) with the latest Visual Studio 2022 Preview 4, the file-scoped namespace had not been applied, could file-scoped namespace be enabled for the new item template?

It may relate to #3359

**Comment by DavidKarlas** [comment]
I just tried with very latest "17.0.0 Preview 5.0 [31719.51]" and this works, but it is important to also add:
```
[*.{cs,vb}]
csharp_style_namespace_declarations=file_scoped:suggestion
```
to your .editorconfig file.

I hope this solves your problem.

**Comment by WeihanLi** [comment]
Thanks, great news
