### ISSUE TITLE
dotnet --interactive not working in 5.0.4xx

### ISSUE THREAD

**Issue by levimatheri** [dotnet/templating#3931]
I've followed all instructions and installed the credential provider. When I run `dotnet new --install <package> --nuget-source <source> --interactive`, nothing happens, the template is NOT installed and no errors are shown. However if I run `dotnet restore <scratch\restore.csproj> --interactive`, it prompts for credentials as expected. How come the `dotnet new --interactive` doesn't prompt me??
Running `dotnet --info` gives me the following:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.401
 Commit:    4bef5f3dbf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.401\

Host (useful for support):
  Version: 5.0.10
  Commit:  e1825b4928

.NET SDKs installed:
  5.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by levimatheri** [comment]
Answering my own question. Not completely sure but I had two sdks installed, uninstalling one of them fixed the issue(?). It's now prompting me for credentials.

**Comment by levimatheri** [comment]
@bekir-ozturk @vlada-shubina  I debugged this issue under `release/5.0.4xx` and noticed we're not using `ForwardStdOut()` [when creating the dotnet restore process.](https://github.com/dotnet/templating/blob/40c1132dcf3c4168d4d80b332361ecdd86ebf529/src/Microsoft.TemplateEngine.Cli/Installer.cs#L280). This causes the interactive prompt not to show on the console. I tried adding the `ForwardStdOut()` and it works correctly. Can we please add this change?

**Comment by DavidKarlas** [comment]
Can you please try with .NET 6 RC1 available  at https://dotnet.microsoft.com/download/dotnet/6.0?

**Comment by levimatheri** [comment]
@DavidKarlas It works with .NET 6 RC1. But my users are not going to have the .NET 6 RC1 sdk installed. The only workaround I can think of is to have them run `dotnet restore --interactive` to trigger the credentials prompt. I noticed this bug affects 5.0.3xx as well.

**Comment by DavidKarlas** [comment]
Another temporary workaround is, to send link to download .nupkg via https, and than user can do 'dotnet new -i path/to/downloaded.nupkg'

**Comment by bekir-ozturk** [comment]
.NET 5 has entered servicing mode, which means it either needs to be security issue or high impact or no workaround to be fixed.
Since .NET 5 serving would go out around same time as .NET 6 stable release and since there is a workaround, we have decided to not fix this bug at this time.

Feel free to reply if you have further concerns.
