### ISSUE TITLE
Inconsistent replacement between  dotnet new cli and VS 2019

### ISSUE THREAD

**Issue by garybond** [dotnet/templating#3939]
I am trying to kebab-case a value in my `azure-pipelines.yml` file and I am getting different behaviour between creating from the template (nuget package) in the CLI (it works) and creating from the VS2019 create new project dialog (same nuget package registered). 

The file generated using the VS create replaces 'APPNAME-IN-KEBAB-CASE' with the 'name' value, but the kebab casing doesn't happen.

Am I doing something wrong?

VS 16.11.3
SDK 5.0.401

```json
  "symbols": {
    "Framework": {
      "type": "parameter",
      "description": "The target framework for the project.",
      "datatype": "choice",
      "choices": [
        {
          "choice": "net5.0",
          "description": "Target net5.0"
        }
      ],
      "replaces": "net5.0",
      "defaultValue": "net5.0"
    },
    "DerivedRenameToKebabCase": {
      "type": "derived",
      "valueSource": "name",
      "valueTransform": "kebab",
      "forms": {
        "global": [ "identity", "kebab" ]
      },      
      "replaces": "APPNAME-IN-KEBAB-CASE"
    }    
  },
  "forms":{
    "kebab": {
      "identifier": "kebabCase"
    }   
  }
```

**Comment by vlada-shubina** [comment]
@garybond kebab case macro was introduced in .NET 5.x, and VS 16.11 uses .NET 3.0 version of template engine, therefore kebab case is not supported there. It will be supported in VS 17 as it uses .NET 6.0 version of template engine.
