### ISSUE TITLE
Cannot install templates from a NuGet package on NET6

### ISSUE THREAD

**Issue by ozziepeeps** [dotnet/templating#3958]
I have a pre-existing NuGet package containing templates for `dotnet new`.

On .NET 6 preview, installation of the templates fails with a "No templates were found in the package" error message. On .NET 5, installation works as expected.

`.NET SDK (reflecting any global.json):`
 `Version:   6.0.100-rc.1.21463.6`
 `Commit:    e627d556a1`

`Host (useful for support):`
`Version: 6.0.0-rc.1.21451.13`
`Commit:  d7619cd4b1`

when I run `dotnet new -i CoStar.Neo.Templates.CSharp::1.15.0-net6support.2`, I get the following output:

`The following template packages will be installed:`
   `CoStar.Neo.Templates.CSharp::1.15.0-net6support.2`

`No templates were found in the package CoStar.Neo.Templates.CSharp::1.15.0-net6support.2`

When I run the same thing on the .NET 5 SDK (via a `global.json` file) the templates install just fine.

Trying to think of how I can provide a repro for you... perhaps I should upload my NuPkgs?

**Comment by ozziepeeps** [comment]
As a note (if it helps) the NuGet package in question is a "top level" package that links to N other NuGet packages that contain the individual templates. Perhaps the walking of the transitive graph has changed/broken in NET6?

**Comment by vlada-shubina** [comment]
@ozziepeeps it would be great if you can provide the package itself.
For the note: the NuGet package should include the templates to be installed. NuGet package dependencies are not supported. It might have worked in .NET 5 due to the templates were installed via dotnet restore, however it won't work in .NET 6.

**Comment by ozziepeeps** [comment]
Please find the NuPkgs attached in a ZIP file. The "top level" package (the one I'm installing) is `CoStar.Neo.Templates.CSharp.1.15.0-net6support.2`. As mentioned previously it doesn't contain any templates itself - it instead pulls in the other packages which do contain templates. This works on NET5. Thanks!

[Templates.zip](https://github.com/dotnet/templating/files/7245538/Templates.zip)

**Comment by ozziepeeps** [comment]
I have worked around this issue by flattening my templates into a top-level NuGet package (which works on NETCORE 3.1, NET5 and on the upcoming NET6), so I am no longer blocked by this. However, please feel free to leave the issue open if you feel like this is a regression (due to the behavioral change between NET5 and NET6)

**Comment by vlada-shubina** [comment]
We decided to close it as we won't support NuGet dependencies for template packages in the near future. Please feel free to comment if you are blocked by this.
