### ISSUE TITLE
File & Folder re-naming via symbols...

### ISSUE THREAD

**Issue by chad-ramos** [dotnet/templating#396]
I would like to see a way to rename targeted files and/or folders via symbol configuration.  

If we are able to target "variables" inside of files, the addition of targeting asset naming might offer a more rounded experience.  Because the templating engine is as flexible as it is, i.e. it does not matter what you put into your template so long as it meets the required contract, I can envision getting great use running ```dotnet new``` inside an already existing project.  In other words, bring the scope down from the project level to a level that is a component of said project. 

## Examples...

Consider the following file structure in your template...

- foo-folder/foo-controller.ts
- foo-folder/foo-service.ts

Hypothetically we would be able to "```dotnet new```" this template to scaffold a new component inside an existing project. 

###  Target individual assets

This would be the most granular approach...

```json
"symbols": {
  "foo-folder-rename": {
    "type": "folder",
    "datatype": "string",
    "replaces": "foo-folder",
    "defaultValue": "new-compnent",
    "description": "Renames component folder"
  },
  "foo-controller-rename": {
    "type": "file",
    "datatype": "string",
    "replaces": "foo-controller",
    "defaultValue": "new-controller",
    "description": "Renames foo-controller"
  },
  "foo-service-rename": {
    "type": "file",
    "datatype": "string",
    "replaces": "foo-service",
    "defaultValue": "new-service",
    "description": "Renames foo-service"
  }
}
```

### Batch target

More of an aggregated approach....

```json
"symbols": {
  "component-rename" : {
    "type": "folder-file",
    "datatype": "string",
    "replaces": "foo",
    "defaultValue": "new-compnent",
    "description": "Renames folder and files"
  }
}
```

**Comment by sayedihashimi** [comment]
Hi @chad-ramos thanks for the issue. We think this sounds interesting, but we have a lot of work that we need to be focused on in the short term.
For the time being we've added this to our list of potential features for the future. Once we make some progress on features like; install/uninstall/update, sharing templates across cli/vs/vs4mac/yeoman, cleaning up help, and a few other important items.

If you're super interested in this and want to take a crack at the code we will review and discuss in a PR.

**Comment by chad-ramos** [comment]
@sayedihashimi Fully understandable.  I just wanted to get my ideas out there now before I forget about them. In regards to taking a crack at it, I have been reviewing the source recently in hopes to do just that.

**Comment by sayedihashimi** [comment]
@chad-ramos sounds good. We welcome community contributions.

**Comment by mlorbetske** [comment]
You should be able to do this now by adding `fileRename` to the parameter:

```
  "symbols": {
    "x": {
      "type": "parameter",
      "dataType": "string",
      "fileRename": "test"
    }
  }
```

Will rename file or directory path segments containing "test" to have the user's specified value

**Comment by chad-ramos** [comment]
@mlorbetske Beautiful! I will check it out soon and provide some feedback.

**Comment by arpit-nagar** [comment]
Thanks...it worked for me 😄

**Comment by FlavioKrahl** [comment]
@sayedihashimi is it possible to use the "fileRename" attribute with your sidewaffle creator somehow?
Could you explain how to update my template wizard interface?
