### ISSUE TITLE
`dotnet new` for custom templates is affected by global.json

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/templating#3978]
See https://github.com/unoplatform/uno/issues/7278.

I believe it should work regardless.

**Comment by vlada-shubina** [comment]
@Youssef1313 global.json determines the dotnet SDK version to be used.
Until .NET 6, the templates had to be installed for each version of dotnet SDK. Starting .NET 6 (preview 4) the templates installed by used will be shared between version.
Let me know if it solves your issue on in case of additional questions.

**Comment by Youssef1313** [comment]
@vlada-shubina The global.json is using the same version in both cases. It's only that allowPrerelease that's different. I don't quite get how this affects things.
