### ISSUE TITLE
Add simpler way to get the "old style" console templates

### ISSUE THREAD

**Issue by dotMorten** [dotnet/templating#3985]
If I don't want to use the new console style projects with generated top-level statements , since I might feel it becomes the odd-one-out file in a project otherwise consisting of "full" classes, I have to do so in a very round about way, as documented here:
https://docs.microsoft.com/en-us/dotnet/core/tutorials/top-level-templates#use-the-old-program-style
![image](https://user-images.githubusercontent.com/1378165/136248356-e2d5f17a-ab6d-4d2b-a2e9-6149d91ea9b6.png)

The problem with this approach (apart from being very unintuitive) is that it doesn't work from within VS2022 (sure I could pick 5 then manually change it after, but if I don't have the 5 SDK installed that leads to more confusing errors on project creation).

Instead I think it would have been cleaner if there was a boolean I could set that the VS IDE also allows me to uncheck to disable the use of top level statements .
It would have been cleaner to have something like
```
    dotnet new console --useTopLevelStatements false
```
and in VS this would translate to a checkbox I can uncheck.

**Comment by glennsills** [comment]
How often to you "dotnet new console"? As features go this one has minimal utility.

**Comment by dotMorten** [comment]
@glennsills VERY often in VS (not so much from the console)

**Comment by jonmikeli** [comment]
Adding to the initial @dotMorten 's request, it would be great whether we could set the default value too (in order to avoid having to type the same options all the time).

Answering to @glennsills, in the team, we use console applications quite often for different types of tests, simulators, etc (mainly in IoT projects, which I understand are quite specific, but not exclusively). We are even working on our own templates for this.

**Comment by sonnemaf** [comment]
@KathleenDollard I don't use the TopLevelStatements because some of the refactorings are not available in it. Take for example the `Introduce local`. 

![image](https://user-images.githubusercontent.com/9335559/136761985-eed1fb02-1b74-4268-9596-287d0012d6ef.png)

![image](https://user-images.githubusercontent.com/9335559/136762226-0bd96a16-5f23-4687-8046-267ad8aa866b.png)

Explaining what a class Program and a static method Main is doing isn't that hard. It also gives me the opportunity to explain readonly fields and access modifiers. Maybe it is just me. But I like the old way just better. So no I'm not considering switching to the new style.

**Comment by tthiery** [comment]
Also consider #3654 (and its original https://GitHub.com/dotnet/templates/issues/520

**Comment by mwwhited** [comment]
I don't use top level statement because the pattern is so disjoin from the rest of the source that it doesn't even seem like the same programming language.

**Comment by henrik-jensen** [comment]
[Norville Barnes to his co-dev](https://www.youtube.com/watch?v=7G5F8ObYgjI): "Top-level statements, I developed it my self, yessiree this is my ticket upstairs."
Co-dev: "???"
Norville: "You know,- for (script) kids"
😁

Nah,- I prefer my c/c++-style main for my console projects, which also offers a return value
```c#
static int Main(string[] args) { return 0; }
``` 
Yeah, I know, `Environment.Exit(0);`, but no!

**Comment by baronfel** [comment]
I'm happy to report that in .NET SDK 6.0, the `--use-program-main` option was added to the console and web templates to bring back the 'old style' of console template. This is available in both VS and CLI experiences. Thanks for your engagement and feedback on this issue!

**Comment by Nordgaren** [comment]
> 

You don't get to decide how people use features. Please don't give non answers like this...

**Comment by Nordgaren** [comment]
> How often to you "dotnet new console"? As features go this one has minimal utility.

You don't get to decide how people use features. Please don't give non answers like this...

**Comment by Nordgaren** [comment]
I am on VS2022 and none of these solutions work, btw. I am sure my SDK is up to date. `--use-program-main ` doesn't work
Error: Invalid option(s):
--use-program-main
   '--use-program-main' is not a valid option

and there is no "Top Level Statements" Checkbox when starting a new console app. Unless I need to download a new template? Shouldn't this just be a part of the SDK by now?

I think this new console template is kinda bad. It's just confusing to new users.

**Comment by baronfel** [comment]
Can you please show what version of the SDK you're using?

**Comment by glennsills** [comment]
@Nordgaren 

Verify this...

```
PS C:\Users\gbsil\src> dotnet --list-sdks
6.0.300 [C:\Program Files\dotnet\sdk]
```
If I then run

```
dotnet new console --use-program-main
```

Program.cs should then look like:

```
namespace src;
class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("Hello, World!");
    }
}
```

You might also want to verify that there is no global.json forcing the use of an older SDK.

**Comment by federico-r-figueredo** [comment]
> I am on VS2022 and none of these solutions work, btw. I am sure my SDK is up to date. `--use-program-main ` doesn't work Error: Invalid option(s): --use-program-main '--use-program-main' is not a valid option
> 
> and there is no "Top Level Statements" Checkbox when starting a new console app. Unless I need to download a new template? Shouldn't this just be a part of the SDK by now?
> 
> I think this new console template is kinda bad. It's just confusing to new users.

I've the exact same problem...

![Screenshot from 2022-10-09 10-48-53](https://user-images.githubusercontent.com/49570839/194760685-a39a21b3-0309-4601-996b-242702cb8fe8.png)

**Comment by glennsills** [comment]
@federico-r-figueredo Try upgrading you .net sdk to 6.0.300 or greater.
