### ISSUE TITLE
Update SimpleConfig to have better defaults for known extensions

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/templating#4]
See https://github.com/ligershark/microsoft-templateengine/issues/56 for what the additional defaults should be

**Comment by seancpeters** [comment]
dotnet/templating@1c0d078 provides setup for nginx.conf and batch file style comments.

**Comment by seancpeters** [comment]
The nginx.conf and robots.txt setup is complete with https://github.com/dotnet/templating/pull/39/commits/d33aa93c0963a099f71613fb2def35e9eb58d90e
