### ISSUE TITLE
File Glob matching is too greedy

### ISSUE THREAD

**Issue by seancpeters** [dotnet/templating#40]
The matches are not anchored and so can match partial paths. Possibly other issues with overlap between what are meant to be disjoint match sets.

**Comment by mlorbetske** [comment]
This should behave the same as globs do in `.gitignore`

From [Git Glossary](https://git-scm.com/docs/gitglossary.html)
> **glob**
Git treats the pattern as a shell glob suitable for consumption by [fnmatch(3)](http://man7.org/linux/man-pages/man3/fnmatch.3.html) with the FNM_PATHNAME flag: wildcards in the pattern will not match a `/` in the pathname. For example, `"Documentation/*.html"` matches `"Documentation/git.html"` but not `"Documentation/ppc/ppc.html"` or `"tools/perf/Documentation/perf.html"`.

> Two consecutive asterisks `("**")` in patterns matched against full pathname may have special meaning:

> A leading `"**"` followed by a slash means match in all directories. For example, `"**/foo"` matches file or directory `"foo"` anywhere, the same as pattern `"foo"`. `"**/foo/bar"` matches file or directory `"bar"` anywhere that is directly under directory `"foo"`.

> A trailing `"/**"` matches everything inside. For example, `"abc/**"` matches all files inside directory `"abc"`, relative to the location of the .gitignore file, with infinite depth.

> A slash followed by two consecutive asterisks then a slash matches zero or more directories. For example, `"a/**/b"` matches `"a/b"`, `"a/x/b"`, `"a/x/y/b"` and so on.

> Other consecutive asterisks are considered invalid.

> Glob magic is incompatible with literal magic.

**Comment by seancpeters** [comment]
:shipit:
