### ISSUE TITLE
Remove nuget.exe

### ISSUE THREAD

**Issue by richlander** [dotnet/templating#405]
https://github.com/dotnet/templating/blob/rel/vs2017/post-rtw/build/nuget.exe

Is this file needed? I thought that this need went away a long time ago, and it certainly doesn't work off of Windows.

This file is currently unattributed, so is violating our licensing policy. We could attribute it, but I'd prefer to just delete it.

/cc @mlorbetske @sayedihashimi  

Same: https://github.com/dotnet/roslyn-project-system/issues/1675 https://github.com/dotnet/symstore/issues/26

**Comment by mlorbetske** [comment]
@richlander unfortunately, we currently use this for building the template packages on our CI (which is Windows). We're working to get this to work via dotnet pack but it currently does not support content only packages. We should attribute this for now and look to remove the need to use it going forward. Any guidance on how to appropriately attribute its use?

**Comment by richlander** [comment]
Interesting. I can attribute it for you, for now. Please keep the issue open so that we remember that we would still prefer to delete the binary. In general, we want to avoid binaries in the repo, because the repo license doesn't neatly apply to them ("it's complicated").

**Comment by mlorbetske** [comment]
Sounds like a plan. Thanks!

**Comment by richlander** [comment]
See #406
