### ISSUE TITLE
[Tab completion] support of template parameters matching for list and search 

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#4061]
Currently we support template parameter filtering for list and search, but the feature is not documented and syntax is not friendly.
Discuss it in scope migration to new parser.

Tests to be reenabled if implemented:

#### Integration tests

DotnetNewList.CanFilterByChoiceParameter
DotnetNewList.CanFilterByNonChoiceParameter
DotnetNewList.IgnoresValueForNonChoiceParameter
DotnetNewList.CanFilterByChoiceParameterWithValue
DotnetNewList.CannotListTemplatesWithUnknownParameter
DotnetNewList.CannotListTemplatesWithUnknownValueForChoiceParameter
DotnetNewList.CannotListTemplatesForInvalidFilters
DotnetNewSearch.CanFilterByChoiceParameter
DotnetNewSearch.CanFilterByNonChoiceParameter
DotnetNewSearch.IgnoresValueForNonChoiceParameter
DotnetNewSearch.CanFilterByChoiceParameterWithValue
DotnetNewSearch.CannotSearchTemplatesWithUnknownParameter
TemplateDiscoveryTests.CanReadCliData
TemplateDiscoveryTests.CanReadCliDataFromDiff

#### Unit tests

TemplateSearchCoordinatorTests.CacheSearchCliSymbolNameFilterTest
TemplateSearchCoordinatorTests.CacheSearchCliSymbolNameMismatchFilterTest

**Comment by vlada-shubina** [comment]
We agreed that in scope of #2191 we will NOT implement support for the existing behavior:

`dotnet new --list --framework` - list all templates which have `--framework` option
`dotnet new --list --framework net5.0` - list all templates which have `--framework` option with value `net5.0`
`dotnet new --search --framework` -  search for all templates which have `--framework` option
`dotnet new --search --framework net5.0` - search for all templates which have `--framework` option with value `net5.0`

however we might implement it with new syntax to be agreed. 
The idea might be `dotnet new --list --has-option framework` or similar.

**Comment by baronfel** [comment]
I suggest the following syntax:

```
dotnet new list --has-symbol OPTION_NAME[=OPTION_VALUE]
```

If only `OPTION_NAME` is specified, the semantic is 'the option specified is present in the template'
If `OPTION_NAME=OPTION_VALUE` is specified, the semantic is 'the option specified is present in the template AND accepts OPTION_VALUE as a valid value'

I _think_ we want to stick with the `symbol` nomenclature here, since symbol is what we call these things in the template.json. It's not the most clear term to the general user, though.

**Comment by vlada-shubina** [comment]
@baronfel term "symbol" means any of: parameter, generated, computed, derived. Only parameters can be entered by user. 
Therefore not sure about using `symbol` here.

**Comment by YuliiaKovalova** [comment]
Close due to no demand.
