### ISSUE TITLE
Auto-Update Solution Files From Excluded Files/Folders

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/templating#4071]
If I have a solution containing a file `appveyor.yml` as a solution item and I have a symbol that excludes the file. The file is not removed from the solution file. I would expect that to happen for me. I'd also expect it to work for project files.

```json
{
  "sources": [
    {
      "modifiers": [
        {
          "condition": "(!AppVeyor)",
          "exclude": [
            "appveyor.yml"
          ]
        }
      ]
    }
  ],
  "symbols": {
    "AppVeyor": {
      "type": "parameter",
      "datatype": "bool",
      "description": "Adds AppVeyor continuous integration build file appveyor.yml.",
      "defaultValue": "false"
    }
  }
}
```

I'm currently having to use `#if` directives inside `.sln` files and this is extremely painful to maintain.

**Comment by bekir-ozturk** [comment]
As mentioned here https://github.com/dotnet/templating/issues/3028, we unfortunately don't have any plans to implement this for the time being.

I will leave this issue open to gather feedback from the community. Feel free to share your thoughts with us here.

**Comment by YuliiaKovalova** [comment]
Close due to no feedback.

**Comment by RehanSaeed** [comment]
The true solution would be to fix .sln files but kind of disappointing that we still have to hand edit them.
