### ISSUE TITLE
Ordering of search results should be based on download count

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/templating#4099]
When I search templates using `dotnet new --search` it looks like the templates are sorted based on the name of the template. For cases when the search has lots of results (ex `dotnet new --search api`) it's hard to find quality templates. I think it would be better to sort by download count, I believe that is how packages are sorted when searching on nuget.org directly.

**Comment by baronfel** [comment]
This makes a lot of sense 👍, we should do it.
