### ISSUE TITLE
Is it possible to have 2 sources in a template?

### ISSUE THREAD

**Issue by javitosanchez** [dotnet/templating#410]
Hello,

I need to generate 2 pairs of sources (files with names) in one template. I tried to pass parameters, but that doesn't generate a file with the name replaced with the parámeter, only the replacement in inside text. Sample:

```
"sourceName": "Company.Item1"
"symbols": {
    "Item2Parameter": {
      "type": "parameter",
      "replaces": "Company.Item2"
    }
```

My source items:
Company.Item1.txt
Company.Item2.txt

Generation name: MyReplacedItem1
Parameter Item2Parameter: MyReplacedItem2

I expect:

MyReplacedItem1.txt
MyReplacedItem2.txt

I get:

MyReplacedItem1.txt
**_Company.Item2.txt_**

**Comment by mlorbetske** [comment]
It would probably work for now to take off the trailing "1" in source name in the config (as Company.Item2 does not contain the string "Company.Item1" but it does contain "Company.Item"). If this doesn't meet your needs, then we'll probably need the issue about adding value forms to be completed - it'll let you apply different transforms to a value and the value it replaces so that the value in the sources (or source item names) gets replaced with the corresponding value.

**Comment by javitosanchez** [comment]
The names where a sample, they are very different, I cannot apply any generic naming logic...

**Comment by mlorbetske** [comment]
I see - if it's the case where you have two values that don't share a common substring between them, then the automatic renaming won't work even with the different value forms (an additional piece that allows for a file name replacements on arbitrary parameters would be needed instead).

Ex.
Source items:
a.txt
b.txt

sourceName:
a.txt

User supplied name:
Test

Cannot result in:
Test(something).txt
Test(something else).txt

If they do share a common substring, setting `sourceName` to that common substring will work.

Ex.
Source items:
xMyItema.txt
yMyItemb.txt

sourceName:
MyItem

User supplied name:
Test

Would result in:
xTesta.txt
yTestb.txt

**Comment by mlorbetske** [comment]
@javitosanchez did my last reply help? If not, I'm not sure how to proceed here - perhaps we could allow other parameters to participate in rename (adding an option to parameters to allow them to match sections of file names)?

**Comment by javitosanchez** [comment]
Not really. It will be solved if the parameters rename the files name.

We'll need both,  the replacement to text inside files and files name.

Thks!!

**Comment by mlorbetske** [comment]
With allowing symbols to participate in renames and the introduction of value forms, this should be fixed now. If there's more to do here, please open a new issue with the pieces that are still missing.
