### ISSUE TITLE
 dotnet new --uninstall -h

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/templating#4100]
I was expecting ` dotnet new --uninstall -h` to show the uninstall context specific help, but instead the command is just executed. Here is the output that I'm seeing.

```
> dotnet new --uninstall -h
Currently installed items:
(No Items)
```

I was expecting this to work because I can use `dotnet new --search -h` to get search specific help.

**Comment by vlada-shubina** [comment]
@sayedihashimi 

did you mean this output by --search specific help?
```
> dotnet new --search -h
Search failed: not enough information specified for search.
To search for templates, specify partial template name or use one of supported filters: 'author', 'baseline', 'language', 'type', 'tag', 'package'.
Examples:
   dotnet new <TEMPLATE_NAME> --search
   dotnet new --search --author Microsoft
   dotnet new <TEMPLATE_NAME> --search --author Microsoft
```

**Comment by sayedihashimi** [comment]
Sorry about that, closing this ticket.
