### ISSUE TITLE
Drop "Core" from template descriptions

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/templating#4109]
https://github.com/dotnet/templating/blob/659138bcba10e2fab5a1ec37d06974d8c6fd7520/template_feed/Microsoft.DotNet.Common.ProjectTemplates.5.0/content/ConsoleApplication-VisualBasic/.template.config/template.json#L10

This is not the only template. Just an example.

**Comment by baronfel** [comment]
We should do this. The branding is:

* .NET Core for versions <5 
* .NET for versions > 5

and we should be consistent with it here.

**Comment by baronfel** [comment]
Another note before I forget - this is ok to be fixed in 6.0.200 only, so we're correct going forward. No need to backport.
