### ISSUE TITLE
Usings in generated project doesn't follow the same order than the template

### ISSUE THREAD

**Issue by jiki974** [dotnet/templating#4119]
When we generate a new project from our template the usings are not correctly sorted and we got this warning on several cs files https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1208.md

**Comment by bekir-ozturk** [comment]
Hi @jiki974 ,
 Thanks for the issue.
 May I ask which template are you instantiating? Using statements come from the template itself and it isn't related to the templating engine. The engine doesn't do sorting.

**Comment by vlada-shubina** [comment]
Closed due to inactivity.

**Comment by jiki974** [comment]
Sorry I was not talking about using statements but using directives https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-directive
