### ISSUE TITLE
Opt-in Nullable Reference Types by default in templates

### ISSUE THREAD

**Issue by hez2010** [dotnet/templating#4138]
# Opt-in Nullable Reference Types by default

`Nullable Reference Types` is a significant feature to decrease the possibility of bugs and it can improve robustness. 
People who don't follow the Microsoft DevBlogs even don't know the existence of this feature, why not opt-in this feature in `dotnet new` template by default? If it was opted-in by default, new projects will consider the nullable issues, and in the future, most projects will not face the unexpected NullableReferenceException.

# Solution
Make all existing templates in `dotnet new` opt-in Nullable Reference Types by default.

**Comment by vlada-shubina** [comment]
This was implemented in https://github.com/dotnet/templating/issues/3359, suggesting to close - let me know if you have any objections.

**Comment by terrajobst** [comment]
Thanks @vlada-shubina!
