### ISSUE TITLE
Doc for creating a template pack duplicates the content in the nupkg

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/templating#4140]
After following the steps at https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates#packing-a-template-into-a-nuget-package-nupkg-file my template nuget package has the content duplicated in the nuget package.

There is a `content` and and `contentFiles` folder in the .nupkg which has the same files. I played around with the csproj for a few min to see what is going on but didn't have time to fully investigate.

The code for my template is at https://github.com/sayedihashimi/sayedha.templates.

I also found the following nuget packages which I believe suffer from the same issue.
 - https://www.nuget.org/packages/SpecFlow.Templates.DotNet/
 - https://www.nuget.org/packages/Threenine.ApiProject/
 - https://www.nuget.org/packages/Laconic.AppTemplate/
 - https://www.nuget.org/packages/E5R.Architecture.Template/0.10.0-beta-330

Can we get the doc updated so that it doesn't duplicate the content in the generated nupkg file? After we should reach out to these template authors to fix their nuget packages as well.

**Comment by vlada-shubina** [comment]
@sayedihashimi  I checked your package - in your case the following property was missing:
`<ContentTargetFolders>content</ContentTargetFolders>` 

I will check other packages - likely the same issue.

It's present in the doc, so nothing to fix there.

**Comment by vlada-shubina** [comment]
`SpecFlow.Templates.DotNet` has a different issue causing the content to appear twice, other templates have the same issue with having no `<ContentTargetFolders>content</ContentTargetFolders>` defined. 

Inform those authors on how to fix their templates.

**Comment by sayedihashimi** [comment]
Thanks @vlada-shubina, not sure how I missed that. I have added an issue to track adding validation to ensure duplicate content isn't in a template .nupkg https://github.com/sayedihashimi/template-sample/issues/48.
