### ISSUE TITLE
Make `SimpleConfigModel` available via public API 

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#4142]
Consider making `SimpleConfigModel` and loading from json public.

It would allow template-analyzer tool to do more advanced checks (https://github.com/sayedihashimi/dotnet-new-web/issues/42), now the tool parses json directly.

It might be useful for other tools that might need to read content on template.json file.
Probably we should consider better naming as `SimpleConfigModel` doesn't sound like a good name (`TemplateConfigModel` may be better).

**Comment by sayedihashimi** [comment]
+1
