### ISSUE TITLE
Unable to uninstall template

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/templating#4156]
I'm trying to uninstall a template, but keep getting an error that the folder isn't found. The folder does exist, but there must be some issue with the template engine that doesn't like it for some reason.

Here is what I'm doing.

 1. Run `dotnet new -u` to get uninstall command
 2. Run uninstall command

Expected: template to be uninstalled
Actual:
```bash
C:\data\mycode> dotnet new --uninstall sayedha.templates
The template package 'C:\data\mycode\sayedha.templates' is not found.
To list installed template packages use:
   dotnet new --uninstall
```

What can I do to diagnose this? I tried `dotnet new --debug:reinit` but that seems to no longer work. Is there some built-in command that can be used to reset `dotnet new` to the install state? That's super handy for template developers.

Here is a gif
![templates-uninstall](https://user-images.githubusercontent.com/1283154/143922318-34fca4a6-6cf1-4a34-8649-41d07c7bf197.gif)
.

**Comment by vlada-shubina** [comment]
@sayedihashimi could you please try to recall the command you installed the template with? (and path you used - it might matter)

I see that uninstall command is not correct in -u output - it should contain absolute path to folder. Subsequent issues may be caused by that.

**Comment by sayedihashimi** [comment]
@vlada-shubina you were correct, I changed directories and the uninstall command worked. Here is the output.

```bash
C:\temp> dotnet new --uninstall sayedha.templates
Success: sayedha.templates::1.0.5 was uninstalled.
```

What a strange bug, definitely would never have figured that out on my own. Do you think we'll be able to fix this or is this something that template authors will need to learn?

**Comment by vlada-shubina** [comment]
yes, it is possible to fix it; I will keep it open.

**Comment by sayedihashimi** [comment]
Sounds good thanks. I'll add some note in about this in my doc.
