### ISSUE TITLE
Dockerfile and vscode configs

### ISSUE THREAD

**Issue by anweiss** [dotnet/templating#416]
Are there plans to include options for generating the appropriate Dockerfile and vscode launch/task configs for running and debugging using Docker? It looks like [generator-docker](https://github.com/Microsoft/generator-docker) hasn't been updated in quite some time. The [Visual Studio Tools for Docker](https://docs.microsoft.com/en-us/dotnet/articles/core/docker/visual-studio-tools-for-docker) doc page still references the `yo docker` scaffolding steps as well.

**Comment by mlorbetske** [comment]
cc @blackdwarf we talked about something similar a while back - should this be rolled in to #233?

**Comment by blackdwarf** [comment]
@mlorbetske yes if I understand @anweiss' comment correctly.  :)

**Comment by mlorbetske** [comment]
Thanks! Added to the template wishlist issue

**Comment by anweiss** [comment]
Thanks all! Will keep an eye on #233
