### ISSUE TITLE
Add support to placing project in root when using post-action AddProjectsToSolutionPostAction

### ISSUE THREAD

**Issue by Tasteful** [dotnet/templating#4178]
When executing the `dotnet sln .. add` we have the ability to add the extra `--in-root` to allow the project to be placed in the root folder. In the template configuration there only exists possibility to set the `--solution-folder` but even if that is set to empty string the project is not placed in root.

**Comment by bekir-ozturk** [comment]
Hi @Tasteful,
 Thanks for the issue. ​This currently isn't in our top priority bucket, but we see the value in implementing this in the future.
​ 
 We think this issue is an easy one for new contributors. If anyone is interested, please consider contributing by creating a PR.

**Comment by levimatheri** [comment]
@bekir-ozturk @vlada-shubina  I'm interested in taking this up. I was trying to look for the source for the post action processor, I don't see it here https://github.com/dotnet/sdk/tree/main/src/Cli/Microsoft.TemplateEngine.Cli/PostActionProcessors.

**Comment by vlada-shubina** [comment]
@levimatheri this code was moved to sdk repo: https://github.com/dotnet/sdk/tree/main/src/Cli/dotnet/commands/dotnet-new/PostActions

Thank you for looking at this!

**Comment by levimatheri** [comment]
Thanks @vlada-shubina

**Comment by vlada-shubina** [comment]
Already done
