### ISSUE TITLE
Computed symbol updates

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/templating#42]
* This is redundant with the "generated -> evaluated" symbol type, use the syntax of computed, and get rid of "generated -> evaluated" type symbols
* The evaluator will need to be able to be specified, right now it always assumes C++ style
* value should behave like a switch, like `postActions` does (keep evaluating conditions until one is true or no condition is specified) to determine the value to assign

**Comment by seancpeters** [comment]
Since computed macro is already setup to take a single condition and set the symbol value to the eval result, we need a new macro for switches, which will be configured with 
"<SymbolName>": {
  "type": "switch",
  "evaluator": "<evaluator_type>"
  "cases": [
    {
      "condition": "<condition 1>",
      "value": "<value 1>"
    },
    {
      "condition": "<condition 2>",
      "value": "<value 2>"
    },
    ...
    {  // optional 
       // if not included and no conditions are true, an empty string will be assigned to the symbol
      "value": "<default value>"
  }
}

**Comment by seancpeters** [comment]
Fixed by PR #49
