### ISSUE TITLE
How to use `ITemplateInfo.TagsCollection`?

### ISSUE THREAD

**Issue by mrlacey** [dotnet/templating#4209]
`ITemplateInfo.Tags` is [marked as deprecated](https://github.com/dotnet/templating/pull/3175) and the comments say to use `TagsCollection` instead. However, I can't find a way to get this to work (with [Microsoft.TemplateEngine.Edge v6.0.100](https://www.nuget.org/packages/Microsoft.TemplateEngine.Edge/)) and I can't find any examples of templates that use TagsCollection.

Is there a way to use the alternative property instead of the one marked deprecated?

Note. I found this when investigating using an _experimental_ updated version of the schema. X-Ref: https://github.com/SchemaStore/schemastore/issues/1980

**Comment by vlada-shubina** [comment]
There was no change to template.json with mentioned issue, ITemplateInfo is not 1:1 representation of template.json. 

Deprecated property 'Tags' used to contain two entities from template.json: 'tags' and symbols of data type 'choice'.
Additionally, 'CacheParameters' contained non-choice parameter symbols.

In new API version:
- TagsCollection contain only 'tags' from template.json
- Parameters contain all parameter symbols from template.json including choices.

**Comment by mrlacey** [comment]
Ok, but how do I use `TagsCollection` rather than `Tags` so I can avoid the deprecation warnings and be ready for when `Tags` is eventually removed?

**Comment by vlada-shubina** [comment]
@mrlacey could you please explain in more details what you are trying to achieve?

My understanding was you are just working on schema as per https://github.com/SchemaStore/schemastore/issues/1980, and schema was not affected with https://github.com/dotnet/templating/pull/3175.

**Comment by mrlacey** [comment]
> @mrlacey could you please explain in more details what you are trying to achieve?
> 
> My understanding was you are just working on schema as per [SchemaStore/schemastore#1980](https://github.com/SchemaStore/schemastore/issues/1980), and schema was not affected with #3175.

I have some templates that use a `template.json` file and have custom tags defined.

After calling `Microsoft.TemplateEngine.Edge.Settings.Scanner.Scan` to read all the supported templates, I get the results from `TemplateEngine.Edge.Settings.ScanResult.Templates` which returns a collection of 
`Microsoft.TemplateEngine.Abstractions.ITemplateInfo`. 
I then apply my own filtering on the returned `IReadOnlyList<ITemplate>` based on the values in the `Tags`.

When I use the `Tags` property in my code, the compiler tells me that:

> 'ITemplateInfo.Tags' is obsolete: 'For choice parameters, use Parameters instead. For template tags, use IReadOnlyDictionary<string, string> TagsCollection instead.'

Because of this warning, I looked to change my code and `template.json` files to use `TagsCollection` instead of `Tags`.
At first, this meant I encountered a JSON Schema that did not know about `TagsCollection` and claimed that `Tags` was still required. Because of this, I looked to see about creating an updated schema file. (Hence the issue on SchemaStore.)

I created a version of a new schema file to test locally. However, when I began using this, I found that the `ITemplateInfo.TagsCollection` property was not populated from my `template.json` files when I called `Scan()` on the appropriate mount point--everything else was still loaded from the files though, and there was no indication of an error.

Assuming that I was doing something wrong, I went looking for documentation or examples on using `TagsCollection` but found none and so opened this issue.

**Comment by vlada-shubina** [comment]
Just tried to do the same, and it worked for me.
My `template.json` is:
```json
{
  "author": "Test Asset",
  "classifications": [ "Test Asset" ],
  "name": "TemplateWithTags",
  "generatorVersions": "[1.0.0.0-*)",
  "groupIdentity": "TestAssets.TemplateWithTags",
  "precedence": "100",
  "identity": "TestAssets.TemplateWithTags",
  "shortName": "TestAssets.TemplateWithTags",
  "tags": {
    "language": "C#",
    "type": "project",
    "custom": "val"
  },
  "sourceName": "bar"
}
```

Test is:
```C#
            EnvironmentSettingsHelper helper = new EnvironmentSettingsHelper();
            Scanner scanner = new Scanner(helper.CreateEnvironment(virtualize: true));
            var result = scanner.Scan("TemplateWithTags");

            Assert.Equal(1, result.Templates.Count);
            Assert.Equal(3, result.Templates[0].TagsCollection.Count);
            Assert.Equal("C#", result.Templates[0].TagsCollection["language"]);
            Assert.Equal("project", result.Templates[0].TagsCollection["type"]);
            Assert.Equal("val", result.Templates[0].TagsCollection["custom"]);

```

It might help if you share you `template.json`, then I can check your defintion.

**Comment by mrlacey** [comment]
@vlada-shubina Oh. thank you so much, that makes sense.
I'd assumed that because of a change in the property being used and that property's name matching what was in the json file, I should change the property name in the json file too.


I had the following snippet in my `template.json`. which is obviously very wrong.

```json

  
  "tagsCollection": {
    "language": "C#",
    "type": "project",
    "custom": "val"
  },
  
```

 
This is all my mistake. Things do work as expected. I just didn't understand.
