### ISSUE TITLE
Add support for look-arounds to all operations for their matched tokens

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/templating#421]
This covers both the configuration read and the internal mechanics of each operation. These require #393 to be completed

- [ ] BalancedNesting
- [ ] Conditional
- [ ] ExpandVariables
- [ ] Include
- [ ] InlineMarkupConditional
- [ ] PhasedOperation
- [ ] Region
- [x] Replacement
- [ ] SetFlag

**Comment by donJoseLuis** [comment]
This issue was last touched some years ago.  We are working on a new delivery road map.  Please reopen if this is something we want & we'll properly assess its' priority compared to other work aimed at improving the overall templating UX.
