### ISSUE TITLE
One of the New3CommandStatus values is out of range (silently truncated)

### ISSUE THREAD

**Issue by RafalSzefler** [dotnet/templating#4253]
https://github.com/dotnet/templating/blob/59bee51d9ff7159ac6483d7bd3d307017e195366/src/Microsoft.TemplateEngine.Cli/New3CommandStatus.cs#L36

This number has 36 bits (coincidentally 36th line as well 😉). It doesn't fit in `int` and thus is truncated (silently, thanks to `unchecked`) to `0x200006`. Since none of the other status codes in this file actually overflows, I assume it is a mistake. Likely there should've been one less zero inside `200006`. As a side effect, this is the only error code that is actually positive.

I'm not sure if it is doable to fix that, I mean such change is not backwards compatible: even though the enum is internal, those codes actually leak outside (I've seen it in console, that's where I started to search for it). But this actually makes debugging a bit hard, since the reported error code is not present in the code.

**Comment by ahaczewski** [comment]
Looks like the error codes come from [the COM error code structure](https://docs.microsoft.com/en-us/windows/win32/com/structure-of-com-error-codes), which expects the 32nd bit to be 1 for errors, in the case of this truncation the error code gives a positive value, which is unexpected of the COM error code for an error condition.

**Comment by vlada-shubina** [comment]
@RafalSzefler thanks for the issue - yes, this seems to be a bug. 
Since it needs breaking change anyway, we would also like to discuss https://github.com/dotnet/templating/issues/3186 at the same time and fix both.

**Comment by vlada-shubina** [comment]
will be fixed as part of #3186
