### ISSUE TITLE
Older package from template than NuGet shows

### ISSUE THREAD

**Issue by GuardRex** [dotnet/templating#426]
`dotnet new mstest` produces a `.csproj` with package versions for `MSTest.TestAdapter` and `MSTest.TestFramework` at `1.1.11` (with the dotnet tooling that installed with VS 2017 RTM; v1.0.0); however, [Nuget is currently showing `1.1.13`](https://www.nuget.org/packages/MSTest.TestAdapter/).

Is this an issue? We plan to put `1.1.11` in the docs because that reflects what the template provides when using `dotnet new mstest`.

**Comment by mlorbetske** [comment]
@GuardRex I don't quite follow, 1.1.12 and 1.1.13 were released to NuGet on 2/22 and 3/10 respectively which would be more recent than the last template update, so they should show as having updates available according to the rules of the package manager window. The template in VS also uses version 1.1.11.

**Comment by GuardRex** [comment]
@mlorbetske Ah, I see. I thought that there would be more :sparkles: magic :sparkles: with the templates/tooling such that if 1.1.13 was latest at NuGet that you'd get that when instantiating the template. We'll go with 1.1.11 in the doc, which will match what the dev sees when they run the command (at least for now ... until the templates are updated).

Thanks for your help :smile:

**Comment by sayedihashimi** [comment]
@GuardRex we haven't added support to update templates yet. That will be coming in a future release.
