### ISSUE TITLE
MAUI authoring

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/templating#4282]
# Background
Deliver "MAUI authoring" requirements.

- [x] https://github.com/dotnet/templating/issues/4490
- [x] https://github.com/dotnet/templating/issues/4491
- [ ] https://github.com/dotnet/templating/issues/4492 - descoped

## Justification
- _Customer impact_ - customers will be able to create item and project templates for MAUI (Multiplatform App UI) framework
- _Engineering impact_ - MAUI team will be able to prepare MAUI templates leveraging dotnet template engine

**Comment by vlada-shubina** [comment]
The work is completed
