### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/templating#4283]
Deliver "Localization" requirements.

Sub tasks:
- [ ] https://github.com/dotnet/templating/issues/4308
- [ ] https://github.com/dotnet/templating/issues/3448
- [x] https://github.com/dotnet/templating/issues/3270
- [ ] https://github.com/dotnet/templating/issues/2819

**Comment by vlada-shubina** [comment]
Closed in favor of https://github.com/dotnet/templating/issues/4308.
