### ISSUE TITLE
MAUI migrations

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/templating#4286]
Deliver "MAUI migrations" requirements.

## Justification
TODO: Any combination of the following...
- Customer impact - what telemetry guided us to this investment? or what use case is this enabling? or is this addressing a popular customer request?
- Needle moving (perf) - what perf gains do we expect? or what are the identified opportunities & corresponding measurements?

**Comment by vlada-shubina** [comment]
Actual implementation was extracted to https://github.com/dotnet/templating/issues/3107
MAUI templates will be adjusted in https://github.com/dotnet/templating/issues/4563
