### ISSUE TITLE
Other Migrations

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/templating#4287]
Other than MAUI Migrations requirements.

## Justification
TODO: Any combination of the following...
- Customer impact - what telemetry guided us to this investment? or what use case is this enabling? or is this addressing a popular customer request?
- Needle moving (perf) - what perf gains do we expect? or what are the identified opportunities & corresponding measurements?

**Comment by vlada-shubina** [comment]
Closed in favor of https://github.com/dotnet/templating/issues/4563
