### ISSUE TITLE
With .NET 7 SDK 7.0.100-alpha.1.22071.3 & SDK 6.0.102, template conflict when creating a new console/classlib without specifying framework

### ISSUE THREAD

**Issue by WenJunJi01** [dotnet/templating#4296]
Environment: .NET 7 SDK 7.0.100-alpha.1.22071.3 and SDK 6.0.102

Repro steps:
1. Install .NET 7 SDK 7.0.100-alpha.1.22071.3 and SDK 6.0.102 on a clean Windows OS.
2. Create a new console or classlib project without specifying framework.

Expected Result:
The project should be created successfully without errors.

Actual Result:
Template conflict when creating a new console/classlib without specifying framework.
![image](https://user-images.githubusercontent.com/87680983/150738321-baf7beca-fb7b-41d5-9b94-0d58556b005f.png)

```
C:\Users\v-wenjj>dotnet new classlib -o mylib1
Unable to resolve the template, the following installed templates are conflicting:
Identity                             Template Name  Short Name  Language  Precedence  Author     Package
-----------------------------------  -------------  ----------  --------  ----------  ---------  -------
Microsoft.Common.Library.CSharp.6.0  Class Library  classlib    C#        8000        Microsoft
Microsoft.Common.Library.CSharp.7.0  Class Library  classlib    C#        8000        Microsoft

Uninstall the templates or the packages to keep only one template from the list.

C:\Users\v-wenjj>dotnet new console -o myconsole1
Unable to resolve the template, the following installed templates are conflicting:
Identity                             Template Name  Short Name  Language  Precedence  Author     Package
-----------------------------------  -------------  ----------  --------  ----------  ---------  -------
Microsoft.Common.Console.CSharp.6.0  Console App    console     C#        8000        Microsoft
Microsoft.Common.Console.CSharp.7.0  Console App    console     C#        8000        Microsoft

Uninstall the templates or the packages to keep only one template from the list.
```

Note: 
Creating a new console/classlib project with the specified framework can succeed.
![image](https://user-images.githubusercontent.com/87680983/150738636-c23cca1e-d3fa-4633-ac48-36f6595b891c.png)

Dotnet info:
.NET SDK (reflecting any global.json):
 Version:   7.0.100-alpha.1.22071.3
 Commit:    b7180e5baf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-alpha.1.22071.3\

Host (useful for support):
  Version: 7.0.0-alpha.1.22066.4
  Commit:  ae2f60c950

.NET SDKs installed:
  6.0.102 [C:\Program Files\dotnet\sdk]
  7.0.100-alpha.1.22071.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-alpha.1.22067.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-alpha.1.22066.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-alpha.1.22065.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by marcpopMSFT** [comment]
@vlada-shubina , let me know if there is anything the SDK team should do here to make this work.

**Comment by vlada-shubina** [comment]
PR is already ready: https://github.com/dotnet/templating/pull/4295

**Comment by vlada-shubina** [comment]
closed in https://github.com/dotnet/templating/pull/4295

**Comment by WenJunJi01** [comment]
With both .NET 6 SDK and .NET 7 SDK installed, unable to create .netstandard classlib even if framework is specified
![image](https://user-images.githubusercontent.com/87680983/151134006-6427b72c-4dee-46f5-a2ec-48994bc6efc7.png)
