### ISSUE TITLE
Installing packages available from unmanaged providers

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#4298]
At the moment nothing prevents a user to install the package available at nuget.org that is already shipped from unmanaged provider (SDK or optional workload). there is a need to make it more robust so the users do not do this unintentionally 

consider

- [x] `dotnet new --install` by default does not install templates which are already installed either from the SDK or an optional workload. To override users need to use additional options (`--force`)

- [x] if user installed the package anyway, continue to remind the user in case newer package exists from unmanaged provider offering the command to uninstall package when the template is run (might be also on any other command) in addition to updates from nuget.org.

- [x] port changes to 6.0.3xx

- [ ] Consider adapting API so all the hosts can benefit from it. As example, make current install API to throw an exception in case package is already available from other providers, overridable by `force`.

**Comment by vlada-shubina** [comment]
@baronfel fyi

**Comment by baronfel** [comment]
Agree with this entirely - we should schedule and do this work as soon as possible.
