### ISSUE TITLE
With both .NET 6 SDK and .NET 7 SDK installed, unable to create .netstandard classlib even if framework is specified. 

### ISSUE THREAD

**Issue by WenJunJi01** [dotnet/templating#4314]
Environment: VS 17.2 Preview 1 [32126.358.main] with 6.0.200-preview.22055.15 + .NET 7 SDK 7.0.100-preview.1.22076.2

Repro steps:
1. Install VS 17.2 P1 [32126.358.main] with 6.0.200-preview.22055.15 + .NET 7 SDK 7.0.100-preview.1.22076.2
2. Create a new .netstandard classlib project with "-f"

Expected Result:
The project should be created successfully.

Actual Result:
Unable to create .netstandard classlib even if framework is specified. 
![image](https://user-images.githubusercontent.com/87680983/151326348-4a39832b-a9af-4f35-8a93-75d64383a0c1.png)

Note:
1. The template conflict issue mentioned in bug https://github.com/dotnet/templating/issues/4296 (Closed) can still repro.
2. Creating a new .net console/classlib project with the specified framework can succeed.

Dotnet info:
.NET SDK (reflecting any global.json):
 Version:   7.0.100-preview.1.22076.2
 Commit:    2e5b83bfe1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-preview.1.22076.2\

Host (useful for support):
  Version: 7.0.0-preview.1.22075.6
  Commit:  aa73132488

.NET SDKs installed:
  6.0.200-preview.22055.15 [C:\Program Files\dotnet\sdk]
  7.0.100-preview.1.22076.2 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-preview.1.22071.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-preview.1.22075.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-preview.1.22075.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by vlada-shubina** [comment]
the fix in https://github.com/dotnet/templating/issues/4296, should help also in this scenario, however insertion to SDK might not have happened yet. @marcpopMSFT could you please confirm when SDK insertion will happen?

**Comment by WenJunJi01** [comment]
Verified on VS 17.2 P1 [32128.244.main] with inserted 6.0.200-preview.22055.15 + NET SDK 7.0.100-preview.1.22078.7, this issue and the bug #4296 are fixed and can not repro. So close it.
