### ISSUE TITLE
Add aliases for common item templates

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#4328]
Consider adding the alternative short names to some item templates, they are often misspelled.
Support for several short names is already available.

- `gitignore` - `.gitignore`
- `globaljson` - `global.json`
- `editorconfig` - `.editorconfig`
- `nugetconfig` - `nuget.config`

**Comment by vlada-shubina** [comment]
@baronfel how do you feel about it? 

One note here: we should think of representation of those in `list` and `help`. While listing all possible short names is good for help, listing all possible short names in `list` tabular output might not be a good idea.

**Comment by baronfel** [comment]
I agree that unbounded choices could make the table look gnarly, but I think for this initial set we don't need to worry about it.
