### ISSUE TITLE
`dotnet new` does not support `--ignore-failed-sources`

### ISSUE THREAD

**Issue by timheuer** [dotnet/templating#4341]
### Describe the bug
The `dotnet new` invocation should honor `--ignore-failed-sources` either directly or through `ENV` settings of some sort

### To Reproduce
Have a nuget feed in your global config that requires integrated auth.  Then `dotnet new <something>` and you'll see a failure:
```
The template "GitHub Actions workflow for .NET Core" was created successfully.
Error: Failed to read package information from NuGet source https://REDACTED/nuget/v3/index.json.
```

In this scenario where dotnet new is doing a restore immediately after it might be good to default to ignore-failed-sources immediately anyway.

**Comment by timheuer** [comment]
Yes @vlada-shubina `--no-update-check` worked!

**Comment by JanKrivanek** [comment]
@timheuer the default behavior now (no switch, env var or so is needed) is that nuget feeds reading errors are debug only. Error is logged only if package was not found in any feed.
