### ISSUE TITLE
EditorConfig template should contain all rules

### ISSUE THREAD

**Issue by cremor** [dotnet/templating#4393]
The file created by `dotnet new editorconfig` ([source](https://github.com/dotnet/templating/blob/main/template_feed/Microsoft.DotNet.Common.ItemTemplates/content/EditorConfig/Dotnet/.editorconfig)) in SDK version 6.0.102 does not contain all available rules. Compared with an EditorConfig file exported by Visual Studio 2022 17.0.6 (via Tools - Options - Text Editor - C# - Code Style - Generate .editorconfig file from settings) the following rules are missing in the template:

```
dotnet_style_namespace_match_folder
csharp_style_namespace_declarations
csharp_style_implicit_object_creation_when_type_is_apparent
csharp_style_prefer_null_check_over_type_check
```

The following are missing too, but I'm not sure if they should be added since they are named "experimental".
```
dotnet_style_allow_multiple_blank_lines_experimental
dotnet_style_allow_statement_immediately_after_block_experimental
csharp_style_allow_blank_line_after_colon_in_constructor_initializer_experimental
csharp_style_allow_blank_lines_between_consecutive_braces_experimental
csharp_style_allow_embedded_statements_on_same_line_experimental
```

**Comment by vlada-shubina** [comment]
@cremor we are considering fixing it as part of https://github.com/dotnet/templating/issues/4126.
Could you please follow that issue? Thank you.

Closing as duplicate.

**Comment by cremor** [comment]
@vlada-shubina Please reopen this issue since it is not part of #4126 any more per your comment https://github.com/dotnet/templating/issues/4126#issuecomment-1321758675 there.

**Comment by vlada-shubina** [comment]
Discussion notes:
- We discussed implementing separate, additional, very basic template engine generator for that to be included to `dotnet new` that will run when the user does `dotnet new editorconfig`
   - generator will generate the `editorconfig` string using Roslyn API and write it to the file
   - ​concerns to address: correct line endings and encoding based on OS
- Step 1: prepare an example of custom generator + test; ensure that multiple generators work end-2-end
- Step 2: implement new generator in sdk repo, incorporate code to generate `editorconfig` content using Roslyn API in `dotnet` CLI
- No parameters to generation are needed, except supporting currently existing `--empty​` flag to generate empty `editorconfig` with `root = true`

**Comment by vlada-shubina** [comment]
Example of custom generator is here: https://github.com/dotnet/templating/pull/5773

**Comment by baronfel** [comment]
@jmarolf here's the custom generator example that we spoke about in our last chat. Will you be able to take a look and SWAG out an editorconfig generator in dotnet/sdk?

**Comment by vlada-shubina** [comment]
> @jmarolf here's the custom generator example that we spoke about in our last chat. Will you be able to take a look and SWAG out an editorconfig generator in dotnet/sdk?

feel free to reach me if you'd need some help on understanding that. There are some features which are not available in example, as localization; but imo we can polish it later.

**Comment by vlada-shubina** [comment]
> Discussion notes:
> 
> * We discussed implementing separate, additional, very basic template engine generator for that to be included to `dotnet new` that will run when the user does `dotnet new editorconfig`
>   
>   * generator will generate the `editorconfig` string using Roslyn API and write it to the file
>   * ​concerns to address: correct line endings and encoding based on OS
> * Step 1: prepare an example of custom generator + test; ensure that multiple generators work end-2-end
> * Step 2: implement new generator in sdk repo, incorporate code to generate `editorconfig` content using Roslyn API in `dotnet` CLI
> * No parameters to generation are needed, except supporting currently existing `--empty​` flag to generate empty `editorconfig` with `root = true`

Step #1 was done in https://github.com/dotnet/templating/pull/5773. This PR demonstrates how the custom generator can be implemented. The testing is performed - it works as expected.

The remaining work is step #2:
- implement new generator in sdk repo, insert it as new component.
- incorporate code to generate `editorconfig` content using Roslyn API (similarly to what VS is done)
- no template parameters to generation are needed, except supporting currently existing `--empty​` flag to generate empty `editorconfig` with `root = true`.
