### ISSUE TITLE
Use file-scoped namespace for classes in project templates

### ISSUE THREAD

**Issue by cremor** [dotnet/templating#4394]
If you create a new project in a solution that uses file-scoped namespaces the classes created by the project template should also use file-scoped namespaces.

Similar to #3930, which only handled new item templates (which work fine).

Repro steps:
1. Create a new repository/solution with an EditorConfig file. Make sure the EditorConfig file contains `csharp_style_namespace_declarations = file_scoped:suggestion`.
2. Create a new project that contains at least one class with a namespace (e.g. class library or WPF application).
3. See that the namespace in the generated class file uses the old block scoped style and that IDE0161 "Convert to file-scoped namespace" is triggered immediately.

- According to dotnet/templating#3360 this should be fixed for class libraries, but I can still reproduce it.
- According to dotnet/aspnetcore#33947 this should be fixed for ASP.NET Core, but I can still reproduce it.
- WPF seems to be still open: dotnet/wpf#4774
- (I didn't test other templates)

Tested with Visual Studio 2022 17.0.6

**Comment by vlada-shubina** [comment]
@cremor 

We investigated the issue yesterday and found out that template is created correctly, however before it it loaded code fixes are applied, also for file-scoped namespace. Unfortunately the code fixes seems to respect only what is defined in options:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/56045248/155284912-c7572c92-6565-4966-ac04-c56926c3f9a7.png) and does not take into account editorconfig settings.

I created VS feedback ticket for this issue: https://developercommunity.visualstudio.com/t/use-file-scoped-namespace-for-classes-in-project-t/1673029, as it is out of scope for dotnet/templating.

I suggest to close this issue and follow up there.

**Comment by cremor** [comment]
@vlada-shubina Thanks for the analysis! I'd like to follow that VS feedback ticket, but it seems like it is not public. Can you please publish it?

**Comment by vlada-shubina** [comment]
@cremor should be public now, could you please check? Thanks

**Comment by bekir-ozturk** [comment]
Hey folks,
 It seems like this was moved to Visual Studio feedback site. So, I'm closing this issue.

**Comment by cremor** [comment]
This was now moved back to Github. See dotnet/roslyn#60449

**Comment by davidwengier** [comment]
Will be fixed by https://github.com/dotnet/roslyn/pull/60450

**Comment by bcheung4589** [comment]
Problem still remains in Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.8.0 Preview 3.0

My editorfile gets ignored.

**Comment by b-maslennikov** [comment]
I still have this problem in latest VS version
