### ISSUE TITLE
Interoperability with other tooling [content discovery for locally installed templates]

### ISSUE THREAD

**Issue by peterblazejewicz** [dotnet/templating#440]
Folks, have you wondered how to proactively provide information for other tooling about installed templates? 
Let me scetch an use case:
- the extension for VSCode can spawn a child process and check if `dotnet cli` is installed`
- if `dotnet cli` is installed the extension could create a content picked by user from the list

The problem with that scenario is IMO that I cannot fill that list in an easy way, at least using available now options for listing installed templates (`-l`,`--list`, `-all`, etc). Some information is missing here (is that template type of project or item?). The next problem is rather non-standard parsing required to get information.

Could you consider for discussion opening more interoperable integration with other tooling just by exposing information from config of installed templates to asking process? I would imagine that just by adding and option like `--json` to `--list` I can get an array of all configs for all templates installed in the current runtime, just like querying REST resource):
https://github.com/dotnet/templating/blob/rel/vs2017/post-rtw/template_feed/Microsoft.DotNet.Web.ProjectTemplates.1.x/content/StarterWeb-FSharp/.template.config/template.json

Thanks!

**Comment by mlorbetske** [comment]
While the generalized approach for getting the data about the available templates is to host the engine (like CLI and other environments do), this seems like a good option for VS Code and the like that would want to offer experiences explicitly from the CLI.

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by donJoseLuis** [comment]
last update was ~3 years ago.  Please reopen if this is some thing that is still desired.
