### ISSUE TITLE
"dotnet new -l" only displays 1 template when there should be 2

### ISSUE THREAD

**Issue by tintoy** [dotnet/templating#443]
Hi.

I have 2 project templates (one creates a project that produces a project template, and the other produces a project that produces an item template). Their `identity` fields (in `template.json`) are different.

Oddly, only 1 of them shows up when running `dotnet new -l` (usually the last one I installed) but never both. I'm not quite sure what the problem is here, but let me demonstrate:

I've tried this by either installing from a [package](https://www.nuget.org/packages/FiftyProtons.Templates.DotNetNew/0.1.0-alpha3) (`dotnet new -i FiftyProtons.Templates.DotNetNew::0.1-alpha3`) or installing from a [folder](https://github.com/tintoy/dotnet-template-templates) (`dotnet new -i src/Templates/content/ProjectTemplate && dotnet new -i src/Templates/content/ItemTemplate`):

```
➜  TemplateDemo: dotnet new -l
Template Instantiation Commands for .NET Core CLI.

Usage: dotnet new [arguments] [options]

Arguments:
  template  The template to instantiate.

Options:
  -l|--list         List templates containing the specified name.
  -lang|--language  Specifies the language of the template to create
  -n|--name         The name for the output being created. If no name is specified, the name of the current directory is used.
  -o|--output       Location to place the generated output.
  -h|--help         Displays help for this command.
  -all|--show-all   Shows all templates


Templates                 Short Name         Language        Tags                 
----------------------------------------------------------------------------------
Console Application       console            [C#], F#        Common/Console       
Class library             classlib           [C#], F#        Common/Library       
Item template             item-template      [C#], [C#]      Common/Templates/Item
Unit Test Project         mstest             [C#], F#        Test/MSTest          
xUnit Test Project        xunit              [C#], F#        Test/xUnit           
ASP.NET Core Empty        web                [C#]            Web/Empty            
ASP.NET Core Web App      mvc                [C#], F#        Web/MVC              
ASP.NET Core Web API      webapi             [C#]            Web/WebAPI           
Solution File             sln                                Solution             
```

Although `project-template` is present, and can be invoked by name, it's not shown in the list.
```
➜  TemplateDemo: dotnet new project-template
Content generation time: 41.4391 ms
The template "Project template" created successfully.
```

**Comment by tintoy** [comment]
I see the `[C#], [C#]` under the Language column, which makes me wonder if dotnet-new is somehow conflating the 2 templates.

**Comment by mlorbetske** [comment]
Is groupIdentity set on these? Could you try setting them to different (from eachother), non-null/empty values?

**Comment by tintoy** [comment]
Yes! Thanks, @mlorbetske, that did indeed fix it. What's the difference between `identity` and `groupIdentity`?

**Comment by mlorbetske** [comment]
Identity is the exact template (globally unique), groupIdentity is the template family (ex. C# and F# MVC templates share a group identity so that they appear as a single template in lists). All templates that have a common group identity will show up at a single template. There was a bug in this until recently (@seancpeters fixed this last week) where templates with a null group identity were grouped even though null is taken to mean "has no logical grouping".

**Comment by tintoy** [comment]
Thanks - that makes sense; so in later builds, I could leave this field out but for now I need to set it to something unique for each template (e.g. the same value as `identity`), have I got that right?

**Comment by mlorbetske** [comment]
Yep, exactly right

**Comment by tintoy** [comment]
Thanks for your help :)
