### ISSUE TITLE
.NET SDK 6.0.103/6.0.201 with runtime 5.0.15&3.1.23, there is an error text if new a 5.0/3.1 ProjectTemplate

### ISSUE THREAD

**Issue by WenJunJi01** [dotnet/templating#4436]
**Environment**: .NET SDK 6.0.103/6.0.201 + Runtime 5.0.15 & 3.1.23

**Repro steps:**

1. Install .NET SDK 6.0.103/6.0.201 + Runtime 5.0.15 & 3.1.23 on a clean Windows/Linux OS.
2. Add feed for 3.1.23&5.0.15&6.0.3:
https://pkgs.dev.azure.com/dnceng/_packaging/3.1.417-servicing-015931-shipping/nuget/v3/index.json
https://pkgs.dev.azure.com/dnceng/_packaging/5.0.406-servicing.22119.1-shipping/nuget/v3/index.json
https://pkgs.dev.azure.com/dnceng/internal/_packaging/6.0.201-servicing.22124.12-shipping/nuget/v3/index.json
4. Run below command to new a 5.0/3.1 ProjectTemplate
```
dotnet new -i Microsoft.DotNet.Web.ProjectTemplates.5.0::5.0.15
dotnet new -i Microsoft.DotNet.Web.ProjectTemplates.3.1::3.1.23
```

**Expected Result:**
The ProjectTemplate can be installed successfully without any errors.

**Actual Result:**
Templates can be installed successfully, but there is an error text.
![image](https://user-images.githubusercontent.com/87680983/155957925-3817b1ed-a0ff-4869-9016-5868a5e084cf.png)
![image](https://user-images.githubusercontent.com/87680983/155958500-1ecf28b4-25cf-4227-a4f3-be0ee88deb03.png)

Note: Log files have been attached.
[Log-3.1.txt](https://github.com/dotnet/templating/files/8152077/Log-3.1.txt)
[Log-5.0.txt](https://github.com/dotnet/templating/files/8152081/Log-5.0.txt)

**Dotnet info:**
.NET SDK (reflecting any global.json):
 Version:   6.0.103
 Commit:    2d7bc7059f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.103\

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  6.0.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by WenJunJi01** [comment]
Similar issue found on February update https://github.com/dotnet/templating/issues/4301: .NET 6.0.102 SDK with 5.0.104 runtime, there is an error text if new a 5.0 ProjectTemplate

**Comment by bekir-ozturk** [comment]
Hi @WenJunJi01 
 Thanks for the issue.

This was fixed in 
- Main branch here: https://github.com/dotnet/templating/pull/4302
- 6.0.3xx branch here: https://github.com/dotnet/templating/pull/4309

We currently don't have any plans to backport this to 6.0.2xx or 6.0.1xx.
