### ISSUE TITLE
Update for template pack is always available at same version for MonoGame

### ISSUE THREAD

**Issue by hsandt** [dotnet/templating#4438]
Coming from MonoGame issue: https://github.com/MonoGame/MonoGame/issues/7429, apparently it is related to the templating engine itself, so reopening an issue here.

Copying the OP's issue description:

"I can't update the MonoGame templates using the command line.
This is very similar to this issue: https://github.com/dotnet/templating/issues/2362, but I am using the correct MonoGame.Templates.CSharp.

dotnet new --install MonoGame.Templates.CSharp::3.8.0.1641 works fine.

But when I create a project:
dotnet new mgdesktopgl -o testmg
I get the following message:

An update for template pack MonoGame.Templates.CSharp::**3.8.0.1641** is available.
    install command: dotnet new -i MonoGame.Templates.CSharp::**3.8.0.1641**

If I run the update command, it seems to work, but I still get the "update available" message.

dotnet new --update-check shows the update available (and others)
dotnet new --update-apply works fine
dotnet new --update-check shows the available Monogame update, but the others are gone.

So it seems I can't update Monogame.Templates.CSharp, but the others work just fine."

As you can see, the update message states the same version twice, making it very odd. Maybe there was a trivial change done without a proper version change, so the templating engine detects a micro diff but can't solve it with a proper version update or something?

**Comment by bekir-ozturk** [comment]
Hey @hsandt,
 Thanks for the issue. 
 This was fixed with .NET 6.0. So updating your SDK should be sufficient.
