### ISSUE TITLE
Does `dotnet new` have merge/append functionality?

### ISSUE THREAD

**Issue by JPThorne** [dotnet/templating#4456]
Let's say I have a template, with a file, and this file has some parametized method. 

Now, I can run this template with some set of params against an output folder and the file is written with the params filled in. If I want to run the template again with a different set of params I have to use `--force`, but of course now my 1st params are overwritten with the new file.

Is there a way to do some sort of 'merge' or 'append' to the generated output rather than a full overwrite? Where could someone request this kind of feature?

**Comment by JPThorne** [comment]
Hi @bekir-ozturk, thank you for the feedback. I will keep an eye on this issue and repo to see what develops, if anything. 

For now I will try to wrap this cli myself and see what "creative" solutions can be used. Maybe I will parse the template variables and append some special marker to make them unique, e.g. PARAM -> PARAM_1, PARAM_2.

**Comment by YuliiaKovalova** [comment]
Close as not planned.
