### ISSUE TITLE
Is it possible to conditionally exclude a file from my template? 

### ISSUE THREAD

**Issue by lukehatcher** [dotnet/templating#4465]
My use case is that I have two very large templates that get generated based on certain user input but only differ by 1-2 files. I would ideally like to only have to maintain one template. 

I have tried using a single base template and then conditionally removing the files I don't need after running `dotnet new` which works fine. I am just curious what the best practice for this scenario is or if there is an API I am missing. I have been looking at [conditional processing](https://github.com/dotnet/templating/wiki/Conditional-processing-and-comment-syntax) but it looks like it's only for the file content, not the files themselves.

Thank you for your time!

**Comment by sayedihashimi** [comment]
@lukehatcher yes you can do this. For example the aspnet core templates exclude files for lots of things. Here is an example https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/StarterWeb-CSharp/.template.config/template.json#L34.

**Comment by hatcherluke** [comment]
Thank you! Just what I was looking for.

**Comment by lukehatcher** [comment]
Thank you! Just what I was looking for.

**Comment by sayedihashimi** [comment]
If that answers your questions please close the issue, and if it doesn't, please let us know where we can provide more details.
