### ISSUE TITLE
dotnet new command should work with the Name provided without the need to specify the name option (-n)

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/templating#4468]
### Is your feature request related to a problem? Please describe.
`dotnet new` command should work with the Name provided without the need to specify its parameter name option (`-n`).

This is especially useful when working with item templates (where specifying the parameter name `-n` is overhead).

I hope readability also improves a lot.

### Describe the solution you'd like
```shell
dotnet new razorcomponent MyComponent
```

Note: there is no need to specify the parameter name `-n` and the first specified parameter is handled as its name.

**Comment by vlada-shubina** [comment]
moved to dotnet/templating. This idea is not new, especially for item templates, it was hardly possible to implement it with old parser.

We don't pass non-option tokens to templates at the moment, it should be possible to do it but imo it makes already complex `dotnet new` syntax even more complex.

**Comment by vlada-shubina** [comment]
Found same issue here: https://github.com/dotnet/templating/issues/3009. Closing as duplicate.
