### ISSUE TITLE
Issue: Failed Local Package Updates with "dotnet new"

### ISSUE THREAD

**Issue by seangwright** [dotnet/templating#4489]
I originally mentioned this issue on another repository and I'm copying here as well.
https://github.com/sayedihashimi/template-sample/issues/55

---

When using a template that was installed locally from a .nupkg file, the .NET CLI wants to check for updates every time the template is used.

```
> dotnet new my-template --name TEST
Warning: MyTemplate is not found in NuGet feeds https://api.nuget.org/v3/index.json, C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\.

<template output>

Failed to check update for MyTemplate::1.0.0: the package is not available in configured NuGet feeds.
```

A locally installed template that is being tested before being published will always produce an error here, which could be confusing to a developer that is trying to resolve issues with the template. They might think these are errors caused by template misconfiguration.

Adding the `--no-update-check` option when invoking the template will prevent this error from appearing.

**Comment by vlada-shubina** [comment]
Similar to: https://github.com/dotnet/templating/issues/4341

**Comment by JanKrivanek** [comment]
@seangwright `dotnet new` will now still perform background checks of template update availability on each instantiation, however it won't report any errors if package is not founf in any configured feeds.
