### ISSUE TITLE
"Templates can be installed from packages in any NuGet feed"

### ISSUE THREAD

**Issue by chad-ramos** [dotnet/templating#449]
- Current README states "Templates can be installed from packages in **any NuGet feed**".  
  - I can't find any additional information about this, is it actually true? 
- It appears that you can only pass the Nuget package name as it exists in a resource listed in https://api.nuget.org/v3/index.json.  
  - Is this correct?

If the answer is yes to either question listed above, it would be of value to be able to define the resource before package name. This would solve issues where the resource is a private feed (MyGet, ProGet, etc...).

**Comment by mlorbetske** [comment]
You should be able to pass package ids/versions corresponding to any feed all long as the feed is either configured for machine wide use or you're in a directory with a nuget.config in or above it pointing to the desired feed when performing the install

**Comment by motowilliams** [comment]
I am able to install templates from a nuget feed albeit a local feed but the API calls _should_ be the same.  https://www.motowilliams.com/building-a-solution-with-dotnet-cli-nuget-templates

**Comment by sayedihashimi** [comment]
@motowilliams is your local feed listed in your global `nuget.config` file? If so I believe it should work.

**Comment by mlorbetske** [comment]
@motowilliams great blog post! One minor thing though, at the bottom, you mention that `dotnet new -i -all` lists all installed templates where it's actually `dotnet new -l -all` (just a typo, since you pass the right switch in the VS code window)
