### ISSUE TITLE
--dry-run doesn't honor output folder option (-o)

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/templating#4526]
`-o|--output` option is not properly honored when using `--dry-run` option - the output folder is still indicated as the current folder (**'./'**):

```
$ dotnet new console --dry-run
File actions would have been taken:
  Create: ./templates.csproj
  Create: ./Program.cs

Processing post-creation actions...
Action would have been taken automatically:
   Restore NuGet packages required by this project.

$ dotnet new console -o foo --dry-run
File actions would have been taken:
  Create: ./foo.csproj
  Create: ./Program.cs

Processing post-creation actions...
Action would have been taken automatically:
   Restore NuGet packages required by this project.

$ dotnet new console -o "C:\foo\bar" --dry-run
File actions would have been taken:
  Create: ./bar.csproj
  Create: ./Program.cs

Processing post-creation actions...
Action would have been taken automatically:
   Restore NuGet packages required by this project.
```

While not harmful, it might be misleading. Actual operation (without `--dry-run`) create targets in proper requested directory.

Tested version: [7.0.1-preview.3 with latest changes at the time of testing](https://github.com/dotnet/templating/tree/2f541cc40b2e2c70e3fa0c154378009eb044244a)

**Comment by JanKrivanek** [comment]
Similar behavior observed with destructive changes notification

**Comment by vlada-shubina** [comment]
Same behavior with earlier versions.
