### ISSUE TITLE
`dotnet new` generates a `dot file` when run from root directory

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/templating#454]
On linux machine with root access:

- `cd /`
- `dotnet new console`
- `ls`

# Expected
Listed files include a csproj file

# Actual
The generated csproj file is called `.csproj`. Since this is a `dot file`, it is hidden from output of ls unless special flags are passed.

**Comment by piotrpMSFT** [comment]
Related to https://github.com/dotnet/templating/issues/381

**Comment by mlorbetske** [comment]
What's the suggested behavior here? Should it fail and indicate that --name must be specified (as it wasn't and the root directory has no name) or should it just use the original names of the files from the template content?
