### ISSUE TITLE
Is it possible to use array custom parameters?

### ISSUE THREAD

**Issue by akorchev** [dotnet/templating#4572]
Is it possible to have array parameters? For example `dotnet new mytemplate -data "one" -data "two" -data "three"` and being able to loop through that parameter somehow and output its value:

In short I would like this file:
```
public static void Main(string[] args)
{
// foreach (var item in data) {
    Console.WriteLine("item");
// }
}
```

To become this:

```
public static void Main(string[] args)
{
    Console.WriteLine("one");
    Console.WriteLine("two");
    Console.WriteLine("three");
}
```

I know it probably isn't supported as "array" doesn't seem to be a supported `dataType` but is there some workaround? Perhaps parse parameter as JSON string? But how would the actual iteration in the source file happen?

**Comment by JanKrivanek** [comment]
Hello @akorchev - in your scenario, do you know all possible values of the `data` param up front?

We have 'multi-choice' parameters on our roadmap https://github.com/dotnet/templating/issues/4490
They should then allow you to specify multiple values for a single symbol. 'Looping' to generate output then might be achieved via [join](https://github.com/dotnet/templating/blob/main/docs/Available-Symbols-Generators.md#join) generator (that will be adjusted to support the multichoices as well).

This is though tailored to `choice` parameters - where the possible values are known up front (enum style parameters). In that case you might be able to simulate similar behavior with todays capabilities via set of boolean flag parameters (`dotnet new mytemplate -isOne true -isTwo true -isThree true`)

**Comment by akorchev** [comment]
Hi @JanKrivanek,

Thanks for the answer!

> do you know all possible values of the data param up front?
No, I don't. Also those parameters could be "complex" values (objects really). 

Could this happen by using the API directly somehow (multiple "object" parameters)? I

**Comment by JanKrivanek** [comment]
@akorchev Unfortunately multivalued or array style parameters are not supported in the engine as of today - so even dirrect API access won't help here.
I'm wondering if [custom script post action](https://github.com/dotnet/templating/blob/main/docs/Post-Action-Registry.md#run-script) might somehow help in your scenario. Otherwise it might help to learn a bit more about what you need to achieve.

**Comment by akorchev** [comment]
I want to generate code from an array parameter. It seems this isn't supported at the moment. Probably a different templating solution is required.
