### ISSUE TITLE
postActions scripts on Visual Studio

### ISSUE THREAD

**Issue by ekrem-c** [dotnet/templating#4575]
I have a template which I have two PostActions that runs PowerShell [scripts](https://github.com/dotnet/templating/wiki/Post-Action-Registry#run-script), and the scripts prompt me to run if I create a project using dotnet CLI ("dotnet new myTemplate -parameters"). 

I want to make this template compatible with Visual Studio. I am able to re-define parameters using ide.host.json file, and parameters seem to be shown fine in the "Create a new project" screen. However, my postActions never run or prompt the user to run when I create a new project using the custom template with Visual Studio. Is there any way to run postActions scripts upon new project creation with Visual Studio, whether by prompting the users or not?

**Comment by vlada-shubina** [comment]
@ekrem-c unfortunately post-action for running scripts in Visual Studio is not available at the moment, we already have an issue for that: https://github.com/dotnet/templating/issues/3226. Could you please follow that one? I am closing this as duplicate.

@sayedihashimi @phenning for visibility.

**Comment by sayedihashimi** [comment]
We do not have any plans to support custom scripts via `postActions` in Visual Studio. To have custom scripts executed you would need to create a VS extension and have that run your custom code.

**Comment by ekrem-c** [comment]
Hi @baronfel , thanks for the question! I have two powershell scripts that run consecutively. 

The first one pushes the newly created document to the Azure DevOps repository passed as template parameter, and creates a pull request. After the pull request creation, it busy-waits until it's completed. (pull request is not critical if impractical to implement)

After the PR is completed, the second script runs and creates a pipeline in Azure DevOps based on the azure-pipelines.yml file defined in the template, and then it runs the pipeline.
