### ISSUE TITLE
Suggestion: Add `WarningLevel` by default to dotnet templates

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/templating#4580]
Roslyn adds new warnings that can affect existing code under higher [warning levels](https://github.com/dotnet/roslyn/blob/main/docs/compilers/CSharp/Warnversion%20Warning%20Waves.md) for backward compatibility. I think for a brand new project, it should opt-in to higher warning levels by default.

For example, for .NET 7, we should have `<WarningLevel>7</WarningLevel>` in the templates (both produced by Visual Studio and by `dotnet` command line - I don't know if they share the same infrastructure).

**Comment by baronfel** [comment]
I think opting new projects into greater analysis is a great idea. Would you expect this to happen across every project template that ships in the project? Or just the default console/classlib projects? 

Thankfully VS and the CLI both use the same packages for their templates, it's just that those templates are scattered across different repositories (we've got a [table](https://github.com/dotnet/templating#template-content-repositories) of them in our README). So we could take care of the console/classlib templates here, but would either need to ask other repo owners to do similarly or send out a flood of tiny PRs ourselves to do so.

**Comment by baronfel** [comment]
Actually, this is already done [at the SDK level](https://github.com/dotnet/sdk/blob/7658805470f69b2c28eec3172e5c1bd31549928e/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Analyzers.targets#L72-L78), it just needs to be expanded for .NET 7.

**Comment by baronfel** [comment]
Closing this as it'll be handled in the SDK.
