### ISSUE TITLE
The `HostIdentifier` cannot be used in condition of the `switch`

### ISSUE THREAD

**Issue by KamenRiderKuuga** [dotnet/templating#4601]
When I use the `(HostIdentifier != \"dotnetcli\" && HostIdentifier != \"dotnetcli-preview\")`, it seems that it was not be correctly evaluated.

This is my template:
https://github.com/KamenRiderKuuga/ProjectForReproduce/tree/main/Template/Content

This is my `template.json`:

```json
{
  //...
  "symbols": {
    "HostIdentifier": {
      "type": "bind",
      "binding": "HostIdentifier"
    },
    "OriginalName": {
      "type": "generated",
      "generator": "switch",
      "replaces": ".API",
      "parameters": {
        "datatype": "string",
        "cases": [
          {
            "condition": "(HostIdentifier != \"dotnetcli\" && HostIdentifier != \"dotnetcli-preview\")",
            "value": ""
          },
          {
            "condition": "(HostIdentifier == \"dotnetcli\" || HostIdentifier == \"dotnetcli-preview\")",
            "value": ".API"
          }
        ]
      }
    }
  },
  "sources": [
    {
      "source": "./",
      "target": "./",
      "condition": "(HostIdentifier == \"dotnetcli\" || HostIdentifier == \"dotnetcli-preview\")",
      "modifiers": [
        {
          "rename": {
            "SafeName.API.csproj": "SafeName.csproj"
          }
        }
      ]
    }
  ]
}
```

What I wanna do is removing the `.API`  when it is not generated by the dotnetcli, otherwise keep it.

Or is there any other way to replace according to conditions?

**Comment by vlada-shubina** [comment]
@KamenRiderKuuga thanks for the feedback. 

It's a nice catch as bind symbols are now evaluated after the generated symbols are processed.  This seems to be a bug. 
Before it is fixed, there is no way to make a condition on host similar to what you want unfortunately.
