### ISSUE TITLE
Add a provision to escape C# Preprocessor Directive statements within the template files

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/templating#4602]
Need a provision to escape C# Preprocessor Directives used within the template sources files.

As of now they're treated as part of template code and processed by the template engine itself than emitting it to the output.

Have tried add something like below:

```csharp
#if ANDROID
        // Code block for Android
#elif IOS
        // Code block for iOS
#elif MACCATALYST
        // Code block for Mac Catalyst
#elif WINDOWS
        // Code block for Windows
#endif
```

But they're getting processed by the templating engine itself and no relevant output is generated.

**Comment by vlada-shubina** [comment]
@egvijayanand please refer to https://github.com/dotnet/templating/wiki/Conditional-processing-and-comment-syntax#ignore-conditions-expressions-in-language-files on how to disable conditions processing.

**Comment by egvijayanand** [comment]
Hi @vlada-shubina,

Thanks for pointing to the link, it worked as expected.

This issue can be marked as resolved.

Regards,
Vijay Anand E G
