### ISSUE TITLE
For instantiating template, .template.config/template.json should not be included if template.json has source.exclude

### ISSUE THREAD

**Issue by GangWang01** [dotnet/templating#4642]
If template.json has source.exclude(similar to below), .template.config/template.json was created unexpectedly after instantiating a local project template.
```
{
  "$schema": http://json.schemastore.org/template,
  "author": "Me",
  "classifications": [ "repro" ],
  "identity": "ExampleTemplate.ReproProject",
  "name": "Example templates: repro .template.config/template.json is created while instantiating template",
  "shortName": "reproproject",
  "tags": {
    "language": "TypeScript",
    "type": "project"
  },
  "sources": [
    {
      "exclude": [ "**/tsconfig.json" ]
    }
  ]
}
```

**Comment by vlada-shubina** [comment]
By changing the behavior, we may break existing templates, especially those who override exclude to include `package.lock.json`. 
We discussed it before and though behavior is not ideal, we decided not to change it.
