### ISSUE TITLE
Implement validation of Template Choice Parameter values

### ISSUE THREAD

**Issue by baronfel** [dotnet/templating#4650]
It would be nice to expand our template validation MSBuild Tasks to validate that the values of Choice parameters are valid - meaning that they do not contain `|` or `,` characters so that they are valid for multi-selects (which use these characters as the delimiters).

This came out of discussions over https://github.com/dotnet/templating/issues/4490.

**Comment by vlada-shubina** [comment]
The error/warning should be shown if such template is attempted to be installed/instantiated, until we have MSBuild task for that.

**Comment by JanKrivanek** [comment]
This is now part of the template validation checks - those happen before template installation and instantiation.
We do not yet have the MSBuild validation task - once added (tracking epic: https://github.com/dotnet/templating/issues/2623), it will use the validation checks and hence the choices validation will automatically be aprt of it.
