### ISSUE TITLE
Visual Studio Host - Create new project/solution with template

### ISSUE THREAD

**Issue by croban** [dotnet/templating#4654]
This is more a question than an Issue.
Is there possibility to get/manipulate project create new wizard parameters?
<img width="726" alt="image" src="https://user-images.githubusercontent.com/7048578/166070373-636d5f9a-ca4b-4730-a0eb-d6dfc521c7c7.png">

or I have to create custom wizard for the template?
Basically what I want is to skip "create sln file" step done by VS automatically. Instead I would like to redirect VS to primaryOutputs.
Is there any solution for that at VS as Host?

**Comment by baronfel** [comment]
Paging @phenning for comment on that, as he's the guru on the VS Integration of the template engine.

**Comment by phenning** [comment]
The new  project dialog NET template creation flow which uses the template engine based templates will always create a solution file as the container for the created project. 

We do have the ability to gather parameters to be passed to the template on that next wizard page. 

Are you trying to create a multi project template, perhaps with a customized solution file? if so, @sayedihashimi has some good guidance in his template sample repro on template integration in Visual Studio.

**Comment by croban** [comment]
This is maybe more cosmetics stuff or even to much philosophically from my side. 

My template works and creates solution with multiple projects.
Just where the template is not same if created over cli or over vs.
CLI - I get following structure.
- docs
- src
  - name.sln <--- great exactly where I to have it
  - name.proj1
  - name.proj2
-tools

VS: I am getting this (if create in same dir):
- name.sln <--- inside root
- docs
- src
  - name.proj1
  - name.proj2
-tools

**Comment by sayedihashimi** [comment]
We don't have a good story for this today. We will need to hear a lot more feedback before proceeding. It's a lot of work to enable this and involves a few different teams. Currently we don't have the justification to push for this support. I know this isn't what you wanted to hear, but that is the best that we have today.

**Comment by croban** [comment]
Okay, I can live with the sln inside root folder just to be consistent.

**Comment by Skleni** [comment]
@sayedihashimi I just ran into the same problem and it took me a while to find out what is happening here. We really like the dotnet template engine and use it to generate more than just dotnet projects but everything we need for a new project:

* backend
  * Name.sln
  * Name.Project1
    * Name.project1.csproj
  * Name.Project2
    * Name.project2.csproj
* frontend
  * Angular project
* ci
  * azure-pipelines.yaml
* iac
  * some .bicep files

 It's working fine when using the CLI, so it's not that much of a problem, but it would be nice if it was possible to use VS without generating the extra .sln file at the root folder.

**Comment by sayedihashimi** [comment]
@Skleni since I posted that comment we have done a lot of work to improve the support for "solution templates". For more info see https://github.com/sayedihashimi/template-sample?tab=readme-ov-file#how-to-create-a-multi-project-solution-template. With that said, I'm not sure if we will have a good experience if the .sln file is in a sub-folder like you have above. @phenning what do you think, will the solution template support work with the .sln file being in a sub-folder like above?

**Comment by phenning** [comment]
No, this won't work.

Solution file support basically causes the template provided sln to merge with the VS generated sln (to bring in solution folders and the like), but the VS sln is the one that is loaded.

There is not currently a way for a template or our provider to suppress VS from generating a sln file prior to invoking our provider.
