### ISSUE TITLE
Update 2.0 templates

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/templating#466]
Get rid of `RuntimeFrameworkVersion`
Update packages to the latest versions

**Comment by livarcocc** [comment]
cc @nguerrera

**Comment by livarcocc** [comment]
We will also need a NuGet.Config to be dropped or will need the user to manually set it. For V1, for the long time we have the former. Maybe we should add it back.

**Comment by mlorbetske** [comment]
@livarcocc the 2.0 templates already drop a NuGet config - are you proposing that we add it to the 1.x ones as well?

**Comment by livarcocc** [comment]
No, no, not at all. I wasn't aware they were already there and wanted to make sure we did not forget it.

Great then.

**Comment by nguerrera** [comment]
NetStandardImplicitVersion should also be removed from the classlib template.
