### ISSUE TITLE
Refactoring: Remove Microsoft.TemplateEngine.Core dependencies on Microsoft.TemplateEngine.Abstractions

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/templating#4665]
Contracts between `Microsoft.TemplateEngine.Orchestrator.RunnableProjects` and `Microsoft.TemplateEngine.Core` are not meant to be exposed publicly. However some of the `Microsoft.TemplateEngine.Abstractions` contracts (that are exposed) are being used - this create risk of breaking changes when working on changes in communication between RunnableProjectGenerator and Core.

We should:
 * remove dependencies on `Microsoft.TemplateEngine.Abstractions` and `Microsoft.TemplateEngine.Utils`
 * copy over any interfaces into `Microsoft.TemplateEngine.Core.Contracts` if needed
 * review those dependencies and get rid of them alltogether if possible (instead of just duplicating)

As part of those changes we should make sure that `ITemplateParameter` changes for multichoice work (#4490) does not expose new parameter option `AllowQuotelessLiterals` to public abstractions (`ITemplateParameter`)

**Comment by YuliiaKovalova** [comment]
close as low priority.
