### ISSUE TITLE
Regular expression to limit the length of the parameter value

### ISSUE THREAD

**Issue by Krusty84** [dotnet/templating#4695]
Hello Dear Team,
Could you help me please,
I want to set maximum length (63 symbols) for the specific parameter:

...
```
"FunctionName": {
      "type": "parameter",
      "datatype": "text",
      "isRequired": true,
      "defaultValue": "bla-bla-bla-bla",
    },

    "regName": {
      "type": "generated",
      "generator": "regex",
      "datatype": "text",
      "replaces": "dummyFunctionName",
      "parameters": {
        "source": "FunctionName",
        "action": "replace",
        "steps": [
          {
            "regex": "^.{1,63}",
            "replacement": ""
          }
        ]
      }
    }

```
But it doesn't work:(

Thank you for any idea!

**Comment by GangWang01** [comment]
@Krusty84 I'm not sure what you want if the value of the parameter exceeds the maximum length. If you need to truncate the string after the maximum length, the regex can be `(?<=.{63}).{0,}` assuming the maximum length is 63.

**Comment by vlada-shubina** [comment]
Related: ability to validate parameter using regex: https://github.com/dotnet/templating/issues/2038

**Comment by Krusty84** [comment]
Dears @GangWang01 and @vlada-shubina, thank you for your support!
