### ISSUE TITLE
Enable persistent scope for ide for console template

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#4719]
Details for the change we need to make to the `ide.host.json` for each web project template, including the console template, in 7.0:

```json
{
  "id": "UseProgramMain",
  "isVisible": true,
  "PersistenceScope": "Shared",
  "PersistenceScopeName": "Microsoft"
}
```

@phenning is going to ensure that qnce we make this change in 7.0, any customer with both 6.x and 7.0 installed will see this option become sticky for all versions of the template available, i.e. it will become sticky in 6.x templates too.

/Cc @vlada-shubina

_Originally posted by @DamianEdwards in https://github.com/dotnet/aspnetcore/issues/41631#issuecomment-1124153234_

**Comment by baronfel** [comment]
That makes perfect sense to me. this option makes sense to be one of the 'sticky' ones.
