### ISSUE TITLE
Refactoring: internal parameters contract Core <-> Orchestrator

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/templating#4730]
`Microsoft.TemplateEngine.Core` and `Microsoft.TemplateEngine.Orchestrator.RunnableProjects` use `ITemplateParameter` and `IParameterSet` to exchange parameters. That is a public contract. There should be an extended contract in `Microsoft.TemplateEngine.Core.Contracts` that will allow Core and Orchestrator to be more agile in using additional information (e.g.: `EnableQuotelessIdentifiers`, [Conditional parameters](https://github.com/dotnet/templating/issues/4491) etc.) without exposing the additional features to public contract in `Microsoft.TemplateEngine.Abstractions`

**Comment by vlada-shubina** [comment]
Related: https://github.com/dotnet/templating/issues/3187

**Comment by YuliiaKovalova** [comment]
close as low priority.
