### ISSUE TITLE
Ability to explicitly unset choice with default value

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/templating#4737]
This is required for multi-choice parameters, but we'll keep the behavior unified with standard choice parameters.

We need to have ability to explicitly unset value for choice parameter (through API and CLI) and support proper template instantiation for this case.
This use case can become quite usual in VS after adding multiselect combobox for multi-choice parameters. It'll be prefilled with default options, but if user unselects all, the current behavior would consider this as valua not specified and default value would be applied - this is confusing and unacceptable behavior. Hence explicit unset needs to be supported.

Related to #4490

**Comment by vlada-shubina** [comment]
More info on this below:

## Working with parameters
`TemplateCreator.InstantiateAsync` method has template parameters collection as an input parameter. This collection has type `IReadOnlyDictionary<string, string?>`, where key is parameter name and value is parameter value. It allows `null` as value.
There might different cases when using this collection:
- the template parameter defined in the template is not present in collection. In this case, the default value of parameter or host default value is used unless template parameter is required.
- the template parameter is present in collection with `null` value. This case is very specific for CLI, and means that the user selected the parameter but didn't specify the value. In CLI this means specifying option without value, for example: `--framework`.
It is possible to define other than default value to be used in this case in template.json (default if option without value).
- the template parameter is present in collection with `string.Empty` value. This means that the user passed empty value for the parameter.
- the template parameter is present in collection with non-empty value. This means that the user passed non-empty value for the parameter.

In host implementations, the following applies:
|Case|CLI|VS (non-choice)|VS (choice)|
|---|---|---|---|
|the template parameter defined in the template is not present in collection|the user didn't specify the option when running the template|this case applicable to VS only in case parameter is hidden||
|the template parameter is present in collection with `null` value|case of option without value (`--framework`)|not applicable to VS||
|the template parameter is present in collection with `string.Empty` value.|`--framework ""`|The user kept value empty/removed default|For multi-value choice, the user unchecked all the values. Not applicable for single-value choice.|
|the template parameter is present in collection with non-empty value|`--framework net6.0` case|the user kept non-empty default value/specified non-empty default value|the user specified at least one value for choice parameters.|

### Issue with choice parameters
Choice parameters doesn't have a way at the moment to keep the value `empty` when default value is set, it would be replaced with default value on execution type/result in error.
The improvement to be made to allow to unselect default value, and in terms of API the caller will need to pass `string.Empty` as the value to this parameter when calling `InstantiateAsync`.
This feature will work for both single-value and multi-value choices. 
For single-value choice in VS it is assumed that it won't be used, as the control doesn't allow to unselect the value. For multi-choices it is assumed it will be used when the user unselects the value.
If such value is marked as required, it should still result in validation error (open for feedback here, for string parameters same situation will not result in validation error).
