### ISSUE TITLE
Little error in documentation about conditional processing in CSS files

### ISSUE THREAD

**Issue by Giuseppetm** [dotnet/templating#4739]
Hello,

looks like there is a little error in documentation about conditional processing about .css files.
https://github.com/dotnet/templating/wiki/Conditional-processing-and-comment-syntax#css-files
I tried, as the doc suggest:

```
/*#if (Condition)

[ css stuff .. ]

#endif*/
```
What happens is that the conditional processing works, but it doesn't seem to notice the `endif` that should close the conditionally processed code.

Using this syntax works fine instead (and is also similar to other examples on other type of files).
```
/*#if (Condition)*/

[ css stuff .. ]

/*#endif*/
```

**Comment by vlada-shubina** [comment]
We should check all the examples in https://github.com/dotnet/templating/wiki/Conditional-processing-and-comment-syntax and preferably add unit tests checking them.
