### ISSUE TITLE
Rename doesn't seem to work

### ISSUE THREAD

**Issue by tintoy** [dotnet/templating#474]
Hi.

I've tried building and running `dotnet-new3` from the `master` branch and, although it copies the file in question, it fails to rename it [in one of my templates](https://github.com/tintoy/dotnet-template-templates/blob/master/src/Templates/content/ProjectTemplate/.template.config/template.json#L32-L34).

BTW, I have to rename this file after copying because, if it's already called `template.json` then `dotnet new -i` will pick up the template content as another template to install (which isn't correct since this template is actually for creating new templates).

Given that I've _never_ seen this feature work correctly, I'm open to the idea that perhaps I'm just doing it wrong :wink:

Either way, any assistance would be greatly appreciated.

**Comment by mlorbetske** [comment]
IIRC, renames work on the path in the output they correspond to, so you'd probably need something along the lines of "./.template.config/_template.json": "./.template.config/template.json"

**Comment by tintoy** [comment]
Would it be worthwhile emitting a warning when a file that should be renamed cannot be found? At the moment it's kinda trial-and-error figuring out what went wrong...

**Comment by mlorbetske** [comment]
Agreed. We've been discussing for months which sets of information are relevant in the different contexts and how we should surface that information. We haven't really landed on a solid plan for this yet, but I'm thinking something along the lines of diagnostics streams will need to be added to the host interface, all "interesting" cases would be logged via the new methods and there'd be some mechanism for enabling/disabling/filtering the records logged.

@seancpeters

**Comment by tintoy** [comment]
BTW, tried the syntax specified above (rename using full paths) and it still doesn't work :-/

**Comment by tintoy** [comment]
Thanks @mlorbetske!

**Comment by mlorbetske** [comment]
Found the issue, checked in the fix & kicking off a new build

**Comment by mlorbetske** [comment]
Also, what you specified originally is the correct syntax

**Comment by tintoy** [comment]
Thanks - I'll pull down that branch and give it a go shortly.

**Comment by tintoy** [comment]
Hmm - the tip of that branch doesn't show any templates at all after clearing out `~/.templateengine` and running `dotnet new3 --list` for the first time. I'll have a play around and see if I can figure out why.

**Comment by mlorbetske** [comment]
I don't have my Ubuntu box or (shared) mac on me at the moment. If you're still running in to this by morning, let me know and I'll check it out on one of those machines

**Comment by tintoy** [comment]
Cheers - will do. I do know that on a mac the `setup.sh` script is trying to pass unsupported arguments to `sed` but I manually modified the `defaultinstall.*.list` files to point to the right place (also, `dotnet-new3` seems unhappy if either of those paths is a mix of `/` and `\`). This worked for `master` but not for `rel/vs2017/post-rtw` BTW.

I'll let you know what I find.
