### ISSUE TITLE
Empty line at the top of solution files

### ISSUE THREAD

**Issue by glen-84** [dotnet/templating#4777]
Is there a reason why there's an empty line at the top of [solution files](https://github.com/dotnet/templating/blob/ffb0930f86aebca016252d024c13f4e57f6697df/template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Solution/Solution1.sln)?

I found [this](https://stackoverflow.com/questions/2469662/about-the-leading-newline-in-visual-studio-solution-files) StackOverflow question, but it doesn't really answer the question.

Is this some weird legacy issue, and if so, can't it be put behind a flag like `dotnet new sln --legacy-formatting`?

**Comment by vlada-shubina** [comment]
@glen-84 is there any scenario which is broken by this? Thanks

**Comment by glen-84** [comment]
Not that I'm aware of (with or without the empty line). I'm just trying to understand why it's necessary, as it looks strange.

**Comment by sayedihashimi** [comment]
Solution files created by Visual Studio have the empty line as well. Doesn't seem like this is a Template Engine issue.

**Comment by sayedihashimi** [comment]
Best thing to do is to create a feedback item with Report a Problem https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022. The code that handles the .sln file is very old and brittle, so they may not be inclined to change this unless it’s blocking something.

**Comment by glen-84** [comment]
https://developercommunity.visualstudio.com/t/Empty-line-at-the-top-of-solution-files/10061064

Closed with no reply. 🙄
