### ISSUE TITLE
dotnet new command changes in net6.0

### ISSUE THREAD

**Issue by heng-liu** [dotnet/templating#4825]
### Describe the bug
There are few dotnet new command works in .NET 5 but fails in .NET 6.

### To Reproduce

1. Install .NET 5 SDK and .NET 6 SDK(6.0.300) in different paths with no path, then set DOTNET_MULTILEVEL_LOOKUP=0, and invoke them separately
2. Template reactredux disappears from .NET 6 if running `dotnet new --list` command. But [doc](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new-sdk-templates#reactredux) doesn't mention this change.
```
C:\net5\dotnet.exe new reactredux
The template "ASP.NET Core with React.js and Redux" was created successfully.
C:\net6\dotnet.exe new reactredux -n reactredux1
No templates found matching: 'reactredux'.
```
3. Template solution could not use `solution `anymore, only `sln `works.
```
C:\net5\dotnet.exe new solution -n Solution1
The template "Solution File" was created successfully.
C:\net6\dotnet.exe new solution -n Solution2
No templates found matching: 'solution'.
```

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by vlada-shubina** [comment]
This is by design. Starting .NET 6.0 it is only possible to use exact 'short name' to instantiate template. For solution template, the only short name is `sln`. 
Partial name or short name matching led to much confusion. This was implemented in https://github.com/dotnet/templating/issues/3113. 

We may add the alternative short name `solution` to this template though. @baronfel thoughts?

**Comment by baronfel** [comment]
@vlada-shubina adding the additional name makes sense here 👍

**Comment by vlada-shubina** [comment]
> Thanks @vlada-shubina ! May I know if Template **reactredux** is removed from .NET 6?

I do not see this template in .NET SDK 6.0.3xx. You may check in https://github.com/dotnet/spa-templates/ what is the status for this template.
