### ISSUE TITLE
Enabling the -n option to create a directory

### ISSUE THREAD

**Issue by alfonsogarciacaro** [dotnet/templating#487]
Hi there! I've created [a template for Fable projects](https://github.com/fable-compiler/Fable/tree/narumi/src/templates/simple) following [this tutorial](http://pioneercode.com/post/how-to-create-a-dot-net-new-project-template-in-dot-net-core). The template is working fine but it's always creating the files in the current directory, even when I add the argument `-n` like `dotnet new fable -n myproject`.

What's needed to make the `-n` argument create a new directory and put the template files there? Thanks a lot for your help in advance!

cc @mlorbetske @enricosada

**Comment by mlorbetske** [comment]
The property you'll want to set is called `perferNameDirectory` ([example](https://github.com/dotnet/templating/blob/rel/vs2017/post-rtw/template_feed/Microsoft.DotNet.Web.ProjectTemplates.1.x/content/EmptyWeb-CSharp/.template.config/template.json#L15))

**Comment by alfonsogarciacaro** [comment]
Thanks @mlorbetske, it's working :+1: Actually @enricosada had already suggested that but I mistakenly believed this option just used the name of the current directory to name the project as in `mkdir myproj && cd myproj && dotnet new fable`.

Hopefully the docs for the templates will be improved soon to avoid confusions like this ;)
