### ISSUE TITLE
BadPackageSpec Errors on the very first use of `new3` on Mac OS X

### ISSUE THREAD

**Issue by peterblazejewicz** [dotnet/templating#488]
I've installed local version of the tool on Mac OS Sierra and have no problem during install.
On the very first use of the cli tool I've got this errors:
```bash
dotnet new3 -all
Getting ready...
Error: Package "%DN3%\..\artifacts\packages" is not a valid package specification.
Error: Package "%DN3%\..\template_feed\" is not a valid package specification.
Template Instantiation Commands for .NET Core CLI
....
```
Something similar to cases here:
https://github.com/dotnet/templating/blob/0aab536d22afeeda918bc78190bf649f0e4fb685/src/Microsoft.TemplateEngine.Cli/Installer.cs#L138-L143

The list of templates for `new3` is empty:
```bash
dotnet new3 --list
Template Instantiation Commands for .NET Core CLI

Usage: dotnet new3 [arguments] [options]

Arguments:
  template  The template to instantiate.

Options:
  -l|--list         Lists templates containing the specified name. If no name is specified, lists all templates.
  -lang|--language  Specifies the language of the template to create.
  -n|--name         The name for the output being created. If no name is specified, the name of the current directory is used.
  -o|--output       Location to place the generated output.
  -h|--help         Displays help for this command.
  --type            Shows a subset of the available templates. Valid values are "project", "item" or "other".
  --force           Forces content to be generated even if it would change existing files.
  --allow-scripts   Specify if post action scripts should run.


Templates      Short Name      Language      Tags
-------------------------------------------------
```
The `dotnet new --list` returns on the other hand:
```
Templates          Short Name       Language      Tags    
----------------------------------------------------------
Nuget Config       nugetconfig                    Config  
Web Config         webconfig                      Config  
Solution File      sln                            Solution
```
Dotnet info:
https://github.com/dotnet/cli/releases/tag/v1.0.1
```bash
dotnet --info
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1
```

**Comment by chad-ramos** [comment]
When you run the "setup" script it attempts to build/install the "template Nuget packages" from the  `..\template_feed` directory.  My current understanding is that because there is a dependency on Nuget.exe to do such, this part of the build is Windows only,

If you want to "install" the default templates, you would need to acquire them from an alternative source. 

That being said, the "error" you provided can be argued to be inaccurate in context.  One might say it is not an error at all if the understanding is that this part of the build is platform specific.

```
Error: Package "%DN3%\..\artifacts\packages" is not a valid package specification.
Error: Package "%DN3%\..\template_feed\" is not a valid package specification.
```

Might it be better it is a warning instead of an error?

**Comment by peterblazejewicz** [comment]
> If you want to "install" the default templates, you would need to acquire them from an alternative source.

I've just want to contribute to the repo content, while I have only Mac OS X based machine.  I doubt I'll use Win/PC machine for this.

@mlorbetske
Mike. You're nearly there with OS X setup. Where should I look for hints if I want to help?

**Comment by mlorbetske** [comment]
@chad-ramos the message itself is just bad, it effectively means "I don't know how to locate something to install in the way you've indicated to find it" - I'll try to get some new wording worked up.

@peterblazejewicz for the time being, changing the backslashes to forward slashes (in `src/dotnet-new3/defaultinstall.package.list` and `src/dotnet-new3/defaultinstall.template.list`) should get you past those errors. For the difference you're seeing between `new` and `new3` - that's actually good, it means that the "preview" and "release" flavors of the CLI aren't interfering with eachother.

@seancpeters in case you get to it first - we should change first run for new3 to not use the list files and instead just look for the template & component feeds relative to one of the assembly locations on disk & then fix the string that says a particular path isn't a valid package.

**Comment by peterblazejewicz** [comment]
Thanks!
