### ISSUE TITLE
ability to extract new search cache data without bumping the api

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#4884]
For future extensions and usages - is there an easy way to add ability to extract new search cache data without bumping the api? Something like: `string? PackageInfo.GetProperty(string propertyName)`

_Originally posted by @JanKrivanek in https://github.com/dotnet/templating/pull/4870#pullrequestreview-1013256443_

**Comment by YuliiaKovalova** [comment]
Close as low priority.

If this feature is needed as a part of the template search in VS, it can be reopened.
