### ISSUE TITLE
Lead to `dotnet new create <template name>`

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#4895]
Currently `dotnet new create` subcommand is hidden. 
In case the template matches subcommand name (list, install, uninstall) the only way to instantiate it is using `dotnet new create`.

Consider creating the lead to the scenario

Some considerations:
- make `create` subcommand visible in help
- allow this scenario via tab completion when conflict exists
- create the lead from subcommand in case the template with same short name exists (example: when running `dotnet new list` and `list` template is available, show note similar to: `To run template with short-name 'list', use dotnet new create list`.

**Comment by JanKrivanek** [comment]
Should we consider blacklisting top level commands from allowed template names/shortnames?

**Comment by vlada-shubina** [comment]
> Should we consider blacklisting top level commands from allowed template names/shortnames?

Added to: https://github.com/dotnet/templating/issues/3828
