### ISSUE TITLE
Use top level statements does not have an accelerator key in display name for Visual Studio

### ISSUE THREAD

**Issue by phenning** [dotnet/templating#4961]
From https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1576097/

![image](https://user-images.githubusercontent.com/2433750/178797140-736a5f64-b799-4b8c-a4df-a87690a5e817.png)

**Comment by vlada-shubina** [comment]
Display name is only used in VS for now. We can add underscore if needed, however in the future we might need other way. 
https://github.com/dotnet/templating/issues/3340 might help

**Comment by vlada-shubina** [comment]
I lack experience a bit: is accelerator usually localized? For example Chinese version is `不使用顶级语句`. Should it be `_不使用顶级语句` then?

**Comment by phenning** [comment]
No what would happen is that the localizers would normally do something like 不使用顶级语句 (_C).

See https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/.template.config/localize/templatestrings.zh-Hans.json

![image](https://user-images.githubusercontent.com/2433750/179007126-763d2086-0e2a-44b1-9906-8e580739bc73.png)

**Comment by vlada-shubina** [comment]
@phenning is there any guideline which word or letter to use as accelerator? 
Likely I also need to add it to `template.json` as it would be used as the fallback, also I'm not sure if translators adapt English version.

**Comment by phenning** [comment]
I think as long as we make a good effort to not conflict with any already existing accelerators, we should be good. I was thinking 'T" for top level statements might work, Since ASP.NET templates also have this parameter, we should just make sure that they are no using the T accelerator for any of their other options in any other template.

@DamianEdwards, FYI, since I opened a bug in aspnet repo about this as well.

**Comment by vlada-shubina** [comment]
@DamianEdwards please confirm which key to use as accelerator. This is the only parameter visible for console, so there should be no clashes at our end.

**Comment by DamianEdwards** [comment]
Happy to let you all decide based on what makes sense in VS. @sayedihashimi?

**Comment by sayedihashimi** [comment]
Phil's suggestion of using `T` works for me.
