### ISSUE TITLE
Update the C++ evaluator to not require paren matching for end detection

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/templating#51]
The general purpose expression evaluator should be used for this as well - bitwise operators & value comparisons will need to be introduced

**Comment by mlorbetske** [comment]
The current issue here (blocking wholesale adoption of Cpp2StyleEvaluatorDefinition.cs) is that it currently fails to appropriately detect condition ends in markup languages in cases where the markup closing tags are also valid operators/operands in the evaluation language.

Ex.
`<!--#if (TEST) -->` will produces a tree like `(((Identity(TRUE) minus ()) minus ()) greaterThan ())`

Ex2.
`@* #if (TEST) *@` will produces a tree like `(Identity(TRUE) multiply '@')`

**Comment by grinrag** [comment]
This bug is outdated (original date is Sep 2016), closing it now. Feel free reopen if it still valid.
