### ISSUE TITLE
(Feature Request) WebApi Authentication

### ISSUE THREAD

**Issue by livarcocc** [dotnet/templating#511]
_From @dansiegel on March 29, 2017 3:49_

`dotnet new webapi -au Individual` should create a new web api project scaffolded with individual authentication just like `dotnet new mvc -au Individual` currently does, only without all of the MVC Views.

_Copied from original issue: dotnet/cli#6185_

**Comment by mlorbetske** [comment]
Great suggestion! We're getting ready to add more auth options to the templates in the coming week.

**Comment by sayedihashimi** [comment]
If we add the help pages to the api template, that should be made into an option so that people can opt in if they want for those pages.

**Comment by mlorbetske** [comment]
#528 added org auth and windows auth options to WebAPI (and MVC). Individual user accounts is not there yet, but I imagine we'll be thinking about that content soon.

**Comment by dansiegel** [comment]
@mlorbetske that's a great add. With my work flow I tend to use use the Individual user accounts way more than org and windows auth.

**Comment by mlorbetske** [comment]
This has been added with #700
