### ISSUE TITLE
ProcessStartPostAction documentation and samples

### ISSUE THREAD

**Issue by MarcinJuraszek** [dotnet/templating#523]
I'm trying to use `ProcessStartPostAction` to run a PowerShell script after the template is copied and am missing some key information to make that possible:
- what is the path context the action runs on? Is it relative to the template, the output directory, the place where `dotnet new` was called? I want to run `powershell.exe` and provide it with path to the script file, but I can't figure out what that path should look like.
- can you disable the prompt from template.json and not rely on user to provide `--allow-scripts` when calling `dotnet new`?

It would be great to have a sample where a batch or PowerShell script is called as PostAction step in the repo itself or in the wiki.

**Comment by MarcinJuraszek** [comment]
After further investigations it looks like the script will run in the context of where the project was created.

**Comment by mlorbetske** [comment]
I'll add this to the docs, thanks for bringing it to our attention that we didn't really define this

**Comment by mlorbetske** [comment]
I've added the additional information in the [docs for post-actions](https://github.com/dotnet/templating/wiki/Post-Action-Registry#run-script). Thanks again!

**Comment by MarcinJuraszek** [comment]
Thanks, @mlorbetske!
