### ISSUE TITLE
Force copyOnly of excluded file types e.g. .nupkg

### ISSUE THREAD

**Issue by nathanwinder** [dotnet/templating#5272]
I have a template that uses copyOnly to copy the contents of a directory which contains *.nupkg files. The template engine automatically excludes .nupkg files. Is there a way to either force copyOnly to copy all contents or remove the .nupkg restriction. I could do a rename, but that adds additional complexity since the version number on the .nupkg changes and would require an update to the template on every change.

```
{
    "source": "./",
    "target": "./",
    "condition": "isApp",
    "exclude": [
      "**/NewServiceNameService/**",
      "**/DependencyInjection/NewServiceNameServiceModule.cs",
      ".padm/new-service-post-actions.cmd",
      ".padm/new-page-post-actions.cmd",
      "presentation/src/**/*.gen.ts",
      "**/.template.config/**"
    ],
    "rename": {
      "presentation/_env": "presentation/.env",
      "_gitignore": ".gitignore"
    },
    "copyOnly": [
      "./Analyzers/**/*"
    ]
},
```

**Comment by JanKrivanek** [comment]
Hello @nathanwinder - can you help us understanding your issue by providing a complete sample?
I'm wondering whether there might be any other part of your config that is preventing the copy.

*.nupkg files are not excluded by default (see [Source definition](https://github.com/dotnet/templating/blob/main/docs/Reference-for-template.json.md#source-definition)). I tried to copy your `sources` defintion (with and without the condition) to a simple console template, while adding a nuget package file into the template - and the package is being copied.

An unrelated topic is a motivation for including nugets into templates and copying them during instantiation - better practise would be to publish the package to some feed (nuget.org or your company internal feed, if needed nuget.config), optionally add `nuget.config` to your template if needed and let the template users pull the reference during the resolve step of the build

**Comment by vlada-shubina** [comment]
@nathanwinder which dotnet version are you at? (please share output of `dotnet --info`) 
Thank you.

**Comment by nathanwinder** [comment]
@vlada-shubina 
```
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400\

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.423 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  5.0.411 [C:\Program Files\dotnet\sdk]
  6.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

**Comment by nathanwinder** [comment]
Here is the resulting `.nupkg` renamed to `.zip`

[Test.0.0.0.zip](https://github.com/dotnet/templating/files/9618025/Test.0.0.0.zip)

**Comment by vlada-shubina** [comment]
@nathanwinder I cannot reproduce your issue at 6.0.4xx unfortunately.
After running your template on 6.0.4xx I got the following files in the output:
- .env
- test.nupkg
- test.txt

Is it what is expected?
The last package attached doesn't have the ` test.nupkg` and ` .env` inside your NuGet. Of course, they won't be created during template instantiation because they were not packed. `dotnet pack` won't include `nupkg` files by default. To include them, `NoDefaultExcludes` property should be set to to true.

```
warning NU5119: File 'Test\Test\.env' was not added to the package. Files and folders starting with '.' or ending with '.nupkg' are excluded by default. To include this file, use -NoDefaultExcludes from the commandline 
warning NU5119: File '\Test\Test\test.nupkg' was not added to the package. Files and
 folders starting with '.' or ending with '.nupkg' are excluded by default. To include this file, use -NoDefaultExclude
s from the commandline
```

**Comment by nathanwinder** [comment]
OK yes, that solves this issue. It seems it's not a templating issue but rather a product of the nuget packing process. BTW, the `-NoDefaultExcludes` flag does not work with `dotnet pack`.

You need set a property in the `.csproj` or at the command line: 

`<NoDefaultExcludes>true</NoDefaultExcludes>`
or
`dotnet pack test.csproj -v d /p:NoDefaultExcludes=true`


Thank you for your help!
