### ISSUE TITLE
Templates fail to create with .NET 7 RC

### ISSUE THREAD

**Issue by normj** [dotnet/templating#5300]
I am the main author of the [Amazon.Lambda.Templates](https://www.nuget.org/packages/Amazon.Lambda.Templates) NuGet package. This is a not a new package, it has existed since the beginning of the `dotnet new` templating.

We haven't made any significant changes and with .NET 6 everything works fine. With .NET 7 RC installed we get the following error when creating projects from the templates.

```
> dotnet new lambda.EmptyFunction -o TestT
Template "Lambda Empty Function" could not be created.
Failed to create template.
Details: Object reference not set to an instance of an object.


For details on the exit code, refer to https://aka.ms/templating-exit-codes#100
```

Creating projects from the `console` template works just fine.

I'm not sure how to go about debugging this error. Is there extra logging I can turn on or something?

**Comment by vlada-shubina** [comment]
@normj we are aware of this issue, and it was fixed in https://github.com/dotnet/templating/commit/3c6a6e1c8bc24b247d520c7734b90303844c1a41. 

Though it was clearly not correct handling on template engine side, we don't recommend to use this workaround anymore:
```
    "safe-sourcename": {
      "type": "generated",
      "generator": "coalesce",
      "parameters": {
        "sourceVariableName": "safe_namespace",
        "fallbackVariableName": "safe_name"
      },
      "replaces": "SourceName._1"
    }
```

Neither `safe_namespace`, nor `safe_name` are not available since .NET Core 1.x, therefore this macro basically does nothing, and .NET 1.x is far eol.

**Comment by normj** [comment]
Thanks @vlada-shubina! Since our package is so old I figured we were using something deprecated. Sounds like all I need to do is remove the `safe-sourcename` section since the templating now automatically handles making the names safe depending on if it is being used in code or a file name on disk.

**Comment by vlada-shubina** [comment]
Closing, already fixed in https://github.com/dotnet/templating/commit/3c6a6e1c8bc24b247d520c7734b90303844c1a41.
