### ISSUE TITLE
Parameters passed via API are now case sensitive.

### ISSUE THREAD

**Issue by phenning** [dotnet/templating#5334]
See internal AZDO bug 1633125.

If a template has a parameter defined like MyAwesomeParameter, but we pass in myawesomeparameter into InstantiateAsync's parameter dictionary, the template uses the default parameter value rather than the passed value.

Looks like the issue is in the following code. The dictionary should be created with StringComparision.OrdinalIgnoreCase. 

https://github.com/dotnet/templating/blob/a7e4062183641655b08aa5bde3f01f314e8cff8c/src/Microsoft.TemplateEngine.Edge/Template/InputDataSet.cs#L46

**Comment by JanKrivanek** [comment]
The fix has been merged and is part of `Microsoft.TemplatingEngine.Edge` from version `7.0.100-rtm.22504.5` and up
