### ISSUE TITLE
Running `dotnet new blazor` doesn't suggest any of the Blazor templates

### ISSUE THREAD

**Issue by danroth27** [dotnet/templating#5531]
If I run `dotnet new blazor` I probably want the `blazorserver` or maybe the `blazorwasm` template, but instead I get a suggestion to use a template unrelated to Blazor:

```console
C:\> dotnet new blazor
No templates or subcommands found matching: 'blazor'.
Did you mean one of the following templates?
   dotnet new razor

To list installed templates similar to 'blazor', run:
   dotnet new list blazor
To search for the templates on NuGet.org, run:
   dotnet new search blazor
```

Can we improve the matching to suggest the Blazor templates?

**Comment by vlada-shubina** [comment]
proposed strategy:
- do 'contains' matching and sort those matches by the 'distance - length of search token', then
- add the normal levenstein-based matches afterwards
