### ISSUE TITLE
Dotnet new install is not picking up sub dirs

### ISSUE THREAD

**Issue by leastprivilege** [dotnet/templating#558]
When I run dotnet new install on this directory:

https://github.com/IdentityServer/IdentityServer4.Templates/tree/dev/src

It only add the first directory to the templates list (IdentityServer4Basic). If I explicitly run dotnet new install twice for both directories - both templates are added.

My understanding was that install searches sub-dirs. Am I missing something?

**Comment by mlorbetske** [comment]
Yep, it's supposed to traverse subdirectories when scanning for content to install. Having a bit of trouble repro-ing this, I recall a while back that there was an issue where some content was missed in local installs unless the path had a trailing slash - if you haven't already, I'd try that. The latest engine (the one that can be built from `master` or `rel/vs2017/post-rtw` doesn't have this issue).

**Comment by leastprivilege** [comment]
Same happens in the nuget package - see #558

**Comment by mlorbetske** [comment]
This should be fixed with the solution in #559, closing this one

**Comment by RehanSaeed** [comment]
I'm having the same issue. Did the fix go out in 2.0 or do we have to wait for 2.1?

**Comment by mlorbetske** [comment]
@RehabSaeed would you be able to open a new issue with your repro steps please? I believe this fix was in the template content and not something that went in to this repo, but it’s been quite a while and will be easier to investigate fresh.

**Comment by RehanSaeed** [comment]
Seems to work with 2.1, so I'm happy.
