### ISSUE TITLE
Nuget package authoring

### ISSUE THREAD

**Issue by leastprivilege** [dotnet/templating#559]
I created a nuget package for our templates

https://www.nuget.org/packages/IdentityServer4.Templates/1.0.0-aberfeldy

nuspec is here:
https://github.com/IdentityServer/IdentityServer4.Templates/blob/dev/feed/IdentityServer4.Templates.nuspec

When I do 

dotnet new -i identityserver4.templates::*

I get 

Errors in C:\Users\dominick\.templateengine\dotnetcli\v1.0.2\scratch\restore.csproj
    Unable to resolve 'identityserver4.templates' for '.NETCoreApp,Version=v1.0'.

What does that mean?

**Comment by mlorbetske** [comment]
@leastprivilege this, unfortunately, seems to be a bug with the way we interact with NuGet to retrieve the packages (we generate a csproj behind the scenes with the package referenced in it, restore the project and inspect what got installed). For prerelease packages, you need to include at least one digit of the version number. `dotnet new -i identityserver4.templates::1-*` seems to be working for me. For packages not marked as pre-release, the command line you mentioned should work just fine.

**Comment by leastprivilege** [comment]
Thanks - that works for me as well.

But now I have the same problem that I described in #558 

Only the first template gets added - the 2nd is not showing up in the list.

Could you have a quick look what might be wrong? TIA

**Comment by mlorbetske** [comment]
Found the issue for this and #558. This is from a bug that's fixed in the upcoming release where templates without a `groupIdentity` set all "unify" in the list (as they all belong to the same template group `null`).

Here are the template.json files with the fix (just added groupIdentity):

```
{
  "author": "Dominick Baier",
  "classifications": [
    "Web"
  ],
  "name": "Basic IdentityServer4 with UI and test users",
  "identity": "IdentityServer4.UI",
  "groupIdentity": "IdentityServer4.UI",
  "shortName": "is4basicui",
  "tags": {
    "language": "C#"
  },
  "sourceName": "IdentityServer4UI",
  "preferNameDirectory": "true"
}
```

and

```
{
  "author": "Dominick Baier",
  "classifications": [
    "Web"
  ],
  "name": "Basic IdentityServer4",
  "identity": "IdentityServer4.Basic",
  "groupIdentity": "IdentityServer4.Basic",
  "shortName": "is4basic",
  "tags": {
    "language": "C#"
  },
  "sourceName": "IdentityServer4Basic",
  "preferNameDirectory": "true"
}
```

**Comment by leastprivilege** [comment]
Thanks - will give it a try.

**Comment by mlorbetske** [comment]
Closing this from the follow up over e-mail where it was stated that this is not blocking anymore.

**Comment by leastprivilege** [comment]
Yep - working now. Thanks!
