### ISSUE TITLE
Duplication across multiple templates

### ISSUE THREAD

**Issue by ideahitme-twin** [dotnet/templating#5635]
Feel free to close this issue if it has been raised before (I could not find anything similar though)

Imagine the following situation: 

I am in charge of maintaining all the custom .NET core templates for my company. Primarily used for generating .NET projects. All of the templates are sufficiently different, so each is defined in its separate directory. So something like: 

```
/my-templates-repo
    /templates
         /http-app-template
            .template.config/
         /grpc-app-template
             .template.config/
```

So far so good. Now each template has a lot of identical and "nearly" identical files. For example, .editorconfig file will be identical in each template. Github CI definition will be nearly identical (a lot of duplication but some stages are different). 

Now if you multiply the number of templates by ten - it gets really tricky to maintain all of those files. How is one supposed to solve this issue when using .NET core templates ? 

In yeoman this can be solved by having a generator that "composes with" generators for .editorconfig and Github CI files. In cookiecutter/jinja2 it could be done via template inheritance. 

One way I could think of here - is to use "Item templates". But it is somewhat awkward, because now generating a complete project will require either:
* asking users to run two commands (dotnet new for the project template and for the item template)
* inventing a middle layer (e.g. shell script which will abstact away dotnet new)
Both ways are not ideal

Any advice is appreciated and thanks for all the good work!

**Comment by vlada-shubina** [comment]
@ideahitme-twin it seems duplicate or at least very similar to https://github.com/dotnet/templating/issues/2771 
could you please track that one instead? If you think that it is different, please feel free to comment why and we will reopen this one. Thanks.
