### ISSUE TITLE
Conditional parameters are not processed correctly in certain cases

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#5647]
Test cases that are failing at the moment:
https://github.com/dotnet/sdk/blob/64aaea464653b3834b016cd08e4a0a41bc797eff/src/Tests/dotnet-new.Tests/DotnetNewInstantiateTests.Approval.cs#L738
https://github.com/dotnet/sdk/blob/64aaea464653b3834b016cd08e4a0a41bc797eff/src/Tests/dotnet-new.Tests/DotnetNewInstantiateTests.Approval.cs#L689

Even if the failure is expected, the error message is not appropriate (cannot add item to a dictionary).

Related or unrelated to this, the following syntax doesn't work
```json
  "symbols": {
    "A": {
      "type": "parameter",
      "datatype": "bool",
      "isEnabled": "B",
      "defaultValue": false
    },
    "B": {
      "type": "parameter",
      "datatype": "bool",
    }
}

```

`> dotnet new template ` and  `> dotnet new template  --B` and fails in this case, as the template engine fails to evaluate `B` as the valid condition.
The issue is not reproduced when:
- using `> dotnet new template  --B true|false`
- using `defaultValue` for parameter `B`.

Additionally: 
https://github.com/dotnet/sdk/blob/69fd7b4a0e43d290ea8c3bcca6d14b53df50ebd6/src/Cli/Microsoft.TemplateEngine.Cli/TemplateInvoker.cs#L210-L211
there were 2 cases that were not handled before - verify if needs the separate processing.

**Comment by JanKrivanek** [comment]
We should likely update all documentation samples to use `B == true` condition instead. The `B` currently behaves as authoring error in condition

**Comment by JanKrivanek** [comment]
Needs to be flown to sdk as well and commented tests uncometed there
