### ISSUE TITLE
conditional parameter- hide/show fields depending on, what user selects

### ISSUE THREAD

**Issue by s19946** [dotnet/templating#5648]
Is it possible to hide/show fields depending on, what a user selects from the dropdown field in the template? 
Let's say I have a dropdown with the options: "A", "B", "C".  If user selects "A", then it shows up a text field below: "Text1",
if user selects "B", then it shows up a different text field below: "Text2" and some checkbox(bool), if "C" nothing happened.
Depending on, what user wrote/selected, different files would show up after creating a new template .

"symbols": {
    "Letter": {
      "type": "parameter",
      "datatype": "choice",
      "choices": [
        {
          "choice": "A"
        },
        {
          "choice": "B"
        },
        {
          "choice": "C"
        },
   "Text1": {
      "type": "parameter",
      "datatype": "text",
    },
    "Text2": {
      "type": "parameter",
      "datatype": "text",
    },
    "Checkbox": {
      "type": "parameter"
       "datatype": "bool"
    },     
}

**Comment by s19946** [comment]
@vlada-shubina  

`"symbols": {
	"Letter": {
	"type": "parameter",
	"datatype": "choice",
	"choices": [
			{
			"choice": "A"
			},
			{
			"choice": "B"
			},
			{
			"choice": "C"
			}
		]
	},
	"Text1": {
		"type": "parameter",
		"datatype": "text",
		"isEnabled": "Letter == A"
	},
	"Text2": {
		"type": "parameter",
		"datatype": "text",
		"isEnabled": "Letter == B"
	},
	"Checkbox": {
		"type": "parameter"
		"datatype": "bool",
		"isEnabled": "Letter == B"
	},
}`

**Comment by s19946** [comment]
@vlada-shubina thanks, should I use "isEnabled" to control field visibility? I tried something like below code, but the fields are still visible, no matter what choice I select
```
"symbols": {
	"Letter": {
	"type": "parameter",
	"datatype": "choice",
	"choices": [
			{
			"choice": "A"
			},
			{
			"choice": "B"
			},
			{
			"choice": "C"
			}
		]
	},
	"Text1": {
		"type": "parameter",
		"datatype": "text",
		"isEnabled": "Letter == A"
	},
	"Text2": {
		"type": "parameter",
		"datatype": "text",
		"isEnabled": "Letter == B"
	},
	"Checkbox": {
		"type": "parameter"
		"datatype": "bool",
		"isEnabled": "Letter == B"
	},
}
```

**Comment by vlada-shubina** [comment]
@s19946 `isEnabled` is correct flag to use.

Assuming you are testing it in Visual Studio, but the support for this feature is not implemented in Visual Studio yet. 
It is only available for .NET SDK (`dotnet new`) at this point. 

I'll keep the issue open to track the feedback on the feature.

**Comment by YuliiaKovalova** [comment]
The relevant issue was created on the [developercommunity](https://developercommunity.visualstudio.com/t/conditional-parameter--hideshow-fields-/10254783).
You can track the state there.

**Comment by sacalata** [comment]
Still not supported on Visual Studio 2022, is this being tracked anywhere?
