### ISSUE TITLE
add string value transform sample

### ISSUE THREAD

**Issue by milanjaros** [dotnet/templating#5651]
Temporarily unarchive the `dotnet-template-samples` repository, please.
I would like to create a pull request with a new sample.

[The sample ](https://github.com/dotnet/dotnet-template-samples/compare/master...milanjaros:dotnet-template-samples:master) demonstrates the usage of `forms` (`ValueForms`) to generate PascalCase, camelCase and kebab-case value. There is also the usage of Regex replacing and chaining of value forms.

When I developed a custom template, I found samples very handy, but I needed to use the value forms to achieve more complex string manipulations. I could not find relevant examples anywhere (note, there is no sample using `valueTransform`), so I was forced to study them from the code. Please, let me extend the documentation this way.

**Comment by vlada-shubina** [comment]
@milanjaros Unfortunately this is not possible. We have https://github.com/dotnet/templating/issues/2522 opened for this.
At the moment the only viable solution is to move examples to dotnet/templating. We can include your PR when moving examples.

**Comment by vlada-shubina** [comment]
@milanjaros we moved the examples to https://github.com/dotnet/templating/tree/main/dotnet-template-samples

could you please redirect your PR there? Thank you.

**Comment by milanjaros** [comment]
@vlada-shubina, I have just created a new PR. Thank you.
