### ISSUE TITLE
Reenable `Signing Validation` step in pipeline

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#5661]
Revert the following PRs:
https://github.com/dotnet/templating/pull/5658
https://github.com/dotnet/templating/pull/5657

**Comment by vlada-shubina** [comment]
Blocked by: https://github.com/dotnet/arcade/issues/11724

**Comment by YuliiaKovalova** [comment]
The issue wasn't resolved for 7.0.1 branch
the PR was reverted for unblocking servicing 
https://github.com/dotnet/templating/pull/5878

**Comment by GangWang01** [comment]
Close as it was done.
