### ISSUE TITLE
Unexpected Internal Software Issue (EX_SOFTWARE)

### ISSUE THREAD

**Issue by ynanech** [dotnet/templating#5664]
Upgrade Exception after net 7，But I stepped back Net 6 Everything is OK

![image](https://user-images.githubusercontent.com/20282409/203543834-e0752cfc-3003-46e6-8a0d-2fb2556f76fd.png)

This is the template variable I defined：
`"symbols": {
    "Title": {
      "type": "parameter",
      "datatype": "text",
      "defaultValue": "TemplateTitle",
      "replaces": "TemplateTitle"
    },
    "EnableMall": {
      "type": "parameter",
      "dataType": "bool",
      "defaultValue": "false"
    },
    "EnableVideo": {
      "type": "parameter",
      "dataType": "bool",
      "defaultValue": "false"
    },
    "EnableChat": { 
      "type": "parameter",
      "dataType": "bool",
      "defaultValue": "false"
    },
    "EnableFileService": { 
      "type": "parameter",
      "dataType": "bool",
      "defaultValue": "false"
    }
  }`

**Comment by vlada-shubina** [comment]
Thank you for reporting.

This is a duplicate for: https://github.com/dotnet/templating/issues/5588
The fix is already done and will be released in 7.0.101. Please follow the issue above for available workarounds
Thank you.
