### ISSUE TITLE
Review feature conditions in common project templates

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/templating#5668]
### Problem

Classlib seems to have overcomplicated conditions for language features: https://github.com/dotnet/sdk/blob/main/template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ClassLibrary-CSharp/.template.config/template.json#L114-L125

Some of those seems to be wrong - e.g. File Scoped Namespaces are not used for classlib if `net6.0` with no explicit language version is requested: https://github.com/dotnet/sdk/blob/main/template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ClassLibrary-CSharp/.template.config/template.json#L120

### Solution

Review the conditions and simplify them. We should be able to decide solely on language version (simply as it's already done for console template)

**Comment by JanKrivanek** [comment]
https://github.com/dotnet/sdk/pull/29221

**Comment by JanKrivanek** [comment]
@vlada-shubina Should we reopen this to track issue for net6.0 templates?

**Comment by vlada-shubina** [comment]
Discussion:
- ensure that: 
   - 1) WPF and WinForms templates are not affected
   - 2) WPF and WinForms templates are using inverted conditions .NET 8 +
- prepare PRs for 6.0.1xx, 6.0.3xx, 6.0.4xx (already done) and 7.0.1xx for Feb servicing
