### ISSUE TITLE
Custom Wizard not getting invoked when used with dotnet template

### ISSUE THREAD

**Issue by yassinebennani** [dotnet/templating#5678]
Hello,

Please I need your help guys I'm struggling to make the custom wizard working with dotnet template in visual studio 2022 17.4.1, I followed every necessary step and I analyzed all @sayedihashimi and @phenning repositories and videos (I really did) but I think there is something wrong, I can see my template while debugging my vsix project but the wizard is not getting invoked when I create the project.
**_(the same wizard is getting invoked when I use a visual studio project template)_**

My $groupid$ is matching the identitygroup field from template.json
My TemplateID is matching the identity field from template.json
My wizard assembly is signed
My .nupkg is getting installed to ProjectTemplates/ via the package definition file
My template.config folder contains also the vstemplate file
My template.zip is getting installed to the right location and contains the 3 files vstemplate, template.json and the icon.

I confirm that I can create my project while debugging the vsix project and the output is like expected but the wizard is not getting invoked.

[template.zip](https://github.com/ligershark/sidewafflev2/files/10083963/template.zip)

Thank you very much.

**Comment by vlada-shubina** [comment]
@phenning @sayedihashimi could you please check this issue and advise? Would you prefer it to be reported via VS Feedback instead?

It is not related to dotnet/templating repo otherwise, but we can help to move it to correct location.

**Comment by phenning** [comment]
@vlada-shubina I'd like to leave this here for a few days. I'd like to solve the immediate problem now, and also perhaps gather some additional information about requirements to help us drive potential replacement extensibility points for our IWizard implementation. I feel the github issues facilitates this a bit better than the Feedback system.

**Comment by yassinebennani** [comment]
Hello @phenning,

thank you for your quick response, 

so for your first question :
To confirm that this is the case, can you confirm if you see if the new project dialog page ever showing a a page that has your AggregateName as a parameter in the UI? 
**The answer is YES.**

for your second advice :
Also, you should not include the .vstemplate file in the nupkg, instead, it should be installed via the Microsoft.VisualStudio.ProjectTemplate asset in the vsixmanifest.
**Done**

for your workaround, effectively when I add the ide.host.json with the content suggested, my template engine template is not getting listed any more on visual studio but I don't understand the second part of your statement _**(but it will still be available to be called by your vstemplate.)**_ what you mean by this please, what will be the user experience, do I have to use a different templateid between the template.json and the vstemplate because only one getting listed when it's the same  as I understood [here](https://devblogs.microsoft.com/dotnet/net-cli-templates-in-visual-studio/),

I tested many combinations with this workaround

- same templateId with ide.host.json = only engine template is listed, parameter AggregateName is displayed, wizard not invoked.
- same templateId + ide.host.json = nothing is getting listed even my vstemplate project.
- diffrente templateid on vstemplate project + ide.host.json= only vstemplate project listed, parameter AggregateName not displayed, wizard invoked nothing from template engine is created(empty output).

Thank you for your help.

for your last question :

I think if you plan to deprecate the wizard implementation a second alternative should be able to answer many limitations that I have seen until now :

-the first one I'm not able to control the virtual solution folder system for my multiproject template because the post action D396686C-DE0E-4DE6-906D-291CD29FC5DE is ignored in visual studio, by the way I don't agree with the statement ([the user indicates where to add project explicitly, so post action defined in the template will be ignored](https://github.com/dotnet/templating/wiki/Post-Action-Registry#add-projects-to-a-solution-file) for me the path for this action should be relative (and use the user choice as root path) and not absolute.

-the second need is that my template will have a lot of parameters with many scenarios and I was disappointed to not be able to group them by a wizard ui steps, as I see there is only one wizard step with next button and then all parameters are on the same next page, thats not providing a good user experience for templates with a lot parameters (I have seen a proposal from @sayedihashimi with collapsible regions on the same page in my opinion scrollbar and expand collapse are not user friendly, I prefer wizard ui steps with next button).

-the third one is that I need to display or hide parameters or a wizard ui step based on the value of a another parameter value.

-run a script I think is not also supported by visual studio using the post action 3A7C4B45-1F5D-4A30-959A-51B88E82B5D2

**Comment by yassinebennani** [comment]
gentle ping @phenning

**Comment by phenning** [comment]
To each of the things you brought up:

> _same templateId without ide.host.json = only engine template is listed, parameter AggregateName is displayed, wizard not invoked(projects created)._

This is expected, vstemplate files and thus the wizard will not be invoked, as the entry point is entirely different.

> _same templateId with ide.host.json = only vstemplate project listed, parameter AggregateName not displayed, wizard invoked, nothing from template engine is created(empty output)._

For AggregateName not being shown, again this is expected, you would be responsible for gathering this via your own UI and then chaining to the inner wizard. You would need to pass through the $uistyle$: none and $groupid$ or $templateid$ yourself, as well as $passthrough:AggegrateName$ via the replacements dictionary.

One thing to keep in mind, is that you are trying to blend two different implementation together in a way that was not intended. The TemplateProvider mechanism that allows us to dynamically show options from the template engine templates was not designed or intended to be extended via wizards or external code entry at this point. The older IWizard implementation, while allowing you to use a wizard, also requires you to implement your own UI to gather any required parameters.

> _the first one I'm not able to control the virtual solution folder system for my multiproject template because the post action D396686C-DE0E-4DE6-906D-291CD29FC5DE is ignored in visual studio, by the way I don't agree with the statement ([the user indicates where to add project explicitly, so post action defined in the template will be ignored](https://github.com/dotnet/templating/wiki/Post-Action-Registry#add-projects-to-a-solution-file) for me the path for this action should be relative (and use the user choice as root path) and not absolute.

You should be able to just output a sln file and have it as a output from your template.json. 

> _the second need is that my template will have a lot of parameters with many scenarios and I was disappointed to not be able to group them by a wizard ui steps, as I see there is only one wizard step with next button and then all parameters are on the same next page, thats not providing a good user experience for templates with a lot parameters (I have seen a proposal from @sayedihashimi with collapsible regions on the same page in my opinion scrollbar and expand collapse are not user friendly, I prefer wizard ui steps with next button).

Thanks for this feedback, this is another datapoint we can share with the IDE team. 

> _the third one is that I need to display or hide parameters or a wizard ui step based on the value of a another parameter value.

This is In consideration for future versions.

> _run a script I think is not also supported by visual studio using the post action 3A7C4B45-1F5D-4A30-959A-51B88E82B5D2

Correct, this is not currently supported by Visual Studio.  This is something though that you could do in your IWizard implementation.

**Comment by YuliiaKovalova** [comment]
Close because of the existing workaround and no potential actions from the templating side.
