### ISSUE TITLE
Unexpected Internal Software Issue (EX_SOFTWARE)

### ISSUE THREAD

**Issue by j-tee** [dotnet/templating#5698]
I tried to create a new project and run into this error

**Comment by vlada-shubina** [comment]
@j-tee, could you please provide more information? Which `dotnet` version are you in?
Can it be the same issue as https://github.com/dotnet/templating/issues/5588? 

Thank you

**Comment by j-tee** [comment]
Yeah, it definitely is

**Comment by vlada-shubina** [comment]
Closing as duplicate. Please follow https://github.com/dotnet/templating/issues/5588 for workarounds
The fix is delivered in 7.0.101.
