### ISSUE TITLE
Update templates to use "exclude" and/or "include" for environment tag helper

### ISSUE THREAD

**Issue by jbagga** [dotnet/templating#570]
`<environment>` tag helper now supports include and exclude attributes https://github.com/aspnet/Mvc/pull/5722

See https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.TagHelpers/EnvironmentTagHelper.cs#L54

The templates can be updated to use them instead

cc @Eilon

**Comment by Eilon** [comment]
@damianedwards - I assume you want this change in the templates, right?

**Comment by DamianEdwards** [comment]
:+1:

**Comment by Eilon** [comment]
@mlorbetske - should we send a PR for this? It's a fairly small change to the templates. Is building the repo and running its tests super easy?

**Comment by mlorbetske** [comment]
Yep, calling setup in the repo root builds and runs tests. Template tests can be added too, we can chat about how to do that is you want content validation. A PR for the change would be great
