### ISSUE TITLE
[Announcement]: Template samples repository setup

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/templating#571]
FYI I have created a samples repo, https://github.com/dotnet/dotnet-template-samples. I've also created a short url https://aka.ms/dotnetnew-template-samples to point to this 

If you would like another sample added please file and issue and/or send a PR. I'm hoping that the community can help with samples, but adding issues for suggestions will be great. I'll take a look at the incoming issues and will create templates.

**Comment by tylerbhughes** [comment]
@sayedihashimi Your first URL takes me to https://github.com/dotnet/templating/issues/dotnet-template-samples whereas your short URL takes me to https://github.com/dotnet/dotnet-template-samples/

**Comment by sayedihashimi** [comment]
@tylerbhughes hmm looks like there was an issue converting the MD to HTML. I've just pasted the raw link. Thanks for letting me know.
