### ISSUE TITLE
NuGet.config's in this repo probably shouldn't use the 'aspnetcore-ci-dev' feed

### ISSUE THREAD

**Issue by Eilon** [dotnet/templating#572]
They should use the 'aspnetcore-dev' feed instead. (No "ci" in the name.)

The 'aspnetcore-ci-dev' feed has bits that are hot off the press and not signed or tested. I doubt there's a need for the templates to be so closely matched with runtime bits.

So, unless there's some special requirement here, the 'aspnetcore-dev' should be used instead.

**Comment by mlorbetske** [comment]
Switching this to use aspnetcore-dev, restore fails with:
`Unable to resolve 'Libuv (>= 1.10.0-preview1-22038)' for '.NETCoreApp,Version=v2.0'`

**Comment by Eilon** [comment]
@moozzyk / @pranavkm / @natemcmaster - any idea why https://dotnet.myget.org/gallery/aspnetcore-ci-dev has Libuv 1.10.0-preview1-22038 (https://dotnet.myget.org/feed/aspnetcore-ci-dev/package/nuget/Libuv), but https://dotnet.myget.org/gallery/aspnetcore-dev has only Libuv 1.10.0-preview1-22036 (2 builds older) (https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Libuv) ?

**Comment by moozzyk** [comment]
I don't think Libuv builds run as part of coherence builds so this is probably why the feeds are out of sync. Not sure how we synchronized feeds before (22036 was built in Jan while 22037/22038 in March) - sometimes rarely built repos get affected by CI changes that seems _unrelated_.

**Comment by Eilon** [comment]
Hmm then I wonder what pushes Libuv to each feed?

**Comment by mlorbetske** [comment]
Fixed by #585
