### ISSUE TITLE
A problem occurs when you customize a template

### ISSUE THREAD

**Issue by yeuxuan** [dotnet/templating#5749]
<img width="1006" alt="企业微信截图_16696877098413" src="https://user-images.githubusercontent.com/77331948/204421739-fb62c012-f457-43f4-8627-fcaeb760a44a.png">
<img width="675" alt="企业微信截图_16696878553330" src="https://user-images.githubusercontent.com/77331948/204421753-73e3898a-c2c9-402b-ad67-8288661787a2.png">

Modify the official example 05-multi-project In the picture I want to  template.json file options add mqttnet packing but Couldn't determine which project file to add a reference to I tried modifying targetFiles, but it didn't work

**Comment by YuliiaKovalova** [comment]
Hi @yeuxuan,

Could you provide your modified full template for further investigation?

Thank you!

**Comment by vlada-shubina** [comment]
Closing due to no feedback. Please comment if the issue still occurs, and we can reopen the issue. Thank you.
