### ISSUE TITLE
AccessDenied action in AAD template not used

### ISSUE THREAD

**Issue by danroth27** [dotnet/templating#575]
I don't see the AccessDenied action in the AAD template being used anywhere. Should it be removed along with it's view?

**Comment by mlorbetske** [comment]
@phenning any ideas? I'm not overly familiar with the mechanics of how that's supposed to work

**Comment by phenning** [comment]
See https://github.com/aspnet/Templates/issues/608

**Comment by danroth27** [comment]
Good to know - thx!
