### ISSUE TITLE
add a way to check if a new templates version exists

### ISSUE THREAD

**Issue by enricosada** [dotnet/templating#579]
After installing a custom template

```
dotnet new -i Fable.Template::*
```

something like

```
dotnet new fable --check`
```

to show if the custom template installed by a nuget package is out of date (a new version of package exists).

and maybe something to just update it directly

```
dotnet new fable --update`
```

**Comment by sayedihashimi** [comment]
We have planned --update. For the update check I wonder if that should just be a switch to --update. For ex:
    dotnet new --update --check

**Comment by mlorbetske** [comment]
We had planned the opposite as the default previously, we'd always check for updates (unless --skip-update-check was passed) & if updates were found we'd prompt to install them. This would tie in with user preferences to indicate the default behavior desired (--update would update all if it were passed, --update {packageid} would be the equivalent of --install {packageid}). Work on this paused when we switched to the model where we heavily abstract template sources as we need to generalize what updating means for all source types.

**Comment by enricosada** [comment]
nice that too, always up-to-date template is nice.

just some feedback:

- ask if user want to update the template, if a new version is found
- be nice on the offline story and timeout. nuget servers (there can more than one) can be really slow to answer. having separate commands help on that.

**Comment by mlorbetske** [comment]
This will be something that we'll want to cover as part of #1084

**Comment by RehanSaeed** [comment]
It would be nice if it automatically checked for an update just before creating a new project from a template.

**Comment by mlorbetske** [comment]
Yep, I've added a comment to the referenced issue to cover exactly that :)

**Comment by tebeco** [comment]
> It would be nice if it automatically checked for an update just before creating a new project from a template.

You mean just like `npx` in Node / Npm echo system ?
Yes it would be great
