### ISSUE TITLE
Verify usage in sdk should be in sync with templating

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/templating#5790]
### Is your feature request related to a problem? Please describe.

We are using fixed version in tests in sdk:

https://github.com/dotnet/sdk/blob/main/src/Tests/dotnet-new.Tests/dotnet-new.IntegrationTests.csproj#L18

This can create downgrade issues when updating version from sdk.

### Describe the solution you'd like.

Likely update the Verify versioning to be managed by dependabot in sdk

**Comment by JanKrivanek** [comment]
Verify.DiffPlex should be managed by dependabot as well

**Comment by vlada-shubina** [comment]
@GangWang01 - could you please add this task to your backlog? Thanks
