### ISSUE TITLE
Porting VSIX Project Template to dotnet new

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/templating#58]
I have started to look into porting the [ASP.NET MVC Boilerplate](https://visualstudiogallery.msdn.microsoft.com/6cf50a48-fc1e-4eaf-9e82-0b2a6705ca7d) project template from a VSIX to `dotnet new`. I have several questions:
1. What is the migration path? Do I totally switch to `dotnet new` or is it possible to somehow produce a `dotnet new` NuGet package, as well as a VSIX? Should I support VS 15 and/or 2017?
2. Is it too soon to do a port?
3. I followed the instructions in the ReadMe.md and could not get `dotnet new3 -i C:\GitHub\templating\template_feed` to actually install the templates in that directory. Is `dotnet new3` broken at the moment?
4. I've had a look at the new [templates](https://github.com/dotnet/templating/tree/master/template_feed) in this repo. What's the best way to learn the new pre-processor syntax, `.netnew.json` syntax, computed symbol syntax and learn how to create a package template? Are there any docs or more examples I can look at?
5. [ASP.NET MVC Boilerplate](https://visualstudiogallery.msdn.microsoft.com/6cf50a48-fc1e-4eaf-9e82-0b2a6705ca7d) has it's own pre-processor syntax and feature selection dialogue. I've written functional tests to run `dotnet restore`, `dotnet build`, `npm install`, `gulp default` and start the MVC site using the `TestHost` API to ensure that every feature combination works. How can I select features and run the templating engine programmatically in my functional tests?
6. Can I execute arbitrary code to create a project from my template? Any examples of this?
7. I love how templates are just NuGet packages. How are multi-project templates or files external to the project (global.json as an example) handled.
8. [ASP.NET MVC Boilerplate](https://visualstudiogallery.msdn.microsoft.com/6cf50a48-fc1e-4eaf-9e82-0b2a6705ca7d) has a WPF UI. Are there plans for a VS UI ontop of `dotnet new`? If not, I'm thinking it would be fairly simple to write an electron app to do feature selection based on .netnew.json, would this be an interesting open source project to the tooling team at Microsoft? It would be nice to provide icons for each feature in .netnew.json.

Please excuse the long list of questions, there is just a lot to templating :)

**Comment by mlorbetske** [comment]
Would you be open to having a call with @sayedihashimi and myself on these items sometime soon? We'd love to hear your thoughts on what would be the most preferred way to proceed here.

**Comment by RehanSaeed** [comment]
Sure, you can get in touch with me on my blogs [contact page](http://rehansaeed.com/contact/) and we can arrange a time.

**Comment by mlorbetske** [comment]
Let's keep this issue open & write about what we decide on for guidance here in case others have the same questions :)

**Comment by RehanSaeed** [comment]
One of my users raised [this question](https://github.com/ASP-NET-MVC-Boilerplate/Templates/issues/131):

- How `dotnet new` will handle installing the correct version of the .NET SDK required for the template. Assuming there are multiple versions.

**Comment by sayedihashimi** [comment]
I sent you a message on th contact page. Let's meet to discuss more in a skype meeting.

**Comment by seancpeters** [comment]
Since you're unblocked, we're going to close this is. Thanks again for all your help & input!
