### ISSUE TITLE
Prevent editors from auto-trimming whitespaces in test snapshot files

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/templating#5805]
### Is your feature request related to a problem? Please describe.

Original idea @baronfel & @vlada-shubina:  https://github.com/dotnet/sdk/pull/29526/commits/7e7c13812c147f1880aebe6ac53f1349a1695116

Unwanted changes to tests snapshots can be performed by editors respecting `.editorconfig`

### Describe the solution you'd like.

We should add globbing pattern into root .editorconfig files in templating and sdk repos to skip processing of `**\Approvals\**` and `**\Snapshots\**` files

**Comment by vlada-shubina** [comment]
@GangWang01 - could you please add this task to your backlog? Thanks
