### ISSUE TITLE
Publish schema for `template.json`

### ISSUE THREAD

**Issue by peterblazejewicz** [dotnet/templating#582]
I appreciate that sample for template comes with comments in `template.json`:
https://github.com/dotnet/dotnet-template-samples/blob/master/01-basic-template/MyProject.StarterWeb/.template.config/template.json
Can you folks consider to publish a schema for `template.json` file just like schemas for old, good one `project.json`?
https://github.com/SchemaStore/schemastore/tree/master/src/schemas/json
https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/project-1.0.0-rc2.json
Thanks!

**Comment by sayedihashimi** [comment]
+1

**Comment by mlorbetske** [comment]
@madskristensen is working on this right now :)

**Comment by mlorbetske** [comment]
Fix is mentioned in #749
