### ISSUE TITLE
Consider supporting `choice` dataType for all the symbols

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#5828]
Background: https://github.com/dotnet/templating/pull/5825#discussion_r1056263658

Currently `choice` dataType is only supported for `parameter` symbols.
It makes sense to extend the support to other symbol types, as `bind`, etc.

JSON schema already indicates that `dataType` is supported for any kind of symbol, and it is not consistent with actual implementation.

**Comment by YuliiaKovalova** [comment]
Closing as not planned.
