### ISSUE TITLE
Visual Studio For Mac ignore `copyOnly` inside `sources`

### ISSUE THREAD

**Issue by viniciusjarina** [dotnet/templating#5832]
### Product

dotnet CLI (dotnet new)

### Describe The Bug

It seems Visual Studio Mac ignores `copyOnly` value on `sources`, causing png files to be corrupted.

### To Reproduce

Steps:
1.  Add a custom template folder to VSMac ( I did test with https://github.com/xamarin/xamarin-android/blob/main/src/Microsoft.Android.Templates/android/.template.config/template.json) But any custom template will repro
2. Try to create  new project from the template
3. Png got corrupted

It seems related to https://github.com/dotnet/templating/issues/3325, but even after adding copyOnly VS4Mac still does the wrong thing

using the command line `dotnet new` works fine, the problem seems to affect only the template engine from VS4Mac

### dotnet Info

Visual Studio Community 2022 for Mac
Version 17.4.2 (build 17)
Installation UUID: cf2bd2ef-355f-4015-b2c8-9b874afd5abf

Runtime
.NET 6.0.12 (64-bit)
Architecture: X64

Roslyn (Language Service)
4.4.0-6.22578.12+3c6ab8e1715e5b080fb7bb77070810ab71e09387

NuGet
Version: 6.3.1.1

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/7.0.101/Sdks
SDK Versions:
	7.0.101
	6.0.404
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.1
	6.0.12
	5.0.17
	3.1.29

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 13.1.99.61 (Visual Studio Community)
Commit: xamarin-android/main/2e10309
Android SDK: /Users/viniciusjarina/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0  (API level 23)
		12.0 (API level 31)
		8.1  (API level 27)
		11.0 (API level 30)
		10.0 (API level 29)
		9.0  (API level 28)
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.3
SDK Build Tools Version: 33.0.0

Build Information: 
Mono: 6dd9def
Java.Interop: xamarin/java.interop/main@984711a3
SQLite: xamarin/sqlite/3.40.0@fdc1e34
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@fa3711b

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.4.0.54
Hash: 6eabb9e
Branch: remotes/origin/d17-4
Build date: 2022-12-13 04:22:32 UTC

Android Device Manager
Version: 0.0.0.1206
Hash: 886af39
Branch: 886af39
Build date: 2022-12-13 04:22:32 UTC

Xamarin Designer
Version: 17.4.0.136
Hash: d49c9ff6d3
Branch: remotes/origin/d17-4
Build date: 2022-12-13 04:22:27 UTC

Apple Developer Tools
Xcode 14.1 (21534.1)
Build 14B47b

Xamarin.Mac
Version: 9.0.0.28 (Visual Studio Community)
Hash: 6714e055b
Branch: xcode14.1
Build date: 2022-11-29 11:45:28-0500

Xamarin.iOS
Version: 16.1.1.28 (Visual Studio Community)
Hash: 6714e055b
Branch: xcode14.1
Build date: 2022-11-29 11:45:29-0500

Build Information
Release ID: 1704020017
Git revision: 7ef5413f2eec3351ce648085f619fc29fd8cb647
Build date: 2022-12-13 04:20:10+00
Build branch: release-17.4
Build lane: release-17.4

Operating System
Mac OS X 12.6.2
Darwin 21.6.0 Darwin Kernel Version 21.6.0
    Sun Nov  6 23:31:16 PST 2022
    root:xnu-8020.240.14~1/RELEASE_X86_64 x86_64

Enabled user installed extensions
Template Creator 0.8

### Visual Studio Version

Visual Studio Community 2022 for Mac Version 17.4.2 (build 17)

**Comment by vlada-shubina** [comment]
@viniciusjarina could you please try to uninstall template, open VS - ensure it is not installed anymore, and then install it back?
This sounds as the caching issue to me. 

If it doesn't help, please consider opening Feedback Ticket - https://developercommunity.visualstudio.com/home - for that, as it looks like VS for Mac issue.

Thanks

**Comment by YuliiaKovalova** [comment]
Hi @viniciusjarina ,

I close the ticket since we haven't received the requested info within 2 weeks.
Feel free to reopen the issue if you still have some questions.
