### ISSUE TITLE
System.CommandLine clean up

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/templating#5856]
Tasks:
- [ ] https://github.com/dotnet/templating/issues/4219 (8.0)
- [ ] https://github.com/dotnet/templating/issues/4225 (8.0)
- [ ] https://github.com/dotnet/templating/issues/4999 (8.0)
- [ ] https://github.com/dotnet/templating/issues/2038 (8.0)
- [x] https://github.com/dotnet/templating/issues/2173

## Justification
1. Combination of issues requested by customers and left-over work from System.CommandLine integration.

**Comment by YuliiaKovalova** [comment]
Closing in favor of individual issues.
