### ISSUE TITLE
Disallow HTTP feeds

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/templating#5859]
Disallowing HTTP feeds, disallowing untrusted/unverified nuget.org categories

**Comment by baronfel** [comment]
Package Source management should be handled by nuget.config transparently, so to me this one mostly looks like additional filters on `search` for trusted only/verified only packages.

**Comment by YuliiaKovalova** [comment]
This handling is relevant for install/update actions.
We suggest **do not allow** installation/update if customer adds option `--add source` and specifies url with **http** feed.
But still it makes sense to allow use **http** source that if` --force` flag is specified

@baronfel, we would love to hear your opinion here.

**Comment by baronfel** [comment]
That seems like a good balance. 

Error case:
```
> dotnet new install flibbertygibbet --nuget-source http://insecure-feed.org
The following template packages will be installed:
   flibbertygibbet

The nuget source 'http://insecure-feed.org' is insecure and will not be searched for the template 'myTemplate'.

flibbertygibbet could not be installed, the package does not exist.

For details on the exit code, refer to https://aka.ms/templating-exit-codes#103
```

Override case:
```
> dotnet new install flibbertygibbet --nuget-source http://insecure-feed.org --force
The following template packages will be installed:
   flibbertygibbet

Success: flibbertygibbet::0.32.0 installed the following templates:
Template Name    Short Name     Language  Tags
-------------    -------------  --------  ------------------------
flibbertygibbet  fg             C#        Scaffold/Console/Library
```

Are there other flags that the nuget API uses to mark sources as secure/insecure? If there is an API for this we should use that instead.

**Comment by YuliiaKovalova** [comment]
the question about validation on Nuget side https://github.com/NuGet/Home/discussions/12484
