### ISSUE TITLE
Review maestro-bot subscriptions

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/templating#5877]
### Product

dotnet CLI (dotnet new)

### Describe The Bug

Are templating subscriptions states and frequencies as expected?
Do we base them off the sdk subscriptions, or what is the key for setting ours.

Particularly: The arcade -> templating (7.0.1xx) subscription was set to frequency *None* - we updated to *EveryDay*, but want to be double-sure this is correct.

**Comment by YuliiaKovalova** [comment]
The relevant info can be found here
https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/27267/Branches-and-branding
