### ISSUE TITLE
Using hyphens or dots for the sourceName

### ISSUE THREAD

**Issue by alfonsogarciacaro** [dotnet/templating#588]
When using hyphens or dots to replace the `sourceName` (e.g. `dotnet new fable-elmish-react -n my-project`), the template engine automatically changes it to underscores in source files, however this is sometimes not desired, for example [here](https://github.com/fable-compiler/fable-elmish/blob/acbc9c2bc74dcce1e2fec3f9fa1dd843db84957a/src/templates/react/Content/package.json#L2) or [here](https://github.com/fable-compiler/fable-elmish/blob/acbc9c2bc74dcce1e2fec3f9fa1dd843db84957a/src/templates/react/Content/webpack.config.js#L18). Is there a way to configure this?

**Comment by mlorbetske** [comment]
This is discussed in #402, let's work through this on that issue.

The solution is to include one or more of those characters in the values the template is created with, there's a grid describing the behavior included on the other issue.

**Comment by alfonsogarciacaro** [comment]
Argh, another duplicate I couldn't find, I was searching for `hyphens` in previous issues. Sorry!
