### ISSUE TITLE
Remove troublesome static initializer in VerificationEngine

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/templating#5880]
### Is your feature request related to a problem? Please describe.

Currently `VerificationEngine` uses static constructor, that configures global behavior of Verify and VerifyDiffplex. This can however clash with other Verify tests if they would be used in a same project together with `TemplateVerifier` tests.

The clashes can either yield unexpected changes in behavior (the snapshoting or comparison type altered by `VerificationEngine` and then kept altered) or to an [exception](https://github.com/VerifyTests/Verify/blob/main/src/Verify/Verifier/InnerVerifier.cs#L27) in newer versions of `Verify`.

### Describe the solution you'd like.

The static initialization should be changed to initialization per test.
In order to be able to do that such an initializations need to be exposed via the Verify libraries:
* https://github.com/VerifyTests/Verify/issues/757
* https://github.com/VerifyTests/Verify.DiffPlex/issues/78

**Comment by JanKrivanek** [comment]
The prerequisities are fixed now - so all we need is to:
 * Update
  Verify.DiffPlex 2.1.0
  Verify.XUnit 19.6.0
* Make sure the above versions are in the donet-public packages feed
* Replace the static constructor with per-test initializers

**Comment by YuliiaKovalova** [comment]
The fix was delivered.
Close the issue
