### ISSUE TITLE
installation fails on debian stretch

### ISSUE THREAD

**Issue by livarcocc** [dotnet/templating#589]
_From @harindu95 on March 26, 2017 2:25_

## Steps to reproduce
I tried the following method from official site.
    
     sudo apt-get install curl libunwind8 gettext
     curl -sSL -o dotnet.tar.gz https://go.microsoft.com/fwlink/?linkid=843453
     sudo mkdir -p /opt/dotnet && sudo tar zxf dotnet.tar.gz -C /opt/dotnet
     sudo ln -s /opt/dotnet/dotnet /usr/local/bin
     dotnet new console -o hwapp   

## Expected  behavior
    Creating a new project

## Actual behavior

Crashed with the following error

     Error reading JObject from JsonReader. Path '', line 0, position 0.
     at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
     at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
     at Newtonsoft.Json.Linq.JObject.Parse(String json)
     at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.EnsureLoaded()
     at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.GetTemplates(HashSet`1 templates)
     at Microsoft.TemplateEngine.Edge.Template.TemplateCreator.List(Boolean exactMatchesOnly, Func`3[] filters)
     at Microsoft.TemplateEngine.Cli.New3Command.PerformCoreTemplateQueryAsync()
     at Microsoft.TemplateEngine.Cli.New3Command.<EnterTemplateManipulationFlowAsync>d__65.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
     at Microsoft.TemplateEngine.Cli.New3Command.<ExecuteAsync>d__66.MoveNext(\'

## Environment data
dotnet --info output:

    .NET Command Line Tools (1.0.1)

    Product Information:
    Version:            1.0.1
    Commit SHA-1 hash:  005db40cd1

    Runtime Environment:
    OS Name:     debian
    OS Version:  9
    OS Platform: Linux
    RID:         debian.8-x64
    Base Path:   /opt/dotnet/sdk/1.0.1

find /opt/dotnet -name '*.so' -type f -print | xargs ldd | grep 'not found'

  	liblldb-3.6.so => not found
	liblldb-3.6.so => not found

_Copied from original issue: dotnet/cli#6153_

**Comment by livarcocc** [comment]
_From @ofmendez on April 14, 2017 20:19_

Same here, exact result :(

**Comment by mlorbetske** [comment]
@ofmendez @harindu95 can you try running `dotnet new --debug:reinit` please?

**Comment by ofmendez** [comment]
@mlorbetske 
Although the comand 
`find /opt/dotnet -name '*.so' -type f -print | xargs ldd | grep 'not found'`
now get empty message...
I resumed the method from official site:
```
dotnet new console -o hwapp
cd hwapp
dotnet restore
```
and in this point I get: 

` [1] 18747 segmentation fault  dotnet restore`

I tried with other names and sequences, like in the official video tutorial:


```
dotnet new console -o myapp
cd myapp
code .
```

And run `dotnet restore` in the built-in terminal of VScode, getting the same result :(

**Comment by mlorbetske** [comment]
@ofmendez I'm not sure what the first command you mentioned is supposed to do to be honest, my Linux command line skills are rusty at best. From the sound of it though, the "new" command has produced a csproj & related artifacts in the specified folder - if that's correct & you're now facing an issue with dotnet restore, I think this issue should move back to dotnet/cli.

/cc @livarcocc

**Comment by mlorbetske** [comment]
@ofmendez did I interpret the state of things correctly? If so, we should get the `restore` issue looked at by moving the issue to the `dotnet/cli` or `nuget/home` repos

**Comment by JacsonF** [comment]
@mlorbetske  
Thank you for the solution.

**Comment by Yutsa** [comment]
I followed @mlorbetske instructions and I have the same issue as @ofmendez when trying to do `dotnet restore` or `dotnet run`.

I guess Stretch isn't supported yet unfortunately. I hope I'll find a way to use dotnet core on my Debian Stretch soon though.

**Comment by mlorbetske** [comment]
Thanks for the clarification. I'll move this back to the CLI repo for further investigation.

**Comment by mlorbetske** [comment]
This issue was moved to dotnet/cli#6537
