### ISSUE TITLE
Use the new Trie for processing and adjust buffer mechanics accordingly

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/templating#6]
This is a big item but will enable lookarounds in token matching. This will address https://github.com/ligershark/microsoft-templateengine/issues/63

**Comment by sayedihashimi** [comment]
Yes I think this is needed for real world templates. For example in my CSS I have "background-color: white" and I want to prompt for a new color. When the replacement is applied it should only change "white" if it's immediately after "background-color:".
