### ISSUE TITLE
Is verifier nuget or CLI available?

### ISSUE THREAD

**Issue by jimAtLoyal** [dotnet/templating#6001]
### Is your feature request related to a problem? Please describe.

I see the ProjectTestRunner has been deprecated and read about the new testing doc here https://github.com/dotnet/templating/wiki/Templates-Testing-Tooling 

But neither the NuGet package nor CLI mentioned in the doc can be found to install. And the link about building in the main readme is a dead link: https://github.com/dotnet/templating/blob/main/Contributing.md 

### Describe the solution you'd like.

Directions on testing templates.

**Comment by YuliiaKovalova** [comment]
Hi @jimAtLoyal,

Our templating testing tool hasn't been released yet, so stay tuned.
The link to the Contributig page will be fixed soon. Sorry for the inconvenience.

**Comment by jimAtLoyal** [comment]
Thanks. Is there an issue I can follow to know when the NuGet package has been published? 

In the mean time, I'll try building it locally instead of using the deprecated tools.

**Comment by jimAtLoyal** [comment]
I downloaded it and `main` uses .NET 8. I see there's some 7.x branches, but they look old. Is there a way to build and run on .NET 7?

**Comment by vlada-shubina** [comment]
@jimAtLoyal 
you can try to build it from release/7.0.2xx branch: https://github.com/dotnet/templating/tree/release/7.0.2xx/tools 
This branch uses `net7.0`. 

Or alternatively download .NET8 from daily builds (see the links in readme here: https://github.com/dotnet/installer).
