### ISSUE TITLE
Post-Actions in SDK do not have tests

### ISSUE THREAD

**Issue by maridematte** [dotnet/templating#6004]
There are almost no tests for the post-actions in the sdk repo. We should add them so we are sure any changes don't affect them. 
Post actions without tests:
- [ ] `ChmodPostActionProcessor`
- [ ] `ChmodPostActionProcessor`

**Comment by YuliiaKovalova** [comment]
Note: We have a test for this post action (runs on Linux machines)

https://github.com/dotnet/sdk/blob/main/src/Tests/dotnet-new.Tests/PostActionTests.cs
https://github.com/dotnet/sdk/blob/main/src/Tests/dotnet-new.Tests/PostActionTests.Approval.cs
https://github.com/dotnet/sdk/blob/a0493978913948bb84ad7d4820500231d84debb2/src/Tests/dotnet-new.Tests/CommonTemplatesTests.cs#L126-L164

**Comment by fgheysels** [comment]
These are integration-tests, but not unitests.

**Comment by vlada-shubina** [comment]
We do have unit tests as well: https://github.com/dotnet/sdk/tree/main/src/Tests/dotnet.Tests/dotnet-new but not for all post actions.

**Comment by fgheysels** [comment]
The unit-tests that are in that location, are unit-tests for post actions that are defined in https://github.com/dotnet/sdk/tree/main/src/Cli/dotnet/commands/dotnet-new/PostActions

However, the post-actions that are defined in https://github.com/dotnet/sdk/tree/main/src/Cli/Microsoft.TemplateEngine.Cli/PostActionProcessors do not have unit-tests.
