### ISSUE TITLE
Sample for "Add a reference to a project file"

### ISSUE THREAD

**Issue by leastprivilege** [dotnet/templating#601]
I want to add nuget packages to an existing csproj. The [wiki](https://github.com/dotnet/templating/wiki/Post-Action-Registry) seems to indicate that this is possible. Any sample for that?

**Comment by mlorbetske** [comment]
@seancpeters can you share an example of this please?

**Comment by seancpeters** [comment]
An example post action setup for adding package references looks like the following (the required configuration will go in the template.json file for the template):
```
  "postActions": [
...
    {
      "Description": "Add a reference",
      "ActionId": "B17581D1-C5C9-4489-8F0A-004BE667B814",
      "ContinueOnError": "false",
      "ManualInstructions": [
        {
          "Text": "Manually add the reference to your project file"
        }
      ],
      "args": {
        "referenceType": "package",     // package | project
        "reference": "newtonsoft.json",
        "version": "9.0.1",
        "projectFileExtensions": ".csproj"
      }
    }
...
  ]
```
The pieces of the configuration represent the following:
description: Meant to be displayed to the user, so should be meaningful. 
actionId (required):  Specifies the post action to perform, so for add package reference post actions, the value will always be B17581D1-C5C9-4489-8F0A-004BE667B814.
continueOnError: Whether or not to process additional post actions if this one fails.
manualInstructions: Will be displayed to the user if the post action cannot be run, e.g. if the host doesn't implement the action.
args (required): For add reference post actions, the args indicate which packages to add, and where to add them, as follows:
- referenceType (required): Use the literal value "package" when configuring to add a package reference.
- reference (required): The name of the package to add.
- version (optional): The version of the package to add. 
- projectFileExtensions (optional): Specifies which project file extensions to use when looking for the project file to add references to. If provided, the value must be a semi-colon (;) separated like of extensions, for example: ".csproj; .fsproj". If not specified, all files matching *.*proj will be considered. Note: wildcard matching is not supported, do not include wildcards in the extension list.

Details on which project file the package references will be added to:
- This post action attempts to locate an appropriate project file starting in the output directory the template is being created in. If no project files are found that match the specified (or default) extensions, look in the parent directory. If no project files are found there, look in its parent, continuing up the directory hierarchy until a project file if found, or until the root directory has been checked.
- If no matching project files are found, no action will be taken. Also, if more than one matching project file is found in the first directory containing matches, no action will be taken.

When creating templates with `dotnet new`, the add package reference post action is handled by `dotnet add`. The actual command issued is one of these (depending on whether a version was specified):
- `dotnet add <project file> package <package name>`
- `dotnet add <project file> package <package name> --version <version>`

**Comment by leastprivilege** [comment]
thanks! I'll give it a try.

**Comment by leastprivilege** [comment]
I tried - but doesn't seem to do anything for me - could you have a look if something is wrong:

https://github.com/IdentityServer/IdentityServer4.Templates/blob/dev/UI/.template.config/template.json

**Comment by mlorbetske** [comment]
One thing worth noting here is that this is supported starting with the 2.0.0-* CLI or with the `new3` command from this repo. I'm not sure if that changes the outcome here.

**Comment by leastprivilege** [comment]
it does. thanks ;)

**Comment by jayantadas1** [comment]
Hello, Is  there a possibility of adding -s to this functionality so that I can add packages from a different source?
