### ISSUE TITLE
Interactive mode: Implement 'opt in' mechanism

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/templating#6021]
**_Exit Criteria_**:
1. Based on the lessons learned from logger & requirements detailed in https://github.com/dotnet/templating/pull/6015, agree with architect on OPT-in\OPT-out implementation
2. Optional: if needed, produce a 1-pager design
3. Implement OPT-in\OPT-out behavior.
4. Deliver tests that sign off on the addressing of requirements. 

Done when all tests reliably run green

**Comment by maridematte** [comment]
The opt-in mechanism will be fully implemented in 8.0 RC 1. Until then, a feature flag will be used to enter interactive mode.
