### ISSUE TITLE
Interactive mode: Implement 'prompting' loop

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/templating#6022]
**_predecessor_**: https://github.com/dotnet/templating/issues/6021

**_Exit Criteria_**:
1. Based on the requirements detailed in https://github.com/dotnet/templating/pull/6015, agree with architect on **_interactive mode prompting loop_** implementation
2. Optional: if needed, produce a 1-pager design
3. Implement prompting loop.
4. Deliver tests that sign off on the addressing of requirements.

Done when all tests reliably run green

**Comment by maridematte** [comment]
The base version of the prompting loop has been implemented in this concept pr: https://github.com/dotnet/sdk/pull/30832. Further development will be tracked by other issues.
