### ISSUE TITLE
#elseif versus #elif

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/templating#603]
I was chatting with @danroth27 and he pointed out that the usage of `#elseif` in [startup.cs](https://github.com/dotnet/templating/blob/rel/vs2017/post-rtw/template_feed/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/StarterWeb-CSharp/Startup.cs#L65) should be `#elif` according to https://msdn.microsoft.com/en-us/library/ed8yd1ha.aspx

**Comment by mlorbetske** [comment]
Dupe of #602
