### ISSUE TITLE
Add ClientSecret parameter to the user secrets file for org auth templates

### ISSUE THREAD

**Issue by danroth27** [dotnet/templating#607]
When using the `--org-read-access` option you need a client secret to be able to talk to the graph API. This secret should be stored in the user secrets file.

**Comment by mlorbetske** [comment]
This issue hasn't been moved to aspnet/templating as there'd be some additional work on dotnet/templating side to support such a gesture (accept some value and write it to the user secrets file after project creation) but it'd also require work in the web templates to enable that functionality.

Is this something we still want to do?

**Comment by mlorbetske** [comment]
Closing this as there hasn't been confirmation of the ask
