### ISSUE TITLE
Support user code style preferences

### ISSUE THREAD

**Issue by dansiegel** [dotnet/templating#6076]
### Is your feature request related to a problem? Please describe.

While this is not the first time this issue has come up (#1440), it will inevitably continue to resurface until it is addressed. We have the age old debate Spaces vs Tabs. As template authors we get to be very opinionated on our own code style preferences which may not necessarily reflect the desires of the developer creating a project with any given template. Over the past several years the tooling has come a long way towards supporting .editorconfig, and it is time that dotnet new starts supporting this with a post action.

### Describe the solution you'd like.

Whether as a library author I place an .editorconfig in the template and provide a symbol to switch between spaces/tabs for my various code files, the generated template should have as a post action a way to utilize the existing tooling to understand .editorconfig and/or the VS user preferences (when created from VS) and update the project files to match the rules of the .editorconfig / user preferences.

**Comment by vlada-shubina** [comment]
@dansiegel thanks for the suggestion.

could you please check if https://github.com/dotnet/templating/issues/5505 fully covers your suggestion? 
it looks like this is a duplicate of that one. 

Implementation-wise we plan to implement it as new post-action.

thanks.

**Comment by dansiegel** [comment]
Thanks @vlada-shubina I definitely missed that one. Yes that seems to cover the issue. Will this be coming in the net8 timeframe?

**Comment by vlada-shubina** [comment]
> Thanks @vlada-shubina I definitely missed that one. Yes that seems to cover the issue. Will this be coming in the net8 timeframe?

yes, it is planned for net8.0 atm.
