### ISSUE TITLE
Create Solution Template - group of projects

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/templating#611]
Ported from: https://github.com/dotnet/cli/issues/6346 by @dyardyGIT

# Original Text

If we have a solution with a number of projects and want to make a template out of the entire package - can this be done?

I believe the answer is yes.  I have been able to put .template.config/template.json at the root level of an existing project then use dotnet new -i to install the template into the library.

I can then use dotnet new {solutionname} to generate a new solution including the projects however there are some issues that I have not been able to solve.

a) i want to pass in new parameter so that the projects are named given solution name + ".web" or ".api" or ".service" etc.  (currently the projects are just copies of the original project name)

b) is it possible to use a replace parameter to float down to all projects that are a member of the template?

thanks-dave

**Comment by sayedihashimi** [comment]
>If we have a solution with a number of projects and want to make a template out of the entire package - can this be done?
I believe the answer is yes. I have been able to put .template.config/template.json at the root level of an existing project then use dotnet new -i to install the template into the library.

Yes that is correct.

>a) i want to pass in new parameter so that the projects are named given solution name + ".web" or ".api" or ".service" etc. (currently the projects are just copies of the original project name)
b) is it possible to use a replace parameter to float down to all projects that are a member of the template?

I think the easiest thing to do here is to apply the desired naming convention to your source projects. For example take a look @ my console + unit test template at https://github.com/dotnet/dotnet-template-samples/tree/master/05-multi-project. That sample doesn't have a `.sln` file but if it was there it should work just fine. In this sample the projects are named:

 - `MyProject.Console`
 - `MyProject.Console.Test`

Then in the [`template.json`](https://github.com/dotnet/dotnet-template-samples/blob/master/05-multi-project/.template.config/template.json) the `sourceName` field is set to `MyProject.Console`. When the user invokes `dotnet new conunit -n Contoso` the result is:

 - Contoso
 - Contoso.Test

I think this is the behavior you're looking for. If you have a pressing need to keep the existing names you should be able to do that, but you'll need to create a new parameter and then define the value based on `sourceName`. I think the approach I outlined is much more straight forward and that's what I'm recommending.

**Comment by sayedihashimi** [comment]
Closing based on no reply

**Comment by vhugogarcia** [comment]
> > If we have a solution with a number of projects and want to make a template out of the entire package - can this be done?
> > I believe the answer is yes. I have been able to put .template.config/template.json at the root level of an existing project then use dotnet new -i to install the template into the library.
> 
> Yes that is correct.
> 
> > a) i want to pass in new parameter so that the projects are named given solution name + ".web" or ".api" or ".service" etc. (currently the projects are just copies of the original project name)
> > b) is it possible to use a replace parameter to float down to all projects that are a member of the template?
> 
> I think the easiest thing to do here is to apply the desired naming convention to your source projects. For example take a look @ my console + unit test template at https://github.com/dotnet/dotnet-template-samples/tree/master/05-multi-project. That sample doesn't have a `.sln` file but if it was there it should work just fine. In this sample the projects are named:
> 
> * `MyProject.Console`
> * `MyProject.Console.Test`
> 
> Then in the [`template.json`](https://github.com/dotnet/dotnet-template-samples/blob/master/05-multi-project/.template.config/template.json) the `sourceName` field is set to `MyProject.Console`. When the user invokes `dotnet new conunit -n Contoso` the result is:
> 
> * Contoso
> * Contoso.Test
> 
> I think this is the behavior you're looking for. If you have a pressing need to keep the existing names you should be able to do that, but you'll need to create a new parameter and then define the value based on `sourceName`. I think the approach I outlined is much more straight forward and that's what I'm recommending.

I just wanted to **thank you** for posting this solution, it helped me a lot for my .NET 6 template solution.
