### ISSUE TITLE
Add Project defaults to wrong location when used after creating new solution

### ISSUE THREAD

**Issue by janstaelensskyline** [dotnet/templating#6134]
### Product

Visual Studio

### Describe The Bug

We have created two templates that sets up projects with all our NuGet MetaData pre-filled and Licenses, readme, ... included.
We have one template that adds a Custom Solution (with a single project) and one that adds a Custom Project to an existing solution.

When we first use Visual Studio "New Project" to create the solution the Location is for example set to "C:\\GIT"
It will automatically open the solution. If you then try to do a right click on the solution explorer and select: Add New Project and select the Custom Project template the Location by default fills in with C:\\GIT.  Thats incorrect, it should be C:\\GIT\\MySolution.

If you don't notice it, and click create it will make the project outside of the solution folder (and also outside the repository so it won't get pushed to github). Its easy to not notice at first until CI/CD pipelines start failing.

Currently you need to restart visual studio after creating the solution in order to avoid the problem. If you restart VS and then try add project you get the correct default Location.

I'm assuming the Location is cached in Visual Studio somehow, and then filled in anytime you open another wizard instead of it filling in a new default value.

We haven't found a way yet to avoid this from happening or add a workaround, hence the bug report.

### To Reproduce

Steps:
1.  Create a new Solution in Visual Studio using the new templating
2.  Without restarting VS, right click in solution explorer and add a new project using the new templating
3.  If you follow default wizard, Location will start wrong. Clicking Create will add the project to solution explorer, but in unexpected location of File Explorer.

### dotnet Info

<details>
  <summary>output</summary>
.NET SDK:
 Version:   7.0.200
 Commit:    534117727b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.200\

Host:
  Version:      7.0.3
  Architecture: x64
  Commit:       0a2bda10e8

.NET SDKs installed:
  2.1.526 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.309 [C:\Program Files\dotnet\sdk]
  7.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
  
  
</details>

### Visual Studio Version

Version 17.5.0

### Additional context

Our templates can be found here: https://github.com/SkylineCommunications/Skyline.DataMiner.VisualStudioTemplates
Note that these are still in development.

**Comment by YuliiaKovalova** [comment]
Hi @janstaelensskyline,

Thank you for reporting this issue. We are taking a look at it.

**Comment by YuliiaKovalova** [comment]
Hi @phenning,

Could you take a look at the ticket and confirm/deny belonging to VS area?

Thank you!

**Comment by phenning** [comment]
This is unrelated to the template engine or template engine host code, since none of our code is invoked until the template is actually run, which happens after that first page has been clicked through. 

The behavior described here is part of the core IDE. “Add New Project and select the Custom Project template the Location by default fills in with C:\GIT. ”.   

This should also reproduce if the second project created into the solution was a traditional vstemplate based project. 

A Visual Studio feedback item should be opened, with a simpler repro, perhaps with two .NET Framework Winforms templates as an example, in order to isolate the repo.

**Comment by YuliiaKovalova** [comment]
@phenning , thank you for these details!

@janstaelensskyline, could you create a Visual Studio feedback item here https://developercommunity.visualstudio.com/VisualStudio/suggest with the requested information above?

**Comment by YuliiaKovalova** [comment]
Close since the ticket has to be created on the https://developercommunity.visualstudio.com/VisualStudio/suggest .
