### ISSUE TITLE
Conditional processing and comment syntax should support .axaml extension as XML

### ISSUE THREAD

**Issue by Mrxx99** [dotnet/templating#6156]
### Is your feature request related to a problem? Please describe.

For .xaml files the normal XML comment syntax can be used for conditions, but that does not work for .axaml files that are used by Avalonia and are also XAML files.

### Describe the solution you'd like.

The .axaml should be one of the supported extensions for XML (https://github.com/dotnet/templating/wiki/Conditional-processing-and-comment-syntax#xml-files)

### Additional context

The syntax for [other file types](https://github.com/dotnet/templating/wiki/Conditional-processing-and-comment-syntax#other-file-types) should continue to work as well, otherwise this would be a breaking change

**Comment by YuliiaKovalova** [comment]
Hi @Mrxx99,

Thank you for reporting this issue. Could you provide an example of the template that uses `.axaml `files?

**Comment by Mrxx99** [comment]
> Hi @Mrxx99,
> 
> Thank you for reporting this issue. Could you provide an example of the template that uses `.axaml `files?
> 

Here: https://github.com/AvaloniaUI/avalonia-dotnet-templates/blob/master/templates/csharp/app/App.axaml

**Comment by YuliiaKovalova** [comment]
Hi @Mrxx99 ,

As a temporary workaround, we can suggest you use the SpecialCustomOperations block for enabling `*.axml` processing:
```
"SpecialCustomOperations": {
    "**.axml": {
      "operations": [
        {
          "type": "conditional",
          "configuration": {
		"endif": [ "#endif", "<!--#endif" ],
		"actionableIf": [ "<!--#if" ],
		"actionableElse": [ "#else", "<!--#else" ],
		"actionableElseif": [ "#elseif", "<!--#elseif", "#elif", "<!--#elif" ],
		"trim": true,
		"wholeLine": true,
		"evaluator": "C++"
          }
        }
      ]
    }
```

![image](https://user-images.githubusercontent.com/95473390/222125913-fae28584-eda8-47b4-b853-0b9613d75198.png)


Unfortunately, it is poorly [documented](https://github.com/dotnet/templating/blob/main/docs/Reference-for-template.json.md#conditional), but we have a ticket for extending it.

**Comment by YuliiaKovalova** [comment]
Close as fixed. Pending release.
