### ISSUE TITLE
Adding missing callback path parameter to mvc b2c template

### ISSUE THREAD

**Issue by danroth27** [dotnet/templating#622]

**Comment by mlorbetske** [comment]
@danroth27 this is done right?

**Comment by danroth27** [comment]
Yeah: 

https://github.com/dotnet/templating/blob/rel/vs2017/post-rtw/template_feed/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/StarterWeb-CSharp/appsettings.json#L11

https://github.com/dotnet/templating/blob/rel/vs2017/post-rtw/template_feed/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/StarterWeb-CSharp/AzureAdB2COptions.cs#L15
