### ISSUE TITLE
dotnet new3 Error on Linux/Mac

### ISSUE THREAD

**Issue by rschiefer** [dotnet/templating#625]
I'm trying to test "dotnet new3" on Linux/Mac but received the following error on both:

> $ dotnet new3 -l
> 
> Unhandled Exception: System.ComponentModel.Win32Exception: No such file or directory
>    at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
>    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start()
>    at Microsoft.DotNet.Cli.Utils.Command.Execute()
>    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
>    at Microsoft.DotNet.Cli.Program.Main(String[] args)
> Aborted (core dumped)

I can run "dotnet new" without issue:

> $ dotnet new -l
> Template Instantiation Commands for .NET Core CLI.
> 
> Usage: dotnet new [arguments] [options]
> 
> Arguments:
>   template  The template to instantiate.
> 
> 
> Templates          Short Name       Language      Tags
> ----------------------------------------------------------
> Nuget Config       nugetconfig                    Config
> Web Config         webconfig                      Config
> Solution File      sln                            Solution

I first ran setup.sh to setup the new3 command from a customized fork, then pulled from the main repo and reran setup.sh.  Received the above error for both branches.  It may be that I'm not properly setting up the new3 command.  I did try the harderreset.sh script but no change.

My fork - https://github.com/rschiefer/templating
Main repo - https://github.com/dotnet/templating

**Comment by mlorbetske** [comment]
It looks like this trace is from the dotnet cli itself, which build of the cli are you running? The difference between new and new3 from the cli perspective is that new calls into these assemblies directly, while new3 must be started as an external process.

**Comment by rschiefer** [comment]
"dotnet --version" returns 1.0.1 on Mac and Linux.  My Windows machine says "1.0.0-rc4-004917".  

What version do I need?

**Comment by rschiefer** [comment]
Not sure if this helps but I ran dotnet from the ".dotnet" folder which is the same version as is working in Windows and got the same error on Linux.

> $ .dotnet/dotnet new3 -l
> 
> Unhandled Exception: System.ComponentModel.Win32Exception: No such file or directory
>    at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
>    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start()
>    at Microsoft.DotNet.Cli.Utils.Command.Execute()
>    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
>    at Microsoft.DotNet.Cli.Program.Main(String[] args)
> Aborted (core dumped)
> 
> $ .dotnet/dotnet --info
> .NET Command Line Tools (1.0.0-rc4-004917)
> 
> Product Information:
>  Version:            1.0.0-rc4-004917
>  Commit SHA-1 hash:  9a4c2c32f4
> 
> Runtime Environment:
>  OS Name:     ubuntu
>  OS Version:  14.04
>  OS Platform: Linux
>  RID:         ubuntu.14.04-x64
>  Base Path:   /mnt/d/Github/dotnet/templating/rschiefer-linux/templating/.dotnet/sdk/1.0.0-rc4-004917

**Comment by sayedihashimi** [comment]
I tried with the latest MAC cli and got a similar but different error.

```
Sayeds-MacBook-Pro:templating sayedhashimi$ dotnet --version
2.0.0-preview1-005825

Sayeds-MacBook-Pro:templating sayedhashimi$ dotnet new3 -h
System.ComponentModel.Win32Exception (0x80004005): No such file or directory
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

**Comment by sayedihashimi** [comment]
When I invoke `dotnet-new3` directly it works. Maybe this is an issue with the symlink to dotnet-new3 or however that is hooked up to `dotnet new3`.

@rschiefer can you try invoking the dotnet-new3 which is under the `dev` folder after running `setup.sh` and let me know if that works for you?

```
Sayeds-MacBook-Pro:templating sayedhashimi$ ./dev/dotnet-new3 -h
Getting ready...
Template Instantiation Commands for .NET Core CLI

Usage: new3 [options]

Options:
  -h, --help          Displays help for this command.
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
  -o, --output        Location to place the generated output.
  -i, --install       Installs a source or a template pack.
  -u, --uninstall     Uninstalls a source or a template pack.
  --type              Filters templates based on available types. Predefined values are "project", "item" or "other".
  --force             Forces content to be generated even if it would change existing files.
  -lang, --language   Specifies the language of the template to create.


Templates                                         Short Name       Language      Tags
----------------------------------------------------------------------------------------------------
Console Application                               console          [C#], F#      Common/Console
Class library                                     classlib         [C#], F#      Common/Library
Unit Test Project                                 mstest           [C#], F#      Test/MSTest
xUnit Test Project                                xunit            [C#], F#      Test/xUnit
ASP.NET Core Empty                                web              [C#], F#      Web/Empty
ASP.NET Core Web App (Model-View-Controller)      mvc              [C#], F#      Web/MVC
ASP.NET Core Web App (Razor Pages)                razor            [C#]          Web/MVC/Razor Pages
ASP.NET Core Web API                              webapi           [C#]          Web/WebAPI
Web Config                                        webconfig                      Config
Nuget Config                                      nugetconfig                    Config
Solution File                                     sln                            Solution
MVC ViewStart                                     viewstart                      Web/ASP.NET
MVC ViewImports                                   viewimports                    Web/ASP.NET
Razor Page                                        page                           Web/ASP.NET


Examples:
    dotnet new3 mvc --framework netcoreapp2.0
    dotnet new3 classlib --framework netcoreapp2.0
    dotnet new3 --help
Sayeds-MacBook-Pro:templating sayedhashimi$
```

**Comment by rschiefer** [comment]
Yes, that works for me too.

> $ ./dev/dotnet-new3 -h
> Template Instantiation Commands for .NET Core CLI
> 
> Usage: new3 [options]
> 
> Options:
>   -h, --help          Displays help for this command.
>   -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
>   -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
>   -o, --output        Location to place the generated output.
>   -i, --install       Installs a source or a template pack.
>   -u, --uninstall     Uninstalls a source or a template pack.
>   --type              Shows a subset of the available templates. Valid values are "project", "item" or "other".
>   --force             Forces content to be generated even if it would change existing files.
>   -lang, --language   Specifies the language of the template to create.
> 
> 
> Templates                 Short Name       Language      Tags
> -----------------------------------------------------------------------
> Console Application       console          [C#], F#      Common/Console
> Class library             classlib         [C#], F#      Common/Library
> Unit Test Project         mstest           [C#], F#      Test/MSTest
> xUnit Test Project        xunit            [C#], F#      Test/xUnit
> ASP.NET Core Empty        web              [C#]          Web/Empty
> ASP.NET Core Web App      mvc              [C#], F#      Web/MVC
> ASP.NET Core Web API      webapi           [C#]          Web/WebAPI
> Web Config                webconfig                      Config
> Nuget Config              nugetconfig                    Config
> Solution File             sln                            Solution
> 
> 
> Examples:
>     dotnet new3 mvc --framework netcoreapp2.0
>     dotnet new3 sln
>     dotnet new3 --help

**Comment by rschiefer** [comment]
Referencing dotnet-new3 from the "dev" folder does allow me to run new3 successfully but it doesn't have any of my changes from Microsoft.TemplateEngine.Cli.  I can copy the bin output to the dev folder and it gets my changes, partially runs my new code but then fails with 

> Error reading template from file: /.template.config/template.json | Error = Could not load file or assembly 'Microsoft.TemplateEngine.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

Tried copying Microsoft.TemplateEngine.Core.dll to the dev folder but same error.

Any help would be greatly appeciated!

**Comment by dansiegel** [comment]
@sayedihashimi I'm actually seeing this error as well. I tried running dotnet-new3 from the dev folder to install a template and got the following error.

```
Dans-MacBook-Air:templating dansiegel$ ./dev/dotnet-new3 --install ~/Repos/Prism-Templates/
Error reading template from file: /content/.template.config/template.json | Error = Could 
not load file or assembly 'Microsoft.TemplateEngine.Core, Version=1.0.0.0, Culture=neutral, 
PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
```

**Comment by mlorbetske** [comment]
The issue when running from dev comes from a component installation ordering issue. I'll try to get a fix in for this tonight. Still not sure where the Process.Start problem is coming from though - it's happening in the CLI before it even gets to us.

**Comment by mlorbetske** [comment]
The component ordering part should be fixed in #667

**Comment by dansiegel** [comment]
@mlorbetske I wiped out the repo locally, re-cloned it, and re-ran the setup.sh.

```
Done!
You can now use setup.sh from anywhere to rebuild dotnet new3
You can now use harderreset.sh from anywhere to delete dotnet new3 artifacts
dotnet new3 is ready!
Dans-MacBook-Air:templating dansiegel$ dotnet new3
System.ComponentModel.Win32Exception (0x80004005): No such file or directory
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, 
Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& 
stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

While I did manage to get a new template to install, trying to create or even access the help for an installed template still results as follows:

```
Dans-MacBook-Air:NewAppTest dansiegel$ ../templating/dev/dotnet-new3 console
Error reading template from file: /Microsoft.DotNet.Common.ProjectTemplates.2.0/content/
ConsoleApplication-CSharp/.template.config/template.json | Error = Could not load file or 
assembly 'Microsoft.TemplateEngine.Core.Contracts, Version=1.0.0.0, Culture=neutral, 
PublicKeyToken=adb9793829ddae60'. An attempt was made to load a program with an 
incorrect format.

Object reference not set to an instance of an object.
Dans-MacBook-Air:NewAppTest dansiegel$ ../templating/dev/dotnet-new3 console --help
Template Instantiation Commands for .NET Core CLI

Usage: new3 [options]

Options:
  -h, --help          Displays help for this command.
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
  -o, --output        Location to place the generated output.
  -i, --install       Installs a source or a template pack.
  -u, --uninstall     Uninstalls a source or a template pack.
  --type              Filters templates based on available types. Predefined values are "project", "item" or "other".
  --force             Forces content to be generated even if it would change existing files.
  -lang, --language   Specifies the language of the template to create.


Console Application (C#)
Author: Microsoft
Error reading template from file: /Microsoft.DotNet.Common.ProjectTemplates.2.0/content/
ConsoleApplication-CSharp/.template.config/template.json | Error = Could not load file or
assembly 'Microsoft.TemplateEngine.Core.Contracts, Version=1.0.0.0, Culture=neutral, 
PublicKeyToken=adb9793829ddae60'. An attempt was made to load a program with an 
incorrect format.

Object reference not set to an instance of an object.
   at Microsoft.TemplateEngine.Cli.New3Command.GetTemplateUsageInformation(ITemplateInfo
templateInfo, IParameterSet& allParams, IReadOnlyList`1& userParamsWithInvalidValues, Boolean&
hasPostActionScriptRunner)
   at Microsoft.TemplateEngine.Cli.New3Command.ShowTemplateGroupHelp(IList`1 templateGroup,
Boolean showImplicitlyHiddenParams)
   at Microsoft.TemplateEngine.Cli.New3Command.DisplayTemplateHelpForSingularGroup()
   at Microsoft.TemplateEngine.Cli.New3Command.<EnterSingularTemplateManipulationFlowAsync>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.TemplateEngine.Cli.New3Command.<EnterTemplateManipulationFlowAsync>d__56.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.TemplateEngine.Cli.New3Command.<ExecuteAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.TemplateEngine.Cli.CommandParsing.NewCommandInputCli.<>c__DisplayClass19_0.<<OnExecute>b__0>d.MoveNext()
```

**Comment by mlorbetske** [comment]
This will be fixed in #857

**Comment by mlorbetske** [comment]
This should be fixed now, you'll want to get rid of any symlinks in /usr/local/bin to dotnet-new3

**Comment by dansiegel** [comment]
@mlorbetske was finally able to run `setup.sh` and `dotnet new3` is working! Thanks for getting that fixed. :)

**Comment by mlorbetske** [comment]
No problem 😊  Sorry for the delay
