### ISSUE TITLE
Escape character in lunux ubuntu environment for custom template

### ISSUE THREAD

**Issue by satyajit-behera** [dotnet/templating#6298]
### Product

dotnet CLI (dotnet new)

### Describe The Bug

The escape sequence is ignored completely when the custom template runs in a linux environment. Same thing works fine in windows environment.

"\\<# ... \#>"
"Or for a file path, \\ is ignored when sent using a string variable in the custom template generation."

### To Reproduce

Create a custom template for dotnet new.

Execute the template in command prompt passing a variable containing escape sequence.

### dotnet Info

<details>
  <summary>output</summary>
  
  
  
  
</details>

**Comment by YuliiaKovalova** [comment]
Hi @satyajit-behera,

Thank you for reporting this issue. We are investigating it.

**Comment by YuliiaKovalova** [comment]
Hi @satyajit-behera,

Could you provide some additional information for us:
1. Which dotnet version do you use? (you can check it with `dotnet --info` command)
2. Could you provide an example of the command that you try to run (params, expected output, etc.)?

Thank you!

**Comment by YuliiaKovalova** [comment]
Close the ticket since the customer hasn't provided the requested information.
