### ISSUE TITLE
Add data migration for .templateengine\packages.json file

### ISSUE THREAD

**Issue by YuliiaKovalova** [dotnet/templating#6334]
After adding information about the package owner and prefixReserved presence, .templateengine\packages.json needs to be updated. 
![image](https://user-images.githubusercontent.com/95473390/229110620-2ad7af2e-1fd9-485d-a782-406514e38b86.png)

Currently, TE doesn't support this feature. The mechanism for data migration has existed before:
https://github.com/dotnet/sdk/blob/e025c3750e2a3ea66fd6854d45614582a97d22dd/src/Cli/dotnet/Program.cs#L196
https://github.com/dotnet/templating/blob/3ea9033de81a08f91ae513c649af1f3b3c8bbcd7/src/Microsoft.TemplateEngine.Edge/Settings/SettingsFilePaths.cs#L33

Open questions: should it be run for CLI only or global level.

**Comment by baronfel** [comment]
We should follow after what the NuGet team did here for a recent security fix - the template engine itself should provide two methods:

* is migration required?
* perform migration

and each Template Engine host should be responsible for calling them. in the CLI we'd add on to the existing first-run mechanism, but the VS host (and others) would need to check as well in whatever their 'initialize'/'startup/ methods are. We should consult with @phenning to make sure that the methods we expose are configurable enough - at minimum I'd expect that each method would somehow need to know where the path to the template engine caches are.

**Comment by YuliiaKovalova** [comment]
add for discussing https://github.com/dotnet/templating/issues/6128
