### ISSUE TITLE
Enable DI container scope validation by default for Development environment in all ASP.NET Core 2.0 templates

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/templating#640]
Update all the ASP.NET Core 2.0 templates to turn on scope validation when in the development environment, e.g.:
``` c#
public class Startup
{
    public Startup(IHostingEnvironment env)
    {
        HostingEnvironment = env;
    }

    public IHostingEnvironment HostingEnvironment { get; }

    public IServiceProvider ConfigureServices(IServiceCollection services)
    {
        // Set up container here...
        
        return services.BuildServiceProvider(validateScopes: HostingEnvironment.IsDevelopment());
    }

    public void Configure()
    {
        ...
    }
}
```

@glennc @davidfowl @pakrym @mlorbetske

**Comment by davidfowl** [comment]
That's not the beautiful new way to do it

**Comment by DamianEdwards** [comment]
@davidfowl please share the 🌷

**Comment by DamianEdwards** [comment]
@davidfowl *bump*

**Comment by pakrym** [comment]
Worked is moved to https://github.com/aspnet/MetaPackages/pull/61

**Comment by lukepuplett** [comment]
I was looking at the code behind CreateDefaultBuilder and documenting what the defaults are for my colleagues, I'm nice like that, but when it came to validating scopes, I'm not sure.

Can I ask for some background on why this is a good idea just for development? Not a loaded question, I literally am ignorant on what this does.

Thanks.

**Comment by davidfowl** [comment]
We didn't want the perf hit in production.

**Comment by pakrym** [comment]
And didn't want to unexpected exceptions from DI in production after migration to 2.0

**Comment by dazinator** [comment]
What is scope validation?

**Comment by davidfowl** [comment]
Scope validation makes sure your dependency graph doesn't have mismatched lifetimes (like depending on a scoped service from a singleton service). Read about "Captive dependencies" https://blog.ploeh.dk/2014/06/02/captive-dependency/

Simple injector also has a feature to detect this - https://simpleinjector.readthedocs.io/en/latest/LifestyleMismatches.html
