### ISSUE TITLE
 [Bug, Breaking change] default comment syntax not supported anymore for AXAML files

### ISSUE THREAD

**Issue by Mrxx99** [dotnet/templating#6409]
### Product

dotnet CLI (dotnet new)

### Describe The Bug

After implementation for https://github.com/dotnet/templating/issues/6156 the old comment syntax (`//#if`)  does not work anymore. This is now a a problem for the avalonia templates, because there it can't use the newly supported xml comment syntax yet because users could still be using .NET 6 or older .NET 7 versions where it is not yet supported.
On the issue itself I had added a note that the old syntax should still also be supported but that seems to have been overlooked.

### To Reproduce

Steps:
1. Make sure SDK preview 7.0.300-preview.23179.2 or higher is installed
2. Set this version with a global.json
3. Install avalonia templates `dotnet new install Avalonia.Templates`
4. Create new avalonia app with `dotnet new avalonia.app`
5. Open up App.axaml

You will see the //#if conditions in the file not resolved

For comparison you could do the same with SDK 7.0.202 where it sill works correctly.

### dotnet Info

Not relevant since set with global.json, see reproduce steps

### Additional context

Avalonia.Templates repo: https://github.com/AvaloniaUI/avalonia-dotnet-templates
App.axaml file: https://github.com/AvaloniaUI/avalonia-dotnet-templates/blob/master/templates/csharp/app/App.axaml

**Comment by YuliiaKovalova** [comment]
Hi @Mrxx99 , we are sorry to hear that. 

@GangWang01, could you take a look at what goes wrong here?

**Comment by YuliiaKovalova** [comment]
@Mrxx99, we have checked that dotnet/templating doesn't support 2 different comment syntaxes for the same file extension. After introducing changes, `.axaml` is treated as `.xml` and all corresponding rules are applied.

**Comment by YuliiaKovalova** [comment]
close as not a bug
