### ISSUE TITLE
Conditional processing newline handling problem

### ISSUE THREAD

**Issue by seancpeters** [dotnet/templating#65]
In some conditional processing situations, an extra newline is emitted. 
See ConditionalTests.VerifyExcludeNestedConditionInNonTakenBranch() for additional notes.
See ConditionalTests.VerifyExcludeNestedCondition() for an example where an extra newline is emitted. The expected result should not have the trailing newline.

**Comment by grinrag** [comment]
This bug is outdated (original date is Nov 2016), closing it now. Feel free reopen if it still valid.
