### ISSUE TITLE
Correcting a link in the wiki

### ISSUE THREAD

**Issue by andychiare** [dotnet/templating#6554]
Please, can you replace the current reference to Auth0 Templates in the _[Available templates for dotnet new](https://github.com/dotnet/templating/wiki/Available-templates-for-dotnet-new)_ wiki page? The old link is no longer valid, and a new version of the templates is now available.

Currently, it's on line 27:

Replace 
```
| [Auth0 Templates](https://github.com/auth0-community/auth0-dotnet-templates) | `dotnet new install "Auth0.Templates"` |
```

with

```
| [Auth0 Templates](https://github.com/auth0/auth0-dotnet-templates) | `dotnet new install Auth0.Templates::2.0.0"` |
```

**Comment by YuliiaKovalova** [comment]
The link was updated, thank you!
