### ISSUE TITLE
File > New > Project > Web > ASP.NET Core Web Application (.NET Core) is broken 

### ISSUE THREAD

**Issue by morrisjoe** [dotnet/templating#656]
Repro

- Install \\cpvsbuild\drops\VS\d15prerel\products\26423.01\bootstrappers\Enterprise
- Select workload of 'ASP.NET and web development'
- After successful VS install, check the version of .NET Core SDK/CLI installed. Confirm it is 2.0.0-preview1-005842
- File > New > Project > Web > ASP.NET Core Web Application (.NET Core)
- Pick Empty Project
- Pick Target Framework of ASP.NET.Core 2.0 from list box 
- Create Project

Expected: No errors in error list. Build and Run is a success
Actual: Error sin error list. Build fails. See image

![capture](https://cloud.githubusercontent.com/assets/12700391/25345443/f1494540-28c9-11e7-952c-d18e4818339e.PNG)

**Comment by mlorbetske** [comment]
At the command prompt, please run `dotnet new` and then try again. This will cause the CLI to expand its fallback folder & register it so that the restore in VS succeeds. I've repro'd and verified that this works.

**Comment by morrisjoe** [comment]
Ok. That workaround works. Noticed after the workaround, 1 warning still hangs around as shown in image below.

![capture](https://cloud.githubusercontent.com/assets/12700391/25350770/12c3c8ba-28db-11e7-9290-6e36f23b38e7.PNG)

**Comment by mlorbetske** [comment]
This is fixed in preview 1
