### ISSUE TITLE
Remove Microsoft.VisualStudio.Web.BrowserLink from MVC template

### ISSUE THREAD

**Issue by livarcocc** [dotnet/templating#658]
_From @JosephWoodward on April 24, 2017 14:31_

Before I create a pull request proposing changes I'm interested to know if there's any discussion around whether the `Microsoft.VisualStudio.Web.BrowserLink` should be included in the .NET Core CLI MVC template (this can be seen by running `dotnew new mvc`)

Given the .NET Core CLI supports cross platform and a variety of editors it seems odd that this package (which is specific to Visual Studio) is included by default and referenced within `startup.cs`.

A better solution would be to add the package as a second step if the project is created within Visual Studio. Alternatively whether the BrowserLink package could be made more general, allowing any IDE the ability to integrate with it. If that's the case then I feel a new package name would be in order.

_Copied from original issue: dotnet/cli#6394_

**Comment by mlorbetske** [comment]
@madskristensen thoughts?

**Comment by mlorbetske** [comment]
cc @barrytang

**Comment by jchannon** [comment]
Agree. dotnet is now xplat and needs to accommodate this so as suggested provide options in the template generation to add BrowserLink if the user wants it. An opt-in approach is always wins IMO.

**Comment by mlorbetske** [comment]
Current plan: add a parameter to the templates that use BrowserLink to indicate whether to include it that will be defaulted to `false`, VS will pass `true` for that parameter.

**Comment by JosephWoodward** [comment]
@mlorbetske Sounds like a great idea, glad to hear it's being looked at 👍

**Comment by sayedihashimi** [comment]
For Core projects can we enable BrowserLink in the same way that we are doing with AI? To be more specific can we do the automatic "Platform lightup" when running in VS so that we don't need the artifacts in the project? I think this would be a better user experience.

**Comment by mlorbetske** [comment]
@sayedihashimi I talked with @madskristensen about this. That's where we want to go for 2.0+; for the 1.x projects though, a switch is probably the best we can do.
