### ISSUE TITLE
`Failed to check the update for the package...` during template installation

### ISSUE THREAD

**Issue by MarcoRossignoli** [dotnet/templating#6611]
### Product

dotnet CLI (dotnet new)

### Describe The Bug

dotnet new templateName -o test1
The template "Template name" was created successfully.

 

Failed to check update for PackagaName::1.0.0-alpha.23267.2: Failed to check the update for the package PackagaName::1.0.0-alpha.23267.2.
Details: Value cannot be null. (Parameter 'releasePrefix')..

### To Reproduce

Call me for the repro, we don't have a public one.

cc: @vlada-shubina

**Comment by maridematte** [comment]
NuGet changed the behavior of one of their functions and it broke part of the restore process for template instantiation. I opened an issue on their repo (https://github.com/NuGet/Home/issues/12618) and we are waiting for an answer from them to see how we're going to fix this issue.

**Comment by MarcoRossignoli** [comment]
thanks

**Comment by YuliiaKovalova** [comment]
The issue will be fixed on Nuget Side
https://github.com/NuGet/NuGet.Client/pull/5198

**Comment by nohwnd** [comment]
The linked bug was fixed, and merged into 6.7.0.57 which is now in latest net8. https://github.com/dotnet/sdk/blob/main/eng/Versions.props#L63

**Comment by YuliiaKovalova** [comment]
> The linked bug was fixed, and merged into 6.7.0.57 which is now in latest net8. https://github.com/dotnet/sdk/blob/main/eng/Versions.props#L63

Great,  thank you 😊
