### ISSUE TITLE
Unexpected Internal Software Issue (EX_SOFTWARE)

### ISSUE THREAD

**Issue by JenniferPlothow** [dotnet/templating#6640]
[managing-accessibility-settings.md](https://github.com/dotnet/templating/files/11594038/managing-accessibility-settings.md)

**Comment by YuliiaKovalova** [comment]
Hi @JenniferPlothow ,

Could you please create a new issue following the template https://github.com/dotnet/templating/issues/new?assignees=&labels=&projects=&template=bug_report.yml? 

Thanks!
