### ISSUE TITLE
Update Razor Pages template to react to latest changes

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/templating#668]
- No longer need to [set pages root to "/Pages"](https://github.com/dotnet/templating/blob/rel/vs2017/post-rtw/template_feed/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/RazorPagesWeb-CSharp/Startup.cs#L27) as that's the framework default
- No longer need to use full paths to views like [here](https://github.com/dotnet/templating/blob/rel/vs2017/post-rtw/template_feed/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/RazorPagesWeb-CSharp/Pages/_ViewStart.cshtml#L2). Just do `Layout = "_Layout";`
- Change About and Contact page to set page message through a property on the page model, **not** through `ViewData`, like [this](https://github.com/DamianEdwards/RazorPagesSample/blob/master/RazorPagesWebApplication/Pages/About.cshtml.cs#L15)

@mlorbetske @rynowak

**Comment by mlorbetske** [comment]
Fixed by #684
