### ISSUE TITLE
Add authentication to Razor Pages project template

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/templating#669]
The authentication & identity features from the regular MVC project template need to be "pagified" and added to the Razor Pages project template.

Use the [example here](https://github.com/DamianEdwards/RazorPagesSample/tree/master/RazorPagesWebApplication/Pages/Account) as a guide.

This will need to include changes for Authentication 2.0 and the Identity Services features when they land. It should also include the options for org auth, etc.

@mlorbetske @danroth27

**Comment by sayedihashimi** [comment]
We have the following auth types in the One ASP.NET dialog

 - Individual Auth
 - Work and School
 - Windows Auth

Is this issue specific to Individual Auth? If so, what about Win and Work & School?

**Comment by danroth27** [comment]
We should have the same auth options for Razor Pages that we do for MVC.

**Comment by mlorbetske** [comment]
@phenning could you drive this please?

**Comment by mlorbetske** [comment]
@danroth27 we can close this now right? All the options that should be there (I think) are there.

**Comment by danroth27** [comment]
Yup, fixed by https://github.com/dotnet/templating/pull/980
