### ISSUE TITLE
Support using templates directly from [github] URL

### ISSUE THREAD

**Issue by flytzen** [dotnet/templating#674]
One thing that would really help is to remove the need to *install* templates locally.
Something like
```dotnet new https://github.com/bob/supertemplate```
or
```dotnet new -t https://github.com/bob/supertemplate```

Installing templates locally is *friction* and also leads to ongoing versioning issues, especially for use internally in an organisation.

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by donJoseLuis** [comment]
the last update was ~ 3years ago.  Pleas reactivate if this is still desired
