### ISSUE TITLE
[Microsoft.Build] Investigate non-deterministic test behavior 

### ISSUE THREAD

**Issue by YuliiaKovalova** [dotnet/templating#6781]
### Product

dotnet CLI (dotnet new)

### Describe The Bug

When a new item template is instantiated, the warning "Failed to evaluate bind symbol 'langVersion', it will be skipped." is generated **sometimes**.

Identify what triggers this scenario.
Can be reproduced in the src/Tests/dotnet-new.Tests/DotnetClassTemplateTests.cs tests

### To Reproduce

Steps:
1. Go to src/Tests/dotnet-new.Tests/DotnetClassTemplateTests.cs
2. Comment custom scrubber that removes the warning message
3. Run tests a couple of times.  

### dotnet Info

release/7.2.0xx

**Comment by YuliiaKovalova** [comment]
@GangWang01 , if you have some time, could you check the output for project templates having the same parameters as in tests?

**Comment by GangWang01** [comment]
> @GangWang01 , if you have some time, could you check the output for project templates having the same parameters as in tests?

Attached the generated project and debug log by running local custom tests that instantiate Console Application CSharp and Class Library CSharp [output.zip](https://github.com/dotnet/templating/files/11817684/output.zip) without language version specified.

**Comment by YuliiaKovalova** [comment]
In order to handle this restriction we recommend introducing a generated symbol for langVersion:
```
    // symbol with langVersion extracted from MSBuild
    "evaluatedLangVersion": {
      "type": "bind",
      "binding": "msbuild:LangVersion",
      "dataType": "string"
    },

    // default langVersion value
    "latestLangVersion": {
      "type": "generated",
      "generator": "constant",
      "parameters": {
        "value": "latest"
      }
    },

    // if "evaluatedLangVersion" is empty, the value will be taken from "latestLangVersion" symbol
    "langVersion": {
      "type": "generated",
      "generator": "coalesce",
      "parameters": {
        "sourceVariableName": "evaluatedLangVersion",
        "fallbackVariableName": "latestLangVersion"
      }
    }, 
```
For getting more info on generated symbols check out the wiki page: https://github.com/dotnet/templating/wiki/Available-Symbols-Generators .
