### ISSUE TITLE
dotnet new details - UI/localization issues

### ISSUE THREAD

**Issue by YuliiaKovalova** [dotnet/templating#6813]
### Product

dotnet CLI (dotnet new)

### Describe The Bug

UI issues are described below.

### To Reproduce

1. run
`dotnet new details testPackage`
![image](https://github.com/dotnet/templating/assets/95473390/fe593ac2-a7a8-4a16-8c97-a1e6b30f41c8)

"To search for the template **packages** on NuGet.org, run:
        dotnet new search --package testPackage"
 `dotnet new search` searches by template names only.
2. run
`dotnet new details Microsoft.Android.Templates`
![image](https://github.com/dotnet/templating/assets/95473390/eb490f03-a97f-40b3-8998-668814fbc1ac)
Please rename the property "Prefix Reserved" for consistency with `dotnet new uninstall `command:
![image](https://github.com/dotnet/templating/assets/95473390/d7e9a218-cb80-4fa2-9695-6701f9a2f9d9)
3. run
` dotnet new details -h`
![image](https://github.com/dotnet/templating/assets/95473390/ee8688fd-47bb-4842-824b-8aaf9a8386f1)
The argument for this command has a different description.

### dotnet Info

.net 8 preview 7

**Comment by maridematte** [comment]
About 1. `dotnet new search` also looks for package names when the `--package` flag is passed, so that error message is correct.
