### ISSUE TITLE
Enhance EntityFramework Provider options in Templates

### ISSUE THREAD

**Issue by dansiegel** [dotnet/templating#698]
The templates currently provide a possible outcome for generating a template using either SqlServer or Sqlite. I think that this could be further enhanced by providing choices for the EntityFramework Provider. 

- SqlServer => Microsoft.EntityFrameworkCore.SqlServer
- SQLite => Microsoft.EntityFrameworkCore.SQLite
- MySQL => MySql.Data.EntityFrameworkCore
- PostgreSQL => Npgsql.EntityFrameworkCore.PostgreSQL
- In Memory => Microsoft.EntityFrameworkCore.InMemory

**Comment by sayedihashimi** [comment]
I would like to expand the list of options as well. I would love some community help in this area.

**Comment by sayedihashimi** [comment]
Any community members interested in sending a PR?

**Comment by dansiegel** [comment]
I'm happy to take a look at this over the weekend.

**Comment by sayedihashimi** [comment]
@dansiegel thanks! I'll mark the item as assigned. Let me know if you need any info or decide to move on from the feature.

**Comment by sayedihashimi** [comment]
@dansiegel it looks like I can assign this item to you. I'll assign it to you, so that we know someone is looking at it.

**Comment by dansiegel** [comment]
For MySql there are actually three different providers. The Official MySql package is also the only one that has yet to release a stable package. Is there a preference to only support the Official MySql provider, all three, or .....

**Comment by dansiegel** [comment]
@sayedihashimi another question for you, and I suppose this could be an issue of it's own as well.

Will the `2017.3.host.json` need updating so that you can choose the EF Provider from within Visual Studio? From looking at the spec it seems like the host file is pretty much set for custom template dialogs centered around web projects. I don't know if maybe this would be an area where you could work with the VS team to expand the spec so Templates can provide a more customized new Project Dialog based on the ever changing needs of the templates.

**Comment by mlorbetske** [comment]
@dansiegel we are the VS team for that too 😉 We're doing a bunch of work right now to provide a UI that can adapt to the options the template has available & some of those capabilities will flow back in to the web project creation (OneASP.NET) dialog. This could certainly be one of those capabilities.

**Comment by sayedihashimi** [comment]
FYI we are having discussions with the team that owns the broader File->New Project experience to get 1st class support for Template Engine templates. Those discussions are more long term discussions. The discussions recently got started. I will keep you posted on progress.

**Comment by dansiegel** [comment]
Since I'm on a Mac about 90% of the time, I do hope this is being done for VS for Mac as well? And hopefully we'll see a parallel or near parallel release?

**Comment by sayedihashimi** [comment]
@dansiegel everything that we do will target VS and VS4Mac from now on. In VS4Mac we have a lot of catch up to do so I'm not sure where it will land priority wise, but we are not in the business of developing VS specific tooling anymore.
From a template perspective we are already working with the VS4Mac team to integrate the Template Engine. That will first be happening for .NET Core projects but it will fan out from there. When you hear me speaking I'll discuss "Visual Studio" but I'm always thinking about VS4Mac as well.

**Comment by dansiegel** [comment]
@sayedihashimi good to hear. With my templates targeting Xamarin I want to be sure that I can provide a first class experience regardless of platform. I'm happy to get you and the VS4Mac team the templates for testing.

More on topic for this thread though... any thoughts on my previous question:

>For MySql there are actually three different providers. The Official MySql package is also the only one that has yet to release a stable package. Is there a preference to only support the Official MySql provider, all three, or .....

**Comment by sayedihashimi** [comment]
@natemcmaster any thoughts on the MySql provider that should be used if we add a `mysql` option to the templates? As @dansiegel indicates there are several packages we can use. Have you used any of them?

**Comment by natemcmaster** [comment]
@sayedihashimi -  @divega would have a more informed opinion on this one. When I left EF, the mysql providers were still half-baked.

**Comment by divega** [comment]
The three MySQL EF Core providers I know about are [SapientGuardian.EntityFrameworkCore.MySql](https://www.nuget.org/packages/SapientGuardian.EntityFrameworkCore.MySql/), [Pomelo.Data.MySql](https://www.nuget.org/packages/Pomelo.Data.MySql/) and the official [MySql.Data.EntityFrameworkCore](https://www.nuget.org/packages/MySql.Data.EntityFrameworkCore/) from the MySQL team. And I can't think of a good way to pick one of them over the others right now. 

I am starting to wonder if we could figure out a way to let providers plug in instead of us having to keep a hardcoded lists. Was this every considered?

BTW, none of the MySQL providers support 2.0 yet. Are the templates only about 2.x or do they work for 1.x?

**Comment by mlorbetske** [comment]
@divega in terms of integrating them with the template content, we don't have template feature level template extensibility at this time (we'd need to think hard about what that means - it's likely more of a post-generation or standalone scaffolding experience as it can impact otherwise static template content at a point where there isn't a semantic understanding of the documents being generated). Extensibility of that form would likely do well after the work to support template chaining (assuming this doesn't have implications on the initial migration or that those can be generated easily).

**Comment by divega** [comment]
@mlorbetske thanks. I think it could be worth brainstorming. Perhaps this is something we can do as a standalone step as you mentioned.

Anyway, do you know the answer to my other question?

> BTW, none of the MySQL providers support 2.0 yet. Are the templates only about 2.x or do they work for 1.x?

**Comment by dansiegel** [comment]
> BTW, none of the MySQL providers support 2.0 yet. Are the templates only about 2.x or do they work for 1.x?

@divega the goal was to have it on 1.x and 2.x templates. I though 1.x libraries work with 2.0?

> The three MySQL EF Core providers I know about are SapientGuardian.EntityFrameworkCore.MySql, Pomelo.EntityFrameworkCore.MySql and the official MySql.Data.EntityFrameworkCore from the MySQL team. And I can't think of a good way to pick one of them over the others right now.

From what I've seen, it appears the"official" MySQL package has had the least amount of effort. Based on the download counts, it would appear that the Pomelo package is probably the most popular.

**Comment by mlorbetske** [comment]
@divega there are separate templates for 1.x and 2.0 (but they show as a single template when both are installed at the same time). The 1.x templates don't ship with the 2.0 CLI, but they are consumed by VS & VS4M

**Comment by mlorbetske** [comment]
Moved to aspnet/templating#615
