### ISSUE TITLE
Consider adding an xunit.runner.json to xunit projects

### ISSUE THREAD

**Issue by rynowak** [dotnet/templating#704]
There's a bunch of useful settings for xunit that are only configurable via the `xunit.runner.json` file, but it's not very discoverable. See https://xunit.github.io/docs/configuring-with-json.html

We should think about including this in the templates.

This has come up many times for projects that test ASP.NET MVC and it usually looks something like this: https://github.com/aspnet/Razor/issues/1212#issuecomment-297885722 The common case for us is that we need to disable shadow copy.

**Comment by sayedihashimi** [comment]
@rynowak I'm not familiar with this file. Can you help me understand when the file is needed and when it is not needed? What % of xunit projects are likely to need that file?

**Comment by rynowak** [comment]
> Can you help me understand when the file is needed and when it is not needed? 

> There's a bunch of useful settings for xunit that are only configurable via the xunit.runner.json file, but it's not very discoverable. See https://xunit.github.io/docs/configuring-with-json.html

This file isn't needed if you want to use the default settings. 

The link that linked to is the description of what kinds of things are configurable. We frequently need to use this file to disable shadow copying. Another common use is so configure how xunit displays the test names in the test explorer in VS. You also use this to configure how tests are parallelized.

It looks like we're using this in our repos about 10% of the time, which is a little less than I expected.

There's also a scheme so you can see what options are available. https://github.com/aspnet/KestrelHttpServer/blob/dev/test/Microsoft.AspNetCore.Server.Kestrel.Tests/xunit.runner.json#L2

**Comment by mlorbetske** [comment]
@sayedihashimi is this something we want to do? If so, where does this fit in in terms of the other things?

**Comment by mlorbetske** [comment]
This issue was moved to dotnet/test-templates#2
