### ISSUE TITLE
Token based Authentication

### ISSUE THREAD

**Issue by dansiegel** [dotnet/templating#707]
Authentication is something that honestly leaves a lot of dev's scratching their heads because it's not something they have to actively think about on a daily basis. Because Token Based authentication is much easier for a dev to work with for connecting their Xamarin Application, the templates should include this either as a new default. If any additional setup is required within the template to ensure they are following best practices, it should be noted either with instructions in the comments or a call to action with a link to one or more articles that can help them get the information they need. 

As an example, if the configuration uses a temporary signing certificate, then there should be documentation for how to use a permanent one with IIS, with Kestrel, and with an Azure App Service.

**Comment by sayedihashimi** [comment]
@dansiegel we are working on something that aligns with this I believe. @danroth27 can you comment?

**Comment by dansiegel** [comment]
@sayedihashimi I thought I might have seen something about Token based auth... just an issue I know has certain been something slowing me down on some projects, and had stumped several dev's I've spoken with. So I wanted to be sure it was something on this team's radar :)

**Comment by danroth27** [comment]
In PR: https://github.com/dotnet/templating/pull/700

**Comment by mlorbetske** [comment]
#700 has been merged
