### ISSUE TITLE
Wrong subscription?

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/templating#7181]
```
https://github.com/dotnet/roslyn-analyzers (.NET 7.0.1xx SDK) ==> 'https://github.com/dotnet/templating' ('main')
  - Id: 809b68bf-a581-4be6-2240-08da53656ef1
  - Update Frequency: EveryWeek
  - Enabled: True
  - Batchable: False
  - PR Failure Notification tags:
  - Merge Policies:
    Standard
  - Last Build: 20221109.1 (31373ce8529c3d2f6b91e61585872160b0d7d7cd)
```

Why does roslyn-analyzers from the .NET 7 SDK ingest into dotnet/templating? cc @MiYanni

**Comment by MiYanni** [comment]
@joeloff Let's review the subscriptions to Templating together next week.

**Comment by joeloff** [comment]
This should be fixed now

https://github.com/dotnet/roslyn-analyzers (.NET 9.0.1xx SDK) ==> 'https://github.com/dotnet/templating' ('main')
  - Id: 809b68bf-a581-4be6-2240-08da53656ef1
  - Update Frequency: EveryWeek
  - Enabled: True
  - Batchable: False
  - PR Failure Notification tags:
  - Merge Policies:
    Standard
  - Last Build: 20231030.1 (cf0cf5520edcf81aecc4b1a9a689dbe9ec0f166f)
