### ISSUE TITLE
Consider adding framework version to default output when a project is created

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/templating#724]
After talking to @shanselman after a project is created on the CLI it would be nice to include the framework version (if known) that was created.

For example:

`
C:\Users\scott\Desktop\poop>dotnet new console
The template "Console Application - 2.0" was created successfully.
`

For templates that are not targetting .NET or when the target fx is not known we can leave that off.

Thoughts?

**Comment by mlorbetske** [comment]
Would the full TFM be ok instead? 

`The template "Console Application - netcoreapp2.0" was created successfully.`

**Comment by shanselman** [comment]
Sure, whatever you have lying around in context that wouldn't require you to do any lookups/transformations/maps or localization. ;)

**Comment by mlorbetske** [comment]
Those aren't the things I'm worried about though :) It's the class library case where there are netstandard1.0/netstandard1.1/netstandard2.0 and netcoreapp1.0/netcoreapp1.1/netcoreapp2.0 where a shortening to just the major/minor pair could be ambiguous.

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by donJoseLuis** [comment]
Though an old issue, let's include it in our roda map.

**Comment by vlada-shubina** [comment]
We will do this change in scope of https://github.com/dotnet/templating/issues/677, closing as duplicate.
