### ISSUE TITLE
Proposal to update help output

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/templating#725]
I was looking through the help output, and I think there are a few areas that we can improve.

To **start the discussion**, I've created a PR that captures the changes that I'm proposing at https://github.com/sayedihashimi/sayed-tools/pull/12. Below you'll find direct links for each command that I looked at.

adding @mlorbetske @seancpeters @shanselman @richlander 

| Command | diff from existing | proposed help output for command |
|---------|------|----------|
| `dotnet new` | [diff](https://github.com/sayedihashimi/sayed-tools/pull/12/files?diff=split#diff-9b1ffbd46b8a434b36df9a9ca756027d) | [proposal](https://raw.githubusercontent.com/sayedihashimi/sayed-tools/d68bac2c3c8eb7fdd596d9382b2a1aa50ae0cef1/powershell/dotnet/help-output/21.dotnet-new3.cmd.txt) | 
| `dotnet new -h` | [diff](https://github.com/sayedihashimi/sayed-tools/pull/12/files?diff=split#diff-61c269f6859c7a4c54a3aa0d317aa148) | [proposal](https://raw.githubusercontent.com/sayedihashimi/sayed-tools/d68bac2c3c8eb7fdd596d9382b2a1aa50ae0cef1/powershell/dotnet/help-output/22.dotnet-new3%20-h.cmd.txt) | 
| `dotnet new -l` | [diff](https://github.com/sayedihashimi/sayed-tools/pull/12/files?diff=split#diff-7dc9c95b37116e7cc3e77c05b0d8e8bc) | [proposal](https://raw.githubusercontent.com/sayedihashimi/sayed-tools/d68bac2c3c8eb7fdd596d9382b2a1aa50ae0cef1/powershell/dotnet/help-output/23.dotnet-new3%20-l.cmd.txt) | 
| `dotnet new console -h` | [diff](https://github.com/sayedihashimi/sayed-tools/pull/12/files?diff=split#diff-1c23296eb34adc37f5de8e14875a7890) | [proposal](https://raw.githubusercontent.com/sayedihashimi/sayed-tools/d68bac2c3c8eb7fdd596d9382b2a1aa50ae0cef1/powershell/dotnet/help-output/24.dotnet-new3%20console%20-h.cmd.txt) | 
| `dotnet new classlib -h` | [diff](https://github.com/sayedihashimi/sayed-tools/pull/12/files?diff=split#diff-bcc1c66e00f19de294c002c547d3878d) | [proposal](https://raw.githubusercontent.com/sayedihashimi/sayed-tools/d68bac2c3c8eb7fdd596d9382b2a1aa50ae0cef1/powershell/dotnet/help-output/25.dotnet-new3%20classlib%20-h.cmd.txt) | 
| `dotnet new mstest -h` | [diff](https://github.com/sayedihashimi/sayed-tools/pull/12/files?diff=split#diff-91681a0e478f51c11714578832d62aba) | [proposal](https://raw.githubusercontent.com/sayedihashimi/sayed-tools/d68bac2c3c8eb7fdd596d9382b2a1aa50ae0cef1/powershell/dotnet/help-output/26.dotnet-new3%20mstest%20-h.cmd.txt) | 
| `dotnet new xunit -h` | [diff](https://github.com/sayedihashimi/sayed-tools/pull/12/files?diff=split#diff-8764a28cd58e55350846329e839ba2a1) | [proposal](https://raw.githubusercontent.com/sayedihashimi/sayed-tools/d68bac2c3c8eb7fdd596d9382b2a1aa50ae0cef1/powershell/dotnet/help-output/27.dotnet-new3%20xunit%20-h.cmd.txt) | 
| `dotnet new web -h` | [diff](https://github.com/sayedihashimi/sayed-tools/pull/12/files?diff=split#diff-d1156761fab1ac309e123839b7f82b40) | [proposal](https://raw.githubusercontent.com/sayedihashimi/sayed-tools/d68bac2c3c8eb7fdd596d9382b2a1aa50ae0cef1/powershell/dotnet/help-output/28.dotnet-new3%20web%20-h.cmd.txt) | 
| `dotnet new mvc -h` | [diff](https://github.com/sayedihashimi/sayed-tools/pull/12/files?diff=split#diff-14c000bbc7be4b8181ac1d62fea027ed) | [proposal](https://raw.githubusercontent.com/sayedihashimi/sayed-tools/d68bac2c3c8eb7fdd596d9382b2a1aa50ae0cef1/powershell/dotnet/help-output/29.dotnet-new3%20mvc%20-h.cmd.txt) | 
| `dotnet new webapi -h` | [diff](https://github.com/sayedihashimi/sayed-tools/pull/12/files?diff=split#diff-ff001c0ac82877aa62b67c9ad022247d) | [proposal](https://raw.githubusercontent.com/sayedihashimi/sayed-tools/d68bac2c3c8eb7fdd596d9382b2a1aa50ae0cef1/powershell/dotnet/help-output/30.dotnet-new3%20webapi%20-h.cmd.txt) | 
| `dotnet new sln -h` | [diff](https://github.com/sayedihashimi/sayed-tools/pull/12/files?diff=split#diff-2adca27734058eb637f5a191e1c83b0b) | [proposal](https://raw.githubusercontent.com/sayedihashimi/sayed-tools/d68bac2c3c8eb7fdd596d9382b2a1aa50ae0cef1/powershell/dotnet/help-output/31.dotnet-new3%20sln%20-h.cmd.txt) | 
| `dotnet new we -l` | [diff](https://github.com/sayedihashimi/sayed-tools/pull/12/files?diff=split#diff-36b0654ed8bac9ede917b0abf9fd50bb) | [proposal](https://raw.githubusercontent.com/sayedihashimi/sayed-tools/d68bac2c3c8eb7fdd596d9382b2a1aa50ae0cef1/powershell/dotnet/help-output/32.dotnet-new3%20we%20-l.cmd.txt) | 
| `dotnet new -l -lang F#` | [diff](https://github.com/sayedihashimi/sayed-tools/pull/12/files?diff=split#diff-ef29d46365b23f654dfa38d89caa2cd8) | [proposal](https://raw.githubusercontent.com/sayedihashimi/sayed-tools/d68bac2c3c8eb7fdd596d9382b2a1aa50ae0cef1/powershell/dotnet/help-output/33.dotnet-new3%20-l%20-lang%20F#.cmd.txt) | 
| `dotnet new -l -lang NotExists` | [diff](https://github.com/sayedihashimi/sayed-tools/pull/12/files?diff=split#diff-94a55c235d712733cde8d02869c1f709) | [proposal](https://raw.githubusercontent.com/sayedihashimi/sayed-tools/d68bac2c3c8eb7fdd596d9382b2a1aa50ae0cef1/powershell/dotnet/help-output/34.dotnet-new3%20-l%20-lang%20NotExists.cmd.txt) | 
| `dotnet new NotExists` | [diff](https://github.com/sayedihashimi/sayed-tools/pull/12/files?diff=split#diff-638fa80ba5d8b454c33724b256ea8f19) | [proposal](https://raw.githubusercontent.com/sayedihashimi/sayed-tools/d68bac2c3c8eb7fdd596d9382b2a1aa50ae0cef1/powershell/dotnet/help-output/35.dotnet-new3%20NotExists.cmd.txt) | 
| `dotnet new --install -h` | [diff](https://github.com/sayedihashimi/sayed-tools/pull/12/files?diff=split#diff-a5c12d0d3e5643dc60e013dad95bc51c) | [proposal](https://raw.githubusercontent.com/sayedihashimi/sayed-tools/d68bac2c3c8eb7fdd596d9382b2a1aa50ae0cef1/powershell/dotnet/help-output/36.dotnet-new3%20--install%20-h.cmd.txt) | 
| `dotnet new --uninstall -h` | [diff](https://github.com/sayedihashimi/sayed-tools/pull/12/files?diff=split#diff-6085e18fc6aa2fe22158418886078d9e) | [proposal](https://raw.githubusercontent.com/sayedihashimi/sayed-tools/d68bac2c3c8eb7fdd596d9382b2a1aa50ae0cef1/powershell/dotnet/help-output/37.dotnet-new3%20--uninstall%20-h.cmd.txt) |

**Comment by mlorbetske** [comment]
What would the proposed verbosity switch do in non-default modes (assuming the current output is the default verbosity)?

Quiet is obvious, but would detailed for example start printing the operations being performed/files being manipulated/etc.?

**Comment by sayedihashimi** [comment]
@mlorbetske for verbosity maybe we should just have on/off. The other commands are calling MSBuild so it makes sense for the diagnostic/detailed/minimal/quiet. But for templating maybe thats overkill. I can update it to be a switch instead of having parameter values. Does that make more sense?

**Comment by sayedihashimi** [comment]
Also adding @andrew-msft

**Comment by sayedihashimi** [comment]
FYI the team is going to review this proposal tomorrow. If the community has any comments please let us know, ideally before tomorrow if possible.

**Comment by sayedihashimi** [comment]
FYI the team is going to review this proposal tomorrow. If the community has any comments please let us know, ideally before tomorrow if possible.

**Comment by RehanSaeed** [comment]
Any updates.

There is far too much white space in custom arguments I've setup in my template. Multiple blank likes everywhere.

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by donJoseLuis** [comment]
Hello @grinrag, please create an issue for each distinct proposal and...

1. label them "needs-prioritization"
1. add them to the "dotnet new help" project
1. bring them up, asap in our next triage

**Comment by richlander** [comment]
I am curious what we are doing in this space. The `dotnet new` experience needs be fully thought through, IMO.

/cc @KathleenDollard

**Comment by grinrag** [comment]
I have split this issue into several small ones. There are several reasons:

1. different proposals have could have different priority
3. some of these proposals are duplicates
4. we can start to work on those items independently and close and deliver them sooner.

All of these items + additional requests about help improvement were put [dotnet new HELP](https://github.com/dotnet/templating/projects/11). After triage, we will assign priorities to them.

**Comment by grinrag** [comment]
list of new items:

- general help information (`dotnet new` , `dotnet new -h`) #2342
- listing of available templates (`dotnet new -l`, `dotnet new -l -lang F#`, `dotnet new we -l`, `dotnet new -l -lang NotExists`) #2346
- the error message, when the provided template doesn't exist  (`dotnet new dotnet new -l -lang NotExists`) #2347 
- more information for the install and uninstall options (`dotnet new --install -h`, `dotnet new --uninstall -h`) #2348 
- if `-h` option is after a template name, we should the information about the template #2349

**Comment by KathleenDollard** [comment]
@richlander Understanding/triaging existing bugs and creating a path is part of the process.

**Comment by donJoseLuis** [comment]
Please track the individual issues called out above by @grinrag .
