### ISSUE TITLE
Xamarin Templates

### ISSUE THREAD

**Issue by dansiegel** [dotnet/templating#729]
I was working on some Xamarin templates and was running into a couple of issues that hopefully someone might have some ideas on how to best handle. The core project is converted over to NetStandard1.4 using the new csproj format, but the Android and iOS projects are still using the older format. I'm sure I'm missing something simple. 

1. I want the template to generate an `#if DEBUG` in the iOS template to enable testing. but obviously this gets stripped out by the templating engine. Is there a way to get the templating engine to ignore that directive?

2. I have a XAML file that needs to change a namespace import depending on which choice they made but I haven't been able to get any conditional lines to work. I had been trying something like the following but it gets totally ignored and the generated project looks exactly the same. 

``` xml
<prism:PrismApplication xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
<!--if UseAutofac -->
             xmlns:prism="clr-namespace:Prism.Autofac;assembly=Prism.Autofac.Forms"
<!--elif UseDryIoc -->
             xmlns:prism="clr-namespace:Prism.DryIoc;assembly=Prism.DryIoc.Forms"
<!--elif UseNinject -->
             xmlns:prism="clr-namespace:Prism.Ninject;assembly=Prism.Ninject.Forms"
<!--else -->
             xmlns:prism="clr-namespace:Prism.Unity;assembly=Prism.Unity.Forms"
<!--endif -->
             x:Class="MobileApp.App">
``` 

3. Similar to the XAML issue is for the packages.config on the platform project

**Comment by sayedihashimi** [comment]
For the #if debug it sounds like the same issue as https://github.com/dotnet/templating/issues/587

**Comment by dansiegel** [comment]
@sayedihashimi that was the missing link... since the issue is already being tracked I'm going to close this issue.

**Comment by dansiegel** [comment]
@sayedihashimi it looks like I'm still running into a couple issues with my templates.

1) I haven't been able to prevent the templating engine from removing elements or blocks in my csproj file that require conditional statements. See the [iOS csproj](https://github.com/dansiegel/Prism-Templates/blob/master/content/MobileApp-CSharp/src/MobileApp.iOS/MobileApp.iOS.csproj#L4) for an example. I have tried wrapping these areas with `-:cnd` and `+:cnd` without any change in behavior

2) I have some computed symbols based on a [choice](https://github.com/dansiegel/Prism-Templates/blob/master/content/MobileApp-CSharp/.template.config/template.json#L90) in my template.json, and I'm yet all of these computed symbols are evaluating as false. 

3) The [dotnetcli.host.json](https://github.com/dansiegel/Prism-Templates/blob/master/content/MobileApp-CSharp/.template.config/dotnetcli.host.json) is being completely ignored.

**Comment by sayedihashimi** [comment]
@dansiegel can you share a sample?

**Comment by mlorbetske** [comment]
For conditions in XML & proj files, the syntax for ignoring conditions is `<!--/-:cnd:noEmit -->` and  `<!--/+:cnd:noEmit -->` (note that this is not available in the 1.0.x CLI, it's being fixed to include it in the 2.0.0-preview1+ CLI, VS & VS4M).

For 2 & 3 can you hook up with @seancpeters to debug?

**Comment by dansiegel** [comment]
@mlorbetske thanks, that did the trick. I had tried that as `<!---:cnd-->`, `<!-- -:cnd -->`, `<!--//-:cnd -->`, and even just `//-cnd` each with and without the `noEmit`. I'm using the latest available 2.0 version of the cli.

@sayedihashimi @seancpeters I linked directly to the files above. The project can be found [here](https://github.com/dansiegel/Prism-Templates)

**Comment by seancpeters** [comment]
@dansiegel I wrote up a pretty detailed explanation of the -:cnd +:cnd type syntax in #627 - - it may be helpful.

**Comment by dansiegel** [comment]
I took at look at the schema and found the problem with the dotnetcli.host.json file. Thanks @madskristensen 

Also looks like problem I was having with some of the computed symbols wasn't actually with the symbols themselves, but how I was using them.

```cs
#if SymbolA
using SomeNamespace;
#elif SymbolB
using AnotherNamespace;
#else
using SomeOtherNamespace;
#endif
```

What finally did work was to change it to only evaluate a single symbol like the following:

```cs
#if SymbolA
using SomeNamespace;
#endif
#if SymbolB
using AnotherNamespace;
#endif
#if SymbolC
using SomeOtherNamespace;
#endif
```

The only problem is that I haven't been able to get it working in the `packages.config` files.

If I have the following in a XAML file it works fine

```xml
<!--#if SymbolA -->
<Label Text="Was Symbol A" />
<!--#else -->
<Label Text="Wasn't Symbol A" />
<!--#end -->
```

But this doesn't work in the packages.config

```xml
<!--#if SymbolA -->
<package id="SomePackage" version="1.0.0" targetFramework="monoandroid71" />
<!--#else -->
<package id="AnotherPackage" version="1.0.0" targetFramework="monoandroid71" />
<!--#end -->
```

**Comment by mlorbetske** [comment]
It looks like `packages.config` isn't covered in the [default configurations](https://github.com/dotnet/templating/blob/9703a93a90c6cb91e4d265857c54963102c27ef6/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/SimpleConfigModel.cs#L405-L428). It should be possible to add the handling for it to the template.json for the time being similar to how [this](https://github.com/dotnet/templating/issues/237) added support for xaml before it made it in to the defaults.

**Comment by dansiegel** [comment]
Thanks @mlorbetske. PR #762 looks good, definitely has support for some files in Xamarin templates that I may want to get crazy with down the road.
