### ISSUE TITLE
Add inferred param types to template cache

### ISSUE THREAD

**Issue by seancpeters** [dotnet/templating#740]
This will make it easier to use the cache info in hosts, particularly VS - @phenning

**Comment by mlorbetske** [comment]
@seancpeters is this still open? Moving it to the backlog for now

**Comment by donJoseLuis** [comment]
This issue was last touched some years ago.  We are working on a new delivery road map.  Please reopen if this is something we want & we'll properly assess its' priority compared to other work aimed at improving the overall templating UX
