### ISSUE TITLE
Add an EmbeddedResource

### ISSUE THREAD

**Issue by grokys** [dotnet/templating#767]
I need to add an `<EmbeddedResource>` to the `.csproj` in my template. I've looked through the examples and it would seem I need an `ActionId`, is there one for adding embedded resources? Are the available action IDs listed anywhere?

**Comment by sayedihashimi** [comment]
@grokys are you asking how you can create a project template which lays down a .resx file? If so, in that case it's no different from creating a regular template. There should be no need for a post action.

**Comment by grokys** [comment]
Hi @sayedihashimi, no I want to create an item template and I need to add an `<EmbeddedResource>` element to the `.csproj` for the file that's is being added.

Also, I wondered if the available action IDs are listed anywhere, they seem to be magic numbers without any explanation afaics.

**Comment by sayedihashimi** [comment]
I see you're creating an item template, and it needs to get listed in the .csproj. Let's see what the team says.

About the ActionID we have a wiki page at  https://github.com/dotnet/templating/wiki/Post-Action-Registry

**Comment by dansiegel** [comment]
@grokys I see you're embedding XAML files. Your best bet is to update the way you handle the XAML files in your csproj. Oren has a great write up on how to do this on his [blog](https://oren.codes/2017/04/23/using-xamarin-forms-with-net-standard-vs-2017-edition/).

**Comment by grokys** [comment]
Thanks @dansiegel - I'd actually just remembered that you can do that (we already do it elsewhere)! The link to the post action registry was useful anyway ;)
