### ISSUE TITLE
Post Action Certificate Creation

### ISSUE THREAD

**Issue by dansiegel** [dotnet/templating#770]
It would be highly valuable for a number of templates from UWP to Web to include a built in post action to create a self signed certificate for the project. In the case of UWP I believe this would need to also update the manifest while a web template wouldn't have such a requirement. 

Having this as a built in post action would alleviate the need to write a custom script for each template requiring such a process or for the user to opt-in to running the scripts.

**Comment by mlorbetske** [comment]
The current plan of record (no timeline yet though) for this is to offer the ability to create a certificate as a standalone tool & to pass in the certificate to the template as a set of parameters. Once that works, we're playing around with the notion of pre-actions that would work just like post-actions with the exception that they'd be able to generate input values - effectively combining the steps of generate the cert & tell the template about the aspects of it that need to be included in the created content.

**Comment by mlorbetske** [comment]
Related to https://github.com/aspnet/DotNetTools/issues/296

**Comment by mlorbetske** [comment]
Talked with @javiercn and it looks like we may be able to borrow some bits from https://github.com/aspnet/DotNetTools/tree/dev/src/Microsoft.AspNetCore.CertificateGeneration.Task to make this happen

**Comment by javiercn** [comment]
@mlorbetske I forgot to mention that the APIs are netcoreapp2.0 only, not sure if that will pose a problem for you.

**Comment by dansiegel** [comment]
@javiercn isn't 2.0 supposed to be compatible with everything under the sun like UWP and Xamarin?

**Comment by mlorbetske** [comment]
@dansiegel the main issue is that the projects in this repo all target netcoreapp1.1 or netstandard1.x ;) Working on a plan - thinking it may be possible to define this post action off at the edges (CLI, VS, VS4Mac) to where we don't need to worry about that particular aspect.

**Comment by poveilleux** [comment]
Hi,
Has there been some work done on this recently?
Thanks!

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by vlada-shubina** [comment]
We would like to get more recent feedback on the issue as it is quite old:
- is this feature still needed?
- can it be worked around by using [Run script](https://github.com/dotnet/templating/wiki/Post-Action-Registry#run-script) post action? 

One of the possible solutions can be that we create new post action that internally calls `dotnet dev-certs` for certificate creation. This might not cover all use cases though.
However, we are considering it as low priority, and possibly will not implement it now unless the feedback is provided. 

Thank you

**Comment by javiercn** [comment]
This is not important for ASP.NET Core scenarios.

We handle things differently, our certificate is installed in the certificate store and its populated as part of the first run experience. I can't speak for other scenarios.

**Comment by YuliiaKovalova** [comment]
Close with Low Priority
