### ISSUE TITLE
"dotnet new -i" downloads internet

### ISSUE THREAD

**Issue by MiloszKrajewski** [dotnet/templating#772]
Hi,

First of all I need to say that I really like .NET templating. I really love the "running-template" approach. I have a question though. Should "dotnet new -i" download whole internet every time?

1. Steps

```dotnet new -i "dotnet-new-nspec::*"```

...and a lot of assemblies are being downloaded. Do it again:

```dotnet new -i "dotnet-new-nspec::*"```

and same assemblies are downloaded again.

2. Expected results

Assemblies are downloaded/installed once.

3. Actual result

They are installed every time.

Am I missing something?

**Comment by sayedihashimi** [comment]
This is already fixed in our dev branch and should be in the next release. In the next release install should be significantly faster than it was in the past. I'm going to close this issue because I think it's resolved. If I missed anything please reopen with details.
