### ISSUE TITLE
Add $schema to all template files

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/templating#778]

**Comment by dansiegel** [comment]
should the schema be added to otherwise empty host specs? [Sample](https://github.com/dotnet/templating/blob/rel/vs2017/3-Preview2/template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Nuget/.template.config/dotnetcli.host.json)

**Comment by mlorbetske** [comment]
I think that'd be good, but I'm not sure if we have host-specific schemas yet

**Comment by dansiegel** [comment]
Yes there is a schema for dotnetcli.host and vs-2017.3.host

**Comment by mlorbetske** [comment]
Fixed in #780
