### ISSUE TITLE
dotnet new --install no longer works after update to VS15.2

### ISSUE THREAD

**Issue by grokys** [dotnet/templating#779]
I recently installed the VS15.2 update which I assume also updated my version of `dotnet`. Now when I try to install templates using `dotnet new --install [path]` nothing seems to happen. Have things changed?

**Comment by sayedihashimi** [comment]
Hmm that should work. We had a bug before where the if the path ended in a trailing slash the call wouldn't work. I think that was fixed though.
Let's see if @mlorbetske or @seancpeters have any ideas.

**Comment by grokys** [comment]
Just to clarify, when I run the command it produces its usual output but doesn't seem to install my templates. The templates I'm trying to install are these: https://github.com/AvaloniaUI/avalonia-dotnet-templates

**Comment by sayedihashimi** [comment]
Did you pass a relative path or full path? I just tried on Mac with `dotnet new -i .\` and that didn't work but when I passed `dotnet new -i /Users/sayedhashimi/mycode/avalonia-dotnet-templates` the new templates showed up.

**Comment by grokys** [comment]
Ah the problem was indeed the trailing slash! I'm sure it used to work with a trailing slash before? Anyway, working now so closing - thanks.
