### ISSUE TITLE
Add descriptions to all elements in the schema

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/templating#782]
We have the following json schema files:

 - https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/template.json
 - https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/dotnetcli.host.json
 - https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/vs-2017.3.host.json

We should add descriptions to all fields.

**Comment by mlorbetske** [comment]
Fixed with https://github.com/SchemaStore/schemastore/pull/493
