### ISSUE TITLE
Template files getting renamed

### ISSUE THREAD

**Issue by dansiegel** [dotnet/templating#783]
One of my templates has several image assets named `Icon@1x.png`, `Icon@2x.png`, etc. I'm not sure when/where this bug came from but the actual assets are being renamed in a url safe name `Icon%401x.png`, `Icon%402x.png`, etc.

None of the files in that directory should be getting renamed at all. This is using dotnet cli v 2.0.0-preview2-006062 with just `dotnet new`

**Comment by mlorbetske** [comment]
If you look in the nupkg, do the files have the encoded names?

**Comment by dansiegel** [comment]
@mlorbetske the names of the files in the nupkg don't appear to be encoded

**Comment by mlorbetske** [comment]
It looks like `ZipArchiveEntry` is returning the encoded names, working on a fix
