### ISSUE TITLE
[docs]: Populate Available Parameter Generators

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/templating#785]
I've created a new wiki page for the [Available Parameter Generators](https://github.com/dotnet/templating/wiki/Available-Parameter-Generators). We should document the current generators there. The list of generators is at https://github.com/dotnet/templating/tree/rel/vs2017/3-Preview2/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/Macros/Config

**Comment by sayedihashimi** [comment]
I've added a bunch of content to https://github.com/dotnet/templating/wiki/Available-Parameter-Generators. I think we are good for the time being. Closing for now. If any community members would like to improve that is welcome.

**Comment by CumpsD** [comment]
Any chance there is some documentation on creating your own parameter generators?
