### ISSUE TITLE
a call to help prevent regressions

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/templating#791]
Would anyone be interested in adding their templates to our creation test battery?

As part of the local and CI build processes, we run a bunch of tests to ensure that content is being generated properly. Essentially, we have a Theory type test that maps command lines for instantiation of templates to JSON files that lists the expectations on what gets created on disk. It's a relatively primitive framework but it can check for the presence/absence of certain files or strings in the contents of those files. These tests are [here](https://github.com/dotnet/templating/tree/rel/vs2017/3-Preview2/test/Microsoft.TemplateEngine.Cli.UnitTests).

For anyone who's interested, please send a PR to add your templates, but be sure to add contact information to the JSON files - if there is an intentional breaking change, we'll use that information to reach out.

**Comment by mlorbetske** [comment]
The basic infrastructure for this is out for PR as https://github.com/dotnet/templating/pull/838. Feel free to comment on what capabilities should be added.

**Comment by RehanSaeed** [comment]
This sounds interesting.

I've tackled the problem from a different viewpoint in https://github.com/dotnet/templating/issues/367 where I run `dotnet restore`, `dotnet build`, `npm install`, 'gulp build', 'dotnet run' using the ASP.NET Core TestHost API to test that the project is functionally operational, rather than the files being add/removed.

I think both approaches are useful and perhaps they could be combined?

**Comment by mlorbetske** [comment]
@seancpeters let's document how to add this kind of test on the [wiki page about testing](https://github.com/dotnet/templating/wiki/Testing-your-templates).

@RehanSaeed if you'd be interested in adding information on your framework as well, that'd be great

**Comment by RehanSaeed** [comment]
@mlorbetske Will do, when I've finished it.

**Comment by seancpeters** [comment]
@mlorbetske @sayedihashimi - please review my newly created documentation on running these tests: [wiki page about testing](https://github.com/dotnet/templating/wiki/Testing-your-templates).

**Comment by mlorbetske** [comment]
Docs look great, thanks!
