### ISSUE TITLE
--dry-run option: a run through without making any changes [discussion-only]

### ISSUE THREAD

**Issue by peterblazejewicz** [dotnet/templating#794]
I'd like to propose that option to make a command no-op is added to available options/switches. As the list of options grows there is a greater chance to make wrong output. I acknowledge existence of `--force` option and default no-override behavior, but `--dry-run` has usually different behavior.
This option is usually set to `false` by default has various aliases:
`--dry-run`
`-d`
`--dryRun`
Have you folks discussed such option? I know it usually has no real or little value in context of IDEs like VS, but I think it is useful for cli usage.

**Comment by mlorbetske** [comment]
It looks like this would be pretty easy to do, the relevant logic is already [here](https://github.com/dotnet/templating/blob/9703a93a90c6cb91e4d265857c54963102c27ef6/src/Microsoft.TemplateEngine.Edge/Template/TemplateCreator.cs#L74-L75), just a matter of exposing a switch & splitting out the logic (and not only showing "destructive" type changes).

**Comment by sayedihashimi** [comment]
I don't think that we've discussed this but I think it's a great idea. PowerShell has built in support for `--whatif`, and this is very similar to that. It would also be nice to have support for `--install`/`--uninstall` to see what templates will be added/removed.
