### ISSUE TITLE
Consider adding an option to the MVC auth template that only does cookie auth without OIDC

### ISSUE THREAD

**Issue by danroth27** [dotnet/templating#800]
We had some requests to provide an option for only doing cookie auth with the OIDC stuff:

https://github.com/aspnet/Identity/issues/1187#issuecomment-301602256

We should see based on the preview1 feedback how many folks want this and react accordingly.

Daniel Roth

**Comment by Ponant** [comment]
Somewhat related (feedback on preview 1)
https://github.com/aspnet/tooling/issues/1040
https://github.com/aspnet/tooling/issues/1041

**Comment by mlorbetske** [comment]
This issue was moved to aspnet/templating#21
