### ISSUE TITLE
OpenID appears in tfp/IdentityService/Manage/ManageLogins VS 2017 15.3 Preview 1

### ISSUE THREAD

**Issue by danroth27** [dotnet/templating#801]
_From @Ponant on May 14, 2017 21:29_

OpenID appears as button in the ManageLogins for a registered user in ASP.NET Core 2.0 in-app Identity whereas it is not expected, a priori.
Furthermore, clicking on this button leads to the Server Error `The view 'AccessDenied' was not found. `

_Copied from original issue: aspnet/Tooling#1040_

**Comment by mlorbetske** [comment]
This issue was moved to aspnet/templating#22
