### ISSUE TITLE
Microsoft.TemplateEngine.Edge transitively references System.Runtime.Loader/4.3.0 on netstandard2.0

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/templating#8061]
https://github.com/dotnet/templating/blob/949caea9115ac7c72c5b2af2f16903553431d200/src/Microsoft.TemplateEngine.Edge/Microsoft.TemplateEngine.Edge.csproj#L28

This reference is problematic. That API is only availble on .NETCoreApp. The System.Runtime.Loader package hasn't shipped for years and was never intended to be used on .NET Standard (support for it was later removed). See https://github.com/dotnet/runtime/issues/38503 for more details

BTW this is the only remaining dependency that brings 4.x.x / .NET Standard 1.x packages in, in this repository (after my other templating PRs got merged).

cc @ericstj @MichalStrehovsky in case you have opinions on what to do here

**Comment by MichalStrehovsky** [comment]
> cc @ericstj @MichalStrehovsky in case you have opinions on what to do here

Build a time machine and stop people from building this package, along with the NetStandard 2.0 package for System.Reflection.Emit that has the same kind of problems.
