### ISSUE TITLE
Can't get coalesce feature to work.

### ISSUE THREAD

**Issue by dasMulli** [dotnet/templating#809]
Been playing around with this for a few hours but can't get it to work - I tried to make a global.json template that falls back to the host cli version if no override is set. I did this by copying from how the kestrel port generation is implemented, but haven't been able to get it to work (using the "final" 2.0.0 preview1 build):

```son
  "symbols": {
    "SdkVersion": {
      "description": "Overrides the version of the .NET SDK to set in the generated global.json.",
      "type": "parameter",
      "binding": "sdkVersion",
      "dataType": "string"
    },
    "HostSdkVersion": {
      "type": "bind",
      "binding": "dotnet-cli-version",
      "dataType": "string"
    },
    "SdkVersionReplacer": {
      "type": "generated",
      "generator": "coalesce",
      "parameters": {
        "sourceVariableName": "SdkVersion",
        "fallbackVariableName": "HostSdkVersion"
      },
      "replaces": "1.0.0"
    }
```

The `"replaces": "1.0.0"` works great on the other two symbols. Full source here: 
https://github.com/dasMulli/global.json-template/blob/93ed39a8f82bcc932991a9d618f013cd2d1d009c/DasMulli.Templates.GlobalJson/content/GlobalJson/.template.config/template.json

Am I missing something obvious here?

**Comment by mlorbetske** [comment]
This is due to the explicit registration that currently happens in the dotnet CLI of components used by the engine - the registration of the new component that handles this was missed. In 2.0.0 Preview 2, this will be changed to dynamic discovery, so this should be picked up. You can try this out now by building this repo & trying it with `dotnet new3`.

**Comment by mlorbetske** [comment]
The change fixing this has made its way into CLI with https://github.com/dotnet/cli/pull/6629
