### ISSUE TITLE
Add project templates for ASP.NET Core 2.0 apps running on .NET Framework

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/templating#813]

**Comment by mlorbetske** [comment]
The 2.0 templates already support passing full framework TFMs via TargetFrameworkOverride (the same mechanism for 1.x) - this option is currently filtered out in the VS UI. Is there more to do here than just not hide them?

**Comment by DamianEdwards** [comment]
Yes, the templates will require other changes, e.g. the packages referenced.

**Comment by mlorbetske** [comment]
Partially addressed in #825
