### ISSUE TITLE
Drop a gitignore file as part of project/sln templates

### ISSUE THREAD

**Issue by anurse** [dotnet/templating#823]
My workflow for creating a new project with `dotnet new` is generally something like this:

1. `mkdir MyNewProject`
2. `cd MyNewProject`
3. `dotnet new console`
4. `git init`
5. Browse to github.com/github/gitignore
6. Find `VisualStudio.gitignore`
7. Click "Raw"
8. Copy the content
9. Edit a new `.gitignore` file in the repo
10. Paste
11. Save

(I only recently realized that I could use `dotnet new console -n MyNewProject` to collapse steps 1-3)

(And yeah, I could save time with the gitignore stuff, but I am a lazy engineer and want tools to do things for me :))

Whereas, when I play with `rust` and use `cargo`, my workflow is this:

1. `cargo new MyNewProject`

The results are the same, a single project is created in a new directory with a Git repo and an appropriate gitignore file. I think we could simplify the `dotnet new` experience quite a bit.

I like that the `cargo` cli has decided to be Git-by-default. I realize that doesn't work in all environments but I think that the command-line audience very frequently wants a git repository and gitignore file. Cargo also has a `--vcs` option which allows you to choose `git`, `hg`, or `none`, and a config system that allows you to have a user-level default if you aren't using `git`.

This would also have to be conditional on detecting if the newly-expanded template is **already** in a git repo.

**Comment by sayedihashimi** [comment]
It seems for .NET projects that the git repo is at the solution level not the project level. Are you suggesting an optional switch to add git support or suggesting it should be the default? I like the idea of having this behind a command line switch, but I'm not sure if it should be the default.

Alternatively, we can add Item Templates for .gitignore/.gitattributes. We don't have a good experience when there is a lot of templates installed, so I'm holding off on adding a bunch of item templates for the time being. We are going to be working on an interactive experience, when we get that I think it will be good to add a bunch of Item Templates.

**Comment by mlorbetske** [comment]
If I'm reading this correctly, the plan is to put this behind the interactive mode work item and create an item template for the `.gitignore` file specifically, right?

**Comment by mlorbetske** [comment]
If this just goes the route of item template, we should add it to #233 and track it there

**Comment by anurse** [comment]
@mlorbetske I hope it won't only be available behind interactive mode. I'd want at least a command line switch (`--git`, etc.) and ideally the ability to configure it to be on by default (and I'd think it should also create the repo if it's not already in a repo).

**Comment by mlorbetske** [comment]
@anurse not that it would only be available through interactive mode, but that after interactive mode is introduced that we'd add the template. The purpose of that ordering is that without interactive mode, the template listing itself gets pretty long & unwieldy - adding interactive mode will at least give us pagination/filtering. You'd still be able to create it without having to use interactive mode though.

**Comment by anurse** [comment]
Cool. My dream behavior for this would be that I can set `dotnet new` up so that on any project or solution template and if the target directory isn't already in a repo it will create a new repo, `.gitattributes` and `.gitignore` files. Has there been any thought of a configuration model for `dotnet new` so that we could provide "default" values for parameters such as possible future `--vcs git` parameter?

**Comment by mlorbetske** [comment]
We've been doing some thinking around customizable preferences (I believe it'd be part of the generalized `dotnet prefs` - or whatever calling it these days) that would do things like let you set the default language & whatnot, but we've not discussed detecting the existence of various VCS artifacts & conditionally creating templates. There are very early talks of "pre-actions" that would run something before creating the template and possibly take some action, but this would require all templates to opt-in to that behavior.

**Comment by sayedihashimi** [comment]
Anybody else looking for the functionality?

**Comment by RehanSaeed** [comment]
`.gitignore` is a solution level artifact, I think there needs to be a general way to handle solution level artifacts that you want to ship along with your project template. A list of files I'd consider adding to my templates include:

- `.editorconfig`
- `.gitignore`, `.gitattributes`
- `build.cake`, `build.ps1`, `build.sh` for Cake build support
- `appveyor.yml`
- `.travis.yml`
- `MyCustomAnalyzerRules.ruleset`
- `README.md`, `CONTRIBUTING.md`

Then I could pass `--EditorConfig --SourceControl Git --Cake --AppVeyor --Travis --ReadMe --Contributing`.

Not sure of the best way. You may well decide that `.gitignore` is a special case and should be baked in as a `--vcs git` command as suggested.

**Comment by maracuja-juice** [comment]
You can add a `.gitignore` to your template and it will be created along with the rest.

**Comment by paule96** [comment]
Hi @anurse,

I have create a template for the .gitignore. I hope it solve your issue. 

You find it [here](https://github.com/paule96/paule96.DotNetTemplate.GitIgnore).

**Comment by donJoseLuis** [comment]
@grinrag , maybe this is something we can do on the short-term?

**Comment by bekir-ozturk** [comment]
Hi @KathleenDollard. Can you check if this should be considered together with the efforts for sln and editorconfig?

**Comment by h3rmanj** [comment]
Would be nice if there was an option to make the template engine initialize a git repo for the user. I know some other templating tools does this, like create-react-app. Would mostly be relevant in the case of solution templates, not when adding projects to solutions though.

**Comment by baronfel** [comment]
I don't think we'd include one automatically - we should lean on the existing `.gitignore` item template, or allow folks to generate their own.

**Comment by vlada-shubina** [comment]
Closing the issue.
To create `gitignore` file, please use `gitignore` template available in .NET SDK.
