### ISSUE TITLE
Can't Install templates in 2.0.0preview1 with dotnet new -i

### ISSUE THREAD

**Issue by livarcocc** [dotnet/templating#824]
_From @JonathanLoscalzo on May 18, 2017 18:3_

## Steps to reproduce

> Install dotnet 2.0.0preview1 on Win10
> Start a GitBash
> Run the following command in Terminal
> dotnet new --install Microsoft.AspNetCore.SpaTemplates::*

### Expected behavior
The CLI downloads the templates, and reports installing them, then lists them in the available templates for "dotnet new"

### Actual behavior
After a time, show list of Templates, but not install any:
$ dotnet new --install Microsoft.AspNetCore.SpaTemplates::*

## Environment data

> .NET Command Line Tools (2.0.0-preview1-005977)
> 
> Product Information:
>  Version:            2.0.0-preview1-005977
>  Commit SHA-1 hash:  414cab8a0b
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.10240
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\

_Copied from original issue: dotnet/cli#6625_

**Comment by sayedihashimi** [comment]
Can you try with quotes:

    dotnet new --install "Microsoft.AspNetCore.SpaTemplates::*"

**Comment by JonathanLoscalzo** [comment]
- With quotes or without, it's the same behavior. 
 - Running the terminal "as Administrator" 
Have "-install" got a Verbosity, -v, or similar option?

**Comment by JonathanLoscalzo** [comment]
#https://github.com/aspnet/JavaScriptServices/issues/948
#https://github.com/aspnet/Announcements/issues/243

Maybe, issue will fix in 2.0.0.preview2?

**Comment by snebjorn** [comment]
I have a similar issue when installing my custom template running the current master and using new3.

## Steps to reproduce

> Install dotnet-dev-win-x64.1.0.4.exe on Win10
> Clone https://github.com/dotnet/templating.git (master branch)
> Start a PowerShell
> Run setup.cmd inside the cloned dir
> Run dotnet new3 --install path/to/mytemplate

### Expected behavior

The CLI reports installing it, then lists it in the available templates for "dotnet new3"

### Actual behavior

Doesn't install my template.
Doesn't show any error message.

## Environment data

> .NET Command Line Tools (1.0.4)
> 
> Product Information:
> Version: current master
> Commit: 5e33a88
> 
> Runtime Environment:
> OS Name: Windows
> OS Version: 10.0.14393
> OS Platform: Windows
> RID: win10-x64
> Base Path: C:\Program Files\dotnet\sdk\1.0.4\

**Comment by JonathanLoscalzo** [comment]
No problem in Ubuntu :+1: 

> .NET Command Line Tools (2.0.0-preview1-005977)
> 
> Product Information:
>  Version:            2.0.0-preview1-005977
>  Commit SHA-1 hash:  414cab8a0b
> 
> Runtime Environment:
>  OS Name:     ubuntu
>  OS Version:  16.04
>  OS Platform: Linux
>  RID:         ubuntu.16.04-x64
>  Base Path:   /usr/share/dotnet/sdk/2.0.0-preview1-005977/
> 
> Microsoft .NET Core Shared Framework Host
> 
>   Version  : 2.0.0-preview1-002111-00
>   Build    : 1ff021936263d492539399688f46fd3827169983

**Comment by mlorbetske** [comment]
In the 2.0.0 preview, the `::*` is no longer required if you want the latest stable version, so `dotnet new --install Microsoft.AspNetCore.SpaTemplates` should work for Git Bash (operating on the assumption that the `*` is causing the problem).

We are looking at expanding the information displayed when templates are discovered as part of install. Ideally, we'll be able to list the templates that were successfully installed as part of the operation & the set of templates that failed to install (and why).

**Comment by jdk339** [comment]
Ran `dotnet new -i Amazon.Lambda.Templates::*` and it kept saying:
> zsh: no matches found: Amazon.Lambda.Templates::*

So I ran `dotnet new -i Amazon.Lambda.Templates` and it finally installed the templates.

`dotnet --info`:

> .NET Command Line Tools (2.1.200)
> 
> Product Information:
>  Version:            2.1.200
>  Commit SHA-1 hash:  2edba8d7f1
> 
> Runtime Environment:
>  OS Name:     Mac OS X
>  OS Version:  10.13
>  OS Platform: Darwin
>  RID:         osx.10.13-x64
>  Base Path:   /usr/local/share/dotnet/sdk/2.1.200/
> 
> Microsoft .NET Core Shared Framework Host
> 
>   Version  : 2.0.7
>   Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11

**Comment by mlorbetske** [comment]
Closing this as either quoting the `{packageName}::*` or not specifying the `::*` part has been confirmed to be working
