### ISSUE TITLE
AddOpenIdConnectAuthentication doesn't work with 2.0.0-preview2-25108

### ISSUE THREAD

**Issue by vRITHNER** [dotnet/templating#837]
Hi,
FYI, any app I try to create with aspnetcore 2.0.0 then upgrade to 2.0.0-preview2-25108
doesn't work anymore with OpenIdConnectOptions
ex: the sample showned at build with IdentityService doesn't run anymore.

> ArgumentException: Options.ClientId must be provided
> Parameter name: ClientId
> Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectOptions.Validate()
> 
> Stack Query Cookies Headers
> ArgumentException: Options.ClientId must be provided
> Parameter name: ClientId

Even If I workaround the template code with :
 

>   public static IServiceCollection AddWebApplicationAuthentication(this IServiceCollection services, IConfiguration configuration)
>     {
>       services.AddAuthentication(sharedOptions =>
>                                  {
>                                    sharedOptions.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
>                                    sharedOptions.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
>                                    sharedOptions.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
>                                  });
> 
>       services.AddOpenIdConnectAuthentication(options =>
>                                               {
>                                                 options.ClientId = configuration["Authentication:IdentityService:ClientId"];
>                                               });
>       services.AddCookieAuthentication();
> 
>       return services;
> 

Result:

> InvalidOperationException: Provide Authority, MetadataAddress, Configuration, or ConfigurationManager to OpenIdConnectOptions

env.  info::

```
.NET Command Line Tools (2.0.0-preview2-006098)

Product Information:
 Version:            2.0.0-preview2-006098
 Commit SHA-1 hash:  8c1dacbe23

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16193
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\vrith\.dotnet\x64\sdk\2.0.0-preview2-006098\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25309-07
  Build    : 41f5fc94eedc889f086800c23f35bf14a8c75a9f
```

Txs

**Comment by mlorbetske** [comment]
@danroth27 thoughts?

**Comment by vRITHNER** [comment]
FYI, I just made a new test with the following steps:
-From VS2017 enterprise preview: `add new web app core 20 identity individual`
-I can see the version today is: "2.0.0-preview2-25149"
-`dotnet restore`
-F5 or `dotnet build -c debug` + `dotnet run -c debug` give the same issue

> An unhandled exception occurred while processing the request.
> 
> ArgumentException: Options.ClientId must be provided
> Parameter name: ClientId
> Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectOptions.Validate()
> 
> Stack Query Cookies Headers
> ArgumentException: Options.ClientId must be provided
>  Parameter name: ClientId
> Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectOptions.Validate()
> Microsoft.AspNetCore.Authentication.AuthenticationHandler+<InitializeAsync>d__42.MoveNext()

**Comment by mlorbetske** [comment]
@javiercn any ideas what the value of clientId should be in the case of the in-app STS?

**Comment by mlorbetske** [comment]
I talked this over with @javiercn offline. He's indicate that this is because a lot of the APIs have changed between preview1 and the build you're using. There's a bunch of changes/simplifications coming that will require changes to the templates.

**Comment by vRITHNER** [comment]
FYI, still not working with latest template used with latest version of VS2017 enterprise Version 15.3.0 Preview 2.0

```
<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0-preview2-25149" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.0-preview2-25149" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.0-preview2-25149" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0-preview2-25149" />
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="2.0.0-preview2-25149" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0-preview2-25149" />
  </ItemGroup>
```

```
Product Information:
 Version:            2.0.0-preview2-006215
 Commit SHA-1 hash:  e67962b0de

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16199
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\vrith\.dotnet\x64\sdk\2.0.0-preview2-006215\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25319-02
  Build    : 7983b575ebcbdc3a825eea4b141ff7fb69d25f9d
```

**Comment by mlorbetske** [comment]
For 2.0, these templates are delivered to VS via the installation of the dotnet CLI. Updating VS on its own won't fix it, you'll need the latest .NET Core 2.0 preview 2 CLI from the release/2.0.0 branch of the CLI repo.

**Comment by vRITHNER** [comment]
Txs for the tip.

I just wonder why the template is so different from previous CLI 2.0 ?

For the auth individual, we used to have the areas sub folder

![image](https://user-images.githubusercontent.com/238842/27020482-17dddea2-4f42-11e7-9b75-6a6485825a21.png)

Now, we are coming back to original v1 template with everything in standard folders ?

![image](https://user-images.githubusercontent.com/238842/27020505-43d12e42-4f42-11e7-94ed-beda8de44a9c.png)

It's quite difficult to follow the patterns
Thanks

**Comment by mlorbetske** [comment]
@danroth27 can you comment on this?
