### ISSUE TITLE
Include missing pages in the wiki TOC

### ISSUE THREAD

**Issue by david-acm** [dotnet/templating#8381]
[[### Is your feature request related to a problem? Please describe.

I found the following doc pages using GH search. Although they contain useful information, they are not included in the home wiki page table of contents:

[docs/Using-Group-Identity.md](https://github.com/dotnet/templating/blob/main/docs/Using-Group-Identity.md)
[docs/template-resolution-for-dotnet-cli.md](https://github.com/dotnet/templating/blob/main/docs/template-resolution-for-dotnet-cli.md)

### Describe the solution you'd like.

Let's include them in the TOC so that they are easy to find

**Comment by baronfel** [comment]
We've actually been meaning to remove/deprecate the wiki as its contents are not easily source-controllable. The docs folder on the repo should be considered the canonical source for documentation.
