### ISSUE TITLE
Bypassing the question: Do you want to run this action [Y(yes)|N(no)]?

### ISSUE THREAD

**Issue by granitbunjaku** [dotnet/templating#8399]
I need to execute a script after a project is created with that template. So, I added that script as postAction and it works fine but I'm facing a problem that when I create the project using **dotnet new** it asks me for confirmation if I want to run the action:

![photo](https://github.com/user-attachments/assets/55cce553-69fc-40d9-8d14-ba69ffca7d59)

Can I somehow bypass this and always run the actions? cause when I create the project using rider or vs, I can't specify this answer (yes or no) as this happens during the creation.

**Comment by granitbunjaku** [comment]
> FYI custom postActions don’t run in Visual Studio, that is by design for the time being.

So, there is no way to execute postActions when creating project with my custom template using Visual Studio?

**Comment by sayedihashimi** [comment]
No, what are you trying to accomplish with the postAction? Maybe there is an alternative.

**Comment by granitbunjaku** [comment]
> No, what are you trying to accomplish with the postAction? Maybe there is an alternative.

I have these json files on my template project. The json files contain sourceName that gets replaced after creating the project, after creation I need these files to be moved somewhere else, I was doing this via postAction shell script

**Comment by sayedihashimi** [comment]
You can probably do that by modifying some content in `template.json`. @baronfel do we have any docs on how to modify the folder where certain files will be generated?

**Comment by granitbunjaku** [comment]
> You can probably do that by modifying some content in `template.json`. @baronfel do we have any docs on how to modify the folder where certain files will be generated?

Thank you for the idea. I achieved this by adding on template.json the following (needed to do the exclude thing to exclude the folder when project is created):

"sources": [
    {
      "source": "./TheDirectoryThatContainsJsonFiles",
      "target": "C:\\Users\\GranitBunjaku\\Desktop\\TheDirectoryIWantThemOn"
    },
    {
      "modifiers": [
        {
          "exclude": [ "TheDirectoryThatContainsJsonFiles/*" ]
        }
     }
]

**Comment by sayedihashimi** [comment]
Happy to hear that you got it working. Be careful using full paths though. If you are all set, please close this issue.

**Comment by granitbunjaku** [comment]
> Happy to hear that you got it working. Be careful using full paths though. If you are all set, please close this issue.

Thanks again for your help and for the tip!
