### ISSUE TITLE
Bower package manager migration while in maintenance 

### ISSUE THREAD

**Issue by peterblazejewicz** [dotnet/templating#840]
Hi folks,
Just to let you know, the Bower package manager tool has been put into maintenance mode officially:
https://github.com/bower/bower/commit/0bd318de53daf9dc3b52bfd7bc753d4d2c2c9948
The related issues was closed on the Bower project discussion list:
https://github.com/bower/bower/issues/2298
The templates ships with Bower configuration and implicit dependency (as precaution the dependencies are bundled with template)
If you start some serious discussion on how to migrate templates to not use Bower and move to NPM/Yarn/Webpack, I'd gladly help.

**Comment by mlorbetske** [comment]
I mentioned this to @madskristensen yesterday as well. This seems like as good a place as any to start the discussion on what the plan for client side package management should be going forward.

**Comment by rogersachan** [comment]
Any update on this?

**Comment by mlorbetske** [comment]
When I talked with @madskristensen about this, the thinking was to use LibraryInstaller. Similar to his PackMan project, it's a lightweight way to install and manage client side content files and is backed by CDNJS by default. It can be configured to point to other sources as well in case there's a restriction on or recommendation for the packages allowed for a particular project.

That being said, tooling for it has not yet reached a 1.0 state to my knowledge and the support policy hasn't yet been made clear.

What would folks think of this approach assuming things get finished up and there's a known support policy?

**Comment by mlorbetske** [comment]
This issue was moved to aspnet/templating#23
