### ISSUE TITLE
Can't use 'script' post action to run 'npm install'

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/templating#849]
Glad to see the improved postActions support!

I've tried to add this to the ASP.NET Core SPA templates. The postAction for `dotnet restore` works well, but I've not succeeded in configuring a `postAction` to run `npm install`.

With this config:

```
{
    "description": "Restores NPM packages required by this project.",
    "manualInstructions": [{ "text": "Run 'npm install'" }],
    "actionId": "3A7C4B45-1F5D-4A30-959A-51B88E82B5D2",
    "args": { "executable": "npm", "args": "install" },
    "continueOnError": false
}
```

... it instantly fails with this error:

```
Processing post-creation actions...
Template is configured to run the following action:
Description: Restores NPM packages required by this project.
Manual instructions: Run 'npm install'
Actual command: npm install
Do you want to run this action (Y|N)?
y
Running command 'npm install'...
The system cannot find the file specified
```

... even though running `npm install` manually in the same command line works fine.

I think this is because, on Windows, `npm` is installed as a batch file called `npm.cmd` (*not* `npm.exe`).

If I change the config to `"args": { "executable": "npm.cmd", args: "install" }` (which is obviously not a cross-platform solution), then it gets a little further, but then fails with:

```
Processing post-creation actions...
Template is configured to run the following action:
Description: Restores NPM packages required by this project.
Manual instructions: Run 'npm install'
Actual command: npm.cmd install
Do you want to run this action (Y|N)?
y
Running command 'npm.cmd install'...
Command failed.
Output from command:
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\path\to\yourproject\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
module.js:471
    throw err;
```

Again, this doesn't occur when running `npm.cmd install` manually, so this is a problem to do with how the process is being launched.

As a further test, I tried changing the config to `"args": { "executable": "cmd", args: "/c \"npm install\"" }` (which again is obviously not a cross-platform solution, but this is just for debugging). In this case it does succeed with running `npm install`, but it's not practical as a solution because:

* It's not cross-platform
* It completely hides `npm`'s console output, so there's no progress indication. Since `npm install` can take minutes to complete, seeing the progress output is essential.

## Possible solutions

1. Maybe you could fix this by changing [this line](https://github.com/dotnet/templating/blob/9703a93a90c6cb91e4d265857c54963102c27ef6/src/Microsoft.TemplateEngine.Cli/PostActionProcessors/ProcessStartPostActionProcessor.cs#L23) to set `UseShellExecute` to `true` - not sure. If you do this, please make sure the command's console output is passed through and visible to the user.
2. **Better solution** Have an explicit built-in post action for `npm install`, considering what a mainstream use case this is. This is better, because then you wouldn't have to throw up the scary permissions prompt. It would feel a lot more streamlined.

Do you think it will be possible to resolve this before preview2 ships? We're planning to have SPA templates in the box in preview 2.

**Comment by mlorbetske** [comment]
@SteveSandersonMS let's chat about this as soon as possible. For VS, our ability to easily make changes for preview 2 ends tomorrow at 6 pm, for CLI it's on Friday I believe. Is the intention to ship the spa templates with VS or CLI or both?

@phenning @seancpeters

**Comment by SteveSandersonMS** [comment]
> Is the intention to ship the spa templates with VS or CLI or both?

Both, but it's less important to have the `npm install` postAction in the VS host, because VS natively restores NPM packages anyway. It matters more with the CLI, where NPM packages aren't automatically restored.

> let's chat about this as soon as possible.

I'm available via email or Skype.

**Comment by mlorbetske** [comment]
Ok, all caught up with context. Since there'll be a 2.0 flavor of these templates (and we only plan to include the 2.0 version), then all we have to do is to set up the insertion into CLI & make sure the VS metadata is set correctly. Please work with @phenning to get the VS metadata in place. Once a new package version for the templates carrying the 2.0 bits & VS artifacts, we'll be able to do that insertion.

For the time being, let's just print a message telling the user to run npm install & we'll investigate how we can make the experience better. @seancpeters please work with @SteveSandersonMS to figure out what the optimal experience is here - having an NPM (or NPM install specific post-action) may be a solution, but it'd need to be done very quickly to hit preview 2.

**Comment by seancpeters** [comment]
@SteveSandersonMS 
Without creating a specific npm install post action, if we could come up with a set of process start post action configurations that each correctly run on some platform(s), and collectively cover all targeted platforms, then we could set them up with platform-based conditions on the post actions so that only the appropriate one runs on each platform.

Something like:
```
"postActions": [
  {
    "condition": "(IsWindows)",
    <windows-specific config here>
  },
  {
    "condition": "(IsMac)",
    <mac specific config here>
  },
  {
    "condition": (!IsWindows && !IsMac)",
    <other config here>
  }
]```

...or however many are needed. 

But if it's deemed best to have an npm install post-action, I can spend some time on it today & tomorrow.

**Comment by SteveSandersonMS** [comment]
@seancpeters Thanks for looking into it!

Having a set of platform-specific configs would be an OK stopgap measure. I know time is very tight. But is there a reasonable way to do it on Windows at all? The closest I got was the `cmd /c "npm install"` approach, which is not really viable since it provides no progress feedback on a process that can take minutes. I think it would be better to go back to showing manual instructions only rather than having `dotnet new` appear to hang. Or is there another way?

If you think you could do an `npm install`-specific postAction without it being an insane scramble, that would certainly be cleanest, but I'll leave that with you and @mlorbetske to determine how feasible it is.

Finally, if we end up just having to show manual instructions instead of invoking `npm install` automatically, it's not so bad. People have successfully done that with the existing SPA templates for months now.

**Comment by seancpeters** [comment]
Regarding the problem of the output not being displayed until the end, I'm currently writing up a change to the script handler post action that reads the command stdout & stderr async, and reports it to the console. If I can get that working, we may be in business.

**Comment by SteveSandersonMS** [comment]
@seancpeters Does that approach look like it's going to work out?

Also, do you know whether the VS host will honour and execute the script postActions, or is that only a CLI concept?

**Comment by seancpeters** [comment]
@SteveSandersonMS - I've got it basically working so the script running console output is reported to the console in real-time. But I haven't been able to capture output if the post action runs `cmd <whatever>`

**Comment by seancpeters** [comment]
VS can run post actions, but the implementation is host-specific. So there can be cases where the CLI implements certain post actions, and but VS does not, or vice-versa.

**Comment by SteveSandersonMS** [comment]
Great, thanks for the update.

> But I haven't been able to capture output if the post action runs cmd <whatever>

Is there a plan then for how a postAction could be usable to invoke `npm install`, or preferably also other `npm` commands like `npm run {task}`? @mlorbetske

> VS can run post actions, but the implementation is host-specific. So there can be cases where the CLI implements certain post actions, and but VS does not, or vice-versa.

OK. I know it might not be your area of work, but do you happen to know if VS does implement the "script" postAction in particular?

**Comment by seancpeters** [comment]
No, VS doesn't currently implement the script running post action.

**Comment by mlorbetske** [comment]
The current plan is this (barring major objections):
- For now, we'll just message that `npm install` needs to happen (turning off the messaging for VS which will do the restore automatically) - VS2017.3 Preview 2
- We'll fix up the execute script post-action to be able to handle batch files appropriately on Windows (we've got some ideas on how to do this & there's prior art) - VS2017.3 Preview 3/RTW
- We'll evaluate adding an `npm` (or `npm install`) post-action - Post-VS2017.3 RTW
  - we'll have to make sure this degrades nicely & doesn't appear that the dotnet CLI doesn't depend on npm /cc @sayedihashimi

**Comment by Grovespaz** [comment]
This issue has lulled a while, but I'm still looking for a reliable way to run npm install as a post action.
What is currently the best way to do an npm install, is it still ```cmd /c npm install```?

Is there anything the community can do to support this issue (npm install post action or something more generic) being implemented?

**Comment by donJoseLuis** [comment]
This issue was last touched some years ago.  We are working on a new delivery road map.  Please reopen if this is something we want & we'll properly assess its' priority compared to other work aimed at improving the overall templating UX.
