### ISSUE TITLE
Suppress creation of Class1.cs file when running dotnet new <type> --force

### ISSUE THREAD

**Issue by livarcocc** [dotnet/templating#853]
_From @brunzefb on May 24, 2017 3:2_

When converting an old-style .csproj to dotnet core/standard, I typically run 'dotnet new classlib --force' from cmd line to re-create the .csproj file.  If other .cs files are detected in the folder or subfolders, the creation of the Class1.cs file should be suppressed, as it useless.  For a new project, it is useful to have, but not when using --force.

## Steps to reproduce
1. Change directory to an existing project containing .csproj and .cs in folder or subfolders
2. run dotnet new classlib --force

## Expected  behavior
1. The .csproj file is overwritten with a template .net core one  

## Actual behavior
1. the .csproj file is correctly overwritten
2. a Class1.cs template file is produced, but should not be when using --force.

## Environment data
`dotnet --info` output:

_Copied from original issue: dotnet/cli#6675_

**Comment by mlorbetske** [comment]
I don't think that conditionally emitting a part of the template based on what is or is not on disk in the target location is the right move - as the template is intended to be a coherent set of content to be used as a starting point. In non-trivial cases where it's just class library or console app where it's one code file plus the project file, there can be worse side effects (overwriting customized scripts with the original names, downgrading client side libraries that have been updated, etc).

Perhaps we'd want more or less an "empty project" template that one could use for these purposes, but we'd have to figure out what the right content for the project file would be.

@sayedihashimi

**Comment by sayedihashimi** [comment]
I think what you're really looking for is a command line utility to migrate from .xproj/project.json to .csproj. I'm not sure if that's being planned or not but the correct place for discussing that I believe would be https://github.com/dotnet/cli/issues.

Back to this issue, we could consider adding a parameter `--noClassFile` so that we create the template without the `Class1.cs` file. Would that work in your case?

**Comment by brunzefb** [comment]
--noClassFile would be great. While we are at this, it might also be very nice to have an option to generate a .csproj file that is not so bare bones, but has some commented out examples that one may want to use.  And now you're getting this request after all the work that went into make things so simple and terse...

**Comment by donJoseLuis** [comment]
This issue was last touched some years ago.  We are working on a new delivery road map.  Please reopen if this is something we want & we'll properly assess its' priority compared to other work aimed at improving the overall templating UX.
