### ISSUE TITLE
Installing template from Nuget throws error

### ISSUE THREAD

**Issue by neman** [dotnet/templating#855]
When I try to install any template from nuget.org, I got the following error:
```
C:\> dotnet new --install "NetEscapades.Templates::*"
  Restoring packages for C:\Users\nemke\.templateengine\dotnetcli\v1.0.4\scratch\restore.csproj...
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): **error : Failed to retrieve information about 'Microsoft.NETCore.App' from remote source** 'C:\Users\nemke\.dotnet\NuGetFallbackFolder'. [C:\Users\nemke\.templateengine\dotnetcli\v1.0.4\scratch\restore.csproj]
```

![image](https://cloud.githubusercontent.com/assets/350314/26392366/a5d6c132-4066-11e7-9d71-c573587ec9ca.png)

C:\> dotnet --info
```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4
```

**Comment by mlorbetske** [comment]
Please check to see whether `%userprofile%\.dotnet\NuGetFallbackFolder` exists. If it does not, there are two options - either create the folder (it's fine if it's empty) or update `%appdata%\NuGet\NuGet.config` to not reference that folder.

**Comment by neman** [comment]
Great! For some reason, there was no .dotnet folder at all. I know I had it, but somehow I probably manage to delete it.
When I created `%userprofile%\.dotnet\NuGetFallbackFolder` everything went fine.
