### ISSUE TITLE
.Net Core class library template actually creates .Net Standard class library

### ISSUE THREAD

**Issue by srivatsn** [dotnet/templating#856]
_From @richaverma1 on May 19, 2017 22:34_

The template for .Net Core class library incorrectly creates a .Net Standard class library. This is on 15.3 internal preview

_Copied from original issue: dotnet/project-system#2247_

**Comment by srivatsn** [comment]
_From @jmarolf on May 19, 2017 22:42_

@richaverma1 what version of the SDK do you have installed?

**Comment by srivatsn** [comment]
This turned out to be an issue in the templating engine and fix is being prepared. Moving to the dotnet\templating repo

**Comment by dmitry-pavlov** [comment]
Vote++. I am experiencing this this issue too.

**Comment by mlorbetske** [comment]
The PR to get the fix in to VS has been submitted & should make it in to tonight's build
