### ISSUE TITLE
Naming of unit test project templates

### ISSUE THREAD

**Issue by dasMulli** [dotnet/templating#858]
The MSTest and xUnit templates are currently named:

* Unit Test Project (.NET Core)
* xUnit Test Project (.NET Core)

This is confusing since you don't see the difference between these two (e.g. [SO Question](https://stackoverflow.com/questions/44165832/visual-studio-2017-unit-test-project-vs-xunit-test-project)).

They should be renamed to clearly indicate that one uses MSTest. For example:

* Unit Test Project - MSTest (.NET Core)
* Unit Test Project - xUnit (.NET Core)

**Comment by mlorbetske** [comment]
@srivsatn @singhsarab would you be OK with this name change?

**Comment by dasMulli** [comment]
Seems related to https://github.com/dotnet/project-system/issues/2183
Not sure which in which repo this belongs..

**Comment by singhsarab** [comment]
@codito @sbaid

**Comment by mlorbetske** [comment]
Yep, this change would be addressed in dotnet/project-system#2183, closing this one as the project system repo is the right one for tracking the name change for those templates in VS
