### ISSUE TITLE
Projects created by the templating engine aren't "considered" new projects

### ISSUE THREAD

**Issue by davkean** [dotnet/templating#863]
CPS's ProjectFactory isn't being told that the new project being passed it from the templating engine is a new project. 

This is causing it to skip all the "new project" paths in the factory.

I'm not sure how the templating engine creates us, below is the stack (sorry, not doing native debugging, so native frames are missing), but we're not being passed the __VSCREATEPROJFLAGS.CPF_CLONEFILE flags which is what we use to indicate that's it a new project:

```
>	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectFactory.CreateProject(string fileName, string location, string name, uint flags, ref System.Guid projectIid, out System.IntPtr project, out int canceled) Line 277	C#
 	Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.VisualStudio.Shell.Flavor.FlavoredProjectFactoryBase.Microsoft.VisualStudio.Shell.Interop.IVsProjectFactory.CreateProject(string fileName, string location, string name, uint flags, ref System.Guid projectGuid, out System.IntPtr project, out int canceled)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Microsoft.VisualStudio.TemplateEngine.UI.dll!Microsoft.VisualStudio.TemplateEngine.TemplateCreatorBase.CreateAsync(EnvDTE.Solution solution, Microsoft.VisualStudio.TemplateEngine.Contracts.ITemplateCreationInteractions interactions, System.Collections.Generic.IReadOnlyDictionary<string, string> passthroughParams, string baseline)	Unknown

```

index is down right now, so can't see everything that is broken right now, but none of the new project initializes extension points run, looks like we're trying to retrieve the solution configuration, and we're trying to find the guid of the project from the solution.

**Comment by davkean** [comment]
tag @lifengl @mlorbetske 

Lifeng, can you expand on what else will be broken because of this?

**Comment by mlorbetske** [comment]
Cc @phenning

**Comment by mlorbetske** [comment]
@davkean the VS integration for template engine creates the project on disk and then adds it to the solution (AddFromFile on the solution IIRC). What is the effect of skipping these paths in the project factory? The only ill effect we've noticed are that the overview page doesn't show if there's not an existing solution prior to wizard launch (we're working on that now).

**Comment by mlorbetske** [comment]
Just checked in something that should fix this

**Comment by mlorbetske** [comment]
The fix has been merged into d15prerel

**Comment by lifengl** [comment]
CPS will copy files from the template, if it is not copied to the location.  If the template engine has done that, it will not impact that logic.

For new projects, CPS also call some additional extensions (ProjectInitializers), which will be skipped when the flag is not set.  The flag is also passed to some other extensibility points like project loader vetoers, but I don't aware anyone uses it.

For .Net Core project, those extension points might not be used by anyone yet, so you don't see the impact.
