### ISSUE TITLE
Smarter conditional evaluator

### ISSUE THREAD

**Issue by espenrl** [dotnet/templating#864]
FYI: I'm aware of the similar issue in case #587.

What I really like about this templating system is the fact that I don't need to alter the source code. I just need a template configuration file "template.json".

This code snippet though needs some changing.

```
#if DEBUG
... code
#endif
```

It has to be annotated or else it will simply be removed from the output when using dotnet new.

```
//-:cnd:noEmit
#if DEBUG
... code
#endif
//+:cnd:noEmit
```

Would it be an idea that if the evaluator can not fully evaluate the expression, it would leave the region intact?

In this case it does not understand the symbol DEBUG, it can not resolve the expression and thus it will simply leave it as is. And it would not be required to annotate the code with //-:cnd:noEmit and //+:cnd:noEmit.

**Comment by mlorbetske** [comment]
This is one of the benefits we'll get when #51 is completed (it's used for the MSBuild evaluator that has the behavior you're looking for).

**Comment by mlorbetske** [comment]
#960 should take care of this, I'll add tests that cover this case specifically to be sure

**Comment by geocine** [comment]
Is there an additional step need for this to be enabled?
