### ISSUE TITLE
Update client_info to include policy

### ISSUE THREAD

**Issue by danroth27** [dotnet/templating#874]
_From @danroth27 on May 5, 2017 6:5_

The `client_info` parameter needs to be updated to look like this:

```
"client_info": { "uid": "c765bd67-ca10-4337-ad54-fa82babad87a-<policy>", "utid": "1350dd1f-7f35-43b7-8d0f-bf80031d668a" }
```

Where <policy> = whatever policy as used for authentication. For example,

```
"client_info": { "uid": "c765bd67-ca10-4337-ad54-fa82babad87a-B2C_1_signupsignin", "utid": "1350dd1f-7f35-43b7-8d0f-bf80031d668a" }
```

_Copied from original issue: aspnet/IdentityService#101_

**Comment by danroth27** [comment]
This only impacts the in app individual user accounts template

**Comment by danroth27** [comment]
@javiercn Are you handling this as part of your template updates

**Comment by mlorbetske** [comment]
@danroth27 @javiercn was this done?

**Comment by javiercn** [comment]
@mlorbetske we can revisit this at a later point

**Comment by mlorbetske** [comment]
This issue was moved to aspnet/templating#24
