### ISSUE TITLE
Issue to track uninstall?

### ISSUE THREAD

**Issue by SimonCropp** [dotnet/templating#893]
here it says https://blogs.msdn.microsoft.com/dotnet/2017/04/02/how-to-create-your-own-templates-for-dotnet-new/

> After running install, to reset your templates back to the default list you can run the command dotnet new --debug:reinit. We don’t currently have support for --uninstall, but we are working on that. 

But i cant find any issue that is tracking that change.

**Comment by SimonCropp** [comment]
ping @sayedihashimi

**Comment by SimonCropp** [comment]
also there is no doco for `--debug:reinit` here https://docs.microsoft.com/en-nz/dotnet/core/tools/dotnet-new do u need a different issue for that?

**Comment by mlorbetske** [comment]
None of the --debug:* switches are intended for normal usage (bugs in the bits that ship in the 1.x CLI have necessitated it to be used counter to the intention), so they're not planned to be added to the main documentation. There is an item for scoped switch help #107. We're investigating being able to ship updated set of bits in a 1.x CLI update to eliminate the mainline need for any of the --debug:* switches.

Uninstall has been implemented, documented in the in-app help and ships with the 2.0.0-preview* dotnet CLI.

**Comment by sayedihashimi** [comment]
As @mlorbetske mentioned `--uninstall` has been implemented and in the help output. We also have https://github.com/dotnet/docs/issues/2315 to track getting it added to https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new. We are not planning to document the `--debug` actions.
