### ISSUE TITLE
Wrong CLI command for template installation at nuget.org

### ISSUE THREAD

**Issue by neman** [dotnet/templating#895]
When I go tu nuget.org to search for some template I got the following page for link https://www.nuget.org/packages/NetEscapades.Templates/

![image](https://cloud.githubusercontent.com/assets/350314/26781234/bf4cc98c-49ed-11e7-9e4a-08bb168b6c62.png)

The command instruct to use `Install-Package NetEscapades.Templates` which does not work. 

```
Install-Package NetEscapades.Templates
Install-Package : No match was found for the specified search criteria and package name 'NetEscapades.Templates'. Try Get-PackageSource to see all available registered p ackage sources.
At line:1 char:1
+ Install-Package NetEscapades.Templates
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```
The correct command is `dotnet new --install "NetEscapades.Templates::*"`

Will this be fixed in future release?  Which will be the correct CLI command?

**Comment by sayedihashimi** [comment]
Thanks for filing the issue. The primary use case for nuget packages is to install them into a project. The "install-package" command is listed for that use case. We are working with the nuget team to introduce the concept of "PackageType". Once the integration is complete I think we will have a better default experience in nuget.org. For the short term this will stay the same but in the long term we should have an improved experience.
