### ISSUE TITLE
Unable to install nuget template

### ISSUE THREAD

**Issue by neman** [dotnet/templating#896]
I created nuget for template with nuget pack command. 
When I try to install it, using CLI command ` dotnet new --install "BIB.Templates::*"` 

I got the following error at the end of installation

```
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): error : Unable to resolve 'BIB.Templates' for '.NETCoreApp,Version=v1.0'. [C:\Users\nemke\.templateengine\dotnetcli\v1.0.4\scratch\restore.csproj]

Generating MSBuild file C:\Users\nemke\.templateengine\dotnetcli\v1.0.4\scratch\obj\restore.csproj.nuget.g.props.
  Generating MSBuild file C:\Users\nemke\.templateengine\dotnetcli\v1.0.4\scratch\obj\restore.csproj.nuget.g.targets.
  Writing lock file to disk. Path: C:\Users\nemke\.templateengine\dotnetcli\v1.0.4\scratch\obj\project.assets.json
  Restore failed in 13,16 sec for C:\Users\nemke\.templateengine\dotnetcli\v1.0.4\scratch\restore.csproj.

  Errors in C:\Users\nemke\.templateengine\dotnetcli\v1.0.4\scratch\restore.csproj
      Unable to resolve 'BIB.Templates' for '.NETCoreApp,Version=v1.0'.

  NuGet Config files used:
      C:\Users\nemke\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

  Feeds used:
      https://api.nuget.org/v3/index.json
      C:\local-nuget
      C:\Users\nemke\.dotnet\NuGetFallbackFolder
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
```

![image](https://cloud.githubusercontent.com/assets/350314/26783654/98fa8ff6-49f9-11e7-9839-6ac15ea82072.png)

When I use the CLI command ` dotnet new --install .` to install from folder, it works.

When I try to install without a star, e.g. `dotnet new --install "BIB.Templates::1.0.0-dev-00002"` it also works. Seems like multiple nuget templates are causing this issue.

### dotnet --info

```
C:\Temp> dotnet --info
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```

**Comment by neman** [comment]
I tried with nuget packages names like

BIB.Templates.1.0.1.nupkg
BIB.Templates.1.0.2.nupkg

BIB.Templates.1.0.1-dev-00001.nupkg
BIB.Templates.1.0.2-dev-00002.nupkg

First works with star, second does not work with star.

**Comment by neman** [comment]
@sayedihashimi  Ok, I'll update my question as soon as possible.

**Comment by mlorbetske** [comment]
This is a NuGet behavior, prerelease packages aren't resolved by star only versions, `BIB.Templates::1.0.0-*` should work for pulling prereleases

**Comment by neman** [comment]
That's it. Know it works. Thanks @mlorbetske 
How can I determine which version of template is installed, but not looking into .templateenginefolder?
Will there be some intuitive way, like column next to dotnet new, or some other command?

**Comment by mlorbetske** [comment]
There's not a really nice way of doing this right now, but `dotnet new --debug:showconfig` will print out the set of things currently in its configuration, including the locations of all the template packages it has installed.

**Comment by neman** [comment]
Template installation is again showing some gremlin errors.
Now I have this, after install command
```
The directory is not empty
   at System.IO.Win32FileSystem.RemoveDirectoryHelper(String fullPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Win32FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Microsoft.TemplateEngine.Utils.PhysicalFileSystem.DirectoryDelete(String path, Boolean recursive)
   at Microsoft.TemplateEngine.Edge.Paths.DeleteDirectory(String path)
   at Microsoft.TemplateEngine.Cli.Installer.InstallRemotePackages(List`1 packages)
   at Microsoft.TemplateEngine.Cli.Installer.InstallPackages(IEnumerable`1 installationRequests)
   at Microsoft.TemplateEngine.Cli.New3Command.EnterInstallFlowAsync()
   at Microsoft.TemplateEngine.Cli.New3Command.<EnterMaintenanceFlowAsync>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.TemplateEngine.Cli.New3Command.<ExecuteAsync>d__66.MoveNext()
```

![image](https://cloud.githubusercontent.com/assets/350314/26819724/6fb668f2-4aa0-11e7-9945-4c55f8c78f5f.png)

**Comment by mlorbetske** [comment]
It looks like something has either leaked a file handle or is holding that directory (`%userprofile%\.templateengine\dotnetcli\1.0.4\scratch`) open. Could you try deleting it and re-running the install?

**Comment by neman** [comment]
Ok, I found the issue. I previously installed the template with the same version. But then I used `dotnet new --debug:reinit`  to ininstall it. After that I tried to install template with the same version.

The error gone when I explicitly deleted package `bib.templates.1.0.0.nupkg` from C:\Users\nemke\.templateengine\dotnetcli\v1.0.4\packages folder

**Comment by neman** [comment]
Looks like ConEmu is holding that directory, after template installation.
