### ISSUE TITLE
RequiresHttps no worky

### ISSUE THREAD

**Issue by HaoK** [dotnet/templating#909]
When we generate b2c/organization auth templates, we do not get any ssl ports generated in launchSettings.json

**Comment by mlorbetske** [comment]
A few questions:
- When generating through the CLI or VS?
- Does the launch settings file get generated at all?
- Is this with new (if so, which CLI version) or new3?

**Comment by HaoK** [comment]
Generated via: `dotnet new` pointing against my branch of the preview2 template feed.
launch settings get generated just with a 0 ssl port.

Not sure if this is new or not, cc @danroth27

**Comment by mlorbetske** [comment]
Talked this over with Dan and Phil, we're able to repro in cases where HTTPS ports aren't required (the only way 0 can be generated). Auth configurations (in app STS until recently, org auth) that require HTTPS end up setting the flag that causes the generation and replacement to happen. Please reopen if we missed a case that leaves it at zero in a case where it's required.
