### ISSUE TITLE
Asp.NET mvc auth individual doesn't compile with latest cli

### ISSUE THREAD

**Issue by vRITHNER** [dotnet/templating#945]
Steps:
Downloaded latest cli :  

> Version:            2.1.0-preview1-006329

`dotnet new mvc --auth Individual -uld`

First, I'm surprised bye the fact the Areas\Identity came back in the template 
ref: [https://github.com/dotnet/templating/issues/936](https://github.com/dotnet/templating/issues/936)

`dotnet build -c debug`

> Areas\IdentityService\Models\ApplicationUser.cs(10,36): error CS0246: The type or namespace name 'IdentityUser' could not be found (are you missing a using directive or an assembly reference?) [D:\Temp\testnewdotnet\testnewdotnet.csproj]
> Areas\IdentityService\Data\IdentityServiceDbContext.cs(13,18): error CS0311: The type 'testnewdotnet.Identity.Models.ApplicationUser' cannot be used as type parameter 'TUser' in the generic type or method 'IdentityServiceDbContext<TUser, TApplication>'. There is no implicit reference conversion from 'testnewdotnet.Identity.Models.ApplicationUser' to 'Microsoft.AspNetCore.Identity.IdentityUser'. [D:\Temp\testnewdotnet\testnewdotnet.csproj]

```
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0-preview2-25332" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.0-preview2-25332" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.0-preview2-25332" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0-preview2-25332" />
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="2.0.0-preview2-25332" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0-preview2-25332" />
  </ItemGroup>

```

![2017-06-14 1](https://user-images.githubusercontent.com/238842/27118534-fc9349e8-50db-11e7-8c77-cbf7b4c5a4d5.png)
![2017-06-14 2](https://user-images.githubusercontent.com/238842/27118537-004137e4-50dc-11e7-9449-0b815e93a6e4.png)
![2017-06-14 3](https://user-images.githubusercontent.com/238842/27118551-09c0baec-50dc-11e7-9e21-3399da284150.png)

txs

**Comment by mlorbetske** [comment]
The CLI that you've got installed (from dotnet --info) is a 2.1 build from the master branch of the CLI repo. For 2.0 templates, the CLI should be coming from the release/2.0.0 branch. The logic in VS for picking the templates up from CLI installs the ones carried from the maximum version installed for each major/minor version pair (the highest from 2.0*, the greatest from 2.1*, etc.) in ascending version order I believe. This would have put the templates back to an older version of the content (as master isn't caught up to the 2.0.0-preview2 content yet). Please uninstall the 2.1 CLI build and install the latest 2.0 CLI from the release/2.0.0 branch & let us know how it goes.

**Comment by vRITHNER** [comment]
Indeed, I just tried with CLI 2.0.0-preview2-006470 and it works.
The template is the one without "areas"
Does it mean the 2.1 will get this new "areas"  for identity stuff ?
txs

**Comment by mlorbetske** [comment]
I believe that's the case, but @danroth27 would be the one to know for sure. Closing this, since the issue you were running in to is resolved.

**Comment by danroth27** [comment]
@vRITHNER The identity as a service work (the stuff in the area) was [pushed out of 2.0](https://github.com/aspnet/Announcements/issues/243) because it needed some more bake time. We are working on getting it done for [2.1](https://github.com/aspnet/Home/wiki/Roadmap).
