### ISSUE TITLE
Update templates to not use PackageTargetFallback

### ISSUE THREAD

**Issue by livarcocc** [dotnet/templating#946]
Now that the SDK has moved to use AssetTargetFallback implicitly, we need to update the templates to do that as well, otherwise restore will fail. I am passing a property to disable implicit asset fallback in the CLI right now to get tests to pass.

Once we update the templates, we should remove that from the tests. Please note, that this also includes the SPA templates.

@mlorbetske @balachir

**Comment by mlorbetske** [comment]
Do we know what needs to be updated in the templates for that? Any pointers to docs/examples would be appreciated
