### ISSUE TITLE
Add developer exception page middleware to the web api templates

### ISSUE THREAD

**Issue by danroth27** [dotnet/templating#949]
We should add developer exception page middleware to the web API templates so that you get some diagnostic error information in the response when there is a 500 in development.

**Comment by mlorbetske** [comment]
Is this just adding 

```
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
```

to the WebAPI templates?

**Comment by danroth27** [comment]
Yes, and the necessary nuget package when running on the .NET Framework.

**Comment by mlorbetske** [comment]
Do you know offhand which package that is? Things seem to be working without updating the packages

**Comment by danroth27** [comment]
Microsoft.AspNetCore.Diagnostics

**Comment by mlorbetske** [comment]
Sweet, this seems to be getting pulled in via the Microsoft.AspNetCore package, so I think we're good
