### ISSUE TITLE
Link to dotnet-template-samples from README

### ISSUE THREAD

**Issue by pierceboggan** [dotnet/templating#951]
This evening, I was looking for some amazing [dotnet/templating samples](https://github.com/dotnet/dotnet-template-samples) and couldn't find any references to a samples repo in the README. It would be awesome if we could link to this in the README!

**Comment by mlorbetske** [comment]
Just added via https://github.com/dotnet/templating/commit/6bddffd8d41a0284ba9d549b18b12946cb0d3eca - not sure if it calls enough attention to it though, what do you think?

@sayedihashimi

**Comment by pierceboggan** [comment]
@mlorbetske I think it probably demands its own section. Often, I've found people don't read the actual text in a README, but just browse the subheadings (just like blog posts 😝).

**Comment by sayedihashimi** [comment]
PR created at https://github.com/dotnet/templating/pull/967. Thoughts on that?
