### ISSUE TITLE
csproj import condition not replaced.

### ISSUE THREAD

**Issue by pierceboggan** [dotnet/templating#952]
When using .NET templating with a solution containing a shared project, all references to the template app are scrubbed on a `dotnet new`, except for conditional imports in csproj files.

## Reproduction Steps

1. Create a new console app project.
2. Add a shared project to the solution.
3. Reference the shared project from the console app.
4. Add generic `.template.config` to replace namespaces and such.
5. Install template.
6. `dotnet new template-name`.
7. The reference in the console app's csproj is updated to import the correct project, but the [`Condition`](https://msdn.microsoft.com/en-us/library/92x05xfs.aspx) attribute is not.

Example, where BlankApp is the template app, and HeyThere is the app created via `dotnet new`:

```
 <Import Project="..\HeyThere\HeyThere.projitems" Label="Shared" Condition="Exists('..\BlankApp\BlankApp.projitems')" />
```

This causes apps not to build, even though a reference is properly there.

**Comment by mlorbetske** [comment]
It looks like the condition evaluator, on determining that that condition wasn't meant for it, just emitted the thing it found but didn't return control to the processor to do replacements until after the block ended.

In the short term, you should be able to work around this by changing

```
 <Import Project="..\BlankApp\BlankApp.projitems" Label="Shared" Condition="Exists('..\BlankApp\BlankApp.projitems')" />
```

to

```
<!--/-:cnd-->
 <Import Project="..\BlankApp\BlankApp.projitems" Label="Shared" Condition="Exists('..\BlankApp\BlankApp.projitems')" />
<!--/+:cnd-->
```

The line before the import will turn off condition processing, so the contents of the condition should be left alone for normal replacements & whatnot. The line after turns it back on.
