### ISSUE TITLE
add a `dotnet new template` for create a new ready to pack template

### ISSUE THREAD

**Issue by enricosada** [dotnet/templating#954]
Add a `dotnet new template`

So is ready to use with just `dotnet restore` and `dotnet pack /p:Version=1.2.3`

More options:

- `dotnet new template --type project` (or `--type item`)
- `dotnet new template --sample option` to add a sample conditional option

Is possibile to create package the template in lot of ways (nuget, nuspec, csproj, prj)

The best one i know atm is doing just with a `.proj` (any extension is ok), like https://github.com/fable-compiler/Fable/blob/master/src/templates/simple/Fable.Template.proj

so like `Fable.Template.proj` (note the `.proj` extension, neutral, not csproj, so doesnt mess with compiler targets)

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>

    <!-- fill some nuget package props (optional) -->
    <Description>Simple Fable App</Description>
    <Authors>Alfonso Garcia-Caro</Authors>
    <!-- fill nuget package version (optional) -->
    <Version>0.2.1</Version>

    <!-- this is a package -->
    <PackageType>Template</PackageType>

    <!-- cruft need to avoid building and making dotnet sdk happy -->
    <PackProjectInputFile>$(MSBuildProjectFullPath)</PackProjectInputFile>
    <NoBuild>true</NoBuild>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <TargetFramework>netstandard1.0</TargetFramework>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>

  </PropertyGroup>
  <PropertyGroup>
    <!-- simple way to exclude things (optional but nice) -->
    <ExcludeFromPackage>
        Content/node_modules/**/*;
        Content/packages/**/*;
        Content/public/bundle.js*;
        Content/bin/**/*;
        Content/obj/**/*;
    </ExcludeFromPackage>
</PropertyGroup>
  <ItemGroup>
    <Content Include="Content/**/*" Exclude="$(ExcludeFromPackage)" >
        <PackagePath>Content\</PackagePath>
    </Content>
  </ItemGroup>
</Project>
```

ref https://github.com/dotnet/dotnet-template-samples/issues/14

**Comment by mlorbetske** [comment]
There's a template template https://github.com/tintoy/dotnet-template-templates pack, I think it'd make sense to have those experiences together. @tintoy would you mind if I send a PR to add a "template packaging project" project template to your templates?

@sayedihashimi agree?

**Comment by tintoy** [comment]
Sure! :)

**Comment by tintoy** [comment]
BTW, I'm open to the idea of changing the existing templates to support `dotnet new template --type <project/item>` if you think people would find that more intuitive.

**Comment by tintoy** [comment]
And thanks for the reminder - need to verify the templates for 2.x!

**Comment by mlorbetske** [comment]
@tintoy PR sent :) I think what you mentioned about maybe having the kind of template be a pivot on the template entry itself might be a good idea, could have a shorter shortName that way & default to the project template flow (we're seeing mostly project templates being created)

**Comment by tintoy** [comment]
Cheers! Will get both sorted first thing tomorrow :)

**Comment by mlorbetske** [comment]
Looks like this has been merged https://github.com/tintoy/dotnet-template-templates/releases/tag/v0.1-beta1, thanks @tintoy!
