### ISSUE TITLE
B2C template is broken

### ISSUE THREAD

**Issue by cesarbs** [dotnet/templating#957]
When creating a new B2C web app with the 2.0-preview2 templates, I see this error on the first run:

![image](https://user-images.githubusercontent.com/924164/27204687-5bdb4990-51e1-11e7-8f6b-dc03315aac5c.png)

Removing the offending `@using`s leads to further errors:

![image](https://user-images.githubusercontent.com/924164/27204638-11da0be2-51e1-11e7-8285-2967c13c336a.png)

Adding an `ApplicationUser` class doesn't help:

![image](https://user-images.githubusercontent.com/924164/27204627-0357df54-51e1-11e7-81ac-63d2a0c466f0.png)

Looks like something is fundamentally broken in the template.

**Comment by mlorbetske** [comment]
Fixed in #955 and #956
