### ISSUE TITLE
Opening generated .csproj freezes VS2017

### ISSUE THREAD

**Issue by kakins** [dotnet/templating#962]
I have VS2017 (latest update as of today).

I did the following

1. dotnet new --install Microsoft.AspNetCore.SpaTemplates::*
2. dotnet new angular
3. Opened the generated .csproj in VS2017.

VS2017 freezes indefinitely.

However, I did notice that the .csproj opens if I do "dotnet restore" and "npm install -d" after creating the angular project.  Perhaps Visual Studio is freezing when trying to resolve all the dependencies?  That seems odd though.  At this point I'm not sure if it's a VS issue or not.

**Comment by seancpeters** [comment]
Hi @kakins,
Could you run the command `dotnet --info` and paste the output here?
Also, could you post the exact version of VS you're running, from help > about?

That info will help us troubleshoot your issue. Thanks!

**Comment by kakins** [comment]
Sure thing...

# VS #
Microsoft Visual Studio Professional 2017 
Version 15.2 (26430.13) Release
VisualStudio.15.Release/15.2.0+26430.13

# dotnet #
Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

**Comment by mlorbetske** [comment]
This issue was moved to aspnet/JavaScriptServices#1139
