### ISSUE TITLE
informations required

### ISSUE THREAD

**Issue by lucamorelli** [dotnet/templating#999]
I'm looking for more informations about a few topics:

- [x]  behavior of the guid macro when the format is not set.
- [ ]  formValue, and some sample, because the actual page is not very helpful.
- [ ]  CustomOperations. I would like to better understand the meaning of

```
Customizations allowed include:

Variable formats
Flag definitions
Modification operations
```

**Comment by sayedihashimi** [comment]
For the guid part, I've updated the sample https://github.com/dotnet/dotnet-template-samples/tree/master/14-guid

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by bekir-ozturk** [comment]
Hi @lucamorelli,
 For forms related documentation, we have the following page: https://github.com/dotnet/templating/wiki/Runnable-Project-Templates---Value-Forms
 For custom operations, we have a dedicated issue to track the documenting effort here https://github.com/dotnet/templating/issues/2516.
 I'm closing this issue now. Please let us know if you need any further help.
